:PROPERTIES:
:ID:       786eb85d-c7f8-4d90-8e6b-3cb99e6b5e32
:END:
#+title: Android

- [[https://github.com/39aldo39/DecSyncCC][39aldo39/DecSyncCC: Android app to sync contacts, calendars and tasks without a server using DecSync]]
- [[https://github.com/adi1090x/termux-desktop][adi1090x/termux-desktop: Setup A Beautiful Desktop/GUI In Termux]]
- [[https://github.com/aind-containers/aind][aind-containers/aind: AinD: Android in Docker. Ain't an emulator.]]
- [[https://github.com/alashow/datmusic-android][alashow/datmusic-android: Music search, downloader & player app using Jetpack Compose]]
- [[https://github.com/alexal1/Insomniac][alexal1/Insomniac: Instagram bot for automated Instagram interaction using Android device via ADB]]
- [[https://github.com/amnesica/KryptEY][amnesica/KryptEY: Android keyboard for secure E2EE communication through the signal protocol in any messenger. Communicate securely and independent, regardless of the legal situation or whether messengers use E2EE]]
- [[https://github.com/appleboy/gorush][appleboy/gorush: A push notification server written in Go (Golang).]]
  - [[https://habr.com/ru/companies/otus/articles/667308/][Go в API для мобильного приложения. Создаем совместный список покупок с мгновенными уведомлениями / Хабр]]
  - [[https://scribe.bus-hit.me/itnext/kubernetes-running-a-push-server-with-gorush-behind-an-aws-loadbalancer-48563f9a0319][Kubernetes: running a push-server with Gorush behind an AWS LoadBalancer]]
- [[https://github.com/aramg/droidcam][aramg/droidcam: Official Linux Client code for DroidDcam]]
- [[https://github.com/aryamangodara/Arcade-Plaza][aryamangodara/Arcade-Plaza: A host of best internet casual games for mobile users.]]
- [[https://github.com/austinried/subtracks][austinried/subtracks: A music streaming app for Subsonic-compatible servers]]
- [[https://github.com/bernaferrari/ChangeDetection][bernaferrari/ChangeDetection: Automatically track websites changes on Android in background.]]
- [[https://github.com/bitrise-io/android][bitrise-io/android: Android Docker image]]
- [[https://github.com/Bnyro/InnerTune][Bnyro/InnerTune: A material design music player to stream music from YouTube Music]]
- [[https://github.com/Bnyro/TranslateYou][Bnyro/TranslateYou: Powerful Translator App built with Material Design 3 (You)]]
- [[https://github.com/Bnyro/WallYou][Bnyro/WallYou: Wallpaper app built with Material Design 3 (You)]]
- [[https://github.com/syncloudsoftech/mobserve][syncloudsoftech/mobserve: Send all incoming and/or outgoing calls or text messages against set rules to webhook.]]
  - [[https://github.com/bogkonstantin/android_income_sms_gateway_webhook][bogkonstantin/android_income_sms_gateway_webhook: Simple Android incoming SMS to URL forwarder]]
    - [[https://github.com/sa3dany/android-sms-hooks][sa3dany/android-sms-hooks: Webhooks for SMS. Sends a POST request to a custom endpoint each time you receive an SMS message]]
- [[https://github.com/bytedance/btrace][bytedance/btrace: 🔥🔥 btrace(AKA RheaTrace) is a high performance Android trace tool which is based on Systrace, it support to define custom events automatically during building apk and using bhook to provider more native events like IO.]]
- [[https://github.com/canyie/BypassKeyguard][canyie/BypassKeyguard: PoC of unlocking an Android device without lock screen password]]
- [[https://github.com/cnlohr/rawdrawandroid][cnlohr/rawdrawandroid: Build android apps without any java, entirely in C and Make]]
- [[https://github.com/diogok/termux-qemu-alpine-docker][diogok/termux-qemu-alpine-docker: Run Docker on Alpine, on Qemu, on Termux, on Android.]]
- [[https://f-droid.org/en/packages/net.christianbeier.droidvnc_ng/][droidVNC-NG | F-Droid - Free and Open Source Android App Repository]]
- [[https://github.com/emanuele-f/PCAPdroid][emanuele-f/PCAPdroid: No-root network monitor, firewall and PCAP dumper for Android]]
- [[https://github.com/enginebai/MovieHunt][enginebai/MovieHunt: Movie Android App written in Kotlin, MVVM, RxJava, Jetpack Compose (implementing), Android Architecture Components and Coroutine (Upcoming).]]
- [[https://github.com/evilpenguin/APKProxyHelper][evilpenguin/APKProxyHelper: Patches those pesky APKs for proxy use.]]
- [[https://github.com/florent37/DiagonalLayout][florent37/DiagonalLayout: With Diagonal Layout explore new styles and approaches on material design]]
- [[https://github.com/Genymobile/scrcpy][Genymobile/scrcpy: Display and control your Android device]]
- [[https://github.com/google/bundletool][google/bundletool: Bundletool is a command-line tool to manipulate Android App Bundles]]
- [[https://github.com/gotev/android-upload-service][gotev/android-upload-service: Easily upload files (Multipart/Binary/FTP out of the box) in the background with progress notification. Support for persistent upload requests, customizations and custom plugins.]]
- [[https://github.com/hackroid/MqttSensorDemo][hackroid/MqttSensorDemo: An Android application using MQTT protocol to send sensor data in real time]]
- [[https://github.com/harjot-oberai/MusicDNA][harjot-oberai/MusicDNA: A Music Player for android that renders beautiful DNA(Visualization) of the currently playing music.]]
- [[https://github.com/ImranR98/Obtainium][ImranR98/Obtainium: Get Android App Updates Directly From the Source.]]
- [[https://github.com/iqiyi/xCrash][iqiyi/xCrash: 🔥 xCrash provides the Android app with the ability to capture java crash, native crash and ANR. No root permission or any system permissions are required.]]
- [[https://github.com/JakeWharton/adb-event-mirror][JakeWharton/adb-event-mirror: Mirror the touch/key/button events of one device onto one or more other devices in real-time]]
- [[https://github.com/judemanutd/AutoStarter][judemanutd/AutoStarter: This library helps bring up the autostart permission manager of a phone to the user so they can add an app to autostart.]]
- [[https://community.kde.org/KDEConnect][KDEConnect - KDE Community Wiki]]
  - [[https://userbase.kde.org/KDE_Connect/Tutorials/Useful_commands][KDE Connect/Tutorials/Useful commands - KDE UserBase Wiki]]
- [[https://github.com/Kunzisoft/KeePassDX][Kunzisoft/KeePassDX: KeePass implementation for android with material design and deluxe features]]
- [[https://github.com/kylecorry31/Trail-Sense][kylecorry31/Trail-Sense: An Android app that uses your phone's sensors to assist with wilderness treks or survival situations.]]
- [[https://f-droid.org/en/packages/com.xinto.mauth/][Mauth | F-Droid - Free and Open Source Android App Repository]]
- [[https://github.com/michaelbel/movies][michaelbel/movies: Discover movies app]]
- [[https://github.com/MinimalAndroidDevelopment/madsw][MinimalAndroidDevelopment/madsw: Mad showcase. A minimal android application that uses neovim(Instead of android studio) and madpm(instead of gradle).]]
- [[https://github.com/ndelphit/apkurlgrep][ndelphit/apkurlgrep: Extract endpoints from APK files]]
- [[https://github.com/offa/android-foss][offa/android-foss: A list of Free and Open Source Software (FOSS) for Android – saving Freedom and Privacy.]]
- [[https://github.com/Paralloid/Paralloid][Paralloid/Paralloid: Generic multi-booting solution for modern Android devices]]
- [[https://github.com/parvardegr/sharing][parvardegr/sharing: Sharing is a command-line tool to share directories and files from the CLI to iOS and Android devices without the need of an extra client app]]
- [[https://postmarketos.org/][postmarketOS // real Linux distribution for phones]]
- [[https://github.com/pyricau/androidsrc][pyricau/androidsrc: Find Android sources]]
- [[https://github.com/recloudstream/cloudstream][recloudstream/cloudstream: Android app for streaming and downloading Movies, TV-Series and Anime.]]
- [[https://github.com/rephus/notification-webhook][rephus/notification-webhook: Notification webhook service for Android]]
- [[https://github.com/skydoves/android-developer-roadmap][skydoves/android-developer-roadmap: 🗺 Android Developer Roadmap 2022 suggests learning paths to understanding Android development.]]
- [[https://github.com/skydoves/Pokedex][skydoves/Pokedex: 🗡️ Android Pokedex using Hilt, Motion, Coroutines, Flow, Jetpack (Room, ViewModel, LiveData) based on MVVM architecture.]]
- [[https://cweb.gitlab.io/StoneAge.html][StoneAge Messenger - Cweb]]
- [[https://github.com/tadfisher/android-nixpkgs][tadfisher/android-nixpkgs: Nix-packaged Android SDK]]
- [[https://github.com/theel0ja/foss-android][theel0ja/foss-android: List of free and open-source alternatives to proprietary Android apps.]]
- [[https://github.com/thyrlian/AndroidSDK][thyrlian/AndroidSDK: 🐳 Full-fledged Android SDK Docker Image]]
- [[https://github.com/tiann/KernelSU][tiann/KernelSU: A Kernel based root solution for Android]]
- [[https://github.com/tombursch/kitchenowl][TomBursch/kitchenowl: KitchenOwl is a self-hosted grocery list and recipe manager. The backend is made with Flask and the frontend with Flutter. Easily add items to your shopping list before you go shopping. You can also create recipes and add items based on what you want to cook.]]
- [[http://tracker2.postman.i2p/index.php?view=TorrentDetail&id=63723][Torrent: Bittorrent and browsing in I2P on Android Tv Box with Termux App - Guide + Video]]
- [[https://waydro.id/][Waydroid]]
- [[https://github.com/whs/K2AUSBKeyboard][whs/K2AUSBKeyboard: Keepass2Android USB Keyboard plugin]]
- [[https://github.com/zverik/every_door][Zverik/every_door: A dedicated app for collecting hundreds of POI for OpenStreetMap]]
- [[https://4pda.ru/forum/index.php?showtopic=820777][Мониторинг сетей сотовой связи в России - 4PDA]]

* API
- [[https://github.com/afollestad/drag-select-recyclerview][afollestad/drag-select-recyclerview: 👇 Easy Google Photos style multi-selection for RecyclerViews, powered by Kotlin and AndroidX.]]
- [[https://github.com/VKCOM/vk-android-sdk][VKCOM/vk-android-sdk: Android library for working with VK API, authorization through VK app, using VK functions.]]

* Backup

#+BEGIN_SRC bash
  #!/bin/bash
  # https://github.com/dwisiswant0/xiaomi-backup/blob/master/backup.sh

  PACKAGES=`adb shell pm list packages -f | cut -d ":" -f2`

  for package in ${PACKAGES}; do
      apk=`echo ${package} | grep -Eo ".*\.apk"`
      pkg=`echo ${package} | rev | cut -d "=" -f1 | rev`
      [[ ${apk} =~ "/data"* ]] && adb pull "${apk}" "${PWD}/${pkg}.apk"
  done
#+END_SRC

* Examples
- [[https://github.com/skydoves/MovieCompose][skydoves/MovieCompose: 🎞 A demo movie app using Jetpack Compose and Hilt based on modern Android tech stacks.]]
- [[https://github.com/ProtsenkoAI/shaboom-app][ProtsenkoAI/shaboom-app: Android app of ShaBoom project]]
- [[https://github.com/mrsegev/MovieNight?auto_subscribed=false][mrsegev/MovieNight: MovieNight is a sample Android application that uses the clean architecture approach and is written in Kotlin.]]

* Froid
- [[https://github.com/NoMore201/playmaker][NoMore201/playmaker: Fdroid repository manager fetching apps from Play Store]]
- [[https://github.com/mvdan/fdroidcl][mvdan/fdroidcl: F-Droid desktop client]]
- [[https://github.com/Iamlooker/Droid-ify][Iamlooker/Droid-ify: F-Droid client with Material UI.]]

* Hardware
- [[https://old.reddit.com/r/selfhosted/comments/vvn1su/running_an_android_phone_247/][Running an Android Phone 24/7 : selfhosted]]
  - [[https://www.youtube.com/watch?v=YfvTjQ9MCwY&t=864s][Building a TRUE 4k home cinema projector (it’s awesome) - YouTube]]
* Learning
- [[https://compizomania.blogspot.com/2021/09/android-adb-ubuntulinux-mint.html][compizomania: Подключаем любое Android-устройство (планшет/телефон), как съёмный носитель с помощью ADB в Ubuntu/Linux Mint]]
- [[https://scribe.bus-hit.me/@roy2477/decrypting-android-app-ssl-traffic-c480e2143743][Decrypting Android App SSL Traffic]]
- [[https://habr.com/ru/articles/302002/][Push уведомления в Android с помощью Firebase Cloud Messaging для начинающих / Хабр]]

* Libraries
- [[https://github.com/ajalt/clikt][ajalt/clikt: Multiplatform command line interface parsing for Kotlin]]

* Linux
- [[https://github.com/AndronixApp/AndronixOrigin][Andronix uses PRoot to run a Linux distribution on your Android device]]

* Linux

- [[https://github.com/Flytreels/termux-archlinux][termux-archlinux]]

* Programs
- ADB⚡OTG (Run ADB commands without a computer (no ROOT needed)) - https://f-droid.org/packages/com.htetznaing.adbotg
- [[https://github.com/alextran1502/immich][alextran1502/immich: Self-hosted photo and video backup solution directly from your mobile phone.]]
- [[https://github.com/android/nowinandroid?auto_subscribed=false&utm_campaign=explore-email&utm_medium=email&utm_source=newsletter&utm_term=weekly][android/nowinandroid: A fully functional Android app built entirely with Kotlin and Jetpack Compose]]
- [[https://github.com/android-password-store/Android-Password-Store][android-password-store/Android-Password-Store: Android application compatible with ZX2C4's Pass command line application]]
- AndroTainer (Manage your docker containers via your smartphone) - https://f-droid.org/packages/com.dokeraj.androtainer
- [[https://github.com/anthonycr/Lightning-Browser][anthonycr/Lightning-Browser: A lightweight Android browser with modern navigation]]
- [[https://github.com/appium/appium][appium/appium: Cross-platform automation framework for all kinds of your apps built on top of W3C WebDriver protocol]]
- AVNC (Fast & Secure VNC client for Android) - https://f-droid.org/packages/com.gaurav.avnc
- [[https://github.com/barry-ran/QtScrcpy][barry-ran/QtScrcpy: Android real-time display control software]]
- [[https://github.com/blokadaorg/blokada][blokadaorg/blokada: Free ad blocker for Android with the best open source community.]]
- BootBoi (Turn on/off your remote machine without leaving your couch!) - https://f-droid.org/packages/com.elektropepi.bootboi
- [[https://github.com/chenxiaolong/BCR][chenxiaolong/BCR: A Basic Call Recorder for rooted Android devices]]
- [[https://github.com/chrisbanes/tivi][chrisbanes/tivi: Tivi is a work-in-progress TV show tracking Android app, which connects to Trakt.tv. It is still in its early stages of development and currently only contains two pieces of UI. It is under heavy development.]]
- [[https://github.com/ChuckerTeam/chucker][ChuckerTeam/chucker: 🔎 An HTTP inspector for Android & OkHTTP (like Charles but on device) - More Chucker than Chuck]]
- [[https://github.com/davidtakac/prognoza][davidtakac/prognoza: Libre weather app with widgets and offline support]]
- [[https://github.com/dessalines/thumb-key][dessalines/thumb-key: A privacy-conscious Android keyboard made for your thumbs]]
- [[https://github.com/dittos/animeta][dittos/animeta: Manage your anime watch history.]]
- [[https://github.com/DroidNinja/Android-FilePicker][DroidNinja/Android-FilePicker: Photopicker and document picker for android]]
- [[https://github.com/DroidPHP/DroidPHP][DroidPHP/DroidPHP: DroidPHP is a small, fast and lightweight open source Web Server for Android]]
- droidVNC-NG (VNC server app that does not require root privileges.) - https://f-droid.org/packages/net.christianbeier.droidvnc_ng
- [[https://github.com/duckduckgo/Android][duckduckgo/Android: DuckDuckGo Android App]]
- [[https://framagit.org/dystopia-project/simple-email][Dystopia Project Free Software, minimalistic and privacy friendly email app for Android. / Simple Email · GitLab]]
- [[https://github.com/EtchDroid/EtchDroid][EtchDroid/EtchDroid: NO LONGER MAINTAINED - An application to write OS images to USB drives, on Android, no root required.]]
- [[https://github.com/euphony-io/waple][euphony-io/waple: Waple helps you share your Wi-Fi password quickly.]]
- [[https://f-droid.org/packages/com.enjoyingfoss.feeel/][Feeel - home workouts | F-Droid - Free and Open Source Android App Repository]]
- [[https://github.com/florisboard/florisboard][florisboard/florisboard: An open-source keyboard for Android which respects your privacy. Currently in early-beta.]]
- [[https://github.com/FredJul/Flym][FredJul/Flym: Flym News Reader is a light Android feed reader (RSS/Atom)]]
- [[https://github.com/google/addlicense][google/addlicense: A program which ensures source code files have copyright license headers by scanning directory patterns recursively]]
- [[https://github.com/google/evergreen-checker][google/evergreen-checker]]
- [[https://github.com/gotev/android-upload-service][gotev/android-upload-service: Easily upload files (Multipart/Binary/FTP out of the box) in the background with progress indication notification]]
- Greentooth (Automatic Bluetooth disabler) - https://f-droid.org/packages/com.smilla.greentooth
- [[https://github.com/grote/Transportr][grote/Transportr: Free Public Transport Assistant without Ads or Tracking]]
- [[https://github.com/Hash-Studios/Prism][Hash-Studios/Prism: Prism is a beautiful open-source wallpapers app for Android. It is built with Dart on top of Google's Flutter Framework.]]
- HTTP Request Shortcuts (Create home screen shortcuts that trigger arbitrary HTTP requests) - [[https://f-droid.org/packages/ch.rmy.android.http_shortcuts][HTTP Request Shortcuts]]
- [[https://github.com/iielse/imageviewer][iielse/imageviewer: A simple and customizable Android full-screen image viewer 一个简单且可自定义的Android全屏图像浏览器]]
- [[https://github.com/ingbyr/VDM][ingbyr/VDM: GUI for command-line video downloader (youtube-dl annie)]]
- [[https://github.com/inorichi/tachiyomi][inorichi/tachiyomi: Free and open source manga reader for Android]]
- [[https://github.com/iTXTech/Daedalus][iTXTech/Daedalus: No root required Android DNS modifier and Hosts/DNSMasq resolver.]]
- [[https://github.com/kevinhinterlong/archwiki-viewer][kevinhinterlong/archwiki-viewer: A simple Android specific viewer for the Arch Linux Wiki.]]
- [[https://github.com/Kunzisoft/KeePassDX][Kunzisoft/KeePassDX: KeePass implementation for android with material design and deluxe features]]
- [[https://github.com/KyleKun/one_second_diary][KyleKun/one_second_diary: Minimalist video diary app.]]
- [[https://github.com/LibreShift/red-moon][LibreShift/red-moon: Android screen filter app for night time phone use.]]
- [[https://github.com/libre-tube/LibreTube][libre-tube/LibreTube: An alternative frontend for YouTube, for Android. [WIP]]]
- [[https://github.com/ligi/PassAndroid][ligi/PassAndroid: Android App to view passes]]
- [[https://github.com/lopspower/CircularImageView][lopspower/CircularImageView: Create circular ImageView in Android in the simplest way possible]]
- [[https://github.com/Martin-Nyaga/termplot][Martin-Nyaga/termplot: A simple terminal plotting tool for visualising streaming data.]]
- [[https://github.com/moezbhatti/qksms][moezbhatti/qksms: The most beautiful SMS messenger for Android]]
- moVirt (mobile client for oVirt monitoring) - https://f-droid.org/packages/org.ovirt.mobile.movirt
- [[https://github.com/mozilla-mobile/fenix][mozilla-mobile/fenix: Firefox for Android]]
- mpv remote (Android application to control mpv running on another computer.) - https://f-droid.org/packages/miccah.mpvremote
- [[https://github.com/mukul500/AnimeXStream][mukul500/AnimeXStream: An Android app to watch anime on your phone without ads.]]
- [[https://github.com/neffex97/Tiwee][neffex97/Tiwee: IPTV player]]
- [[https://github.com/NeoApplications/Neo-Backup][NeoApplications/Neo-Backup: backup manager for android]]
- [[https://github.com/NeoApplications/Neo-Store][NeoApplications/Neo-Store: F-Droid client with Material UI.]]
- [[https://ntfy.sh/][ntfy.sh | simple HTTP-based pub-sub]]
  - [[https://github.com/binwiederhier/ntfy-android][binwiederhier/ntfy-android: Android app for ntfy.sh]]
- [[https://github.com/openhab/openhab-android][openhab/openhab-android: openHAB client for Android]]
- [[https://github.com/organicmaps/organicmaps][organicmaps/organicmaps: 🍃 Organic Maps is a free Android & iOS offline maps app for travelers, tourists, hikers, and cyclists. It uses crowd-sourced OpenStreetMap data and is developed with love by MapsWithMe (MapsMe) founders and our community. No ads, no tracking, no data collection, no crapware. Your donations and positive reviews motivate and inspire our small team!]]
- [[https://github.com/PaulWoitaschek/Voice][PaulWoitaschek/Voice: Minimalistic audiobook player]]
- [[https://github.com/phikal/ReGeX][phikal/ReGeX: A Regular Expression game for Android]]
- Presence Publisher (Regularly publish to an MQTT topic) - https://f-droid.org/packages/org.ostrya.presencepublisher
- Public IP (App and Widget allowing user to find its current public IP address) - https://f-droid.org/packages/net.guildem.publicip
- qBController (handling qBittorrent servers) - https://f-droid.org/packages/com.lgallardo.qbittorrentclient
- RestSMS (REST service to send SMS via your Android device) - https://f-droid.org/packages/net.xcreen.restsms
- [[https://github.com/RetroMusicPlayer/RetroMusicPlayer][RetroMusicPlayer/RetroMusicPlayer: Best Material You Design music player for Android]]
- [[https://github.com/rkkr/simple-keyboard?auto_subscribed=false][rkkr/simple-keyboard]]
- [[https://github.com/rom1v/sndcpy][rom1v/sndcpy: Android audio forwarding (scrcpy, but for audio)]]
- [[https://github.com/saket/press][saket/press: A cross-platform markdown editor written in Kotlin Multiplatform (work in progress)]]
- ServeIt (A simple http-server on android using flutter.) - https://f-droid.org/packages/com.example.flutter_http_server
- [[https://github.com/shadowsocks/shadowsocks-android][shadowsocks/shadowsocks-android: A shadowsocks client for Android]]
- [[https://github.com/SimpleMobileTools/Simple-Calendar][SimpleMobileTools/Simple-Calendar: A simple calendar with events, customizable widgets and no ads.]]
- [[https://github.com/sourcerer-io/sourcerer-app][sourcerer-io/sourcerer-app: 🦄 Sourcerer app makes a visual profile from your GitHub and git repositories.]]
- Spider (This application enables you to connect to your SFTP server using a password or) - https://f-droid.org/packages/org.kknickkk.spider
- [[https://github.com/stfalcon-studio/StfalconImageViewer][stfalcon-studio/StfalconImageViewer: A simple and customizable Android full-screen image viewer with shared image transition support, "pinch to zoom" and "swipe to dismiss" gestures]]
- [[https://github.com/theAkito/webmon][theAkito/webmon: Android app for monitoring web services. Notifies you of any HTTP or Onion destination not being available.]]
- [[https://framagit.org/tom79/nitterizeme][Thomas A small application that allows to handle Twitter and Youtube to redirect them to their Nitter or Invidious URLs and open them with the appropriate app. / UntrackMe · GitLab]]
- TSVNC (Small and simple VNC client.) - https://f-droid.org/packages/de.toshsoft.tsvnc
- [[https://github.com/ukanth/afwall][ukanth/afwall: AFWall+ (Android Firewall +) - iptables based firewall for Android]]
- Vernet (Host and Port scanner. Ping IP or domain.) - https://f-droid.org/packages/org.fsociety.vernet
- Webmon (Monitor web services and get notified, if a service becomes unavailable.) - https://f-droid.org/packages/ooo.akito.webmon
- [[https://github.com/westnordost/StreetComplete][westnordost/StreetComplete: Easy to use OpenStreetMap editor for Android]]
- Wi-Fi Reminders (Unknown application) - https://f-droid.org/packages/ru.glesik.wifireminders
- [[https://github.com/wlanjie/trinity][wlanjie/trinity: android video record editor muxer sdk]]
- [[https://github.com/yuriykulikov/AlarmClock][yuriykulikov/AlarmClock: Most popular open source Android Alarm Clock App]]
- [[https://github.com/zagum/Android-SwitchIcon][zagum/Android-SwitchIcon: Google launcher-style implementation of switch (enable/disable) icon]]
- [[https://github.com/Zfinix/worddle][Zfinix/worddle: 😘 A wordle game clone built in flutter.]]
- [[https://github.com/zt64/Hyperion][zt64/Hyperion: An alternative YouTube front-end]]
** Games
- [[https://github.com/AbhiramVAnand/Lucky][AbhiramVAnand/Lucky: Lucky is a simple android game]]
** Misc
- [[https://github.com/mvt-project/mvt][mvt-project/mvt: MVT is a forensic tool to look for signs of infection in smartphone devices]]

** Proprietary
- [[https://audiorelay.net/][Stream your PC audio to your phone - AudioRelay]]
- [[https://4pda.to/forum/index.php?showtopic=1031584][NokoPrint — Печать по Wi-Fi, Bluetooth и USB - 4PDA]]
- [[https://pikabu.ru/story/upakuy_pallet_bratukha_upakuy_8231944][Упакуй паллет, братуха, упакуй... | Пикабу]]
- [[https://pikabu.ru/story/zhurnal_schyotchikov_v20_5086251][Журнал счётчиков v.2.0 | Пикабу]]- [[https://pikabu.ru/story/kalkulyator_dlya_podguznikov_6534402][Калькулятор для подгузников | Пикабу]]

** Emulators
- [[https://github.com/Swordfish90/Lemuroid][Swordfish90/Lemuroid: All in one emulator on Android!]]

* Security

- [[https://github.com/dwisiswant0/apkleaks][dwisiswant0/apkleaks: Scanning APK file for URIs, endpoints & secrets.]]

* Sites
- [[https://trashbox.ru/][Трешбокс.ру]]

* SSH
** SimpleSSHD
Open =Settings= and configure =SSH Path= to =/storage/emulated/0/.ssh=.

Make sure =/storage/emulated/0/.ssh/authorized_keys= file exists and has
public keys.

* Tools
- [[https://github.com/0x192/universal-android-debloater][0x192/universal-android-debloater: Cross-platform GUI written in Rust using ADB to debloat non-rooted android devices. Improve your privacy, the security and battery life of your device.]]
- [[https://github.com/alibaba/p3c][alibaba/p3c: Alibaba Java Coding Guidelines pmd implements and IDE plugin]]
- [[https://github.com/bytedance/CodeLocator][bytedance/CodeLocator]]
- [[https://github.com/corbindavenport/nexus-tools][corbindavenport/nexus-tools: Installer for ADB, Fastboot, and other Android tools on Linux, macOS, Chrome OS, and Windows]]
- [[https://github.com/darkhz/adbtuifm][darkhz/adbtuifm: A TUI File Manager for ADB]]
- [[https://github.com/DeviceFarmer/stf][DeviceFarmer/stf: Control and manage Android devices from your browser.]]
- [[https://github.com/GoogleChromeLabs/bubblewrap][GoogleChromeLabs/bubblewrap: Bubblewrap is a Command Line Interface (CLI) that helps developers to create a Project for an Android application that launches an existing Progressive Web App (PWAs) using a Trusted Web Activity.]]
- [[https://github.com/iBotPeaches/Apktool][iBotPeaches/Apktool: A tool for reverse engineering Android apk files]]
- [[https://github.com/JakeWharton/SdkSearch][JakeWharton/SdkSearch: An Android app and Chrome extension for searching the Android SDK documentation.]]
- [[https://github.com/michaelbel/android-app-template][michaelbel/android-app-template: A simple GitHub template that lets you create a modern Android app]]
- [[https://github.com/mobile-dev-inc/maestro][mobile-dev-inc/maestro: Painless Mobile UI Automation]]
- [[https://github.com/mrrfv/linux-android-backup][mrrfv/linux-android-backup: Back up your device without vendor lock-ins, using insecure software or root. Supports encryption and compression out of the box. Works cross-platform.]]
- [[https://github.com/nikp123/scrcpy-desktop][nikp123/scrcpy-desktop: Run an Android desktop environment off of a device using ONLY scrcpy]]
- [[https://github.com/pbreault/adb-idea][pbreault/adb-idea: A plugin for Android Studio and Intellij IDEA that speeds up your day to day android development.]]
- [[https://github.com/react-native-community/docker-android][react-native-community/docker-android: Android Docker Image for React Native and common android development.]]
- [[https://github.com/rom1v/autoadb][rom1v/autoadb: Execute a command whenever a device is adb-connected]]
- [[https://github.com/secure-software-engineering/FlowDroid][secure-software-engineering/FlowDroid: FlowDroid Static Data Flow Tracker]]
- [[https://github.com/sickcodes/adb-download-all][sickcodes/adb-download-all: ADB Download All Files - A dirty shell script to adb pull all readable files using adb pull & base64]]
- [[https://github.com/sickcodes/dock-droid][sickcodes/dock-droid: Docker Android - Run QEMU Android in a Docker! X11 Forwarding! CI/CD for Android!]]
- [[https://github.com/spotify/ruler][spotify/ruler: Gradle plugin which helps you analyze the size of your Android apps.]]
- [[https://github.com/tanprathan/MobileApp-Pentest-Cheatsheet][tanprathan/MobileApp-Pentest-Cheatsheet: The Mobile App Pentest cheat sheet was created to provide concise collection of high value information on specific mobile application penetration testing topics.]]
- [[https://github.com/tiann/eadb][tiann/eadb: eBPF Android Debug Bridge]]
- [[https://github.com/Tomotoes/scrcpy-gui][Tomotoes/scrcpy-gui: A simple & beautiful GUI application for scrcpy. QQ群:734330215]]
- [[https://github.com/vfsfitvnm/ViMusic][vfsfitvnm/ViMusic: A Jetpack Compose Android application for streaming music from YouTube Music.]]
- [[https://tech-geek.ru/notifications-from-android-on-linux/][Как получать уведомления с Android на Linux Android2Linux]]
  - [[https://github.com/patri9ck/a2ln-server][patri9ck/a2ln-server: A way to display Android phone notifications on Linux (Server)]]

* Xiaomi
- [[https://github.com/Szaki/XiaomiADBFastbootTools][Szaki/XiaomiADBFastbootTools: A simple tool for managing Xiaomi devices on desktop using ADB and Fastboot]]a

* Scripting

** Prerequisite

Firstly you need to enable wireless ADB on your Android device.

https://github.com/Genymobile/scrcpy/blob/87da1372380ebddb60e4d89cff9a251c866e21c5/README.md
#+begin_src markdown
  Alternatively, it is possible to enable the TCP/IP connection manually using adb:

      Plug the device into a USB port on your computer.

      Connect the device to the same Wi-Fi network as your computer.

      Get your device IP address, in Settings → About phone → Status, or by executing this command:

      adb shell ip route | awk '{print $9}'

      Enable adb over TCP/IP on your device: adb tcpip 5555.

      Unplug your device.

      Connect to your device: adb connect DEVICE_IP:5555 (replace DEVICE_IP with the device IP address you found).

      Run scrcpy as usual.
#+end_src

** Cheat sheet

- [[https://xakep.ru/2014/10/24/android-shell-script/][Shell-скриптинг в среде Android — Хакер]]

- connect adb over wifi
  : adb connect 192.168.0.177:5555

- call
  : adb shell am start -a android.intent.action.CALL tel:xxxxxxxxxxx

#+begin_src markdown
  Shell-скриптинг в среде Android
  Евгений Зобнин	
  24.10.2014
  8 комментариев
  393099
  Содержание статьи

      Особенности Android-окружения
      Первый пример
      Автозапуск
      Запуск скриптов до и после установки прошивки
      INFO
      Что еще?
      Вместо выводов

  Android основан на ядре Linux, включает в себя набор стандартных UNIX-команд и простой шелл sh. Все это значит, что мы можем не только использовать командную строку для выполнения низкоуровневых операций, но и писать шелл-скрипты, которые будут выполнять функции, недоступные из графического интерфейса. В этой статье мы поговорим о том, что с их помощью можно сделать и зачем все это нужно.

  Для прошлого номера журнала я написал статью о Tasker — системе, которая позволяет автоматизировать работу Android и заменить сотни сторонних приложений. К сожалению, Tasker ограничен высокоуровневыми функциями Android и не позволяет выполнять такие низкоуровневые операции, как монтирование файловых систем, изменение параметров ядра, системных переменных или запуск демонов. Зато все это можно сделать с помощью скриптов.

  Сразу оговорюсь, что в этой статье речь пойдет о шелл-скриптах в традиционном для Linux понимании, без использования инструментов вроде SL4A, QPython или Roboto. Главное назначение таких скриптов — изменение поведения системы, параметров ядра, работа с демонами (ADB, например) и тому подобное. Скрипты могут стартовать на этапе загрузки ОС, установки новой прошивки, после тапа по кнопке или же по традиции — из терминала.

  В статье я расскажу, как писать такие скрипты, как заставить их стартовать автоматически, привязывать к определенному системному событию. В качестве бонуса также объясню, как заставить консоль восстановления (recovery) выполнить необходимые тебе действия перед установкой или сразу после установки новой прошивки. Начинаем.

  Особенности Android-окружения

  В самой своей основе, там, где нет Java и Dalvik, Android представляет собой минималистичный Linux-дистрибутив со всеми свойственными ему атрибутами: ядром, системой инициализации, набором библиотек, демонов, консольных команд и, конечно же, шеллом. Последний — это не что иное, как mksh из MirBSD, переименованный в sh; простой командный интерпретатор с поддержкой языковых конструкций классического Bourne shell из UNIX и автодополнением по нажатию Tab.

  В качестве комплекта базовых UNIX-команд здесь используется toolbox, своего рода урезанная альтернатива BusyBox, которая позволяет вызывать несколько разных команд из одного бинарника (с помощью симлинков). Toolbox включает в себя очень ограниченный набор команд, в котором нет не только grep или sort, но даже cp. Поэтому для полноценной работы со скриптами настоятельно рекомендуется установка BusyBox, благо в маркете полно бесплатных инсталляторов.

  Сам шелл располагается не совсем по адресу, поэтому «шибанг» в скриптах будет выглядеть несколько по-иному, а именно #!/system/bin/sh. Зато о расположении бинарников можно не думать вообще, так как в переменной $PATH всегда прописаны правильные значения. Каталогов для поиска команд тут всегда три: /system/bin/, /system/sbin/ и /system/xbin/ для внешних бинарников. Туда обычно устанавливается BusyBox.

  Основное назначение скриптинга в Android — работа с ядром и системными утилитами. Ядро тут стандартное и экспортирует все те же интерфейсы /proc и /sys, через которые можно рулить железом и состоянием системы. Плюс есть набор специфичных для Android утилит, которые будут очень полезны при разработке скриптов:

      pm — менеджер пакетов, позволяет устанавливать, удалять и перемещать софт;
      am — менеджер активностей (Activity), может быть использован для запуска приложений;
      dumpsys — дамп в консоль массы различной информации о состоянии системы;
      screencap — утилита для снятия скриншота;
      screenrecord — утилита для записи скринкастов;
      getprop/setprop — команды для чтения и изменения системных переменных;
      start/stop — запуск и остановка системных служб;
      input — позволяет отправлять в текущее окно кей-коды (эмуляция клавиатуры);
      service — утилита для управления Java-сервисами, имеет очень много возможностей;
      svc — позволяет управлять Wi-Fi, USB-подключением и питанием.

  Часть вывода команды dumpsys
  Часть вывода команды dumpsys
  Другие статьи в выпуске:
  Хакер #185. Докажи баг!

      Содержание выпуска
      Подписка на «Хакер»-60%


  Первый пример

  Теперь давайте попробуем написать первый скрипт. Делать это лучше на компе, а еще лучше в Linux или редакторе, который умеет создавать текстовые файлы без символа возврата каретки (который при открытии в Android будет выглядеть как ^M в конце каждой строки). Наш первый скрипт будет состоять всего из двух строк, которые делают бэкап всех установленных приложений на карту памяти. Его код (требует BusyBox):

  #!/system/bin/sh

  mkdir /sdcard/backup
  cp /data/app/*.apk /sdcard/backup

  Сохраняем (пусть он называется apk_backup.sh) и перекидываем на смартфон с помощью ADB:

  $ adb push apk_backup.sh /sdcard/

  Теперь его нужно запустить. Проще всего сделать это с помощью все того же ADB:

  $ adb shell sh /sdcard/apk_backup.sh

  Примерно таким же образом скрипт можно запустить из консоли на самом смартфоне/планшете:

  $ sh /sdcard/apk_backup.sh

  Само собой, такой способ не очень удобен. Поэтому нам нужен какой-то быстрый способ запуска скрипта. Наиболее удобное из найденных мной решений — это приложение QuickTerminal. Устанавливаем, запускаем, переходим на вкладку Quick Command, нажимаем кнопку «+», вбиваем имя (произвольное) и команду (sh /sdcard/apk_backup.sh), в поле Output Type выбираем либо Dialog Output, либо Nothing. В первом случае во время выполнения скрипта на экране появится окно с результатом, во втором все пройдет в фоне. Кому что удобнее. Далее сохраняем и получаем кнопку, с помощью которой скрипт можно будет запустить быстро и легко.

  Теперь напишем скрипт, который восстановит наш бэкап:

  #!/system/bin/sh

  for i in /sdcard/backup/*; do
  pm install -t -r $i
  done

  В нем мы задействовали команду pm с опцией install и флагами -t и -r, которые заставляют систему устанавливать приложения, даже если они подписаны тестовым ключом или уже установлены. Также можно использовать флаг -s, который принуждает приложения к установке на карту памяти (если такая возможность есть), или -f — установка во внутреннюю память устройства.
  Почти все команды Android имеют подробную справку
  Почти все команды Android имеют подробную справку

  Имея рут, можно даже сделать бэкап настроек всех приложений с помощью копирования и архивации каталога /data/data/, однако восстановить его будет очень проблематично, так как в Android каждое приложение исполняется от имени созданного специально для него Linux-юзера и хранит настройки внутри каталога, принадлежащего этому пользователю. Проблема здесь в том, что идентификатор Linux-юзера для каждого приложения генерируется динамически, поэтому после восстановления бэкапа в заново установленной системе идентификаторы не будут совпадать и приложения не смогут прочитать свои настройки. Придется вручную выяснять ID юзера для каждого приложения и менять права доступа на каталоги с данными.

  С другой стороны, мы можем использовать встроенный в Android Backup Manager, позволяющий сторонним приложениям использовать возможности системы для бэкапа и восстановления приложений и их данных. Управлять им можно из консоли (а значит, и с помощью скриптов), но сам по себе он никакого бэкапа не производит, а возлагает эту работу на сторонние приложения. Helium — одно из таких приложений. Если установить и настроить его, операцию бэкапа и восстановления можно будет заскриптовать. Например, следующий простой скрипт сделает резервную копию всех сторонних приложений:

  #!/system/bin/sh
  # Получаем список всех сторонних приложений
  for i in `pm list packages -e`; do
  # Добавляем каждое из них в очередь
  bmgr backup ${i:8}
  done
  # Запускаем операцию бэкапа
  bmgr run

  Конструкция ${i:8} здесь нужна, чтобы обрезать слово «packages:», которое pm добавляет в начало имени каждого пакета. Чтобы восстановить бэкап, можно использовать либо тот же Helium, либо команду bmgr:

  $ bmgr list sets # Получаем список бэкапов
  $ bmgr restore <тег> # Восстанавливаем нужный бэкап


  Автозапуск

  «Это все круто, но скрипты должны запускаться сами», — скажешь ты и будешь абсолютно прав. Без автозапуска от скриптов толку мало, но это легко исправить, если воспользоваться все тем же Tasker. Он умеет запускать любые шелл-команды в ответ на любое событие. Чтобы воспользоваться этой функциональностью, достаточно создать новый профиль, выбрать событие (для бэкапа лучшим событием будет время), затем добавляем действие, выбираем Script -> Run Shell, вбиваем команду (sh /sdcard/script.sh), выбираем, если необходимо, файл для записи результата и включаем профиль.

  Другой популярный способ автозапуска — это использование средств автоматического исполнения скриптов при загрузке в сторонних прошивках. Сегодня почти все сколько-нибудь известные кастомные прошивки умеют стартовать скрипты из каталога /system/etc/init.d/, а в стоке такую функциональность можно получить с помощью приложения Universal init.d из маркета. С последним, однако, надо быть осторожным, так как оно запускает скрипты не на раннем этапе загрузки, как это происходит в том же CyanogenMod, а уже после полной загрузки системы.

  Итак, что мы можем поместить в автозагрузку? Например, скрипт запуска демона ADB в сетевом режиме:

  #!/system/bin/sh
  setprop service.adb.tcp.port 5555
  stop adbd
  start adbd

  Для подключения к нему с ПК набираем такую команду:

  $ adb connect IP-смартфона

  Также мы можем применить некоторые оптимизации подсистемы виртуальной памяти:

  #!/system/bin/sh
  echo "4096" > /proc/sys/vm/min_free_kbytes
  echo "0" > /proc/sys/vm/oom_kill_allocating_task;
  echo "0" > /proc/sys/vm/panic_on_oom;
  echo "0" > /proc/sys/vm/laptop_mode;
  echo "0" > /proc/sys/vm/swappiness
  echo "50" > /proc/sys/vm/vfs_cache_pressure
  echo "90" > /proc/sys/vm/dirty_ratio
  echo "70" > /proc/sys/vm/dirty_background_ratio

  Ну или подогнать механизм lowmemorykiller (автоматическое убийство фоновых приложений при нехватке памяти) под наши нужды:

  #!/system/bin/sh
  echo "2048,3072,6144,15360,17920,20480" > /sys/module/lowmemorykiller/parameters/minfree

  Ну и конечно же, автоматический выбор планировщика процессов:

  #!/system/bin/sh
  echo "powersave" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

  Все это можно сделать с помощью специализированного софта, но зачем загружать систему дополнительным ПО, которое еще и будет висеть в фоне, когда можно обойтись несколькими простыми скриптами?
  Как запустить скрипт с помощью Tasker
  Как запустить скрипт с помощью Tasker

  Запуск скриптов до и после установки прошивки

  Почти каждый, кто устанавливает на свой гаджет стороннюю прошивку, также ставит поверх нее пакет с фирменными приложениями Google (gapps), который включает в себя маркет, YouTube, Gmail и другой софт. Каждый раз, когда происходит обновление прошивки, раздел /system, содержащий ее и gapps, полностью стирается, но приложения Google всегда остаются на месте. Это происходит потому, что, кроме всего прочего, gapps содержит в своем составе специальный скрипт, который размещается в каталоге /system/addon.d/ и запускается консолью восстановления до и после установки прошивки. Этот скрипт делает бэкап и восстановление приложений Google.

  Мы можем использовать эту возможность для выполнения наших собственных действий до и после установки прошивки. Вот так, например, выглядит мой скрипт восстановления, который ничего не бэкапит, но подчищает прошивку от мусора сразу после ее установки:

  #!/sbin/sh

  # Загружаем подсобные функции
  . /tmp/backuptool.functions

  # Рингтон и звук уведомления, которые должны остаться в системе
  RINGTONE=Machina
  NOTIFICATION=Argon

  case "$1" in
  backup)
      # Пусто :)
  ;;
  restore)
      # Рингтоны, уведомления и звук будильника
      cd /system/media/audio/ringtones/
      rm [!${RINGTONE}]*.ogg
      cd /system/media/audio/notifications/
      rm [!${NOTIFICATION}]*.ogg
      rm /system/media/audio/alarms/*

      # Языки синтеза и офлайн-распознавания речи
      rm /system/tts/lang_pico/*
      rm -rf /system/usr/srec/config/*

      # Приложения
      A=/system/app/
      rm $A/Email.apk
      rm $A/Exchange2.apk
      rm $A/LockClock.apk
      rm $A/PicoTts.apk
      rm $A/Term.apk
      rm $A/ThemeChooser.apk
      rm $APPS/WAPPushManager.apk
      rm $A/LiveWallpapers.apk
      rm $A/LiveWallpapersPicker.apk
      rm $A/VisualizationWallpapers.apk
      A=/system/priv-app/
      rm $A/CMUpdater.apk
      rm $A/ThemeManager.apk
  ;;
  pre-backup)
      # ...
  ;;
  post-backup)
      # ...
  ;;
  pre-restore)
      # ...
  ;;
  post-restore)
      # ...
  ;;
  esac

  Скрипт удаляет рингтоны, уведомления, движок синтеза речи и несколько приложений. Все эти действия запускаются в ответ на передачу скрипту опции командной строки restore (это делает консоль восстановления после установки прошивки), однако также предусмотрены и варианты обработки таких опций, как backup, pre-backup, post-backup, pre-restore и post-restore. Здесь это просто заглушки, но если бы мы захотели сделать бэкап некоторых файлов и приложений перед установкой прошивки, мы могли бы добавить их в блок backup, как это сделано в скрипте /system/addon.d/70-gapps.sh:

  . /tmp/backuptool.functions

  list_files() {
  cat <<EOF
  app/GoogleContactsSyncAdapter.apk
  etc/permissions/com.google.android.maps.xml
  etc/permissions/com.google.android.media.effects.xml
  ...
  EOF
  }
  case "$1" in
  backup)
      list_files | while read FILE DUMMY; do
      backup_file $S/$FILE
  done
  ;;
  ...

  Этот кусок скрипта прекрасно иллюстрирует, как сделать бэкап файлов. Ключевые элементы здесь: функция listfiles, которая при запуске выводит листинг файлов, и функция backupfile, которая является частью консоли восстановления (определена в файле /tmp/backuptool.functions). Она делает бэкап файлов в цикле.
  Содержимое /system/addon.d/ в CyanogenMod 11 на Motorola Defy
  Содержимое /system/addon.d/ в CyanogenMod 11 на Motorola Defy


  Скрипт бэкапа приложений Google
  Скрипт бэкапа приложений Google

  INFO

  По словам разработчика mksh, изначально пользовательские версии Android-смартфонов вообще не должны были иметь в своем составе шелл, но после выпуска смартфона для разработчиков HTC (T-Mobile) G1 он фактически стал стандартной частью системы.

  Версии Android 2.3 и ниже вместо mksh использовали минималистичный шелл ash, который входит в базовый комплект всех BSD-систем.

  Чтобы получить одни и те же скрипты на всех устройствах, можно использовать приложение DropSync или FolderSync (автоматическая синхронизация через Dropbox).

  Что еще?

  С помощью скриптов в Android можно сделать намного больше, чем бэкапы и настройка параметров системы. Вот, например, скрипт, который просыпается каждые десять минут и, если уровень заряда батареи стал меньше 30%, отключает Wi-Fi и Bluetooth:

  #!/system/bin/sh

  while true; do
  if [ `cat /sys/class/power_supply/battery/capacity` -lt 30 ]; then
      svc wifi disable
      service call bluetooth_manager 8
  fi
  sleep 600
  done

  Чтобы скрипт работал в фоне, достаточно вызвать его следующим образом:

  $ script.sh &

  А это скрипт, который позволяет быстро заполнять формы, требующие ввода имэйла и пароля (в приложениях и на веб-сайтах):

  #!/system/bin/sh

  adb shell input text "user@gmail.com"
  adb shell input keyevent 23
  adb shell input keyevent 20
  adb shell input text "ПАРОЛЬ"
  adb shell input keyevent 23
  adb shell input keyevent 20

  Запускать его можно разными способами. Либо перед запуском приложения, установив задержку:

  $ sleep 15; sh /sdcard/script.sh

  Либо повесить на какое-то событие Tasker, например на взмах смартфоном. Другой вариант — использовать буфер обмена. В Android, чтобы вставить нужный текст в буфер обмена, достаточно выполнить такую команду:

  $ service call clipboard 2 i32 1 i32 1 s16 "Этот текст появится в буфере обмена"

  Не ахти как удобно, зато работает. Как мы можем использовать такую функциональность? Например, сделать простенький скрипт clip.sh:

  #!/system/bin/sh
  service call clipboard 2 i32 1 i32 1 s16 "$1"

  Соль в том, что скрипт можно вызывать через удаленный ADB либо вообще поместить в /system/etc/init.d/, заменив $1 на нужный текст. Так нужные нам данные всегда будут под рукой, а бесполезный на смартфоне механизм копирования/вставки получит хоть какое-то назначение. Консольные команды можно использовать и для более высокоуровневых операций, например позвонить по указанному номеру:

  $ am start -a android.intent.action.CALL tel:123

  Или просто открыть окно номеронабирателя с нужным номером:

  $ am start -a android.intent.action.DIAL tel:123

  Примерно таким же образом можно отправить SMS:

  #!/system/bin/sh
  am start -a android.intent.action.SENDTO -d sms:$1 --es sms_body "$2" --ez exit_on_sent true
  sleep 1
  input keyevent 22
  sleep 1
  input keyevent 66

  Скрипт принимает два аргумента: номер телефона и содержимое SMS. После запуска он откроет окно SMS-приложения, вставит в него нужный текст, а затем нажмет кнопку Enter для отправки, после чего окно закроется.

  Другие полезные при скриптинге команды:

      Перезагрузка в режим recovery:

      $ su -c reboot recovery

      Мягкая перезагрузка (без перезапуска ядра):

      $ setprop ctl.stop zygote

      Открыть нужное приложение (в данном примере — «Настройки»):

      $ am start -n com.android.settings/com.android.settings.Settings

      Открыть веб-страницу:

      $ am start -a android.intent.action.VIEW http://www.google.com

      Сообщить приложениям о низком уровне заряда батареи (есть софт, который при этом снижает свою активность):

      $ am broadcast -a android.intent.action.BATTERY_LOW

      Изменить MAC-адрес:

      $ ip link set eth0 address 00:11:22:33:44:55

      Активировать вибратор:

      $ echo 100 > /sys/devices/virtual/timed_output/vibrator/enable

      Включить фонарик:

      $ echo 1 > /sys/devices/platform/flashlight/leds/flashlight/brightness

      Проиграть файл (может не сработать):

      $ stagefright -a -o file.mp3

      Отключить указанное приложение (можно организовать цикл для отключения bloatware по списку):

      $ pm disable com.google.android.calendar

      Получить список приложений, которые имеют уведомления в строке состояния:

      $ dumpsys statusbar | grep StatusBarNotification | awk '{ print $2 }' | cut -d '=' -f2

      Оптимизировать внутренние базы данных с настройками (можно добавить скрипт в автозагрузку, требуется BusyBox):

      #!/system/bin/sh
      for i in `find /data -iname "*.db"`; do
      sqlite3 $i 'VACUUM;'
      done

      Переключить Wi-Fi-тизеринг на основной интерфейс (нужно для обмана операторов, которые ограничивают скорость соединения при раздаче интернета по Wi-Fi):

      $ settings put global tether_dun_required 0
#+end_src

* TV

** [[https://gist.github.com/arjunv/2bbcca9a1a1c127749f8dcb6d36fb0bc][Keymap]]

- enter
  : adb shell input keyevent 66

- down
  : adb shell input keyevent 20

* Android Studio

[[https://github.com/cypherstack/stack_wallet][cypherstack/stack_wallet: Stack Wallet, a multicoin, cryptocurrency wallet]]

Android Studio is the recommended IDE for development, not just for launching
on Android devices and emulators but also for Linux desktop
development. Install it and configure it as follows:

    # setup android studio
    sudo apt install -y openjdk-11-jdk
    sudo snap install android-studio --classic

Use Tools > SDK Manager to install the SDK Tools > Android SDK (API 30), SDK
Tools > NDK, SDK Tools > Android SDK command line tools, and SDK Tools > CMake

Then install the Flutter plugin and restart the IDE. In Android Studio's
options for the Flutter language, enable auto format on save to match the
project's code style. If you have problems with the Dart SDK, make sure to run
`flutter` in a terminal to download it (use `source ~/.bashrc` to update your
environment variables if you're still using the same terminal from which you
ran `setup.sh`)

Make a Pixel 4 (API 30) x86\_64 emulator with 2GB of storage space for
emulation

* Chatgpt
** What could be used to automate proprietary apps on Android device?

To automate proprietary apps on an Android device, you can use a mobile automation testing tool that supports Android operating systems. Here are a few options:

    Appium: Appium is an open-source mobile automation testing tool that supports both Android and iOS platforms. It uses the WebDriver protocol to automate mobile apps and provides a wide range of automation capabilities such as gesture support, element locating strategies, and multi-platform testing.

    UI Automator: UI Automator is an Android testing framework that allows you to perform automated functional testing of user interfaces. It can be used to test the interaction between multiple apps on the device and supports running tests on multiple devices in parallel.

    Espresso: Espresso is a testing framework for Android that allows you to write automated UI tests for your app. It is designed to be lightweight, fast, and reliable, and it provides a simple and intuitive API for creating tests.

    Robotium: Robotium is an Android testing framework that allows you to write automated UI tests for your app. It provides a simple and intuitive API for creating tests, and it supports a wide range of Android versions and devices.

    Selendroid: Selendroid is a testing framework that allows you to automate native and hybrid Android apps. It supports multiple Android versions and devices and provides a wide range of automation capabilities such as element locating strategies, gesture support, and multi-platform testing.
** android show what activities launched (debug any application)

To see what activities are launched when an application is running on an Android device, you can use the Android Debug Bridge (ADB) tool that comes with the Android SDK. Here are the steps:

    Connect your Android device to your computer using a USB cable and make sure USB debugging is enabled on the device. You can enable USB debugging by going to the Developer options in the device's Settings app and toggling the "USB debugging" switch.

    Open a terminal or command prompt on your computer and navigate to the directory where the ADB tool is located.

    Type the following command to start ADB and connect to your device:

    adb devices

    This will list all the connected Android devices. Make sure your device is listed.

    Type the following command to start monitoring the device's activity:

    adb shell "logcat ActivityManager:I *:S"

    This will show all the activity manager logs with a priority level of "Info" and suppress all logs with other priority levels.

    Launch the application you want to debug on your device.

    Check the activity manager logs in the terminal or command prompt window. You should see the activities launched by the application listed in the logs.

Note: The logs may contain a lot of information, so it may be helpful to filter the logs by the application's package name. You can do this by adding the package name as a filter to the logcat command. For example:

adb shell "logcat ActivityManager:I *:S | grep com.example.app"

This will only show the logs related to the application with the package name "com.example.app". Replace "com.example.app" with the actual package name of the application you want to debug.

** Could I get network traffic from android device, e.g. to reverse API used by application?

Yes, you can capture network traffic from an Android device to reverse engineer the APIs used by an application. One way to do this is to use a network traffic analysis tool, such as Wireshark or Fiddler, and set up a proxy server on your computer to capture the traffic between the device and the application's server.

Here are the steps to capture network traffic from an Android device using Wireshark:

    Connect your Android device to your computer using a USB cable and make sure USB debugging is enabled on the device.

    Install and run Wireshark on your computer.

    Set up a proxy server on your computer by going to the Wireshark menu, selecting "Edit" -> "Preferences", and then selecting the "Proxies" tab. Under "HTTP Proxy", check the "Enabled" box and set the "Proxy server" to "127.0.0.1" and the "Proxy port" to "8888".

    Set up the Android device to use the proxy server by going to the device's Wi-Fi settings, long-pressing the network you're connected to, selecting "Modify network", and then selecting "Advanced options". Under "Proxy", select "Manual", and set the "Proxy hostname" to "127.0.0.1" and the "Proxy port" to "8888".

    Launch the application you want to reverse engineer on your Android device.

    In Wireshark, select the network interface that corresponds to the Wi-Fi network you're connected to and start capturing packets.

    Use the application on your device and perform the actions that you want to capture the network traffic for.

    Stop the packet capture in Wireshark and filter the captured packets by the IP address of the application's server. This will show you the network traffic between the application and its server.

    Analyze the captured packets to reverse engineer the APIs used by the application.

Note: Some applications may use encrypted traffic, such as HTTPS, which can make it more difficult to analyze the network traffic. In this case, you may need to use additional tools or techniques to decrypt the traffic.
