:PROPERTIES:
:ID:       b21b269d-3557-4c87-839a-6b155991e916
:END:
#+title: Anime

- [[https://github.com/adrianhajdin/anime_vault][adrianhajdin/anime_vault: Your favorite anime, all in one place.]]
- [[https://github.com/irevenko/what-anime-cli][irevenko/what-anime-cli: ❓🖼 Find the anime scene by image using your terminal]]
- [[https://github.com/laynH/Anime-Girls-Holding-Programming-Books][laynH/Anime-Girls-Holding-Programming-Books: Anime Girls Holding Programming Books]]
- [[https://github.com/irevenko/weebsay][irevenko/weebsay: 🎭👄 Like cowsay but it's random anime quote]]
- [[https://github.com/Mukosame/Anime2Sketch][Mukosame/Anime2Sketch: A sketch extractor for anime/illustration.]]
- [[https://github.com/pystardust/ani-cli][pystardust/ani-cli: A cli tool to browse and play anime]]
- [[https://github.com/IchBinLeoon/hanime][IchBinLeoon/hanime: 📥 Command-line tool to download videos from hanime.tv]]
- [[https://github.com/saikou-app/saikou][saikou-app/saikou: An anilist only client, which lets you stream & download Anime & Manga.]]
- [[https://github.com/animenotifier/notify.moe][animenotifier/notify.moe: Anime tracker, database and community.]]
  - [[https://notify.moe/][Anime Notifier]]
- [[https://github.com/AaronFeng753/Waifu2x-Extension-GUI][AaronFeng753/Waifu2x-Extension-GUI: Video, Image and GIF upscale/enlarge(Super-Resolution) and Video frame interpolation. Achieved with Waifu2x, Real-ESRGAN, Real-CUGAN, SRMD, RealSR, Anime4K, RIFE, CAIN, DAIN, and ACNet.]]
- [[https://github.com/makegirlsmoe/makegirlsmoe_web][makegirlsmoe/makegirlsmoe_web: Create Anime Characters with MakeGirlsMoe]]
  - [[https://make.girls.moe/#/][MakeGirlsMoe - Create Anime Characters with A.I.!]]
- [[https://github.com/anime-dl/anime-downloader][anime-dl/anime-downloader: A simple but powerful anime downloader and streamer.]]
- [[https://github.com/erengy/taiga][erengy/taiga: A lightweight anime tracker for Windows]]
- [[https://github.com/TianZerL/Anime4KCPP][TianZerL/Anime4KCPP: A high performance anime upscaler]]
- [[https://github.com/LagradOst/CloudStream-3][LagradOst/CloudStream-3: Android app for streaming and downloading Movies, TV-Series and Anime.]]
- [[https://github.com/LagradOst/QuickNovel][LagradOst/QuickNovel: Android app for downloading novels]]
- [[https://github.com/jmir1/aniyomi][jmir1/aniyomi: Unofficial fork of Tachiyomi for anime]]
- [[https://github.com/mchong6/JoJoGAN][mchong6/JoJoGAN: Official PyTorch repo for JoJoGAN: One Shot Face Stylization]]
- [[https://github.com/gotson/komga][gotson/komga: Media server for comics/mangas/BDs with API and OPDS support]]
- [[https://github.com/NyaaPantsu/nyaa][NyaaPantsu/nyaa: Nyaa.se replacement written in golang]]
- [[https://github.com/rocktimsaikia/anime-chan][rocktimsaikia/anime-chan: A free rest API for anime quotes]]
- [[https://github.com/Oshan96/monkey-dl][Oshan96/monkey-dl: Bulk download your favourite anime episodes from your favourite anime websites]]
- [[https://github.com/kiraka/annict-web][kiraka/annict-web: A platform for anime addicts built with Rails and Hotwire.]]
- [[https://github.com/Kylart/KawAnime][Kylart/KawAnime: Desktop app for anime fans]]
- [[https://github.com/Pizzacus/satania.moe][Pizzacus/satania.moe: Satania IS the BEST waifu, no really, she is, if you don't believe me, this website will convince you]]
- [[https://github.com/manami-project/anime-offline-database][manami-project/anime-offline-database: Updated every week: A JSON based offline anime database containing the most important meta data as well as cross references to various anime sites such as MAL, ANIDB, ANILIST, KITSU and more...]]
- [[https://github.com/justfoolingaround/animdl][justfoolingaround/animdl: A highly efficient, fast, powerful and light-weight anime downloader and streamer for your favorite anime.]]
- [[https://github.com/BeeeQueue/yuna][BeeeQueue/yuna: ツ An anime player that integrates with AniList, Simkl, Crunchyroll, and Hidive.]]
- [[https://github.com/shosetsuorg/shosetsu][shosetsuorg/shosetsu: An android application for reading light novels]]
- [[https://github.com/soruly/trace.moe-telegram-bot][soruly/trace.moe-telegram-bot: This Telegram Bot can tell the anime when you send an screenshot to it]]
- [[https://github.com/ThaUnknown/miru][ThaUnknown/miru: Bittorrent streaming software for cats]]
- [[https://github.com/IAmPara0x/Yuno][IAmPara0x/Yuno: Yuno is context based search engine for anime.]]
- [[https://github.com/bangumi/server][bangumi/server: The next-generation backend server for https://bgm.tv]]
- [[https://github.com/bchao1/Anime-Face-Dataset][bchao1/Anime-Face-Dataset: A collection of high-quality anime faces.]]
- [[https://github.com/AniDevTwitter/animeopenings][AniDevTwitter/animeopenings: Displays random anime openings]]
- [[https://github.com/Decimation/SmartImage][Decimation/SmartImage: Reverse image search (SauceNao, ImgOps, trace.moe) tool for Windows]]
- [[https://github.com/MakotoAme/twitter-saucenao][MakotoAme/twitter-saucenao: A Twitter bot that utilizes the SauceNao API to find the source of images or anime screencaps]]
- [[https://github.com/chirag-droid/animeflix][chirag-droid/animeflix: A anime discovery, streaming site made with NextJs and TailwindCSS. Uses AniList API and video data from GogoAnime. No ads and no vpn required]]
- [[https://github.com/erengy/anitomy][erengy/anitomy: Anime video filename parser]]
- [[https://github.com/LISTEN-moe/android-app][LISTEN-moe/android-app: Official LISTEN.moe Android app]]
- [[https://github.com/qhgz2013/anime-face-detector][qhgz2013/anime-face-detector: A Faster-RCNN based anime face detector implementation using tensorflow.]]
- [[https://github.com/platers/MAL-Map][platers/MAL-Map: Cluster and visualize relationships between anime on MyAnimeList]]
  - [[https://www.malmap.net/#][MAL Map]]
- [[https://github.com/freedomofkeima/transfer-learning-anime][freedomofkeima/transfer-learning-anime: Transfer Learning for Anime Characters Recognition]]
- [[https://github.com/spillerrec/Overmix][spillerrec/Overmix: Automatic anime screenshot stitching in high quality]]
- [[https://github.com/Kylart/MalScraper][Kylart/MalScraper: Scrape everything you can from MyAnimeList.net]]

* Tools
- [[https://github.com/hummingbird-me][Kitsu is a content discovery platform that helps anime and manga fans track, share and discover more of what they love.]]

* Downloaders
- [[https://github.com/Xonshiz/anime-dl][Xonshiz/anime-dl: Anime-dl is a command-line program to download anime from CrunchyRoll and Funimation.]]

* Clients
- [[https://github.com/Enime-Project/enime][Enime-Project/enime: [IN DEVELOPMENT] A desktop application to let people enjoy anime]]
- [[https://github.com/s32x/anirip][s32x/anirip: A Crunchyroll show/season ripper]]

** Android
- [[https://github.com/czy0729/Bangumi][czy0729/Bangumi: An unofficial https://bgm.tv app client for Android and iOS, built with React Native. 一个无广告、不盈利的 bgm.tv 第三方客户端。简单比喻就是专门做ACG的类豆瓣应用。专门为移动端重新设计，已适配 iOS / Android、mobile / pad、light / dark theme，并加入了很多网页端难以实现的增强型功能。]]
- [[https://github.com/SkyD666/Imomoe][SkyD666/Imomoe: 樱花动漫第三方安卓Android客户端，不含广告，免费开源，目的是学习Android开发。]]
- [[https://github.com/kl3jvi/animity][kl3jvi/animity: 🎦 Android app to watch anime on your phone without ads and best streaming available.]]
- [[https://github.com/Drutol/MALClient][Drutol/MALClient: Not so small client app for Myanimelist.net - Windows 10 UWP & Android]]
- [[https://github.com/Killerpac/Kayuri][Killerpac/Kayuri: An Anime Watching App With Better player And Faster Servers]]
- [[https://github.com/ShokoAnime/ShokoServer][ShokoAnime/ShokoServer: Repository for Shoko Server.]]
- [[https://github.com/Chesire/Nekome][Chesire/Nekome: Nekome is an Android application to manage tracked Anime and Manga lists.]]
- [[https://github.com/AniTrend/anitrend-app][AniTrend/anitrend-app: Track all your favorite Anime & Manga with AniTrend as it offers anime or manga lookup, tracking and reference powered by AniList]]

* List

Taken from [[https://github.com/MALSync/MALSync][MALSync/MALSync: Integrates MyAnimeList/AniList/Kitsu/Simkl into various sites, with auto episode tracking.]]

#+begin_src html
  <table>
    <thead>
      <tr>
        <th>Anime</th>
        <th>Manga</th>
        <th>Media Server</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><a href="https://9anime.to"><img src="https://favicon.malsync.moe/?domain=https://9anime.to"> 9anime</a></td>
        <td><a href="https://www.mangadex.org"><img src="https://favicon.malsync.moe/?domain=https://www.mangadex.org"> Mangadex</a></td>
        <td><a href="http://app.emby.media"><img src="https://favicon.malsync.moe/?domain=app.emby.media"></a> <a href="http://app.emby.media">Emby</a> <a href="https://github.com/MALSync/MALSync/wiki/Emby-Plex">[Wiki]</a></td>
      </tr><tr>
        <td><a href="https://www.crunchyroll.com"><img src="https://favicon.malsync.moe/?domain=https://www.crunchyroll.com"> Crunchyroll</a></td>
        <td><a href="https://proxer.me"><img src="https://favicon.malsync.moe/?domain=https://proxer.me"> Proxer</a></td>
        <td><a href="http://app.plex.tv"><img src="https://favicon.malsync.moe/?domain=http://app.plex.tv"></a> <a href="http://app.plex.tv">Plex</a> <a href="https://github.com/MALSync/MALSync/wiki/Emby-Plex">[Wiki]</a></td>
      </tr><tr>
        <td><a href="https://vrv.co"><img src="https://favicon.malsync.moe/?domain=https://vrv.co"> Vrv</a></td>
        <td><a href="https://manganato.com"><img src="https://favicon.malsync.moe/?domain=https://manganato.com"> MangaNato</a></td>
        <td><a href="https://jellyfin.org/"><img src="https://favicon.malsync.moe/?domain=https://jellyfin.org/"></a> <a href="https://jellyfin.org/">Jellyfin</a> <a href="https://github.com/MALSync/MALSync/wiki/Emby-Plex">[Wiki]</a></td>
      </tr><tr>
        <td><a href="https://gogoanime.tv"><img src="https://favicon.malsync.moe/?domain=https://gogoanime.tv"> Gogoanime</a></td>
        <td><a href="https://www.viz.com"><img src="https://favicon.malsync.moe/?domain=https://www.viz.com"> VIZ</a></td>
        <td><a href="https://komga.org/"><img src="https://favicon.malsync.moe/?domain=https://komga.org/"></a> <a href="https://komga.org/">Komga</a> <a href="https://github.com/MALSync/MALSync/wiki/Emby-Plex">[Wiki]</a></td>
      </tr><tr>
        <td><a href="https://twist.moe"><img src="https://favicon.malsync.moe/?domain=https://twist.moe"> Twistmoe</a></td>
        <td><a href="https://serimanga.com"><img src="https://favicon.malsync.moe/?domain=https://serimanga.com"> serimanga</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.turkanime.co"><img src="https://favicon.malsync.moe/?domain=https://www.turkanime.co"> TurkAnime</a></td>
        <td><a href="https://mangadenizi.com"><img src="https://favicon.malsync.moe/?domain=https://mangadenizi.com"> mangadenizi</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animepahe.com"><img src="https://favicon.malsync.moe/?domain=https://animepahe.com"> animepahe</a></td>
        <td><a href="https://mangalivre.net"><img src="https://favicon.malsync.moe/?domain=https://mangalivre.net"> mangalivre</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.netflix.com"><img src="https://favicon.malsync.moe/?domain=https://www.netflix.com"> Netflix</a></td>
        <td><a href="https://lectortmo.com"><img src="https://favicon.malsync.moe/?domain=https://lectortmo.com"> tmofans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animeflv.net"><img src="https://favicon.malsync.moe/?domain=https://animeflv.net"> Animeflv</a></td>
        <td><a href="https://unionleitor.top"><img src="https://favicon.malsync.moe/?domain=https://unionleitor.top"> unionmangas</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://jkanime.net"><img src="https://favicon.malsync.moe/?domain=https://jkanime.net"> Jkanime</a></td>
        <td><a href="https://mangaplus.shueisha.co.jp"><img src="https://favicon.malsync.moe/?domain=https://mangaplus.shueisha.co.jp"> MangaPlus</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://proxer.me"><img src="https://favicon.malsync.moe/?domain=https://proxer.me"> Proxer</a></td>
        <td><a href="https://www.japscan.ws"><img src="https://favicon.malsync.moe/?domain=https://www.japscan.ws"> JapScan</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.wakanim.tv"><img src="https://favicon.malsync.moe/?domain=https://www.wakanim.tv"> Wakanim</a></td>
        <td><a href="https://manga.fascans.com"><img src="https://favicon.malsync.moe/?domain=https://manga.fascans.com"> FallenAngels</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www1.aniflix.tv"><img src="https://favicon.malsync.moe/?domain=https://www1.aniflix.tv"> Aniflix</a></td>
        <td><a href="http://mangakatana.com"><img src="https://favicon.malsync.moe/?domain=http://mangakatana.com"> MangaKatana</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.kickassanime.ro"><img src="https://favicon.malsync.moe/?domain=https://www.kickassanime.ro"> KickAssAnime</a></td>
        <td><a href="https://manga4life.com"><img src="https://favicon.malsync.moe/?domain=https://manga4life.com"> manga4life</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animekisa.tv"><img src="https://favicon.malsync.moe/?domain=https://animekisa.tv"> AnimeKisa</a></td>
        <td><a href="https://bato.to"><img src="https://favicon.malsync.moe/?domain=https://bato.to"> bato</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animeindo.net"><img src="https://favicon.malsync.moe/?domain=https://animeindo.net"> AnimeIndo</a></td>
        <td><a href="https://mangapark.net"><img src="https://favicon.malsync.moe/?domain=https://mangapark.net"> MangaPark</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://shinden.pl"><img src="https://favicon.malsync.moe/?domain=https://shinden.pl"> Shinden</a></td>
        <td><a href="https://www.tsukimangas.com"><img src="https://favicon.malsync.moe/?domain=https://www.tsukimangas.com"> Tsuki Mangás</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://voiranime.com"><img src="https://favicon.malsync.moe/?domain=https://voiranime.com"> Voiranime</a></td>
        <td><a href="https://mangatx.com"><img src="https://favicon.malsync.moe/?domain=https://mangatx.com"> mangatx</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.neko-sama.fr"><img src="https://favicon.malsync.moe/?domain=https://www.neko-sama.fr"> NekoSama</a></td>
        <td><a href="https://scantrad.net"><img src="https://favicon.malsync.moe/?domain=https://scantrad.net"> Scantrad</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://anime-odcinki.pl"><img src="https://favicon.malsync.moe/?domain=https://anime-odcinki.pl"> AnimeOdcinki</a></td>
        <td><a href="https://furyosquad.com/"><img src="https://favicon.malsync.moe/?domain=https://furyosquad.com/"> Furyosquad</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.animezone.pl"><img src="https://favicon.malsync.moe/?domain=https://www.animezone.pl"> AnimeZone</a></td>
        <td><a href="http://www.mangahere.cc"><img src="https://favicon.malsync.moe/?domain=http://www.mangahere.cc"> MangaHere</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://moeclip.com"><img src="https://favicon.malsync.moe/?domain=https://moeclip.com"> moeclip</a></td>
        <td><a href="http://fanfox.net"><img src="https://favicon.malsync.moe/?domain=http://fanfox.net"> MangaFox</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://goyabu.com"><img src="https://favicon.malsync.moe/?domain=https://goyabu.com"> Goyabu</a></td>
        <td><a href="https://wuxiaworld.site"><img src="https://favicon.malsync.moe/?domain=https://wuxiaworld.site"> WuxiaWorld</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animes.vision"><img src="https://favicon.malsync.moe/?domain=https://animes.vision"> AnimesVision</a></td>
        <td><a href="https://edelgardescans.com"><img src="https://favicon.malsync.moe/?domain=https://edelgardescans.com"> EdelgardeScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.hulu.com"><img src="https://favicon.malsync.moe/?domain=https://www.hulu.com"> Hulu</a></td>
        <td><a href="https://hatigarmscanz.net"><img src="https://favicon.malsync.moe/?domain=https://hatigarmscanz.net"> HatigarmScanz</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.hidive.com"><img src="https://favicon.malsync.moe/?domain=https://www.hidive.com"> Hidive</a></td>
        <td><a href="https://leviatanscans.com"><img src="https://favicon.malsync.moe/?domain=https://leviatanscans.com"> LeviatanScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.primevideo.com"><img src="https://favicon.malsync.moe/?domain=https://www.primevideo.com"> Amazon Prime Video</a></td>
        <td><a href="https://methodscans.com"><img src="https://favicon.malsync.moe/?domain=https://methodscans.com"> MethodScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://dreamsub.cc"><img src="https://favicon.malsync.moe/?domain=https://dreamsub.cc"> DreamSub</a></td>
        <td><a href="https://the-nonames.com"><img src="https://favicon.malsync.moe/?domain=https://the-nonames.com"> NonamesScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animeshouse.net"><img src="https://favicon.malsync.moe/?domain=https://animeshouse.net"> AnimesHouse</a></td>
        <td><a href="https://reaperscans.com"><img src="https://favicon.malsync.moe/?domain=https://reaperscans.com"> ReaperScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animexin.xyz"><img src="https://favicon.malsync.moe/?domain=https://animexin.xyz"> AnimeXin</a></td>
        <td><a href="https://lynxscans.com"><img src="https://favicon.malsync.moe/?domain=https://lynxscans.com"> LynxScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://monoschinos2.com"><img src="https://favicon.malsync.moe/?domain=https://monoschinos2.com"> MonosChinos</a></td>
        <td><a href="https://skscans.com"><img src="https://favicon.malsync.moe/?domain=https://skscans.com"> SKScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animefire.net"><img src="https://favicon.malsync.moe/?domain=https://animefire.net"> AnimeFire</a></td>
        <td><a href="https://zeroscans.com"><img src="https://favicon.malsync.moe/?domain=https://zeroscans.com"> ZeroScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://otakufr.co"><img src="https://favicon.malsync.moe/?domain=https://otakufr.co"> OtakuFR</a></td>
        <td><a href="https://reader.deathtollscans.net"><img src="https://favicon.malsync.moe/?domain=https://reader.deathtollscans.net"> DeathTollScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://samehadaku.vip"><img src="https://favicon.malsync.moe/?domain=https://samehadaku.vip"> Samehadaku</a></td>
        <td><a href="https://reader.kireicake.com"><img src="https://favicon.malsync.moe/?domain=https://reader.kireicake.com"> KireiCake</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.tranimeizle.net/"><img src="https://favicon.malsync.moe/?domain=https://www.tranimeizle.net/"> TRanimeizle</a></td>
        <td><a href="https://sensescans.com"><img src="https://favicon.malsync.moe/?domain=https://sensescans.com"> SenseScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://anihub.tv"><img src="https://favicon.malsync.moe/?domain=https://anihub.tv"> Anihub</a></td>
        <td><a href="https://manhuaplus.com"><img src="https://favicon.malsync.moe/?domain=https://manhuaplus.com"> ManhuaPlus</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://beta.animestreamingfr.fr"><img src="https://favicon.malsync.moe/?domain=https://beta.animestreamingfr.fr"> AnimeStreamingFR</a></td>
        <td><a href="https://readm.org"><img src="https://favicon.malsync.moe/?domain=https://readm.org"> Readm</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.animeid.tv"><img src="https://favicon.malsync.moe/?domain=https://www.animeid.tv"> AnimeId</a></td>
        <td><a href="https://mangasee123.com"><img src="https://favicon.malsync.moe/?domain=https://mangasee123.com"> MangaSee</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animixplay.to"><img src="https://favicon.malsync.moe/?domain=https://animixplay.to"> AniMixPlay</a></td>
        <td><a href="https://asurascans.com"><img src="https://favicon.malsync.moe/?domain=https://asurascans.com"> AsuraScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://myanimelist.net"><img src="https://favicon.malsync.moe/?domain=https://myanimelist.net"> MyAnimeList</a></td>
        <td><a href="https://naniscans.com"><img src="https://favicon.malsync.moe/?domain=https://naniscans.com"> NaniScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animeunity.it"><img src="https://favicon.malsync.moe/?domain=https://animeunity.it"> AnimeUnity</a></td>
        <td><a href="https://merakiscans.com"><img src="https://favicon.malsync.moe/?domain=https://merakiscans.com"> MerakiScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://yayanimes.net"><img src="https://favicon.malsync.moe/?domain=https://yayanimes.net"> YayAnimes</a></td>
        <td><a href="https://mangajar.com"><img src="https://favicon.malsync.moe/?domain=https://mangajar.com"> MangaJar</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://desu-online.pl"><img src="https://favicon.malsync.moe/?domain=https://desu-online.pl"> DesuOnline</a></td>
        <td><a href="https://toonily.net"><img src="https://favicon.malsync.moe/?domain=https://toonily.net"> Toonily</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://simplyaweeb.to"><img src="https://favicon.malsync.moe/?domain=https://simplyaweeb.to"> Simplyaweeb</a></td>
        <td><a href="https://www.nonstopscans.com"><img src="https://favicon.malsync.moe/?domain=https://www.nonstopscans.com"> NonstopScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://tioanime.com"><img src="https://favicon.malsync.moe/?domain=https://tioanime.com"> tioanime</a></td>
        <td><a href="https://guya.moe"><img src="https://favicon.malsync.moe/?domain=https://guya.moe"> Guya & Cubari</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://yugen.to"><img src="https://favicon.malsync.moe/?domain=https://yugen.to"> YugenAnime</a></td>
        <td><a href="https://mangahub.io"><img src="https://favicon.malsync.moe/?domain=https://mangahub.io"> MangaHub</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animetribes.ru"><img src="https://favicon.malsync.moe/?domain=https://animetribes.ru"> AnimeTribes</a></td>
        <td><a href="https://comick.fun"><img src="https://favicon.malsync.moe/?domain=https://comick.fun"> ComicK</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://okanime.tv"><img src="https://favicon.malsync.moe/?domain=https://okanime.tv"> Okanime</a></td>
        <td><a href="https://www.japanread.cc/"><img src="https://favicon.malsync.moe/?domain=https://www.japanread.cc/"> Japanread</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://bs.to"><img src="https://favicon.malsync.moe/?domain=https://bs.to"> bs.to</a></td>
        <td><a href="https://mangasushi.net"><img src="https://favicon.malsync.moe/?domain=https://mangasushi.net"> MangaSushi</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://pantsubase.tv"><img src="https://favicon.malsync.moe/?domain=https://pantsubase.tv"> Pantsubase</a></td>
        <td><a href="https://arangscans.org"><img src="https://favicon.malsync.moe/?domain=https://arangscans.org"> ArangScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://an1me.nl"><img src="https://favicon.malsync.moe/?domain=https://an1me.nl"> An1me</a></td>
        <td><a href="https://hunlight-scans.info/"><img src="https://favicon.malsync.moe/?domain=https://hunlight-scans.info/"> HunlightScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animedao.to"><img src="https://favicon.malsync.moe/?domain=https://animedao.to"> AnimeDao</a></td>
        <td><a href="https://tritinia.com"><img src="https://favicon.malsync.moe/?domain=https://tritinia.com"> TritiniaScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.otakustv.com"><img src="https://favicon.malsync.moe/?domain=https://www.otakustv.com"> Otakustv</a></td>
        <td><a href="https://readmanhua.net"><img src="https://favicon.malsync.moe/?domain=https://readmanhua.net"> ReadManhua</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animewho.com"><img src="https://favicon.malsync.moe/?domain=https://animewho.com"> AnimeWho</a></td>
        <td><a href="https://flamescans.org"><img src="https://favicon.malsync.moe/?domain=https://flamescans.org"> FlameScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animesuge.to"><img src="https://favicon.malsync.moe/?domain=https://animesuge.to"> AnimeSuge</a></td>
        <td><a href="https://immortalupdates.com"><img src="https://favicon.malsync.moe/?domain=https://immortalupdates.com"> ImmortalUpdates</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://fumetsu.pl"><img src="https://favicon.malsync.moe/?domain=https://fumetsu.pl"> Fumetsu</a></td>
        <td><a href="https://lhtranslation.net"><img src="https://favicon.malsync.moe/?domain=https://lhtranslation.net"> LHTranslation</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://frixysubs.pl"><img src="https://favicon.malsync.moe/?domain=https://frixysubs.pl"> FrixySubs</a></td>
        <td><a href="https://mangas-origines.fr/"><img src="https://favicon.malsync.moe/?domain=https://mangas-origines.fr/"> MangasOrigines</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.anime-shitai.com"><img src="https://favicon.malsync.moe/?domain=https://www.anime-shitai.com"> AnimeShitai</a></td>
        <td><a href="https://www.bluesolo.org"><img src="https://favicon.malsync.moe/?domain=https://www.bluesolo.org"> BlueSolo</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://zoro.to"><img src="https://favicon.malsync.moe/?domain=https://zoro.to"> Zoro</a></td>
        <td><a href="https://disasterscans.com"><img src="https://favicon.malsync.moe/?domain=https://disasterscans.com"> DisasterScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.funimation.com"><img src="https://favicon.malsync.moe/?domain=https://www.funimation.com"> Funimation</a></td>
        <td><a href="https://dynasty-scans.com"><img src="https://favicon.malsync.moe/?domain=https://dynasty-scans.com"> DynastyScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://beta.kitsune.tv"><img src="https://favicon.malsync.moe/?domain=https://beta.kitsune.tv"> Kitsune</a></td>
        <td><a href="https://sugarbbscan.com/"><img src="https://favicon.malsync.moe/?domain=https://sugarbbscan.com/"> SugarBabies</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animesonline.org"><img src="https://favicon.malsync.moe/?domain=https://animesonline.org"> AnimesOnline</a></td>
        <td><a href="https://Alpha-Scans.org"><img src="https://favicon.malsync.moe/?domain=https://Alpha-Scans.org"> AlphaScans</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://tenshi.moe"><img src="https://favicon.malsync.moe/?domain=https://tenshi.moe"> tenshi</a></td>
        <td><a href="https://www.amascan.com"><img src="https://favicon.malsync.moe/?domain=https://www.amascan.com"> AMAScan</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://shiro.is"><img src="https://favicon.malsync.moe/?domain=https://shiro.is"> shiro</a></td>
        <td><a href="https://www.bilibilicomics.com"><img src="https://favicon.malsync.moe/?domain=https://www.bilibilicomics.com"> BilibiliComics</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://Anistream.de"><img src="https://favicon.malsync.moe/?domain=https://Anistream.de"> Anistream</a></td>
        <td><a href="https://mangareader.to"><img src="https://favicon.malsync.moe/?domain=https://mangareader.to"> MangaReader</a></td>
        <td></td>
      </tr><tr>
        <td><a href="https://anicloud.io"><img src="https://favicon.malsync.moe/?domain=https://anicloud.io"> Anicloud</a></td>
        <td></td>
        <td></td>
      </tr><tr>
        <td><a href="https://betteranime.net"><img src="https://favicon.malsync.moe/?domain=https://betteranime.net"> BetterAnime</a></td>
        <td></td>
        <td></td>
      </tr><tr>
        <td><a href="https://animeonsen.xyz"><img src="https://favicon.malsync.moe/?domain=https://animeonsen.xyz"> AnimeOnsen</a></td>
        <td></td>
        <td></td>
      </tr><tr>
        <td><a href="https://puray.moe"><img src="https://favicon.malsync.moe/?domain=https://puray.moe"> Puray</a></td>
        <td></td>
        <td></td>
      </tr><tr>
        <td><a href="https://www.animetoast.cc"><img src="https://favicon.malsync.moe/?domain=https://www.animetoast.cc"> Animetoast</a></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>
#+end_src
