#+title: Apache

- cat /home/u12345/logs/www.example.com | awk '{ print $NF, $6, $7, $9, $12, $4 }' | sort -n | tail -n 25
- [[https://github.com/apache/arrow][apache/arrow: Apache Arrow is a cross-language development platform for in-memory data. It specifies a standardized language-independent columnar memory format for flat and hierarchical data, organized for efficient analytic operations on modern hardware. It also provides computational libraries and zero-copy streaming messaging and interprocess communication. Languages currently supported include C, C++, Java, JavaScript, Python, and Ruby.]]

* Syntax

If you are using Apache 2.4 and above, you might get the following error message. This might specifically start happening after you’ve upgraded from an older version of apache.
: AH01630: client denied by server configuration: /home/myapp/server/
- [[https://linux.101hacks.com/unix/client-denied-by-server-configuration/][How to Fix Apache AH01630 Client Denied by Server Configuration Error]]
  - Remove any “Order deny,allow”, “Order allow,deny”, and related lines
  - Replace “Deny from all” to “Require all denied”
  - Replace “Allow from all” to “Require all granted”
  - If you are allowing any specific hostname, change them accordingly. For example, replace “Allow from 192.168.1.2” to “Require host 192.168.1.2”

MPM-ITK + php-cgi = Simple setup for running scripts as the owner, ok performance, can't use APC. Low memory usage.MPM-ITK + mod_php = Very simple setup, good performance and ability to use APC. Little more memory used.MPM-ITK + mod_fcgid = Couldn't get it working.MPM-prefork + suEXEC + php-cgi = More complicated setup, performance similar to MPM-ITK + php-cgi.MPM-prefork + suEXEC + mod_php = more complicated setup, good performance.MPM-prefork + suEXEC + mod_fcgid=more complicated setup, excellent performance.MPM-worker + suEXEC + php-cgi=More complicated setup, better performance than MPM-ITK + php-cgi.MPM-worker + suEXEC + mod_php=Not recommended because php is apparently not thread safe.MPM-worker + suEXEC + mod_fcgid=More complicated setup, best performance.
