
Archived entries from file /home/oleg/org/inbox.org


* [2017-09-15 Fri 01:47] [[gnus:INBOX#87y3pqtvze.fsf@gnu.org][Email from Ludovic Courtès: “Code Staging in GNU Guix”]] by [[mailto:ludovic.courtes@inria.fr][Ludovic Courtès]]
  :PROPERTIES:
  :ARCHIVE_TIME: 2019-11-26 Tue 02:48
  :ARCHIVE_FILE: ~/org/inbox.org
  :ARCHIVE_OLPATH: INBOX
  :ARCHIVE_CATEGORY: inbox
  :END:

- https://hal.inria.fr/hal-01580582/en
- https://conf.researchr.org/home/gpce-2017
- https://lists.gnu.org/archive/html/guix-devel/2017-07/msg00181.html


Archived entries from file /home/oleg/org/inbox.org


* [2017-09-15 Fri 11:33] [[gnus:INBOX#87d16xdway.fsf@gmail.com][Email from Maxim Cournoyer: Re: My experiences with GuixSD]] by [[mailto:maxim.cournoyer@gmail.com][Maxim Cournoyer]]
  :PROPERTIES:
  :ARCHIVE_TIME: 2019-11-26 Tue 02:48
  :ARCHIVE_FILE: ~/org/inbox.org
  :ARCHIVE_OLPATH: INBOX
  :ARCHIVE_CATEGORY: inbox
  :END:

  What greatly improved the font rendering on my side was to create a
  ~/.config/fontconfig/fonts.conf containing the following:


Archived entries from file /home/oleg/org/inbox.org


* [2017-09-15 Fri 11:34] [[gnus:INBOX#87d16xdway.fsf@gmail.com][Email from Maxim Cournoyer: Re: My experiences with GuixSD]] by [[mailto:maxim.cournoyer@gmail.com][Maxim Cournoyer]]
  :PROPERTIES:
  :ARCHIVE_TIME: 2019-11-26 Tue 02:48
  :ARCHIVE_FILE: ~/org/inbox.org
  :ARCHIVE_OLPATH: INBOX
  :ARCHIVE_CATEGORY: inbox
  :END:

  What greatly improved the font rendering on my side was to create a
  ~/.config/fontconfig/fonts.conf containing the following:

  #+BEGIN_EXAMPLE
    <?xml version="1.0"?>
    <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
    <fontconfig>
    <match target="font">
      <edit mode="assign" name="hinting" >
        <bool>true</bool>
      </edit>
    </match>
    <match target="font" >
      <edit mode="assign" name="autohint" >
        <bool>true</bool>
      </edit>
    </match>
    <match target="font">
      <edit mode="assign" name="hintstyle" >
        <const>hintfull</const>
      </edit>
    </match>
    <match target="font">
      <edit mode="assign" name="rgba" >
        <const>rgb</const>
      </edit>
    </match>
    <match target="font">
      <edit mode="assign" name="antialias" >
        <bool>true</bool>
      </edit>
    </match>
    <match target="font">
      <edit mode="assign" name="lcdfilter">
        <const>lcddefault</const>
      </edit>
    </match>
    <match target="pattern">
      <edit name="dpi" mode="assign"><double>92</double></edit>
    </match>
    <alias>
      <family>monospace</family>
      <prefer><family>Hack</family></prefer>
    </alias>
    <alias>
      <family>fixed</family>
      <prefer><family>Hack</family></prefer>
    </alias> 
    </fontconfig>
  #+END_EXAMPLE


Archived entries from file /home/oleg/org/inbox.org


* [2017-09-15 Fri 21:32] [[gnus:INBOX#86fubtkatd.fsf@zoho.com][Email from Emanuel Berg: Re: dired local ignore file ex]] by [[mailto:moasen@zoho.com][Emanuel Berg]]
  :PROPERTIES:
  :ARCHIVE_TIME: 2019-11-26 Tue 02:48
  :ARCHIVE_FILE: ~/org/inbox.org
  :ARCHIVE_OLPATH: INBOX
  :ARCHIVE_CATEGORY: inbox
  :END:

  #+BEGIN_SRC emacs-lisp
    (setq completion-ignored-extensions
          (nconc completion-ignored-extensions (list ".bcf" ".run.xml")))
  #+END_SRC


Archived entries from file /home/oleg/org/inbox.org


* [2017-09-15 Fri 22:10] [[gnus:INBOX#a6e1d6254c16421fef857bf8dbb208a2@hypermove.net][Email from Amirouche Boubekki: Guile in the browser {Was: Sum]] by [[mailto:amirouche@hypermove.net][Amirouche Boubekki]]
  :PROPERTIES:
  :ARCHIVE_TIME: 2019-11-26 Tue 02:48
  :ARCHIVE_FILE: ~/org/inbox.org
  :ARCHIVE_OLPATH: INBOX
  :ARCHIVE_CATEGORY: inbox
  :END:


Archived entries from file /home/oleg/org/inbox.org


* [2017-09-15 Fri 23:28] [[gnus:INBOX#E1dsOqu-00038a-T9@crmserver1p.fsf.org][Email from Richard Stallman: Why hackathons should insist o]] by [[mailto:info@fsf.org][Richard Stallman]]
  :PROPERTIES:
  :ARCHIVE_TIME: 2019-11-26 Tue 02:48
  :ARCHIVE_FILE: ~/org/inbox.org
  :ARCHIVE_OLPATH: INBOX
  :ARCHIVE_CATEGORY: inbox
  :END:

- https://www.gnu.org/philosophy/hackathons.html
- https://www.gnu.org/philosophy/free-sw.html
- https://www.gnu.org/philosophy/free-hardware-designs.html
- https://www.gnu.org/philosophy/free-software-even-more-important.html
- https://www.beyondhackathon.com/en
- http://www.hackathon.io/rbc-digital
- https://expediaconnectivity.com/blog#madrid-hackathon-winners
- https://www.gnu.org/licenses/license-list.html
- https://www.gnu.org/philosophy/open-source-misses-the-point.html
- https://www.gnu.org/education/edu-schools.html
- https://status.fsf.org/fsf
- https://fsf.org/blogs/RSS
- https://www.fsf.org/jf
- https://my.fsf.org/civicrm/mailing/unsubscribe?reset=1&jid=153744&qid=27942913&h=25897b414aa3112c
- https://my.fsf.org/civicrm/mailing/optout?reset=1&jid=153744&qid=27942913&h=25897b414aa3112c


Archived entries from file /home/oleg/org/inbox.org


* [[gnus:INBOX#E1dtjUd-0006B5-SG@fencepost.gnu.org][Email from Richard Stallman: Re: JSON/YAML/TOML/etc. parsin]] by [[mailto:rms@gnu.org][Richard Stallman]]
  :PROPERTIES:
  :ARCHIVE_TIME: 2019-11-26 Tue 02:48
  :ARCHIVE_FILE: ~/org/inbox.org
  :ARCHIVE_OLPATH: INBOX
  :ARCHIVE_CATEGORY: inbox
  :END:

  Yes it can be, but please avoid the term "MIT license".  There are
  two different licenses people sometimes call by that term, the X11
  license and the Expat license.  See
  https://gnu.org/licenses/license-list.html.

  Both of them are weak licenses -- we also call them "pushover"
  licenses -- since they permit inclusion in nonfree software.

  Please don't associate them with the name of MIT, as the
  association tends to promote them.


Archived entries from file /home/oleg/org/inbox.org


* [[gnus:INBOX#20170920061156.ed6ybieloxxvvs42@abyayala][Email from ng0: Re: Adopt a patch!]] by [[mailto:ng0@infotropique.org][ng0]]
  :PROPERTIES:
  :ARCHIVE_TIME: 2019-11-26 Tue 02:48
  :ARCHIVE_FILE: ~/org/inbox.org
  :ARCHIVE_OLPATH: INBOX
  :ARCHIVE_CATEGORY: inbox
  :END:

  https://www.youtube.com/watch?v=KJ9Y0midtW4&feature=youtu.be
  http://blog.ffwll.ch/2017/01/maintainers-dont-scale.html
  http://blog.ffwll.ch/slides/lca-2017.pdf
  https://www.linux.conf.au/schedule/presentation/57/

  There's also some interesting links in there aswell.

  There are some more recent post of this maintainer
  at http://blog.ffwll.ch/

