* [[https://www.banki.ru/news/daytheme/?id=10970863][Разбираемся, что такое чарджбэк, как запустить возврат денег, в каком случае это сработает и сколько дней займет процедура.]]

** Что такое чарджбэк

Это процедура оспаривания операции, когда покупатель оплатил товар или услугу
по банковской карте. Чарджбэк не упоминается в российском законодательстве,
поэтому его правила определяются правилами платежных систем. Как правило, это
бесплатно, но если банк просит комиссию, то стоит проверить договор, так как
этот нюанс должен быть обязательно отражен.

В этом процессе участвует также платежная система, поэтому если клиент оплатил
подписку или купил товар в зарубежном магазине по картам Visa и Mastercard,
процедуру провести уже не получится. Если банк-эквайер продавца тот же, что и
у клиента, то платежная система для чарджбэка не нужна. Процедуру также можно
запустить, если товар купили в российском магазине, хотя и по картам ушедших
из России платежных систем. Чарджбэк можно оформить на покупки и за рубежом, и
в России, если списание было с карты с платежной системой «Мир».

** Банк возвращает собственные средства или есть какая-то страховка?

Нет. Если процедуру одобрят, то эти деньги спишут у продавца или сервиса, плюс
их может оштрафовать платежная система. В крайнем случае бизнес может лишиться
эквайринга. Банки и компании платят платежным системам комиссию, если их
клиент оказывается не прав, поэтому очень важно подготовить все документы
правильно.

** В каких случаях банк может вернуть деньги

Вот несколько ситуаций, когда чарджбэк возможен:

- Покупатель оплатил товар в интернет-магазине, то заказ так и не пришел.
- Сервис онлайн-бронирований снял деньги за номер, хотя в условиях была
  указана бронь без предоплаты. Или клиент отменил бронь, у него списали
  средства за номер.
- Деньги за товар или услугу списали дважды.
- Клиент оплатил курс, но его не провели, потому что не набралось достаточно
  человек. Образовательная организация отказывается возвращать деньги и
  предлагает записаться на другой курс.
- Покупатель вернул некачественный товар, но деньги за него так и не вернулись.
- Продавец намеренно или по ошибке списал сумму больше, чем было указано на
  ценнике или в оферте. Правда, если речь идет о валютных сделках, то тогда
  вернуть деньги не получится — из-за комиссий за конвертацию сумма будет
  разная.
- Исполнитель оказал услугу частично. Например, клиент оплатил годовой
  абонемент в спортивный зал, но последний закрылся посреди года. Деньги
  вернутся за оставшийся месяц.
- Онлайн-сервис по ошибке списал деньги. Например, клиент оплатил подписку на
  один период и отказался от автопродления, но приложение все равно списывает
  деньги. Или из-за технической ошибки на стороне сервиса по аренде самокатов
  клиенту не удалось вовремя завершить поездку.

Важно! Клиенту придется доказать банку, что самостоятельно конфликт разрешить
не удается. Придется приложить к заявлению подтверждающие документы, скриншоты
и так далее. Чем весомее доказательство, тем больше шанс на возврат денег.

** Когда банк точно откажет в процедуре

Банк может отказать в процедуре чарджбэка, если уверен, что клиент не
прав. Это касается случаев, когда:

- Клиент добровольно отдал деньги мошенникам. К сожалению, в этом случае
  придется обращаться в полицию.
- Клиент недоволен оказанной услугой или качеством товара. По сути продавец
  выполнил все условия оферты или договора, а все остальные разбирательства
  должны проходить по закону о правах потребителей. При этом если клиент
  заказал одежду одного размера, ему доставили другого, а компания
  отказывается делать возврат, то в этом случае вернуть деньги можно.
- Клиент платил наличными, а хочет возврат на карту.

Правда, стоит помнить, что оставить заявление клиент все равно может, после
чего должен получить обоснованный отказ. Устные отказы со стороны сотрудников
отделений банков не повод сомневаться в своей правоте. К тому же решение по
процедуре принимают не в отделении банка, а профильные специалисты.

** Как попросить у банка чарджбэк

**** Шаг первый. Решаем конфликт без участия банка

Перед тем как обращаться в банк с заявлением, стоит попытаться решить проблему
с продавцом. Во-первых, если сразу бежать к банку, то он может отказать в
процедуре, так как Центральный банк не рекомендует вмешиваться в торговые
отношения между сторонами. Во-вторых, это способ собрать доказательства, что
продавец или сервис недобросовестно выполняет условия договора или оферты.

С продавцом можно связаться в чате поддержки или по электронной почте, а также
отправить заказное письмо. Ответ лучше подождать пару дней, а в случае с
письмом — 20–30 дней. Если общение ни к чему не приводит или продавец его
игнорирует, то пора готовить заявление в банк. Главное, не забывать делать
скриншоты всех переписок и не терять уведомления о вручении письма.

**** Шаг второй. Готовим заявление в банк

Заявление на чарджбэк лучше писать в отделении банка — у сотрудников должен
быть шаблон, в котором указаны пункты, которые интересуют при процедуре
чарджбэка больше всего. При этом заявление можно написать и в свободной форме,
направив пакет документов почтой. Лучше описывать все максимально точно и
подробно, но без лирических отступлений. Вот небольшой чек-лист, что должно
быть прикреплено к пакету документов:

- чеки и квитанции
- переписки с продавцом или проигнорированные сообщения
- условия, которые нарушил продавец или сервис — это могут быть скриншоты
  ценников или фотографии
- все СМС-уведомления от банка, связанные со случаем
- коды трансакций, связанные со случаем
- другие доказательства, что продавец злоупотребляет списаниями — например,
  фотографии машины, когда завершена поездка на каршеринге

У клиента есть порядка 120 дней с даты операции, чтобы ее оспорить.

**** Шаг третий. Ждем решения

У банка есть 30 дней, чтобы принять [[https://www.consultant.ru/document/cons_doc_LAW_115625/b0062cfb1c3cae710d57f0557303e78760a31d16/][решение]], но сроки увеличиваются до 60
дней, если покупка сделана за пределами России. Когда банк клиента убедится,
что его претензии обоснованы, он отправит запрос платежной системе, а та в
свою очередь передаст его эквайеру компании, который проверит все детали
операции, а также даст возможность предоставить доказательства другой
стороне. Если компания не отвечает, то деньги вернут клиенту.

Если банки не смогли договориться или убедить клиентов, платежная система
становится третьей стороной, которая по своим правилам принимает окончательное
решение. Если запрос оказывается справедливым, со счета компании списываются
деньги, а банк покупателя перечисляет их заявителю.

*** Помогают ли чарджбэк-сервисы вернуть деньги

Эти сервисы берут комиссию за то, что клиент может сделать и сам —
сформировать заявление и отправить его в банк. Если все-таки хочется перевести
общение с банком на посредника, то можно обезопасить себя и отказаться от
выплаты аванса.

Еще это могут быть мошенники. Стоит насторожиться, если сервис настойчиво
требует предоплаты за свои услуги и собирает банковские данные: номер карты,
срок действия карты и трехзначный CVV-код. Чтобы подать заявление на чарджбэк,
достаточно номера трансакции, а карту или счет, с которого оплачивалась
покупка, банк знает и сам. Поэтому такие сервисы не только не помогут, но еще
и украдут данные.

* [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/][Что такое чарджбэк и как им воспользоваться]]

** Содержание
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_1][Что такое чарджбэк и как им воспользоваться]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_2][В каких случаях можно запросить чарджбэк]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_3][Когда чарджбэк точно не сработает]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_4][Переводы частным лицам]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_5][Безосновательность претензии]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_6][Зарубежные операции]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_7][Политика банка-эмитента]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_8][Как подать заявление на чарджбэк]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_9][Сколько длится процедура возврата денег]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_10][Что делать, если в услуге chargeback отказали]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_11][Ваш банк не занимается чарджбэком или вышли сроки подачи заявки]]
- [[https://alfabank.ru/help/articles/credit-cards/chto-takoe-chardzhbek-i-kak-im-vospolzovatsya/#part_12][Нехватка оснований для чарджбэка]]
  
Оплатили онлайн-заказ, а товар так и не пришёл? Со счёта снимают деньги за
подписку, которую вы не оформляли? Расплатились с таксистом наличными, но с
карты всё равно списали стоимость поездки? Отменить безналичный платёж, с
которым вы не согласны, поможет процедура чарджбэка.

** Что такое чарджбэк

Слово chargeback переводится с английского как «возвратный платёж». Чарджбэк —
это возможность оспорить транзакцию и вернуть деньги при наличии объективных
причин.

В процедуре участвует несколько сторон:

- покупатель;
- продавец;
- банк-эмитент;
- банк продавца.

Покупатель — это владелец банковского счёта, с которого списаны
средства. Покупатель хочет вернуть деньги и выступает инициатором чарджбэка:
составляет заявление и обращается в свой банк. Самостоятельно оспорить
операцию оплаты покупатель не может, так как право на это имеют только
финансовые организации.

Продавец в chargeback-схеме — это юридическое или физическое лицо, в чью
пользу списаны средства. Продавцом может выступать интернет-магазин,
провайдер, онлайн-сервис, отель, авиакомпания, туроператор и другие поставщики
товаров или услуг.

Банк-эмитент — это банк покупателя. Он принимает заявление от своего клиента
и, если chargeback возможен, запускает процедуру возврата средств. Для этого
банк-эмитент обращается в платёжную систему, через которую был проведён
платёж. В свою очередь, платёжная система передаёт запрос на возврат денег в
банк продавца.

Банк продавца расследует инцидент и оценивает правомерность претензии. Если
решение принимается в пользу покупателя, то проводится процедура chargeback:
списание суммы со счёта продавца и возврат покупателю.

** В каких случаях можно запросить чарджбэк

Chargeback возможен только при безналичной оплате юридическому лицу или
ИП. Все обстоятельства сделки оценивают финансовые организации: решение о том,
вернуть ли средства покупателю, принимают банки.

Наиболее распространённые ситуации, в которых доступен chargeback:

- вы оплатили заказ, а его не доставили;
- оплаченный вами заказ пришёл, но товар оказался некачественным, и вы его
  вернули продавцу;
- заказ пришёл не в полном объёме;
- продавец прислал не тот товар, который вы оплатили;
- вы оплатили услуги, которые не были оказаны;
- оплата списалась дважды;
- со счёта списаны деньги за покупку, которую вы не совершали;
- сумма, списанная со счёта, превышает сумму заказа.

В последнем случае чарджбэк может и не сработать: например, при взаиморасчётах
с иностранным продавцом разница может быть обусловлена конвертацией валют.

Ситуация с недоставленным заказом тоже спорная: возможно, продавец отправил
товар, но посылка затерялась по дороге. Словом, каждый запрос на чарджбэк
требует детального изучения обстоятельств.

** Когда чарджбэк точно не сработает

*** Переводы частным лицам

Возврат денег возможен только в том случае, если вы обращались к легальному
продавцу. На переводы между частными лицами процедура chargeback не
распространяется.

Пример ситуаций, в которых чарджбэк не применяется:

- по ошибке отправили деньги не тому человеку;
- поверили мошенникам и перевели средства на чужой счёт;
- хотите отменить оплату товара, купленного с рук у физлица в соцсетях;
- переводили средства знакомому, но случайно отправили больше, чем собирались.

Что делать в подобных ситуациях? При ошибочном платеже свяжитесь с получателем
и попросите о возврате денег. В случае отказа вы вправе обратиться в суд на
основании статьи 1102 ГК РФ «Обязанность возвратить неосновательное
обогащение».

*** Безосновательность претензии

Chargeback не сработает, если права покупателя не были нарушены. Пример: вы
забронировали отель с предоплатой, но поездка отменилась. Если в правилах
отеля или сервиса бронирования указана информация о том, что эта бронь
невозвратная, то вернуть предоплату не получится.

Самые спорные ситуации касаются качества предоставленных услуг в сфере
образования, консалтинга, коучинга. Как доказать, что пройденный вами тренинг
оказался неинформативным и не стоит потраченных денег? Или что вместо
обещанного разговорного английского вам объясняли базовую грамматику? Проблема
в том, что в договоре между клиентом и поставщиком услуг обычно указывается
количество часов или уроков, а вот программа обучения не фиксируется. Поэтому
подтвердить факт недобросовестно выполненной работы вряд ли получится.

*** Зарубежные операции

В связи с остановкой обслуживания российских карточек «Виза» и «Мастеркард»
сейчас невозможен чарджбэк по взаиморасчётам с иностранными продавцами. Внутри
страны опротестовать операции по «Мастеркард» и «Виза» можно.

*** Политика банка-эмитента

Chargeback — это не услуга, решение о формировании Chargeback зависит от
правил платежной системы и обоснованности требований клиента. Однако заявление
у вас в любом случае примут: это прописано в законе № 161-ФЗ.

** Как подать заявление на чарджбэк

В первую очередь попробуйте договориться с продавцом напрямую. Если вам не
идут навстречу или игнорируют звонки и письма, то обратитесь в банк.

Узнайте, в какой форме принимаются заявления на возврат платежа. Уточните, на
какой адрес и в каком виде высылать заявку. Правильное оформление документов
сэкономит время сотрудникам банка и ускорит рассмотрение вашего обращения.

Приложите к заявлению максимум доказательств:

- чеки;
- выписки по счёту;
- переписку с продавцом;
- описание политики компании-продавца.

Допустим, вы купили через интернет одежду, а она не подошла. Продавец
отказывается возвращать деньги, хотя в правилах интернет-магазина такая
возможность указана. Значит, вместе с заявлением нужно предоставить банку
подтверждение заказа, оплаты и ссылку на сайт магазина, где описана политика
возврата.

** Сколько длится процедура возврата денег

В нашей стране процедура чарджбэка на законодательном уровне не
регламентирована. Порядок рассмотрения заявления и сроки возврата средств
определяют финансовые организации: платёжные системы и банки в соответствии с
внутренними регламентными документами.

В Альфа-Банке мы стараемся как можно быстрее рассматривать заявления от
клиентов. Обычно ответ приходит в течение 30 дней, но при международных
переводах процедура может занять больше времени. В процессе рассмотрения
заявки мы изучаем детали сделки, оцениваем обоснованность претензии, при
необходимости запрашиваем у вас дополнительные документы.

После рассмотрения заявки вы получаете уведомление об итогах рассмотрения
вашего обращения. В некоторых случаях ответом может быть отказ. Возможные
причины:

- недостаточно оснований для оспаривания платежа;
- истекли сроки обращения.

Обратите внимание: процедура чарджбэк не является обязательной. Мы вправе
отказать в ее проведении, а также установить свои сроки и порядок проведения
процедуры.

При положительном решении по заявке в процедуру включаются платёжная система и
банк продавца. Сроки выплаты зависят от их действий, а также от самого
продавца, который имеет право аргументировать свою позицию и оспорить
chargeback.

Если покупатель и продавец являются клиентами одного банка, значит, денежная
операция проведена без участия платёжной системы, и это может ускорить процесс
возвращения средств.

** Что делать, если в услуге chargeback отказали

Варианты зависят от причины отказа.

*** Ваш банк не занимается чарджбэком или вышли сроки подачи заявки

Можно обратиться в суд, пожаловаться в Роспотребнадзор или обсудить с
продавцом альтернативные варианты компенсации. Возможно, ваш оппонент не имеет
возможности вернуть деньги, но готов предложить аналогичный товар, бесплатную
услугу, скидку, льготное обслуживание у партнёров.

Когда продавец не идёт на контакт, а судебную тяжбу затевать вы не готовы,
можно привлечь к проблеме внимание интернет-общественности. Оставляйте честные
комментарии и отзывы, подробно описывайте ситуацию и предпринятые меры. Этот
простой способ особенно эффективен при общении с компаниями, которые строят
бизнес на продвижении бренда и дорожат своей репутацией в сети.

*** Нехватка оснований для чарджбэка

Узнайте в банке, можете ли вы предоставить больше сведений для решения вопроса
в вашу пользу. Как правило, крупные банки предоставляют чёткие инструкции по
заполнению заявления и документам для чарджбэка.

Для клиентов Альфа-Банка мы разместили подробную информацию по процедуре
возврата платежей на [[https://alfabank.ru/claim/][этой странице]]. Для каждой ситуации выложен шаблон заявки
и указан email, на который нужно выслать документы.

Перечень проблем, с которыми наши клиенты могут обратиться за chargeback:

- оформили возврат товара, а продавец не вернул средства;
- отказались от услуги, а деньги вам не возвращают;
- двойное списание;
- сумма в чеке отличается от фактического списания — списалось больше в той же
  валюте;
- расплатились в одной валюте, а списание прошло в другой;
- товары или услуги не были получены (банкомат не выдал наличные, авиакомпания
  отменила рейс и т. п.);
- вы не совершали операцию и никому не сообщали ваши платёжные реквизиты, но
  со счёта списаны средства;
- покупка или услуга оплачена другой карточкой или наличными, из-за чего
  произошло дублирование оплаты.

Также в целях поддержки клиентов мы сделали упор на предоставление доступных и
выгодных финансовых услуг. Одним из таких продуктов является флагманская
[[https://alfabank.ru/get-money/credit-cards/100-days/][кредитка с целым годом без %]].

Преимущества продукта:
- 365 дней без процентов на покупки в первые 30 дней;
- далее 100 дней без процентов;
- год обслуживания 0 ₽;
- снятие до 50 000 ₽ в месяц без комиссии;
- кэшбэк до 33%.
  
Процедура оформления простая: подаёте заявку на сайте и получаете одобрение
через две минуты. Карточку могут сделать в тот же день или на
следующий. Забрать её можно в ближайшем отделении Альфа-Банка или заказать
доставку.

Чтобы получить выгодную кредитку, оформите заявку онлайн!
