* [[https://www.banki.ru/news/daytheme/?id=10970863][Разбираемся, что такое чарджбэк, как запустить возврат денег, в каком случае это сработает и сколько дней займет процедура.]]

** Что такое чарджбэк

Это процедура оспаривания операции, когда покупатель оплатил товар или услугу
по банковской карте. Чарджбэк не упоминается в российском законодательстве,
поэтому его правила определяются правилами платежных систем. Как правило, это
бесплатно, но если банк просит комиссию, то стоит проверить договор, так как
этот нюанс должен быть обязательно отражен.

В этом процессе участвует также платежная система, поэтому если клиент оплатил
подписку или купил товар в зарубежном магазине по картам Visa и Mastercard,
процедуру провести уже не получится. Если банк-эквайер продавца тот же, что и
у клиента, то платежная система для чарджбэка не нужна. Процедуру также можно
запустить, если товар купили в российском магазине, хотя и по картам ушедших
из России платежных систем. Чарджбэк можно оформить на покупки и за рубежом, и
в России, если списание было с карты с платежной системой «Мир».

** Банк возвращает собственные средства или есть какая-то страховка?

Нет. Если процедуру одобрят, то эти деньги спишут у продавца или сервиса, плюс
их может оштрафовать платежная система. В крайнем случае бизнес может лишиться
эквайринга. Банки и компании платят платежным системам комиссию, если их
клиент оказывается не прав, поэтому очень важно подготовить все документы
правильно.

** В каких случаях банк может вернуть деньги

Вот несколько ситуаций, когда чарджбэк возможен:

- Покупатель оплатил товар в интернет-магазине, то заказ так и не пришел.
- Сервис онлайн-бронирований снял деньги за номер, хотя в условиях была
  указана бронь без предоплаты. Или клиент отменил бронь, у него списали
  средства за номер.
- Деньги за товар или услугу списали дважды.
- Клиент оплатил курс, но его не провели, потому что не набралось достаточно
  человек. Образовательная организация отказывается возвращать деньги и
  предлагает записаться на другой курс.
- Покупатель вернул некачественный товар, но деньги за него так и не вернулись.
- Продавец намеренно или по ошибке списал сумму больше, чем было указано на
  ценнике или в оферте. Правда, если речь идет о валютных сделках, то тогда
  вернуть деньги не получится — из-за комиссий за конвертацию сумма будет
  разная.
- Исполнитель оказал услугу частично. Например, клиент оплатил годовой
  абонемент в спортивный зал, но последний закрылся посреди года. Деньги
  вернутся за оставшийся месяц.
- Онлайн-сервис по ошибке списал деньги. Например, клиент оплатил подписку на
  один период и отказался от автопродления, но приложение все равно списывает
  деньги. Или из-за технической ошибки на стороне сервиса по аренде самокатов
  клиенту не удалось вовремя завершить поездку.

Важно! Клиенту придется доказать банку, что самостоятельно конфликт разрешить
не удается. Придется приложить к заявлению подтверждающие документы, скриншоты
и так далее. Чем весомее доказательство, тем больше шанс на возврат денег.

** Когда банк точно откажет в процедуре

Банк может отказать в процедуре чарджбэка, если уверен, что клиент не
прав. Это касается случаев, когда:

- Клиент добровольно отдал деньги мошенникам. К сожалению, в этом случае
  придется обращаться в полицию.
- Клиент недоволен оказанной услугой или качеством товара. По сути продавец
  выполнил все условия оферты или договора, а все остальные разбирательства
  должны проходить по закону о правах потребителей. При этом если клиент
  заказал одежду одного размера, ему доставили другого, а компания
  отказывается делать возврат, то в этом случае вернуть деньги можно.
- Клиент платил наличными, а хочет возврат на карту.

Правда, стоит помнить, что оставить заявление клиент все равно может, после
чего должен получить обоснованный отказ. Устные отказы со стороны сотрудников
отделений банков не повод сомневаться в своей правоте. К тому же решение по
процедуре принимают не в отделении банка, а профильные специалисты.

** Как попросить у банка чарджбэк

**** Шаг первый. Решаем конфликт без участия банка

Перед тем как обращаться в банк с заявлением, стоит попытаться решить проблему
с продавцом. Во-первых, если сразу бежать к банку, то он может отказать в
процедуре, так как Центральный банк не рекомендует вмешиваться в торговые
отношения между сторонами. Во-вторых, это способ собрать доказательства, что
продавец или сервис недобросовестно выполняет условия договора или оферты.

С продавцом можно связаться в чате поддержки или по электронной почте, а также
отправить заказное письмо. Ответ лучше подождать пару дней, а в случае с
письмом — 20–30 дней. Если общение ни к чему не приводит или продавец его
игнорирует, то пора готовить заявление в банк. Главное, не забывать делать
скриншоты всех переписок и не терять уведомления о вручении письма.

**** Шаг второй. Готовим заявление в банк

Заявление на чарджбэк лучше писать в отделении банка — у сотрудников должен
быть шаблон, в котором указаны пункты, которые интересуют при процедуре
чарджбэка больше всего. При этом заявление можно написать и в свободной форме,
направив пакет документов почтой. Лучше описывать все максимально точно и
подробно, но без лирических отступлений. Вот небольшой чек-лист, что должно
быть прикреплено к пакету документов:

- чеки и квитанции
- переписки с продавцом или проигнорированные сообщения
- условия, которые нарушил продавец или сервис — это могут быть скриншоты
  ценников или фотографии
- все СМС-уведомления от банка, связанные со случаем
- коды трансакций, связанные со случаем
- другие доказательства, что продавец злоупотребляет списаниями — например,
  фотографии машины, когда завершена поездка на каршеринге

У клиента есть порядка 120 дней с даты операции, чтобы ее оспорить.

**** Шаг третий. Ждем решения

У банка есть 30 дней, чтобы принять [[https://www.consultant.ru/document/cons_doc_LAW_115625/b0062cfb1c3cae710d57f0557303e78760a31d16/][решение]], но сроки увеличиваются до 60
дней, если покупка сделана за пределами России. Когда банк клиента убедится,
что его претензии обоснованы, он отправит запрос платежной системе, а та в
свою очередь передаст его эквайеру компании, который проверит все детали
операции, а также даст возможность предоставить доказательства другой
стороне. Если компания не отвечает, то деньги вернут клиенту.

Если банки не смогли договориться или убедить клиентов, платежная система
становится третьей стороной, которая по своим правилам принимает окончательное
решение. Если запрос оказывается справедливым, со счета компании списываются
деньги, а банк покупателя перечисляет их заявителю.

*** Помогают ли чарджбэк-сервисы вернуть деньги

Эти сервисы берут комиссию за то, что клиент может сделать и сам —
сформировать заявление и отправить его в банк. Если все-таки хочется перевести
общение с банком на посредника, то можно обезопасить себя и отказаться от
выплаты аванса.

Еще это могут быть мошенники. Стоит насторожиться, если сервис настойчиво
требует предоплаты за свои услуги и собирает банковские данные: номер карты,
срок действия карты и трехзначный CVV-код. Чтобы подать заявление на чарджбэк,
достаточно номера трансакции, а карту или счет, с которого оплачивалась
покупка, банк знает и сам. Поэтому такие сервисы не только не помогут, но еще
и украдут данные.
