:PROPERTIES:
:ID:       63242a98-634c-4236-999c-5b26d588b4d9
:END:
#+title: BGP

- [[https://habr.com/ru/post/211176/][Защита от DDOS атак средствами BGP / Хабр]]
- [[https://www.jordanwhited.com/posts/corebgp-plugging-in-to-bgp/][CoreBGP - Plugging in to BGP | Jordan Whited]]
- [[https://github.com/jwhited/corebgp][jwhited/corebgp: CoreBGP is a BGP library written in Go that implements the BGP FSM with an event-driven, pluggable model.]]
- [[https://github.com/RIPE-NCC/bgpdump][RIPE-NCC/bgpdump: Utility and C Library for parsing MRT files]]
- [[https://github.com/osrg/rustybgp][osrg/rustybgp: BGP implemented in the Rust Programming Language]]
- [[https://github.com/osrg/gobgp][osrg/gobgp: BGP implemented in the Go Programming Language]]
- [[https://github.com/osrg/bgperf][osrg/bgperf]]
- [[https://isbgpsafeyet.com/][Is BGP safe yet? · Cloudflare]]
- [[https://www.ssi.gouv.fr/uploads/2016/03/bgp-configuration-best-practices.pdf][bgp-configuration-best-practices.pdf]]
- [[https://peeringdb.com/net/10572][PeeringDB DataIX]]
- [[https://techstat.net/bgp-how-to-configure-basic-multipathload-balancing/][BGP - How to configure basic Multipath/Load balancing - Techstat]]
- [[https://blog.benjojo.co.uk/post/bgp-battleships][Playing battleships over BGP]]
- [[https://habr.com/ru/post/184350/][Сети для самых маленьких. Часть восьмая. BGP и IP SLA / Хабр]]
- [[https://q05t9n.wordpress.com/2016/02/08/2-%D0%B0%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%D1%8B-bgp-%D0%B8-%D0%B2%D1%8B%D0%B1%D0%BE%D1%80-%D0%BF%D1%83%D1%82%D0%B8/][2. Атрибуты BGP и выбор пути. – q05t9n goes ccnp]]
- [[https://github.com/Exa-Networks/exabgp/wiki/Controlling-ExaBGP-:-possible-options-for-process][Controlling ExaBGP : possible options for process · Exa-Networks/exabgp Wiki]]
- [[https://erco.xyz/][Erco: Exabgp Routes Controller]]
- [[https://thepacketgeek.com/exabgp/getting-started/][ExaBGP and Python Getting Started - thePacketGeek]]
- [[https://www.dasblinkenlichten.com/working-with-exabgp-4/][Working with ExaBGP 4 – Das Blinken Lichten]]
- [[https://github.com/faucetsdn/ryu][faucetsdn/ryu: Ryu component-based software defined networking framework]]
- [[https://www.noction.com/blog/bgp-flow-specification-version-2][BGP Flow Specification Version 2 | Noction]]
- [[https://github.com/inex/IXP-Manager][inex/IXP-Manager: Full stack web application powering peering at ~200 Internet Exchange Points (IXPs) globally.]]

* Looking glass
- [[http://lg.level3carrier.com/lg/lg.cgi][AS58682 Looking Glass]]
- [[https://lg.telia.net/][Telia Looking Glass]]
- [[https://lg.he.net/][Looking Glass - Hurricane Electric (AS6939)]]
- [[https://looking.house/point.php?id=86][Point in Netherlands, Amsterdam, data center Datacenter.com from Eurobyte]]
- [[https://www.msk-ix.ru/en/lookingglass/][LG :: MSK-IX]]
- [[https://looking.house/index.php][Looking Glass points: execute host, ping, traceroute and mtr commands for domain name and IPv4 or IPv6 addresses]]
- [[https://bgpview.io/asn/43362#upstreams-v4][AS43362 Hosting Ltd BGP Network Information - BGPView]]

** [[http://lg.mtu.ru/cgi-bin/lgform_img.cgi][MTS]]
Our PeeringDB page: as8359
Our Peering Policy page: here
Should you have any questions, please contact noc@mtu.ru

* RIPE
- [[https://apps.db.ripe.net/db-web-ui/query?bflag=&searchtext=AS-DATAIX&source=RIPE#resultsSection][Webupdates — RIPE Network Coordination Centre]]
- [[https://habr.com/ru/company/linxdatacenter/blog/526508/][Основы работы с базой данных RIPE / Хабр]]

Полезные запросы whois:

- Посмотреть шаблон объекта.
  : whois -t object_type

- Узнать все маршруты, которые происходят из автономной системы.
  : whois -T route -i origin ASxxxxx

- Узнать все объекты, которые защищены объектом «maintainer_name».
  : whois -i mnt-by maintainer_name

- Узнать, на какие более мелкие подсети поделена подсеть «subnet».
  : whois -M subnet

- Узнать, из какой более крупной подсети образована подсеть «subnet».
  : whois -L subnet

* Learning
- [[https://antiddos.biz/nastrojka-bgp-marshrutizacii-dlya-raboty-s-sobstvennoj-setyu/][Настройка BGP маршрутизации для работы с собственной сетью. - AntiDDoS.biz]]
  - [[https://dn42.eu/Home][dn42 is a big dynamic VPN, which employs Internet technologies (BGP, whois database, DNS, etc).]]
- [[https://github.com/leahneukirchen/docker-lab-bgp][leahneukirchen/docker-lab-bgp: A small BGP lab in Docker]]
- [[https://linkmeup.ru/blog/1198/][Сети для самых маленьких. Часть восьмая. BGP и IP SLA - linkmeup]]
- [[https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ][Free CCNA 200-301 | Complete Course 2022 - YouTube]]
- [[https://habr.com/ru/post/282532/][Ищем свободные IPv4 в BGP full-view / Хабр]]
- [[https://linkmeup.ru/blog/1201/][Сети для самых маленьких. Микровыпуск №3. IBGP - linkmeup]]

** BGP

BGP stands for Border Gateway Protocol, which is a standardized exterior gateway protocol designed to exchange routing and reachability information between routers in different autonomous systems (AS) on the Internet.

BGP is used to build routing tables in routers that direct packets between networks, and it enables routers to make informed decisions on which paths to use when forwarding packets. The information exchanged between routers using BGP includes the destination network, the next hop to the destination network, and various attributes that describe the characteristics of the path, such as its cost, reliability, and latency.

BGP is an important component of the Internet's infrastructure and plays a crucial role in enabling the interconnectivity of different networks and ensuring that data can be reliably and efficiently routed from one place to another.

** What is BGP full view?

A "BGP full view" refers to the complete set of BGP routing information that a router has learned from its neighbors. In BGP, routers exchange information about the routes they know about and update their routing tables accordingly. The full view includes all of the BGP routes that the router has learned from its neighbors, including information about the destination network, the next hop, and the various attributes that describe the path.

Having a full view of the BGP routing information is important for routers in making informed decisions about how to forward packets. The full view allows routers to determine the best paths to use for forwarding packets and to detect and avoid potential routing loops.

In some cases, a router may not have a full view of the BGP routing information due to a lack of neighbors, limited resources, or other factors. In these cases, the router may only have a partial view of the BGP routing information, which can result in suboptimal routing decisions and increased latency.

** Use cases for BG full view?

There are several use cases for a BGP full view:

    Internet Service Providers (ISPs): ISPs use BGP to exchange routing information with other ISPs and to build routing tables that allow them to direct traffic between their networks and the Internet. Having a full view of the BGP routing information is important for ISPs because it allows them to make informed decisions about how to forward traffic, ensure that traffic is being routed over the most efficient paths, and avoid potential routing loops.

    Data Centers: Data centers use BGP to interconnect their networks and to ensure that traffic is being routed between their networks in an efficient and reliable manner. A full view of the BGP routing information is important for data centers because it allows them to make informed decisions about how to forward traffic, avoid potential routing loops, and ensure that traffic is being routed over the most efficient paths.

    Enterprises: Enterprises use BGP to interconnect their networks and to ensure that traffic is being routed between their networks in an efficient and reliable manner. A full view of the BGP routing information is important for enterprises because it allows them to make informed decisions about how to forward traffic, avoid potential routing loops, and ensure that traffic is being routed over the most efficient paths.

    Government Agencies: Government agencies use BGP to interconnect their networks and to ensure that traffic is being routed between their networks in an efficient and reliable manner. A full view of the BGP routing information is important for government agencies because it allows them to make informed decisions about how to forward traffic, avoid potential routing loops, and ensure that traffic is being routed over the most efficient paths.

Overall, having a full view of the BGP routing information is important for ensuring efficient and reliable routing of traffic on the Internet.
