:PROPERTIES:
:ID:       eafefc5b-8b3a-4d19-aecc-102f30c64254
:END:
#+title: CISCO

* Misc

- logging
.May 11 10:27:02: %PORT_SECURITY-2-PSECURE_VIOLATION: Security violation occurred, caused by MAC address xxxx.xxxx.xxxx on port FastEthernet0/20.
.May 11 10:27:02: %PORT_SECURITY-2-PSECURE_VIOLATION_VLAN: Security violation on port FastEthernet0/20 due to MAC address xxxx.xxxx.xxxx on VLAN 253

- terminal length 0
- [[https://github.com/rememberYou/gen-cisco][rememberYou/gen-cisco: 🧨 Generates Cisco scripts based on YAML files]]

- [[https://admin-gu.ru/device/cisco/nastrojka-zerkalirovaniya-span-i-rspan-na-cisco][Настройка зеркалирования SPAN и RSPAN на cisco]]

* Port-security
- [[http://xgu.ru/wiki/Port_security][Port security — Xgu.ru]]
Best use "sticky".

* Cheat sheet
- [[https://packetlife.net/media/library/40/IOS_Interior_Routing_Protocols.pdf][Visio-Internal Routing Protocols Poster.vsd - IOS_Interior_Routing_Protocols.pdf]]

- copy running-config startup-config

- Reset interface to defulat settings
  #+begin_example
    sw2-mr12.intr(config)#default interface fa0/24
    Interface FastEthernet0/24 set to default configuration
  #+end_example

#+begin_example
  sw2-mr12.intr#show mac-address-table | include 2c2d
   252    0025.9006.2c2d    DYNAMIC     Fa0/35
  Fa0/35    mj355-ipmi         connected    252        a-full  a-100 10/100BaseTX
#+end_example

* 

Cisco ICND

Origin https://community.cisco.com/t5/routing/how-to-enable-ssh-cli-on-cisco-2960-switch/td-p/2123470

How to enable SSH CLI on Cisco 2960 Switch

SSH config

http://www.cisco.com/en/US/docs/switches/lan/catalyst2960/software/release/12.2_53_se/configuration/guide/swauthen.html#wp1227177

Port security

http://www.cisco.com/en/US/docs/switches/lan/catalyst2960/software/release/12.2_53_se/configuration/guide/swtrafc.html#wp1038501

Port Protection

http://www.cisco.com/en/US/docs/switches/lan/catalyst2960/software/release/12.2_53_se/configuration/guide/swtrafc.html#wp1175133

RSTP

http://www.cisco.com/en/US/docs/switches/lan/catalyst2960/software/release/12.2_53_se/configuration/guide/swstp.html#wp1166029

TFTP

http://www.cisco.com/en/US/products/sw/iosswrel/ps1835/products_tech_note09186a008020260d.shtml

For TFTP you will need a TFTP server set up.  From the router you will issue the commands in the link I provided.

* tcpdump

tcpdump -v -s0 udp and port 520

* Configure telnet

https://learningnetwork.cisco.com/thread/66649

Under the switch go to the vlan1 interface: interface vlan 1

(config-if) ip address x.x.x.x  x.x.x.x

(config-if) no shut

(config) ip default-gateway x.x.x.x

* Learning
- [[https://habr.com/ru/articles/738068/][Журналирование событий средствами Cisco / Хабр]]

* Download

- http://ipmanager.ir/?=CISCO%5C7200
- http://ciscotips.ru/singlearea-ospf-configuration

* Errors

Inbound errors on interface fa0/12
However most likely a Rcv-err is indicating a duplex mismatch.Xmit-Err and Rcv-ErrThis indicates that the internal port transmit (Tx) or receive (Rx) buffers are full. A common cause of Xmit-Err is traffic from a high-bandwidth link that is switched to a lower-bandwidth link, or traffic from multiple inbound links that is switched to a single outbound link. For example, if a large amount of bursty traffic comes in on a Gigabit port and is switched out to a 100-Mbps port, the Xmit-Err field might increment on the 100-Mbps port. This is because the port output buffer is overwhelmed by the excess traffic because of the speed mismatch between the incoming and outgoing bandwidths.
: Заменить патчкорд?

* VLAN

- [[https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst2960/software/release/12-2_40_se/configuration/guide/scg/swvlan.pdf][Configuring VLANs]]
#+begin_example
  Switch(config)# interface gigabitethernet0/1
  Switch(config-if)# switchport trunk allowed vlan remove 2
  Switch(config-if)# end
#+end_example
