#+TITLE: Emacs

* Clipboard

- [[http://pragmaticemacs.com/emacs/add-the-system-clipboard-to-the-emacs-kill-ring/][Add the system clipboard to the Emacs kill-ring]]

* ormode

** News
- [[http://kitchingroup.cheme.cmu.edu/blog/2016/11/04/New-link-features-in-org-9/?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed:+TheKitchinResearchGroup+(The+Kitchin+Research+Group)][New link features in org 9]]

** Howtos
- C-c l and C-c C-l -- Store links

* Spacemacs

** Themes

[[https://github.com/nashamri/spacemacs-theme][nashamri/spacemacs-theme: Light and dark theme for spacemacs that supports GUI and terminal]]

** Docker

 - [[https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bdistributions/spacemacs-docker/README.org][spacemacs/README.org at develop · syl20bnr/spacemacs]]

* ivy

- C-c C-o (ivy-occur) -- Saves the current candidates to a new buffer and exits completion.
- C-m r l -- (ivy-resume)
* Howtos

- [[https://www.youtube.com/watch?v=ZP_wXNQsydI][Open a file with su/sudo inside Emacs using Spacemacs Distribution - YouTube]]

* Elisp

- [[http://harryrschwartz.com/2014/04/08/an-introduction-to-emacs-lisp.html][Harry R. Schwartz]]
* gnus

** Show read articles

*** shortcut

L -- show all articles
B DEL -- remove article

*** stack

[[https://lists.gnu.org/archive/html/info-gnus-english/2012-03/msg00188.html][Re: gnus newbie question: why do read articles disappear from summary?]]

Brendan Miller <address@hidden> writes:

> After reading an article in summary it gets marked with 'R'. If I leave
> the summary buffer for my group with q and log back in, that article
> disappears. Why is this? Also, is there a way to prevent this behavior?

If you enter the summary with a prefix (like C-u RET), it'll show up
again. Within a summary buffer, you can do C-u M-g to show read
articles. 

But if anyone's got a handy "show me ten older articles" elisp snippet
hanging around, I'd love to get a copy …

> I really only want articles to disappear if I manually ask for it.

With news groups, you may have 27102 "read" articles, showing all of
them each time you enter would take a while … but I guess you could bind
a key to do the equivalent of C-u 20 RET to always show you the 20 last
when you enter.

> Also, I've noticed there is a way to mark an article read using d, but
> it makes it with a lower case 'r' flag. What's the difference between
> this lower case 'r' flag and the upper case 'R' flag?

r is manually marked read, R is really read ;) I'm pretty sure they're
treated the same when you exit the summary though.

-Kevin
