- [2020-08-06 Thu 11:15] [[gnus:INBOX#E1k3Wq4-00055u-Ns@fencepost.gnu.org][Email from Richard Stallman: Making GNUS continue to work with Gmail]] by [[mailto:rms@gnu.org][Richard Stallman]]** 
  - [[https://debbugs.gnu.org/cgi/bugreport.cgi?bug=41386][#41386 - 28.0.50; Gnus nnimap OAuth 2.0 support - GNU bug report logs]]

* gnus-posting-styles
#+begin_quote
I am trying to use Gnus again after about five years. Using my
configuration file that I had with Ma Gnus (so maybe that's the
issue...).

I have multiple accounts and used posting styles to send from different
accounts based on the From header. The set-up I have below worked
previously. Now mails cannot be sent and Emacs thinks that smtpmail is
not running. 

I using Emacs GNU Emacs 26.3 (build 1, x86_64-unknown-openbsd, GTK+
Version 3.24.20) of 2020-05-09 and the Gnus that comes with it, v5.13. 

Any suggestions or pointers would be greatly appreciated.

This is my SMTP part:

(setq message-signature-directory "~/.signatures")
(setq smtpmail-auth-credentials "~/.authinfo.gpg")
(setq message-send-mail-function 'smtpmail-send-it)

(setq gnus-posting-styles
      '(("Countermail:*"
	 (x-identity "Countermail")
	 (address "aorchid@countermail.com")
	 (reply-to "aorchid@countermail.com")
	 ("X-Message-SMTP-Method" "smtp imap1.countermail.com 465")
	 (body "\nThanks, Aric\n"))

	((header "to" "someone@ucla.edu")
	 (x-identity "Countermail-another")
	 (address "someone@countermail.com")
	 (reply-to "someone@countermail.com")
	 ("X-Message-SMTP-Method" "smtp imap1.countermail.com 465")
	 (body "\nThanks, Aric\n")
	 (eval (setq mml2015-signers '("someone@countermail.com")))
	 )

	((header "to" "someone@countermail.com")
	 (x-identity "Countermail-another")
	 (address "someone@countermail.com")
	 (reply-to "someone@countermail.com")
	 (eval (setq mml2015-signers '("someone@countermail.com")))
	 ("X-Message-SMTP-Method" "smtp imap1.countermail.com 465")
	 (body "\nThanks, Aric\n")
	 (signature-file "signature-short"))
	("Mac:*" 
	 (address "me@mac.com")
	 ("X-Message-SMTP-Method" "smtp outbound.mailhop.org 465
	user") 
	(body "\nThanks, Aric\n")
	 (signature-file "signature_bike"))
	("Gmail:*"
	 (address "me@gmail.com")
	 (reply-to "me@gmail.com")
	 ("X-Message-SMTP-Method" "smtp smtp.gmail.com 587")
	 (signature-file "signature_bike"))

The .auth file looks like the following:

machine Gmail login "me@gmail.com" port "587" password "..." 
machine BOL login "..." port "587" password "..." 
machine "mail.mac.com" login "me" port "imaps" password
"..." 
machine Gmail login "me" port "imaps" password "..."
machine BOL login "..." port "imaps" password "..."
machine "imap1.countermail.com" login "..." port
"imaps" password "..." 
machine "outbound.mailhop.org" login "someone" port "465" password
"..." 
machine "imap1.countermail.com" login "..." port "465" password "..."

Thanks in advance.
Aric
#+end_quote

* Toggle steam type

  #+begin_src emacs-lisp
    (defun change-stream-type ()
      (cond ((equal user-mail-address "metoothree@gmail.com")
             (setq smtpmail-stream-type 'ssl))
            ((equal user-mail-address "metoo@mac.com")
             (setq smtpmail-stream-type 'starttls))
            ((equal user-mail-address "me@countermail.com")
             (setq smtpmail-stream-type 'starttls))
            ((equal user-mail-address "aorchid@countermail.com")
             (setq smtpmail-stream-type 'starttls))))

    (add-hook 'message-send-hook 'change-stream-type)
  #+end_src

  Mail headers
  #+begin_src emacs-lisp
    (setq gnus-visible-headers
          '( "^From:"
             "^Newsgroups:"
             "^Subject:"
             "^Date:"
             "^Message-ID:"
             "^Supersedes:"
             "^Followup-To:"
             "^Reply-To:"
    ;;       "^Summary:"
    ;;       "^Keywords:"
    ;;       "^Importance:"
             "^To:"
             "^Cc:"
             "^Bcc:"
    ;;       "^Gnus-Warning:"
             "^X-Face-Img:"
             "^User-Agent:"
             "^X-Mailer:"
             "^X-Mailreader:"
             "^X-Newsreader:"
             "^X-User-Agent:"
    ;;       "^X-Now-Playing:"
    ;;       "^Content-Type:"
             "^X-Spam-Status:"))
  #+end_src

* MIME

: <87wo20b4lo.fsf@tullinup.koldfront.dk>

What do I need to configure to have that done automatically, so I don't have
to navigate to the attachment and press RET?

The motivating factor of asking a question is incredible. This is what I found
was needed:

#+begin_src emacs-lisp
  ;; Show inline:
  (add-to-list 'mm-attachment-override-types "application/zip")
  (add-to-list 'mm-automatic-display "application/zip")

  (add-to-list 'mm-attachment-override-types "application/tlsrpt\\+gzip")
  (add-to-list 'mm-automatic-display "application/tlsrpt\\+gzip")
  (add-to-list 'mm-inline-media-tests '("application/tlsrpt\\+gzip" mm-inline-text identity))
  (add-to-list 'mm-inlined-types "application/tlsrpt\\+gzip")
#+end_src

To keep the "buttons" being displayed, also add:

#+begin_src emacs-lisp
  (add-to-list 'gnus-buttonized-mime-types "application/zip")
  (add-to-list 'gnus-buttonized-mime-types "application/tlsrpt\\+gzip")
#+end_src

* Server

<87a6yg5spv.fsf@tullinup.koldfront.dk>

  #+begin_src emacs-lisp
    (nnml "archive"
          (nnml-directory "~/Mail/archive")
          (nnml-active-file "~/Mail/archive/active")
          (nnml-get-new-mail nil)
          (nnml-inhibit-expiry t))
  #+end_src

  #+begin_src emacs-lisp
    (setq asjo-archive-method '(nnml "archive"
                                     (nnml-directory "~/Mail/archive")
                                     (nnml-active-file "~/Mail/archive/active")
                                     (nnml-get-new-mail nil)
                                     (nnir-search-engine notmuch)
                                     (nnml-inhibit-expiry t)))
    (setq gnus-message-archive-method asjo-archive-method)

    (setq gnus-refer-article-method
          ;; First try to load the article from your local newsserver or nnml
          '(current
            ;; Then try the archive (?):
            (list asjo-archive-method)
            ....

  #+end_src

** Lists

Usenet groups, from nntp.aioe.org:

  - alt.os.linux
  - alt.test    
  - alt.tv.survivor
  - alt.usage.english
  - rec.sport.boxing
  - rec.woodworking

and the following MLs, with Gmane:

  - gmane.comp.shells.zsh.user
  - gmane.comp.terminal-emulators.tmux.user
  - gmane.comp.video.ffmpeg.user
  - gmane.discuss
  - gmane.emacs.bugs
  - gmane.emacs.devel
  - gmane.emacs.gnus.general
  - gmane.emacs.gnus.user
  - gmane.emacs.help
  - gmane.emacs.orgmode
  - gmane.emacs.w3m
  - gmane.linux.debian.user
  - gmane.test

* Misc

,----[ C-h v gnus-list-identifiers RET ]
| gnus-list-identifiers is a variable defined in ‘gnus-sum.el’.
| Its value is nil
| 
| Documentation:
| Regexp that matches list identifiers to be removed from subject.
| This can also be a list of regexps.
`----

#+begin_src emacs-lisp
  (setq gnus-summary-line-format "%U%R%z%B%s -- %n\n")
  (setq gnus-sum-thread-tree-root "● ")
  (setq gnus-sum-thread-tree-single-leaf "`->")
#+end_src
