- [[https://www.h3c.com/en/Support/Resource_Center/EN/Switches/Catalog/S5560X/S5560X-EI/default.htm][Support - H3C S5560X-EI Switch Series- H3C]]
- [[https://downloadcdn.h3c.com/en/202201/05/20220105_6539258_H3C%20S5560X-EI%20Series%20Converged%20Gigabit%20Switches%20Datasheet_1084419_294549_0.pdf][1234 - 20220105_6539258_H3C S5560X-EI Series Converged Gigabit Switches Datasheet_1084419_294549_0.pdf]]
- [[https://www.h3c.com/en/Products_Technology/Enterprise_Products/Switches/Campus_Switches/H3C_S5560X-EI/][Products & Technology- H3C S5560X-EI Series Converged Gigabit Switches- H3C]]
- [[https://downloadcdn.h3c.com/en/201806/12/20180612_3528325_99-book_1086453_294551_0.pdf][20180612_3528325_99-book_1086453_294551_0.pdf]]
- [[http://www.h3c.com/en/Support/Resource_Center/HK/Switches/H3C_S5560X-EI_Switch_Series/H3C_S5560X-EI_Switch_Series/Technical_Documents/Installation/Installation_Guide/H3C_S5560X-EI_IG-6W105/201907/1212070_294551_0.htm][H3C S5560X-EI Switch Series Installation Guide-6W105 - 01-Text- H3C]]
- [[http://www.h3c.com/en/Support/Resource_Center/HK/Switches/H3C_S9800/H3C_S9800/Technical_Documents/Configure/Configuration_Guide/H3C_S9800_CG-Release_213x-6W101/02/][02-IRF Configuration Guide - - H3C]]
- [[https://www.h3c.com/en/d_201808/1102928_294551_0.htm][Support - 12-Management with Boot ROM- H3C]]

* Cheat sheet

Here are some of the most commonly used commands for managing H3C network switches:

show interfaces: This command displays information about the interfaces on the switch, including status, configuration, and statistics.

show running-config: This command displays the current configuration of the switch, including the configuration of interfaces, VLANs, and other settings.

configure terminal: This command enters configuration mode, allowing you to change the configuration of the switch.

interface [interface-name]: This command enters interface configuration mode, allowing you to change the configuration of a specific interface.

shutdown: This command disables an interface.

no shutdown: This command enables an interface.

vlan [vlan-id]: This command enters VLAN configuration mode, allowing you to configure the settings for a specific VLAN.

save: This command saves the current configuration to the switch's non-volatile memory (NVRAM).

copy running-config startup-config: This command saves the current running configuration to the startup configuration, so that it will be used when the switch is next rebooted.

These are just a few examples of the commands that you can use to manage H3C network switches. The exact commands and syntax will depend on the specific model and firmware version of the switch that you are using. Additionally, you can find more information on the command line interface (CLI) in the switch's documentation and user guide.

: <sw4-mr13.intr>system-view 

: [sw4-mr13.intr]interface Bridge-Aggregation 8

: [sw4-mr13.intr-Bridge-Aggregation8]display this 

: display current-configuration interface GigabitEthernet 1/0/17
