#+TITLE:

* Перестройка
Перестройка - масштабные перемены в идеологии, экономической и
политической жизни СССР во второй половине 1980-х годов.
** Целью реформ
была всесторонняя демократизация сложившегося в СССР
общественно-политического и экономического строя.
* Footnotes
** [2017-01-27 Fri 14:52] [[https://groups.google.com/forum/#!searchin/leti-user/%25D0%25BC%25D0%25B5%25D1%2582%25D0%25BE%25D0%25B4%25D0%25B8%25D1%2587%25D0%25BA%25D0%25B0%257Csort:relevance/leti-user/4erMEbFfXJo/Wa4d4wLiAgAJ][Fwd: ИСТОРИЯ / ЗАОЧНАЯ ГРУППА 6005 / студент ПОЛЯКОВ ИВАН СЕРГЕЕВИЧ / Контрольная работа ОБНОВЛЕННАЯ / вариант 1 - Google Groups]]
 #+BEGIN_QUOTE
 17.01.2017, 23:38, "Кафедра ИКГП" <ikgp_etu@mail.ru>:

 Принято
 Вот вам методичка
 #+END_QUOTE
** Videos
*** TODO [2017-01-27 Fri 13:56] [[https://www.youtube.com/watch?v=sy9pohFi3oQ&index=30&list=PLHu93aj7YZS7qGLm3fd0i5ddsp7Vnn2Lc][История России XX века. Фильм 30 "Брестский мир" - YouTube]]
 #+BEGIN_QUOTE
 Published on Jun 6, 2016
 Фильм рассказываете том, кто стал главным технологом построения советской власти, в чьих руках после октября 1917 года оказалась страна. Авторы затрагивают тему подписания Брестского мира, повествуя о том, почему этот мир был так нужен Германии. В центре внимания создателей картины - причины геноцида русского народа, который начался сразу после свершения Великого Октября.
 #+END_QUOTE
*** [2017-01-26 Thu 05:10] [[https://www.youtube.com/watch?v=hcVlvN37vOs&index=23&list=PLHu93aj7YZS7qGLm3fd0i5ddsp7Vnn2Lc][История России XX века. Фильм 23 "Распутин" - YouTube]]
 #+BEGIN_QUOTE
 Published on Jun 6, 2016
 Авторы развенчивают миф о Распутине как о человеке, установившем контроль над Царской семьей. В фильме высказывается точка зрения, что убийство Распутина было организовано английскими спецслужбами

 #+END_QUOTE
*** [2017-01-26 Thu 04:16] [[https://www.youtube.com/watch?v=NdDZPht8F3k&index=14&list=PLHu93aj7YZS7qGLm3fd0i5ddsp7Vnn2Lc][История России XX века. Фильм 14 "Август 1914 года. Западный фронт" - YouTube]]
 #+BEGIN_QUOTE
 Published on Jun 6, 2016
 Немецкие зверства в Бельгии - неизвестная в России страница Первой мировой войны. Почему Русский царь при всем желании не мог предотвратить войну, даже ценой предательства братьев сербов. Зачем Россия вступила в войну, не дождавшись окончания мобилизации

 #+END_QUOTE
