* INBOX
** [2017-09-15 Fri 01:47] [[gnus:INBOX#87y3pqtvze.fsf@gnu.org][Email from Ludovic Courtès: “Code Staging in GNU Guix”]] by [[mailto:ludovic.courtes@inria.fr][Ludovic Courtès]]

- https://hal.inria.fr/hal-01580582/en
- https://conf.researchr.org/home/gpce-2017
- https://lists.gnu.org/archive/html/guix-devel/2017-07/msg00181.html

** [2017-09-15 Fri 11:33] [[gnus:INBOX#87d16xdway.fsf@gmail.com][Email from Maxim Cournoyer: Re: My experiences with GuixSD]] by [[mailto:maxim.cournoyer@gmail.com][Maxim Cournoyer]]

   What greatly improved the font rendering on my side was to create a
   ~/.config/fontconfig/fonts.conf containing the following:

** [2017-09-15 Fri 11:34] [[gnus:INBOX#87d16xdway.fsf@gmail.com][Email from Maxim Cournoyer: Re: My experiences with GuixSD]] by [[mailto:maxim.cournoyer@gmail.com][Maxim Cournoyer]]

   What greatly improved the font rendering on my side was to create a
   ~/.config/fontconfig/fonts.conf containing the following:

   #+BEGIN_EXAMPLE
     <?xml version="1.0"?>
     <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
     <fontconfig>
     <match target="font">
       <edit mode="assign" name="hinting" >
         <bool>true</bool>
       </edit>
     </match>
     <match target="font" >
       <edit mode="assign" name="autohint" >
         <bool>true</bool>
       </edit>
     </match>
     <match target="font">
       <edit mode="assign" name="hintstyle" >
         <const>hintfull</const>
       </edit>
     </match>
     <match target="font">
       <edit mode="assign" name="rgba" >
         <const>rgb</const>
       </edit>
     </match>
     <match target="font">
       <edit mode="assign" name="antialias" >
         <bool>true</bool>
       </edit>
     </match>
     <match target="font">
       <edit mode="assign" name="lcdfilter">
         <const>lcddefault</const>
       </edit>
     </match>
     <match target="pattern">
       <edit name="dpi" mode="assign"><double>92</double></edit>
     </match>
     <alias>
       <family>monospace</family>
       <prefer><family>Hack</family></prefer>
     </alias>
     <alias>
       <family>fixed</family>
       <prefer><family>Hack</family></prefer>
     </alias> 
     </fontconfig>
   #+END_EXAMPLE

** [2017-09-15 Fri 21:32] [[gnus:INBOX#86fubtkatd.fsf@zoho.com][Email from Emanuel Berg: Re: dired local ignore file ex]] by [[mailto:moasen@zoho.com][Emanuel Berg]]

   #+BEGIN_SRC emacs-lisp
     (setq completion-ignored-extensions
           (nconc completion-ignored-extensions (list ".bcf" ".run.xml")))
   #+END_SRC

** [2017-09-15 Fri 22:10] [[gnus:INBOX#a6e1d6254c16421fef857bf8dbb208a2@hypermove.net][Email from Amirouche Boubekki: Guile in the browser {Was: Sum]] by [[mailto:amirouche@hypermove.net][Amirouche Boubekki]]

** [2017-09-15 Fri 23:28] [[gnus:INBOX#E1dsOqu-00038a-T9@crmserver1p.fsf.org][Email from Richard Stallman: Why hackathons should insist o]] by [[mailto:info@fsf.org][Richard Stallman]]

- https://www.gnu.org/philosophy/hackathons.html
- https://www.gnu.org/philosophy/free-sw.html
- https://www.gnu.org/philosophy/free-hardware-designs.html
- https://www.gnu.org/philosophy/free-software-even-more-important.html
- https://www.beyondhackathon.com/en
- http://www.hackathon.io/rbc-digital
- https://expediaconnectivity.com/blog#madrid-hackathon-winners
- https://www.gnu.org/licenses/license-list.html
- https://www.gnu.org/philosophy/open-source-misses-the-point.html
- https://www.gnu.org/education/edu-schools.html
- https://status.fsf.org/fsf
- https://fsf.org/blogs/RSS
- https://www.fsf.org/jf
- https://my.fsf.org/civicrm/mailing/unsubscribe?reset=1&jid=153744&qid=27942913&h=25897b414aa3112c
- https://my.fsf.org/civicrm/mailing/optout?reset=1&jid=153744&qid=27942913&h=25897b414aa3112c

** [[gnus:INBOX#E1dtjUd-0006B5-SG@fencepost.gnu.org][Email from Richard Stallman: Re: JSON/YAML/TOML/etc. parsin]] by [[mailto:rms@gnu.org][Richard Stallman]]

   Yes it can be, but please avoid the term "MIT license".  There are
   two different licenses people sometimes call by that term, the X11
   license and the Expat license.  See
   https://gnu.org/licenses/license-list.html.

   Both of them are weak licenses -- we also call them "pushover"
   licenses -- since they permit inclusion in nonfree software.

   Please don't associate them with the name of MIT, as the
   association tends to promote them.

** [[gnus:INBOX#20170920061156.ed6ybieloxxvvs42@abyayala][Email from ng0: Re: Adopt a patch!]] by [[mailto:ng0@infotropique.org][ng0]]

   https://www.youtube.com/watch?v=KJ9Y0midtW4&feature=youtu.be
   http://blog.ffwll.ch/2017/01/maintainers-dont-scale.html
   http://blog.ffwll.ch/slides/lca-2017.pdf
   https://www.linux.conf.au/schedule/presentation/57/

   There's also some interesting links in there aswell.

   There are some more recent post of this maintainer
   at http://blog.ffwll.ch/

* Bug report
** Send an email about guix.scm failed to get a gcc in environment 08.03.18

* Email
** [2017-10-06 Fri 07:46] [[gnus:INBOX#87h8vd4p38.fsf@gnu.org][Email from Ludovic Courtès: Re: WIP gnu social package]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2017-10-06 Fri 07:47] [[gnus:INBOX#87fubazdn8.fsf@gmail.com][Email from Chris Marusich: Re: Should I upgrade root user]] by [[mailto:cmmarusich@gmail.com][Chris Marusich]]
** [2017-10-06 Fri 07:48] [[gnus:INBOX#87a82c7vmf.fsf_-_@escafil][Email from Ian Dunn: Re: {ELPA} New package: Captai]] by [[mailto:dunni@gnu.org][Ian Dunn]]
** [2017-10-09 Mon 19:56] [[gnus:INBOX#20170918215906.2c32b61d@cbaines.net][Email from Christopher Baines: Building things other than Gui]] by [[mailto:mail@cbaines.net][Christopher Baines]]
** [2017-11-03 Fri 19:50] [[gnus:nndoc+ephemeral:bug#29137#CAJ=RwfZbfzsg-TrFQkU48E6Mza0+PWDhTokGdzK9sXAReC7Ukw@mail.gmail.com][Email from David Thompson: Re: Interactive programming wi]] by [[mailto:dthompson2@worcester.edu][David Thompson]]

 #+BEGIN_SRC scheme
   (use-modules (chickadee)
                (chickadee math vector)
                (chickadee render sprite)
                (chickadee render texture)
                (system repl coop-server))

   (define sprite #f)
   (define repl #f)

   (define (load)
     (set! sprite (load-image "images/chickadee.png"))
     (set! repl (spawn-coop-repl-server)))

   (define (draw alpha)
     (draw-sprite sprite (vec2 256.0 176.0)))

   (define (update dt)
     (poll-coop-repl-server repl))

   (add-hook! load-hook load)
   (add-hook! update-hook update)
   (add-hook! draw-hook draw)
   (add-hook! quit-hook abort-game)

   (run-game)
 #+END_SRC
** Libpurple Bitlbee [[gnus:INBOX#20171004080427.13668-1-sleep_walker@gnu.org][Email from Tomáš Čech: {bug#28698} {PATCH} gnu: Enabl]] by [[mailto:sleep_walker@gnu.org][Tomáš Čech]]
** [2017-11-14 Tue 00:57] [[gnus:INBOX#87vak1l11m.fsf@nicolasgoaziou.fr][Email from Nicolas Goaziou: Re: {O} function for inserting]] by [[mailto:mail@nicolasgoaziou.fr][Nicolas Goaziou]]
** Replicant FOSDEM 2017

   - [[gnus:INBOX#1510570651.1176.2.camel@paulk.fr][Email from Paul Kocialkowski: {Replicant} FOSDEM Hardware En]] by
     [[mailto:contact@paulk.fr][Paul Kocialkowski]]
** [2017-11-18 Sat 21:40] [[gnus:nndoc%2Bephemeral:bug#27271#fake%2Bnone%2Bnndoc%2Bephemeral:bug#27271%2B1][Email from bug: Status: {PATCH 0/4} Catch collisions]] by [[mailto:27271@debbugs.gnu.org][bug]]
** Emacs with athena graphical toolkit

   [[gnus:INBOX#87po8gwjpk.fsf@gmail.com][Email from Mekeor Melire: Re: error running emacs instal]] by [[mailto:mekeor.melire@gmail.com][Mekeor Melire]]

   #+BEGIN_SRC scheme
     (define-public own-emacs
       (package
         (inherit emacs)
         (name "emacs")
         (synopsis "The extensible, customizable, self-documenting text editor
         with athena toolkit" )
         (build-system gnu-build-system)
         (inputs `(
                   ("inotify-tools" ,inotify-tools)
                   ("libxaw" ,libxaw)
                   ,@(alist-delete "gtk+" (package-inputs emacs))))
         (arguments `(
                      #:configure-flags '("--with-x-toolkit=athena")
                                        ,@(package-arguments emacs)))))
   #+END_SRC
** TODO GitHub highlight-escape-sequences
   [2017-11-19 Sun 01:10] [[gnus:INBOX#dgutov/highlight-escape-sequences/issues/6/345467554@github.com][Email from Dmitry Gutov: Re: {dgutov/highlight-escape-s]] by [[mailto:notifications@github.com][Dmitry Gutov]]
** [2017-11-28 Tue 19:59] [[gnus:INBOX#20171128124143.3vvpsxzuhchuztqz@abyayala][Email from ng0@n0.is: bug#24279: XTerm menu doesn't]] by [[mailto:ng0@n0.is][ng0]]
** [2017-11-29 Wed 06:17] [[gnus:nndoc+ephemeral:bug#24279#87shcyj2n9.fsf@gmail.com][Email to John Darrington: bug#24279: Bug in xterm and/or]] by [[mailto:go.wigust@gmail.com][Oleg Pykhalov]]
** [2017-12-01 Fri 10:54] [[gnus:INBOX#877eu73dhv.fsf@gnu.org][Email from Ludovic Courtès: Re: isc-bind service draft]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2017-12-01 Fri 11:02] [[gnus:INBOX#87shcxqble.fsf@gnu.org][Email from Ludovic Courtès: Re: bug#29106: Build loop afte]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2017-12-04 Mon 13:41] [[gnus:INBOX#87h8t6rhip.fsf@gnu.org][Email from Ludovic Courtès: Re: fcgiwrap doesn't see gzip]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2017-12-12 Tue 17:26] [[gnus:INBOX#922234369.95863@mta02.estisrapid.pro][Email from Светлана Бычкова: {Японский язык} Онлайн-урок 14 декабря]] by [[mailto:mail@tensaigakkou.ru][Светлана Бычкова]]
** [2017-12-12 Tue 18:57] [[gnus:INBOX#c2098c8f-7d0e-5067-abf5-02fd776878f7@gmail.com][Email from Manolis Ragkousis: Guix on FOSDEM 2018]] by [[mailto:manolis837@gmail.com][Manolis Ragkousis]]
** [2017-12-13 Wed 05:05] [[gnus:INBOX#20171202172327.0db2d98b@uwaterloo.ca][Email from Andy Patterson: {bug#29540} {PATCH} gnu: spice opengl acceleration]] by [[mailto:ajpatter@uwaterloo.ca][Andy Patterson]]
** [2017-12-13 Wed 05:21] [[gnus:INBOX#922234369.95863@mta02.estisrapid.pro][Email from Светлана Бычкова: {Японский язык} Онлайн-урок то]] by [[mailto:mail@tensaigakkou.ru][Светлана Бычкова]]
** [2017-12-18 Mon 01:55] [[gnus:INBOX#87shc9tp1i.fsf@cbaines.net][Email from Christopher Baines: {bug#27438} {PATCH} vendor gems install in system]] by [[mailto:mail@cbaines.net][Christopher Baines]]
** [2017-12-18 Mon 01:58] [[gnus:INBOX#E1eKiIe-0002ZC-Ex@duik.vrijschrift.org][Email from Translation Project Robot: New French PO file for 'guix']] by [[mailto:robot@translationproject.org][Translation Project Robot]]
** [2017-12-18 Mon 02:26] [[gnus:nndoc+ephemeral:bug#28659#87r2uih3lx.fsf@gmail.com][Email from Maxim Cournoyer: bug#28659: v0.13: guix pull github arhives non determenistic]] by [[mailto:maxim.cournoyer@gmail.com][Maxim Cournoyer]]
** [2017-12-20 Wed 19:22] [[gnus:INBOX#877etkxufy.fsf@gnu.org][Email from Ludovic Courtès: Re: Dualbooting with guixsd no]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2018-01-06 Sat 03:24] [[gnus:INBOX#20180105170034.6243-1-ludo@gnu.org][Email from Ludovic Courtès: {bug#29995} {PATCH 0/5} Publish build logs]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2018-01-06 Sat 22:25] [[gnus:INBOX#20171216201700.23564-1-mail@cbaines.net][Email from Christopher Baines: {bug#29741} {PATCH 1/2} gnu: httpd]] by [[mailto:mail@cbaines.net][Christopher Baines]]
** [2018-01-06 Sat 23:03] [[gnus:INBOX#87r2sg3qxx.fsf@gnu.org][Email from Ludovic Courtès: bug#29255: "Profile collision]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2018-01-06 Sat 23:04] [[gnus:INBOX#87y3lretyh.fsf@gmail.com][Email from Alex Kost: {bug#29582} {PATCH} emacs- prerfix]] by [[mailto:alezost@gmail.com][Alex Kost]]
** [[gnus:INBOX#87vag2wopo.fsf@gnu.org][Email from Mike Gerwitz: Running IceCat in a container]] by [[mailto:mtg@gnu.org][Mike Gerwitz]]

   #+BEGIN_SRC sh
   guix environment \
        --container \
        --network \
        -r "$gc_root" \
        --share=/tmp/.X11-unix/ \
        --expose=/etc/machine-id \
        --share=$HOME/.mozilla/ \
        --share=$HOME/.cache/mozilla/ \
        --share=$HOME/.Xauthority \
        --share=$HOME/Downloads/icecat-container/=$HOME/Downloads/ \
        --ad-hoc icecat coreutils
        -- \
        env DISPLAY="$DISPLAY" icecat "$@"
   #+END_SRC
** TODO [2018-01-16 Tue 11:47] [[gnus:INBOX#87shbbqiq5.fsf@gnu.org][Email from Ludovic Courtès: Re: {bug#30084} {PATCH} gnu: Add urho3d.]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2018-01-21 Sun 19:42] [[gnus:INBOX#20171211173102.6279-1-tomi.ollila@iki.fi][Email from Tomi Ollila: {PATCH} make notmuch release archive reproducible]] by [[mailto:tomi.ollila@iki.fi][Tomi Ollila]]
** [2018-02-04 Sun 15:05] [[gnus:INBOX#87bmh5o8ux.fsf@librem.i-did-not-set--mail-host-address--so-tickle-me][Email from Alex ter Weele: Defining shepherd user service]] by [[mailto:alex.ter.weele@gmail.com][Alex ter Weele]]
** [2018-02-06 Tue 07:12] [[gnus:INBOX#878tckvfro.fsf@mdc-berlin.de][Email from Ricardo Wurmus: Re: {PATCH} Add SELinux policy for guix-daemon.]] by [[mailto:ricardo.wurmus@mdc-berlin.de][Ricardo Wurmus]]

   https://people.redhat.com/duffy/selinux/selinux-coloring-book_A4-Stapled.pdf

   But I *really* don’t recommend it for learning SELinux.  Half of
   the book doesn’t even apply to common SELinux installations, and
   the bit that *does* apply really isn’t thorough enough.  All I
   took away from it was that a dog shouldn’t eat cat food (and
   that’s enforced by an angry penguin).
** [2018-02-06 Tue 12:30] Maybe a Guix substitute server [[gnus:INBOX#20180204204945.GA2228@jurong][Email from Andreas Enge: Re: Redhill is back!]] by [[mailto:andreas@enge.fr][Andreas Enge]]

   after switching internet providers, I brought redhill back online
   under its new IP address. Testing the offload shows no problems
   (with a changed machines.scm that contains only redhill):
   hydra@20121227-hydra:~/maintenance$ guix offload test machines.scm
   guix offload: testing 1 build machines defined in 'machines.scm'...
   guix offload: 'redhill.guixsd.org' is running guile (GNU Guile)
   2.2.2 guix offload: Guix is usable on 'redhill.guixsd.org' (test
   returned "/gnu/store/883yjkl46dxw9mzykykmbs0yzwyxm17z-test")
   sending 1 store item to 'redhill.guixsd.org'...  exporting path
   `/gnu/store/ciq39nchn8pd4k4m1vgivmrmf6c5rg3g-export-test' guix
   offload: 'redhill.guixsd.org' successfully imported
   '/gnu/store/ciq39nchn8pd4k4m1vgivmrmf6c5rg3g-export-test'
   retrieving 1 store item from 'redhill.guixsd.org'...  guix offload:
   successfully imported
   '/gnu/store/8a1509iirfaibm19ysc2ywg89vrz6v1r-import-test' from
   'redhill.guixsd.org'
** Emacs generate user dictionary from bunch of files
   [[gnus:nnimap+USER:INBOX#877eu3bkv7.fsf@gnu.org][Email from Ian Dunn: {ELPA} New package: paced]] by [[mailto:dunni@gnu.org][Ian Dunn]]

   I'd like to submit paced[1] to ELPA.

   Paced (Predictive Abbreviation Completion and Expansion using Dictionaries)
   scans a group of files (determined by "population commands") to construct a
   usage table (dictionary).  Words (or symbols) are sorted by their usage, and may
   be later presented to the user for completion.  A dictionary can then be saved
   to a file, to be loaded later.

   Population commands determine how a dictionary should be filled with words or
   symbols.  A dictionary may have multiple population commands, and population may
   be performed asynchronously.  Once population is finished, the contents are
   sorted, with more commonly used words at the front.  Dictionaries may be edited
   through EIEIO's customize-object interface.

   Completion is done through `completion-at-point'.  The dictionary to use for
   completion can be customized.

   The code is on Bazaar on Savannah:

   bzr branch https://bzr.savannah.gnu.org/r/paced-el/ paced

   [1] http://nongnu.org/paced-el
** [2018-02-10 Sat 21:28] [[gnus:INBOX#87h8qshkdf.fsf@gmx.us][Email from rasmus@gmx.us: Re: {O} Prompt org-capture for buffer?]] by mailto:rasmus@gmx.us
   #+BEGIN_SRC emacs-lisp
     (file+function "~/doc.org"
                    (lambda ()
                      (org-goto-local-search-headings
                       (ido-completing-read
                        "File note to: "
                        (org-element-map
                            (org-element-parse-buffer)
                            'headline
                          (lambda (hl)
                            (and (= (org-element-property :level hl) 1)
                                 (org-element-property :title hl)))))
                       nil nil)
                      (forward-line 1))
                    :prepend t
                    :empty-lines-after 1)


   #+END_SRC
** [2018-02-11 Sun 11:05] [[gnus:INBOX#878tc13hnq.fsf@hyperbola.info][Email from Adonay Felipe Nogueira: Re: {O} do you need a separate LaTeX installation to export org mode files to pdf?]] by [[mailto:adfeno@hyperbola.info][Adonay Felipe Nogueira]]

   I have also been writing a guide for Org mode and LaTeX for
   researchers and writers, it's currently in Brazilian Portuguese and
   isn't as broad as the info page in GNU Emacs itself, see [1]. Also,
   [2] has a more advanced example of a work being done using (mostly)
   Org mode but also LaTeX, BibTeX, TikZ and abnTeX2.

   [1] <https://notabug.org/adfeno/Org_LaTeX_intro>.
   [2] <https://notabug.org/adfeno/Trabalho_sobre_gestao_universitaria>.
** [2018-02-14 Wed 14:12] [[gnus:nnimap+USER:INBOX#87h8qvivyv.fsf@gnu.org][Email from Ludovic Courtès: Re: Can we speed it up? Prev: compiling guix is too slow?]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]

 Pjotr Prins <pjotr.public12@thebird.nl> skribis:

 > What will it be like with 15K packages? We will get there. We can
 > actually try it now by doubling the package tree - anyone wants to try
 > and create a simulation? I.e., not just double the tree, make sure
 > there are cross references between the two graphs by modifying some of
 > the inputs at random.
 >
 > This leads to the following thought: why don't we create a 'lazy'
 > build. There are multiple ways to go about it (I think). One would be
 > to parse scheme files for package names and only compile those that
 > are needed when someone invokes a guix command (and have not been
 > compiled yet). Or generate a meta list for a source tree.

 Note that there are several things we could do:

   • Not compile gnu/packages/*.scm at all and instead turn on Guile’s
     auto-compilation.  As things are currently, the first ‘guix package’
     invocation would take ages though.

   • Never compile gnu/packages/*.scm and instead interpret it, though
     that’s currently relatively slow and probably more memory-consuming.

 I think with ‘wip-pull-reload’ (I’ll resume work on it, I promise!)
 things should already be nicer, and then, we should keep improving the
 compiler (Andy already significantly improved CPU consumption in Guile
 2.2.3).
** [2018-02-14 Wed 15:33] [[gnus:INBOX#20180203093626.6c927477@alma-ubu][Email from Björn Höfling: bug#30107: How I got the core dump]] by [[mailto:bjoern.hoefling@bjoernhoefling.de][Björn Höfling]]
   #+BEGIN_QUOTE
   On request, I'm writing here how I got to that coredump.
   #+END_QUOTE
** [2018-03-02 Fri 07:00] [[gnus:INBOX#20180301230003.C0FE514A713@mrelay-bulk1.hh.ru][Email from hh ru: Подходящие вакансии]] by [[mailto:no_reply@hh.ru][hh ru]]
** [2018-03-06 Tue 11:20] [[gnus:INBOX#87sh9iegbl.fsf@gnu.org][Email from Ludovic Courtès: Re: Reinstall GuixSD from another distribution with chroot (Recover Grub)]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2018-03-07 Wed 13:49] [[gnus:INBOX#20180208171243.dnligzfvwsxvc4l3@floriannotebook][Email from pelzflorian@pelzflorian.de: Re: Haunt patches: Introduce page variants for translations]] by [[mailto:pelzflorian@pelzflorian.de][pelzflorian]]
** TODO [2018-03-07 Wed 17:30] [[gnus:INBOX#87tvtsrnpv.fsf@gnu.org][Email from Ludovic Courtès: Re: {bug#29733} Add virtaal (translation app)]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2018-03-07 Wed 17:31] [[gnus:INBOX#20180307124601.fjjvtkjw4ppcqxxk@abyayala][Email from ng0@n0.is: Re: torbrowser]] by [[mailto:ng0@n0.is][ng0]]
** [2018-03-07 Wed 17:45] [[gnus:INBOX#87eflzfkwh.fsf@cbaines.net][Email from Christopher Baines: Package input loop detection]] by [[mailto:mail@cbaines.net][Christopher Baines]]
** [2018-03-07 Wed 18:05] [[gnus:INBOX#20180216114753.0cd0d28b@mykolab.com][Email from Rutger Helling: Graphically isolating Guix containers with Xpra.]] by [[mailto:rhelling@mykolab.com][Rutger Helling]]
** [2018-03-07 Wed 18:19] [[gnus:INBOX#20180226181914.18955-1-mbakke@fastmail.com][Email from Marius Bakke: {bug#28004} {PATCH} gnu: Add chromium.]] by [[mailto:mbakke@fastmail.com][Marius Bakke]]
** [2018-03-08 Thu 01:04] [[gnus:INBOX#87y3j4l3xj.fsf@mdc-berlin.de][Email from Ricardo Wurmus: installing python 2 and python 3 in the same profile]] by [[mailto:ricardo.wurmus@mdc-berlin.de][Ricardo Wurmus]]
** [2018-03-09 Fri 12:09] [[gnus:INBOX#CAFyQvY2U_rLCyj=jPUS20fByvAqmF1Pq3b9m3r=Nett6WPw9Vw@mail.gmail.com][Email from Kaushal Modi: Re: Teaching emacsclient to act as a pager, and more]] by [[mailto:kaushal.modi@gmail.com][Kaushal Modi]]
** [2018-03-10 Sat 13:18] [[gnus:INBOX#c275dcbc-18bf-16bd-54d1-da9d1031719b@gmail.com][Email from Matt Wette: {ANN} Nyacc version 0.83.0 released]] by [[mailto:matt.wette@gmail.com][Matt Wette]]
** [2018-03-10 Sat 13:20] [[gnus:INBOX#87fu6o2ge2.fsf@gmail.com][Email from Maxim Cournoyer: bug#30290: guix-daemon slows to a crawl when a substitute server is offline]] by [[mailto:maxim.cournoyer@gmail.com][Maxim Cournoyer]]
