https://xakep.ru/2011/01/13/54477/

* Inotify-tools

Кроме Incron есть еще полезная штука, использующая inotify — inotify-tools, включающая в себя inotifywait и inotifywatch, которые очень удобно использовать в скриптах. Inotifywait просто ждет указанных событий над указанными файлами и завершается с тем или иным кодом возврата. Немного модифицированный скрипт из man'а, хорошо иллюстрирующий предназначение inotifywait:

$ cat ~/script.sh
while inotifywait -e modify \
/var/log/apache2/error.log;
do
tail -1 /var/log/apache2/error.log | \
notify-send "Apache needs love!"
done

Inotifywatch просто собирает статистику по обращению к определенному файлу/каталогу в течение определенного времени или до прерывания и отображает ее в виде таблицы. Есть возможность сбора статистики только по определенным событиям, задания исключения файлов по маске и чтения списка объектов для мониторинга из файла.

* Inotify: мониторинг событий

С помощью strace можно отследить, к каким файлам обращалось конкретное приложение. Но иногда возникает обратная задача — отследить обращения к определенному файлу и выполнить какието действия при этих обращениях. Тогда на помощь придет механизм inotify. Inotify — подсистема ядра, позволяющая отслеживать файловые операции. Технология проверена временем — она была включена еще в ядро 2.6.13 (июнь 2005). Inotify активно используется, например, десктопными поисковиками (вроде Beagle), а также такой полезной штукой, как incron.

Incron — аналог обычного cron с той лишь разницей, что выполнение команды происходит не по времени, а по наступлению указанного в задании события. После установки (incron есть в репозиториях большинства дистрибутивов) создается пустой файл /etc/incron.allow, в котором надо перечислить пользователей, которым разрешено использовать incron.
Создаются задания с помощью команды:

$ incrontab -e

Формат заданий:

<путь> <событие> <команда> (с разделением через пробел)

Самые интересные события

    IN_ACCESS — файл был прочитан
    IN_ATTRIB — изменились метаданные файла/каталога
    IN_MODIFY — файл был изменен
    IN_CREATE — файл или каталог был создан в отслеживаемой директории
    IN_DELETE — файл или каталог был удален в отслеживаемой директории
    IN_DELETE_SELF — отслеживаемый файл или каталог был удален
    IN_MOVE — файл был перемещен из отслеживаемого каталога или в него
    IN_ALL_EVENTS — все события

В описании команды можно использовать внутренние переменные. Самые полезные:

    $@ — полное имя отслеживаемого файла/каталога
    $# — относительное имя файла, вызвавшего событие (только при мониторинге каталога)
    $% — название события
