:PROPERTIES:
:ID:       58fafa35-7cfa-4a4e-a703-153d03a386c6
:END:
To get LAN mode: ipmitool raw 0x30 0x70 0x0c 0.
To set LAN mode dedicated: ipmitool raw 0x30 0x70 0x0c 1 0.
To set LAN mode onboard/shared: ipmitool raw 0x30 0x70 0x0c 1 1.
To set LAN mode failover: ipmitool raw 0x30 0x70 0x0c 1 2.

- IPMI reset password to default (login is ADMIN)
  : ipmitool -I open lan set 1 password ADMIN

* ipmitool

[[https://habr.com/ru/post/263091/][HA-Cluster на основе Pacemaker под контейнерную виртуализацию LXC и Docker / Хабр]]

Сеть для ipmi желательно вынести в отдельный vlan, во первых это позволит её
изолировать, во вторых не будет проблем со связностью, если IPMI BMC
(baseboard management controller) разделяет сетевой интерфейс с сервером.

#+begin_example
  impitool> lan set 1 ipsrc static
  impitool> lan set 1 ipaddr 10.1.15.1
  impitool> lan set 1 netmask 255.255.255.0
  impitool> lan set 1 defgw ipaddr 10.1.15.254
  impitool> lan set 1 vlan id 314
  # настройка доступа:
  impitool> lan set 1 access on
  impitool> lan set 1 auth ADMIN MD5
  ipmitool> channel setaccess 1 2 callin=on ipmi=on link=on privilege=4
#+end_example

#+begin_example
  ipmitool -I lan -U admin -P 'очень секретный пароль' -H 10.1.15.1 bmc info
#+end_example

* Links
- [[https://github.com/DrSpeedy/ipmi_fancontrol-ng][DrSpeedy/ipmi_fancontrol-ng: IPMI Fan Control Daemon]]
- [[https://www.tzulo.com/crm/knowledgebase/47/IPMI-and-IPMITOOL-Cheat-sheet.html][IPMI & IPMITOOL Cheat sheet - Knowledgebase - tzulo, inc.]]

IPMI & IPMITOOL Cheat sheet

    156 

What is IPMI?

The Intelligent Platform Management Interface (IPMI) is a standardized computer system interface used by system administrators for out-of-band management of computer systems and monitoring of their operation. Out-of-band is also referred to as LOM (Lights-out management) involves the use of a dedicated management channel for device maintenance.
There are number of options available to manage the device remotely. There are vendor specific server management technologies available. HP’s Integrated Lights-out or iLO, Dell’s Dell Remote Access Controller or DRAC and IBM’s Remote supervisor adapter (RSA) are a few to list. The above listed modules are vendor specific and proprietary. IPMI whereas is vendor-neutral and cross-platform. It is available on Linux distros. The functionality of IPMI can be accessed via IPMItool. IPMItool is a simple command line utility which is used to manage IPMI-enabled devices. IPMItool enables you to manage system hardware components, monitor system health, and monitor and manage the system environment, independent of the operating system.

Cheat sheet

You can install IPMI and IPMItool via yum using the following command:

[root@anm ~]# yum install OpenIPMI OpenIPMI-tools

Make sure that the server is set to start during startup and start the IPMI service.

[root@anm ~]# chkconfig ipmi on 
[root@anm ~]# service ipmi start

We have here some IPMItool commands which can be used in day-to-day operations.

1. Man and help info for IPMItool

ipmitool help 
man ipmitool

2. To check firmware version

ipmitool mc info

3. To reset the management controller

ipmitool mc reset [ warm | cold ]

4. Show field-replaceable-unit details

ipmitool fru print

5. Show sensor output

ipmitool sdr list 
ipmitool sdr type list 
ipmitool sdr type Temperature 
ipmitool sdr type Fan 
ipmitool sdr type ‘Power Supply’

6. Chassis commands

ipmitool chassis status ipmitool chassis identify [] # turn on front panel identify light (default 15s) 
ipmitool [chassis] power soft # initiate a soft-shutdown via acpi 
ipmitool [chassis] power cycle # issue a hard power off, wait 1s, power on 
ipmitool [chassis] power off # issue a hard power off 
ipmitool [chassis] power on # issue a hard power on 
ipmitool [chassis] power reset # issue a hard reset

7. Modify boot device for next reboot

ipmitool chassis bootdev pxe 
ipmitool chassis bootdev cdrom 
ipmitool chassis bootdev bios

8. Logging

ipmitool sel info 
ipmitool sel list 
ipmitool sel elist # extended list (see manpage) 
ipmitool sel clear

9. For remote access, you need to setup user and network settings, either at boot time on the iLO or DRAC card itself, or from the OS via ipmitool: 
Display/reset password for default root user (userid ’2′)

ipmitool user list 1 
ipmitool user set password 2

10. Display/configure lan settings

ipmitool lan print 1
ipmitool lan set 1 ipsrc [ static | dhcp ] 
ipmitool lan set 1 ipaddr {YOUR DESIRED IP}
ipmitool lan set 1 netmask {YOUR NETMASK}
ipmitool lan set 1 defgw ipaddr 10.0.1.1

After configuring the lan settings you should be able to connect remotely using the ‘lan’ interface of IPMItool.
The following is an example:

[root@anm ~]# ipmitool -I lan -U root -H {YOUR DESIRED IP} chassis status

11. Hanging BMC

ipmitool bmc reset cold

12. Change system state

ipmitool -H <ip> -U <user> chassis power <status|on|off|cycle|reset>

13. Get debug info

ipmitool lan print
ipmitool -H <ip> -U <user> shell # get ipmitool shell, type 'help'
ipmitool -H <ip> -U <user> sel list # Show system event log
ipmitool -H <ip> -U <user> sdr # List sensor data

14. Get SOL console

modprobe lanplus # If not yet loaded
ipmitool -H <IP> -U <user> -I lanplus sol activate


Additional cheatsheet commands:


#list users
ipmitool -U <login> -P '<password>' -H <IP> user list

#delete user id
ipmitool -U <login> -P '<password>' -H <IP> user set name <id> ""


#add user

#user password
ipmitool -U <login> -P '<password>' -H <IP> ipmitool user set password <id> blah

#power status
ipmitool -U <login> -P '<password>' -H <IP> power status

#power off
ipmitool -U <login> -P '<password>' -H <IP> power off

#power on
ipmitool -U <login> -P '<password>' -H <IP> power on

#power reset
ipmitool -U <login> -P '<password>' -H <IP> power reset

* Cheat sheet

- host status
  : ipmipower --hostname=web16.ipmi.intr --username=ADMIN --password="$(pass show majordomo/public/ipmi/ADMIN)" --stat

- reboot
  : ipmipower --hostname=web16.ipmi.intr --username=ADMIN --password="$(pass show majordomo/public/ipmi/ADMIN)" --reset
  : ipmitool -I lanplus -H web16.ipmi.intr -U ADMIN -P "$(pass show majordomo/public/ipmi/ADMIN)" power cycle 

- print networking information
  : ipmitool -H web16.ipmi.intr -U ADMIN -P "$(pass show majordomo/public/ipmi/ADMIN)" lan print

- [[https://galaxydata.ru/community/ipmi-sbros-parolya-i-prochee-x8dtu-f-supermicro-188][IPMI сброс пароля и прочее x8dtu-f supermicro - GalaxyData Community]]

* Tools
- [[https://github.com/kontron/python-ipmi][kontron/python-ipmi: A pure python IPMI library]]
- [[https://github.com/yinheli/ipmi-fan-control][yinheli/ipmi-fan-control: A tool to control the fan speed by monitoring the temperature of CPU via IPMI.]]

* [[https://gist.github.com/egernst/66febb5b95a1d303881db05c926e0b63][ipmi serial over lan sol]]
#+begin_src markdown
  ## Pre-requisites

  Install IPMItools using your package manager on laptop and target machine. Load the drivers on the target.

  ```bash
  modprobe ipmi_devintf
  modprobe ipmi_si
  ```

  If you see the following, drivers are not loaded.

  ```
  Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
  ```

  ## IPMI setup

  On the target machine run below commands to setup access - 

  ```bash
  ipmitool lan print 1
  ipmitool lan set 1 ipsrc dhcp
  ipmitool lan print 1
  ```

  Make a note of the IP address from the above output. This will be used to connect from your laptop

  ```bash
  ipmitool user list 1
  ipmitool user set name 3 rockstar
  ipmitool user set password 3
  ```

  You'll get a password prompt. Set the password. `whatcouldgowrong` in our example. Next -

  ```bash
  ipmitool channel setaccess 1 3 link=on ipmi=on callin=on privilege=4
  ipmitool user enable 3
  ipmitool user list 1
  ``` 

  Now from your laptop you can execute commands, like so

  ```bash
  ipmitool -I lanplus -U rockstar -P whatcouldgowrong -H <IP address> chassis power (on|off|status)
  ```

  ## SOL setup

  Enable SOL for root and above user. Enable SOL.

  ```bash
  ipmitool sol payload enable 1 2
  ipmitool sol payload enable 1 3
  ipmitool sol set enabled true 
  # try the below command even if this command fails.
  ```

  Check links 2 and 5 for BIOS and OS configurations necessary.
  In the BIOS, you can also set DHCP hostname for the BMC, frees you from tracking IP addresses.
  To access the SOL console, on your local machine use the activate option as shown.
  Check SOL session help by typing this `~?`. To kill a hung SOL session use deactivate.

  ```bash
  ipmitool -I lanplus -U rockstar -P whatcouldgowrong -H <IP address> sol (activate|deactivate)
  ```

  If everything works you will be able to remotely access the target machine's console and make selections in grub menu, etc.,
  My NixOS config settings that worked

  ```text
  # Use the GRUB 2 boot loader.
  boot = {
   loader.grub = {
   ...
   extraConfig = "serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1; terminal_input serial; terminal_output serial";
   };
  kernelModules=["lanplus" ... ];
  }
  boot.kernelParams = [
   ...
  "console=tty0" "console=ttyS0,115200n8"
  ];
  systemd.services."serial-getty@ttyS0".wantedBy = [ "multi-user.target" ];
  ```

  ## Appendix
  1. http://www.openfusion.net/linux/ipmi_on_centos
  2. http://tech.sid3windr.be/2016/02/configuring-ipmi-serial-over-lan-on-debian-8-jessie/
  3. https://discuss.pivotal.io/hc/en-us/articles/206396927-How-to-work-on-IPMI-and-IPMITOOL
  4. https://wiki.hetzner.de/index.php/IPMI/en
  5. http://wiki.drewhess.com/wiki/IPMI_and_SOL_on_an_Intel_S3200SHV
#+end_src

https://gist.github.com/egernst/66febb5b95a1d303881db05c926e0b63?permalink_comment_id=4189594#gistcomment-4189594
#+begin_src markdown
  For whoever next stumbles upon this, I also had to set

  admin sol set non-volatile-bit-rate 115.2
  admin sol set volatile-bit-rate 115.2

  BIOS settings (Asrock E3C236D2I) were apparently misleading
#+end_src
