#+TITLE: Самостоятельная работа по истории IX-XIX веков 1 вариант
#+AUTHOR: Студент группы № 6005 Пыхалов Олег Витальевич
#+EMAIL: opykhalov@yandex.ru
#+OPTIONS: email:t

#+LANGUAGE: ru
#+LaTeX_HEADER: \usepackage[utf8]{inputenc}
#+LaTeX_HEADER: \usepackage[T1,T2A]{fontenc}
#+LaTeX_HEADER: \usepackage[english,russian]{babel}
#+LATEX_HEADER: \hypersetup{colorlinks, citecolor=black, filecolor=black, linkcolor=black, urlcolor=blue, pdfpagemode=FullScreen}

#+OPTIONS: H:2 toc:t num:t
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+LATEX_CLASS_OPTIONS: [aspectratio=169]
#+LATEX_HEADER: \beamertemplatenavigationsymbolsempty
#+BEAMER_THEME: default
#+BEAMER_COLOR_THEME: crane
#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt)

* Вопросы

** 1-й вопрос – Киевская Русь IX-XIII вв.

Роль варягов в образовании и развитии Древнерусского
государства. Норманнская проблема.

** 2-й вопрос – Московская Русь XIV-XVII вв.

Система отношений между Русью и Ордой в XIII-XV вв. и ее влияние на
развитие русских земель.

** 3-й вопрос – Российская империя XVIII-XIX вв.

Итоги и последствия петровских реформ. Оценка современников и
потомков.

* Роль варягов в образовании и развитии Древнерусского государства

** Объединение земель

Варяги способствовали объединению северной и южной Руси.

** Новые правители

Варяги дали новую правящую династию Рюриковичей в 862-1598 годах.

** Возможное происхождение название Руси

Предположительно название Русь происходит от варяжского племени Руси,
к которому принадлежал Рюрик.

* Норманнская проблема

** Создатели норманнской теории

Немецкие Ученые на руссийской Службе:
- Байер
- Миллер
- Шлёцер

** Норманнская теория

Государственность на Русь принесли варяги, приглашенные в 862 года на
княжение в Новгород. Варяжская династия Рюриковичей объединила
северную и южную Русь, создала систему сбора дани, управления и
судопроизводства на огромной территории.

** Антинорманская теория

Основатель -- Михаил Васильевич Ломоносов

Наиболее активные сторонники в 19 веке историки:
- Иличевский
- Беляев
- Забелин

Государственность на Руси существовала в виде локальных образований и
до середины 9 века восточные славяне смогли организовать себя сами,
без помощи варягов.

Современные историки говорят о наличие на Руси до 9 века трёх центров
государственности:
- Куяба
- Славия
- Артания

** Почему был приглашен варяг

- варяги были хорошими воинами
- у варягов уже был опыт в создании государства
- нейтральная фигура

Современные историки предполагают, что варяги пришли не по
приглашению, а как завоеватели и были не скандинавами, а славянами с
южных берегов Балтики.

* Система отношений в XIII-XV веках между Русью и Ордой

** Начало политической истории

Начало политической истории Золотой Орды относится к 1243 году, когда
Батый возвратился из похода в Европу.

В этом же году великий князь Ярослав первым из русских правителей
прибыл в ставку монгольского хана за ярлыком на княжение.

Монголы сохраняли местные династии, не размещали воинские гарнизоны,
не совершали гонений на церковь.

Князья были вассалами Батыя и его наследников.

Монголы использовали систему заложничества.

** Перепись населения и сбор дани

C 1257 по 1259 года производилась перепись русского населения для
сбора дани.

Главный вид дани, собиравшейся серебром, называется ордынский
выход. Всего было 14 видов дани, в том числе и дань кровью (юношей
забирали в монгольскую армию).

Сначала дань собирали баскаки, после восстаний - князья.

** Монгольское иго

Отношения Руси с Ордой приняли предсказуемые и устойчивые формы -
рождается явление, получившее название "монгольского ига".

При этом, однако, практика периодических карательных походов не
прекращалась до 14 века.

Многие русские князья подверглись террору и запугиванию с целью не
допустить с их стороны антиордынских выступлений.

** Православие

Деятельность православной епархии в Орде не прошла даром.

После 1318 года на Русь двинулся поток православных татар. Они в
большинстве своем принимались на военную службу к московскому князю,
находившемуся в союзе с православной церковью.

** Могущественные войны Москвы

Москва затмила могуществом другие княжества, получив в свою дружину
воинов, не имевших себе равных за счет совершенной боевой выучки и
особой воинской солидарности.

** Передача сбора дани

Уже в конце 13 века сбор дани Орда передала русским князьям, что
облегчало им возможности для финансового и политического
маневрирования.

Иван Калита и другие потомки Александра Невского продолжали проводить
политику "смиренной мудрости", постепенно накапливая предпосылки для
перелома в происходящем.

Золотая Орда разделилась на 2 части по Волге.

** Повторное завоевание Руси

С 1371 года дань более не выплачивалась Донским.

Мамаю необходимо было вновь завоевывать Русь.

Перелом произошел в 1380 году, когда на Куликовом поле московское
войско, вбирая в себя массы добровольцев из всех русских земель,
выступило против ордынского темника Мамая, поддержанного Литвой и
Генуей.

Значения: Руси удалось отстоять свои интересы, меняются отношения Орды
и Руси, на открытые сражения монголы не выходили, дань,
восстановленная после 1382, приобретает роль откупа, усиление
московского войска, идея объединения становится доминирующей.

** Распад

После присоединения Новгородской земли Московское княжество
превратилось в большое и сильное государство.

К этому времени Золотая Орда распалась.

От неё отделились Казанское, Астраханское, Крымское и Сибирское
ханства, жившие в постоянной вражде между собой.

** Разрыв отношений

Заключив союз с крымским ханом Менгли-Гиреем, Иван III начал
готовиться к разрыву с Ордой. В 1478 году Иван III в присутствии
московских бояр и ордынских послов разорвал и растоптал договор с
Ордой, заявив, что больше не будет подчиняться хану и платить
дань. Ханских послов выгнали из Москвы.

** После распада

Ордынское иго оказало мощное воздействие на ход русской истории.

Через 200 лет после создания ханом Батыем монгольского государства, оно
распалось на несколько составных:
- Большую Орду
- Астраханское
- Казанское
- Крымское
- Сибирское ханства
- Ногайскую Орду

В то же самое время Московская Русь напротив консолидировалась и
набирала мощь.

После распада Золотой Орды ее геополитическое наследство неизбежно
должно было перейти Руси.

* Влияние Орды на развитие русских земель

** Монгольское завоевание

Монгольское завоевание искусственно и резко прервало независимое
развитие русской государственности.

Не только оборвалось государственное развитие, но вся русская
государственная машина в княжествах, попавших под власть Золотой Орды,
была круто переориентирована Восток, в Азию.

** Изменение внешней политики

Изменилось существо русской внешней политики: из самостоятельной она
стала вассальной, из ориентированной на европейскую государственность
и культуру превращалась в приспособленческо-азиатскую, из базирующейся
на христианской психологии и понятиях начинала базироваться на
восточно-рабской психологии.

** Упадок экономии

Ордынское владычество привело к длительному упадку в экономическом,
политическом и культурном развитии русских земель, положило начало
отставанию их от передовых западноевропейских стран.

Запустели и пришли в упадок старые земледельческие центры и некогда
освоенные территории. Границы земледелия отодвинулись на
север.

** Разорение городов

Массовому разорению и уничтожению подверглись русские города, их роль
в политической и экономической жизни страны упала.

** Упадок развития производства

Исчезли навсегда или возродились лишь через 150-300 лет такие ремесла:
- скань
- чернь
- перегородчатая эмаль
- полихромная поливная керамика
- резьба по камню

Приостановилось каменное строительство.

Пришло в упадок изобразительное и прикладное искусство.

Ослабла связь городского ремесла с рынком.

Затормозилось развитие товарного производства.

** Прекращение денежного обращения

Дань “серебром” привела к утечке его в Орду и почти полному
прекращению денежного обращения внутри русских земель, что
обескровливало страну.

** Потери в битвах и рабство

Наконец, десятки тысяч людей погибли в битвах или были угнаны в
рабство в результате непрекращавшихся набегов монголо-татар на русские
земли.

** Крупные вторжения и набеги

Только за последнюю четверть ХIII в. было совершено 14 крупных
вторжений на Русь, не считая множества более мелких набегов.

** Разрушение важнейших городов

Неоднократное разрушение городов:
- Переславль-Залесский
- Муром
- Суздаль
- Рязань

** Период татарского владычества

Русь была под татарским владычеством 242 года.

Этот период ее истории ознаменовался чрезвычайно тяжелыми
материальными жертвами и полным упадком русской культуры, которая
дотоле блестяще развивалась и опережала культуру западноевропейских
стран.

Особенно первые полтораста лет до победы Дмитрия Донского на Куликовом
поле, которая значительно ослабила иго завоевателей и фактически
прекратила их вмешательство во внутренние дела страны

* Итоги и последствия петровских реформ

** Преодоление кризиса традиционализма

Важнейшим результатом преобразований Петра было преодоление кризиса
традиционализма путем модернизации страны.

** Активная внешняя политика

Россия стала полноправной участницей международных отношений,
проводившей активную внешнюю политику.

Значительно вырос авторитет России в мире, а сам Петр стал для многих
образцом государя реформатора.

** Заложение основ национальной культуры

При Петре были заложены основы русской национальной культуры.

** Систематизация управления и территориальное деление

Царь создал также систему управления и административно
территориального деления страны, сохранявшуюся в течение долгого
времени.

** Инструменты реформ и их влияние

Вместе с тем, главным инструментом проведения реформ было
насилие.

Петровские реформы не только не избавили страну от сложившейся ранее
системы социальных отношений, воплощенной в крепостничестве, но,
наоборот, консервировали и укрепили его институты.

В этом заключалось главное противоречие петровских реформ, предпосылки
будущего нового кризиса.

* Оценка современников и потомков деятельности Петра Первого

** Идея Соловьева

Развивая общее наше историческое сознание, идея Соловьева дала
направление и многим частным историческим исследованиям.

** Исторические монографии

Исторические монографии о XVII в. и времени Петра I констатируют
теперь связь преобразований с предыдущими эпохами и в отдельных сферах
древнерусской жизни.

В результате таких монографий является всегда одинаковый вывод, что
Петр непосредственно продолжал начинания XVII в. и оставался всегда
верен основным началам нашего государственного быта, как он сложился в
XVII в. Понимание этого века стало иным.

Недалеко то время, когда эпоха первых царей Романовых представлялась
временем общего кризиса и разложения, последними минутами тупого
застоя.

** Изменение представления

Теперь представления изменились. XVII век представляется веком
сильного общественного брожения, когда сознавали потребность перемен,
пробовали вводить перемены, спорили о них, искали нового пути,
угадывали, что этот путь в сближении с Западом, и уже тянулись к
Западу.

Теперь ясно, что XVII век подготовил почву для реформы и самого Петра
I воспитал в идее реформы. Увлекаясь этой точкой зрения, некоторые
исследователи склонны даже преуменьшать значение самого Петра в
преобразованиях его эпохи и представлять эти преобразования как
"стихийный" процесс, в котором сам Петр играл пассивную роль
бессознательного фактора.

** Милюков

У П. Н. Милюкова в его трудах о петровской реформе ("Государственное
хозяйство России в первой четверти XVIII в. и реформа Петра В." и
"Очерки по истории русской культуры") находим ту мысль, что реформа
часто "из вторых рук попадала в сознание преобразователя", бессильного
удержать ход дела в своем распоряжении и даже понять направление
событий.

Нечего и говорить, что такого рода взгляд есть крайность, не
разделяемая последующими исследователями преобразований (Н. П.
Павлов-Сильванский, "Проекты реформ в записках современников Петра
В.").

** Итоги

Научное понимание Петра Великого основывается на мысли, полнее и
справедливее всего высказанной Соловьевым. Наша наука успела связать
Петра I с прошлым и объяснить необходимость его реформ. Факты его
деятельности собраны и обследованы в нескольких ученых
трудах. Исторические результаты деятельности Петра, политической и
преобразовательной, тоже не один раз указаны.

* Список использованной литературы

1. Фомин В. В. -- Варяги и варяжская Русь. К итогам дискуссии по варяжскому вопросу.
2. Э. С. Кульпин -- Золотая Орда. Проблемы генезиса Российского государства.
3. Н. И. Павленко -- Россия в период реформ Петра I
4. https://www.wikipedia.org
5. https://www.youtube.com/watch?v=k5kY7AEfQfM

* Требования ответов на вопросы :noexport:
Выбирать один из двух предложенных вариантов контрольных заданий.

Вариант в зависимости от четности последней цифры студенческого билета:
- нечетное выполнять 1 вариант;
- четное ИЛИ «0» выполнять второй вариант.

Каждый вариант состоит из трех групп вопросов по истории:
- Киевской Руси IX-XIII вв.
- Московской Руси XIV-XVII вв.
- Российской империи XVIII-XIX вв.

Выбрать по одному вопросу из каждой группы.

Таким образом всего ответить на 3 вопроса.

Представить выполненную работу на пятой учебной неделе осеннего семестра,
то есть до 7 октября 2016 года.

На титульном листе работы следует указать
«Самостоятельная работа по истории студента группы № ______ Ф.И.О.,
номер варианта или вопроса, тема работы»

Общий объем выполненного задания в электронном формате *не должен*:
- быть меньше 10000 знаков с пробелами;
- превышать 20000 знаков с пробелами

(10 машинописных листов).

В конце самостоятельной работы
обязательно должен быть приведен список использованных материалов.
В нем должно быть *не меньше 5 наименований*.

В случае отправки работы по электронной почте файл должен включать:
- фамилию
- номер группы студента
- тема письма

Например, «Селиванов_ 6008».

В графе «тема письма» указывается «самост. работа заочника»

Все работы будут проверены на предмет их самостоятельности с тем,
чтобы исключить плагиат.

Работы, содержащие большие цельные фрагменты «чужого» текста,
зачтены не будут.

* Links :noexport:
- [[https://www.youtube.com/watch?v=etmRI2_9Q_A][Russia, the Kievan Rus, and the Mongols: Crash Course World History #20 - YouTube]]
- [[http://ивтб.рф/wiki/doku.php?id=examination:history:question4][examination:history:question4 ИВТ(б)-вики]]
- [[http://rushist.wikia.com/wiki/%D0%9A%D0%B8%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F_%D0%A0%D1%83%D1%81%D1%8C][Киевская Русь | Русская История Вики | Fandom powered by Wikia]]
- [[http://www.shpl.ru/events/exhibition/varyagi/?archive=yes][Варяги и образование Древнерусского государства]]
- [[https://www.youtube.com/watch?v=2M2mG8pnwto][Варяжская Гвардия - Древний Спецназ. Документальный Фильм - YouTube]]
- [[https://www.youtube.com/watch?v=bGjFK0NMHCY][Первое русское государство Варяжская проблема Говорящие камни - YouTube]]
- [[http://books.house/vsemirnaya-istoriya/obrazovanie-drevnerusskogo-gosudarstva-39313.html][§ 22. Образование Древнерусского государства: Особенности становления цивилизации у восточных славян. С VI]]
- [[http://istorik-samara.ru/files/Ratnikova.pdf][Ratnikova.pdf]]
- [[http://uclg.ru/education/otechestvennaya_istoriya/6_klass/narodyi_i_gosudarstva_na_territorii_nashey_stranyi_v_XIII_-_XIV_vekah/lecture_lec_otnosheniya_rusi_i_zolotoy_ordyi__mifyi_i_realnost.html][Отношения Руси и золотой орды: мифы и реальность | Учеба-Легко.РФ - крупнейший портал по учебе]]
- [[https://otvet.mail.ru/question/95883662][Ответы Mail.Ru: влияние Золотой Орды на развитие древней Руси в XIII-XV вв]]
- [[https://otvet.mail.ru/question/29795144][Ответы Mail.Ru: Итоги и значение Петровских реформ!]]
- [[http://rushist.com/index.php/platonov-lectures/1974-otsenki-reform-i-deyatelnosti-petra-i][Оценки реформ и деятельности Петра I - Русская историческая библиотека]]
** Варяги

- [[http://factsanddetails.com/russia/History/sub9_1a/entry-4932.html][VIKINGS IN RUSSIA | Facts and Details]]
- [[http://www.loudoun.k12.va.us/cms/lib4/VA01000195/Centricity/Domain/10599/Kievan%20Russia.pdf][Kievan Russia.pdf]]
- [[http://www.maritimeheathen.org/Documents/Scandinavins%20in%20Kievan%20Russia-Katie%20Lane.pdf][() - Scandinavins in Kievan Russia-Katie Lane.pdf]]
- [[https://en.wikipedia.org/wiki/Rus%27_people][Rus' people - Wikipedia]]
- [[https://en.wikipedia.org/wiki/Vikings][Vikings - Wikipedia]]
- [[https://www.youtube.com/watch?v=G-gZqGDaYTY][Viking (2016) New russian historical movie teaser - YouTube]]

** Орда

- [[http://www.newworldencyclopedia.org/entry/Golden_Horde][Golden Horde - New World Encyclopedia]]
- [[https://en.wikipedia.org/wiki/Golden_Horde][Golden Horde - Wikipedia]]
- [[https://en.wikipedia.org/wiki/Kievan_Rus%27][Kievan Rus' - Wikipedia]]
- [[https://en.wikipedia.org/wiki/List_of_early_East_Slavic_states][List of early East Slavic states - Wikipedia]]
- [[https://en.wikipedia.org/wiki/Mongol_invasion_of_Rus%27][Mongol invasion of Rus' - Wikipedia]]
- [[https://www.reddit.com/r/AskHistorians/][AskHistorians]]
- [[https://www.reddit.com/r/AskHistorians/comments/1h8qns/what_impact_did_the_golden_horde_have_in_russia/][What impact did the Golden Horde have in Russia? : AskHistorians]]
- [[https://www.youtube.com/watch?v=7q8C34jD-x8][The Horde (Russian movie with English subtitles) - YouTube]]

** Петр Первый

- [[https://en.wikipedia.org/wiki/Peter_the_Great][Peter the Great - Wikipedia]]
- [[https://www.youtube.com/watch?v=HNfSBCygXTg][Epic History: Russia Part 2 - YouTube]]
- [[https://www.youtube.com/watch?v=ZfWaHCWO42M][Peter the Great - YouTube]]
- [[https://www.youtube.com/watch?v=wojI4sQO5M0][Peter the Great: Tsar of Russia - YouTube]]

