#+TITLE: Самостоятельная работа по истории IX-XIX веков 1 вариант
#+AUTHOR: Студент группы № 6005 Пыхалов Олег Витальевич
#+EMAIL: opykhalov@yandex.ru
#+OPTIONS: email:t

#+LANGUAGE: ru
#+LaTeX_HEADER: \usepackage[utf8]{inputenc}
#+LaTeX_HEADER: \usepackage[T1,T2A]{fontenc}
#+LaTeX_HEADER: \usepackage[english,russian]{babel}
#+LATEX_HEADER: \hypersetup{colorlinks, citecolor=black, filecolor=black, linkcolor=black, urlcolor=blue}

#+OPTIONS: H:2 toc:t num:t
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+LATEX_CLASS_OPTIONS: [aspectratio=169]
#+LATEX_HEADER: \beamertemplatenavigationsymbolsempty
#+BEAMER_THEME: default
#+BEAMER_COLOR_THEME: crane
#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt)

* Вопросы

** 1-й вопрос – Киевская Русь IX-XIII вв.

Роль варягов в образовании и развитии Древнерусского
государства. Норманнская проблема.

** 2-й вопрос – Московская Русь XIV-XVII вв.

Система отношений между Русью и Ордой в XIII-XV вв. и ее влияние на
развитие русских земель.

** 3-й вопрос – Российская империя XVIII-XIX вв.

Итоги и последствия петровских реформ. Оценка современников и
потомков.

* Роль варягов в образовании и развитии Древнерусского государства

** Объединение земель

Варяги способствовали объединению северной и южной Руси.

** Новые правители

Варяги дали новую правящую династию Рюриковичей в 862-1598 годах.

** Возможное происхождение название Руси

Предположительно название Русь происходит от варяжского племени Руси,
к которому принадлежал Рюрик.

* Норманнская проблема

** Создатели норманнской теории

Немецкие Ученые на руссийской Службе:
- Байер
- Миллер
- Шлёцер

** Норманнская теория

Государственность на Русь принесли варяги, приглашенные в 862 года на
княжение в Новгород. Варяжская династия Рюриковичей объединила
северную и южную Русь, создала систему сбора дани, управления и
судопроизводства на огромной территории.

** Антинорманская теория

Основатель -- Михаил Васильевич Ломоносов

Наиболее активные сторонники в 19 веке историки:
- Иличевский
- Беляев
- Забелин

Государственность на Руси существовала в виде локальных образований и
до середины 9 века восточные славяне смогли организовать себя сами,
без помощи варягов.

Современные историки говорят о наличие на Руси до 9 века трёх центров
государственности:
- Куяба
- Славия
- Артания

** Причины приглашения варяг

- Были хорошими воинами
- Был опыт в создании государства
- Нейтральные

Современные историки предполагают, что варяги пришли не по
приглашению, а как завоеватели. А также были не скандинавами, а
славянами с южных берегов Балтики.

* Система отношений в XIII-XV веках между Русью и Ордой

** Начало политической истории

Начало политической истории Золотой Орды относится к 1243 году, когда
Батый возвратился из похода в Европу.

В этом же году, великий князь Ярослав, первым из русских правителей,
прибыл в ставку монгольского хана за ярлыком на княжение.

Монголы сохраняли местные династии, не размещали воинские гарнизоны,
не совершали гонений на церковь.

Князья были вассалами Батыя и его наследников.

Монголы использовали систему заложничества.

** Перепись населения и сбор дани

C 1257 по 1259 года производилась перепись русского населения для
сбора дани.

Главный вид дани, собиравшейся серебром, назывался "Ордынский
выход".

Всего было 14 видов дани.

Сначала дань собирали баскаки, а после восстаний князья.

** Монгольское иго

Отношения Руси с Ордой приняли предсказуемые и устойчивые формы.

Появляется явление, получившее название, "Монгольское иго".

Практика периодических карательных походов не прекращалась до 14 века.

Многие русские князья подверглись террору и запугиванию с целью не
допустить с их стороны антиордынских выступлений.

** Православие

Деятельность православной епархии в Орде не прошла даром.

После 1318 года на Русь двинулся поток православных татар. В основном
они принимались на военную службу московскому князю, находившемуся в
союзе с православной церковью.

** Могущественные войны Москвы

Москва превосходила силой другие княжества. Она получила воинов, не
имевших себе равных.

** Передача сбора дани

В конце 13 века Орда передала русским князьям сбор дани.
Это облегчило возможности для финансового и политического маневрирования.

Потомки Александра Невского продолжали проводить политику "смиренной
мудрости". Они постепенно накапливали предпосылки для перелома в
происходящем.

** Разделение на части

Золотая Орда разделилась на 2 части по Волге.

** Повторное завоевание Руси

С 1371 года дань больше не выплачивалась Донским.

Мамаю нужно было снова завоевывать Русь.

Перелом произошел в 1380 году. На Куликовом поле московское войска,
набиравшие в добровольцы людей из всех русских земель, выступили
против орды.

Руси удалось отстоять свои интересы. Изменились отношения Орды и Руси.
Монголы не сражались в открытую. Дань, восстановленная после 1382,
стала откупом и усилением московского войска.

** Распад

После присоединения Новгородской земли, Московское княжество
превратилось в большое и сильное государство.

К этому времени Золотая Орда распалась.

От неё отделились, жившие в постоянной вражде между собой ханства:
- Казанское
- Астраханское
- Крымское
- Сибирское

** Разрыв отношений

Иван III заключил союз с крымским ханом Менгли-Гиреем. После он начал
готовиться к разрыву с Ордой.

В 1478 году Иван III, в присутствии московских бояр и ордынских
послов, разорвал и растоптал договор с Ордой, заявив, что больше не
будет подчиняться хану и платить дань.

Ханских послов выгнали из Москвы.

** После распада

Ордынское иго оказало мощное влияние на ход русской истории.

Через 200 лет после создания ханом Батыем монгольского государства, оно
распалось на несколько составных государств:
- Большую Орду
- Астраханское
- Казанское
- Крымское
- Сибирское ханства
- Ногайскую Орду

Московская Русь напротив консолидировалась и набирала мощь.

После распада Золотой Орды, геополитическое наследство перешло Руси.

* Влияние Орды на развитие русских земель

** Монгольское завоевание

Монгольское завоевание искусственно и резко прервало независимое
развитие русской государственности.

Вся русская государственная машина в княжествах, попавших под власть
Золотой Орды, была переориентирована на Восток в Азию.

** Изменение внешней политики

Изменилась русская внешняя политика.
Из самостоятельной она превратилась в вассальную.

** Упадок экономии

Ордынское владычество привело к упадку в экономическом, политическом и
культурном развитии русских земель. Также оно положило начало
отставанию их от передовых западноевропейских стран.

Запустели и пришли в упадок старые земледельческие центры и освоенные
территории. Границы земледелия отодвинулись на север.

** Разорение городов

Были разорены и уничтожены русские города. Их роль в политической и
экономической жизни страны упала.

** Упадок развития производства

Исчезли навсегда и лишь возродились через долгое время ремесла:
- скань
- чернь
- перегородчатая эмаль
- полихромная поливная керамика
- резьба по камню

Приостановилось каменное строительство.

Пришло в упадок изобразительное и прикладное искусство.

Ослабла связь городского ремесла с рынком.

Затормозилось развитие товарного производства.

** Прекращение денежного обращения

Дань "серебром" привела к утечке его в Орду и почти полному
прекращению денежного обращения внутри русских земель.

** Потери в битвах и рабство

Десятки тысяч людей погибли в битвах или были угнаны в рабство в
результате набегов Золотой Орды на русские земли.

** Крупные вторжения и набеги

За последнюю четверть ХIII века было совершено 14 крупных вторжений на
Русь, а также множество более мелких набегов.

** Разрушение важнейших городов

Периодичное разрушение городов:
- Переславль-Залесский
- Муром
- Суздаль
- Рязань

** Период татарского владычества

Русь была под татарским управлением 242 года.

Этот период в ее истории ознаменовался чрезвычайно тяжелыми
материальными жертвами и полным упадком русской культуры, которая до
этого блестяще развивалась и опережала культуру западноевропейских
стран.

Особенно первые несколько лет до победы Дмитрия Донского на Куликовом
поле, которая значительно ослабила иго завоевателей и прекратила их
вмешательство во внутренние дела страны.

* Итоги и последствия Петровских реформ

** Преодоление кризиса традиционализма

Важнейшим результатом преобразований Петра стало преодоление кризиса
традиционализма с помощью модернизации страны.

** Активная внешняя политика

Россия стала полноправной участницей международных отношений,
проводившей активную внешнюю политику.

Значительно вырос авторитет России в мире. Петр стал для многих
образцом государя реформатора.

** Заложение основ национальной культуры

Петр заложил основы русской национальной культуры.

** Систематизация управления и территориальное деление

Петр создал также систему управления и административно
территориального деления страны, длившуюся в течение долгого времени.

** Влияние реформ

Петровские реформы не избавили страну от сложившейся системы
социальных отношений, воплощенной в крепостничестве, а также
консервировали и укрепили его институты.

Главное противоречие Петровских реформ, предпосылки будущего нового
кризиса.

* Оценка современников и потомков деятельности Петра I

** Идея Соловьева

Идея Соловьева дала направление многим историческим исследованиям.

** Исторические монографии

Исторические монографии о XVII в. и времени Петра I показывают связь
преобразований с предыдущими эпохами и в отдельных участках
древнерусской жизни.

Результатом этих монографий является всегда вывод, что Петр
непосредственно продолжал и оставался всегда верен основным началам
нашего государственного быта.

Эпоха первых царей Романовых представлялась временем общего кризиса и
разложения.

** Изменение представления

XVII век -- это век сильного общественного брожения, когда хотели
перемен, пробовали перемениться, спорили о переменах, искали нового
пути, и тянулись к Западу.

XVII век подготовил почву для реформы.

** Милюков

У П. Н. Милюкова в его трудах о петровской реформе "Государственное
хозяйство России в первой четверти XVIII в. и реформа Петра В." и
"Очерки по истории русской культуры".

Реформа часто "из вторых рук попадала в сознание преобразователя",
бессильного удержать ход дела в своем распоряжении и даже понять
направление событий.

** Итоги

Понимание Петра I основывается на мысли, полнее всего высказанной
Соловьевым.

Наша наука успела связать Петра I с прошлым и объяснить необходимость
его реформ.

Факты его деятельности собраны и обследованы в нескольких ученых
трудах.

Исторические результаты деятельности Петра, политической и
преобразовательной, тоже указаны.

* Список использованной литературы

** Книги

1. Фомин В. В. -- Варяги и варяжская Русь. К итогам дискуссии по варяжскому вопросу.
2. Кульпин Э. С. -- Золотая Орда. Проблемы генезиса Российского государства.
3. Павленко Н. И. -- Россия в период реформ Петра I

** Интернет ресурсы

4. https://www.wikipedia.org
5. https://www.youtube.com/watch?v=k5kY7AEfQfM

* Требования ответов на вопросы :noexport:
Выбирать один из двух предложенных вариантов контрольных заданий.

Вариант в зависимости от четности последней цифры студенческого билета:
- нечетное выполнять 1 вариант;
- четное ИЛИ «0» выполнять второй вариант.

Каждый вариант состоит из трех групп вопросов по истории:
- Киевской Руси IX-XIII вв.
- Московской Руси XIV-XVII вв.
- Российской империи XVIII-XIX вв.

Выбрать по одному вопросу из каждой группы.

Таким образом всего ответить на 3 вопроса.

Представить выполненную работу на пятой учебной неделе осеннего семестра,
то есть до 7 октября 2016 года.

На титульном листе работы следует указать
«Самостоятельная работа по истории студента группы № ______ Ф.И.О.,
номер варианта или вопроса, тема работы»

Общий объем выполненного задания в электронном формате *не должен*:
- быть меньше 10000 знаков с пробелами;
- превышать 20000 знаков с пробелами

(10 машинописных листов).

В конце самостоятельной работы
обязательно должен быть приведен список использованных материалов.
В нем должно быть *не меньше 5 наименований*.

В случае отправки работы по электронной почте файл должен включать:
- фамилию
- номер группы студента
- тема письма

Например, «Селиванов_ 6008».

В графе «тема письма» указывается «самост. работа заочника»

Все работы будут проверены на предмет их самостоятельности с тем,
чтобы исключить плагиат.

Работы, содержащие большие цельные фрагменты «чужого» текста,
зачтены не будут.

* Links :noexport:
- [[https://www.youtube.com/watch?v=etmRI2_9Q_A][Russia, the Kievan Rus, and the Mongols: Crash Course World History #20 - YouTube]]
- [[http://ивтб.рф/wiki/doku.php?id=examination:history:question4][examination:history:question4 ИВТ(б)-вики]]
- [[http://rushist.wikia.com/wiki/%D0%9A%D0%B8%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F_%D0%A0%D1%83%D1%81%D1%8C][Киевская Русь | Русская История Вики | Fandom powered by Wikia]]
- [[http://www.shpl.ru/events/exhibition/varyagi/?archive=yes][Варяги и образование Древнерусского государства]]
- [[https://www.youtube.com/watch?v=2M2mG8pnwto][Варяжская Гвардия - Древний Спецназ. Документальный Фильм - YouTube]]
- [[https://www.youtube.com/watch?v=bGjFK0NMHCY][Первое русское государство Варяжская проблема Говорящие камни - YouTube]]
- [[http://books.house/vsemirnaya-istoriya/obrazovanie-drevnerusskogo-gosudarstva-39313.html][§ 22. Образование Древнерусского государства: Особенности становления цивилизации у восточных славян. С VI]]
- [[http://istorik-samara.ru/files/Ratnikova.pdf][Ratnikova.pdf]]
- [[http://uclg.ru/education/otechestvennaya_istoriya/6_klass/narodyi_i_gosudarstva_na_territorii_nashey_stranyi_v_XIII_-_XIV_vekah/lecture_lec_otnosheniya_rusi_i_zolotoy_ordyi__mifyi_i_realnost.html][Отношения Руси и золотой орды: мифы и реальность | Учеба-Легко.РФ - крупнейший портал по учебе]]
- [[https://otvet.mail.ru/question/95883662][Ответы Mail.Ru: влияние Золотой Орды на развитие древней Руси в XIII-XV вв]]
- [[https://otvet.mail.ru/question/29795144][Ответы Mail.Ru: Итоги и значение Петровских реформ!]]
- [[http://rushist.com/index.php/platonov-lectures/1974-otsenki-reform-i-deyatelnosti-petra-i][Оценки реформ и деятельности Петра I - Русская историческая библиотека]]
** Варяги

- [[http://factsanddetails.com/russia/History/sub9_1a/entry-4932.html][VIKINGS IN RUSSIA | Facts and Details]]
- [[http://www.loudoun.k12.va.us/cms/lib4/VA01000195/Centricity/Domain/10599/Kievan%20Russia.pdf][Kievan Russia.pdf]]
- [[http://www.maritimeheathen.org/Documents/Scandinavins%20in%20Kievan%20Russia-Katie%20Lane.pdf][() - Scandinavins in Kievan Russia-Katie Lane.pdf]]
- [[https://en.wikipedia.org/wiki/Rus%27_people][Rus' people - Wikipedia]]
- [[https://en.wikipedia.org/wiki/Vikings][Vikings - Wikipedia]]
- [[https://www.youtube.com/watch?v=G-gZqGDaYTY][Viking (2016) New russian historical movie teaser - YouTube]]

** Орда

- [[http://www.newworldencyclopedia.org/entry/Golden_Horde][Golden Horde - New World Encyclopedia]]
- [[https://en.wikipedia.org/wiki/Golden_Horde][Golden Horde - Wikipedia]]
- [[https://en.wikipedia.org/wiki/Kievan_Rus%27][Kievan Rus' - Wikipedia]]
- [[https://en.wikipedia.org/wiki/List_of_early_East_Slavic_states][List of early East Slavic states - Wikipedia]]
- [[https://en.wikipedia.org/wiki/Mongol_invasion_of_Rus%27][Mongol invasion of Rus' - Wikipedia]]
- [[https://www.reddit.com/r/AskHistorians/][AskHistorians]]
- [[https://www.reddit.com/r/AskHistorians/comments/1h8qns/what_impact_did_the_golden_horde_have_in_russia/][What impact did the Golden Horde have in Russia? : AskHistorians]]
- [[https://www.youtube.com/watch?v=7q8C34jD-x8][The Horde (Russian movie with English subtitles) - YouTube]]

** Петр Первый

- [[https://en.wikipedia.org/wiki/Peter_the_Great][Peter the Great - Wikipedia]]
- [[https://www.youtube.com/watch?v=HNfSBCygXTg][Epic History: Russia Part 2 - YouTube]]
- [[https://www.youtube.com/watch?v=ZfWaHCWO42M][Peter the Great - YouTube]]
- [[https://www.youtube.com/watch?v=wojI4sQO5M0][Peter the Great: Tsar of Russia - YouTube]]
