#+TITLE: Самостоятельная работа по истории студента группы № 6005 Пыхалова Олега Витальевича, 1 вариант ? вопрос, по истории IX-XIX вв.

* Вариант 1

** 1-й вопрос – Киевская Русь IX-XIII вв.

*** 1
Роль варягов в образовании и развитии Древнерусского государства.
Норманнская проблема.

*** 2
Отношения между русскими княжествами и кочевыми соседями в IX-XIII вв.

*** 3
*Сравните* социальное и политическое устройство русских княжеств
XI-XIII вв. с устройством современных им европейских государств
(Франции, Англии или Германии).

*** 4
Духовная культура Киевской Руси.

*** Определение
Древнерусское государство, *Киевская Русь* — государство,
возникшее в IX веке в результате объединения восточнославянских племён
под властью князя Олега Вещего.

В период наивысшего расцвета Киевская Русь занимала территорию *от*:
- Таманского полуострова на юге,
- Днестра и верховьев Вислы на западе,
*до*:
- верховьев Северной Двины на севере.

К середине XII века вступила в состояние политической раздробленности
и фактически распалась на отдельные русские княжества.

Вплоть до монгольского нашествия (1237—1240)
Киев формально продолжал считаться главным городом Руси,
а Киевское княжество занимало главные позиции в государстве.


** 2-й вопрос – Московская Русь XIV-XVII вв.

1.​ Система отношений между Русью и Ордой в XIII-XV вв. и ее влияние на развитие русских земель.

2.​ Сравните устройство Московского государства и европейского централизованного государства XV-XVI вв. (Франции)

3.​ Крепостное право: причины и этапы закрепощения крестьян

4.​ Россия в XVII в. Выделите и опишите основные направления развития страны.

** 3-й вопрос – Российская империя XVIII-XIX вв.

1.​ Итоги и последствия петровских реформ. Оценка современников и потомков.

2.​ Изменение государственных границ Российской империи в XVIII-XIX вв.

3.​ Сопоставьте замыслы либеральных реформ Александра I и их воплощение в реальной жизни

4.​ Социальная структура, национальный состав и культурные особенности российского общество в период после реформ Александра II.

* Вариант 2

** 1-й вопрос – Киевская Русь IX-XIII вв.

1.​ Проанализируйте роль географического фактора (природа, климат, соседи) развития древнерусского государства.

2.​ С какими странами и народами активно контактировала Древняя Русь в IX-XII вв.? В чем выражались эти контакты?

3.​ «Русская Правда» как правовой акт и как источник по истории Древней Руси.

4.​ Архитектура Киева, Новгорода и Владимира. Основные особенности и памятники.

** 2-й вопрос – Московская Русь XIV-XVII вв.

1.​ Альтернативные центры объединения русских земель и причины их неудачи

2.​ Сравните политическое устройство Новгорода, Литвы и Москвы в XV в.

3.​ Правление Ивана Грозного. Оценка современников и потомков

4.​ Церковь и государство. Раскол середины XVII вв.

** 3-й вопрос – Российская империя XVIII-XIX вв.

1.​ «Золотой век» Екатерины II – достижения и недостатки.

2.​ Развитие социально-политической мысли в России XIX в.

3.​ Александр II: отмена крепостного права и условия наделения крестьян землей

4.​ Россия в системе международных отношений в XIX в.

* Варяги

** Определение варягов
Варя́ги (др.-сканд. Væringjar, греч. Βάραγγοι) — группа в составе населения
Древней Руси, *носящая*:
- этнический
- социальный характер, который вызывает многочисленные дискуссии

** Кого называли варягами
На Руси варягами называли выходцев:

*** из Скандинавии
- викингов
- обрусевших потомков викингов
  
*** с южного побережья Балтийского моря
- полабских славян
- балтов
  
бывших в Древнерусском государстве IX—XII вв. *И* Византии XI—XIII вв.
- наёмными воинами
- торговцами

Норма́нская тео́рия (нормани́зм) — направление в историографии, развивающее концепцию того, что народ-племя русь происходит из Скандинавии периода экспансии викингов, которых в Западной Европе называли норманнами.


** Роль варягов в образовании и развитии Древнерусского государства
Согласно Лаврентьевской летописи.

В 862 году обратились к норманнам (ИЛИ варягам, как их называли на Руси):
- чудь;
- славяне;
- кривичи.

«Земля наша велика и обильна, а наряда (порядка) в ней нет.
Приходите княжить и владеть нами».

По приглашению со своими родами прибыли *три князя*:
- Рюрик в Новгород;
- Синеус на Белоозере;
- Трувор в Изборске.

** Норманнская проблема
В 18 веке летописная версия стала предметом ожесточенной дискуссии.

*** Участники спора

Немецкие ученые:
- Г.З. Байером,
- Г.Ф. Миллером,
- А.Л. Шлецером.

Российский академик М.В. Ломоносовым.

*** Проблема
В спорах родилась целая *«норманнская проблема»*.

На протяжении последующих двух столетий
эта проблема становилась объектом ожесточенной идеологической борьбы.

Одни авторы отрицали способность восточных славян
к созданию собственной государственности.

Другие авторы пренебрегали ролью варягов в отечественной истории.

Фактически «варяжский вопрос»
заключался в оценке степени участия скандинавов
в формировании Древнерусского государства.

С.М. Соловьев не отрицал призвания варяжских князей на Русь,
но отказывался видеть в этом неразвитость славян.

В.О. Ключевский утверждал,
что именно из Киева,
пошло политическое объединение славянских племен,
а не из Новгорода, 

*** Норманисты
В большей или меньшей степени «норманистами» являлись:
- Н.М. Карамзин,
- М.П. Погодин,
- В.О. Ключевский.

**** Противники норманистов
Противниками норманистов выступили:
- дворянские историки,
- буржуазные историки.

Среди них:
Иловайский Д. И.,
Гедеонов С. А.,
Васильевский В. Г..

**** Обзор В. М. Мошина
Лучшая попытка представить цельную картину этой научной полемики
является обзор Мошина В. М.,
опубликованный в 1931 году,
в пражском журнале «Slavia».

«Варяжский вопрос» включает в себя
- факт призвания варягов на Русь;
- вопрос о географической привязке древнейшей родины племени «русь»;
- лингвистические толкования имен «русь» и «варяги».

В вопросе о хронологии некоторые верят:
- летописи;
- в более раннее появление племени «русь» в Восточной Европе.
  
**** Предложение Рыдзевская Е. А.
В 1939 году Рыдзевская Е. А. предложила:
- преодолеть противопоставление норманизма и антинорманизма;
- учесть сильные и слабые стороны обоих течений в историографии.

**** Вклад школы Грекова Б. Д.
В советской историографии
большой вклад в изучение этой проблемы внесла
школа Грекова Б. Д..

Сделала упор на изучение внутренних факторов.

Разработала концепцию классового общества и
государства в восточнославянских землях.

Формирование Древнерусского государства
рассматривалось исследователями
как результат многовекового процесса социально-экономического развития
восточнославянского общества.

Протекавшего на огромном пространстве от:
- Ладоги до низовьев Днепра
- Карпат до бассейна Оки и Нижней Волги.

Совершенно очевидным при этом становится тот факт,
что радикальные социально-экономические изменения,
на столь огромной территории,
не могли быть результатом деятельности отрядов
чужеземных пришельцев-завоевателей.

**** Анализ письменных источников Пашуто В. Т.
Формирование нового подхода
к варяжской проблеме в отечественной науке
связано с именем Пашуто В. Т..

Анализ письменных источников,
который провел Пашуто,
позволил выработать тот взгляд на варягов,
которого придерживаются большинство современных исследователей.

Древняя Русь этнически неоднородное государство,
выросшее из конфедерации 14 земель-княжений,
возглавляемых славянской знатью.

В летописном делении Руси на:
- «верховную» (с центром в Новгороде)
- «низовую» (с центром в Киеве)
просматриваются следы союзов земель Южной и Северной Руси.

Варяжские князья правили от имени давших им власть славянских мужей.

Варяжские дружины были лишь из слагаемых рати,
в которой преобладали славянские воины.

В письменных источниках,
по мнению Пашуто,
нет данных ни о:
- завоевании Руси норманнами,
- ее колонизации.

* Требования
Выбирать один из двух предложенных вариантов контрольных заданий.

Вариант в зависимости от четности последней цифры студенческого билета:
- нечетное выполнять 1 вариант;
- четное ИЛИ «0» выполнять второй вариант. 

Каждый вариант состоит из трех групп вопросов по истории:
- Киевской Руси IX-XIII вв.
- Московской Руси XIV-XVII вв.
- Российской империи XVIII-XIX вв.

Выбрать по одному вопросу из каждой группы.

Таким образом всего ответить на 3 вопроса.

Представить выполненную работу на пятой учебной неделе осеннего семестра,
то есть до 7 октября 2016 года.

На титульном листе работы следует указать
«Самостоятельная работа по истории студента группы № ______ Ф.И.О.,
номер варианта или вопроса, тема работы»

Общий объем выполненного задания в электронном формате *не должен*:
- быть меньше 10000 знаков с пробелами;
- превышать 20000 знаков с пробелами
  
(10 машинописных листов).

В конце самостоятельной работы
обязательно должен быть приведен список использованных материалов.
В нем должно быть *не меньше 5 наименований*.

В случае отправки работы по электронной почте файл должен включать:
- фамилию
- номер группы студента
- тема письма

Например, «Селиванов_ 6008».

В графе «тема письма» указывается «самост. работа заочника»

Все работы будут проверены на предмет их самостоятельности с тем,
чтобы исключить плагиат.

Работы, содержащие большие цельные фрагменты «чужого» текста,
зачтены не будут.

* Материал
http://rushist.wikia.com/wiki/%D0%9A%D0%B8%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F_%D0%A0%D1%83%D1%81%D1%8C
[[https://www.youtube.com/watch?v=2M2mG8pnwto][Варяжская Гвардия - Древний Спецназ. Документальный Фильм]]

1. 
2. 
3. 
4. 
5. 
