#+TITLE: Japanese

おとこ	男	otoko	man
おんあのひと	???	onnanohito	woman
かぞく	家族	kazoku	family
あたま	頭	atama	head
かお	顔	kao	face
かみ	神	kami	hear
やめて!			stop it!

	手洗い		toilet
わかりません		wakarimasen
	英語	eigo	english
	服	fuku	clothes
	死にそう	shini sou	seems like I'm going to die
	警察	keisatsu	police
	亜部内	abunai	dangerous
	危険	kiken	peril, hazard
	みます	mimasu	to see
		ikimasu	to go
	おはようございます	ohayougozaimasu	good morning
		kore ha	there is

                        わたし	watashi	I
	あなた	anata	you
	ひと	hito	human

	いぬ	inu	dog
	ねこ	neko	cat
	さかな	sakana	fish
	は = わ	ha

	これ	kore	this	это, предмет возле говорящего
	それ	sore	this, that	это, то, предмет возле собеседника
	あれ	are		то, предмет вдалеке от обоих или возле третьего лица

* Частицы

[[https://www.youtube.com/watch?v%3DNm45O8buf4A&index%3D4&list%3DPLUQ8IPIJSszABqsC8HliK-7Q4oYj7z7r1][Японский язык - Урок 1. Основные конструкции]]

** は

Частица は в предложении указывает на слово или сочетание слов,
являющимся темой предложения.  То есть слово, стоящее перед этой
частицей является темой предложения.

です [desu] (des) であります быть или являться.  Указывает на уровень
вежливости в предложении.  Часто может опускаться или заменяться
другими.  На начальных этапах рекомендуется всегда ставить в конце
предложения.

#+BEGIN_EXAMPLE
わたし は ひと です [watashi ha hito desu] - я человек. Что касается меня, я человек.

あなた は ひと です [anata ha hito desu] - ты человек.

これ は ねこ です [kore ha neko desu] - это кошка (возле меня).

それ は いぬ です [sore ha inu desu] - это собака (возле тебя).

おれ は そかな です [ore ha sokana desu] - то рыба (находится в далеке от обоих лиц).
#+END_EXAMPLE

** Принадлежность или отношение предмета

Частица の означает принадлежность или отношение одного предмета к другому.

Существительное $x$ принадлежит существительному $y$: $x$ の $y$.

#+BEGIN_EXAMPLE
わたし の ねこ [watashi no neko] - моя кошка, то есть кошка которая принадлежит мне.

これ は なたし の ねこ です [kore ha natashi no neku desu] - это моя кошка.
#+END_EXAMPLE

** Вопросительная частица

Вопросительная частица か [ka] - играет роль вопросительного знака.
Добавив его после です [desu] в конце, мы предадим предложению
вопросительный оттенок.  Интонация будет тоже с повышением в конце.

#+BEGIN_EXAMPLE
それ は あなた の いぬ です か [sore ha anata no inu desu ka] - Это твоя собака?
#+END_EXAMPLE

