#+TITLE: Japanese

* Words

Hiragana OR Katakana		Type	English	Русский

おとこ	男	otoko	man
おんあのひと	???	onnanohito	woman
かぞく	家族	kazoku	family
あたま	頭	atama	head
かお	顔	kao	face
かみ	神	kami	hear
やめて!			stop it!

	手洗い		toilet
わかりません		wakarimasen
	英語	eigo	english
	服	fuku	clothes
	死にそう	shini sou	seems like I'm going to die
	警察	keisatsu	police
	亜部内	abunai	dangerous
	危険	kiken	peril, hazard
みます		mimasu	to see
		ikimasu	to go
おはようございます		ohayougozaimasu	good morning
		kore ha	there is

わたし		watashi	I	я
あなた		anata	you	ты
ひと		hito	human	человек

いぬ		inu	dog	собака
ねこ		neko	cat	кошка
さかな		sakana	fish	рыба
は = わ		ha		частица

これ		kore	this	это, предмет возле говорящего
それ		sore	this, that	это, то, предмет возле собеседника
あれ		are		то, предмет вдалеке от обоих или возле третьего лица

ジュス		jusu	juse	сок
ペン		pen	pen	ручка
でんしせ		denshise	train	электропоезд
くつ		kutsu                   boots	обувь
そら		sora	sky	небо
がつこう		gatsukou	school	школа
だいがくー		daigak-	university	университет
にほん		nihon	Japan	Япония
につぽんー		nipon	Japan	Япония
にほんごー		nihongo	japanese	японский язык
のみます		nomimas|u	drink	пить
かいます		kaimas|u	buy	покупать
へんきようしますー		henkiyoushimas|u-	learn	заниматься, учиться
いきます		ikimas|u	go, ride	идти, ехать
みます		mimas|u	see, watch	видеть, смотреть
を		wo		частица


* Вопросы

Как правильно пишется?
へんきようしますー		henkiyoushimasu-	learn	заниматься, учиться

* Грамматика

** Частицы

- [[https://www.youtube.com/watch?v%3DNm45O8buf4A&index%3D4&list%3DPLUQ8IPIJSszABqsC8HliK-7Q4oYj7z7r1][Японский язык - Урок 1. Основные конструкции]]
- [[https://www.youtube.com/watch?v%3DRGZIcOimQkM&index%3D3&list%3DPLUQ8IPIJSszABqsC8HliK-7Q4oYj7z7r1][Японский язык - Урок 2. Основные конструкции - #2]]

*** Частица указывающая на тему предложения

Частица は в предложении указывает на слово или сочетание слов,
являющимся темой предложения.  То есть слово, стоящее перед этой
частицей является темой предложения.

です [desu] (des) であります быть или являться.  Указывает на уровень
вежливости в предложении.  Часто может опускаться или заменяться
другими.  На начальных этапах рекомендуется всегда ставить в конце
предложения.

#+BEGIN_EXAMPLE
  わたし は ひと です [watashi ha hito desu] - я человек. Что касается меня, я человек.
  あなた は ひと です [anata ha hito desu] - ты человек.
  これ は ねこ です [kore ha neko desu] - это кошка (возле меня).
  それ は いぬ です [sore ha inu desu] - это собака (возле тебя).
  おれ は そかな です [ore ha sokana desu] - то рыба (находится в далеке от обоих лиц).
#+END_EXAMPLE

*** Частица показывая принадлежность или отношение предмета

Частица の означает принадлежность или отношение одного предмета к
другому. Существительное $x$ принадлежит существительному
$y$: $x$ の $y$.

#+BEGIN_EXAMPLE
  わたし の ねこ [watashi no neko] - моя кошка, то есть кошка которая принадлежит мне.
  これ は なたし の ねこ です [kore ha natashi no neku desu] - это моя кошка.
#+END_EXAMPLE

*** Вопросительная частица

Вопросительная частица か [ka] - играет роль вопросительного знака.
Добавив его после です [desu] в конце, мы предадим предложению
вопросительный оттенок.  Интонация будет тоже с повышением в конце.

#+BEGIN_EXAMPLE
  それ は あなた の いぬ です か [sore ha anata no inu desu ka] - Это твоя собака?
#+END_EXAMPLE

*** Закрепить

**** Вопросы

#+BEGIN_EXAMPLE
  1. あなた は ひと です [anata ha hito desu] - ???
  2. これ は いぬ です [kore ha inu desu] - ???
  3. それ は なたし の さかな です [sore ha natashi no sakana desu] - ???
  4. あれ は あなた の ねこ です か [are ha anata no neko desu ka] - ???
#+END_EXAMPLE

**** Ответы

1. Ты человек.
2. Это собака (возле говорящего).
3. Это моя рыба (возле собеседника).
4. То (на расстоянии) твоя кошка?

*** 

Слово стоящее перед частицей を [wo] находится в винительном падеже и
является дополнением.  То есть を [wo] указывает на предмет, к
которому направленно действие.  Соответственно, после слова частицы,
нужно поставить глагол, который будет обозначать это действие.

#+BEGIN_EXAMPLE
  ジュス を のみます [jusu wo nomimas|u] - пить сок.
#+END_EXAMPLE

Сок - это существительное, к которому направлено действие - пить.

#+BEGIN_EXAMPLE
  くつ を かいます [kutsu wo kaimas|u] - покупать обувь.
#+END_EXAMPLE

Совершенно действие покупать к предмету обувь.

#+BEGIN_EXAMPLE
  そら を みます [sora wo mimas|u] - смотреть на небо, видеть небо.
#+END_EXAMPLE

*** 

で [de]

Чаще всего используется в значении: слово после которого стоит частица
で [de] обычно существительное или местоимение.  В таком случае они
будут обозначать место действия.  Можно сказать, что эта частица
служет аналогом предлога "в" или "на" в русском языке.

**** TODO

#+BEGIN_EXAMPLE
  わたし は だいかがく で [watashi ha daigaku de] - Я учусь в университете.
#+END_EXAMPLE

После слова тайгаку (университет) стоит частица で [de].  Она указывает на то, что
действие учиться совершается в этом месте.

** Заимствованные слова из других языков


** Формы глаголов

*** Глаголы в образованной вежливой форме
