:PROPERTIES:
:ID:       9c64447f-9474-4b29-9cc4-7be791261d98
:END:
- [[https://github.com/spring-projects-experimental/spring-native?auto_subscribed=false][spring-projects-experimental/spring-native: Spring Native provides beta support for compiling Spring applications to native executables using GraalVM native-image compiler.]]
- [[https://github.com/team-dodn/spring-boot-kotlin-template][team-dodn/spring-boot-kotlin-template: SpringBoot basic structure template based on Kotlin]]

- oleg@guixsd ~$ curl http://localhost:8981/actuator/; echo
  : {"_links":{"self":{"href":"http://localhost:8981/actuator","templated":false},"health":{"href":"http://localhost:8981/actuator/health","templated":false},"health-path":{"href":"http://localhost:8981/actuator/health/{*path}","templated":true},"info":{"href":"http://localhost:8981/actuator/info","templated":false}}}

* Learning
- [[https://github.com/christoph-gardner/springBootTutorial][christoph-gardner/springBootTutorial]]
- [[https://dzone.com/articles/deploying-microservices-spring-cloud-vs-kubernetes][Deploying Microservices: Spring Cloud vs. Kubernetes - DZone Cloud]]
- [[https://www.youtube.com/watch?v=ZIjqDIdFyBw][Getting Started with Spring Authorization Server - YouTube]]
- [[https://github.com/manuelernesto/kotlin-spring-boot-rest-api][manuelernesto/kotlin-spring-boot-rest-api: Sharing how to work with @Kotlin and @spring boot in an uncomplicated way]]
- [[https://piotrminkowski.com/2023/03/13/microservices-with-spring-boot-3-and-spring-cloud/][Microservices with Spring Boot 3 and Spring Cloud]]
- [[https://spring.io/projects/spring-authorization-server][Spring Authorization Server]]
- [[https://piotrminkowski.com/2022/11/03/spring-boot-3-observability-with-grafana/][Spring Boot 3 Observability with Grafana - Piotr's TechBlog]]
- [[https://www.youtube.com/watch?v=vUo3cTE3Y0g][Алексей Нестеров — Spring Cloud в эру Kubernetes - YouTube]]
- [[https://proglib.io/p/spring-data-mongodb][Знакомство со Spring Data MongoDB]]
- [[https://habr.com/ru/articles/755550/][Как скомпилировать Spring Boot приложение в native image с помощью GraalVm и развернуть его с помощью Docker / Хабр]]
- [[https://habr.com/ru/companies/piter/articles/580670/][Книга «Head First. Паттерны проектирования. 2-е издание» / Хабр]]
- [[https://habr.com/ru/company/jugru/blog/341026/][Что такое Spring Cloud и как его готовить – интервью с Евгением Борисовым и Кириллом Толкачёвым / Хабр]]

** Why people use Spring Boot framework?

People use the Spring Boot framework for several reasons:

    Easy to set up: Spring Boot provides an easy way to set up a new project with a minimum amount of configuration required. This makes it easier for developers to get started quickly with a new project.

    Rapid Development: With its out-of-the-box features, developers can save time by not having to write boilerplate code, which speeds up the development process.

    Versatility: Spring Boot is a highly flexible framework that can be used for developing a wide range of applications, from simple microservices to complex, enterprise-level applications.

    Integration with other technologies: Spring Boot provides seamless integration with other popular Java technologies such as Hibernate, Spring Security, and Thymeleaf, making it easier to build comprehensive applications.

    Large Community: Spring Boot has a large and active community of developers who are constantly contributing to its development and improvement. This community provides a wealth of resources and support, making it easier to find answers to any questions that arise during development.

** DTO

In Spring framework, DTO (Data Transfer Object) is a design pattern used to transfer data between layers or components of an application. It is commonly used to encapsulate and transfer data between the presentation layer (UI) and the service or persistence layer.

DTOs are often used to simplify the communication between different layers by providing a standardized way to package and transmit data. They typically contain only the relevant fields and information needed for the specific use case, and they are often immutable.

DTOs can be used to:

1. Transfer data from the database or service layer to the presentation layer.
2. Define the API contract for data exchange between different services or microservices.
3. Aggregate multiple entities or domain objects into a single object to reduce the number of network calls.

DTOs are lightweight objects that usually contain only getters and setters for the data fields they are transferring. They are not intended to contain business logic or perform computations.

In Spring, DTOs are often used in conjunction with mapping frameworks like ModelMapper or MapStruct to easily convert between DTOs and domain entities or other data objects.

The use of DTOs helps in achieving loose coupling between different layers of an application and promotes separation of concerns by keeping the business logic separate from data transfer and presentation concerns.

* Documentation

- https://spring.io/guides/gs/messaging-rabbitmq/
- https://spring.io/guides/gs/accessing-data-mongodb/
- [[https://seroter.com/2020/01/28/lets-try-out-the-new-durable-replicated-quorum-queues-in-rabbitmq/][Let’s try out the new durable, replicated quorum queues in RabbitMQ – Richard Seroter's Architecture Musings]]
- [[https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-logging][Spring Boot Features]]

* Monitoring
- [[https://github.com/Scalify/spring_exporter][Scalify/spring_exporter: Spring actuator Exporter for https://prometheus.io]]

* Programs
- [[https://github.com/weiwosuoai/WeBlog][weiwosuoai/WeBlog: 📗 Spring Boot + Vue 3.2 + Vite 前后端分离博客]]

* Libraries
- [[https://github.com/spring-projects/spring-vault][spring-projects/spring-vault: Provides familiar Spring abstractions for HashiCorp Vault]]

* Debug
#+begin_src yaml
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      com.howtodoinjava: DEBUG
      org.hibernate: DEBUG

  log4j:
    logger:
      org.springframework.web: DEBUG
#+end_src

* Alternatives
- [[https://en.wikipedia.org/wiki/Play_Framework][Play Framework - Wikipedia]]
  - [[https://habr.com/ru/sandbox/64752/][Play framework + Scala — from zero to hero / Хабр]]

* Actuator

- [[https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html][Production-ready Features]]
- https://spring.io/guides/gs/centralized-configuration/

- oleg@guixsd ~$ curl localhost:8981/actuator/refresh -d {} -H "Content-Type: application/json"

- management.endpoints.web.exposure.include=*

- [[https://habr.com/ru/company/otus/blog/650871/][Мониторинг приложения Spring Boot с помощью Micrometer, Prometheus и Grafana, используя пользовательские метрики / Хабр]]
