* Cheat sheet
:PROPERTIES:
:ID:       3ff31915-4332-439a-9a7a-a91a5e9fea9e
:END:

- [[https://www.oreilly.com/library/view/juniper-mx-series/9781449358143/ch01s02.html][Juniper MX Chassis - Juniper MX Series [Book]]]

- [[http://net.cmed.us/Home/juniper/junos-cheat-sheet][JUNOS Cheat Sheet - net]]

- configuration mode
  - single user
    : configure exclusive
  - multiple users
    : configure private

- [[https://grumbl.org/juniperdayone/Junos%20Monitoring%20and%20Troubleshooting.pdf][DAY ONE: JUNOS MONITORING AND TROUBLESHOOTING - Junos Monitoring and Troubleshooting.pdf]]

- tail logs
  : tail -f /var/log/{wtmp,snmpd,mib2d,messages,interactive-commands,chassisd}

- show down interfaces
#+begin_example
  root@sw2-mr13.intr> show ethernet-switching interfaces | match down 
  ae2.0        down   VLAN253             253   untagged blocked by STP
  ge-0/0/8.0   down   VLAN253             253   tagged   blocked by STP
  ge-0/0/10.0  down   VLAN254             254   untagged blocked by STP
  ge-0/0/16.0  down   VLAN82              82    untagged blocked by STP
  ge-0/0/22.0  down   VLAN244             244   untagged blocked by STP
  ge-0/0/41.0  down   VLAN109             109   tagged   blocked by STP
  ge-0/0/43.0  down   VLAN16              16    untagged blocked by STP
  me0.0        down   mgmt                      untagged unblocked
#+end_example

- netstat
  origin: [[https://kb.juniper.net/InfoCenter/index?page=content&id=KB21222&cat=SRX_SERIES&actp=LIST][[Junos] How to identify the process that is listening on a specific port - Juniper Networks]]
  : show system connections | no-more
  : netstat –Aa   ( to get the protocol control block, PCB)
  : fstat (to get the process using the PCB from the previous command)

- set VLAN
  : set interfaces ge-0/0/44 unit 0 family ethernet-switching vlan members VLAN253

- mtr like utility
  : traceroute monitor 8.8.8.8   

- config path
  : /config/juniper.conf.gz

- Показывает CPU, Mem and Temperature
  : show chassis routing-engine

- Перезагрузить одного члена
  : request system reboot member 1

- Сменить мастера
  : request chassis routing-engine master switch

- Удаляет не примененные команды
  : clear system commit

- show previous commit
  origin: https://www.juniper.net/documentation/en_US/junos/topics/reference/command-summary/show-system-rollback.html
  : show system rollback 1 compare 0
  : show system rollback 2 compare 1

- [[https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/ref/statement/apply-path-edit-policy-options.html][apply-path | Juniper Networks]]
  - [[https://kb.juniper.net/InfoCenter/index?page=content&id=KB29448][[M/MX/T/TX] Example - How to confirm apply-path is working - Juniper Networks]]
     : policy-options prefix-list test | display inheritance

- automate history
  : sh -c 'f() { echo cli "show system rollback $1 compare $(($1 - 1))"; }; f 3'

- show commit
  : show system commit

- rollback
  origin: https://forums.juniper.net/t5/Ethernet-Switching/Discarding-uncommitted-changes/td-p/89828
  : show | compare rollback 0

- ex4550 соединены не по спец кабелю, а через 2 10Гб порта
  : show virtual-chassis vc-port all-members

- set command length
  : set cli screen-length 0

- [[https://kb.juniper.net/InfoCenter/index?page=content&id=KB29448&actp=RSS][[M/MX/T/TX] Example - How to confirm apply-path is working - Juniper Networks]]
  - root@sr1-mr13-14> show configuration policy-options prefix-list miran | display inheritance
  - [[https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/ref/statement/apply-path-edit-policy-options.html][apply-path | Junos OS | Juniper Networks]]

- tcpdump to wireshark on a local machine
  : sshpass -p"$(pass show majordomo/private/ssh/router)" ssh sr1-dh507-508.intr -- tcpdump -w - -i ae113 -n -c 1000 | wireshark -k -i -

- show routes advertised to neighbor
  origin: http://xgu.ru/wiki/BGP_%D0%B2_Juniper
  #+BEGIN_EXAMPLE
    root@br1-mr14.intr> show route advertising-protocol bgp 78.108.80.191

    inet.0: 773477 destinations, 963660 routes (773451 active, 2 holddown, 171 hidden)
    Restart Complete
      Prefix                  Nexthop              MED     Lclpref    AS path
    ,* 78.108.80.0/24          Self                                    I
    ,* 78.108.81.0/24          Self                                    I
    ,* 78.108.82.0/23          Self                                    I
    ,* 78.108.84.0/23          Self                                    I
    ,* 78.108.86.0/23          Self                                    I
    ,* 178.250.244.0/23        Self                                    I
    ,* 178.250.246.0/23        Self                                    I
    ,* 185.84.108.0/22         Self                                    I
    ,* 185.84.108.0/23         Self                                    I
    ,* 185.84.110.0/23         Self                                    I
  #+END_EXAMPLE

- show bgp groups
  : show bgp group summary

- show configuration in set commands
  : show configuration | display set

- tail -f /var/log/{mastership,jam_dfwd,jam_chassisd,inventory,chassisd_snmp,dcd_commit_check,erp-default,dcd,chassisd,wtmp,messages,snmpd,mib2d,log-bgp}

- show logings
  : monitor start policy_session
  : monitor stop

#+BEGIN_EXAMPLE
  edit routing-options static 87.1.2.3/32
  discard
#+END_EXAMPLE

- Junos: 15.1R5.5
  : loop-detect они подвезли только в Release 20.4R1.

- Show why route is not added
#+begin_example
  root@sr1-dh507-508# run show route receive-protocol bgp 10.10.0.2 hidden extensive

  inet.0: 127 destinations, 298 routes (126 active, 0 holddown, 2 hidden)
  Restart Complete
    0.0.0.0/0 (2 entries, 1 announced)
       Nexthop: 37.153.0.96
       MED: 200
       Localpref: 100
       AS path: 12345 12346 I
       Hidden reason: rejected by import policy

    XXX.XXX.XXX.XXX/24 (1 entry, 0 announced)
       Nexthop: 10.10.0.2
       Localpref: 100
       AS path: I
       Hidden reason: rejected by import policy

  nat.inet.0: 34 destinations, 37 routes (34 active, 0 holddown, 0 hidden)
#+end_example

** [[https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/topic-map/troubleshooting-bgp-sessions.html][Troubleshooting BGP Sessions | Junos OS | Juniper Networks]]

Tasks Command or Action

*** Verify BGP Peers

- Verify BGP on an Internal Router
: show configuration

- Verify BGP on a Border Router
: show configuration

- Verify Advertised BGP Routes
: show route advertising-protocol bgp neighbor-address

- Verify That a Particular BGP Route Is Received on Your Router
: show route receive-protocol bgp neighbor-address

*** Examine BGP Routes and Route Selection 	 

- Examine the Local Preference Selection
: show route destination-prefix < detail >

- Examine the Multiple Exit Discriminator Route Selection
: show route destination-prefix < detail >

- Examine the EBGP over IBGP Selection
: show route destination-prefix < detail >

- Examine the IGP Cost Selection
: show route destination-prefix < detail >

- Examine Routes in the Forwarding Table 	
: show route forwarding-table

** commit compare

#+BEGIN_EXAMPLE
root@br1-mr14.intr> show system rollback 6 compare 11 
[edit protocols bgp group DATAIX]
-    export announce;
+    export announce-except-vlan111;
[edit protocols bgp group COMFORTEL]
-    export announce;
+    export announce-except-vlan111;
[edit protocols bgp group SERVICE-PIPE]
-    export [ then-reject announce-vlan109 ];
+    export [ announce-vlan111 then-reject ];
#+END_EXAMPLE

#+BEGIN_EXAMPLE
root@br1-mr14.intr> show system rollback 25 compare 28    
[edit protocols bgp group DATAIX]
-    export announce-except-vlan109;
+    export announce;
[edit protocols bgp group COMFORTEL]
-    export announce-except-vlan109;
+    export announce;
[edit protocols bgp group SERVICE-PIPE]
-    export [ announce-vlan109 then-reject ];
+    export [ then-reject announce-vlan109 ];
#+END_EXAMPLE


** [[https://habr.com/ru/post/320310/][Обновление JunOS на коммутаторах EX4500 в VirtualChassis — что может пойти не так? Часть 2 / Хабр]]
#+begin_example
  root@sr1-mr13-14> show virtual-chassis 

  Virtual Chassis ID: c54e.bbd5.6084
  Virtual Chassis Mode: Enabled
                                                  Mstr           Mixed Route Neighbor List
  Member ID  Status   Serial No    Model          prio  Role      Mode  Mode ID  Interface
  0 (FPC 0)  Prsnt    LX0216350058 ex4550-32f     129   Master*      N  VC   1  vcp-255/1/6
                                                                             1  vcp-255/1/7
  1 (FPC 1)  Prsnt    LX0216330173 ex4550-32f     128   Backup       N  VC   0  vcp-255/1/6
                                                                             0  vcp-255/1/7

  Member ID for next new member: 2 (FPC 2)

  {master:0}
  root@sr1-mr13-14> request session member 0 
  Password:


  --- JUNOS 15.1R5.5 built 2016-11-25 16:39:56 UTC
  root@sr1-mr13-14:RE:0% 
  root@sr1-mr13-14:RE:0% 
  root@sr1-mr13-14:RE:0% exit
  logout
  rlogin: connection closed

  {master:0}
  root@sr1-mr13-14> request session member 1    

  --- JUNOS 15.1R5.5 built 2016-11-25 16:39:56 UTC
  root@sr1-mr13-14:BK:1% 

  root@sr1-mr13-14:BK:1% cli
  warning: This chassis is operating in a non-master role as part of a virtual-chassis (VC) system.
  warning: Use of interactive commands should be limited to debugging and VC Port operations.
  warning: Full CLI access is provided by the Virtual Chassis Master (VC-M) chassis.
  warning: The VC-M can be identified through the show virtual-chassis status command executed at this console.
  warning: Please logout and log into the VC-M to use CLI.
  {backup:1}
#+end_example

* Learning
- [[https://www.youtube.com/watch?v=9csuuoyEs3Y][(10) How To Add Comments In Juniper Junos OS Configuration - YouTube]]

- [[https://www.youtube.com/watch?v=OCGZu3KMsbM][(71) Juniper Virtual Chassis: Under the Hood - YouTube]]

- [[https://www.juniper.net/documentation/us/en/software/junos/virtual-chassis-ex-8200/topics/concept/virtual-chassis-ex8200-network-port-interface-numbering.html][Network Port Interface Names on an EX8200 Virtual Chassis | Virtual Chassis User Guide for EX8200 Switches | Juniper Networks TechLibrary]]
  : type-fpc / pic / port

- fpc — Flexible PIC Concentrator. In an EX8200 Virtual Chassis, the FPC
  number indicates the slot number of the line card within the Virtual
  Chassis. The FPC number on member 0 is always 0 through 15. The FPC number
  on member 1 is always 16 through 31.

- pic — PIC (Physical Interface Card) number in interface names. On EX8200
  member switches in an EX8200 Virtual Chassis, the PIC number is always 0.

- port — Port number. On EX8200 switches, the network ports are numbered from
  left to right on each line card. On line cards that have two rows of ports,
  the ports on the top row start with 0 followed by the remaining
  even-numbered ports, and the ports on the bottom row start with 1 followed
  by the remaining odd-numbered ports.

- [[https://www.oreilly.com/library/view/junos-enterprise-switching/9780596804244/ch04.html][4. EX Virtual Chassis - JUNOS Enterprise Switching Book]]
- [[https://isp-tech.ru/tag/juniper/][Архивы Juniper - isp-tech.ru]]
- [[https://habr.com/ru/companies/rostelecom/articles/819515/][Автоматизация Juniper на Python / Хабр]]
** virtual-chassis
- [[https://blog.netpro.be/virtual-chassis-on-ex2200-switches/][Virtual Chassis on EX2200 switches | netprobe]]
- [[https://isp-tech.ru/en/juniper-qfx5100-virtual-chassis/][How to configure Virtual chassis on Juniper QFX5100 - isp-tech.ru]]
: root@sr1-mr13-14# set routing-options nonstop-routing 
: root@sr1-mr13-14# set system commit synchronize 
: root@sr1-mr13-14# set chassis redundancy graceful-switchover 
** [[https://cmdref.net/hardware/junos/traffice-monitor][How to monitor traffic on Junos SRX (like tcpdump on Linux) [cmdref.net - Cheat Sheet and Example]]]
** [[https://disnetern.ru/config-bgp-juniper-as/][configure bgp on juniper junos | IT Knowledge Base]]
** [[https://disnetern.ru/junos-%d0%bf%d0%be%d0%bb%d0%b5%d0%b7%d0%bd%d1%8b%d0%b5-%d0%ba%d0%be%d0%bc%d0%b0%d0%bd%d0%b4%d1%8b/][JunOS — полезные команды | IT Knowledge Base]]
** [[https://disnetern.ru/configuration-interfaces-juniper/][Настройка интерфейсов Juniper | IT Knowledge Base]]
** [[https://disnetern.ru/juniper/][Линейка оборудования Juniper | IT Knowledge Base]]
*** Коммутаторы
- CTP — Обеспечение надежной и эффективной работы технологий уплотнения с
  временным разделением канала (TDM) и других приложений, которые используют
  коммутацию каналов, внутри IP-сетей нового поколения.
- EX — Ethernet-коммутаторы серии EX представляют собой высокопроизводительные
  высокодоступные решения операторского класса для конвергентных сред
  филиалов, кампусов и центров обработки данных, а также для поставщиков
  услуг.
- PTX — Известные в отрасли системы конвергентного суперъядра созданы, чтобы
  обеспечить предельную производительность пакетного транспорта и
  беспрецедентную эффективность управления ядром сети.
- QFX — Коммутаторы серии QFX представляют собой высокопроизводительные
  пограничные устройства с низкой задержкой.
*** Маршрутизаторы
- ACX — Маршрутизаторы серии ACX представляют собой основу технологии Juniper
  Universal Access, благодаря адаптивной служебной архитектуре, быстрому
  развертыванию служб доступа и прозрачной платформе доставки.
- BX — Шлюзы многостанционного доступа являются частью решения для
  маршрутизации в транспортных сетях. Они позволяют решить проблемы, связанные
  с пропускной способностью канала, снизить эксплуатационную стоимость
  оборудования и в будущем может быть использовано
- ERX — Маршрутизаторы семейства Juniper Networks ERX предназначены для работы
  «на краю» сети. Они позволяют предоставлять услуги широкополосного доступа
  абонентам, использующим технологии xDSL, кабельные модемы, беспроводные сети
  и Ethernet.
- J — Маршрутизаторы Juniper Networks серии J расширяют возможности
  корпоративных приложений и обеспечивают надежную связь с удаленными офисами
  за счет высокопроизводительных средств сетевой защиты и новейших сервисов
- JCS — Идеально подходит для построения архитектур маршрутизации, отвечающих
  стандартам будущего. Она дает возможность конвергировать различные сервисы
  на едином оборудовании продвижения данных, обеспечивая четкое разграничение
  между сервисами.
- M — Надежность, стабильность, безопасность и богатая функциональность в
  сочетании с функциями для работы в сетях IP/MPLS.
- MX — Маршрутизаторы 3D Universal Edge серии MX поддерживают масштабируемость
  полосы пропускания, абонентов и служб, отвечая быстро растущим потребностям
  предприятий и поставщиков услуг в сетях любого размера.
- SRX — Архитектура динамического предоставления услуг шлюзов Services Gateway
  серии SRX обеспечивает интегрированную маршрутизацию, коммутацию и
  безопасность для систем в филиалах предприятий и в полевых условиях.
- T — В течение десяти лет маршрутизаторы ядра серии T находят применение в
  сетях крупнейших поставщиков услуг, предоставляющих проводные, мобильные,
  видео- и облачные сервисы.
- WXC — Платформы для ускорения работы приложений WXC обеспечивают надёжный
  доступ к приложениям и услугам, доступным в WAN-сети, способны обнаруживать
  и останавливать избыточные процессы, ускоряют работу протокола TCP и иных
  протоколов приложений
*** VPN
- MAG — Эти шлюзы представляют собой точки доступа с возможностью гибкой
  конвергенции для сетей VPN с шифрованием SSL и контроля доступа к сети, а
  также предоставляют службы ускорения работы приложений.
- SA — Обеспечение доступа к корпоративным ресурсам и приложениям для
  удаленных сотрудников, клиентов и партнеров предприятия из любой точки
  подключения и в любое время.
*** Межсетевые экраны
- IDP — Защита от атак на уровне сети и приложений, прежде чем сети будет
  причинен ущерб, и минимизация временных и материальных затрат, связанных с
  поддержанием безопасности сети.
- ISG — Эти высокопроизводительные шлюзы созданы специально для обеспечения
  безопасности в сети, поэтому они обладают масштабируемыми средствами
  обеспечения безопасной работы сетей и приложений и предназначены для крупных
  предприятий, операторов связи
- NetScreen — Служит для обеспечения безопасности на высокопроизводительных
  платформах межсетевых экранов/VPN на крупных предприятиях, в компаниях
  операторов связи и сетях ЦОД.
- STRM — Единое решение управления производительностью и безопасностью сети
  для предприятий и операторов связи, предлагающее функции ведения журналов,
  управления угрозами и соблюдения требований стандартов безопасности для
  продуктов производства Juniper
*** Беспроводные сети
- AX — Высокопроизводительные точки беспроводного доступа стандарта 802.11n
  (WLAN), оптимально подходящая для использования в удаленных подразделениях
  предприятий.
- CX — Решения серии CX являются простыми, гибкими и самыми надежными в
  отрасли решениями для организации беспроводной связи в сетях WAN.
- WLA — Беспроводные точки доступа серии WLA позволяют создавать сети как
  внутри, так и снаружи помещений для инфраструктур любого размера или типа с
  поддержкой низкой задержки передачи, высокой масштабируемости и
  производительности для беспроводной IP-телефонии
- WLC — Контроллеры беспроводных локальных сетей серии WLC используются для
  интеграции надежных, масштабируемых, безопасных, беспроводных локальных
  сетей в существующие инфраструктуры проводной связи в системах любого
  масштаба — от филиалов небольших компаний
- WLM — Системы управления беспроводными локальными сетями серии WLM
  унифицируют управление инфраструктурами, безопасностью и службами, давая
  администраторам сети возможность планировать, настраиваеть, развертывать,
  отслеживать и оптимизировать беспроводные сети
** juniper syslog_facility_code
Avatar
TheB.AI

In Juniper devices, the syslog_facility_code specifies the facility code used for logging messages to a syslog server. This code helps to categorize the log messages and is part of the syslog protocol.

Common facility codes include:

    0: kernel messages
    1: user-level messages
    2: mail system
    3: system daemons
    4: security/authorization messages
    5: messages generated internally by syslogd
    6: line printer subsystem
    7: network news subsystem
    8: UUCP subsystem
    9: clock daemon
    10: security/authorization messages
    11: FTP daemon
    ... and more, up to 23.

To configure the syslog facility code on a Juniper device, you would typically use the following command in the configuration mode:

plaintext

set system syslog host <hostname or IP> facility <facility_code>

For example, if you want to set the facility to local6, the command would be:

plaintext

set system syslog host <hostname or IP> facility local6

Feel free to ask if you need more detailed information or examples! 😊
Avatar
juniper syslog_facility_code 20
Avatar
TheB.AI

In the context of Juniper devices and syslog, the facility code 20 corresponds to local0. This range (local0 to local7) is reserved for custom use, allowing administrators to categorize logs based on their specific needs.

To configure your Juniper device to use the local0 facility for syslog messages, you would do it like this in configuration mode:

plaintext

set system syslog host <hostname or IP> facility local0

You can replace <hostname or IP> with the actual address of your syslog server. If you have any more questions or need further assistance, just let me know! 😊
** [[https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/ref/statement/bridge-domains-edit.html][bridge-domains allows to merge VLANS | Junos OS | Juniper Networks]]
Еще существует vepa - специально для виртуалок протокол с авто маршрутизацией,
но наши h3c его тоже не держат, нужны подороже.
** Documentation
- [[https://www.juniper.net/documentation/partners/ibm/junos11.4-oemlitedocs/config-guide-routing.pdf][Routing Protocols Configuration Guide - config-guide-routing.pdf]]
- [[https://www.juniper.net/documentation/en_US/junos/information-products/pathway-pages/junos-cli/junos-cli.pdf][Junos® OS CLI User Guide - junos-cli.pdf]]

* Misc

- [[https://www.fs.com/ru/products/11581.html][\u041c\u043e\u0434\u0443\u043b\u044c Juniper Networks EX-SFP-10GE-LR \u0421\u043e\u0432\u043c\u0435\u0441\u0442\u0438\u043c\u044b\u0439 10GBASE-LR SFP+ 1310\u043d\u043c 10\u043a\u043c \u041c\u043e\u0434\u0443\u043b\u044c SFP LR - FS \u0420\u043e\u0441\u0441\u0438\u044f]]
- [[https://habr.com/en/sandbox/80771/][Полезные команды]]

set interfaces ge-0/0/0.0 family inet address 192.168.60.3/24
set interfaces ge-0/0/1.0 family inet address 192.168.60.71/24
set interfaces ge-0/0/2.0 family inet address 192.168.60.72/24
set interfaces ge-0/0/3.0 family inet address 192.168.60.73/24
set interfaces ge-0/0/4.0 family inet address 192.168.60.74/24

set security zones security-zone trust interfaces ge-0/0/1 host-inbouinterfaces ge-0/0/2 host-inbound-traffic system-services all
set security zones security-zone trust interfaces ge-0/0/2 host-inbouinterfaces ge-0/0/2 host-inbound-traffic system-services all
set security zones security-zone trust interfaces ge-0/0/3 host-inbouinterfaces ge-0/0/2 host-inbound-traffic system-services all
set security zones security-zone trust interfaces ge-0/0/4 host-inbouinterfaces ge-0/0/2 host-inbound-traffic system-services all

#+begin_example
  root@br1-mr14.intr> show system rollback 5 compare 1    
  [edit protocols bgp group COMFORTEL]
  -    export announce-except-vlan80;
  +    export announce;
  [edit protocols bgp group SERVICE-PIPE]
  -    export announce-vlan80;
  +    export then-reject;
  [edit protocols bgp group PROMETEY]
  -    export announce-except-vlan80;
  +    export announce;
#+end_example

#+begin_example
root@sr1-mr13-14> show route table nat.inet.0 78.108.82.41 

nat.inet.0: 7 destinations, 9 routes (7 active, 0 holddown, 0 hidden)
+ = Active Route, - = Last Active, * = Both

0.0.0.0/0          *[Static/5] 45w6d 09:28:16
                    > to 172.16.103.254 via vlan.253

{master:0}
#+end_example

* Monitoring



#+begin_example
  awk '/Out/ && /IP/ && !/missing/ { print $4, $6 }' | sort | uniq -c | sort -n
#+end_example

* Virtualization
- [[https://prudnitskiy.pro/2009/07/11/juniper-emu/][Эмуляция Juniper M на PC]]

* DHCP

Попробовал обновить адрес на другом IPMI - он тоже пропал.  Повис DHCP.

#+begin_example
  error: the dhcp subsystem is not responding to management requests
  root@sr1-mr13-14> restart dhcp gracefully 
  Dynamic Host Configuration Protocol process started, pid 13558
#+end_example

* Misc

  list logs
  #+begin_src bash
    #!/usr/bin/env bash
    
    set -x
    
    mapfile -t files <(sshpass -p"$(pass show majordomo/public/ssh/router)" ssh br1-mr14.intr -- find /var/log -maxdepth 1 -type f -mmin -10 -not -name wtmp)
    
    for file in "${files[@]}"
    do
        echo "$file"
    done
  #+end_src

* Firewall

- [[https://www.juniper.net/documentation/en_US/junos/topics/task/troubleshooting/firewall-filter-ex-series.html][Troubleshooting Firewall Filters - TechLibrary - Juniper Networks]]
пишет то, что я выше присылал
например

vlan {
        unit 500 {
            family inet {
                filter {
                    input rules;
                }
                address 178.238.125.94/30;
            }
        }
}

если не влезет фильтр rules, то интерфейс будет висеть без fw
чтоб опять включить нужно закоммитить конфиг без этого фильтра и потом опять его добавить в меньшем размере

#+begin_example
  root@sr1-dh507-508# commit
  [edit protocols]
    'bgp'
      warning: requires 'bgp' license
  configuration check succeeds
  fpc1:
  commit complete
  commit complete

  {master:0}[edit policy-options prefix-list noc-allow-ssh]
  root@sr1-dh507-508#
  Message from syslogd@sr1-dh507-508 at Jan 27 16:24:20  ...
  sr1-dh507-508 backup dfw_grph_merge_dfw_bind: rules for filter rules will not be installed

  Message from syslogd@sr1-dh507-508 at Jan 27 16:24:20  ...
  sr1-dh507-508 master dfw_grph_merge_dfw_bind: rules for filter rules will not be installed

  {master:0}[edit policy-options prefix-list noc-allow-ssh]
  root@sr1-dh507-508#
#+end_example

и тут фаервол уже не пашет

16:47
ex4550 софтовый firewall, mx80 хардверный
если я правильно запомнил что мне как-то сказали

16:49
не, они оба хардовые вроде
посмотреть текущие таблицы можно так:

root@sr1-dh507-508:RE:0% vty fpc0
PFEM0(vty)# show tcam vendor 1 rules



ну show pfe pfem extensive перестал показывать отрицательные значения
наверное что-то починилось



unit 0 {
    family inet {
        ##
        ## Warning: configuration block ignored: unsupported platform (ex4550-32f)
        ##
        ##
        ## Warning: Requires forwarding-options sampling or packet-capture config
        ##
        sampling {
            input;
            output;
        }
        address 10.70.0.22/30;
        address 10.70.0.26/30;
    }
    ##
    ## Warning: Family ethernet-switching and rest of the families are mutually exclusive
    ##
    family ethernet-switching {
        port-mode trunk;
        vlan {
            members all;
        }
    }
}

* lldpd

#+begin_example


  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12
  13
  14
  15
  16
  17
  18
  19
  20
  21
  22
  23
  24
  25
  26
  27
  28
  29
  30
  31
  32

  [root@deprecated-web29:~]# lldpctl
  -------------------------------------------------------------------------------
  LLDP neighbors:
  -------------------------------------------------------------------------------
  Interface:    eno1, via: LLDP, RID: 1, Time: 0 day, 00:00:10
    Chassis:
      ChassisID:    mac 64:64:9b:ac:5c:40
      SysName:      sw2-mr13.intr
      SysDescr:     Juniper Networks, Inc. ex2200-48t-4g , version 12.3R6.6 Build date: 2014-03-13 07:02:54 UTC
      Capability:   Bridge, on
      Capability:   Router, on
    Port:
      PortID:       local 592
      PortDescr:    web29
      TTL:          120
      MFS:          1514
      PMD autoneg:  supported: yes, enabled: yes
        Adv:          10Base-T, HD: yes, FD: yes
        Adv:          100Base-TX, HD: yes, FD: yes
        Adv:          1000Base-T, HD: no, FD: yes
        MAU oper type: unknown
    VLAN:         253, pvid: no VLAN253
    LLDP-MED:
      Device Type:  Network Connectivity Device
      Capability:   Capabilities, yes
      Capability:   Policy, yes
      Capability:   Location, yes
      Capability:   MDI/PSE, yes
    Unknown TLVs:
      TLV:          OUI: 00,90,69, SubType: 1, Len: 12 43,55,30,32,31,34,32,39,30,35,34,34
  -------------------------------------------------------------------------------
#+end_example

показывает

  Port:
    PortID:       local 592
    PortDescr:    web29

В целом можно определить, если зайти на джун

Logical interface ge-0/0/42.0 (Index 116) (SNMP ifIndex 592)
Description: web29

* Tools

- [[https://github.com/ckishimo/juniper_display_set][ckishimo/juniper_display_set: Script to translate a Junos configuration file into a list of 'set' commands]]
- [[https://github.com/zengxinhui/juniper_display_set][zengxinhui/juniper_display_set: This script converts standard Juniper config into a list of 'set' commands which you can use to configure a Juniper device]]

* ChatGPT

** To clear the ARP cache in Junos:

    Enter operational mode on the Junos device by typing cli from configuration mode.

    Run the following command to clear the ARP cache:

    clear arp

Clearing the ARP cache can sometimes resolve connectivity issues related to MTU settings.

Remember, before making any changes to your network devices, it's recommended to schedule maintenance windows and exercise caution to minimize any impact on network connectivity.
