- [[https://github.com/kubevirt/kubevirt/blob/main/docs/vm-configuration.md][kubevirt/vm-configuration.md at main · kubevirt/kubevirt]]
- [[https://www.youtube.com/watch?v=Z9hBIoO4KOs&t=2490s][(91) KubeVirt deep dive - YouTube]]
- [[https://kubevirt.io/quickstart_minikube/][KubeVirt quickstart with Minikube | KubeVirt.io]]
- [[https://github.com/kubevirt/containerized-data-importer][kubevirt/containerized-data-importer: Data Import Service for kubernetes, designed with kubevirt in mind.]]
- [[https://github.com/k8snetworkplumbingwg/ovs-cni][k8snetworkplumbingwg/ovs-cni: Open vSwitch CNI plugin]]
- [[https://github.com/kubevirt/kubevirt/issues/6665][Is there a way to attach virtual machine storage to a LVM Group? · Issue #6665 · kubevirt/kubevirt]]
  - [[https://github.com/topolvm/topolvm][topolvm/topolvm: Capacity-aware CSI plugin for Kubernetes]]
- [[https://linbit.com/blog/using-drbd-block-devices-for-kubevirt/][Using DRBD block devices for kubevirt » LINBIT]]
- [[https://events19.linuxfoundation.org/wp-content/uploads/2018/07/Running-Legacy-VMs-with-Kubernetes.pdf][KubeVirt - Running-Legacy-VMs-with-Kubernetes.pdf]]
- [[https://kubevirt.io/2019/KubeVirt_storage_rook_ceph.html][Persistent storage of your Virtual Machines in KubeVirt with Rook | KubeVirt.io]]
- [[https://habr.com/ru/company/otus/blog/649367/][Мониторинг устаревших виртуальных машин и их приложений — «метод Kubernetes» / Хабр]]
- [[https://livewyer.io/blog/2021/02/23/kubevirt-showcase-a-kubernetes-cluster-within-a-kubernetes-cluster/][LiveWyer | Cloud Native Architecture Experts | KubeVirt Showcase: A Kubernetes Cluster within a Kubernetes Cluster]]
- [[https://github.com/Tedezed/kubevirt-images-generator][Tedezed/kubevirt-images-generator: Easy Kubevirt images generator - Public images repository 💿]]
- [[https://kubevirt.io/2020/OKD-web-console-install.html][Managing KubeVirt with OpenShift Web Console | KubeVirt.io]]

* learning
- [[https://www.cncf.io/wp-content/uploads/2020/08/Fast_Packet_Processing_v1.pdf][Fast_Packet_Processing_v1.pdf]]
- [[https://www.youtube.com/watch?v=cPA6nN5lvoM][(58) High Performance KubeVirt in Action - YouTube]]

* cdi

oleg@guixsd ~$ kubectl delete pvc/demo-vm-pv
persistentvolumeclaim "demo-vm-pv" deleted

oleg@guixsd ~$ kubectl get pvc -A
NAMESPACE   NAME                 STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default     demo-vm-pv-scratch   Bound         pvc-8a68838b-b6ff-46e3-a4c7-058a7b1107c3   2Gi        RWO            local-path     20m
default     demo-vm-pv           Bound         pvc-852f1d10-a8cc-4069-97c0-585f0563de04   2Gi        RWO            local-path     3d1h

* [[https://docs.openshift.com/container-platform/4.7/virt/virtual_machines/advanced_vm_management/virt-configuring-pxe-booting.html][Configuring PXE booting for virtual machines | OpenShift Virtualization | OpenShift Container Platform 4.7]]

#+begin_src yaml
  apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachineInstance
  metadata:
    creationTimestamp: null
    labels:
      special: vmi-pxe-boot
    name: vmi-pxe-boot
  spec:
    domain:
      devices:
        disks:
        - disk:
            bus: virtio
          name: containerdisk
          bootOrder: 2
        - disk:
            bus: virtio
          name: cloudinitdisk
        interfaces:
        - masquerade: {}
          name: default
        - bridge: {}
          name: pxe-net
          macAddress: de:00:00:00:00:de
          bootOrder: 1
      machine:
        type: ""
      resources:
        requests:
          memory: 1024M
    networks:
    - name: default
      pod: {}
    - multus:
        networkName: pxe-net-conf
      name: pxe-net
    terminationGracePeriodSeconds: 0
    volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt/fedora-cloud-container-disk-demo
    - cloudInitNoCloud:
        userData: |
          #!/bin/bash
          echo "fedora" | passwd fedora --stdin
      name: cloudinitdisk
  status: {}
#+end_src

Fix "reply from unexpected source"
: dig +short a gnu.org @10.43.0.10
modprobe br_netfilter
thanks [[https://stackoverflow.com/questions/48148838/kube-dns-error-reply-from-unexpected-source][kubernetes - kube-dns error: reply from unexpected source - Stack Overflow]]

* PVC

#+begin_example
  oleg@guixsd ~/.local/share/chezmoi/dotfiles/kubernetes/kubevirt/guix$ virtctl image-upload --pvc-name=guix-vm-pv --pvc-size=10Gi --image-path=$PWD/guix.qcow2 --uploadproxy-url=https://10.43.57.196 --insecure
  PVC default/guix-vm-pv not found
  PersistentVolumeClaim default/guix-vm-pv created
  Waiting for PVC guix-vm-pv upload pod to be ready...
  Pod now ready
  Uploading data to https://10.43.57.196

   426.38 MiB / 426.38 MiB [==========================================================================================================================================================] 100.00% 1s

  Uploading data completed successfully, waiting for processing to complete, you can hit ctrl-c without interrupting the progress
  Processing completed successfully
  Uploading /home/oleg/.local/share/chezmoi/dotfiles/kubernetes/kubevirt/guix/guix.qcow2 completed successfully
#+end_example

** [[https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner][kubernetes-sigs/sig-storage-local-static-provisioner: Static provisioner of local volumes]]

  The local volume static provisioner manages PersistentVolume lifecycle for
  pre-allocated disks by detecting and creating PVs for each local disk on the
  host, and cleaning up the disks when released. It does not support dynamic
  provisioning.

- [[https://scribe.rip/alterway/kubernetes-local-static-provisioner-4c197e0f83ab][Kubernetes local static provisioner]]

** [[https://github.com/kubevirt/hostpath-provisioner-operator][kubevirt/hostpath-provisioner-operator]]

- [[https://www.sobyte.net/post/2022-05/kubevirt/][Kubevirt Managing Virtual Machines - SoByte]]

* Delete

[[https://bytemeta.vip/repo/kubevirt/hyperconverged-cluster-operator/issues/1408][Error from server (InternalError): Internal error occurred: failed calling webhook "kubevirt-update-validator.kubevirt.io": Post https://kubevirt-operator-webhook.kubevirt-hyperconverged.svc:443/kubevirt-validate-update?timeout=10s: no endpoints available for service "kubevirt-operator-webhook" - bytemeta]]

#+begin_quote
It was cleared by deleting ValidatingWebhookConfiguration and
MutatingWebhookConfiguration. After deleting all resources from both, then I
can clearly delete kubevirt CRD and Kubevirt-Hyperconverged. So close the
issue.
#+end_quote

: for a in $(kubectl get apiservices | grep kube | awk '{ print $1 }'); do kubectl delete apiservices "$a"; done

: kubectl delete ValidatingWebhookConfiguration virt-operator-validator
validatingwebhookconfiguration.admissionregistration.k8s.io "virt-operator-validator" deleted

: kubectl -n kubevirt patch kv kubevirt --type=merge -p '{"metadata":{"finalizers":[]}}'
kubevirt.kubevirt.io/kubevirt patched

* Cheat sheet

#+begin_example
  $ virtctl vnc vm-nixos1-datavolume                                                                          [36/36]
  You are using a client virtctl version that is different from the KubeVirt version running in the cluster
  Client Version: v0.53.0
  Server Version: v0.55.0
  Can't access VMI vm-nixos1-datavolume: Internal error occurred: dialing virt-handler: could not verify peer certificate: x509: certificate has expired or is not yet valid: current time 2022-08
  -06T04:10:48Z is after 2022-08-05T18:56:56Z
#+end_example

#+begin_example
  $ kubectl delete pods --namespace kubevirt -l kubevirt.io
#+end_example

** All virtualmachineinstance failed

After cluster restart all virtualmachineinstance are in =failed= state.

#+begin_example
  NAMESPACE   NAME                                                      AGE   PHASE     IP           NODENAME   READY   LIVE-MIGRATABLE   PAUSED
  default     virtualmachineinstance.kubevirt.io/vm-guix0-datavolume    57s   Failed   10.1.52.55   kube7      True    False
  default     virtualmachineinstance.kubevirt.io/vm-nixos0-datavolume   57s   Failed   10.1.52.54   kube7      True    False
  default     virtualmachineinstance.kubevirt.io/vm-nixos1-datavolume   57s   Failed   10.1.52.53   kube7      True    False
  default     virtualmachineinstance.kubevirt.io/vm-nixos2-datavolume   57s   Failed   10.1.52.56   kube7      True    False
  default     virtualmachineinstance.kubevirt.io/vm-nixos3-datavolume   57s   Failed   10.1.52.57   kube7      True    False
#+end_example

The following fixed the issue.

#+begin_example
  $ kubectl delete --all pods --namespace=kubevirt
#+end_example
