#+TITLE: links

* Links
** [[https://github.com/mooz/keysnail][mooz/keysnail: Allows you to bind commands to key sequences in Mozilla Firefox]]
 KeySnail is an add-on for Mozilla Firefox that aims to be a competitor and lightweight alternative to Vimperator. Unlike Vimperator, KeySnail provides comfortable browsing experience for Emacs users, but its target users are not limited to.
** [[https://github.com/viewvc/viewvc][viewvc/viewvc: ViewVC is a browser interface for CVS and Subversion version control repositories.]]
 ViewVC is a browser interface for CVS and Subversion version control repositories. It generates templatized HTML to present navigable directory, revision, and change log listings. It can display specific versions of files as well as diffs between those versions. Basically, ViewVC provides the bulk of the report-like functionality you expect out of your version control tool, but much more prettily than the average textual command-line program output.
 Features

     Support for filesystem-accessible CVS and Subversion repositories.
     Support for path-based authorization, including parsing and honoring Subversion authz configuration files.
     RSS feed generation for tracking changes to repositories or individual items within repositories.
     Individually configurable virtual host support.
     Line-based annotation/blame display.
     Revision graph capabilities (via integration with CvsGraph) (CVS only).
     Syntax highlighting support.
     Bonsai-like repository query facilities.
     Template-driven output generation.
     Colorized, side-by-side differences.
     Tarball generation (by tag/branch for CVS, by revision for Subversion).
     Localization support based on the Accept-Language request header.
     Ability to run either as CGI script or as a standalone server.
     Regexp-based file searching.
     INI-like configuration file (as opposed to requiring actual code tweaks).

 Requirements

 The only hard software requirement for running ViewVC is a suitable version of Python. The specifics of that, as well as all other requirements, depend on what you want to do with the tool. As those have changed somewhat over the years, it's best to consult the INSTALL file of the specific ViewVC release you wish to evaluate for its exact requirements. Here are pointers to the INSTALL files for the current major release lines:

     ViewVC 1.1.x
     Unreleased bleeding edge (1.2-dev)
** [[https://discordapp.com/][Discord - Free Voice and Text Chat for Gamers]]
 It’s time to ditch Skype and TeamSpeak.

 All-in-one voice and text chat for gamers that’s free, secure, and works on
 both your desktop and phone. Stop paying for TeamSpeak servers and hassling
 with Skype. Simplify your life.
** [[https://github.com/ZZROTDesign/docker-clean][ZZROTDesign/docker-clean: A script that cleans docker containers, images, volumes, and networks.]]
 A simple Shell script to clean up the Docker Daemon.
** [[https://github.com/dmgerman/org-manage][dmgerman/org-manage: org-manage]]
 This is a module to help managing a large collection of org files. It is based
 on org-octopress by Yoshinari Nomura.
** [[https://github.com/kiwanami/emacs-ctable][kiwanami/emacs-ctable: Table Component for elisp]]
 ctable.el is a table component for emacs lisp. Emacs lisp programs can display
 a nice table view from an abstract data model. The many emacs programs have the
 code for displaying table views, such as dired, list-process, buffer-list and
 so on. So, ctable.el would provide functions and a table framework for the
 table views.
** [[https://www.youtube.com/watch?v=Y8VNiybERVU][Сравнение императивного и функционального программирования на примере Python и Haskell (Артём Канев) - YouTube]]
 Выступление Артёма Канева 6 августа 2015 г. "Сравнение императивного и
 функционального программирования на примере Python и Haskell. Плюсы и минусы"

 Большей частью внимание уделено Haskell. Поскольку в Haskell нет циклов и
 переменных (переменные эмулируются другими средствами языка), то имеет смысл
 начать с самого начала, то есть с управления состоянием и обхода разного рода
 массивов. По восходящей подберемся к созданию простенького REST приложения на
 обоих языках. Надеюсь, получится отразить как можно больше косяков обоих
 подходов.
** [[https://www.youtube.com/watch?v=t8gim17hryw][MuniHac 2016: Hakyll - YouTube]]
 A keynote talk at MuniHac 2016 given by Jasper Van der Jeugt.

 Hakyll is a static site generator written in Haskell. It is more like a library
 than a conventional application, since the configuration is done in Haskell as
 well -- a bit like Xmonad. In this talk, we will give a high-level overview of
 the advantages of static site generators in general and build a quick site
 together. After that, we will dive a bit deeper and examine how semi-automatic
 dependency tracking works in the library.

 See also MuniHac 2016: http://www.munihac.de

 Recorded at TNG Technology Consulting / http://www.tngtech.com at 2nd of
 September 2016 at Unterföhring near Munich
** [[http://ergoemacs.org/emacs/emacs_eww_web_browser.html][Emacs: Using Eww Web Browser]]
 How to make emacs always use eww?
** [[https://github.com/appleshan/my-spacemacs-config][appleshan/my-spacemacs-config: My personal Spacemacs config]]
 Hacking 始于 2012 年。2015 年爱上 Spacemacs 😄 💖

 我的 Spacemacs 配置一共有两部分： 一个 .emacs.d 目录，是 Spacemacs 的原始代码，未做任何修改； 一个 .spacemacs.d 目录，存放私有 layer。
** [[https://github.com/Fanael/rainbow-identifiers][Fanael/rainbow-identifiers: Rainbow identifier highlighting for Emacs]]
 Rainbow identifiers mode is an Emacs minor mode providing highlighting of identifiers based on their names. Each identifier gets a color based on a hash of its name.
** [[https://github.com/ankurdave/color-identifiers-mode][ankurdave/color-identifiers-mode: Emacs minor mode to highlight each source code identifier uniquely based on its name]]
 Color Identifiers is a minor mode for Emacs that highlights each source code identifier uniquely based on its name. It is inspired by a post by Evan Brooks.

 Currently it supports Scala (scala-mode2), JavaScript (js-mode and js2-mode), Ruby, Python, Emacs Lisp, Clojure, C, C++, and Java. You can add support for your favorite mode by modifying color-identifiers:modes-alist and optionally calling color-identifiers:set-declaration-scan-fn.

 Check out the demo.
** [[https://julien.danjou.info/projects/emacs-packages][Emacs packages | Julien Danjou]]
 rainbow-mode is a minor mode for Emacs which displays strings representing colors with the color they represent as background.
** [[https://github.com/syl20bnr/nyan-mode][syl20bnr/nyan-mode: Nyan Cat for Emacs! Nyanyanyanyanyanyanyanyanyan!]]
 Fork modifications

     the starting nyan cat image has no rainbow behind it,
     the starting rainbow image has zigzags,
     the animation loop is not endless and occurs only when nyan cat moves.

 Introduction

 WARNING, MIND DUMBING CONTENT INSIDE.

 “Nyan-mode. It’s things like this that make me proud to be an emacs user.” - mitchellh

 Nyanmacs is expanding!! Read the story so far! :).
** [[https://github.com/petervanderdoes/gitflow-avh][petervanderdoes/gitflow-avh: AVH Edition of the git extensions to provide high-level repository operations for Vincent Driessen's branching model]]
 A collection of Git extensions to provide high-level repository operations for Vincent Driessen's branching model. This fork adds functionality not added to the original branch.
** [[https://github.com/jtatarik/magit-gitflow][jtatarik/magit-gitflow: GitFlow plugin for magit.el]]
 GitFlow plugin for magit.el
** [[https://www.youtube.com/watch?v=Qve7g0LB7ao&list=PLIcAMDxr6tppz0MDTAj7aj23_E6FwrRfO&index=1][Javascript - #1 - Прототипное наследование - YouTube]]
 В этом уроке мы разберем как реализуются классы, что такое прототипы, как создавать экземпляры классов и как реализовывать наследование в Javascript.
 Смотрите больше видео по AngularJS на нашем сайте.
 Текст и исходный код урока смотрите на http://monsterlessons.com/project/les...
** [[http://jblevins.org/projects/deft/][Deft for Emacs]]
 Deft is an Emacs mode for quickly browsing, filtering, and editing directories of plain text notes, inspired by Notational Velocity. It was designed for increased productivity when writing and taking notes by making it fast and simple to find the right file at the right time and by automating many of the usual tasks such as creating new files and saving files.
** [[https://github.com/rejeep/prodigy.el][rejeep/prodigy.el: Manage external services from within Emacs]]
 Manage external services from within Emacs

 I came up with the idea when I got to work one Monday morning and before I could start working I had to manually start ten or so services.

 To get rid of this tedious work, I started working on this Emacs plugin, which provides a nice and simple GUI to manage services.
** [[https://www.youtube.com/watch?v=EUrfyfQc_2o][4 Free Resources: Save Time Choosing Your Next Machine Vision Camera - YouTube]]
 Welcome to the Point Grey Youtube Channel where we talk about all things related to machine vision cameras. As a thank you for stopping by here are 4 links to our time-saving resources.
 1) Camera Sensor Review: http://www.ptgrey.com/point-grey/10845
 2) How to Calculate Camera Sensitivity - Understanding and using the EMVA1288 standard (Video and White Paper): http://www.ptgrey.com/white-paper/id/...
 3) Camera Selector Tool: http://www.ptgrey.com/Camera-selector
 4) Resolution vs Frame Rates:https://www.ptgrey.com/point-grey/10902

 Want to talk cameras? Email me at michael.jacoby(at)ptgrey.com or @mikeyjacoby (twitter)
** [[https://www.youtube.com/user/MrBrainMurder/about][Светослав Нинов - YouTube]]


 Autodesk Advance Steel видео, уроки, туториалы
** [[https://www.youtube.com/channel/UCDJBKl1AuqVcXpf9PMDV7rQ][Bal5.info - YouTube]]
  Наша команда представляет вам: -Видео уроки Инженерной графики и Начертательной геометрии
** [[https://github.com/getpelican/pelican-plugins/tree/master/sitemap][pelican-plugins/sitemap at master · getpelican/pelican-plugins]]
 This plugin generates plain-text or XML sitemaps. You can use the SITEMAP variable in your settings file to configure the behavior of the plugin.
** [[https://support.google.com/webmasters/answer/156184][Learn about sitemaps - Search Console Help]]
 A sitemap is a file where you can list the web pages of your site to tell Google and other search engines about the organization of your site content. Search engine web crawlers like Googlebot read this file to more intelligently crawl your site.
** [[https://support.google.com/webmasters/answer/182072?hl=en][Googlebot - Search Console Help]]
 Googlebot is Google's web crawling bot (sometimes also called a "spider"). Crawling is the process by which Googlebot discovers new and updated pages to be added to the Google index.
** [[https://www.youtube.com/watch?v=O0UgY-DmFbU][Emacs Rocks! Episode 01: From var to this - YouTube]]
 http://emacsrocks.com - Rocking emacs tricks and tips screencast.
** [[https://www.flickr.com/photos/tags/emacs][emacs photos on Flickr | Flickr]]
 Sacha Chua's photos
** [[https://media.libreplanet.org/][GNU MediaGoblin]]
  This site hosts media about free software and the amazing community that uses and builds it. Much of the media is from our yearly LibrePlanet conference in Cambridge, MA, USA, but some is from other events.

 This site and the conference are run by the Free Software Foundation, a nonprofit with three decades of experience promoting and defending computer user freedom. The site itself is running GNU MediaGoblin, a wonderful free media hosting platform. Enjoy!
** [[https://www.youtube.com/watch?v=WARpRQ3XBEY][10 Самых ожидаемых аниме зимы 2017 года по мнению японцев - YouTube]]
 10 Самых ожидаемых аниме зимы 2017 года по мнению японцев
 HelloPal: https://goo.gl/dblmhl
 В этом видео я рассказываю о 10 самых ожидаемых аниме зимы 2017 года по мнению японцев. Этой зимой выходит довольно много картин различного жанра, но пользовательским голосованием в Японии были выбраны именно эти 10 аниме. Согласны ли вы с этим рейтингом? Какой у вас топ 10 самых ожидаемых аниме зимы 2017 года?
** [[http://vimgolf.com/][VimGolf - real Vim ninjas count every keystroke!]]
 Real Vim ninjas count every keystroke - do you?
** [[https://www.youtube.com/watch?v=wQiobWLa6k4][Можно ли припаять 6 пин разъём на видеокарту если его нет - YouTube]]

 Можно ли припаять 6 пин разъём на видеокарту если его нет
** [[https://www.youtube.com/watch?v=f6ji-QcOo_U][Learn Python Programming for Free Today! - YouTube]]
 Learn Python Programming and take your programming skills to the next level in this free screen capture HD video tutorial course. You will start with installing Python and going through your first program, before navigating through the interfaces and moving into Object Orientated Programming. Get access to the full course at a huge 95% discount, which has 8+ hours of HD video at https://www.udemy.com/learn-python-3-...

 You get a comprehensive free course here covering the basics of Python Programming. The amazing thing is that you will be able to learn this in one day and take your skills to an expert level. Here is a complete list of what you will learn so that you can skip to any important parts.
** [[https://www.youtube.com/user/anilibriatv/about][AniLibria.Tv - YouTube]]


 AniLibria - некоммерческий проект по озвучиванию и адаптации зарубежных сериалов, мультфильмов и аниме, аниме-обзорам, видеоблогам, рецензиям.

 Нашей особенностью является стабильная и качественная работа над тем контентом, который мы предоставляем пользователям.
 Нашей целью является достижение большой популярности ресурса AniLibria.Tv, чтобы впоследствии начать озвучивать аниме в дубляже по лицензии от Японцев и/или выпускать на постоянной основе собственные мультфильме в стиле, максимально приближенном к аниме.
 Наши успехи на данном этапе: сейчас мы обошли большинство своих конкурентов в озвучивании, впереди остаются лишь наши вечные конкуренты по имени AniDub.
** [[http://www.anilibria.tv/][AniLibria.TV - Так звучит аниме! Озвучка аниме для домашнего просмотра.]]
  Вы можете смотреть аниме онлайн или скачать аниме с трекера, а так же заказать аниме на озвучку для бесплатного домашнего ознакомительного просмотра. Все материалы на сайте предоставлены только для ознакомления, вы обязаны удалить их в течение суток после скачивания, в случаях нарушения авторских прав - обращайтесь на почту lupin@anilibria.tv и мы решим вашу проблему. Самая качественная озвучка для бесплатного просмотра на бесплатной основе - AniLibria.TV, заходите к нам, у нас вам всегда рады!
** [[http://dic.academic.ru/][Словари и энциклопедии на Академике]]
 Экспорт словарей на сайты, сделанные на PHP,
 Joomla,
 Drupal,
 WordPress, MODx.
** [[http://www.blinn.edu/brazos/matheng/jcoffelt/graphics/files/ege/ortho/ortho_page5.htm][Line Creation]]
 Rules of Line Creation and Use
** [[http://www.artrecept.com/risunok/zhivotnye/][Как рисовать животных: кошку собаку медведя слона]]
 Нашу планету населяет огромное количество видов животных, и все они обладают своими особенностями, яркими отличительными чертами. Каждое живое существо по-своему интересно, красиво и уникально.
** [[https://www.youtube.com/watch?v=GSJ4BXsR5Xw][GPL LGPL BSD MIT EULA MADNESS! - YouTube]]
 The differences between common software licenses in use today.
** [[http://kodi.wiki/view/backup][Just a moment...]]
  DDoS protection by CloudFlare
** [[https://github.com/spiderbit/kodi-remote.el][spiderbit/kodi-remote.el: Emacs Remote Control functions for Kodi]]
 Emacs Remote Control for Kodi Including a function to send youtube and other urls to kodi

     see youtube-dl for supported sites
** [[https://github.com/K0HAX/spacemacs-emms][K0HAX/spacemacs-emms: Emms layer for Spacemacs]]
 The main purpose of this elisp is to install EMMS inside Spacemacs.
** [[https://github.com/dochang/emms-player-mpv][dochang/emms-player-mpv: mpv support for EMMS]]
 This library provides a player that uses mpv for EMMS. It supports pause and seeking. For loading subtitles automatically, try adding autosub-match=fuzzy to your ~/.mpv/config, see mpv manual for more.

 This library is based on `emms-player-mplayer.el' in EMMS.
** [[https://github.com/pft/mingus][pft/mingus: GNU Emacs control of Music Player Daemon (MPD)]]
 Mingus is a frontend for GNU Emacs to the Music Player daemon. The interface closely, though not strictly, resembles that of ncmpc, which I had been using before (the main drawback of ncmpc for me was it’s apparent lack of support for unicode). It has some advantages over other clients, mainly in the field of playlist editing. This is achieved through marking and regions as you are used too in emacs and in dired. Mingus also provides a point-of-insertion for inserting new songs. This can be handy to drop a song after the currently playing one (enqueue), but is more flexible. Mingus is distributed under the GPL.
** [[https://www.gnu.org/manual/manual.html][GNU Manuals Online - GNU Project - Free Software Foundation]]
 This table lists official GNU packages with links to their primary documentation, where available. When a package has several associated manuals, they are all listed. If a package has no specific manual online, the link just goes to the package's home page (which is also linked to explicitly).
** [[https://www.gnu.org/software/libc/][The GNU C Library]]
 What is glibc?

 The GNU C Library project provides the core libraries for the GNU system and GNU/Linux systems, as well as many other systems that use Linux as the kernel. These libraries provide critical APIs including ISO C11, POSIX.1-2008, BSD, OS-specific APIs and more. These APIs include such foundational facilities as open, read, write, malloc, printf, getaddrinfo, dlopen, pthread_create, crypt, login, exit and more.

 The GNU C Library is designed to be a backwards compatible, portable, and high performance ISO C library. It aims to follow all relevant standards including ISO C11, POSIX.1-2008, and IEEE 754-2008.

 The project was started circa 1988 and is almost 30 years old. You can see the complete project release history on the wiki.

 Despite the project's age there is still a lot to do so please Get Started and Get Involved!
 Current Status

 The GNU C Library releases every 6 months. See the NEWS file in the glibc sources for more information.

     The current stable version of glibc is 2.24, released on August 5, 2016.
     The current development version of glibc 2.25, releasing on or around February 1, 2017.
** [[https://github.com/franziskuskiefer/app-keys-gnome-shell-extension][franziskuskiefer/app-keys-gnome-shell-extension: Unity-like shortcuts for gnome dock applications]]
 Adds Super+NUM shortcuts for activating applications from dash. Extension can be installed from https://extensions.gnome.org/extension/413/dash-hotkeys/
** [[https://github.com/phocean/TopIcons-plus][phocean/TopIcons-plus]]
 Topicons Plus is an alternative to the Gnome Shell Legacy Tray, which is hidden most of the time and generally considered inconvenient.

 It brings all icons to back to the top panel, as with most desktop environments.
** [[https://www.youtube.com/channel/UCTF-G2t8p9toWdhe3777waw/about][Simple BSD - YouTube]]
  Joined Mar 10, 2015
** [[https://www.gnu.org/manual/manual.html][GNU Manuals Online - GNU Project - Free Software Foundation]]
 This table lists official GNU packages with links to their primary documentation, where available. When a package has several associated manuals, they are all listed. If a package has no specific manual online, the link just goes to the package's home page (which is also linked to explicitly).

 Many packages could be listed in any of several categories, but for the table here just one has to be chosen, usually following the Free Software Directory.
** [[https://www.gnu.org/software/gnu-c-manual/][The GNU C Reference Manual - GNU Project - Free Software Foundation]]
  The GNU C Reference Manual is a reference for the C programming language, as implemented by the GNU C Compiler.

 This manual is strictly a reference, not a tutorial. Its aim is to cover every linguistic construct in GNU C, but not the library functions (which are documented elsewhere). This manual would probably not make a good introductory book for new programmers, although those who know languages other than C should be able to learn C using it.

 The v0.2.5 release of the manual is now available, which includes a number of corrections suggested by readers. If you don't feel like building the manual from the Texinfo source, you can also read an HTML version or PDF version of the manual.

 For additional information, please see the manual's project page at Savannah.
** [[https://gcc.gnu.org/onlinedocs/][GCC online documentation - GNU Project - Free Software Foundation (FSF)]]
 GCC online documentation
 Latest releases

 These are manuals for the latest full releases.
** [[https://www.gnu.org/software/libc/manual/][The GNU C Library - GNU Project - Free Software Foundation (FSF)]]
 This manual (libc, aka glibc) is available in the following formats:

     HTML - entirely on one web page.
     HTML - one web page per node.
     HTML compressed (gzipped tar file) - with one web page per node.
     Info document (gzipped tar file).
     ASCII text compressed (gzipped).
     TeX dvi file (gzipped).
     PDF file.
     Texinfo source (gzipped tar file).
** [[https://www.reddit.com/r/emacs/comments/2d37bo/info_manuals_in_debian_and_ubuntu_some_information/][Info Manuals in Debian and Ubuntu some information : emacs]]


 Almost all GNU project languages and utilities have manuals in Info format. Unfortunately for us users, the Debian people decided that the GNU Free Documentation License is a "non-free" license. When the GNU project switched to using it for manuals the Debian people put them in a non-free repository. In my opinion, the behaviour of both sides was bad. Debian derivatives like Ubuntu keep that structure.
** [[https://github.com/politza/python-info/][politza/python-info]]

     Install the latest sphinx with python2 .
     Download the desired python distribution.
     Build the info file as follows.
** [[https://github.com/iammeat/POSTAL-1-Open-Source][iammeat/POSTAL-1-Open-Source]]


     C++ 61.8% Objective-C 27.9% C 10.0% Other 0.3%
** [[https://proglib.io/p/youtube-python-channels/][9 Youtube-каналов для изучения Python - Библиотека программиста]]
 Мы собрали 9 лучших каналов на YouTube для освоения и дальнейшего изучения языка программирования Python.
 1. sentdex

 Туториалы по Питону для продвинутых. На канале можно найти материалы по машинному обучению, анализу данных, робототехнике, веб-разработке, разработке игр и многое другое.
 2. Chris Hawkes

 На данном канале вы сможете найти материалы не только по языку программирования Python, но узнать подробнее, что такое ReactJS, Django и прочее.
 3. ИМКН УрФУ

 Языки сценариев — видеолекции по курсу «Языки сценариев», читаемому в Институте математики и компьютерных наук Уральского федерального университета. Курс посвящен третьей версии языка программирования Python.
 4. Moscow Python

 MoscowPython — сообщество, появившееся в 2012-м году под именем MoscowDjango. Сегодня на встречи собирается больше 200 человек, и сообщество активно сотрудничает с такими компаниями, как Mail.Ru Group, Rambler&Co, Яндекс, #tceh и другими.
 5. PyCon 2016

 Большая коллекция записей докладов с конференции PyCon 2016, проходившей в Портленде.
 6. PyCon 2015

 Огромная коллекция докладов c международной конференции по самым различным темам, которые связаны с языком программирования Питон.
 7. PyCon 2014

 Доклады с конференции PyCon 2014, которая проходила в Монреале.
 8. Next Day Video

 Коллекция лекций и докладов по Питону.
 9. PyData

 PyData – собрание пользователей и разработчиков инструментов для анализа данных в Python. Цель — предоставить разработчикам-энтузиастам место для того, чтобы делиться друг c другом идеями и опытом о применении языка программирования и его инструментов для решения задач в управлении, обработке, аналитике и визуализации данных.
** [[https://www.slac.stanford.edu/comp/unix/gnu-info/emacs_26.html][GNU Emacs Manual - Compiling and Testing Programs]]
  The previous chapter discusses the Emacs commands that are useful for making changes in programs. This chapter deals with commands that assist in the larger process of developing and maintaining programs.
** [[https://github.com/nick96/basic-c-compile][nick96/basic-c-compile: Emacs package to create a Makefile, compile and run a C file]]
 The purpose of this package is to automate come of the basic and repetetive tasks involved in C programming. All the tasks that this pacakge automate are language agnostic and whilst the defaults are C specific you can set them to any statically compiled language.
** [[https://github.com/syohex/emacs-quickrun][syohex/emacs-quickrun: Run command quickly. This packages is inspired quickrun.vim]]
 quickrun.el is a extension to execute editing buffer. quickrun.el is similar to executable-interpret, but quickrun.el provides more convenient commands. quickrun.el execute not only script languages(Perl, Ruby, Python etc), but also compiling languages(C, C++, Go, Java etc) and markup language.
** [[https://github.com/bbatsov/projectile][bbatsov/projectile: Project Interaction Library for Emacs]]
 Projectile is a project interaction library for Emacs. Its goal is to provide a nice set of features operating on a project level without introducing external dependencies (when feasible). For instance - finding project files has a portable implementation written in pure Emacs Lisp without the use of GNU find (but for performance sake an indexing mechanism backed by external commands exists as well).
** [[https://www.youtube.com/watch?v=o_RKfLrmCEs][C Programming Tutorial 56, String Functions pt.7 - YouTube]]
 Uploaded on Feb 5, 2012
** [[https://github.com/jlsutherland/doc2text][jlsutherland/doc2text: Detect text blocks and OCR poorly scanned PDFs in bulk. Python module available via pip.]]
 Developing text corpora can be a massive pain in the butt. Much of the text data we are interested in as scientists are locked away in pdfs that are poorly scanned. These scans can be off kilter, poor resolution, have a hand in them... and if you OCR these scans without fixing these errors, the OCR doesn't turn out so well. doc2text was created to help researchers fix these errors and extract the highest quality text from their pdfs as possible.
** [[https://github.com/politza/python-info][politza/python-info]]

     Install the latest sphinx with python2 .
     Download the desired python distribution.
     Build the info file as follows.

 cd Python-x.y.z/Doc
 sphinx-build -b texinfo -d build/doctrees . build/texinfo
 cd build/texinfo && make

 Or use the Makefile.
** [[https://www.youtube.com/watch?v=Gn0YiN8uzrg][Xubuntu on Nexus 7 {native, multiROM} - it's actually useful - YouTube]]
 Published on Sep 29, 2013

 Xubuntu = ubuntu +Xfce, and its running awesomely on the nexus 7 (the old one). In this in-depth video I will describe my experience with it and show how well some common tasks work so you could decide if its worth the effort of getting it running (it definitely is).

 This video was moved from a different (removed) account - originally uploaded at August 29th, 2013.

 Links & tips:

 http://forum.xda-developers.com/showt... - multiROM, you can get pretty much everything from there, there is also a short guide on how to get Ubuntu working with multiROM which includes link to download Ubuntu 13.04 for he N7. There are also links for kernels with kexec-hardboot patch (required by multiROM) and other guides for related things...

 Install Xfce: "sudo apt-get install xubuntu-desktop" in ubuntu terminal or just search "xubuntu-desktop" in ubuntu software center.

 Remove Unity after installing Xfce (you don't have to): http://askubuntu.com/questions/292394... (it's in the first answer...)

 Get Flash player working: http://hwswbits.blogspot.cz/2013/04/f...

 Fix touchscreen rotation:
 in the terminal: xinput (to find id of elan-touchscreen device - 7 in my case)
 xinput set-prop 7 "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1 (to rotate the touchscreen right - same rotation as the display obviously)

 Running Windows and Age of Empires: http://www.youtube.com/watch?v=zN3_td...

 If you are bored with your (now old) nexus 7, this is a great way to revive it and make it do new cool (and most importantly useful) things... Nothing from the process of getting it running was particularly difficult, but if you don't have basic knowledge about flashing roms & kernels, don't know what a custom recovery is, etc. - than you should start with tutorials on that, just use google. The same thing applies about using Ubuntu/Linux.

 I encourage you to make questions, I will answer any question which isn't answered in the video or in this description, if it will be important i will also add the answer to this description.
** [[https://habrahabr.ru/post/303600/][Emacs как редактор кода для Python и Golang / Хабрахабр]]
 Когда полгода назад я решил перейти с Vim на Emacs сначала я решил поискать статьи по настройке последнего на хабре. К моему удивлению нашлась всего одна статья в которой рассказывали, как настроить данный редактор для работы с Python. У меня было 2 года опыта работы с vim и имелись определенные требования, которые не были затронуты в данной статье. Вообще рускоязычных статей про работу в Emacs над Python очень мало на просторах интернета. Я не буду рассказывать про тонкости настройки самого Emacs, для этого не хватит даже отдельной статьи.
** [[https://letsencrypt.org/][Let's Encrypt - Free SSL/TLS Certificates]]
 Let’s Encrypt is a free, automated, and open Certificate Authority.

 We are a 501(c)(3) nonprofit. We're running a crowdfunding campaign to support our operations, please consider contributing now!
** [[https://github.com/doxygen/doxygen][doxygen/doxygen: Official doxygen git repository]]
 Doxygen is the de facto standard tool for generating documentation from annotated C++ sources, but it also supports other popular programming languages such as C, Objective-C, C#, PHP, Java, Python, IDL (Corba, Microsoft, and UNO/OpenOffice flavors), Fortran, VHDL, Tcl, and to some extent D.
** [[http://ogp.me/][The Open Graph protocol]]
 The Open Graph protocol enables any web page to become a rich object in a social graph. For instance, this is used on Facebook to allow any web page to have the same functionality as any other object on Facebook.
** [[https://en.wikipedia.org/wiki/Piwik][Piwik - Wikipedia]]
 Piwik (pronounced /ˈpiːwiːk/[1]) is a free and open source web analytics application written by a team of international developers that runs on a PHP/MySQL webserver. It tracks online visits to one or more websites and displays reports on these visits for analysis. As of September 2015, Piwik was used by nearly 900 thousand websites,[2] or 1.3% of all websites,[3] and has been translated to more than 45 languages.[4] New versions are regularly released every few weeks.[5]
** [[https://github.com/python-pillow/Pillow][python-pillow/Pillow: The friendly PIL fork (Python Imaging Library)]]
 Pillow is the friendly PIL fork by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
** [[https://github.com/ChrisAntaki/visited-links-firefox][ChrisAntaki/visited-links-firefox: Disables visited link styles.]]
 This plugin cleanly disables visited link styles.
** [[https://github.com/Malabarba/camcorder.el][Malabarba/camcorder.el: Tool for capturing screencasts directly from Emacs.]]
 Tool for capturing screencasts directly from Emacs.

     To use it, simply call M-x camcorder-record.
     A new smaller frame will popup and recording starts.
     When you’re finished, hit F12.

 View screencasts are generated in ogv format, and you can even pause the recording with F11! You can also convert the .ogv file to a gif by issuing the command M-x camcorder-convert-to-gif.

 If you want to record without a popup frame, use M-x camcorder-mode.
** [[http://jr0cket.co.uk/2017/01/spacemacs-creating-animated-gifs-videos.html][camcorder.el - Creating Animated Gifs & Videos for Spacemacs | jr0cket]]
 Using animated gifs are a lightweight way to show Emacs in action, as can be seen at Emacs Gifs.
** [[https://github.com/caiorss/clip.jar][caiorss/clip.jar: Utility to paste images from clipboard to Emacs org-mode or any markdown.]]
 Clip is a self-contained command line utility written in Scala to extract images from clipboard and save it to a file. It is a module of org-wiki project.
** [[https://html5up.net/][HTML5 UP! Responsive HTML5 and CSS3 Site Templates]]
 ... makes spiffy HTML5
 site templates that are:

     Fully
     Responsive Built on intelligent
     HTML5 + CSS3 Super
     Customizable100% Free under the
     Creative Commons
** [[https://github.com/ctfs/write-ups-2014][ctfs/write-ups-2014: Wiki-like CTF write-ups repository, maintained by the community. 2014]]
 There are some problems with CTF write-ups in general:

     they’re scattered across the interwebs
     they don’t usually include the original files needed to solve the challenge
     some of them are incomplete or skip ‘obvious’ parts of the explanation, and are therefore not as helpful for newcomers
     often they disappear when the owner forgets to renew their domain or shuts down their blog

 This repository aims to solve those problems.

 It’s a collection of CTF source files and write-ups that anyone can contribute to. Did you just publish a CTF write-up? Let us know, and we’ll add a link to your post — or just add the link yourself and submit a pull request. Spot an issue with a solution? Correct it, and send a pull request.
** [[https://github.com/joshnewlan/say_what][joshnewlan/say_what: Using speech-to-text to fully check out during con calls]]
 This script listens to meetings I'm supposed to be paying attention to and pings me on hipchat when my name is mentioned.

 It sends me a transcript of what was said in the minute before my name was mentioned and some time after.

 It also plays an audio file out loud 15 seconds after my name was mentioned which is a recording of me saying, "Sorry, I didn't realize my mic was on mute there."

 Uses IBM's Speech to Text Watson API for the audio-to-text.

 Currently relies on Splunk as a data store, but can be extended to use an open-source tool instead.

 Relies on Uberi's SpeechRecognition PyAudio and API wrapper: https://github.com/Uberi/speech_recognition
** [[https://github.com/malb/emacs.d/tree/48508219453ebb542e6fec370bb49fba9980c2a2][malb/emacs.d at 48508219453ebb542e6fec370bb49fba9980c2a2]]
 These are the relevant bits of my emacs config. Some stuff not suitable for general consumption is missing. Hence, you cannot just clone this repository and try it. I have no intention of changing this.
** [[http://orgmode.org/worg/org-contrib/org-protocol.html][org-protocol.el – Intercept calls from emacsclient to trigger custom actions]]
 Intercept calls from emacsclient to trigger
** [[http://docs.getpelican.com/en/stable/settings.html][Settings — Pelican 3.7.0 documentation]]
 If you want to use FeedBurner for your feed, you will likely need to decide upon a unique identifier. For example, if your site were called “Thyme” and hosted on the www.example.com domain, you might use “thymefeeds” as your unique identifier, which we’ll use throughout this section for illustrative purposes. In your Pelican settings, set the FEED_ATOM attribute to thymefeeds/main.xml to create an Atom feed with an original address of http://www.example.com/thymefeeds/main.xml. Set the FEED_DOMAIN attribute to http://feeds.feedburner.com, or http://feeds.example.com if you are using a CNAME on your own domain (i.e., FeedBurner’s “MyBrand” feature).

 There are two fields to configure in the FeedBurner interface: “Original Feed” and “Feed Address”. In this example, the “Original Feed” would be http://www.example.com/thymefeeds/main.xml and the “Feed Address” suffix would be thymefeeds/main.xml.
** [[https://github.com/bitlbee/bitlbee][bitlbee/bitlbee: An IRC to other chat networks gateway]]
 An IRC to other chat networks gateway
** [[https://vk.com/im?sel=c2][Conversations]]
 помогло конвертированием шрифта otf-->ttf и его положение не в системе. а непосредственно в папку в префиксе вайна запихал. кажется. Или наоборот, не помню
** [[https://www.youtube.com/watch?v=L_0x3lYpoNY][ЭРА RADEONa: Native games {06.01.2017, 23.00 MSK}-stream 720p - YouTube]]
 Купил AMD Radeon RX 460 3Gb NITRO OC
 Задаем вопросы, делимся своим мнением, обсуждаем что будет интересно увидеть в серии видео о АМД карте)
** [[https://www.maketecheasier.com/install-flatpak-on-ubuntu/][How to Install FlatPak on Ubuntu - Make Tech Easier]]
 Luckily, there’s a Flatpak for that. Fedora users has taken it upon themselves to serve up the official Telegram chat client in the form of a Flatpak. This means it’ll always have up-to-date binaries, and installing Telegram on new machines can be just a few commands away.
** [[https://github.com/fgallina/mu4e-multi][fgallina/mu4e-multi: Multiple account facilities for mu4e]]
 mu4e-multi just depends on setting the mu4e-multi-account-alist properly and calling mu4e-multi-enable.

 As an example let's assume you have two email accounts: personal and work. For handling such accounts mu4e-multi assumes your maildir's layout is as follows:
** [[https://github.com/myuhe/org-gcal.el][myuhe/org-gcal.el: Org sync with Google Calendar]]

     Fetch google calendar event
     Post/edit org element
     Sync between Org and Gcal
** [[https://github.com/anishathalye/git-remote-dropbox][anishathalye/git-remote-dropbox: A transparent bridge between Git and Dropbox - use a Dropbox (shared) folder as a Git remote!]]
 git-remote-dropbox is a transparent bidirectional bridge between Git and Dropbox. It lets you use a Dropbox folder or a shared folder as a Git remote!

 This Git remote helper makes Dropbox act like a true Git remote. It maintains all guarantees that are provided by a traditional Git remote while using Dropbox as a backing store. This means that it works correctly even when there are multiple people operating on the repository at once, making it possible to use a Dropbox shared folder as a Git remote for collaboration.

 Once the helper is installed, using it is as simple as adding a remote like dropbox://path/to/repo.
** [[https://github.com/lxde/pavucontrol-qt][lxde/pavucontrol-qt: A Pulseaudio mixer in Qt (port of pavucontrol)]]
 pavucontrol-qt is the Qt port of volume control pavucontrol of sound server PulseAudio.

 As such it can be used to adjust all controls provided by PulseAudio as well as some additional settings.

 The software belongs to the LXQt project but its usage isn't limited to this desktop environment.
** [[https://github.com/equalsraf/neovim-qt][equalsraf/neovim-qt: Neovim client library and GUI, in Qt5.]]
 Neovim client library and GUI, in Qt5.
** [[https://github.com/jonian/acestream-launcher][jonian/acestream-launcher: Acestream Launcher allows you to open Acestream links with a Media Player of your choice]]
 Acestream Launcher allows you to open Acestream links with a Media Player of your choice
** [[http://hakunin.com/six-ansible-practices][6 practices for super smooth Ansible experience by Maxim Chernyak]]
 I started porting my setup from Chef to Ansible a few weeks ago. Having had plenty of experience with Chef gave me a pretty good idea of what I wanted to achieve. One of the main advantages I see in Ansible is the ability to drive your server setup via ssh from your own machine. If you don’t have 100s of servers (update: actually more like tens of thousands, see the comment by mpdehaan), this agentless “push” approach is very powerful. You get to simplify things tremendously in ways like
** [[https://vk.com/im?sel=c5][Conversations]]
 Расписание. На 2 этаже слева в коридоре. В том корпусе где деканат
 на 3.
** [[https://en.wikipedia.org/wiki/SpinRite][SpinRite - Wikipedia]]
 SpinRite is a computer program for scanning magnetic data storage devices such as hard disks, recovering data from them and refreshing their surfaces. The first version was released in 1987 by Steve Gibson. Version 6.0, still current as of January 2017, was released in 2004.[1] SpinRite is run from a bootable medium (floppy disc, optical disc, bootable external storage device such as a USB stick) on a PC-compatible computer. Spinrite uses its own operating system and ignores any boot loader or file system structure that may be on the drive being examined.
** [[https://tldrlegal.com/][TLDRLegal - Software Licenses Explained in Plain English]]
 Lookup popular software licenses summarized at-a-glance.
** [[https://github.com/eonpatapon/gnome-shell-extension-caffeine/issues/67][Caffeine causes gnome-session-quit time out in GNOME 3.20 · Issue #67 · eonpatapon/gnome-shell-extension-caffeine]]
 The issue only happened once when you first call power off button, and second time or more is fine.

     GUI

     if click "power off" button in control menu, which is located on the right-top of main screen, it will take long time (about 20 second) to start power off menu and I couldn't do nothing during this time but move cursor.

     Command-Line

 Try to use command line to call the power off menu with "gnome-session-quit --power-off" in terminal to check the error information. it still take long time and only could move cursor. the error message below:
** [[https://github.com/eonpatapon/gnome-shell-extension-caffeine/issues/76][delay time between shutdown select and when windows appears · Issue #76 · eonpatapon/gnome-shell-extension-caffeine]]
 On click on shutdown button inside the top menu (ref. attach. n.1) the delay time until the windows appear are about 30 seconds. Occur only on the first time on the session.
 Case 1: caffeine disabled
 instantly windows appear.
 Case 2: caffeine enabled
 first selection 30 seconds for windows appear.
 Case 3: caffeine enabled - with the second attempt
 first selection 30 seconds for windows appear, then i press cancel button. On second attempt the windows appear instantly.
 Case 4: caffeine enabled - gnome-shell restarted
 after case 3 i restart gnome-shell and the issue return.
** [[https://github.com/plone/planet.plone.org][plone/planet.plone.org: Planet Plone Site Configuration and buildout. Add your feed here.]]
 This is the buildout for Planet Venus (an RSS aggregator) for Plone, the content management system. This buildout provides the configuration for Planet Venus, normally served at http://planet.plone.org/.
** [[http://planetperl.ru/][Русский Перл]]

 Язык занятный. Параллелить и устраивать межпроцессное общение просто.
** [[http://www.planetplanet.org/][Planet Feed Reader]]
  Planet is an awesome 'river of news' feed reader. It downloads news feeds published by web sites and aggregates their content together into a single combined feed, latest news first.
** [[https://github.com/insanum/gcalcli][insanum/gcalcli: Google Calendar Command Line Interface]]
 gcalcli is a Python application that allows you to access your Google Calendar(s) from a command line. It's easy to get your agenda, search for events, add new events, delete events, edit events, and even import those annoying ICS/vCal invites from Microsoft Exchange and/or other sources. Additionally, gcalcli can be used as a reminder service and execute any application you want when an event is coming up.
** [[http://pragmaticemacs.com/emacs/how-i-view-my-google-calendar-agenda-in-emacs/][How I view my google calendar agenda in Emacs | Pragmatic Emacs]]
  I use gcalcli to access my google calendar from the command line, and run it as a cron job using gcalcli agenda and redirecting the output to a file. Then in Emacs I have a simple function to display the contents of that file.
** [[https://www.khanacademy.org/math/precalculus/imaginary-and-complex-numbers/the-imaginary-numbers/v/calculating-i-raised-to-arbitrary-exponents][Powers of the imaginary unit | What are the imaginary numbers? | Imaginary and complex numbers | Precalculus | Khan Academy]]
 Sal gives several examples of how we simplify high powers of i. For instance, i^100=1. Created by Sal Khan.
** [[https://www.symbolab.com/solver/complex-numbers-calculator/i%255E%257B15%257D][i^{15} - Complex Numbers Calculator - Symbolab]]
 Simplify complex expressions using algebraic rules step-by-step
** [[https://www.khanacademy.org/math/algebra2/rational-expressions-equations-and-functions/simplify-rational-expressions/v/simplifying-rational-expressions-introduction][Intro to rational expression simplification | Simplifying rational expressions | Rational expressions, equations, and functions | Algebra II | Khan Academy]]
 Sal explains what it means to simplify a rational expression and why we would want to do that. Just don't forget the excluded values! Created by Sal Khan and CK-12 Foundation.
** [[http://www.emathhelp.net/notes/algebra-2/trigonometry/short-multiplication-formulas/][Short Multiplication Formulas on eMathHelp]]
 In some cases the transformation of integral expression into the standart form of polynomial realize with the using of identities:
** [[https://www.sharelatex.com/learn/List_of_Greek_letters_and_math_symbols][List of Greek letters and math symbols - ShareLaTeX, Online LaTeX Editor]]


     1 Greek letters
     2 Arrows
     3 Miscellaneous symbols
     4 Binary Operation/Relation Symbols
     5 Further reading
** [[https://www.sharelatex.com/learn/Subscripts_and_superscripts][Subscripts and superscripts - ShareLaTeX, Online LaTeX Editor]]
 The use of superscripts and subscripts is very common in mathematical expressions involving exponents, indexes, and in some special operators. This article explains how to write superscripts and subscripts in simple expressions, integrals, summations, etcetera.
** [[https://www.youtube.com/watch?v=3N9beoPmbEQ][Как правильно разговаривать с гопниками? - YouTube]]
 Published on Aug 21, 2016

 Ты идешь по чужому району, и тут тебе свистят - "братан, подойди поговорим" что делать в такой ситуации? Как правильно разговаривать с гопниками?
** [[http://www.freeorion.org/index.php/Main_Page][FreeOrionWiki]]
 FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game being designed and built by the FreeOrion project. FreeOrion is inspired by the tradition of the Master of Orion games, but is not a clone or remake of that series or any other game.
** [[https://www.khanacademy.org/math/algebra-home/alg-polynomials/alg-polynomial-remainder-theorem/v/polynomial-remainder-theorem][Intro to the Polynomial Remainder Theorem | Polynomial Remainder Theorem | Polynomial expressions, equations, & functions | Algebra | Khan Academy]]
 The Polynomial Remainder Theorem allows us to determine whether a linear expression is a factor of a polynomial expression easily. Check it out!
** [[https://github.com/viktomas/godu][viktomas/godu: Simple golang utility helping to discover large files/folders.]]
 Tired of looking like a noob with Disk Inventory X or SpaceMonger? Do you want something that

     can do the job
     works in terminal
     makes you look cool
     is written in Golang
     you can contribute to
** [[https://github.com/livibetter/READYT][livibetter/READYT: A CLI lover wants you to READYT]]
 Mostly short, but not tutorials, almost all without audio tracks, no horrible music, no terribly unnecessary transitioning texts. Go straight to the points of what I want to show you about a program.

 There will be description about my thoughts, possibly some short notes about controls or command-line options. My video includes the description, video and description together are the whole video, so be sure to read the description.

 In the end of description, links and information about version, programming languages and major dependencies or libraries, the author(s), and the license.
** [[https://github.com/nielssp/colorgrab][nielssp/colorgrab: A cross-platform color picker]]

     Pick colors from screen.
     Magnify screen.
     Convert between color models and representations.
     Palette tool.
** [[https://www.khanacademy.org/math/algebra2/arithmetic-with-polynomials/long-division-of-polynomials/v/polynomial-division][Intro to long division of polynomials | Long division of polynomials | Arithmetic with polynomials | Algebra II | Khan Academy]]
 [[https://www.khanacademy.org/math/algebra2/arithmetic-with-polynomials/long-division-of-polynomials/v/polynomial-division][Intro to long division of polynomials | Long division of polynomials | Arithmetic with polynomials | Algebra II | Khan Academy]]
** [[https://www.khanacademy.org/math/algebra/algebra-functions/evaluating-functions/v/what-is-a-function][(3) What is a function? | Evaluating functions | Functions | Algebra I | Khan Academy]]
 Functions assign a single unique output for each of their inputs. In this video, we see examples of various kinds of functions. Created by Sal Khan.
** [[https://vk.com/eltech6871?from=top][ЛЭТИ, группа 6871]]
 Электроэнергетика и электротехника, 1 курс
** [[https://www.youtube.com/watch?v=UsIHdrpNSbE][СТУДИИ КОТОРЫЕ ПОГУБИЛА ELECTRONIC ARTS - YouTube]]
 Published on Jan 2, 2017

 Electronic Arts может и исправляется, но за ней всё ещё следует кличка самой ужасной игровой корпорации в мире. Так что сегодня мы решили вспомнить, за что они эту кличку получили.
** [[https://zblock.co/][zBlock]]
  Forum software by XenForo™ ©2010-2016 XenForo Ltd.
 Перевод: XF-Russia.ru
** [[https://youpartnerwsp.com/join][Медиа сеть партнерских каналов VSP Group - Официальный агрегатор партнерских каналов на YouTube]]
 Партнерская программа VSP Group предоставляет возможность монетизации вашего канала и получения "Премиум аккаунта" на платформе YouTube в составе нашей Медиа сети.
** [[https://www.emacswiki.org/emacs/OpenWith][EmacsWiki: Open With]]
 Open files with external applications. Works from everywhere (find-file, dired, etc.).
** [[https://www.reddit.com/r/emacs/comments/5mff61/anyone_got_any_good_advanced_orgmode_resources/][Anyone got any good advanced org-mode resources? : emacs]]
 I'm starting to get into org-mode, and am wondering if anyone's got a good blog or otherwise educational resource to point me to. I know I can just read the emacs/org manual, but a more enjoyable exposition would be pretty cool
** [[https://www.youtube.com/watch?v=P_cDP4ZGIhE][Cheat For Test - YouTube]]
 Uploaded on Nov 12, 2008

 One more way to make a cheat sheet
** [[https://www.youtube.com/watch?v=SNQ08e1xGC0][Делаем резьбу в программе КОМПАС 3D - YouTube]]
 Published on Feb 26, 2014

 КОМПАС V14. Создаем болт с произвольной резьбой и шляпкой.
** [[http://www.eltech.ru/ru/fakultety/otkrytyy-fakultet/uchebn-dlya-studentov-zaochnoy-formy-obucheniya/pamjatka][http://www.eltech.ru/ru/fakultety/otkrytyy-fakultet/uchebn-dlya-studentov-zaochnoy-formy-obucheniya/pamjatka]]
 ПАМЯТКА

 для студентов 1-го курса 1-го семестра заочной формы обучения

  (прием 2016 года)

 Деканат Открытого факультета (заочное обучение) СПбГЭТУ  расположен в 3 корпусе, 3 этаж, комн. 3309
** [[https://www.symbolab.com/solver/complex-numbers-calculator/%255Cleft(8-6i%255Cright)%255Cleft(8%252B6i%255Cright)][(8-6i)(8+6i) - Complex Numbers Calculator - Symbolab]]
  Simplify complex expressions using algebraic rules step-by-step
** [[https://www.youtube.com/watch?v=wed_lYcslRM][Complex Numbers in Polar Form - YouTube]]
 I explain the relationhip between complex numbers in rectangular form and polar form. I also do an example of converting back and forth between the two forms.
** [[https://www.youtube.com/watch?v=wed_lYcslRM][Complex Numbers in Polar Form - YouTube]]
 Uploaded on Jan 13, 2012

 I explain the relationhip between complex numbers in rectangular form and polar form. I also do an example of converting back and forth between the two forms.
 At time 9:57 I should say...Converting from Polar to Rectangular is very simple. Converting from Rectangular to Polar requires you to think about the final theta measure.

 Check out http://www.ProfRobBob.com, there you will find my lessons organized by class/subject and then by topics within each class. Find free review test, useful notes and more at http://www.mathplane.com
** [[https://www.youtube.com/watch?v=tbWfxuV-IeE&list=PLAC5EA62150BD3A5A][Rewriting Powers of ' i ' - Ex 2 - YouTube]]
 Published on May 10, 2010

 Rewriting Powers of ' i ' - In this video, I take the complex number ' i ', raise it to some different powers, and simplify!
** [[https://www.youtube.com/watch?v=2bMKu1CXyB0][How do we Plot Root 2 on a Number Line? - YouTube]]
 Published on Dec 19, 2014

 View this video to understand how the square root of 2 can be plotted on a number line. To know more about Rational, Irrational and Real Numbers, please visit https://DontMemorise.com

 Don’t Memorise brings learning to life through its captivating FREE educational videos.

 New videos every week. To stay updated, subscribe to our YouTube channel : http://bit.ly/DontMemoriseYouTube

 Register on our website to gain access to all videos and quizzes:
 http://bit.ly/DontMemoriseRegister

 Subscribe to our Newsletter: http://bit.ly/DontMemoriseNewsLetter

 Join us on Facebook: http://bit.ly/DontMemoriseFacebook

 Follow us : http://bit.ly/DontMemoriseBlog
** [[https://www.youtube.com/watch?v=jXXSRzliprg][HSC Maths Ext2 - Complex Numbers - Finding Square Roots of Complex Numbers - YouTube]]
 Published on Nov 27, 2013

 Welcome to my HSC 4 Unit maths: Complex Numbers series. In this video, we see how to find the square roots of complex numbers, which will be useful for solving quadratics with complex coefficients.
** [[https://www.youtube.com/watch?v=nUyLnjgGumg][Square root in 3 seconds - math trick - YouTube]]
 Published on Mar 24, 2015

 Finding the square root is easy for any perfect square under 100! You'll be able to calculate squares faster than ever and amaze everyone with your utter genius!
 To find the square root of non perfect squares follow this link: https://www.youtube.com/watch?v=PJHtq...
** [[https://www.youtube.com/watch?v=fF5qbbAoMHc][Complex Numbers (How to find the nth root) : ExamSolutions Maths Video Tutorials - YouTube]]
 Published on Mar 11, 2013

 Go to http://www.examsolutions.net/maths-re... to see the main index of maths video tutorials and others on complex numbers and de Moivre's theorem
** [[https://www.youtube.com/watch?v=eYmHMib6fhg][Solving for Complex Numbers and Roots - YouTube]]
 Published on Mar 20, 2012

 http://tylertarver.com/math

 Solving for Complex Numbers and Roots
** [[https://www.youtube.com/watch?v=MO6qU3SCLbM][DeMoivre's Theorem: Raising a Complex Number to a Power, Ex 1 - YouTube]]
 Published on Jan 5, 2011

 DeMoivre's Theorem: Raising a Complex Number to a Power, Ex 1. In this video I give DeMoivre's theorem and use it to raise a complex number to a power. Note that our number must be in polar form!
** [[https://www.youtube.com/watch?v=C-lsvE8Rxgg][DeMoivre's Theorem - YouTube]]
 Uploaded on May 18, 2010

 Watch more videos on http://www.brightstorm.com/math/preca...

 SUBSCRIBE FOR All OUR VIDEOS!
 https://www.youtube.com/subscription_...

 VISIT BRIGHTSTORM.com FOR TONS OF VIDEO TUTORIALS AND OTHER FEATURES!
 http://www.brightstorm.com/

 LET'S CONNECT!
 Facebook ► https://www.facebook.com/brightstorm
 Pinterest ► https://www.pinterest.com/brightstorm/
 Google+ ► https://plus.google.com/+brightstorm/
 Twitter ► https://twitter.com/brightstorm_
 Brightstorm website ► https://www.brightstorm.com/
** [[https://www.youtube.com/watch?v=k4ZddA4e3a4][DeMoivre's Theorem (Mathematical Induction) - YouTube]]
 Published on Jul 25, 2012

 A quick look at DeMoivre's theorem and a qualitative explanation on how to prove something with mathematical induction

 DeMoivre's theorem (0:00)
 Mathematical Induction (2:28)
** [[https://www.youtube.com/watch?v=ZkWbvZ0yjT8][De Moivre's Theorem Example 1 - YouTube]]
 Published on May 21, 2016

 Example of how to expand a complex number using DeMoivre's Theorem
** [[http://www.mathportal.org/calculators/complex-numbers-calculator/complex-unary-operations-calculator.php][Complex numbers calculator - with detailed explanation]]


 This calculator extracts the square root, calculate the modulus, finds inverse, finds conjugate and transform complex number to polar form. The calculator will generate a detailed explanation for each operation.
** [[http://kitchingroup.cheme.cmu.edu/blog/2015/06/29/Getting-Emacs-to-read-to-me/][Getting Emacs to read to me]]
  I thought it would be interesting to have Emacs read text on the screen. Why? Sometimes I get tired of reading ;) Seriously though, this has applications in accessibility, learning to read, translation, taking a break from looking at the screen, reading emails out loud, fun and games, etc… Seems like a worthwhile endeavor!
** [[https://vk.com/im?peers=384426051_13368088&sel=c4][Диалоги]]
 23.01 я буду в 14.30-16.00 в а.5143
 26.01 я буду в 1200-13.30 в а. 5143
 1.02 я буду в 14.30-16.00 в а.5423
 В это время вы можете придти ко мне с направлением и пересдать
** [[http://window.edu.ru/resource/396/62396][Начертательная геометрия: Конспект лекций. Скачать бесплатно онлайн в электронном виде | Единое окно]]


 В пособии рассмотрены следующие темы курса начертательной геометрии: комплексные чертежи фигур; позиционные задачи; метрические задачи; развертки поверхностей; ортогональная аксонометрия. Приведены примеры решения основных задач и даны условия задач для самостоятельного решения. Пособие предназначено для студентов всех специальностей вечерней и заочной форм обучения технических вузов.
** [[https://www.youtube.com/watch?v=SpEnXMzDZAI][Perpendicular Vectors: Dot Product - YouTube]]
 Published on Feb 28, 2013

 Determine if two vectors are perpendicular by checking if the inner product (dot product) is equal to zero.
** [[http://www.cleverstudents.ru/vectors/condition_of_vectors_perpendicularity.html][Условие перпендикулярности векторов.]]


 Для перпендикулярности двух ненулевых векторов формула и формула необходимо и достаточно, чтобы их скалярное произведение равнялось нулю, то есть, чтобы выполнялось равенство формула.
** [[http://www.webmath.ru/poleznoe/formules_13_14.php][Как найти вектор перпендикулярный вектору? Ответ на webmath.ru]]
 Для того чтобы вектор был перпендикулярен вектору необходимо, чтобы их скалярное произведение было равно нулю, то есть
** [[https://www.youtube.com/watch?v=51vgIfdBlAk][1.1 Vectors with 3 components (3 dimensions) - YouTube]]
 Uploaded on Aug 5, 2011

 http://www.rootmath.org | Linear Algebra

 We'll look at how to graph vectors with 3 components using 3-dimensional axes.
** [[https://www.khanacademy.org/math/algebra-home/alg-system-of-equations/alg-equivalent-systems-of-equations/v/king-s-cupcakes-solving-systems-by-elimination][(17) Systems of equations with elimination: King's cupcakes | Equivalent systems of equations and the elimination method | System of equations | Algebra | Khan Academy]]
 Sal uses simple elimination to figure out how many cupcakes are eaten by children and adults. Created by Sal Khan.
** [[http://ru.onlinemschool.com/math/assistance/matrix/inverse1/][Онлайн калькулятор. Обратная матрица методом алгебраических дополнений.]]
 Используя этот онлайн калькулятор для вычисления обратной матрицы методом алгебраических дополнений, вы сможете очень просто и быстро найти обратную матрицу.

 Воспользовавшись онлайн калькулятором для вычисления обратной матрицы методом алгебраических дополнений, вы получите детальное решение вашей задачи, которое позволит понять алгоритм решения задач на вычисления обратной матрицы, а также закрепить пройденный материал.
** [[https://github.com/jsvine/waybackpack][jsvine/waybackpack: Download the entire Wayback Machine archive for a given URL.]]
 Waybackpack is a command-line tool that lets you download the entire Wayback Machine archive for a given URL.

 For instance, to download every copy of the Department of Labor's homepage through 1996 (which happens to be the first year the site was archived), you'd run:
** [[https://github.com/yask123/Instant-Music-Downloader][yask123/Instant-Music-Downloader: 🎷 Downloads Music From The Web]]


     Please use gitter for all communications. I won't be able to respond individually via emailuntill Jan (busy). But I will try my best to answer all your questions via gitter.
** [[https://github.com/EvilCult/Video-Downloader][EvilCult/Video-Downloader: 下载youku,letv,sohu,tudou,bilibili,acfun,iqiyi等网站分段视频文件，提供mac&win独立App。]]
  下载youku,letv,sohu,tudou,bilibili,acfun,iqiyi等网站分段视频文件，提供mac&win独立App。 http://evilcult.github.io/Video-Downl…
** [[https://github.com/sabnzbd/sabnzbd][sabnzbd/sabnzbd: SABnzbd - The automated Usenet download tool]]
 SABnzbd is an Open Source Binary Newsreader written in Python.

 It's totally free, incredibly easy to use, and works practically everywhere.

 SABnzbd makes Usenet as simple and streamlined as possible by automating everything we can. All you have to do is add an .nzb. SABnzbd takes over from there, where it will be automatically downloaded, verified, repaired, extracted and filed away with zero human interaction.
** [[https://github.com/np1/mps][np1/mps: Terminal based MP3 search, playback and download]]

     Search and stream music
     Search albums or single tracks
     Create playlists
     Download tracks
     Works with Python 2.7+ and 3.3+
     Works with Windows, Linux and Mac OS X
     No Python dependencies
     Requires mplayer
** [[https://github.com/pyload/pyload][pyload/pyload: Free and Open Source download manager written in Python and designed to be extremely lightweight, fully customizable and remotely manageable]]
 pyLoad is a free and open source downloader for 1-click-hosting sites
 like rapidshare.com or uploaded.to.
 It supports link decryption as well as all important container formats.
** [[https://github.com/nishad/udemy-dl][nishad/udemy-dl: Python script to download a udemy.com course, for personal offline use.]]
 Python script to download a udemy.com course, for personal offline use.
** [[https://www.khanacademy.org/math/precalculus/prob-comb/basic-prob-precalc/v/basic-probability][(17) Intro to theoretical probability | Basic probability | Probability and combinatorics | Precalculus | Khan Academy]]
 We give you an introduction to probability through the example of flipping a quarter and rolling a die. Created by Sal Khan.
** [[https://www.youtube.com/watch?v=QudbrUcVPxk][Abstract Algebra: The definition of a Group - YouTube]]
 Published on Sep 1, 2013

 Learn the definition of a group - one of the most fundamental ideas from abstract algebra.
** [[https://www.youtube.com/watch?v=6RC70C9FNXI][Abstract Algebra: The definition of a Ring - YouTube]]
 Published on Dec 29, 2013

 Learn the definition of a ring, one of the central objects in abstract algebra. We give several examples to illustrate this concept including matrices and polynomials.
** [[https://play.google.com/store/apps/details?id=com.orgzly][Orgzly: Notes & To-Do Lists - Android Apps on Google Play]]
 Orgzly is an outliner for notes and tasks. It stores notebooks in plain-text and keeps them where you choose to.
** [2017-01-21 Sat 18:01] [[about:reader?url=http%3A%2F%2Fcarper.ca%2Fblog%2F170%2Flets-try-to-learn-japanese-for-the-87th-time-plus-a-wanikani-review][Let's try to learn Japanese for the 87th time. Plus a WaniKani review.]]
 I've been trying to learn Japanese for a looong time, with varying degrees of success. It's hard in ways that might be surprising. The main problem is motivation. This is a tale of my minor successes and major failures, and then a review of my latest flavor-of-the-week, WaniKani.
** [2017-01-21 Sat 18:09] [[https://github.com/avendael/emacs-geeknote][avendael/emacs-geeknote: Use Evernote in Emacs through geeknote]]
 Use Evernote in Emacs through geeknote
** [2017-01-21 Sat 19:15] [[https://www.emacswiki.org/emacs/IncrementalReading#toc10][EmacsWiki: Incremental Reading]]
 #+BEGIN_QUOTE
 Save a buffer of text you want to incrementally read.
 For HTML, use M-! lynx -dump URL (Does anyone know of a way to get numbered links with either links or w3m?).

 #+END_QUOTE
** [2017-01-21 Sat 20:03] [[https://github.com/defunkt/gist.el][defunkt/gist.el: Yet another Emacs paste mode, this one for Gist.]]
 #+BEGIN_QUOTE
 Uses your local GitHub config if it can find it.

 Go to your GitHub Settings and generate a personal access token with gist scope


 #+END_QUOTE
