:PROPERTIES:
:ID:       9bd9dd4b-0d7b-45b0-b9e3-5a9d54f8417e
:END:
- snapshot
  : lvcreate --size 4G --snapshot --name magnolia--vg-root-01 /dev/mapper/magnolia--vg-root
- [[https://www.man7.org/linux/man-pages/man7/lvmvdo.7.html][lvmvdo(7) - Linux manual page]]

- increase size of logical volume
  : lvextend -L+10G /dev/lvm1/web99

- [[https://storytime.ivysaur.me/posts/why-not-zfs/][Why not ZFS]]

root@guixsd ~ [env]# pvcreate /dev/sdd5 
File descriptor 5 (/gnu/store/2rlcdsb7p3njs7wbh2nanyl7j14gwj1w-guix-command) leaked on pvcreate invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
File descriptor 14 (socket:[112552]) leaked on pvcreate invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
  Physical volume "/dev/sdd5" successfully created.

root@guixsd ~ [env]# vgcreate lvm1 /dev/sdd5
File descriptor 5 (/gnu/store/2rlcdsb7p3njs7wbh2nanyl7j14gwj1w-guix-command) leaked on vgcreate invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
File descriptor 14 (socket:[112552]) leaked on vgcreate invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
  Volume group "lvm1" successfully created

root@guixsd ~ [env]# vgchange -a y lvm1
File descriptor 5 (/gnu/store/2rlcdsb7p3njs7wbh2nanyl7j14gwj1w-guix-command) leaked on vgchange invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
File descriptor 14 (socket:[112552]) leaked on vgchange invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
  0 logical volume(s) in volume group "lvm1" now active

root@guixsd ~ [env]# virsh pool-define-as lvm1 logical --source-name lvm1 --target /dev/sdd5 
Pool lvm1 defined

root@guixsd ~ [env]# virsh pool-start lvm1
Pool lvm1 started


[root@localhost ~]# pvcreate /dev/vdb1
  Physical volume "/dev/vdb1" successfully created.
[root@localhost ~]# vgcreate vg0 /dev/vdb1
  Volume group "vg0" successfully created
[root@localhost ~]# lvcreate -l 100%FREE -Zn --type thin-pool --thinpool pool0 vg0
  Thin pool volume with chunk size 64.00 KiB can address at most <15.88 TiB of data.
  Logical volume "pool0" created.
[root@localhost ~]# lvcreate -T vg0/pool0 -V 9 -n volume0
  Rounding up size to full physical extent 12.00 MiB
  Logical volume "volume0" created.

** thin pool

#+begin_example
  root@guixsd ~# lvcreate -l 100%FREE --thinpool thinpool2 lvm2
    Thin pool volume with chunk size 1.00 MiB can address at most 253.00 TiB of data.
    WARNING: Pool zeroing and 1.00 MiB large chunk size slows down thin provisioning.
    WARNING: Consider disabling zeroing (-Zn) or using smaller chunk size (<512.00 KiB).
    Logical volume "thinpool2" created.
#+end_example

#+begin_example
  root@guixsd ~# lvs
    LV                            VG   Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
    almalinux                     lvm1 -wi-a-----  30.00g
    centos                        lvm1 -wi-a-----  20.00g
    centos7                       lvm1 -wi-a-----  32.00g
    debian1                       lvm1 -wi-a-----  16.00g
    debian2                       lvm1 -wi-a-----  16.00g
    guix                          lvm1 -wi-a-----  64.00g
    guix-test                     lvm1 -wi-a-----  40.50g
    nginx99                       lvm1 -wi-a-----  34.00g
    nixos                         lvm1 -wi-a-----  20.00g
    nixos-test                    lvm1 -wi-a-----  20.00g
    qubeos                        lvm1 owi---s---  64.00g
    qubeos-snap1                  lvm1 swi---s---  32.00g      qubeos
    qubes                         lvm1 -wi-a-----  64.00g
    test                          lvm1 -wi-a-----  10.00g
    ubuntu                        lvm1 -wi-a-----  64.00g
    web99                         lvm1 -wi-a-----  80.00g
    whonix-gateway-direct         lvm1 -wi-a-----   8.00g
    whonix-workstation-qbittorent lvm1 -wi-a-----  10.00g
    win10                         lvm1 -wi-a-----  40.00g
    ntfs-games                    lvm2 -wi-a----- 520.00g
    thinpool2                     lvm2 twi-a-tz--  <1.22t             0.00   10.43
    ubuntu22.04                   lvm2 -wi-a-----  20.00g
#+end_example

* Learning
- [[https://www.linuxsysadmins.com/create-thinly-provisioned-logical-volume/][Create a Thinly Provisioned Logical Volume on Linux]]

* Backup
- [[https://github.com/tasket/wyng-backup][tasket/wyng-backup: Fast Time Machine-like backups for logical volumes]]

* Cheatsheet

- create logical volume
  : lvcreate -L 100G lvm1 -n whonix-gateway

- Fix "LV Status" is "NOT available"
  : vgchange -a y VOLNAME

* Snapshots

root@guixsd ~ [env]# modprobe dm-snapshot
root@guixsd ~ [env]# lvcreate -L 32G -n qubeos-snap1 -s /dev/lvm1/qubeos
File descriptor 5 (/gnu/store/9dwykxc9sdml1fn9d8hgpsfifb9fv684-guix-command) leaked on lvcreate invocation. Parent PID 30051: /gnu/store/d99ykvj3axzzidygsmdm
  Logical volume "qubeos-snap1" created.

- revert changes
  : lvconvert --merge /dev/lvm1/qubeos-snap1

- delete snapshot and save changes
  : lvremove /dev/lvm1/qubeos-snap1

** MariaDB

- [[https://www.oreilly.com/library/view/mariadb-high-performance/9781783981601/ch11s03.html][LVM - MariaDB High Performance Book]]

To make a usable MariaDB datadir snapshot, you first need to lock your tables:
: MariaDB [(none)]> flush tables with read lock;

Now we're sure there will be no changes on our instance. Let's create the
snapshot on the system:
: lvcreate --snapshot -n snap_mariadb ...

* Mount

#+begin_example
  root@guixsd ~ [env]# parted /dev/lvm1/debian1 
  GNU Parted 3.4
  Using /dev/dm-11
  Welcome to GNU Parted! Type 'help' to view a list of commands.
  (parted) unit                                                             
  Unit?  [compact]? B                                                       
  (parted) print                                                            
  Model: Linux device-mapper (linear) (dm)
  Disk /dev/dm-11: 17179869184B
  Sector size (logical/physical): 512B/4096B
  Partition Table: gpt
  Disk Flags: 

  Number  Start       End           Size          File system  Name  Flags
  14      1048576B    4194303B      3145728B                         bios_grub
  15      4194304B    134217727B    130023424B    fat16              boot, esp
   1      134217728B  17179852287B  17045634560B  ext4
#+end_example

#+begin_example
  mount -o loop,offset=134217728 /dev/lvm1/debian1 /mnt/debian1
#+end_example
