:PROPERTIES:
:ID:       9bd9dd4b-0d7b-45b0-b9e3-5a9d54f8417e
:END:
- snapshot
  : lvcreate --size 4G --snapshot --name magnolia--vg-root-01 /dev/mapper/magnolia--vg-root
- [[https://www.man7.org/linux/man-pages/man7/lvmvdo.7.html][lvmvdo(7) - Linux manual page]]
- [[https://storytime.ivysaur.me/posts/why-not-zfs/][Why not ZFS]]

root@guixsd ~ [env]# pvcreate /dev/sdd5 
File descriptor 5 (/gnu/store/2rlcdsb7p3njs7wbh2nanyl7j14gwj1w-guix-command) leaked on pvcreate invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
File descriptor 14 (socket:[112552]) leaked on pvcreate invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
  Physical volume "/dev/sdd5" successfully created.

root@guixsd ~ [env]# vgcreate lvm1 /dev/sdd5
File descriptor 5 (/gnu/store/2rlcdsb7p3njs7wbh2nanyl7j14gwj1w-guix-command) leaked on vgcreate invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
File descriptor 14 (socket:[112552]) leaked on vgcreate invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
  Volume group "lvm1" successfully created

root@guixsd ~ [env]# vgchange -a y lvm1
File descriptor 5 (/gnu/store/2rlcdsb7p3njs7wbh2nanyl7j14gwj1w-guix-command) leaked on vgchange invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
File descriptor 14 (socket:[112552]) leaked on vgchange invocation. Parent PID 8206: /gnu/store/d99ykvj3axzzidygsmdm
  0 logical volume(s) in volume group "lvm1" now active

root@guixsd ~ [env]# virsh pool-define-as lvm1 logical --source-name lvm1 --target /dev/sdd5 
Pool lvm1 defined

root@guixsd ~ [env]# virsh pool-start lvm1
Pool lvm1 started


[root@localhost ~]# pvcreate /dev/vdb1
  Physical volume "/dev/vdb1" successfully created.
[root@localhost ~]# vgcreate vg0 /dev/vdb1
  Volume group "vg0" successfully created
[root@localhost ~]# lvcreate -l 100%FREE -Zn --type thin-pool --thinpool pool0 vg0
  Thin pool volume with chunk size 64.00 KiB can address at most <15.88 TiB of data.
  Logical volume "pool0" created.
[root@localhost ~]# lvcreate -T vg0/pool0 -V 9 -n volume0
  Rounding up size to full physical extent 12.00 MiB
  Logical volume "volume0" created.

* Snapshots

root@guixsd ~ [env]# modprobe dm-snapshot
root@guixsd ~ [env]# lvcreate -L 32G -n qubeos-snap1 -s /dev/lvm1/qubeos
File descriptor 5 (/gnu/store/9dwykxc9sdml1fn9d8hgpsfifb9fv684-guix-command) leaked on lvcreate invocation. Parent PID 30051: /gnu/store/d99ykvj3axzzidygsmdm
  Logical volume "qubeos-snap1" created.

- revert changes
  : lvconvert --merge /dev/lvm1/qubeos-snap1

- delete snapshot and save changes
  : lvremove /dev/lvm1/qubeos-snap1
