:PROPERTIES:
:ID:       4f9e0884-5ba6-4405-b4ee-68046655de58
:END:
- [[https://habr.com/ru/company/flant/blog/572340/][MySQL в Docker не может писать slow-логи в /dev/stderr / Хабр]]
- [[https://mariadb.com/kb/en/innodb-recovery-modes/][InnoDB Recovery Modes - MariaDB Knowledge Base]]
- [[https://github.com/datacharmer/test_db][datacharmer/test_db: A sample MySQL database with an integrated test suite, used to test your applications and database servers]]
- [[https://mariadb.com/kb/en/setting-up-a-replica-with-mariabackup/][Setting up a Replica with Mariabackup - MariaDB Knowledge Base]]

* Learning

- [[https://severalnines.com/blog/how-to-rebuild-inconsistent-mysql-slave/][How to Rebuild an Inconsistent MySQL Slave? | Severalnines]]
- [[https://habr.com/ru/post/56702/][Основы репликации в MySQL / Хабр]]

* Master slave replication

#+begin_example
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [ERROR] InnoDB: The error means the system cannot find the path specified.
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [ERROR] InnoDB: If you are installing InnoDB, remember that you must create directories yourself, InnoDB does not create them.
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [ERROR] InnoDB: Cannot open datafile for read-only: './foobar/phpbb_extensions.ibd' OS error: 71
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [ERROR] InnoDB: Operating system error number 2 in a file operation.
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [ERROR] InnoDB: The error means the system cannot find the path specified.
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [ERROR] InnoDB: If you are installing InnoDB, remember that you must create directories yourself, InnoDB does not create them.
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [ERROR] InnoDB: Could not find a valid tablespace file for ``foobar`.`phpbb_extensions``. Please refer to https://mariadb.com/kb/en/innodb-data-dictionary-troubleshooting/ for how to resolve the issue.
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [Warning] InnoDB: Ignoring tablespace for `foobar`.`phpbb_extensions` because it could not be opened.
  Nov 02 15:22:34 dc-1 mysql-pre-start[1680160]: 2021-11-02 15:22:33 0 [ERROR] InnoDB: Operating system error number 2 in a file operation.
#+end_example

The restore process for partial backups is quite different than the process
for full backups. A partial backup is not a completely functional data
directory. The data dictionary in the InnoDB system tablespace will still
contain entries for the databases and tables that were not included in the
backup.

Rather than using the --copy-back or the --move-back, each individual InnoDB
file-per-table tablespace file will have to be manually imported into the
target server. The process that is used to import the file will depend on
whether partitioning is involved.

*  [[https://artkiev.com/blog/error-plugin-innodb-init.htm][MySQL ошибка InnoBD: Plugin InnoDB init function returned error » Блог. ArtKiev Design Studio]]

MySQL ошибка InnoBD: Plugin InnoDB init function returned error

После обновления сервера произошел неприятный момент. Причем обнаружилось это
спустя 2 месяца после обновлений. Все дело в том, что на всех таблицах у нас
использовался MyISAM. Сервер стартовал, все отлично работало, пока не
понадобилось создать таблицы в InnoBD. Вариант выбора InnoBD просто
отсутствовал в списке выбора форматов хранения.[sql]130102 9:33:01 [ERROR]
Plugin 'InnoDB' init function returned error.130102 9:33:01 [ERROR] Plugin
'InnoDB' registration as a STORAGE ENGINE failed.[/sql]

Обратившись в поддержку, выяснилось, что вариантов решения есть несколько, но
все они не помогли.  Начали танцевать с бубнами и о чудо!  Если у вас в
конфиге MySQL InnoBD и MyISAM хранятся в разных папках - это и есть весь
корень зла.

 
Решение ошибки: Plugin InnoDB init function returned error

- Нужно остановить сервер.
- Удалить строку innodb_data_home_dir из конфигурационного файла
- В каталоге где хранятся базы данных найти и удалить: ib_logfile0,
  ib_logfile1, ib_logfile2, ibdata1
- Запустить сервер

Осторожно. Если у вас уже были таблице с InnoBD - они могут
пострадать. Делайте бэкап данных всегда!
