  - https://social.heldscal.la/main/public

  - 2252304

  - [[https://superuser.com/questions/972233/how-do-i-convert-utf-8-special-characters-in-bash][How do I convert UTF-8 special characters in Bash?]]
    : echo '=?UTF-8?B?U2Now7ZuZSBHcsO8w59lIQ==?=' | perl -CS -MEncode -ne 'print decode("MIME-Header", $_)'

  - [[https://www.zeitverschiebung.net/en/timezone/asia--bangkok][Timezone Linux Online]]

  - Стирка
    + Порошек половина станака
    + Кондиционер половина крышки
    + Светлая одежда: Смешанные ткани
    + Темная одежда: Темные ткани

  - 09:10 Code meta data
    + wikidata
    + fsf directory
    + libraries.io

  - http://www.nongnu.org/pretest/command-line-qemu.html

  - https://quitter.is/main/all
  - eternal-september.org

#+BEGIN_EXAMPLE
  +To find a patch file at point invoke @kbd{M-x guix-devel-ffap-patch}
  +command.  If you want to do this with a @kbd{M-x ffap} command, you
  +can do it like this:
  +
  +@example
  +(add-to-list 'ffap-alist '("\\.patch" . guix-devel-ffap-patch))
#+END_EXAMPLE

 - Implement builtins in lisp https://stackoverflow.com/q/3683388

 - next browser
   : LD_LIBRARY_PATH=/home/natsu/.guix-profile/lib sbcl
   : (asdf:load-asd "/home/natsu/quicklisp/local-projects/nEXT/next/next.asd")
   : (ql:quickload :next)
   : "TLS/SSL support not available; install glib-networking"

 - dd with progress bar
   : dd if=/dev/sda bs=1M | pv | dd of=/dev/sdc bs=1M

 - Convert JPEG and PNG to ASCII
   : guix package --install jp2a

 - Manually start GNOME Wayland
   : XDG_SESSION_TYPE=wayland dbus-run-session gnome-session

 - Print the commands that are being run during =make=
   : make V=1

 - Time conversion
   : date -d 'TZ="US/Eastern" 9am tomorrow'

 - Curl IMAP
   #+BEGIN_SRC shell
     curl -s --insecure --url "imaps://whatever.imap.server" --user\
     "myuserid:mypassword" --request "STATUS INBOX (UNSEEN)"
   #+END_SRC

 - What file it tries and fails to dlopen
   : LD_DEBUG=files emacs

 - Show dynamic libraries
   : ldd $(dirname $(readlink -f $(type -P emacs)))/.emacs-25.3-real | grep glibc

 - Show object
   : objdump -p /gnu/store/…-spectrwm-3.1.0/lib/libswmhack.so.0.0

 - [[/home/natsu/Downloads/ISO/05001-10000/ISO%2009660-1988%20scan.pdf][iso files]]

 - headsets like thinkpad style
   #+BEGIN_QUOTE
        <drewbinaj> I could spend up to around $250
        <drewbinaj> damn those headphones are crazy lol
        <drewbinaj> is he saying he just uses those? hyperx cloud 2's?
        <the_dilbobaggins> sorry, right no sound
        <the_dilbobaggins> they're rig 515
   #+END_QUOTE

 - https://unix.stackexchange.com/a/42933
   #+BEGIN_SRC shell
     #!/bin/bash
     #
     # L Nix <lornix@lornix.com>
     # reload browser window
     #
     # whether to use SHIFT+CTRL+R to force reload without cache
     RELOAD_KEYS="CTRL+R"
     #RELOAD_KEYS="SHIFT+CTRL+R"
     #
     # set to whatever's given as argument
     BROWSER=$1
     #
     # if was empty, default set to name of browser, firefox/chrome/opera/etc..
     if [ -z "${BROWSER}" ]; then
         BROWSER=firefox
     fi
     #
     # get which window is active right now
     MYWINDOW=$(xdotool getactivewindow)
     #
     # bring up the browser
     xdotool search --name ${BROWSER} windowactivate --sync
     # send the page-reload keys (C-R) or (S-C-R)
     xdotool search --name ${BROWSER} key --clearmodifiers ${RELOAD_KEYS}
     #
     # sometimes the focus doesn't work, so follow up with activate
     xdotool windowfocus --sync ${MYWINDOW}
     xdotool windowactivate --sync ${MYWINDOW}
   #+END_SRC

 - Zevenet :: Load balancer

 - https://peers.community/

 - Stumpwm get current window PID
   : (xlib:get-property (window-xwin (current-window)) :_net_wm_pid)

 - [[http://jk.ozlabs.org/projects/patchwork/][Patchwork]] :: Patchwork is a web-based patch tracking system designed
      to facilitate the contribution and management of contributions to
      an open-source project.

 - [[https://docs.google.com/presentation/d/1PkeO_lC5WTPScSV3ZzEEjVuDWeQtL2eHK6jEcf7axA0/edit#slide=id.g2a3d5327f3_30_0][Rossmann Repair Training Guide]]
 - [[https://rutracker.org/forum/viewtopic.php?t=5355404][SHENZHEN I/O]]

 - https://fosdem.org/2018/schedule/event/vai_qemu_in_uefi/

 - https://brilliant.org/
 - https://www.youtube.com/channel/UCaTznQhurW5AaiYPbhEA-KA
 - https://www.youtube.com/watch?v=oVyx9L3IGfs

 - /gnu/store/3bmsc44drb7siv8bf7jxndmdwmvgpyip-tor-0.3.2.9/bin/torify: torsocks not found in your PATH.  Perhaps it isn't installed?  (tsocks is no longer supported, for security reasons.)

 - https://appdb.winehq.org/objectManager.php?sClass=version&iId=28786&iTestingId=91445

 - [[https://www.reddit.com/r/emacs/comments/83frxm/reading_managing_annotating_and_highlighting/dvhkvza/][Zotero]] :: PDF library manager

* Articles
  - http://www.shakthimaan.com/downloads.html#gpg-in-10-minutes

* Sites
  - https://www.bibsonomy.org/
  - [[https://repology.org/][Repology, the packaging hub]]
  - [[https://ecraven.github.io/r7rs-benchmarks/][r7s7 benchmarks]]
  - https://git.savannah.nongnu.org/cgit/
  - https://git.savannah.gnu.org/cgit/
  - https://directory.fsf.org
  - https://www.fsf.org/licensing/
  - https://www.defectivebydesign.org/
  - https://www.fsf.org/resources/hw/endorsement/respects-your-freedom
  - https://www.gnu.org/philosophy/open-source-misses-the-point.html
  - https://12starsmedia.com/video-production/how-to-download-archive-your-entire-youtube-library
  - https://www.google.com/takeout/#custom:youtube
  - https://stockfishchess.org/
** Pastebin
   - http://sprunge.us/

* Streams
  - https://www.youtube.com/channel/UCK-d8Z08ElRz0zgKiAla5fg
  - https://www.youtube.com/user/gameglaz
  - https://www.youtube.com/user/igroglaz
  - https://www.youtube.com/user/streamguild

* Scan all Internet
  #+BEGIN_SRC shell
    sudo nmap -Pn -sS -p 70 -iR 0 --open --min-parallelism=4096 -T5
      -oG /dev/stdout 2>/dev/null | grep '70/open' | awk '{print $2}' | xargs -I
      '{}' sh -c "curl -m 3 -s 'gopher://{}' > /dev/null && echo '{}'"
  #+END_SRC

* Dovecot
  #+BEGIN_SRC shell
    doveadm -c CONFIG search -A mailbox INBOX
    doveadm -c CONFIG search -u 'natsu' mailbox '*' since 1d unseen
  #+END_SRC

  #+BEGIN_SRC shell
    doveadm -c /gnu/store/…-dovecot.conf fetch body\
            mailbox-guid 08ad6405a8bffe591a340000d09efc50 uid UID
    doveadm -c /gnu/store/…-dovecot.conf expunge\
            mailbox INBOX from MAIL_ADDRESS
  #+END_SRC

* Windows offline share

  Create a block device

  #+BEGIN_SRC sh
    fallocate -l 1G drive.img
  #+END_SRC

  Boot virtual machine and partition it

  #+BEGIN_SRC sh
    qemu-system-x86_64 -enable-kvm -m 4096 -cpu host -daemonize -smp 2\
                       -net none -hda /tmp/windows-7.qcow2 -hdb drive.img
  #+END_SRC

  Get partition offset

  #+BEGIN_SRC sh
    fdisk -l /tmp/drive.img
  #+END_SRC

  Mount

  #+BEGIN_SRC sh
    mount -t vfat -o loop,offset=$((128*512)) drive.img /mnt
  #+END_SRC

* C

uint32_t *val = (uint32_t *) value; means "declare val as a pointer to
a 32-bit unsigned integer that points to an integer whose address is
the same as the address of the char pointed to by value"

** Keep PC busy

   #+BEGIN_SRC c
     #include <pthread.h>

     static void *
     foo (void *data)
     {
       while (1);
     }

     int main ()
     {
       pthread_t thr;

       for (int i = 0; i < 31; i++)
         pthread_create (&thr, NULL, foo, NULL);

       while (1);
     }

     // gcc -o busy this-file.c -pthread
   #+END_SRC

* Firefox
  =gfx.xrender.enabled=false= in IceCat/GuixSD.  Enabling it made the
  IceCat/GuixSD performance about the same as Firefox/Debian (which
  comes w/ =gfx.xrender.enabled=true=).

* Replicant Andoid
  In Android, starting from 6.0, there is a new feature called
  safe-mode that can be triggered by keeping then volume up and volume
  down buttons pressed during boot.

* Hydra
  - URL examples
    #+BEGIN_SRC emacs-lisp
      (mapcar (lambda (query) (concat "https://hydra.gnu.org/" query))
              '("queue" "status" "machines" "evals" "all" "build/2454846"))
    #+END_SRC

* Video editors
  - http://mltframework.org
  - http://shotcut.org
  - gneve

* TODO geiser-connection-timeout
  #+BEGIN_EXAMPLE
      <wigust> dustyweb: geiser-connection-timeout is interesting,
               let me know how it goes please :-)
             ,* dustyweb setq's and waits :)
    <dustyweb> wigust: that fixed it!  [01:17]
    <dustyweb> wigust: I set it to 100000 ... 100 seconds :)
      <wigust> dustyweb: cool, great to know about this variable,
               thx  [01:18]
    <dustyweb> wigust: so you could also supply a higher value:
           ,*** catonano (~user@151.45.37.164) has joined channel
               #guix  [01:19]
    <dustyweb> geiser-eval--send/wait takes a timeout value
    <dustyweb> wigust: so you could possibly set something higher
               ;)
    <dustyweb> but maybe you shouldn't :)
    <dustyweb> I dunno :)
      <wigust> dustyweb: Maybe for guix-all-available-packages
               this should be greater by default
    <dustyweb> wigust: yes  [01:20]
    <dustyweb> probably!
    <dustyweb> wigust: I'm on an old machine but I'm not sure if
               it's my profile making it slow
    <dustyweb> or if just that guix has so many packages now..
    <dustyweb> wigust: so what would happen if one of the synopsis
               fields had #t or #f in them? ;)  [01:21]
    <dustyweb> would the regex replace it?
  #+END_EXAMPLE

* Grub
  Message-Id: <20180119100415.fe7d979f7c505a5e19dbce82@laposte.net>
  file:/boot/grub/grub.cfg
  #+BEGIN_EXAMPLE
    menuentry "Linux" {
            insmod all_video
            echo "Loading Linux..."
            search --no-floppy -u --set=root 20f4d726-6cec-4f00-b941-bab03fdff981
            linux /boot/vmlinuz root=/dev/sda3 ro
    }
    menuentry "Windows" {
            echo "Loading Windows..."
            search --no-floppy -u --set=root 7E75-0EC2
            chainloader /EFI/Microsoft/Boot/bootmgfw.efi
    }
  #+END_EXAMPLE

* Linux
  - [[https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html][Kernel parameters]]
  - [[https://askubuntu.com/questions/992137/how-to-check-that-kpti-is-enabled-on-my-ubuntu][Check if KPTI is enabled]]

* GNU

** Mirrors
   - http://mirror.reismil.ch/gnu/
   - https://mirror.cyber-perikarp.eu/gnu/

* Libraries
  - http://libgen.io
  - https://libraries.io/
  - https://arxiv.org/
  - http://ieeexplore.ieee.org/

** Mailing list archives
  - http://www.nabble.com/

** Research
   - https://zenodo.org/

* Testing software
  - https://systemundertest.org/xterm/

* TODO Typo in (guile) Creating a Procedure

   Before very long, though, you will want to create new procedures that
encapsulate aspects of your own applications’ functionality.  To do
this, you can use the famous ‘lambda’ syntax.
- check the unread count directly
  #+BEGIN_SRC shell
    curl -s --insecure --url "imaps://whatever.imap.server" --user\
    "myuserid:mypassword" --request "STATUS INBOX (UNSEEN)"
  #+END_SRC

* Standarts

  - [[http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html][ISO]]

* Translation

  - http://www.iro.umontreal.ca/contrib/po/HTML/teams.html
  - http://www.iro.umontreal.ca/contrib/po/HTML/leaders.html
  - http://www.iro.umontreal.ca/contrib/po/HTML/index.html

#+BEGIN_EXAMPLE
  If you're talking about a system roughly comparable with MacOS,
  I'm sure you mean GNU/Linux, not Linux which is a kernel only.

  Many people do call the system "Linux", but when they do, it treats us
  unfairly by attributing our work to someone else.  "Us" includes
  everyone contributing to the GNU Project, including everyone that
  works on GNU Emacs.  Would you please give us equal mention by saying
  "GNU/Linux"?
#+END_EXAMPLE

- [[http://debian-help.ru/web-servers/ab-apache-benchmark-test-proizvoditelnosti-servera/][Howto Apache Benchmark]]
- [[https://www.inmotionhosting.com/support/website/server-usage/view-level-of-traffic-with-apache-access-log][Howto Parse Apache logs]]
- [[http://bradthemad.org/tech/notes/exim_cheatsheet.php][exim cheatsheet]]
