:PROPERTIES:
:ID:       cec0346f-1183-44d2-81fc-f6b02c47fbd6
:END:

* Tools
- [[https://github.com/basings/selfhosted-music-overview][basings/selfhosted-music-overview: A table listing software network services which can be hosted on your own servers]]
- [[https://github.com/benjojo/dubstep-data][benjojo/dubstep-data: Put data inside dubstep drops]]
- [[https://github.com/CircuitCoder/cuedflacfs][CircuitCoder/cuedflacfs: FUSE for exposing CUE/FLAC CD archives as individual FLAC tracks]]
- [[https://github.com/HackerPoet/FractalSoundExplorer][HackerPoet/FractalSoundExplorer: Explore fractals in an audio-visual sandbox]]
- [[https://github.com/ironsmile/euterpe][ironsmile/euterpe: Self-hosted music streaming server 🎶 with RESTful API and Web interface. Think of it as your very own Spotify!]]
- [[https://github.com/koel/koel][koel/koel: A personal music streaming server that works.]]
- [[https://github.com/SheetAble/SheetAble][SheetAble/SheetAble: Self-hosted music sheet organizing software]]
- [[https://github.com/navidrome/navidrome][navidrome/navidrome: Modern Music Server and Streamer compatible with Subsonic/Airsonic]]
- [[https://github.com/epoupon/lms][epoupon/lms: Lightweight Music Server. Access your self-hosted music using a web interface.]]
- [[https://github.com/ampache/ampache][ampache/ampache: A web based audio/video streaming application and file manager allowing you to access your music & videos from anywhere, using almost any internet enabled device.]]
- [[https://github.com/FerryYoungFan/FanselineVisualizer][FerryYoungFan/FanselineVisualizer: Convert audio files to visualized video]]
- [[https://github.com/airsonic-advanced/airsonic-advanced][Airsonic is a free, web-based media streamer, providing ubiquitous access to your music]]
- [[https://github.com/sentriz/gonic][sentriz/gonic: music streaming server / subsonic server API implementation]]
- [[https://github.com/jeffvli/sonixd][jeffvli/sonixd: A full-featured Subsonic/Jellyfin compatible desktop music player]]
- [[https://github.com/tamland/airsonic-refix][tamland/airsonic-refix: Modern UI for Airsonic / Subsonic]]
- [[https://github.com/bytedance/music_source_separation][bytedance/music_source_separation]]
- [[https://github.com/krateng/maloja][krateng/maloja: Self-hosted music scrobble database to create personal listening statistics and charts]]
- [[https://github.com/SeaDve/Mousai][SeaDve/Mousai: Identify songs in seconds]]
- [[https://github.com/tsoding/musializer][tsoding/musializer: Music Visualizer]]
- [[https://github.com/schollz/collidertracker][schollz/collidertracker: A terminal-based music tracker that uses SuperCollider for synthesis and sample playback.]]

* Services
- [[https://www.pepper.ru/deals/yandeksplyus-2-mesyaca-za-1rub-dlya-vsex-182967][Яндекс.Плюс 2 месяца за 1₽ для всех без активной подписки]]

* Streaming
- [[https://github.com/soundscapecloud/soundscape][soundscapecloud/soundscape: Soundscape - a personal music streaming server]]

* Search
- [[https://habr.com/ru/company/audiomania/blog/522728/][«Найди все сам»: как подбирать музыку для работы и отдыха без помощи рекомендательных систем / Блог компании Аудиомания / Хабр]]
- [[https://habr.com/ru/company/audiomania/blog/522616/][«Что угодно кроме алгоритмов»: где искать музыку, если стриминговые платформы уже надоели / Блог компании Аудиомания / Хабр]]

* Libraries

- https://www.metal-archives.com/
- https://librivox.org/
- http://freemusicarchive.org/
- [[https://bandcamp.com/][Bandcamp]]

* Tracks

- Mix - Mia Martina feat. Waka Flocka - Beast (Official Video)
- [[https://www.youtube.com/watch?v=am36QHp-TgQ][Lineage 2 New Best Soundtrack Compilation]]
- [[https://www.youtube.com/channel/UCVXzBnzP5i5W-3snrxu8kfg/videos][EVERGLOW]]
- [[file:/srv/music/MV_YEZI_Cider.mkv][Yezi - 사이다 cider]]
- [[file:/srv/music/GARNiDELiA - Mirai-nziMTeijTZw.mkv]]
- [[file:/srv/music/M_V 1NB(원앤비) - STALKER(스토커) (섹시 Sexy Ver.)-IST2JgPOlUI.mkv]]
- [[file:/srv/music/Kizumonogatari [AMV] Hope Of Morning (Lyrics)-HOAQaPy5Hgs.mkv]]
- [[file:/srv/music/[HOT] 4MINUTE - Canvas, 포미닛 - Canvas Show Music core 20160213-GC33VMCiZ34.mkv]]
- [[file:/srv/music/Best of NoCopyrightSounds _ Gaming Music 2017 _ Best of EDM-zyrBp8sx5A4.mkv]]

** Greek
- [[https://www.youtube.com/watch?v=g5WQcoluFEA][(13) Fluffy Time (Original Mix) - YouTube]]

* Metal

- Fairy Tail - Doriarte [New 2016 Ost]
- Fairy Tail - Tempester the Immortal [New 2016 Ost]
- Fairy Tail - Carbuncle Raishuu Ost
- Fairy Tail - Ezel's Theme

- [[file:/srv/videos/Angel_Dust_-_Bleed.mkv]]
- [[file:/srv/videos/Mercenary_-_Through_Our_Darkest_Days.mkv]]

- [[file:/srv/videos/Dissection_-_Black_Dragon.mkv]]
- [[file:/srv/videos/GRAVE_DIGGER_-_Highland_Farewell_Official.mkv]]

- [[file:/srv/videos/AVATARIUM_-_Moonhorse_OFFICIAL_LYRIC_VIDEO.mkv]]
- [[file:/srv/videos/Ghost_-_Cirice.webm]]

- [[file:/srv/videos/HAMMERFALL_-_Any_Means_Necessary_OFFICIAL_MUSIC_VIDEO.mkv]]

- [[file:/srv/videos/KORPIKLAANI_-_Vodka_OFFICIAL_VIDEO.mkv]]

- [[file:/srv/videos/Mercyful_Fate_Come_to_the_Sabbath.webm]]

- [[file:/srv/videos/Metallica_-_Fade_to_Black.mkv]]
- DS」Mad Hatter [Public MEP]-_Ug-enFt9CQ.mkv
- [[file:/srv/music/Monogatari AMV • Red Lips-7QO2Fn-4i8E.mkv]]
- [[file:/srv/music/Shimoneta AMV • RIOT-eCmJTxLl3Bg.mkv]]

- Anime Mix- Savior-tFE6G6rNS1E.mkv
- https://www.youtube.com/watch?v=rIEA3Eq8j5Y

- https://www.youtube.com/watch?v=4CTGxKIzD7M

- [[https://www.youtube.com/playlist?list=PL4YsUf1g7HB59vTrl6n7IpySBX0fBvvo9][(54) Royalty Free Metal - YouTube]]

- [[https://www.metal-archives.com/albums/Emperor/In_the_Nightside_Eclipse/93][Emperor - In the Nightside Eclipse - Encyclopaedia Metallum: The Metal Archives]]

- cradle of fith - existense is futile

- Twilight Force

- [[https://www.youtube.com/watch?v=VO5emLlZ9Cg][Lunatic Gods - Starecká - YouTube]]

- Sepultura
- Soulfly

* YouTube

  - [[https://www.youtube.com/channel/UCJ6td3C9QlPO9O_J5dF4ZzA][Mostercat]]
  - [[https://www.youtube.com/watch?v=-O3cZ3M4hAo][Perturbator]]
  - [[https://www.youtube.com/user/FirstClassTrashView][(93) First Class Trash - YouTube]]

* Monstercat

- Pixl Rat Twist
- /srv/music/[Special Clip] 몬스타엑스 (MONSTAX) - 히어로 (HERO) Rooftop Ver.-FZ9lJ5ctd0s.mkv

* LOL

- Если мент спросит документ
- Френдзона Бойчик

* [[https://docs.google.com/document/d/19vE-9RgYG1k79BU6801eP4zYVj08RDt_JrV4GUnSW40/edit][Мой плейлист STRIM KAEF - Google Docs]]

Если вы хотите предложить новую музыку, то воспользуйтесь наградой за баллы канала на твиче. 

МОЙ МУЗЫКАЛЬНЫЙ ПЛЕЙЛИСТ НА СТРИМЕ:

kerbal x BLANKED x MehDead — Ex Mashup
!nfsmw.mp3  Styles of Beyond - Nine Thou
1942.mp3 Battlefield 1942 soundtrack main theme
3 Doors Down - I'm Here without You Baby.mp3
50 Cent - Disco Inferno
50 Cent - In Da Club.mp3
50 Cent - Just A Lil Bit.mp3
50 Cent - P.I.M.P.mp3
50 Cent feat. Olivia - Candy Shop.mp3
ABBA - Lay All Your Love On Me.mp3
AC?DC (ost Supernatural) - Highway To Hell.mp3
ACDC - Back In Black (OST Iron Man ).mp3
Adele - Rolling in the Deep.mp3
Aerosmith - Dream On.mp3
a-ha - Take on Me.mp3
Akcent - Too Late to Cry.mp3
Akon feat. Eminem - Smack That.mp3
Ak'Sent - Kylie.mp3
Alexander Rybak - Fairytale.mp3
Alice Cooper - Poison.mp3
Alient Ant Farm - Smooth Criminal (OST Американский пирог 2).mp3
Alyans - Na Zare.mp3
America - A horse with no name.mp3
And I say, hey hey hey hey. - I said hey, what's going on.mp3
Animal Джаz - Чувства.mp3
Aqua - Barbie Girl.mp3
Arash - Boro Boro.mp3
Arash feat. Shaggy - Donya.mp3
Ava Max - Kings & Queens.mp3
Ava Max - Salt.mp3
Avicii - Levels (Original Mix).mp3
Avicii - Waiting For Love.mp3
Avicii feat. Aloe Blacc - Wake Me Up.mp3
Avril Lavigne - Complicated.mp3
Avril Lavigne - Girlfriend.mp3
Avril Lavigne - Hot.mp3
B.J. Thomas - Raindrops Keep Falling On My Head (Re-Recorded).mp3
Bag Riders - Shooting Stars.mp3
Basshunter - All I Ever Wanted.mp3
Basshunter - Dota.mp3
Basshunter - I Can Walk on Water.mp3
Basshunter - Now You're Gone.mp3
Battlefield Bad Company 2 Vietnam OST (Box Tops) - The letter.mp3
Battlefield Vietnam - Cat Stevens - Wild World.mp3
bbno$ feat. Rich Brian - edamame.mp3
BENEE feat. Gus Dapperton - Supalonely.mp3
Beyoncé - Single Ladies (Put a Ring on It).mp3
Beyoncé - Sweet Dreams.mp3
Beyoncé, Shakira - Beautiful Liar.mp3
Billie Eilish - everything i wanted.mp3
Billy Talent - Devil In A Midnight Mass.mp3
Billy Talent - Red Flag.mp3
Billy Talent - Worker Bees.mp3
Black Eyed Peas - The Time.mp3
Blake Shelton - Footloose.mp3
Blondie - Call Me.mp3
Bloodhound Gang - American Bitches.mp3
BLOODHOUND GANG - The Bad Touch (Original).mp3
Bloodhound Gang - Uhn Tiss Uhn Tiss Uhn Tiss.mp3
Blue - Curtain Falls.mp3
Blur - Song 2.mp3
Bon Jovi - It's my life w- lyrics.mp3
Bon Jovi - Livin' On A Prayer.mp3
Boney M. - Rasputin.mp3
Boni M - Барбара Стрейзант.mp3
Bonie Tyler - I Need A Hero.mp3
Bosson - Walking.mp3
brainpower.mp3
Breaking Benjamin - Follow.mp3
Breaking Benjamin - So Cold.mp3
Britney Spears - Oops.I Did It Again.mp3
Britney Spears - Till the World Ends.mp3
Britney Spears - Toxic.mp3
Busta Rhymes, Mariah Carey feat. Flipmode Squad - I Know What You Want.mp3
C.C. CATCH - Cause You Are Young.mp3
Евро & Status Quo - - In The Army Now 2005_Архив Радио DFM_ D-Чарт Хит-парад за .mp3
Caramell - Caramelldansen.mp3
Caravan Palace - Lone Digger.mp3
Carly Rae Jepsen - Call Me Maybe.mp3
Carly Rae Jepsen - I Really Like You.mp3
CC Catch - Strangers By Night.mp3
Celline Dion - My heart will go on.mp3
Chamillionaire feat. Krayzie Bone - Ridin'.mp3
Chris Norman & C. C. Catch - Stumblin in.mp3
Chumbawamba - Tumbthumping.mp3
Clean Bandit feat. Sean Paul, Anne-Marie - Rockabye (feat. Anne-Marie & Sean Pau.mp3
Coldplay - A Sky Full Of Stars.mp3
Coldplay - Adventure of a Lifetime.mp3
Coldplay - In My Place.mp3
Coldplay - Paradise (Official Video).mp3
Coldplay - The Scientists.mp3
Coldplay (ft. Beyonce) - Hymn For The Weekend.mp3
Coolio feat. L.V. - Gangsta's Paradise (feat. L.V.).mp3
craig david-  7 days.mp3
Craig David feat. Sting - Rise & Fall.mp3
Crazy Town - Butterfly.mp3
Creedence Clearwater Revival - Fortunate Son.mp3
Cutting Crew - (I Just) Died In Your Arms.mp3
Daft Punk - Harder, Better, Faster, Stronger.mp3
Daft Punk feat. Pharrell Williams, Nile Rodgers - Get Lucky.mp3
Darude - Feel The Beat.mp3
Darude - Sandstorm.mp3
Daryl Hall & John Oates - You Make My Dreams (Come True).mp3
David Guetta - Baby when the light.mp3
David Guetta - In Love With Myself.mp3
David Guetta - Love Dont Let Me Go (Original Edit).mp3
David Guetta - The World Is Mine.mp3
David Guetta feat. Akon, Ne-Yo - Play Hard (feat. Ne-Yo & Akon).mp3
David Guetta feat. Kid Cudi - Memories (feat. Kid Cudi).mp3
David Guetta feat. Sam Martin - Dangerous (feat. Sam Martin).mp3
David Guetta feat. Sia - Titanium.mp3
David Guetta, Chris Willis - Love Is Gone.mp3
David Usher - Black Black Heart.mp3
Dead Or Alive - You Spin Me Round (Like a Record).mp3
Initial D - Deja Vu.mp3
Depeche Mode - Enjoy The Silence.mp3
Dido - Thank You.mp3
DJ Leonid Rudenko feat. Nicco - Destination.mp3
DMX - Act a fool.mp3
DMX - Party Up (Up In Here).mp3
DMX - Ruff Ryders Anthem.mp3
DMX - Slippin.mp3
DMX - Trina Moe.mp3
DMX feat. Sisqo - What these bitches want from a nigga .mp3
DNCE - Cake By The Ocean.mp3
DNCE feat. Nicki Minaj - Kissing Strangers.mp3
Dr. Alban - Коко джамбо.mp3
Dr. Dree & Snoop Dog - Still Dre.mp3
DU HAST.mp3
Dua Lipa - Physical.mp3
Eagles - Hotel California.mp3
Earth Wind and Fire - dancing in September.mp3
East 17 - It's Alright.mp3
Ed Sheeran - Shape of You.mp3
Edward Maya & Vika Jigulina - Stereo Love (Original).mp3
Edward Maya feat. Vika Jigulina - Desert Rain (feat. Vika Jigulina).mp3
Edward Maya feat. Vika Jigulina - This Is My Life.mp3
Eiffel 65 - Blue ( Hannover Radio Edit ).mp3
Ellie Goulding, Diplo, Swae Lee - Close To Me.mp3
Elvis Presley, JXL - A Little Less Conversation.mp3
Eminem - Just Lose It (Encore 2004).mp3
Eminem - Lose Yourself.mp3
Eminem - Mockingbird.mp3
Eminem - My Name Is.mp3
Eminem - Not Afraid.mp3
Eminem - Rap God.mp3
Eminem - The Real Slim Shady.mp3
Eminem - We Made You.mp3
Eminem - Without Me.mp3
Eminem & D12 - My Band.mp3
Eminem feat. Dido - Stan.mp3
Eminem feat. Nate Dogg - 'Till I Collapse.mp3
Eminem feat. Rihanna - Love The Way You Lie.mp3
Eminem, 50 Cent, Cashis & Lloyd Banks - You Don't Know (Eminem Presents_ The Re-.mp3
Enrique Iglesias feat. Ludacris, DJ Frank E - Tonight (I'm Fuckin' You).mp3
E-rotic - help me mr dick.mp3
Europe - The Final Countdown
Eurythmics - Sweet Dreams.mp3
Evanescence - Bring me to life (OST Сорвиголова).mp3
Evanescence - My Immortal.mp3
Fall Out Boy - She's My Winona.mp3
Fall Out Boy - Thnks fr th Mmrs.mp3
Fatboy Slim - Wonderful Night.mp3
Flo Rida - Whistle.mp3
Flo Rida feat. Ke$ha - Right Round (feat. Ke$ha).mp3
Flo Rida feat. Olly Murs - Trouble maker (new 2012) The best song of Florida.mp3
Flo Rida feat. T-Pain - Low (feat. T-Pain).mp3
Foo Fighters - The Pretender.mp3
Fool's Garden - Lemon Tree1.mp3
Foster the People - Pumped Up Kicks (Bridge and Law Remix).mp3
FUN - we are young (original).mp3
Garth Brooks - If Tomorrow Never Comes.mp3
Gary Jules - Mad World.mp3
Genesis - Another Day In Paradise.mp3
gidv.mp3
Glams - Words Don't Come Easy to Me.mp3
Glass Animals - Heat Waves.mp3
Golden Earring - Going to the Run.mp3
Gorillaz - Feel Good Inc.mp3
Gotye feat. Kimbra - Somebody That I Used To Know.mp3
Green Day - 21 Guns [Official Music Video].mp3
Green Day - Basket Case.mp3
Green Day - Boulevard Of Broken Dreams [BB].mp3
Green Day - Holiday.mp3
Green Day - Wake Me Up When September Ends.mp3
Green Day - When I Come Around.mp3
Green Day - When Its Time To Say I Love You.mp3
Green Day [American Idiot] - American Idiot.mp3
Grimes - World Princess part II.mp3
Guns N' Roses - Knockin' On Heaven's Door.mp3
Guns N Roses - Welcome To The Jungle.mp3
Guns'n'Roses - Don't you cry tonight.mp3
Gwen Stefani - 4 In The Morning.mp3
Gwen Stefani - Cool.mp3
Gym Class Heroes - Cupid's Chokehold _ Breakfast in America.mp3
Gym Class Heroes feat. Adam Levine - Stereo Hearts (feat. Adam Levine).mp3
Haddaway - What Is Love.mp3
Harry Styles - Sign of the Times.mp3
HIM - The Funeral Of Hearts.mp3
Hoizer - Take Me to Church.mp3
Hush - Fired up.mp3
Hypnogaja - Nothing Box.mp3
Ian Carey feat Michelle Sheller - Keep on rising.mp3
Imagine Dragons - Believer.mp3
Imagine Dragons - Demons (original).mp3
Imagine Dragons - It's Time.mp3
Imagine Dragons - Natural.mp3
Imagine Dragons - Radioactive.mp3
Imagine Dragons - Thunder.mp3
Imagine Dragons - Whatever It Takes.mp3
Initial D - Running In The 90s.mp3
Inna - 10 Minutes.mp3
Inna - Hot.mp3
Iyaz - Replay.mp3
Jason Mraz - I'm yours.mp3
Jasper Forks - River Flows in You 2012.mp3
Jay-Z feat. Alicia Keys - Empire State of Mind (New York).mp3
jefferson airplane - Somebody to Love.mp3
Jennifer Lopez - Ain't It Funny.mp3
Jennifer Lopez - Love Don't Cost a Thing.mp3
Johnny Cash - Hurt.mp3
Johnny Hates Jazz - Shattered Dreams.mp3
Juice Newton - Queen Of Hearts.mp3
Justin Bieber - Sorry.mp3
Jаmes Blunt - You're beautiful, it's true.mp3
K Koke feat. Maverick Sabre - Turn Back.mp3
Kanye West - Stronger.mp3
Kate Alexa - Another Now.mp3
Katy Perry - E.T.mp3
Katy Perry - Firework.mp3
Katy Perry - Hot N Cold.mp3
Katy Perry - I Kissed A Girl.mp3
Katy Perry - Last Friday Night.mp3
Katy Perry - Roar.mp3
Katy Perry feat. Skip Marley - Chained To The Rhythm.mp3
Kavinsky - Nightcall.mp3
Ke$ha - Die Young.mp3
Kelly Clarkson - Stronger (What Doesn't Kill You).mp3
Kesha - TikTok.mp3
Kesha - We Are Who We Are.mp3
Kiss - I Was Made For Lovin' You (1979).mp3
Kiss - Strutter.mp3
K'NAAN - Wavin' Flag.mp3
La Caution - The a la Menthe.mp3
Lady Gaga - Alejandro.mp3
Lady Gaga - Bad Romance.mp3
Lady Gaga - Just Dance.mp3
Lady Gaga - Paparazzi.mp3
Lady Gaga - Poker Face.mp3
Lady Gaga feat. Beyonce - Telephone.mp3
Lana Del Rey - Dark Paradise (Original).mp3
Las Lokas del Sur - Aserejé.mp3
Led Zeppelin - Stairway To Heaven (HQ).mp3
Lena - Satelite.mp3
Lexter - Freedom To Love (Radio Edit).mp3
Lilly Wood & The Prick, Robin Schulz - Prayer in C.mp3
Linkin Park - Burn It Down(2012) - Без названия.mp3
Linkin Park - Faint.mp3
Linkin Park - In the End.mp3
Linkin Park - Leave Out All The Rest.mp3
Linkin Park - Lost In The Echo.mp3
Linkin Park - New Divide (Official Video).mp3
Linkin Park - Numb (original).mp3
Linkin Park - What I've Done (Official Video).mp3
LMFAO feat. Lauren Bennett, GoonRock - Party Rock Anthem.mp3
Lost Frequencies Feat. Easton Corbin - Are You With Me [Original mix] [SM].mp3
Lucky Twice - Lucky.mp3
Luis Fonsi - Despacito.mp3
Lynyrd Skynyrd - Free Bird.mp3
Macklemore, Ryan Lewis feat. Ray Dalton - Can't Hold Us (feat. Ray Dalton).mp3
Macklemore, Ryan Lewis feat. Wanz - Thrift Shop (feat. Wanz).mp3
Madcon feat. Ameerah - Freaky Like Me ТАНЦЕВАТЬ.mp3
Madonna - Frozen.mp3
Madonna - Give It 2 Me.mp3
Madonna - Hung Up.mp3
Magic! - Rude.mp3
Mark Ronson feat. Bruno Mars - Uptown Funk.mp3
Maroon 5 - Lucky Strike.mp3
Maroon 5 - Makes Me Wonder.mp3
Maroon 5 - Maps.mp3
Maroon 5 - Memories.mp3
Maroon 5 - Misery (Main Version).mp3
Maroon 5 - Never Gonna Leave This Bed.mp3
Maroon 5 - One More Night.mp3
Maroon 5 - She Will Be Loved.mp3
Maroon 5 - Sugar.mp3
Maroon 5 - This Love.mp3
Maroon 5 - Wake Up Call.mp3
Maroon 5 - Won't Go Home Without You.mp3
Maroon 5 feat. Cardi B - Girls Like You.mp3
Maroon 5 feat. Christina Aguilera - Moves Like Jagger.mp3
Maroon 5 feat. Wiz Khalifa - Payphone.mp3
Mattafix - Big City Life.mp3
MC Hammer - U Can't Touch This .mp3
Meja - All 'Bout The Money.mp3
Metallica - Enter Sandman.mp3
Metallica - Nothing Else Matters.mp3
Metallica - The Unforgiven (Video).mp3
Metallica - The Unforgiven II.mp3
Michael Jackson - Billie Jean.mp3
Michael Jackson - Smooth Criminal.mp3
Michel_Tel_-_Ai_Se_Eu_Te_Pego_(musmore.com).mp3
Mika - Relax Take It Easy (Original Mix)1.mp3
Miley Cyrus - Wrecking Ball.mp3
MOBY - Lift Me Up.mp3
Modern Talking - Brother Louie (Пластинка).mp3
Modern Talking - Cheri Cheri Lady.mp3
Modern Talking - Geronimo's Cadillac.mp3
Modern Talking - You're My heart, You're My soul.mp3
Modjo - Mojo - Lady.mp3
Modo - Eins, zwei, polizei.mp3
Mohombi - Bumpy Ride.mp3
Mr. Credo - Чудная долина.mp3
Nadiya - Amies-Ennemies.mp3
Nelly Furtado - All Good Things (Come To An End) (UK Radio Mix).mp3
Nelly Furtado - I'm Like A Bird.mp3
Nelly Furtado - Say It Right.mp3
Ne-Yo - Closer.mp3
Nickelback - How You Remind Me.mp3
Nickelback - If Today Was Your Last Day.mp3
Nickelback - When We Stand Together (2011).mp3
Nik Kershaw - The Riddle (Gigi D' Agostino Edit).mp3
Nirvana - Rape me - Rape Me.mp3
Nirvana - Smells Like Teen Spirit.mp3
No Dobut (Gwen Stefani) - It`s my life .mp3
No Doubt - Dont speak.mp3
Bee gees - Staying alive.mp3
Oasis - Don't Look Back in Anger.mp3
Oasis - Wonderwall.mp3
Oingo Boingo - Little Girls.mp3
Olivia Rodrigo - good 4 u.mp3
OneRepublic - All The Right Moves.mp3
OneRepublic - Apologize Original Version.mp3
OneRepublic - counting stars (original version).mp3
One-T ft. Cool-T - The Magic Key.mp3
Opus - Life Is Life.mp3
OST - Top Of The World.mp3
Outkast - Hey Ya.mp3
Outkast - Ms Jackson.mp3
O-ZONE - Dragonstea Din Tei (Radio Edit).mp3
Pakito - Living in video.mp3
Panic! At The Disco - High Hopes.mp3
Passenger - Let Her Go [Official Video].mp3
PH Electro - Englishman In New York (Radio Edit).mp3
Pharrell Williams - Happy.mp3
Pitbul - Timber (ft. Kesha).mp3
Pitbull feat. Ne-Yo, Afrojack, Nayer - Give Me Everything.mp3
Pitbull Ft. Eila - Slow.mp3
Pixies - Where Is My Mind.mp3
Postmodern Jukebox - Thrift Shop .mp3
Professor Green feat. Emeli Sandé - Read All About It.mp3
Queen - Another One Bites The Dust.mp3
Queen - I Want To Break Free.mp3
R.E.M. - Losing My Religion.mp3
Radiohead - All I Need.mp3
Radiohead - Creep.mp3
Radiohead - Karma Police.mp3
Radiohead - No Surprises1.mp3
Rammstein - America.mp3
Rammstein - Ashe Zu Asche - 4 Herzeleid - 1995.mp3
Rammstein - Mein Land.mp3
RASMUS - In the shadows (re-edit.mp3
Rasmus - Livin' In A World Without You.mp3
Reamon - Tonight.mp3
Reamonn - My Supergirl.mp3
Red Hot Chili Peppers - Californication.mp3
Red Hot Chili Peppers - Can't Stop.mp3
Red Hot Chili Peppers - Dani California1.mp3
Red Hot Chili Peppers - Dark Necessities.mp3
Red Hot Chili Peppers - Desecration Smile.mp3
Red Hot Chili Peppers - Otherside.mp3
Red Hot Chili Peppers - Scar Tissue.mp3
Red Hot Chili Peppers - Snow (Hey Oh).mp3
Red Hot Chili Peppers - Under The Bridge.mp3
RHCP - Road Trippin'.mp3
Rick Astley - Never Gonna Give You Up.mp3
Ricky Martin - Livin' la Vida Loca.mp3
Rihanna - Diamonds.mp3
Rihanna - S&M.mp3
Rihanna feat. JAY-Z - Umbrella.mp3
Rob Thomas - Lonely No More.mp3
Robert Miles - Children (Dream Version2).mp3
Robin Schulz feat. Francesco Yates - Sugar (feat. Francesco Yates).mp3
Rod Stewart - Young Turks.mp3
Roxette - It Must Have Been Love.mp3
Roxette - Listen To Your Heart.mp3
Roxette - Sleeping In My Car.mp3
S3RL - MTC.mp3
SAFRI - DUO.mp3
Sam Smith - I'm Not The Only One.mp3
Sander van Doorn feat. Carol Lee - Love Is Darkness (Radio Edit) 2011 .mp3
Scatman John - (I Want To) Be Someone.mp3
Scatman John - Everybody Jam.mp3
Scatman John - Scatman (Ski-Ba-Bop-Ba-Dop-Bop).mp3
Scatman John - Scatman's World.mp3
Scooter - Fire.mp3
Scooter - How Much Is The Fish.mp3
Scooter - Scooter - Shake That.mp3
Scorpions - Still Loving You.mp3
Scorpions - White Dove.mp3
Scorpions - Wind Of Change.mp3
Selena Gomez - Come & Get It.mp3
Selena Gomez & The Scene - Love You Like A Love Song.mp3
Semisonic - Closing Time.mp3
September - It Doesn't Matter.mp3
September - Satelite.mp3
September - You'll Never See Me Again.mp3
Shakira - Objection (Tango).mp3
Shakira - She Wolf.mp3
Shakira - Underneath Your Clothes.mp3
Shakira - Whenever, Wherever.mp3
Shakira feat. Wyclef Jean - Hips Don't Lie.mp3
Shawn Mendes, Camila Cabello - Senorita.mp3
Sia - Chandelier.mp3
Sia - Unstoppable.mp3
SKRILLEX - Bangarang feat. Sirah
Smash Mouth - All Star.mp3
Smash Mouth - I'm A Believer.mp3
Smoke On The Water With Lyrics.mp3
Snoop Dogg & Wiz Khalifa Ft Bruno Mars - Young Wild & Free.mp3
Snoop Dogg, David Guetta - Sweat (Snoop Dogg Vs. David Guetta).mp3
Snoop Dogg, Dr. Dre - The Next Episode.mp3
Spice Girls - Wannabe.mp3
Steppenwolf - Born To Be Wild.mp3
Stevie Wonder - I just call to say I love you .mp3
Sting - Englishman in New York.mp3
Sting - Shape of my heart.mp3
Story Of The Year - The Antidote.mp3
Stromae - Alors on dance.mp3
Sum 41 - Fat Lip.mp3
Sum 41 - In Too Deep.mp3
Sum 41 - Some Say.mp3
Sum 41 - The Hell Song.mp3
Sum&41 - Still waiting.mp3
Sunrise Avenue - Fairytale Gone Bad.mp3
Sunrise Avenue - Welkom to my life.mp3
Supermode - Tell Me Why.mp3
Survivor - Eye of the Tiger.mp3
Survivor - You are the best.mp3
Sylver - Forgiven.mp3
System Of A Down - Aerials1.mp3
System Of A Down - Atwa.mp3
System Of A Down - B.Y.O.B. (2005).mp3
System Of A Down - Chop Suey!.mp3
System Of A Down - Empty Walls.mp3
System Of A Down - Hypnotize.mp3
System Of A Down - Lonely Day.mp3
System Of A Down - Lost In Hollywood.mp3
System Of A Down - Psycho.mp3
System Of A Down - Question!.mp3
System Of A Down - Radio Video.mp3
System Of A Down - Roulette.mp3
System Of A Down - Sky Is Over.mp3
System Of A Down - Toxity.mp3
Taio Cruz feat. Flo Rida - Hangover.mp3
Take That - Love Love [OST Люди-Икс Первый класс].mp3
Taylor Swift - Blank Space.mp3
Taylor Swift - I Knew You Were Trouble.mp3
Taylor Swift - Shake It Off.mp3
The Baseballs - Umbrella.mp3
The Black Eyed Peas - Don't Phunk With My Heart.mp3
The Black Eyed Peas - I Gotta Feeling.mp3
The Black Eyed Peas - Let's Get It Started
The Black Eyed Peas - My Humps\
The Black Eyed Peas - Pump It.mp3
The Black Eyed Peas - Shut Up.mp3
The Bobby Fuller Four - I Fought the Law [Battlefield Vietnam - OST #5 (Кванг Тр.mp3
The Caesars - Jerk It out.mp3
The Connells - 74'-75'.mp3
The Cranberries - Zombie.mp3
The Desert Rose Band - One Step Forward.mp3
The Guess Who - Shakin' All Over.mp3
The Killers - Mr. Brightside.mp3
The Killers - Somebody Told Me.mp3
The Mamas  The Papas - California Dreamin'.mp3
The Offspring - One Fine Day.mp3
The Offspring - The Kids Aren't Alright!.mp3
The Offspring - Trust In You.mp3
The Offspring - Want You Bad.mp3
the offspring - Why Don't You Get A Job.mp3
The Offspring - You're Gonna Go Far, Kid.mp3
the offstpring - white guy2.mp3
The Police - Every Breath You Take.mp3
THE PRODIGYPAIN - PAIN-Shut Your Mouth.mp3
The Pussycat Dolls - When I Grow Up.mp3
The Rembrandts - I'll Be There For You.mp3
The Rolling Stones - (I Can't Get No) Satisfaction (Official Lyric Video).mp3
The Rolling Stones - Paint It, Black (Official Lyric Video).mp3
The Verve - Bitter Sweet Symphony.mp3
The Weekend - Blinding lights.mp3
The Weeknd - Can't Feel My Face.mp3
The Weeknd - In Your Eyes.mp3
The Weeknd - Save Your Tears.mp3
The White Stripes - Seven Nation Army.mp3
The Who - Behind blue eyes (1971).mp3
La Caution - Thé à la Menthe - The Laser Dance Song.mp3
Third Eye Blind - Jumper (OST Yes Man).mp3
Three Days Grace - Chalk Outline.mp3
Three Days Grace - I Hate Everything About You.mp3
Tim McMorris - Life Is Beautiful [muzmo.ru].mp3
Timbaland ft. Katty Perry - If We Ever Meet Again.mp3
Tinie Tempah feat. Eric Turner - Written In The Stars.mp3
Tom Petty - runnin' down a dream.mp3
Tonight Radio Edit Jay Sean
Tony Igy - Astronomia.mp3
Tony Igy - Pentagrama (original).mp3
Törsh - Thai Take Away.mp3
Toto - Africa.mp3
Toto - Hold the Line.mp3
Train - 50 Ways To Say Goodbye.mp3
Train - Drive By.mp3
Train - Hey, Soul Sister.mp3
trauma.mp3
Turbo Knight - Rasengan (Original Mix 2018).mp3
twenty one pilots - Heathens.mp3
Twenty One Pilots - Stressed Out.mp3
U2 - With or without you .mp3
Usher feat. Lil Jon, Ludacris - Yeah.mp3
Vance Joy - Riptide.mp3
Velvet - Electric Avenue.mp3
Vengaboys - Boom Boom Boom Boom (mp3store.cc).mp3
Vengaboys - We Like To Party.mp3
Wham! - Careless Whisper (Дэдпул [2016]  Deadpool)[vk.comamazingmoviesmusic].mp3
Wiz Khalifa feat. Charlie Puth - See You Again (feat. Charlie Puth).mp3
Xzibit - X (original version).mp3
Yellowcard - Breathing.mp3
Yves Larock - Rise Up (Original Radio).mp3
АЗА#ZLO - Я хочу.mp3
Альберт Матосян - Адлер-Сочи.mp3
Ария - Потерянный рай.mp3
Ария-Беспечный Ангел - Беспечный ангел.mp3
Балаган Лимитед - Крылышки.mp3
Бутырка - Запахло весной.mp3
Валентин Стрыкало - Гей.mp3
валентин стрыкало - наше лето.mp3
Валентин Стрыкало - Преждевременное семяизвержение.mp3
Валентин Стрыкало - Ты не такая.mp3
Валентин Стрыкало - Я бью женщин и детей.mp3
Доминик Джокер - Если ты со мной.mp3
Звери - Брюнетки и блондинки.mp3
Кабанчик - Без названия.mp3
Кино - Кончится лето.mp3
Кипелов - 4. Я Свободен (2013).mp3
Король и Шут - Лесник.mp3
Король и Шут - Разбежавшись прыгну со скалы.mp3
Ленинград - Я свободен! .mp3
МАЛЬЧИШКИ - ЭТОТ БИТ (премьера клипа за 5 минут) (1).mp3
Михаил Круг - Владимирский централ.mp3
Михаил Круг - Магадан.mp3
Мортал Комбат - Саунтрек.mp3
Нейромонах Феофан - Притоптать.mp3
нексюша - Любви все возрасты покорны.mp3
Ногу свело - Наши юные смешные голоса.mp3
Сан бой - Гром хит мурашки по телу.mp3
Свинцовый Туман - Я знаю придет тот день.mp3
Сектор Газа - Песенка.mp3
Фактор 2 - Марихуана 2000.mp3
Шуфутинский Михаил - Наколочка.mp3
Я волна хрен пойми кто поёт.mp3
Kate Alexa - No Ordinary Girl.mp3
Grimes - Flesh without Blood.mp3
50 Cent Feat. Justin Timberlake & Timbaland - Ayo Technology (Prod by Timbaland)
J Cut & Kolt Siewerts - The Flute Tune (Soulpride Extended Remix)
Justin Timberlake - What Goes Around.Comes Around.mp3
Timbaland feat. Justin Timberlake, Nelly Furtado - Give It To Me.mp3
Madonna feat. Justin Timberlake, Timbaland - 4 Minutes (feat. Justin Timberlake .mp3
Enrique Iglesias feat. Ciara - Takin' Back My Love.mp3
Enrique Iglesias - Tired Of Being Sorry.mp3
Enrique Iglesias feat. Pitbull - I Like It.mp3
Enrique Iglesias feat. Wisin - DUELE EL CORAZON.mp3
S3RL - Pika Girl.mp3
Pendulum - Witchcraft.mp3
Pendulum - Watercolour.mp3
Shakira feat. Rihanna - Can't Remember to Forget You.mp3
Sean Paul - Give It Up to Me.mp3
Mr.Kitty - After Dark.mp3
Madcon feat. Ray Dalton - Don't Worry (with Ray Dalton).mp3
Robin Thicke feat. T.I, Pharrell - Blurred Lines.mp3
Cherish feat. Yung Joc - Killa.mp3
Taio Cruz feat. Ludacris - Break Your Heart.mp3
Placebo - Every You, Every Me.mp3
Placebo - Pure Morning.mp3
Aaron Smith - Dancin.mp3
Juanes - La Camisa Negra.mp3
Milky Chance - Stolen Dance.mp3
Miley Cyrus - Who Owns My Heart.mp3
Miley Cyrus - We Can't Stop.mp3
Willy William - Ego.mp3
Alex Clare - Too Close.mp3
Rag'n'Bone Man - Human.mp3
Kwabs - Walk.mp3
Disturbed - Decadence.mp3
Nelly Furtado - Manos Al Aire (Juan Magan Remix) (2010).mp3
Nelly Furtado - Turn Off The Light.mp3
Akcent - Stay with Me.mp3
Akcent - Jokero.mp3
Ace of Base - All That She Wants
Dr. Alban - It's My Life
Lil Nas X, Jack Harlow - INDUSTRY BABY.mp3
BRAINSTORM - MAYBE.mp3
Avril Lavigne - Sk8er Boi.mp3
Tityo - Come Along With Me.mp3
Burak Yeter Ft. Danelle Sandoval - Tuesday.mp3
P!NK - U + Ur Hand.mp3
P!NK - Stupid Girls.mp3
P!NK - Blow Me (One Last Kiss).mp3
P!NK - Who Knew.mp3
P!NK - Try.mp3
P!NK - Fkin' Perfect.mp3
P!NK - Whataya Want from Me.mp3
Alizée - Moi. Lolita.mp3
Lana Del Rey - Summertime Sadness.mp3
Lana Del Rey - Young And Beautiful.mp3
Daniel Powter - Bad Day
Lipps Inc. - Funky Town.mp3
Ellie Goulding - Burn.mp3
Ellie Goulding - Love Me Like You Do.mp3
Rita Ora, DJ Fresh, DJ Fresh feat. Rita Ora - Hot Right Now.mp3
Aura Dione feat. Rock Mafia - Friends.mp3
Gym Class Heroes - I have a new girlfriend.mp3
Timo Maas feat. Brian Molko - It's a first day of the rest of my life.mp3
Desireles - Voyage, Voyage.mp3
Madonna - Sorry.mp3
Stromae - Tous Les Memes.mp3
Evanescence - Going Under.mp3
Timbaland, D.O.E. feat. Keri Hilson - The Way I Are.mp3
Pitbull feat. Christina Aguilera - Feel This Moment.mp3
Aura Dione - Geronimo.mp3
Jay Sean - Ride It.mp3
Christina Aguilera - Genie In a Bottle.mp3
Christina Aguilera - Hurt.mp3
Christina Aguilera - Your Body.mp3
The Weeknd feat. Daft Punk - Starboy.mp3
Paradisio Ft Maria Garcia & Dj Patrick Samoy - Bailando.mp3
t.A.T.u. - Я сошла с ума.mp3
Two Door Cinema Club - What You Know (OST Мастер Гитары 2).mp3
Rick Astley - Together Forever.mp3
Daft Punk - Instant Crush.mp3
MGMT - Kids.mp3
Naughty Boy feat. Sam Smith - La La La.mp3
Kansas - Carry On Wayward Son.mp3
Morandi - Angels (Love Is The Answer).mp3
Morandi - Save Me.mp3
Powerwolf - Army of the Night.mp3
The Offspring - Can't Repeat.mp3
John Newman - Love Me Again.mp3
Lenka - Everything at Once.mp3
Irene Cara - Flashdance. What A Feeling.mp3
Manuel - Gas Gas Gas.mp3
Rammstein - Links 2 3 4.mp3
noisestorm_-_crab_rave_muzrecord.net.mp3
Дора - Если хочешь.mp3
Yakuza 0 - Friday Night.mp3
Alex Gaudino feat. Crystal Waters - Destination Calabria.mp3
Rihanna - Shut Up And Drive.mp3
ABBA - Gimme! Gimme! Gimme! (A Man After Midnight).mp3
Stromae - Papaoutai.mp3
Кино - Закрой за мной дверь, я ухожу.mp3
Village People - YMCA.mp3
Initial D - Don't Stop The Music.mp3
Madcon - Madcon_Beggin_48055195.mp3
Cypis - Gdzie jest biały węgorz (Zejście).mp3
Lil Nas X - Old Town Road.mp3
Piano Fantasia - Song for Denise.mp3
ATB - 9Pm (Till I Come).mp3
The Kiffness - Ievan Polkka ft. Bilal Göregen (Club Remix).mp3
Ace of Base - Happy Nation.mp3
Masterboy - Porque te vas.mp3
Selena - Freed from Desire 2008 (radio edit).mp3
PPK - Resurrection.mp3
Imany - Don't Be So Shy 
Cher - Believe.mp3
Eric Prydz - Call on Me.mp3
Dragonforce - Through The Fire & Flames.mp3
C.C. CATCH - I Can Lose My Heart Tonight.mp3
Laura Branigan - Self Control.mp3
Amy Macdonald - This Is The Life.mp3
Pesni_iz_SERIALOV_Visokosnyy_god-Tihiy_ogonek.mp3
Benassi Bros, Dhany - Hit My Heart - Radio Edit.mp3
Meg & Dia - Monster.mp3
Skillet - Monster.mp3
Rise Against - Savior.mp3
The Prodigy - Voodoo People.mp3
Daft Punk - Giorgio by Moroder (remix without Moroder's voice).mp3
Adam Gontier & Three Days Grace - Time of Dying.mp3
Far East Movement feat. Justin Bieber - Live My Life.mp3
C-BooL - Never Go Away.mp3
Gnarls Barkley - Crazy.mp3
LP - Lost on You.mp3
Geek Music - Portal _ End Credits _ Still Alive.mp3
Geek Music - Portal 2 _ End Credits _ Want You Gone.mp3
Flashdance - She's a maniac (Танец - вспышка).mp3
Bloodhound Gang - Foxtrot Uniform.mp3
Psy - Gangnam Style (강남스타일).mp3
Nina Kraviz - Skyscrapers.mp3
The Beloved - Sweet Harmony.mp3
Miss Jane - Its A Fine Day
A Touch Of Class - Around the World (La La La La La) (Radio Version).mp3
Babylon Zoo - Spaceman.mp3
Muse - Supermassive Black Hole.mp3
Bomfunk MC's - Freestyler.mp3
Doja Cat - Say So.mp3
Ногу Свело - Свежий ветер-ROCK-REMIX.mp3
Любэ - Ветер-ветерок.mp3
Dr Bombay - Calcutta (Taxi, Taxi, Taxi).mp3
Reel 2 Real feat. The Mad Stuntman - I Like To Move It (feat. The Mad Stuntman).mp3
Shocking Blue - Venus.mp3
Никодим - Кто-то отписался
Santana feat. Rob Thomas - Smooth.mp3
Marty Robbins - Big Iron.mp3
Axel F - Crazy Frog.mp3
Studio Yuraki - The 2017 Bad Apple Rock Cover (Sam Luff Ver.).mp3
Imagine Dragons x J.I.D - Enemy.mp3
Benny Benassi pres. The Biz - 02 Satisfaction (Isak Original Extended).mp3
Sabrina - Boys (Summertime Love)
Paul Engemann - Scarface
Fall Out Boy - Centuries.mp3
Arash feat. Helena - Pure Love.mp3
AySel, Arash - Always.mp3
Arash - Joone Man.mp3
Arash feat. Aneela - Chori Chori.mp3
The Chemical Brothers - Galvanize.mp3
Limp Bizkit - Rollin'.mp3
Sam Houghton, Joe Collinson - Into Asgard.mp3
Ray Parker, Jr. - Ghostbusters.mp3
INTELLIGENCY - AUGUST (ENGLISH VERSION).mp3
Lykke Li - I Follow Rivers.mp3
Fratii din Carbuna - Of Of Ce Sa Fac.mp3
Lazy Town - We Are Number One.mp3
Alex C. feat. Yass - Tienes el Culo Mas Bello del Mundo.mp3
E-Type - Russian Lullaby.mp3
Bellini - Samba De Janeiro (Club Mix 1997) .mp3
The Cardigans - My Favourite Game.mp3
Nena - 99 Luftballons.mp3
Ice Cube - It Was A Good Day.mp3
Невiдомий - Sonia y Selena - Con una mano en mi cintura.mp3
Мурат Тхагалегов - Калым.mp3
2Pac feat. Talent - Changes.mp3
Witch Doctor - cartoons ooh eeh uuh aah aah ting tang walla walla bing bang.mp3
REDNEX - Cotton Eye Joe.mp3
Tokio Hotel - Monsoon.mp3
Sash! - Ecuador.mp3
Armin van Buuren feat. Sharon den Adel - In And Out Of Love 
Mylène Farmer - L'amour n'est rien.mp3
Benny Benassi - Every Single Day
Sandra - Around My Heart
Hurts - Wonderful Life.mp3
Moby - Why Does My Heart Feel So Bad.mp3
Deepside Deejays - Never Be Alone.mp3
Inna - Amazing.mp3
Arash feat. Helena - Broken Angel.mp3
Adam Lambert - Whataya Want from Me.mp3
Adam Lambert - Ghost Town.mp3
Adam Lambert - If I Had You.mp3
Adam Lambert - Never Close Our Eyes.mp3
Mondotek - Alive.mp3
KATO feat. Jon - Turn The Lights Off.mp3
Alex Hepburn - Under.mp3
DJ Layla feat. Alissa - Single Lady, Pt. 1.mp3
The Script feat. will.i.am - Hall of Fame.mp3
Playmen feat. Demy - Fallin.mp3
Morandi - Midnight Train.mp3
The Black Eyed Peas - Just Can’t Get Enough.mp3
DEV - In The Dark.mp3
Example - Changed the Way You Kiss Me.mp3
Morandi - Colors.mp3
Morandi - Love Me.mp3
Don Omar feat. Tego Calderón - Bandoleros.mp3
Basic Element - Touch You Right Now.mp3
Lucenzo feat. Don Omar - Danza Kuduro
Avicii, Nicky Romero - I Could Be The One (Avicii Vs. Nicky Romero).mp3
The Wanted - Chasing The Sun.mp3
Bob Sinclar feat. Steve Edwards - World Hold on (Children of the Sky) [Radio Edi.mp3
Bob Sinclar - Love Generation.mp3
Alexandra Stan - Mr. Saxobeat.mp3
Pakito - Moving on Stereo.mp3
Tom Boxer feat. Antonia - Morena.mp3
Timofey ft. Bartosz Brenes vs. Terry B. - Heaven.mp3
The Prodigy - Omen.mp3
Skrillex feat. Sirah - Kyoto (feat. Sirah).mp3
Serge Devant featuring Hadley - Addicted.mp3
Serge Devant ft. Emma Hewitt - Take me with you.mp3
J-Five - Find a Way.mp3
Global Deejays - Hardcore Vibes (Original Mix).mp3
040_Discobitch - C'est Beau La Bourgeoisie (Bodybangers Remix).mp3
Danzel - You Spin Me Round.mp3
Danzel - Pump It Up.mp3
Dan Balan - Justify Sex.mp3
Dan Balan - Freedom.mp3
Skillet - Hero.mp3
Lil Jon & The East Side Boyz - Get Low 
Yolanda Be Cool & DCUP - We No Speak Americano.mp3
Rihanna, Calvin Harris - We Found Love.mp3
Fort Minor feat. Styles Of Beyond - Remember the Name (feat. Styles of Beyond).mp3
Radio Killer - Lonely Heart.mp3
R.I.O. - Shine On.mp3
Pitbull feat. Chris Brown - International Love.mp3
Pitbull - Hotel Room Service.mp3
Pitbull feat. T-Pain - Hey Baby (Drop It to the Floor).mp3
Paul van Dyk feat. Rea Garvey - Let Go.mp3
DMX - Get It On The Floor (Feat. Swizz Beatz).mp3
K.Maro - Let's go.mp3
K.Maro - Femme like U.mp3
Skrillex, Damian Jr Gong Marley - Make It Bun Dem.mp3
Shakira feat. Dizzee Rascal - Loca.mp3
Jakarta - One Desire.mp3
Loreen - Euphoria.mp3
Akon - Lonely.mp3
Far East Movement feat. The Cataracs, DEV - Like A G6.mp3
Far East Movement - Turn Up The Love (feat. Cover Drive).mp3
Nero - Promises.mp3
Marius feat. Giulia - Rain.mp3
Swedish House Mafia feat. John Martin - Don't You Worry Child.mp3
Flo Rida feat. Sia - Wild Ones (feat. Sia).mp3
MFG - Summertime Sadness (Cedric Gervais remix).mp3
Lexter - Freedom To Love.mp3
Laurent Wolf - No Stress (English radio).mp3
Keri Hilson - I Like.mp3
Fly Project - Mandala.mp3
Hurts - Stay.mp3
Guru Josh Project - Infinity 2008.mp3
[muzmo.ru] Global Deejays - The Sound Of San Francisco [muzmo.ru].mp3
Eric Prydz feat. Pink Floyd - Proper Education (Original Mix).mp3
Eric Prydz - Pjanoo.mp3
Freemasons - Heartbreak (Make Me a Dancer).mp3
Pitbull Ft. Marc Anthony - Rain Over Me(Prod. by RedOne).mp3
Cascada - Everytime We Touch.mp3
DJ Chris Parker - Symphony 2011.mp3
Craig David - Insomnia.mp3
Skillet - Awake and Alive.mp3
Ранетки - О Тебе.mp3
Anastacia - Left Outside Alone.mp3
Narcotic Thrust - I Like It.mp3
Basto - Again & Again.mp3
Bruno Mars - Just The Way You Are.mp3
Alan Walker - The Spectre.mp3
PewDiePie - Congratulations (Clean).mp3
Taylor Swift - Bad Blood.mp3
Dynoro, Gigi D'Agostino - In My Mind.mp3
Calvin Harris, Rihanna - This Is What You Came For.mp3
AronChupa - I'm an Albatraoz.mp3
Shawn Mendes - Stitches.mp3
Martin Garrix - Animals.mp3
The Chainsmokers feat. Daya - Don't Let Me Down.mp3
Fifth Harmony feat. Ty Dolla $ign - Work from Home.mp3
Pedro Capó - Calma.mp3
Daddy Yankee feat. Snow - Con Calma.mp3
Charlie Puth feat. Selena Gomez - We Don't Talk Anymore (feat. Selena Gomez).mp3
ZAYN feat. Sia - Dusk Till Dawn.mp3
Tones And I - Dance Monkey.mp3
Major Lazer feat. DJ Snake, MØ - Lean On.mp3
Dua Lipa - New Rules.mp3
J Balvin, Willy William - Mi Gente.mp3
Billie Eilish - bad guy.mp3
Justin Bieber feat. Ludacris - Baby.mp3
Marshmallow - Alone.mp3
Alan Walker - Faded.mp3
Alan Walker - Alone.mp3
Девид Таварэ - Summer love.mp3
David Guetta feat. Kelly Rowland - When Love Takes Over .mp3
Whitney Houston - I Will Always Love You.mp3
Ian Carey - Redlight.mp3
David A. Stewart feat. Candy Dulfer - Lily Was Here.mp3
Kenny G - Havana (1997 год).mp3
Неизвестен - Yann Tiersen - J'y Suis Jamais Alle-Amelie [Remix] CHECK THE DESCRI
Muse - Uprising
Boney M. - Sunny.mp3
Boney M. - Daddy Cool.mp3
Boney M. - Bahama Mama.mp3
Alice DeeJay - Better Off Alone (Radio Edit).mp3
PH Electro - San Francisco
SNAP! - Rhythm Is A Dancer.mp3
La Bouche - Be My Lover.mp3
Toto Cutugno - L'Italiano.mp3
Неизвестен - Al Bano - Felicita.mp3
Gipsy Kings - Bamboléo.mp3
bôa - Duvet.mp3
Bad Boys Blue - I Wanna Hear Your Heartbeat [Sunday Girl].mp3
Tom Jones feat. Mousse T. - Sexbomb.mp3
Kaoma - Lambada.mp3
Geri Halliwell - It's Raining Men.mp3
Fatboy Slim - The Rockafeller Skank (1).mp3
Blondie - Heart Of Glass.mp3
Freddie Mercury - Living on My Own.mp3
Демо - Солнышко.mp3
Charli XCX - Boom Clap.mp3
Bob Marley & The Wailers - Three Little Birds.mp3
Gloria Gaynor - I Will Survive.mp3
Ray Charles - Hit the Road Jack.mp3
Depeche Mode - Personal Jesus.mp3
Агата Кристи - Как на войне [320 kbps]
Агата Кристи - Сказочная тайга.mp3
TSERIES DISS TRACK // bitch lasagna Pewdipie
One Direction - One Way or Another (Teenage Kicks).mp3
Poets of the Fall - Carnival of Rust.mp3
ABBA - Mamma Mia.mp3
Цыган - Ай ДИГИ-ДИГИ-ДИГИ-ДАЙ (zaycev.net).mp3
Louis Armstrong - What A Wonderful World.mp3
Bring Me The Horizon - Can You Feel My Heart.mp3
Неизвестен - Tarkan - Dudu.mp3
Ram Jam - Black Betty.mp3
Daryl Hall & John Oates - Out of Touch.mp3
ARABESQUE (1980) - Midnight Dancer.mp3
Nirvana - Come As You Are.mp3
Mylène Farmer - Sans contrefaçon.mp3
The Cardigans - Lovefool.mp3
Sophie Ellis-Bextor - Catch You.mp3
Кино - Группа крови.mp3
Max Romeo, The Upsetters - Chase The Devil.mp3
Garbage - I Think I'm Paranoid.mp3
SEREBRO - Song #1.mp3
Icona Pop feat. Charli XCX - I Love It (feat. Charli XCX).mp3
George Thorogood & The Destroyers - Bad To The Bone.mp3
Lynyrd Skynyrd - Sweet Home Alabama.mp3
Поющие вместе - Такого, как Путин.mp3
Justice - Civilization.mp3
Nena - Irgendwie, irgendwo, irgendwann.mp3
HIM - Join Me in Death.mp3
Tears For Fears - Shout.mp3
Limp Bizkit - Behind Blue Eyes.mp3
David Guetta feat. Akon - Sexy Bitch (feat. Akon).mp3
Waterflame - Glorious Morning 2.mp3
Waterflame - Glorious Morning.mp3
Lou Bega - Mambo No. 5 (A Little Bit of.).mp3
In-Grid - Tu es foutu.mp3
New Order - Hey Now What You Doing.mp3
Radical Face - Welcome Home, Son (Remastered).mp3
The Living Tombstone, Eurobeat Brony - Discord.mp3
Alex Gaudino feat. Shena - Watch Out.mp3
Mötley Crüe - Kickstart My Heart.mp3
Ария - Пробил час.mp3
Bobby McFerrin - Don't Worry Be Happy.mp3
Akcent - On And On.mp3
Aly and Aj - Potential break up song.mp3
Amel Bent - Ma philosophie.mp3
Andreea Banica & Dony - Samba ( во румыны жгут! ).mp3
Bastian Van Shield - With Dust.mp3
Beats & Styles feat. Papa Dee - Take It Back (feat. Papa Dee).mp3
BeFour - How do you do.mp3
Benny Benassi & The Biz - Stop-Go.mp3
Cheryl Cole - Fight For This Love.mp3
Cheryl Cole - Parachute.mp3
Clara Chocolat - La Danse De Clara.mp3
193_Claudia Pavell Feat. Fatman Scoop - Just A Little Bit.mp3
Akon - Right Now (Na Na Na)
Danny feat. Therese - If Only You.mp3
David Tavare - Hot Summer Night (O La La La) .mp3
Delano and Crockett - Missing (Hi Tack radio mix)
DJ Matt feat Davin Dale - Baby I love you
Eiffel 65 - In a Song Italia
Flipsyde - When It Was Good.mp3
Florizel - Florizel - Les Valses De Vienne.mp3
Garou - Nothing Else Matters.mp3
Hi-tack - Silence
Ian Oliver feat. Shantel - Bucovina
Inna_-_Sun_is_Up
Inna - Love
John The Whistler - Wild Wild Web.mp3
Junior Caldera & Sophie Ellis-Bextor - Cant Fight This Feeling (Album Version).mp3
leonid_rudenko_and_max_fredrikson_-_goodbye_beautiful_eyes
Corona - Rhytm Of The Night.mp3
Calagero - Face A La Mer.mp3
Neoclubber - Don't Believe (Summer Mix).mp3
Neoclubber - I Heal My Soul.mp3
No Tone feat. Inusa Dawuda - Down Down Down (Dubwork mix).mp3.mp3
Oceana - Cry Cry.mp3
Plumb - Hang on (radio mix).mp3
Pussycat_Dolls_-_Hush_Hush(official_remix)
Rihanna - Cry.mp3
Rihanna - Rude Boy.mp3
Rihanna - Russian Roulette.mp3
Sean Paul & Zaho - Hold My Hand.mp3
Sharam featuring Daniel Bedingfield - The One.mp3
Shaun Baker Feat. Maloy - Give (Sebastian Volter Original Version).mp3
Sophie Ellis-Bextor - If I Can't Dance.mp3
Starclub - All The Boys (In Da Club) (DJRoMashko collection).mp3
01. STARCLUB feat. DR. ALBAN - CHIKI CHIKI (Radio Edit).mp3
Sunloverz - Summer Of Love (Ian Carey Remix).mp3
The Pussycat Dolls feat. Timbaland - Wait A Minute.mp3
Selena Gomez & The Scene - A Year Without Rain.m
Ottawan - Hands up (Give Me Your Heart).mp3p3
Smokie - I'll Meet You at Midnight.mp3
Zhi-Vago - Celebrate [The Love].mp3
Armin van Buuren, Sophie Ellis-Bextor - Not Giving Up On Love.mp3
Nelly - Just A Dream.mp3
T.I. - Castle Walls (feat. Christina Aguilera).mp3
Feder feat. Lyse - Goodbye (feat. Lyse).mp3
Kylie Minogue - Can't Get You out of My Head.mp3
StarPro - Mia Martina - Tu Me Manques (Missing You).mp3
Nico & Vinz - Am I Wrong.mp3
Scotty - The Black Pearl (Dave Darell Remix).mp3
TEAM BS - CASE DEPART (Europa Plus).mp3
Anna Naklab feat. Alle Farben, YOUNOTUS - Supergirl (feat. Alle Farben & YOUNOTU.mp3
Felix Jaehn feat. Jasmine Thompson - Ain't Nobody (Loves Me Better).mp3
Kygo, Parson James - Stole the Show.mp3
Lost Frequencies feat. Janieck Devy - Reality.mp3
Dana Russell - Romantic World (Radio Edit).mp3
Adele - Set Fire to the Rain.mp3
Adele - Set Fire to the Rain (Moto Blanco remix).mp3
Mishelle feat. Randi - Only You (Original Radio Edit).mp3
Nayer Feat. Mohombi & Pitbull - Suavemente.mp3
The Parakit feat. Alden Jacob - Save Me (feat. Alden Jacob).mp3
Alok, Zeeba, Bruno Martini - Hear Me Now (feat. Zeeba).mp3
Calvin Harris - My Way.mp3
Dimitri Vegas & Like Mike feat. Ne-Yo - Higher Place (Radio Edit).mp3
Felix Jaehn feat. Polina - Book Of Love.mp3
Capital Cities - Safe And Sound.mp3
The Underdog Project - Summer Jam.mp3
Daniel Powter - Crazy All My Life (Dfm 2013).mp3
Darren Hayes - Insatiable.mp3
De-Grees feat. Joy - 2 Times.mp3
Jessie J feat. B.o.B - Price Tag.mp3
Lana Del Rey - Young And Beautiful (Kevin Blank rmx)
LeAnn Rimes - Can't Fight The Moonlight (Latino Mix).mp3
Muttonheads feat. Eden Martin - Snow White (Alive).mp3
Ola - Jackie Kennedy.mp3
Samantha Jade - Firestarter.mp3
Riton x Nightcrawlers feat. Mufasa Hypeman - Friday (Dopamine Re-Edit) .mp3
Lil Wayne feat Jennifer Lopez - Im Into You.mp3
Dolce Vita - Mambo italiano DJ invive cut.mp3
Junior Caldera feat. Natalia Kills, Far East Movement - Lights Out (Go Crazy).mp3
Rockwell - Somebody's Watching Me (1984 г.).mp3
Deathray - I Wanna Lose Control (Uh Oh).mp3
Billy Talent - Fallen Leaves.mp3
Three Days Grace - Fallen Angel.mp3
Queen - Don't Stop Me Now.mp3
Snoop Dogg, Dr. Dre - Nuthin But A G'Thang.mp3
The Offspring - The Future Is Now.mp3
Ghost - Square Hammer.mp3
Айдар Галимов - Эх, алмасы.mp3
Empire Of The Sun - Alive.mp3
Army Of Lovers - Sexual Revolution.mp3
Empire Of The Sun - We Are The People.mp3
Neon Genesis Evangelion Full Opening Theme Song
The Pussycat Dolls feat. Snoop Dogg - Buttons.mp3
The Pussycat Dolls, Busta Rhymes - Don't Cha.mp3
Kelly Clarkson - Because of You.mp3
Adriano Celentano - Soli
Tim McMorris - It's a Beautiful Day.mp3
Tim McMorris - On Top Of The World.mp3
Morten Harket - Scared Of Heights.mp3
Counting Crows - Accidentally In Love.mp3
Royal Republic - Getting Along.mp3
ERA - Ameno.mp3 Remix
Aerosmith - I Don't Wanna Miss a Thing.mp3
Eminem - Like Toy Soldiers.mp3
DMX - X Gon' Give It To Ya.mp3
Robbie Williams - Supreme.mp3
KANA-BOON - Silhouette.mp3
Nickelback - Gotta Be Somebody.mp3
Oliver Heldens feat. Syd Silvair - Never Look Back (feat. Syd Silvair).mp3
Post Malone, Swae Lee - Sunflower.mp3
Anne-Marie - Ciao Adios.mp3
Sean Paul feat. Dua Lipa - No Lie.mp3
Erika - I Don't Know.mp3
Calvin Harris feat. Ellie Goulding - Outside.mp3
Anberlin - The Feel Good Drag.mp3
Azuro feat. Elly - Je Ne Sais Pas (R.I.O. Remix) (zaycev.net).mp3
Nelly feat. Kelly Rowland - Dilemma.mp3
Yellow Claw feat. Rochelle - Shotgun (feat. Rochelle).mp3
Element Eighty - Broken Promises.mp3
Fonzerelli featuring Ellenyi - Moonlight Party 2011 (feat. Ellenyi) [Extended Ra.mp3
Wham! - Last Christmas.mp3
Gorky Park - Moscow Calling.mp3
Fly Project - Musica.mp3
P!NK - So What.mp3
Sandu Ciorba - Ale.mp3
Whitesnake - Is This Love.mp3
DK - Я Смотрю Аниме.mp3
Unknown - Spooky Scary Skeletons (Remix) (Extended Mix) (Spooktober Theme Song).mp3
Roxette - Joyride.mp3
Silent Theory - Fragile Minds.mp3
Михайлов Стас - Все для тебя.mp3
Неизвестен - Magnolia - It's All Vain (Radio Edit).mp3
Lindsey Stirling - Roundtable Rival.mp3
Fratii din Carbuna - Ce Frumoasa E Carbuna.mp3
5sta Family - Вместе мы.mp3
Aoyagi Ryoko - Believe (Baki the Grappler OST).mp3
S3RL - I'll See You Again (feat. Chi Chi).mp3
DJ Smash - Dj Sm@sh-Moscow Never Sleeps.mp3
Lil Peep, XXXTENTACION - Falling Down.mp3
Asian Kung-Fu Generation (Naruto OST) - Haruka Kanata.mp3
Ikimonogakari - Blue Bird.mp3
003 Стас Михайлов - Без Тебя=.mp3
E-rotic - Max Don't Have Sex With Your Ex.mp3
Yakuza 0 OST - 82 Koi No Disco Queen (恋のディスコクイーン).mp3
blink-182 - What's My Age Again.mp3
Каста - Вокруг шум.mp3
Kate Ryan - Voyage voyage.mp3
Miracle Of Sound - The New Black Gold 2013 (Deus Ex Song).mp3
Alphaville - Big in Japan.mp3
Roy Orbison - Oh, Pretty Woman.mp3
Natalie Imbruglia - Torn.mp3
Сектор Газа - Бомж.mp3
Lily Allen - Smile.mp3
Витас - 7 Элемент.mp3
Танцы Минус - Город (Ремастеринг 2017).mp3
Кино - Последний герой.mp3
Our Stolen Theory - United (L.A.O.S Remix).mp3
Валерий Меладзе - Салют, Вера.mp3
Валерий Меладзе - Се ля ви.mp3
Caravan Palace - Miracle.mp3
DZIDZIO feat. Вова зі Львова - Павук - Павук.mp3
Vaya Con Dios - Nah Neh Nah.mp3
Paul Stanley - Live To Win.mp3
zerodovich - Нурминский - Валим (Gachi Remix).mp3
Cheryl - Call My Name.mp3
Oceana - Endless Summer (Video Version).mp3
Чи-Ли - Лето.mp3
David Guetta - One Love (feat. Estelle).mp3
Yeah Yeah Yeahs - Heads Will Roll (A-Trak Radio Edit) (320).mp3
Blondie - Maria.mp3
Andreas Johnson - Glorious.mp3 
Uniting Nations - You And Me
Jevo - Bad Piggies Theme.mp3
TWICE - The Feels.mp3
Fall Out Boy feat. John Mayer - Beat It.mp3
Dead by April - Losing You (ALT Version).mp3
Vengaboys - 5. We're Going To Ibiza.mp3
Tevvez - Legend Ψ.mp3
Men At Work - Down Under.mp3
Imagine Dragons - Bones.mp3
Pendulum - Propane Nightmares.mp3
Korn feat. Skrillex, Kill The Noise - Narcissistic Cannibal (feat. Skrillex & Ki.mp3
Günther - Ding Dong Song.mp3
Kiesza - Hideaway.mp3
DREAMERS - Die Happy.mp3
Nyusha - Выше.mp3
John Denver - Take Me Home, Country Roads.mp3
DJVI - Back On Track.mp3
DJVI - Can't Let Go.mp3
DJVI - Cycles.mp3
Avicii - Hey Brother.mp3
Pendulum - Crush.mp3
Kungs, Cookin' On 3 Burners - This Girl (Kungs Vs. Cookin' On 3 Burners).mp3
Aimee B - Fallen Angel.mp3
Dire Straits - Sultans Of Swing.mp3
Mr. Probz - Waves (Robin Schulz Remix) (Raadio Uuno).mp3
Лера МАССКВА [http___muz-vk.ru] - Мы с тобой вместе (OST Универ) - http___muz-vk.mp3
Корни - Наперегонки с ветром.mp3
Bambee - Bumble Bee
Ava Max - Sweet but Psycho.mp3
Jaymes Young - Infinity.mp3
Camila Cabello feat. Young Thug - Havana.mp3
Ariana Grande - Into You.mp3
Post Malone - Better Now.mp3
David Guetta - Love Is Gone (Another VERSION not my fav).mp3
Love is gone - SLANDER (1_45)(Justin Dai_Marvin remix).mp3
YAZOO - Don't Go ☆ MANDEE REMIX ☆
The Prodigy - Invaders Must Die (Radio Edit) (new).mp3
ATB - The Summer (Instrumental Club Version)
BEL SUONO & DJ Magic Finger - Te Quiero
P!NK feat. Nate Ruess - Just Give Me a Reason.mp3
Pompeya - 90.mp3
Dj_Snake_AlunaGeorge_-_You_Know_You_Like_It_(musmore.com).mp3
Elvis Presley - Tutti Frutti.mp3

https://cloud.mail.ru/public/AZei/wujutz5Do

* Mekarazium
Uratsakidogi - Black Hop III (Black Hop Beat-Молот) (5:27)
7Б - Молодые ветра (4:25)
7Б - Некрещеная луна (3:55)
Uratsakidogi - Black Hop VIII (Old School Darkness) (4:43)
83key - Λ (2:52)
Ministry - Rio Grande Blood (4:24)
Ministry - Senor Peligro (3:38)
AISHA - The Disaster of Passion (3:56)
AISHA (38) , Epsilon Zero - Love the Subhuman Self (5:10)
AJUKIRA - Heat Haze Shadow, Pt. 1 (3:22)
AJUKIRA - Heat Haze Shadow, Pt. 2 (3:12)
Alice Glass - Stillbirth (2:48)
Allegaeon - 1.618 (4:17)
Allegaeon - A Path Disclosed (4:29)
Allegaeon - Apoptosis (10:18)
Allegaeon - Bastards of the Earth (4:32)
Allegaeon - Behold (God I Am) (7:18)
Allegaeon - Biomech - Vals No. 666 (7:27)
Allegaeon - Biomech II (5:17)
Allegaeon - Cognitive Computations (5:58)
Allegaeon - Dyson Sphere (4:47)
Allegaeon - Formshifter (5:18)
Allegaeon - Interphase // Meiosis (5:08)
Allegaeon - Into Embers (5:19)
Allegaeon - Of Beasts and Worms (6:30)
Allegaeon - Of Mind and Matrix (5:33)
Allegaeon - Only Loss (6:53)
Allegaeon - Proponent for Sentience II - The Algorithm (8:19)
Allegaeon - Proponent for Sentience III - The Extermination [feat. Björn ''Speed'' Strid] (6:59)
Allegaeon - Saturnine (4:41)
Allegaeon - Secrets of the Sequence (6:02)
Allegaeon - Stellar Tidal Disruption (6:06)
Allegaeon - Subdivisions [Rush cover] (5:25)
Allegaeon - Terrathaw and the Quake (6:10)
Allegaeon - The Weeds Will Prosper (3:56)
Allegaeon - Threshold of Preception (6:06)
Allegaeon - To Carry My Grief Through Torpor and Silence (5:19)
AlphaWolves - Bayonets (4:37)
Amaranthe - 1.000.000 Lightyears (3:15)
Amaranthe - Automatic (3:24)
Amaranthe - Drop Dead Cynical (3:17)
Amaranthe - Hunger (3:12)
Amaranthe - The Nexus (3:16)
Andy Hunter - The Wonders of You (4:23)
Arch Enemy - A Fight I Must Win (6:35)
Arch Enemy - Avalanche (4:38)
Arch Enemy - Enemy Within (4:21)
Arch Enemy - Nemesis (4:12)
Arch Enemy - No More Regrets (4:05)
Arch Enemy - Ravenous (4:06)
Arch Enemy - Saints and Sinners (4:41)
Arch Enemy - Savage Messiah (5:18)
Arch Enemy - The Eagle Flies Alone (5:15)
Arch Enemy - The Race (3:15)
Arch Enemy - The World Is Yours (4:53)
Arch Enemy - War Eternal (4:16)
Army Of Lovers - Lit De Parade (3:20)
Assemblage 23 - Anthem (5:53)
Assemblage 23 - Collapse (5:31)
Assemblage 23 - Darkflow (5:35)
Assemblage 23 - How Can You Sleep? (5:33)
Assemblage 23 - Purgatory (5:48)
Assemblage 23 - Sun (4:26)
Assemblage 23 - The Cruelest Year (4:48)
Atlantida project - Sarva mangalam (6:31)
Atlantida project - Атлантида (Маяк) (5:32)
Atlantida project - Бездна (2:54)
Atlantida project - Бхавани дайаки (5:03)
Atlantida project - Внутренний конфликт (3:42)
Atlantida project - Гармоническая гамма (2:37)
Atlantida project - Гвозди (ft. Noize MC) (3:27)
Atlantida project - Гиперпространство (3:40)
Atlantida project - Киты (4:47)
Atlantida project - Колыбельная (2:18)
Atlantida project - Красная королева (3:34)
Atlantida project - Круги (3:05)
Atlantida project - Ледяное дыхание (3:07)
Atlantida project - Мы здесь (4:50)
Atlantida project - Ничего Нового (ft. Noize MC) (4:31)
Atlantida project - Новое измерение (3:43)
Atlantida project - Разум (5:30)
Atlantida project - Рыцари (4:17)
Atlantida project - Северный ледовитый океан (3:49)
Atlantida project - Сигнальные огни (3:05)
Atlantida project - Солнце (5:05)
Atlantida project - Спокойствие (3:37)
Atlantida project - Танки (2:44)
Atlantida project - Тонкая грань (7:15)
Atlantida project - Чистое зло (3:16)
ATLUS Sound Team & ATLUS GAME MUSIC - Battle -alkalic acid rush- (6:36)
ATLUS Sound Team & ATLUS GAME MUSIC - Battle -beast of bloodshed- (3:14)
ATLUS Sound Team & ATLUS GAME MUSIC - Battle -primordial goddess- (6:26)
ATLUS Sound Team & ATLUS GAME MUSIC - Battle -Qadištu- (4:39)
ATLUS Sound Team & ATLUS GAME MUSIC - Battle -speedster- (4:44)
ATLUS Sound Team & ATLUS GAME MUSIC - Battle -the adversary- (4:34)
Avatar - A Secret Door (6:06)
Avatar - Black Waltz (6:00)
Avatar - Bloody Angel (6:04)
Avatar - Colossus (4:01)
Avatar - Deeper Down (3:46)
Avatar - Get In Line (3:13)
Avatar - Hail The Apocalypse (4:13)
Avatar - Paint Me Red (4:33)
Avatar - Silence In The Age Of Apes (4:21)
Avatar - Smells Like A Freak Show (4:55)
Avatar - The Great Pretender (4:03)
Avatar - The King Welcomes You To Avatar Country (5:36)
Avatar - Torn Apart (6:28)
Avatar - Tower (6:04)
Avatar - Tsar Bomba (3:33)
Avatar - Vultures Fly (4:38)
Axxis - Tales of Glory Island (5:38)
Axxis - The Monsters Crawl (4:44)
AZALEA - 卒業ですね (Sewerslvt Remix) (4:27)
Azumi Takahashi Lotus Juice ATLUS Sound Team ATLUS GAME MUSIC - Full Moon Full Life (4:53)
Black Tide - Honest Eyes (3:57)
Blood Stain Child - Dedicated To Violator (3:53)
Blood Stain Child - Electricity (3:39)
Blood Stain Child - Forever Free (3:57)
Blood Stain Child - Innocence (3:32)
Blood Stain Child - Moon Light Wave (2:44)
Blood Stain Child - Stargazer (4:21)
Blue Stahli - Anti You (3:29)
Blue Stahli - Catastrophe (5:04)
Blue Stahli - Corner (4:52)
Blue Stahli - Demon (4:55)
Blue Stahli - Doubt (3:58)
Blue Stahli - Down In Flames (4:07)
Blue Stahli - Metamorphosis (4:37)
Blue Stahli - Nothing Ever Stays (4:02)
Blue Stahli - Obsidian (3:24)
Blue Stahli - One Last Breath (3:27)
Blue Stahli - Prognosis (3:55)
Blue Stahli - Scrape (4:46)
Blue Stahli - Scrape (Acoustic) (2:54)
Blue Stahli - Throw Away (5:57)
Blue Stahli - ULTRAnumb (4:25)
Bonobo - Prelude + Kiara (5:08)
Bring Me the Horizon - 1x1 (feat. Nova Twins) (3:29)
Bring Me the Horizon - Kingslayer (feat. BABYMETAL) (3:40)
Bring Me the Horizon - Parasite Eve (4:51)
Cain's Offering - Stormcrow (6:16)
Cain's Offering - The Best of Times (4:30)
Celldweller - Against the Tide (5:50)
Celldweller - Birthright (5:20)
Celldweller - Blackstar (4:07)
Celldweller - End of an Empire (7:32)
Celldweller - End of an Empire (Instrumental) (7:32)
Celldweller - Eon (6:22)
Celldweller - Fadeaway (4:47)
Celldweller - Frozen (7:00)
Celldweller - Ghosts (Feat. Tom Salta) (5:05)
Celldweller - Good L ck (Yo 're F cked) (3:35)
Celldweller - I Believe You (3:26)
Celldweller - New Elysium (6:52)
Celldweller - One Good Reason (3:52)
Celldweller - Own Little World (3:33)
Celldweller - Shapeshifter (Feat. Styles Of Beyond) (3:37)
Celldweller - So Long Sentiment (6:03)
Celldweller - So Long Sentiment vs Eon (Live) (6:04)
Celldweller - Switchback (5:02)
Celldweller - Symbiont (5:27)
Celldweller - The Best It's Gonna Get (5:20)
Celldweller - The Last Firstborn (7:41)
Celldweller - The Seven Sisters (3:39)
Celldweller - Tragedy (3:47)
Celldweller & Atlas Plug - A Shattered Eyedol (4:59)
Celldweller & Atlas Plug - Enter the Battletoad (4:25)
Celldweller & Atlas Plug - For the Horde! (5:12)
Celldweller & Atlas Plug - Kneel to Your God (5:25)
Celldweller & Atlas Plug - Nocturne in Blood (4:28)
Celldweller & Atlas Plug - The Champion of Sanghelios (5:43)
Celldweller & Atlas Plug - The Dragon Spirit (5:19)
Chaoseum - First Step to Hell (6:42)
Chaoseum - My Wonderland (5:00)
Chaoseum - Smile Again (4:27)
Chaoseum - Unreal (5:09)
Chaoseum - Welcome Home (6:33)
Combichrist - All Pain is Gone (4:57)
Combichrist - Blut Royale (5:33)
Combichrist - Clouds Of War (4:03)
Combichrist - Compliance (5:02)
Combichrist - Declamation (1:54)
Combichrist - Electrohead (6:00)
Combichrist - Empty (4:31)
Combichrist - Enjoy the Abuse (5:14)
Combichrist - Follow the Trail of Blood (5:32)
Combichrist - Get Your Body Beat (4:48)
Combichrist - How Old Is Your Soul? (3:32)
Combichrist - Never Surrender (4:49)
Combichrist - Pull The Pin (3:54)
Combichrist - Sent To Destroy (4:39)
Combichrist - Throat Full of Glass (4:48)
Combichrist - Today I Woke to the Rain of Blood (5:45)
Combichrist - What the Fuck is Wrong With You? (5:00)
Combichrist - Without Emotions (4:40)
Conquering Dystopia - Destroyer Of Dreams (7:36)
Conquering Dystopia - Kufra At Dusk (3:54)
Conquering Dystopia - Tethys (5:16)
Current Value - Dark Rain
Daisuke Ishiwatari - Awe Of She (Dizzy's Theme) (3:08)
Daisuke Ishiwatari - Bloodstained Lineage (Testament's Theme) (3:21)
Daisuke Ishiwatari - Feel A Fear (Eddie's Theme) (3:04)
Daisuke Ishiwatari - Haven't You Got Eyes In Your Head? (Slayer's Theme) (3:09)
Daisuke Ishiwatari - Holy Orders (Be Just Or Be Dead) (Ky's Theme) (3:01)
Daisuke Ishiwatari - Keep Yourself Alive II (Sol's Theme) (3:06)
Daisuke Ishiwatari - Momentary Life (Baiken's Theme) (3:08)
Daisuke Ishiwatari - Simple Life (Bridget's Theme) (3:08)
Daisuke Ishiwatari - The Midnight Carnival (BOSS) (3:08)
Daisuke Ishiwatari - Writhe In Pain (Millia's Theme) (3:02)
Dance With The Dead - Eyes of Madness (4:38)
Dance with the Dead - Not of this Earth (4:16)
Dark Oath - Land of Ours (9:54)
Dark Oath - When Fire Engulfs the Earth (5:26)
Dark Oath - Wrath Unleashed (5:47)
Dark Tranquillity - Identical to None (3:41)
Dark Tranquillity - In Truth Divided (4:40)
Dark Tranquillity - Phantom Days (3:59)
Dark Tranquillity - Transient (4:11)
Djerv - Headstone (3:50)
Djerv - Madman (4:25)
Dope Stars Inc. - Bang Your Head (3:00)
Dope Stars Inc. - Can You Imagine (4:16)
Dope Stars Inc. - C-beams (4:48)
Dope Stars Inc. - Don't wanna know (3:49)
Dope Stars Inc. - Generation Plastic (5:03)
Dope Stars Inc. - It's going to rain for you (2:40)
Dope Stars Inc. - It's Today (3:27)
Dope Stars Inc. - Lies irae (3:35)
Dope Stars Inc. - Make A Star (4:52)
Dope Stars Inc. - Many thanks (3:58)
Dope Stars Inc. - Theta Titanium (6:25)
Dope Stars Inc. - Vyperpunk (4:02)
Edenbridge - Arcana (9:48)
Edenbridge - October Sky (5:11)
Edenbridge - Shine (8:29)
Edenbridge - Solitaire (6:16)
Edenbridge - Starlight Reverie (4:12)
Eisenfunk - Pong (5:31)
Ekstrak - Induction Kit (3:26)
Epica - Chasing the Dragon (7:40)
Epica - The Second Stone (5:00)
Epica - Unchain Utopia (4:45)
Erika de Bonis - I Don't Know (3:01)
Eskimo Callboy - Crystals (3:46)
Fatboy Slim - Fucking in Heaven (3:54)
Fatboy Slim - Gangster Tripping (5:20)
Fatboy Slim - Love Island (5:18)
Fear Factory - A Therapy for Pain (9:45)
Fear Factory - Archetype (4:35)
Fear Factory - Default Judgement (5:23)
Fear Factory - Demanufacture (4:12)
Fear Factory - Self Bias Resistor (5:11)
Fear Factory - Slave Labour (3:53)
Ferry Corsten - The Hot Wind Blowing featuring Ferry Corsten (Platinum Mix-Instrumental) (2:18)
Flying Steps - We Are Electric (3:29)
Frank Klepacki & The Tiberian Sons - Act On Instinct (2:48)
Frank Klepacki & The Tiberian Sons - Brain Freeze (4:17)
Frank Klepacki & The Tiberian Sons - Grinder 1 & 2 Medley (2:53)
Frank Klepacki & The Tiberian Sons - Hell March (3:34)
Frank Klepacki & The Tiberian Sons - Hell March 2 & 3 Medley (4:12)
Frank Klepacki & The Tiberian Sons - Industrial (2:54)
Frank Klepacki & The Tiberian Sons - Mad Rap (3:38)
Frank Klepacki & The Tiberian Sons - Target / Mechanical Man (3:02)
Free Dominguez - A Stranger I Remain (Maniac Agenda Mix) (2:25)
Front Line Assembly - Afterlife (5:57)
Front Line Assembly - Angriff (Mindless Faith Mix) (5:42)
Front Line Assembly - Circuitry (5:55)
Front Line Assembly - Contagion (5:19)
Front Line Assembly - Hostage (6:57)
Front Line Assembly - Humanity (World War Three), Fawnchopper (Hidden Track) (13:39)
Front Line Assembly - I. E. D. (6:34)
Front Line Assembly - Laws of Deception (5:20)
Front Line Assembly - Mechvirus (6:33)
Front Line Assembly - Meteorfall (6:49)
Front Line Assembly - Millennium (Ashes to Ashes Mix) (6:38)
Front Line Assembly - Mindphaser (12' Version) (6:44)
Front Line Assembly - Providence (9:22)
Front Line Assembly - Release (5:20)
Front Line Assembly - Social Enemy (5:23)
Front Line Assembly - Unleashed (5:17)
Gala - Freed From Desire (3:31)
Gojira - Stranded (4:29)
Gorillaz - 19-2000 (3:27)
Graeme Cornies - Dark Skies (Platinum Mix) (2:21)
Graeme Cornies - Dark Skies (Platinum Mix-Low Key Version) (2:17)
Graeme Cornies - I’m My Own Master Now (Platinum Mix) (2:10)
Graeme Cornies - The War Still Rages Within (5:00)
Graeme Norgate - Controlling Transmission (Original Arcade Soundtrack) (3:53)
Grima - Enisey (4:32)
Halford - Hell's Last Survivor (3:24)
Halford - Made In Hell (4:12)
Halford - Resurrection (3:58)
Halford - Silent Screams (7:06)
Hardcore Superstar - Last Call For Alcohol (3:25)
Hardcore Superstar - Moonshine (4:00)
Harm's Way - Breeding Grounds (3:39)
Harm's Way - Call My Name (4:22)
Harm's Way - Isolation (2:34)
Harm's Way - Scrambled (4:03)
Heaven Pierce Her - ORDER (7:00)
Heilung - Alfadhirhaiti (7:16)
Heilung - Elddansurin (8:05)
Heilung - Fylgija Futhorck (12:45)
Heilung - Hamrer Hippyer (14:08)
Heilung - Krigsgaldr (9:48)
Heilung - Tenet (13:05)
Hirata Shihoko (平田志穂子) - Time To Make Hisory (2:31)
Hirata Shihoko (平田志穂子) - Your Affection (2:52)
Hocico - Crown of Knives (6:57)
Hocico - Damaged (5:15)
Hocico - Damaged (Remixed By Hallucinator) (4:53)
Hocico - N.W.O. (Ministry Cover) (5:29)
Hocico - Palabras De Sangre (6:27)
Hocico - Peccata Mundi (4:20)
Hocico - The Fall (4:05)
Hocico - Weapons of Resistance (feat. Aaron Matts) (4:00)
hxvvxn, билборды - Это не любовь (2:13)
Hypocrisy - Apocalypse (5:56)
Hypocrisy - Chemical Whore (5:19)
Hypocrisy - Children Of The Gray (5:17)
Hypocrisy - Dead World (4:09)
Hypocrisy - End Of Disclosure (4:47)
Hypocrisy - Eraser (4:26)
Hypocrisy - Gods Of The Underground (4:48)
Hypocrisy - Slave To The Parasites (4:57)
Hypocrisy - Tales Of Thy Spineless (4:36)
Hypocrisy - The Eye (5:42)
Hypocrisy - The Fourth Dimension (5:52)
Hypocrisy - War Within (4:53)
Igorrr - Camel Dancefloor (3:13)
Ilaria Graziano - Replica (5:23)
Illidiance - Boiling Point (3:43)
Illidiance - New Millenium Crushers (3:52)
Illidiance - Open Your Eyes (3:44)
In Flames - Cynosure (4:05)
In Flames - In The Dark (4:17)
In Flames - Meet Your Maker (3:57)
In Flames - State Of Slow Decay (3:58)
Iron Savior - Battering Ram (4:49)
Iron Savior - H.M. Powered Man (4:17)
Iron Savior - Riding Free (5:15)
Iron Savior - Stand Against the King (5:01)
Iron Savior - Starchaser (4:27)
Iron Savior - Tyranny of Steel (4:27)
Iron Savior - Wings of Deliverance (4:48)
Jane's Addiction - Mountain Song (4:05)
Janne Da Arc - Feel the Wind (4:47)
Jason Miller - Red Sun (Maniac Agenda Mix) (2:13)
Jeff Loomis - Azure Haze (4:59)
Jeff Loomis - Cashmere Shiv (6:17)
Jeff Loomis - Devil Theory (6:16)
Jeff Loomis - Jato Unit (4:41)
Jimmy Gnecco - Collective Consciousness (Maniac Agenda Mix) (2:38)
Jimmy Gnecco - It Has To Be This Way (Platinum Mix) (2:55)
John Bush - Return to Ashes (Platinum Mix-Low Key Version) (2:14)
John Bush - The Hot Wind Blowing featuring Ferry Corsten (Platinum Mix) (2:18)
Judas Priest - A Touch of Evil (5:44)
Judas Priest - Breaking the Law (2:33)
Judas Priest - Night Crawler (5:44)
Judas Priest - Painkiller (6:05)
Julian Winding - A Dish Best Served Cold (6:06)
Kenichi Tsuchiya - Heterodox Hall - Curse (2:55)
Kenichi Tsuchiya - Heterodox Hall - Full Kagutsuchi (3:40)
Kit Walters - A Soul Can’t Be Cut (Platinum Mix) (2:19)
Kit Walters - A Soul Can’t Be Cut (Platinum Mix-Low Key Version) (2:10)
Kit Walters - The Stains of Time (Maniac Agenda Mix) (2:10)
KMFDM - A Drug Against War (3:35)
KMFDM - Anarchy (5:34)
KMFDM - Glory (3:53)
KMFDM - Kunst (5:01)
KMFDM - Leid Und Elend (6:09)
KMFDM - Light (6:11)
KMFDM - Megalomaniac (6:07)
KMFDM - Pussy Riot (4:10)
KMFDM - Sucks (3:31)
KMFDM - Total State Machine (4:24)
KMFDM - Unfit (6:01)
KMFDM - Waste (3:39)
Korn - A Different World (Feat Corey Taylor) (3:20)
Korn - A.D.I.D.A.S. (2:32)
Korn - Alone I Break (4:16)
Korn - Black Is The Soul (4:01)
Korn - Chaos Lives In Everything (Feat. Skrillex) (3:47)
Korn - Coming Undone (3:19)
Korn - Counting (3:37)
Korn - Counting On Me (4:49)
Korn - Did My Time (4:04)
Korn - Falling Away From Me (4:30)
Korn - Freak On A Leash (4:15)
Korn - Got The Life (3:45)
Korn - Here To Stay (4:31)
Korn - Insane (3:50)
Korn - Liar (4:14)
Korn - Make Believe (4:37)
Korn - Narcissistic Cannibal (Feat. Skrillex & Kill The Noise) (3:10)
Korn - No One's There (5:05)
Korn - Oildale (Leave Me Alone) (4:43)
Korn - Rotting In Vain (3:33)
Korn - Somebody Someone (3:47)
Korn - Thoughtless (4:32)
Korn - Wake Up Hate (3:12)
Korn - Way Too Far (Feat. 12th Planet & Flinch) (3:49)
Kypck - 1917 (4:59)
KYPCK - Белорусский снег (4:53)
Kypck - Демон (7:49)
KYPCK - Дети Биркенау (7:25)
KYPCK - Имя на стене (4:53)
KYPCK - Как философия губит самоотверженных, бескорыстных бюрократов (4:29)
KYPCK - Пророк (6:16)
Kypck - Сталинград (5:11)
KYPCK - Трос, грузовик и темный балкон (7:49)
Lamb Of God - 512 (4:44)
Lamb of God - Beating On Death's Door (5:07)
Lamb of God - Blacken The Cursed Sun (5:28)
Lamb of God - Walk With Me In Hell (5:11)
Leaves' Eyes - Maid of Lorraine (5:13)
Leaves' Eyes - Njord (6:14)
Limp Bizkit - Boiler (7:00)
Limp Bizkit - Break Stuff (2:46)
Limp Bizkit - Dad Vibes (2:12)
Limp Bizkit - Eat You Alive (3:57)
Limp Bizkit - Faith (2:28)
Limp Bizkit - Gimme The Mic (3:05)
Limp Bizkit - Gold Cobra (3:53)
Limp Bizkit - Hot Dog (3:50)
Limp Bizkit - Just Like This (3:35)
Limp Bizkit - My Generation (3:41)
Limp Bizkit - My Way (4:32)
Limp Bizkit - Nobody Loves Me (4:27)
Limp Bizkit - Nookie (4:49)
Limp Bizkit - Out Of Style (3:22)
Limp Bizkit - Re-Arranged (5:54)
Limp Bizkit - Rollin' (Air Raid Vehicle) (3:33)
Limp Bizkit - Take A Look Around (5:21)
Limp Bizkit - You Bring Out The Worst In Me (3:12)
Linkin Park - Breaking the Habit (3:16)
Linkin Park - Buy Myself (Marilyn Manson Remix) (B-Side Rarities) (4:27)
Linkin Park - By Myslf (Josh Abraham and Mike Shinoda Reanimation) (3:42)
Linkin Park - Carousel (Hybrid Theory EP) (3:02)
Linkin Park - Cure for the Itch (2:37)
Linkin Park - Don't Stay (3:08)
Linkin Park - From the Inside (2:55)
Linkin Park - High Voltage (B-Side Rarities) (3:44)
Linkin Park - Kyur4 Th Ich (Chairman Hahn Reanimation) (2:32)
Linkin Park - Lying from You (2:55)
Linkin Park - Nobody's Listening (2:59)
Linkin Park - One Step Closer (2:37)
Linkin Park - Papercut (3:04)
Linkin Park - Session (2:24)
Linkin Park - Somewhere I Belong (3:34)
Linkin Park, Aaron Lewis - Krwlng (Mike Shinoda Reanimation) [feat. Aaron Lewis] (5:40)
Linkin Park, Black Thought - X-Ecutioner Style (feat. Black Thought) (1:49)
Linkin Park, Chali 2na - Frgt/10 (Alchemist Reanimation) [feat. Chali 2na] (3:31)
Linkin Park, Jonathan Davis - 1Stp Klosr (The Humble Brothers Reanimation) [feat. Jonathan Davis] (5:46)
Linkin Park, Phoenix Orion - Rnw@y (Backyard Bangers Reanimation) [feat. Phoenix Orion] (3:13)
Linkin Park, Stephen Richards - P5hng Me A*wy (Mike Shinoda Reanimation) [feat. Stephen Richards] (4:37)
Linkin Park, Zion - Plc.4 Mie Hæd (Amp Live Reanimation) [feat. Zion] (4:20)
Luca Turilli - Kings Of The Nordic Twilight (4:52)
Luca Turilli - Legend Of Steel (5:21)
Lyn - Life Will Change (4:21)
Lyn - Wake Up, Get Up, Get Out There (4:37)
Machinae Supremacy - A View From The End of The World (3:53)
Machinae Supremacy - Attack Music (3:33)
Machinae Supremacy - Blind Dog Pride (6:26)
Machinae Supremacy - Conveyer (3:51)
Machinae Supremacy - Dark City (5:56)
Machinae Supremacy - Deus Ex Machinae (4:43)
Machinae Supremacy - Edge and Pearl (4:00)
Machinae Supremacy - Ghost (Beneath The Surface) (5:11)
Machinae Supremacy - Gimme More (3:32)
Machinae Supremacy - I Know The Reaper (4:34)
Machinae Supremacy - Indiscriminate Murder is Counter-Productive (4:06)
Machinae Supremacy - Insidious (5:33)
Machinae Supremacy - Into The Night World (3:21)
Machinae Supremacy - Killer Instinct (3:52)
Machinae Supremacy - Laser Speed Force (4:06)
Machinae Supremacy - Machinae Prime (7:03)
Machinae Supremacy - Need for Steve (4:11)
Machinae Supremacy - Ninja (5:23)
Machinae Supremacy - Nova Prospekt (5:14)
Machinae Supremacy - Oki Kumas Adventure (5:22)
Machinae Supremacy - Overworld (4:21)
Machinae Supremacy - Perfect Dark (3:50)
Machinae Supremacy - Player One (5:39)
Machinae Supremacy - Radio Future (4:40)
Machinae Supremacy - Reanimator (March Of The Undead III) (5:02)
Machinae Supremacy - Renegades (6:15)
Machinae Supremacy - Return to Snake Mountain (5:20)
Machinae Supremacy - Rogue World Asylum (4:10)
Machinae Supremacy - Ronin (5:13)
Machinae Supremacy - Seventeen (3:42)
Machinae Supremacy - Skin (5:24)
Machinae Supremacy - Soundtrack to The Rebellion (6:00)
Machinae Supremacy - Stand (4:47)
Machinae Supremacy - Super Steve (5:37)
Machinae Supremacy - The Bigger They Are The Harder They Fall (4:33)
Machinae Supremacy - The Greatest Show on Earth (3:32)
Machinae Supremacy - Through The Looking Glass (5:08)
Machinae Supremacy - Truth of Tomorrow (4:35)
Machinae Supremacy - Truth Of Tomorrow (Live at Assembly 2011) (5:20)
Machinae Supremacy - Versus (6:01)
Machinae Supremacy - Violator (3:04)
Marilyn Manson - Coma White (5:38)
Marilyn Manson - mOBSCENE (3:25)
Marilyn Manson - Putting Holes In Happiness (4:31)
Marilyn Manson - Rock Is Dead (3:09)
Marilyn Manson - The Dope Show (3:46)
Marilyn Manson - This Is The New Shit (4:19)
Marilyn Manson - Use Your Fist And Not Your Mouth (3:34)
Mastodon - Blood and Thunder (3:48)
Mastodon - Tread Lightly (5:14)
Maxim - Carmen Queasy (4:03)
Mick Gordon - .Execute (7:30)
Mick Gordon - Ballet of death (5:12)
Mick Gordon - Hatchery 09 (3:41)
Mick Gordon - Herald of Gargos (8:55)
Mick Gordon - Hinnamatoom (5:51)
Mick Gordon - I'm Back to Rise! (8:49)
Mick Gordon - Inferno (7:15)
Mick Gordon - Polemos (6:41)
Mick Gordon - Sandstorm (6:01)
Mick Gordon - Shatterhail (4:45)
Mick Gordon - Temperance & Vengeance (8:10)
Mick Gordon - The Instinct (6:53)
Mick Gordon - The Tiger Warrior (5:04)
Mick Gordon - Type-03 (5:22)
Mick Gordon - Village of Whispers (7:16)
Mick Gordon - Warlord (6:26)
Mick Gordon, Ali Edwards - Touch me and I'll break your face (5:48)
Ministry - Burning Inside (5:20)
Ministry - Corrosion (4:56)
Ministry - Dream Song (4:48)
Ministry - Filthpig (6:19)
Ministry - Jesus Built My Hotrod (vocals Gibby Haynes) (4:52)
Ministry - Just One Fix (5:11)
Ministry - Lava (6:29)
Ministry - N.W.O. (5:31)
Ministry - Psalm 69 (5:29)
Ministry - Scarecrow (8:21)
Ministry - So What (8:13)
Ministry - The Fall (4:54)
Ministry - Thieves (5:02)
Naoki Hashimoto - Alone Infection (4:34)
Naoki Hashimoto - Find Your One Way (3:39)
Naoki Hashimoto - Mirror of the World (6:43)
Naoki Hashimoto - Requiem (4:51)
Naoki Hashimoto , AISHA - Necessary Discrepancy (6:19)
Nero - My Eyes (4:49)
Neurotech - Below These Scars (5:54)
Neurotech - Damage is Done (4:15)
Neurotech - Decipher (7:12)
Neurotech - Evasive (7:32)
Neurotech - Let the Healing Begin (2:23)
Neurotech - Maelstrom (4:17)
Neurotech - The Cyber Waltz (4:04)
Neurotech - The Race to Recovery (4:02)
Neurotech - The Tide Is Rising (5:39)
Nevermore - Believe In Nothing (4:22)
Nevermore - Beyond Within (5:11)
Nevermore - Born (5:06)
Nevermore - Dead Heart In A Dead World (5:06)
Nevermore - Dreaming Neon Black (6:26)
Nevermore - Emptiness Unobstructed (4:37)
Nevermore - Enemies Of Reality (5:11)
Nevermore - Engines Of Hate (4:42)
Nevermore - Evolution 169 (5:51)
Nevermore - Final Product (4:22)
Nevermore - I Am The Dog (4:13)
Nevermore - I, Voyager (5:48)
Nevermore - Inside Four Walls (4:39)
Nevermore - Insignificant (4:56)
Nevermore - Love Bites (Judas Priest cover) (5:22)
Nevermore - Moonrise (Through Mirrors Of Death) (4:01)
Nevermore - My Acid Words (5:41)
Nevermore - Never Purify (4:03)
Nevermore - Next In Line (5:33)
Nevermore - No More Will (5:45)
Nevermore - Sentient 6 (6:58)
Nevermore - The Death Of Passion (4:10)
Nevermore - The Heart Collector (5:55)
Nevermore - The Learning (16:01)
Nevermore - The Lotus Eaters (4:25)
Nevermore - The Obsidian Conspiracy (5:18)
Nevermore - The Politics Of Ecstasy (7:56)
Nevermore - The River Dragon Has Come (5:05)
Nevermore - The Seven Tongues Of God (5:59)
Nevermore - The Termination Proclamation (3:08)
Nevermore - The Tiananmen Man (5:24)
Nevermore - This Godless Endeavor (8:59)
Nevermore - This Sacrament (5:09)
Nevermore - Tomorrow Turned Into Yesterday (4:35)
Nevermore - Who Decides (4:15)
Nevermore - Without Morals (4:17)
Nicolas Bougaïeff - Nexus (3:18)
Nightwish - Amaranth (3:51)
Nightwish - Crownless (4:25)
Nightwish - Ghost Love Score (10:01)
Nightwish - I Want My Tears Back (5:07)
Nightwish - Last Ride Of The Day (4:31)
Nightwish - Nemo (4:35)
Nightwish - Scaretale (7:32)
Nightwish - Storytime (5:22)
Nightwish - The Phantom Of The Opera (4:08)
Nightwish - Wish I Had An Angel (4:04)
Nightwish - Wishmaster (4:24)
Orbit Culture - Carvings (4:29)
Orbit Culture - Mast of the World (5:26)
Orbit Culture - North Star of Nija (5:14)
Origa - Date Of Rebirth (4:40)
Origa - Inner Universe (4:54)
Origa - Rise (5:29)
Origa with Heartsdales - Player (5:42)
Pain - Bye/Die (3:02)
Pain - Coming Home (4:40)
Pain - Computer God (3:25)
Pain - Dancing With The Dead (4:13)
Pain - Dark Fields Of Pain (5:00)
Pain - Eleanor Rigby (The Beatles cover) (3:51)
Pain - End Of The Line (4:03)
Pain - Fade Away (4:59)
Pain - Follow Me (4:16)
Pain - Generation X (4:18)
Pain - I'm Going In (3:16)
Pain - Live Fast/Die Young (3:42)
Pain - My Misery (3:55)
Pain - Not Afraid to Die (4:15)
Pain - Nothing (4:07)
Pain - On And On (3:17)
Pain - Play Dead (Bjork cover) (4:03)
Pain - Psalms Of Extinction (4:09)
Pain - Same Old Song (3:58)
Pain - Shut Your Mouth (3:12)
Pain - Suicide Machine (4:16)
Pain - The Great Pretender (4:05)
Pain - The Tables Have Turned (4:22)
Pain - The Third Wave (3:50)
Pain - Walking On Glass (3:51)
Pain - Zombie Slam (3:32)
Panzerfaust - Promethean Fire (10:22)
Pastel Ghost - Embrace (3:24)
Pendulum - 9,000 Miles (6:26)
Pendulum - Colourfast (3:44)
Pendulum - Crush (4:13)
Pendulum - Different (5:51)
Pendulum - Granite (4:41)
Pendulum - Propane Nightmares (5:13)
Pendulum - Salt in the Wounds (6:38)
Pendulum - Self vs. Self (ft. In Flames) (4:45)
Pendulum - Showdown (5:27)
Pendulum - The Other Side (5:15)
Pendulum - The Tempest (7:27)
Pendulum - The Vulture (4:03)
Pendulum - Visions (5:36)
Pendulum - Watercolour (5:03)
Pendulum - Witchcraft (4:12)
Pendulum & Bullet For My Valentine - Halo (2:47)
Pendulum & SCARLXRD - Mercy Killing (3:49)
Plazma - Take My Love (3:40)
Powerman 5000 - Free (3:50)
Powerwolf - Alive Or Undead (4:23)
Powerwolf - Armata Strigoi (3:59)
Powerwolf - Army Of The Night (3:21)
Powerwolf - Conquistadores (4:45)
Powerwolf - Dancing With The Dead (4:05)
Powerwolf - Demons Are A Girl's Best Friend (3:38)
Powerwolf - Fire & Forgive (4:30)
Powerwolf - Fist By Fist [Sacralize Or Strike] (3:30)
Powerwolf - Gods Of War Arise (5:53)
Powerwolf - Gods Of War Arise (5:53)
Powerwolf - Incense & Iron (3:57)
Powerwolf - Lupus Dei (6:08)
Powerwolf - Night Crawler (5:42)
Powerwolf - Nightside Of Siberia (3:52)
Powerwolf - Reverent Of Rats (2:54)
Powerwolf - Sanctus Dominus (3:22)
Powerwolf - Saturday Satan (5:16)
Powerwolf - Seven Deadly Saints (3:29)
Powerwolf - Stossgebet (3:53)
Powerwolf - The Sacrament Of Sin (3:26)
Powerwolf - Tiger Of Sabrod (3:53)
Powerwolf - Touch Of Evil (5:40)
Powerwolf - Touch Of Evil (5:40)
Powerwolf - Vampires Don't Die (3:08)
Powerwolf - Werewolves Of Armenia (3:54)
Powerwolf - When The Moon Shines Red (4:24)
Powerwolf - Wolves Against The World (6:04)
Prodigy - Breathe (5:34)
Prodigy - Diesel Power (4:17)
Prodigy - Firestarter (4:39)
Prodigy - Funky Shit (5:16)
Prodigy - Mindfields (5:39)
Prodigy - Narayan (9:05)
Prodigy - Serial Thrilla (5:11)
Prodigy - Smack My Bitch Up (5:42)
Psyclon Nine - Order Of The Shadow [The Heretic Awakened] (6:10)
Psyclon Nine - Shadows Unveiled (5:07)
Psyclon Nine - Shadows Unveiled (5:07)
Psyclon Nine - Suffer Well (5:23)
Psyclon Nine - Suffer Well (5:23)
Psyclon Nine - Suicide Note Lullaby (4:50)
Psyclon Nine - The Saint And The Valentine (5:39)
Psyclon Nine - Use Once And Destroy (4:03)
Psyclon Nine - We The Fallen (5:24)
Purity Ring - Begin Again (3:37)
Purity Ring - Fineshrine (3:29)
Purity Ring - Flood On The Floor (3:14)
Purity Ring - Obedear (3:29)
Purity Ring - Repetition (3:38)
Purity Ring - Sea Castle (3:27)
Purity Ring - Stillness In Woe (4:00)
Purity Ring - Stranger Than Earth (4:18)
pyrokinesis - До последнего люмена (3:09)
Rabbit Junk - Relentless (Omicron Nu Epsilon) (4:09)
Rage Against The Machine - Ashes In The Fall (4:36)
Rage Against The Machine - Bombtrack (4:05)
Rage Against The Machine - Born Of A Broken Man (4:41)
Rage Against The Machine - Bulls On Parade (3:51)
Rage Against The Machine - Calm Like A Bomb (4:58)
Rage Against The Machine - Calm Like A Bomb (4:58)
Rage Against The Machine - Fistful Of Steel (5:31)
Rage Against The Machine - Freedom (6:07)
Rage Against The Machine - Guerrilla Radio (3:26)
Rage Against The Machine - Killing In The Name (5:14)
Rage Against The Machine - Know Your Enemy (4:55)
Rage Against The Machine - Maggie's Farm (6:54)
Rage Against The Machine - Mic Check (3:33)
Rage Against The Machine - New Millennium Homes (3:45)
Rage Against The Machine - People Of The Sun (2:30)
Rage Against The Machine - Renegades Of Funk (4:35)
Rage Against The Machine - Sleep Now In The Fire (3:25)
Rage Against The Machine - Take The Power Back (5:36)
Rage Against The Machine - Testify (3:30)
Rage Against The Machine - Vietnow (4:39)
Rage Against The Machine - Voice Of The Voiceless (2:31)
Rage Against The Machine - Year Of Tha Boomerang (4:01)
Rammstein - Dalai Lama (5:37)
Rammstein - Engel (4:24)
Rammstein - Feuer Frei! (3:11)
Rammstein - Ich Will (3:38)
Rammstein - Ich Will (3:37)
Rammstein - Links 2-3-4 (3:36)
Rammstein - Mein Herz Brennt (4:39)
Rammstein - Mein Teil (4:32)
Rammstein - Moskau (4:16)
Rammstein - Mutter (4:32)
Rammstein - Mutter (4:29)
Rammstein - Rammstein (4:25)
Rammstein - Rein Raus (3:09)
Rammstein - Reise Reise (4:11)
Rammstein - Sonne (4:32)
Rammstein - Wollt Ihr Das Bett In Flammen Sehen (5:17)
Rave The Reqviem - Aeon (3:28)
Rave The Reqviem - Fvck The Vniverse (4:13)
Rave The Reqviem - Heroin(e) (3:08)
Rave The Reqviem - Ikaros (3:41)
Rave The Reqviem - Is Apollo Still Alive (2:58)
Rave The Reqviem - Schizophrenia In Reverse (4:58)
Rave The Reqviem - The Ascension (4:22)
Rave The Reqviem - The Svlphvry Void (4:22)
Red Hot Chili Peppers - Californication (5:29)
Red Shift - В темноте (Ногу свело! cover) (3:03)
Rhapsody Of Fire - Emerald Sword (4:20)
Rhapsody Of Fire - The March Of The Swordmaster (5:04)
Rob Zombie - Crow Killer Blues (5:00)
Rob Zombie - Demon Speeding (3:29)
Rob Zombie - Meet the Creeper (3:13)
Rob Zombie - The Triumph Of King Freak (A Crypt Of Preservation & Superstition) (4:07)
Robert Stjärnström - Beast Engine (2:53)
Robert Stjärnström - Legions Metal (2:00)
Royksopp - Running To The Sea (3:45)
Ryota Kozuka - Battle - f8 One Who Stands Against God (6:02)
Sabaton - Twilight Of The Thunder God (3:59)
Sanctuary - Arise And Purify (4:13)
Sanctuary - Death Rider / Third War (4:14)
Sanctuary - Exitium (Anthem Of The Living) (4:53)
Sanctuary - Frozen (5:46)
Sanctuary - I Am Low (5:15)
Sanctuary - Let The Serpent Follow Me (4:46)
Sanctuary - Question Existence Fading (4:20)
Sanctuary - The Year The Sun Died (5:33)
SEGA/ゆよゆっぱ(TOKYO LOGIC) - The Purgatory (4:00)
SEGA/ゆよゆっぺ(TOKYO LOGIC)/(吉田 沙織) - Fiercest Warrior ver.0 (2:49)
SEGA/庄司 英徳 - Fatal Conflict (3:51)
SEGA/庄司 英徳 - Archnemesis (3:27)
SEGA/庄司 英徳 - Crash Addiction (3:04)
SEGA/庄司 英徳 - Force Addiction (2:26)
SEGA/庄司 英徳 - Growling Hound (2:05)
SEGA/庄司 英徳 - One-Eyed Assassin (2:27)
SEGA/庄司 英徳 - One-Eyed Dancer (3:37)
SEGA/庄司 英徳 - One-Eyed Slugger (3:41)
SEGA/庄司 英徳 - Parry Addiction (3:51)
SEGA/庄司 英徳 - Receive You 〜Tech Trance Arrange〜 (3:41)
SEGA/庄司 英徳 - Receive You The Subtype (3:51)
SEGA/庄司 英徳 - t u s k (3:59)
SEGA/庄司 英徳 - Two Dragons (4:32)
SEGA/庄司 英徳 - With Vengeance (3:32)
SEGA/庄司 英徳 - Wounded Hound (2:19)
SEGA/庄司 英徳/吉田 真理(TEMPEST STUDIO) - Reign (5:05)
SEGA/稲毛 謙介(TEMPEST STUDIO) - La-Di-Da (3:13)
Septic Flesh - A Desert Throne (4:18)
Septic Flesh - A Dreadful Muse (4:09)
Septic Flesh - Anubis (4:17)
Septic Flesh - Coming Storm (4:50)
Septic Flesh - Hierophant (4:05)
Septic Flesh - Neuromancer (5:01)
Septic Flesh - Pyramid God (5:13)
Septic Flesh - Sangreal (5:16)
Septic Flesh - Self-Eater (4:27)
Septic Flesh - Sunlight/Moonlight (4:08)
Septic Flesh - The Collector (4:03)
Septic Flesh - Virtues Of The Beast (5:17)
Septicflesh - Enemy of Truth (4:55)
Septicflesh - Faceless Queen (5:20)
Septicflesh - Martyr (5:07)
Septicflesh - Portrait of a Headless Man (5:00)
Sewerslvt - blissful overdose (4:11)
Sewerslvt - Cyberia lyr1 (4:54)
Sewerslvt - Cyberia lyr2 (4:05)
Sewerslvt - Cyberia Lyr3 (3:38)
Sewerslvt - Dysphoria (4:36)
Sewerslvt - goodbye (17:00)
Sewerslvt - intheend (4:06)
Sewerslvt - Jvnko Still Loves You (6:59)
Sewerslvt - Rapescape (3:54)
Sewerslvt - U.nder the weight of a thousand demons [crycaswitchshit] (1:58)
Sewerslvt - ultradespair (5:39)
Sewerslvt - whatever (4:37)
Shadow Domain - Digital Divide (4:47)
Shadow Domain - Give up on Joy (3:30)
Shadow Domain - Magnitizdat (5:40)
Shadow Domain - Who Whatched the Watchers (6:52)
Shadow of Intent - Dirge of the Void (3:18)
Shadow of Intent - Elegy I: Adapt (2:28)
Shadow of Intent - Elegy II: Devise (4:25)
Shadow of Intent - Elegy III: Overcome (6:01)
Shadow of Intent - From Ruin... We Rise (4:50)
Shadow of Intent - Gravesinger (3:58)
Shadow of Intent - Malediction (5:41)
Shadow of Intent - Melancholy (5:15)
Shadow of Intent - Of Fury (4:47)
Shadow of Intent - Oudenophobia (4:09)
Shadow of Intent - Saurian King (5:24)
Shadow of Intent - The Heretic Prevails (4:48)
Shadow of Intent - The Tartarus Impalement (7:52)
Shihoko Hirata - Shadow World (4:43)
Shihoko Hirata - Time To Make History (2:31)
Shin Megami Tensei V - Battle ~Dancing Crazy Murder~ (4:30)
Shin Megami Tensei V - Battle ~Demi-Fiend~ (6:33)
Shin Megami Tensei V - Battle ~ferocity~ (3:13)
Shoji Meguro - Beelzebub (2:43)
Shoji Meguro - Beneath the Mask -rain, instrumental version- (4:38)
Shoji Meguro - Freedom and Peace (3:51)
Shoji Meguro - Supreme Ruler of the Dark (1:19)
Shoji Meguro - When Mother Was There (3:59)
Shoji Meguro (目黒将司) - Beneath the Mask (Instrumental Version) (4:42)
Shoji Meguro (目黒将司) - Will Power (2:45)
Shortparis - Amsterdam (4:40)
Shortparis - Говорит Москва (4:29)
Shortparis - Двадцать (3:35)
Shortparis - КоКоКо / Cтруктуры не выходят на улицы (3:49)
Shortparis - Нелюбовь (4:35)
Shortparis - НОВОЕ НОВОЕ (3:30)
Shortparis - Новокузнецк (4:31)
Shortparis - Скука (3:51)
Shortparis - Страшно (4:49)
Shortparis - Стыд (4:28)
Shortparis - Так закалялась сталь (4:07)
Shortparis - Только хуже стало (5:10)
Shortparis - Туту (4:15)
Shortparis - Что-то особое во мне (5:02)
Shortparis - Яблонный сад (4:33)
Skold - Dirty Horizon (4:00)
Skold - Don't Pray for Me (4:02)
Skold - In Another Life (4:48)
Skold - Kill Yourself (3:56)
Skold - Never Is Now (4:28)
Skold - Pharmaceuticals (4:31)
Skold - Ravenous (5:02)
Skold - Small World (4:56)
Skold - Temple of Rage (5:20)
Skold - Unspoken (3:38)
Skold Vs KMFDM - All Or Nothing (5:03)
Skold Vs KMFDM - Antigeist (5:14)
Skold Vs KMFDM - Bloodsport (5:06)
Skold Vs KMFDM - It's Not What (4:14)
Skold Vs KMFDM - Why Me (4:29)
Slipknot - (sic) (3:19)
Slipknot - (sic) (Molt-Injected Mix) (Bonus Track) (3:27)
Slipknot - All Hope Is Gone (4:47)
Slipknot - AOV (5:32)
Slipknot - Before I Forget (4:38)
Slipknot - Custer (4:14)
Slipknot - Dead Memories (4:28)
Slipknot - Diluted (3:23)
Slipknot - Disasterpiece (5:08)
Slipknot - Duality (4:12)
Slipknot - Eeyore (2:49)
Slipknot - Eyeless (3:56)
Slipknot - Gehenna (6:53)
Slipknot - I Am Hated (2:37)
Slipknot - Iowa (15:04)
Slipknot - Killpop (3:45)
Slipknot - Left Behind (4:01)
Slipknot - Liberate (3:06)
Slipknot - My Plague (3:40)
Slipknot - Nero Forte (5:15)
Slipknot - No Life (2:47)
Slipknot - People = Shit (3:35)
Slipknot - Psychosocial (4:43)
Slipknot - Pulse Of The Maggots (4:19)
Slipknot - Purity (Bonus Track) (4:25)
Slipknot - Scissors (8:23)
Slipknot - Solway Firth (5:55)
Slipknot - Spit It Out (2:39)
Slipknot - Sulfur (4:37)
Slipknot - Surfacing (3:38)
Slipknot - The Blister Exists (5:19)
Slipknot - The Devil In I (5:42)
Slipknot - The Heretic Anthem (4:14)
Slipknot - The Nameless (4:28)
Slipknot - The Negative One (5:25)
Slipknot - Unsainted (4:20)
Slipknot - Wait And Bleed (2:27)
SoulRelic - Down On My Path (3:40)
Soulrelic - It's All So Easy (3:27)
Spiritbox - Angel Eyes (3:28)
Spiritbox - Angel Eyes (3:28)
Spiritbox - Aphids (4:36)
Spiritbox - Belcarra (3:55)
Spiritbox - Bleach Bath (5:05)
Spiritbox - Cellar Door (4:44)
Spiritbox - Cellar Door (4:43)
Spiritbox - Circle With Me (3:53)
Spiritbox - Electric Cross (5:23)
Spiritbox - Eternal Blue (3:59)
Spiritbox - Holy Roller (2:53)
Spiritbox - Holy Roller (2:53)
Spiritbox - Hurt You (3:46)
Spiritbox - Hysteria (3:44)
Spiritbox - Jaded (4:22)
Spiritbox - Jaded (4:22)
Spiritbox - Perennial (4:06)
Spiritbox - Rotoscope (3:35)
Spiritbox - Rule Of Nines (3:31)
Spiritbox - Secret Garden (3:39)
Spiritbox - Secret Garden (3:39)
Spiritbox - Sew Me Up (3:31)
Spiritbox - Sun Killer (3:47)
Spiritbox - The Beauty Of Suffering (5:37)
Spiritbox - The Mara Effect, Pt.1 (4:40)
Spiritbox - The Mara Effect, Pt.2 (3:40)
Spiritbox - The Mara Effect, Pt.3 (5:38)
Spiritbox - The Summit (3:57)
Spiritbox - The Void (3:40)
Spiritbox - Trust Fall (5:19)
Spiritbox - Ultraviolet (4:08)
Spiritbox - We Live In A Strange World (2:48)
Spiritbox - Yellowjacket (feat. Sam Carter) (3:18)
Static-X - A Dios Alma Perdida (6:03)
Static-X - Accelerate (2:48)
Static-X - All In Wait (4:01)
Static-X - All These Years (3:56)
Static-X - Anything But This (4:03)
Static-X - Anything But This (4:03)
Static-X - Behemoth (3:00)
Static-X - Black And White (3:50)
Static-X - Bled For Days (3:45)
Static-X - Brainfog (9:57)
Static-X - Bring You Down (3:35)
Static-X - Cannibal (3:13)
Static-X - Dead Souls (4:44)
Static-X - Dead World (2:47)
Static-X - Destroy All (2:18)
Static-X - Fix (2:49)
Static-X - Follow (3:08)
Static-X - Get To The Gone (2:49)
Static-X - Grind 2 Halt (4:55)
Static-X - Hollow (2:43)
Static-X - I'm With Stupid (3:24)
Static-X - Invincible (4:05)
Static-X - Just In Case (4:24)
Static-X - Machine (3:26)
Static-X - My Damnation (4:01)
Static-X - My Destruction (3:29)
Static-X - New Pain (2:57)
Static-X - Night Terrors (3:09)
Static-X - No Submission (2:41)
Static-X - Otsego Placebo (4:20)
Static-X - Otsegolation (3:32)
Static-X - Otsegolectric (2:39)
Static-X - Permanence (4:01)
Static-X - Push It (2:35)
Static-X - Shadow Zone (3:05)
Static-X - So (3:40)
Static-X - So Real (5:41)
Static-X - Something Of My Own (2:52)
Static-X - Start A War (2:44)
Static-X - Structural Defect (3:39)
Static-X - Sweat Of The Bud (3:29)
Static-X - Tera-Fied (5:19)
Static-X - The Only (2:51)
Static-X - The Trance Is The Motion (4:50)
Static-X - This Is Not (2:57)
Static-X - Wisconsin Death Trip (3:09)
SuperSweep - A Grain of Sand 1st (4:12)
SuperSweep - A Grain of Sand 2nd (2:51)
SuperSweep - Dojo 1st (4:27)
SuperSweep - Dojo 2nd (3:18)
SuperSweep - Equator Line 1st (3:01)
SuperSweep - Equator Line 2nd (3:34)
Sweet Tempest - Mine (3:42)
Sybreed - A Radiant Daybreak (5:30)
Sybreed - A.E.O.N. (5:02)
Sybreed - Bioactive (6:24)
Sybreed - Challenger (4:37)
Sybreed - Critical Mass (6:11)
Sybreed - Decoy (5:07)
Sybreed - Destruction And Bliss (9:44)
Sybreed - Doomsday Party (4:19)
Sybreed - Downfall Inc. (5:00)
Sybreed - Ego Bypass Generator (4:55)
Sybreed - Emma-0 (4:27)
Sybreed - Ethernity (9:20)
Sybreed - God Is An Automaton (5:59)
Sybreed - Into The Blackest Light (4:28)
Sybreed - Love Like Blood (4:45)
Sybreed - No Wisdom Brings Solace (4:37)
Sybreed - Nomenklatura (4:45)
Sybreed - Permafrost (5:05)
Sybreed - Plasmaterial (6:25)
Sybreed - Re-Evolution (4:03)
Sybreed - Rusted (5:34)
Sybreed - The Line Of Least Resistance (4:32)
Sybreed - Twelve Megatons Gravity (5:44)
Sylosis - Enshrined (19:16)
Sylosis - Sands of Time (5:07)
System of a Down - Aerials (6:11)
System of a Down - ATWA (2:56)
System of a Down - B.Y.O.B. (4:15)
System of a Down - Cigaro (2:11)
System of a Down - Deer Dance (2:55)
System Of A Down - Dreaming (3:59)
System of a Down - Forest (4:00)
System Of A Down - Fuck The System (2:12)
System Of A Down - Highway Song (3:13)
System Of A Down - Holy Mountains (5:28)
System Of A Down - Hypnotize (3:09)
System Of A Down - I-E-A-I-A-I-O (3:08)
System Of A Down - Innervision (2:33)
System Of A Down - Know (2:56)
System of a Down - Lost in Hollywood (5:20)
System Of A Down - Mind (6:16)
System Of A Down - Mr. Jack (4:09)
System of a Down - Needles (3:13)
System of a Down - Old School Hollywood (2:56)
System Of A Down - Pictures (2:06)
System of a Down - Prison Song (3:21)
System of a Down - Question! (3:20)
System of a Down - Sad Statue (3:25)
System Of A Down - She's Like Heroin (2:44)
System Of A Down - Soil (3:25)
System Of A Down - Soldier Side (3:40)
System Of A Down - Stealing Society (2:58)
System Of A Down - Sugar (2:33)
System Of A Down - Suite-Pee (2:31)
System Of A Down - Vicinity Of Obscenity (2:51)
System of a Down - Violent Pornography (3:31)
Tardigrade Inferno - All Pigs Are the Same (3:23)
Tardigrade Inferno - All Tardigrades Go to Hell (2:58)
Tardigrade Inferno - Arrival Of A Train (3:55)
Tardigrade Inferno - Burn the Circus (3:45)
Tardigrade Inferno - Cholera (4:06)
Tardigrade Inferno - Church Asylum (4:04)
Tardigrade Inferno - Clockwork God (4:26)
Tardigrade Inferno - Clown Therapy (3:48)
Tardigrade Inferno - Dreadful Song (3:07)
Tardigrade Inferno - Evoke (4:17)
Tardigrade Inferno - I'm Coming for Your Soul (4:42)
Tardigrade Inferno - Little Princess (4:44)
Tardigrade Inferno - Marmalade (3:04)
Tardigrade Inferno - Mastermind (3:58)
Tardigrade Inferno - Ringmaster Has to Die (4:32)
Tardigrade Inferno - Splinter in the Eye (3:13)
Tardigrade Inferno - The Worst Of Me (3:25)
Tardigrade Inferno - Wearing White (4:43)
Tardigrade Inferno - Write With Blood (3:24)
Testudo - Pillium (3:15)
The Birthday Massacre - Blue (4:30)
The Birthday Massacre - Control (3:20)
The Birthday Massacre - Counterpane (3:31)
The Birthday Massacre - Diaries (3:32)
The Birthday Massacre - Divide (4:04)
The Birthday Massacre - Falling Down (4:12)
The Birthday Massacre - Goodnight (4:02)
The Birthday Massacre - Happy Birthday (3:39)
The Birthday Massacre - Hex (3:37)
The Birthday Massacre - In The Dark (3:42)
The Birthday Massacre - Kill The Lights (3:55)
The Birthday Massacre - Looking Glass (4:25)
The Birthday Massacre - Midnight (3:43)
The Birthday Massacre - Pale (3:58)
The Birthday Massacre - Pins And Needles (4:19)
The Birthday Massacre - Remember Me (4:07)
The Birthday Massacre - Shallow Grave (3:47)
The Birthday Massacre - Sleepwalking (3:49)
The Birthday Massacre - Superstition (3:51)
The Birthday Massacre - Under Your Spell (4:31)
The Birthday Massacre - Video Kid (4:34)
The Birthday Massacre - Violet (3:37)
The Birthday Massacre - Walking With Strangers (3:55)
The Gloom In the Corner - Deer Hunter [Instrumental] (3:50)
The Gloom in the Corner - Misanthropic (4:04)
The Luna Sequence - Bloom in the Shadows (4:40)
The Luna Sequence - Drifting, Converging (4:46)
The Luna Sequence - Ends With Me (3:36)
The Luna Sequence - From Many Fires (4:31)
The Luna Sequence - Resonance (4:55)
The Luna Sequence - She Guarded the Silence (4:06)
The Luna Sequence - The Opposite Shore (5:01)
The Luna Sequence - There, at the Roots (4:43)
The Luna Sequence - When Answered (4:39)
The Prodigy - Break & Enter (8:24)
The Prodigy - Girls (4:07)
The Prodigy - Hotride (4:36)
The Prodigy - Medusa's Path (6:08)
The Prodigy - No Good (Start The Dance) (6:17)
The Prodigy - Omen (3:36)
The Prodigy - Phoenix (4:38)
The Prodigy - Poison (6:42)
The Prodigy - Run With The Wolves (4:24)
The Prodigy - Spitfire (5:08)
The Prodigy - Take Me To The Hospital (3:40)
The Prodigy - The Narcotic Suite: 3 Kilos (7:25)
The Prodigy - The Narcotic Suite: Claustrophobic Sting (7:11)
The Prodigy - Their Law (Featuring Pop Will Eat Itself) (6:40)
The Prodigy - Thunder (4:09)
The Prodigy - Voodoo People (6:27)
The Prodigy - Worlds On Fire (4:50)
The Prodigy - You'll Be Under My Wheels (3:56)
The Qemists - Anger (4:33)
The Weathermen - Reports Of A Possible Kidnapping (4:40)
TOOL - 7empest (15:43)
TOOL - Descending (13:37)
TOOL - Fear Inoculum (10:20)
TOOL - Invincible (12:44)
TOOL - Jambi (7:28)
TOOL - Parabol (3:04)
TOOL - Parabola (6:03)
TOOL - Right In Two (8:55)
TOOL - Rosetta Stoned (11:11)
TOOL - Schism (6:47)
TOOL - The Grudge (8:36)
TOOL - The Pot (6:21)
TOOL - Vicarious (7:05)
Toshiki Konishi - Prison Labor (5:34)
Toshiki Konishi - Prison Labor (5:34)
Twisted Sister - We're not Gonna Take It (3:40)
Tyson Yen - A Soul Can’t Be Cut (Platinum Mix-DLC Version) (2:19)
Uratsakidogi - Black Hop VI 2020 (Valhallala feat. Lou) (4:12)
Uratsakidogi - Black Hop X (Nordic Flow) (3:47)
Warrel Dane - As Fast As The Others (4:43)
Warrel Dane - Lucretia My Reflection (4:38)
Warrel Dane - Rain (5:41)
Wayne Static - Around The Turn (2:26)
Wayne Static - Assassins Of Youth (3:12)
Wayne Static - Static Killer (5:05)
Within Temptation - In Vain (4:24)
Yumi Kawamura - Memories of You (6:09)
Yumi Kawamura (川村ゆみ) - Memories of You (キミの記憶) (6:01)
Zardonic - Against All Odds (Instrumental Mix) (5:29)
Zardonic - Against All Odds (Original Mix) (5:17)
Zardonic - Pure Power (Instrumental Mix) (4:52)
Zardonic - Pure Power (Original Mix) (4:52)
Zeromancer - Dr. Online (3:18)
Агата Кристи - Опиум для никого (3:56)
Алиса - Трасса Е-95 (3:36)
Ария - Беспечный ангел (3:58)
Ария - Потерянный рай (5:53)
Аукцыон - Дорога (3:17)
Бездна Анального Угнетения - Not ЛГБТ friendly (3:35)
Бездна Анального Угнетения - Адская дрочильня (4:11)
Бездна Анального Угнетения - Бабушка вернулась из ада (7:50)
Бездна Анального Угнетения - Голос овощей (7:03)
Бездна Анального Угнетения - Одноклассница Лена (3:46)
Бездна Анального Угнетения - Поезд-убийца (4:00)
Бездна Анального Угнетения - Ректальные роботы яндекса (4:44)
Бездна Анального Угнетения - Церковь свидетелей Путина (4:43)
Бездна Анального Угнетения - Чёрный толчок смерти (5:54)
Бездна Анального Угнетения - Шишки-телепаты (3:52)
Би-2 - Мой рок-н-ролл (6:16)
билборды - Алые цветы (2:45)
билборды - Бессонница (2:49)
билборды - В ноль (2:18)
билборды - В полной темноте (1:47)
билборды - Вместо последней строчки (2:27)
билборды - Всё в порядке (2:21)
билборды - Всё в порядке (2:21)
билборды - Встретимся в аду (3:21)
билборды - Здесь нет меня (2:48)
билборды - Исчезаю (2:26)
билборды - Кома (2:56)
билборды - Кома (2:56)
билборды - На прощание (2:13)
билборды - Не могу смотреть в твои глаза (2:50)
билборды - Невесомость (2:48)
билборды - Острые лезвия (2:43)
билборды - Острые лезвия (2:43)
билборды - Отпусти (2:30)
билборды - Пепел (2:45)
билборды - Пепел (2:45)
билборды - Рисую кровью (2:35)
билборды - Скучно (2:36)
билборды - Слишком поздно (2:30)
билборды - Слишком поздно (2:30)
билборды - Снег (2:30)
билборды - Стёртые слова (3:03)
билборды - Тень (3:06)
билборды - Только для тебя (2:42)
билборды - Убежать домой (2:44)
билборды - Холодное дыхание (2:34)
билборды - Что скрываю внутри (3:00)
билборды - Что скрываю внутри (3:00)
ДДТ - Ты не один (5:12)
Дельфин - Весна (4:51)
Земфира - ∞ (5:04)
Земфира - ариведерчи (2:46)
Земфира - П.М.М.Л. (3:37)
Земфира - почему (4:44)
Кипелов - Я свободен (7:13)
Король и Шут - Ели мясо мужики (2:14)
Крематорий - Безобразная Эльза (3:03)
Кукрыниксы - Не беда (3:33)
Кукрыниксы - По раскрашенной душе (3:35)
Линда - Агония (3:24)
Линда - Беги (4:32)
Линда - Беги на цыпочках (3:14)
Линда - Взгляд изнутри (4:57)
Линда - Ворона (5:32)
Линда - ДНК Мира (5:41)
Линда - Золотая вода (4:00)
Линда - Мир против нас (3:22)
Линда - Недолюбили (5:05)
Линда - Никогда (4:30)
Линда - Северный ветер (5:09)
Линда - Сидите потише (5:17)
Линда - Так кричали птицы (4:13)
Линда - Хватит! (4:32)
Линда - Цепи и кольца (3:37)
Лолита Быстрова - Выше! (Single Edit) (4:56)
Лолита Быстрова - Гарри Поттер (3:23)
Лолита Быстрова - Друг (3:11)
Лолита Быстрова - Жизнь на потом (4:39)
Лолита Быстрова - Королевские сердца (4:16)
Лолита Быстрова - Не исчезай (3:45)
Лолита Быстрова - Некуда идти (3:45)
Лолита Быстрова - Спокойной ночи (3:05)
Лолита Быстрова - Ты не знаешь меня (F.A.Q.) (3:31)
Машина Времени - Однажды Мир Прогнется под Нас (3:14)
Мумий Тролль - Владивосток 2000 (2:40)
Мумий Тролль - Утекай (2:18)
Найк Борзов - Верхом на звезде (3:34)
Наутилус Помпилиус - Матерь богов (4:21)
Несчастный случай - Генералы песчаных карьеров (4:12)
Ногу Свело! - Наши юные смешные голоса (6:34)
Ногу Свело! - Хару Мамбуру (3:46)
Пилот - Карма (6:32)
Пилот - Нет вестей с небес (4:37)
Пилот - Рок (3:59)
Пилот - Сердце машины (4:48)
Пилот - Сфинксы (6:13)
Пилот - Ч Б (4:28)
Пилот - Шнурок (4:00)
Смысловые Галлюцинации - Вечно молодой (3:15)
ЧАЙФ - Аргентина-Ямайка - 5 0 (3:17)
吉田 沙織 - K.O.G. (3:50)
山内 祐介 - Arms of Immortal (5:28)
岡部啓一 - Hills of Radiant Winds - Another Edit Version (3:52)
岡部啓一 - Snow in Summer - Another Edit Version (4:49)
平田志穂子 - Pursuing My True Self (3:05)
庄司 英徳 - Penumbra (5:22)
目黒将司 - I'll Face Myself (-Battle-) (5:17)
目黒将司 - sky's the limit -special mix- (4:21)
青木 千紘 - Unwavering Belief -Full Spec Edition- (6:33)

* ChatGPT

** Could you recommend 10 song groups like "The Birthday Massacre"?

Certainly, here are 10 bands that you may enjoy if you like The Birthday Massacre:

    Covenant
    Ladytron
    Ashbury Heights
    Clan of Xymox
    Drab Majesty
    Blutengel
    Crüxshadows
    VNV Nation
    She Wants Revenge
    Depeche Mode

All of these bands have a similar sound to The Birthday Massacre, and they incorporate elements of synthpop, darkwave, and industrial music. Enjoy exploring!
