:PROPERTIES:
:ID:       cec0346f-1183-44d2-81fc-f6b02c47fbd6
:END:

* Tools
- [[https://github.com/basings/selfhosted-music-overview][basings/selfhosted-music-overview: A table listing software network services which can be hosted on your own servers]]
- [[https://github.com/benjojo/dubstep-data][benjojo/dubstep-data: Put data inside dubstep drops]]
- [[https://github.com/CircuitCoder/cuedflacfs][CircuitCoder/cuedflacfs: FUSE for exposing CUE/FLAC CD archives as individual FLAC tracks]]
- [[https://github.com/HackerPoet/FractalSoundExplorer][HackerPoet/FractalSoundExplorer: Explore fractals in an audio-visual sandbox]]
- [[https://github.com/ironsmile/euterpe][ironsmile/euterpe: Self-hosted music streaming server 🎶 with RESTful API and Web interface. Think of it as your very own Spotify!]]
- [[https://github.com/koel/koel][koel/koel: A personal music streaming server that works.]]
- [[https://github.com/SheetAble/SheetAble][SheetAble/SheetAble: Self-hosted music sheet organizing software]]
- [[https://github.com/navidrome/navidrome][navidrome/navidrome: Modern Music Server and Streamer compatible with Subsonic/Airsonic]]
- [[https://github.com/epoupon/lms][epoupon/lms: Lightweight Music Server. Access your self-hosted music using a web interface.]]
- [[https://github.com/ampache/ampache][ampache/ampache: A web based audio/video streaming application and file manager allowing you to access your music & videos from anywhere, using almost any internet enabled device.]]
- [[https://github.com/FerryYoungFan/FanselineVisualizer][FerryYoungFan/FanselineVisualizer: Convert audio files to visualized video]]
- [[https://github.com/airsonic-advanced/airsonic-advanced][Airsonic is a free, web-based media streamer, providing ubiquitous access to your music]]
- [[https://github.com/sentriz/gonic][sentriz/gonic: music streaming server / subsonic server API implementation]]
- [[https://github.com/jeffvli/sonixd][jeffvli/sonixd: A full-featured Subsonic/Jellyfin compatible desktop music player]]
- [[https://github.com/tamland/airsonic-refix][tamland/airsonic-refix: Modern UI for Airsonic / Subsonic]]
- [[https://github.com/bytedance/music_source_separation][bytedance/music_source_separation]]
- [[https://github.com/krateng/maloja][krateng/maloja: Self-hosted music scrobble database to create personal listening statistics and charts]]
- [[https://github.com/SeaDve/Mousai][SeaDve/Mousai: Identify songs in seconds]]

* Services
- [[https://www.pepper.ru/deals/yandeksplyus-2-mesyaca-za-1rub-dlya-vsex-182967][Яндекс.Плюс 2 месяца за 1₽ для всех без активной подписки]]

* Streaming
- [[https://github.com/soundscapecloud/soundscape][soundscapecloud/soundscape: Soundscape - a personal music streaming server]]

* Search
- [[https://habr.com/ru/company/audiomania/blog/522728/][«Найди все сам»: как подбирать музыку для работы и отдыха без помощи рекомендательных систем / Блог компании Аудиомания / Хабр]]
- [[https://habr.com/ru/company/audiomania/blog/522616/][«Что угодно кроме алгоритмов»: где искать музыку, если стриминговые платформы уже надоели / Блог компании Аудиомания / Хабр]]

* Libraries

- https://www.metal-archives.com/
- https://librivox.org/
- http://freemusicarchive.org/
- [[https://bandcamp.com/][Bandcamp]]

* Tracks

- Mix - Mia Martina feat. Waka Flocka - Beast (Official Video)
- [[https://www.youtube.com/watch?v=am36QHp-TgQ][Lineage 2 New Best Soundtrack Compilation]]
- [[https://www.youtube.com/channel/UCVXzBnzP5i5W-3snrxu8kfg/videos][EVERGLOW]]
- [[file:/srv/music/MV_YEZI_Cider.mkv][Yezi - 사이다 cider]]
- [[file:/srv/music/GARNiDELiA - Mirai-nziMTeijTZw.mkv]]
- [[file:/srv/music/M_V 1NB(원앤비) - STALKER(스토커) (섹시 Sexy Ver.)-IST2JgPOlUI.mkv]]
- [[file:/srv/music/Kizumonogatari [AMV] Hope Of Morning (Lyrics)-HOAQaPy5Hgs.mkv]]
- [[file:/srv/music/[HOT] 4MINUTE - Canvas, 포미닛 - Canvas Show Music core 20160213-GC33VMCiZ34.mkv]]
- [[file:/srv/music/Best of NoCopyrightSounds _ Gaming Music 2017 _ Best of EDM-zyrBp8sx5A4.mkv]]

* Metal

- Fairy Tail - Doriarte [New 2016 Ost]
- Fairy Tail - Tempester the Immortal [New 2016 Ost]
- Fairy Tail - Carbuncle Raishuu Ost
- Fairy Tail - Ezel's Theme

- [[file:/srv/videos/Angel_Dust_-_Bleed.mkv]]
- [[file:/srv/videos/Mercenary_-_Through_Our_Darkest_Days.mkv]]

- [[file:/srv/videos/Dissection_-_Black_Dragon.mkv]]
- [[file:/srv/videos/GRAVE_DIGGER_-_Highland_Farewell_Official.mkv]]

- [[file:/srv/videos/AVATARIUM_-_Moonhorse_OFFICIAL_LYRIC_VIDEO.mkv]]
- [[file:/srv/videos/Ghost_-_Cirice.webm]]

- [[file:/srv/videos/HAMMERFALL_-_Any_Means_Necessary_OFFICIAL_MUSIC_VIDEO.mkv]]

- [[file:/srv/videos/KORPIKLAANI_-_Vodka_OFFICIAL_VIDEO.mkv]]

- [[file:/srv/videos/Mercyful_Fate_Come_to_the_Sabbath.webm]]

- [[file:/srv/videos/Metallica_-_Fade_to_Black.mkv]]
- DS」Mad Hatter [Public MEP]-_Ug-enFt9CQ.mkv
- [[file:/srv/music/Monogatari AMV • Red Lips-7QO2Fn-4i8E.mkv]]
- [[file:/srv/music/Shimoneta AMV • RIOT-eCmJTxLl3Bg.mkv]]

- Anime Mix- Savior-tFE6G6rNS1E.mkv
- https://www.youtube.com/watch?v=rIEA3Eq8j5Y

- https://www.youtube.com/watch?v=4CTGxKIzD7M

- [[https://www.youtube.com/playlist?list=PL4YsUf1g7HB59vTrl6n7IpySBX0fBvvo9][(54) Royalty Free Metal - YouTube]]

- [[https://www.metal-archives.com/albums/Emperor/In_the_Nightside_Eclipse/93][Emperor - In the Nightside Eclipse - Encyclopaedia Metallum: The Metal Archives]]

- cradle of fith - existense is futile

- Twilight Force

- [[https://www.youtube.com/watch?v=VO5emLlZ9Cg][Lunatic Gods - Starecká - YouTube]]

* YouTube

  - [[https://www.youtube.com/channel/UCJ6td3C9QlPO9O_J5dF4ZzA][Mostercat]]
  - [[https://www.youtube.com/watch?v=-O3cZ3M4hAo][Perturbator]]
  - [[https://www.youtube.com/user/FirstClassTrashView][(93) First Class Trash - YouTube]]

* Monstercat

- Pixl Rat Twist
- /srv/music/[Special Clip] 몬스타엑스 (MONSTAX) - 히어로 (HERO) Rooftop Ver.-FZ9lJ5ctd0s.mkv

* LOL

- Если мент спросит документ
- Френдзона Бойчик

* [[https://docs.google.com/document/d/19vE-9RgYG1k79BU6801eP4zYVj08RDt_JrV4GUnSW40/edit][Мой плейлист STRIM KAEF - Google Docs]]

Если вы хотите предложить новую музыку, то воспользуйтесь наградой за баллы канала на твиче. 

МОЙ МУЗЫКАЛЬНЫЙ ПЛЕЙЛИСТ НА СТРИМЕ:

kerbal x BLANKED x MehDead — Ex Mashup
!nfsmw.mp3  Styles of Beyond - Nine Thou
1942.mp3 Battlefield 1942 soundtrack main theme
3 Doors Down - I'm Here without You Baby.mp3
50 Cent - Disco Inferno
50 Cent - In Da Club.mp3
50 Cent - Just A Lil Bit.mp3
50 Cent - P.I.M.P.mp3
50 Cent feat. Olivia - Candy Shop.mp3
ABBA - Lay All Your Love On Me.mp3
AC?DC (ost Supernatural) - Highway To Hell.mp3
ACDC - Back In Black (OST Iron Man ).mp3
Adele - Rolling in the Deep.mp3
Aerosmith - Dream On.mp3
a-ha - Take on Me.mp3
Akcent - Too Late to Cry.mp3
Akon feat. Eminem - Smack That.mp3
Ak'Sent - Kylie.mp3
Alexander Rybak - Fairytale.mp3
Alice Cooper - Poison.mp3
Alient Ant Farm - Smooth Criminal (OST Американский пирог 2).mp3
Alyans - Na Zare.mp3
America - A horse with no name.mp3
And I say, hey hey hey hey. - I said hey, what's going on.mp3
Animal Джаz - Чувства.mp3
Aqua - Barbie Girl.mp3
Arash - Boro Boro.mp3
Arash feat. Shaggy - Donya.mp3
Ava Max - Kings & Queens.mp3
Ava Max - Salt.mp3
Avicii - Levels (Original Mix).mp3
Avicii - Waiting For Love.mp3
Avicii feat. Aloe Blacc - Wake Me Up.mp3
Avril Lavigne - Complicated.mp3
Avril Lavigne - Girlfriend.mp3
Avril Lavigne - Hot.mp3
B.J. Thomas - Raindrops Keep Falling On My Head (Re-Recorded).mp3
Bag Riders - Shooting Stars.mp3
Basshunter - All I Ever Wanted.mp3
Basshunter - Dota.mp3
Basshunter - I Can Walk on Water.mp3
Basshunter - Now You're Gone.mp3
Battlefield Bad Company 2 Vietnam OST (Box Tops) - The letter.mp3
Battlefield Vietnam - Cat Stevens - Wild World.mp3
bbno$ feat. Rich Brian - edamame.mp3
BENEE feat. Gus Dapperton - Supalonely.mp3
Beyoncé - Single Ladies (Put a Ring on It).mp3
Beyoncé - Sweet Dreams.mp3
Beyoncé, Shakira - Beautiful Liar.mp3
Billie Eilish - everything i wanted.mp3
Billy Talent - Devil In A Midnight Mass.mp3
Billy Talent - Red Flag.mp3
Billy Talent - Worker Bees.mp3
Black Eyed Peas - The Time.mp3
Blake Shelton - Footloose.mp3
Blondie - Call Me.mp3
Bloodhound Gang - American Bitches.mp3
BLOODHOUND GANG - The Bad Touch (Original).mp3
Bloodhound Gang - Uhn Tiss Uhn Tiss Uhn Tiss.mp3
Blue - Curtain Falls.mp3
Blur - Song 2.mp3
Bon Jovi - It's my life w- lyrics.mp3
Bon Jovi - Livin' On A Prayer.mp3
Boney M. - Rasputin.mp3
Boni M - Барбара Стрейзант.mp3
Bonie Tyler - I Need A Hero.mp3
Bosson - Walking.mp3
brainpower.mp3
Breaking Benjamin - Follow.mp3
Breaking Benjamin - So Cold.mp3
Britney Spears - Oops.I Did It Again.mp3
Britney Spears - Till the World Ends.mp3
Britney Spears - Toxic.mp3
Busta Rhymes, Mariah Carey feat. Flipmode Squad - I Know What You Want.mp3
C.C. CATCH - Cause You Are Young.mp3
Евро & Status Quo - - In The Army Now 2005_Архив Радио DFM_ D-Чарт Хит-парад за .mp3
Caramell - Caramelldansen.mp3
Caravan Palace - Lone Digger.mp3
Carly Rae Jepsen - Call Me Maybe.mp3
Carly Rae Jepsen - I Really Like You.mp3
CC Catch - Strangers By Night.mp3
Celline Dion - My heart will go on.mp3
Chamillionaire feat. Krayzie Bone - Ridin'.mp3
Chris Norman & C. C. Catch - Stumblin in.mp3
Chumbawamba - Tumbthumping.mp3
Clean Bandit feat. Sean Paul, Anne-Marie - Rockabye (feat. Anne-Marie & Sean Pau.mp3
Coldplay - A Sky Full Of Stars.mp3
Coldplay - Adventure of a Lifetime.mp3
Coldplay - In My Place.mp3
Coldplay - Paradise (Official Video).mp3
Coldplay - The Scientists.mp3
Coldplay (ft. Beyonce) - Hymn For The Weekend.mp3
Coolio feat. L.V. - Gangsta's Paradise (feat. L.V.).mp3
craig david-  7 days.mp3
Craig David feat. Sting - Rise & Fall.mp3
Crazy Town - Butterfly.mp3
Creedence Clearwater Revival - Fortunate Son.mp3
Cutting Crew - (I Just) Died In Your Arms.mp3
Daft Punk - Harder, Better, Faster, Stronger.mp3
Daft Punk feat. Pharrell Williams, Nile Rodgers - Get Lucky.mp3
Darude - Feel The Beat.mp3
Darude - Sandstorm.mp3
Daryl Hall & John Oates - You Make My Dreams (Come True).mp3
David Guetta - Baby when the light.mp3
David Guetta - In Love With Myself.mp3
David Guetta - Love Dont Let Me Go (Original Edit).mp3
David Guetta - The World Is Mine.mp3
David Guetta feat. Akon, Ne-Yo - Play Hard (feat. Ne-Yo & Akon).mp3
David Guetta feat. Kid Cudi - Memories (feat. Kid Cudi).mp3
David Guetta feat. Sam Martin - Dangerous (feat. Sam Martin).mp3
David Guetta feat. Sia - Titanium.mp3
David Guetta, Chris Willis - Love Is Gone.mp3
David Usher - Black Black Heart.mp3
Dead Or Alive - You Spin Me Round (Like a Record).mp3
Initial D - Deja Vu.mp3
Depeche Mode - Enjoy The Silence.mp3
Dido - Thank You.mp3
DJ Leonid Rudenko feat. Nicco - Destination.mp3
DMX - Act a fool.mp3
DMX - Party Up (Up In Here).mp3
DMX - Ruff Ryders Anthem.mp3
DMX - Slippin.mp3
DMX - Trina Moe.mp3
DMX feat. Sisqo - What these bitches want from a nigga .mp3
DNCE - Cake By The Ocean.mp3
DNCE feat. Nicki Minaj - Kissing Strangers.mp3
Dr. Alban - Коко джамбо.mp3
Dr. Dree & Snoop Dog - Still Dre.mp3
DU HAST.mp3
Dua Lipa - Physical.mp3
Eagles - Hotel California.mp3
Earth Wind and Fire - dancing in September.mp3
East 17 - It's Alright.mp3
Ed Sheeran - Shape of You.mp3
Edward Maya & Vika Jigulina - Stereo Love (Original).mp3
Edward Maya feat. Vika Jigulina - Desert Rain (feat. Vika Jigulina).mp3
Edward Maya feat. Vika Jigulina - This Is My Life.mp3
Eiffel 65 - Blue ( Hannover Radio Edit ).mp3
Ellie Goulding, Diplo, Swae Lee - Close To Me.mp3
Elvis Presley, JXL - A Little Less Conversation.mp3
Eminem - Just Lose It (Encore 2004).mp3
Eminem - Lose Yourself.mp3
Eminem - Mockingbird.mp3
Eminem - My Name Is.mp3
Eminem - Not Afraid.mp3
Eminem - Rap God.mp3
Eminem - The Real Slim Shady.mp3
Eminem - We Made You.mp3
Eminem - Without Me.mp3
Eminem & D12 - My Band.mp3
Eminem feat. Dido - Stan.mp3
Eminem feat. Nate Dogg - 'Till I Collapse.mp3
Eminem feat. Rihanna - Love The Way You Lie.mp3
Eminem, 50 Cent, Cashis & Lloyd Banks - You Don't Know (Eminem Presents_ The Re-.mp3
Enrique Iglesias feat. Ludacris, DJ Frank E - Tonight (I'm Fuckin' You).mp3
E-rotic - help me mr dick.mp3
Europe - The Final Countdown
Eurythmics - Sweet Dreams.mp3
Evanescence - Bring me to life (OST Сорвиголова).mp3
Evanescence - My Immortal.mp3
Fall Out Boy - She's My Winona.mp3
Fall Out Boy - Thnks fr th Mmrs.mp3
Fatboy Slim - Wonderful Night.mp3
Flo Rida - Whistle.mp3
Flo Rida feat. Ke$ha - Right Round (feat. Ke$ha).mp3
Flo Rida feat. Olly Murs - Trouble maker (new 2012) The best song of Florida.mp3
Flo Rida feat. T-Pain - Low (feat. T-Pain).mp3
Foo Fighters - The Pretender.mp3
Fool's Garden - Lemon Tree1.mp3
Foster the People - Pumped Up Kicks (Bridge and Law Remix).mp3
FUN - we are young (original).mp3
Garth Brooks - If Tomorrow Never Comes.mp3
Gary Jules - Mad World.mp3
Genesis - Another Day In Paradise.mp3
gidv.mp3
Glams - Words Don't Come Easy to Me.mp3
Glass Animals - Heat Waves.mp3
Golden Earring - Going to the Run.mp3
Gorillaz - Feel Good Inc.mp3
Gotye feat. Kimbra - Somebody That I Used To Know.mp3
Green Day - 21 Guns [Official Music Video].mp3
Green Day - Basket Case.mp3
Green Day - Boulevard Of Broken Dreams [BB].mp3
Green Day - Holiday.mp3
Green Day - Wake Me Up When September Ends.mp3
Green Day - When I Come Around.mp3
Green Day - When Its Time To Say I Love You.mp3
Green Day [American Idiot] - American Idiot.mp3
Grimes - World Princess part II.mp3
Guns N' Roses - Knockin' On Heaven's Door.mp3
Guns N Roses - Welcome To The Jungle.mp3
Guns'n'Roses - Don't you cry tonight.mp3
Gwen Stefani - 4 In The Morning.mp3
Gwen Stefani - Cool.mp3
Gym Class Heroes - Cupid's Chokehold _ Breakfast in America.mp3
Gym Class Heroes feat. Adam Levine - Stereo Hearts (feat. Adam Levine).mp3
Haddaway - What Is Love.mp3
Harry Styles - Sign of the Times.mp3
HIM - The Funeral Of Hearts.mp3
Hoizer - Take Me to Church.mp3
Hush - Fired up.mp3
Hypnogaja - Nothing Box.mp3
Ian Carey feat Michelle Sheller - Keep on rising.mp3
Imagine Dragons - Believer.mp3
Imagine Dragons - Demons (original).mp3
Imagine Dragons - It's Time.mp3
Imagine Dragons - Natural.mp3
Imagine Dragons - Radioactive.mp3
Imagine Dragons - Thunder.mp3
Imagine Dragons - Whatever It Takes.mp3
Initial D - Running In The 90s.mp3
Inna - 10 Minutes.mp3
Inna - Hot.mp3
Iyaz - Replay.mp3
Jason Mraz - I'm yours.mp3
Jasper Forks - River Flows in You 2012.mp3
Jay-Z feat. Alicia Keys - Empire State of Mind (New York).mp3
jefferson airplane - Somebody to Love.mp3
Jennifer Lopez - Ain't It Funny.mp3
Jennifer Lopez - Love Don't Cost a Thing.mp3
Johnny Cash - Hurt.mp3
Johnny Hates Jazz - Shattered Dreams.mp3
Juice Newton - Queen Of Hearts.mp3
Justin Bieber - Sorry.mp3
Jаmes Blunt - You're beautiful, it's true.mp3
K Koke feat. Maverick Sabre - Turn Back.mp3
Kanye West - Stronger.mp3
Kate Alexa - Another Now.mp3
Katy Perry - E.T.mp3
Katy Perry - Firework.mp3
Katy Perry - Hot N Cold.mp3
Katy Perry - I Kissed A Girl.mp3
Katy Perry - Last Friday Night.mp3
Katy Perry - Roar.mp3
Katy Perry feat. Skip Marley - Chained To The Rhythm.mp3
Kavinsky - Nightcall.mp3
Ke$ha - Die Young.mp3
Kelly Clarkson - Stronger (What Doesn't Kill You).mp3
Kesha - TikTok.mp3
Kesha - We Are Who We Are.mp3
Kiss - I Was Made For Lovin' You (1979).mp3
Kiss - Strutter.mp3
K'NAAN - Wavin' Flag.mp3
La Caution - The a la Menthe.mp3
Lady Gaga - Alejandro.mp3
Lady Gaga - Bad Romance.mp3
Lady Gaga - Just Dance.mp3
Lady Gaga - Paparazzi.mp3
Lady Gaga - Poker Face.mp3
Lady Gaga feat. Beyonce - Telephone.mp3
Lana Del Rey - Dark Paradise (Original).mp3
Las Lokas del Sur - Aserejé.mp3
Led Zeppelin - Stairway To Heaven (HQ).mp3
Lena - Satelite.mp3
Lexter - Freedom To Love (Radio Edit).mp3
Lilly Wood & The Prick, Robin Schulz - Prayer in C.mp3
Linkin Park - Burn It Down(2012) - Без названия.mp3
Linkin Park - Faint.mp3
Linkin Park - In the End.mp3
Linkin Park - Leave Out All The Rest.mp3
Linkin Park - Lost In The Echo.mp3
Linkin Park - New Divide (Official Video).mp3
Linkin Park - Numb (original).mp3
Linkin Park - What I've Done (Official Video).mp3
LMFAO feat. Lauren Bennett, GoonRock - Party Rock Anthem.mp3
Lost Frequencies Feat. Easton Corbin - Are You With Me [Original mix] [SM].mp3
Lucky Twice - Lucky.mp3
Luis Fonsi - Despacito.mp3
Lynyrd Skynyrd - Free Bird.mp3
Macklemore, Ryan Lewis feat. Ray Dalton - Can't Hold Us (feat. Ray Dalton).mp3
Macklemore, Ryan Lewis feat. Wanz - Thrift Shop (feat. Wanz).mp3
Madcon feat. Ameerah - Freaky Like Me ТАНЦЕВАТЬ.mp3
Madonna - Frozen.mp3
Madonna - Give It 2 Me.mp3
Madonna - Hung Up.mp3
Magic! - Rude.mp3
Mark Ronson feat. Bruno Mars - Uptown Funk.mp3
Maroon 5 - Lucky Strike.mp3
Maroon 5 - Makes Me Wonder.mp3
Maroon 5 - Maps.mp3
Maroon 5 - Memories.mp3
Maroon 5 - Misery (Main Version).mp3
Maroon 5 - Never Gonna Leave This Bed.mp3
Maroon 5 - One More Night.mp3
Maroon 5 - She Will Be Loved.mp3
Maroon 5 - Sugar.mp3
Maroon 5 - This Love.mp3
Maroon 5 - Wake Up Call.mp3
Maroon 5 - Won't Go Home Without You.mp3
Maroon 5 feat. Cardi B - Girls Like You.mp3
Maroon 5 feat. Christina Aguilera - Moves Like Jagger.mp3
Maroon 5 feat. Wiz Khalifa - Payphone.mp3
Mattafix - Big City Life.mp3
MC Hammer - U Can't Touch This .mp3
Meja - All 'Bout The Money.mp3
Metallica - Enter Sandman.mp3
Metallica - Nothing Else Matters.mp3
Metallica - The Unforgiven (Video).mp3
Metallica - The Unforgiven II.mp3
Michael Jackson - Billie Jean.mp3
Michael Jackson - Smooth Criminal.mp3
Michel_Tel_-_Ai_Se_Eu_Te_Pego_(musmore.com).mp3
Mika - Relax Take It Easy (Original Mix)1.mp3
Miley Cyrus - Wrecking Ball.mp3
MOBY - Lift Me Up.mp3
Modern Talking - Brother Louie (Пластинка).mp3
Modern Talking - Cheri Cheri Lady.mp3
Modern Talking - Geronimo's Cadillac.mp3
Modern Talking - You're My heart, You're My soul.mp3
Modjo - Mojo - Lady.mp3
Modo - Eins, zwei, polizei.mp3
Mohombi - Bumpy Ride.mp3
Mr. Credo - Чудная долина.mp3
Nadiya - Amies-Ennemies.mp3
Nelly Furtado - All Good Things (Come To An End) (UK Radio Mix).mp3
Nelly Furtado - I'm Like A Bird.mp3
Nelly Furtado - Say It Right.mp3
Ne-Yo - Closer.mp3
Nickelback - How You Remind Me.mp3
Nickelback - If Today Was Your Last Day.mp3
Nickelback - When We Stand Together (2011).mp3
Nik Kershaw - The Riddle (Gigi D' Agostino Edit).mp3
Nirvana - Rape me - Rape Me.mp3
Nirvana - Smells Like Teen Spirit.mp3
No Dobut (Gwen Stefani) - It`s my life .mp3
No Doubt - Dont speak.mp3
Bee gees - Staying alive.mp3
Oasis - Don't Look Back in Anger.mp3
Oasis - Wonderwall.mp3
Oingo Boingo - Little Girls.mp3
Olivia Rodrigo - good 4 u.mp3
OneRepublic - All The Right Moves.mp3
OneRepublic - Apologize Original Version.mp3
OneRepublic - counting stars (original version).mp3
One-T ft. Cool-T - The Magic Key.mp3
Opus - Life Is Life.mp3
OST - Top Of The World.mp3
Outkast - Hey Ya.mp3
Outkast - Ms Jackson.mp3
O-ZONE - Dragonstea Din Tei (Radio Edit).mp3
Pakito - Living in video.mp3
Panic! At The Disco - High Hopes.mp3
Passenger - Let Her Go [Official Video].mp3
PH Electro - Englishman In New York (Radio Edit).mp3
Pharrell Williams - Happy.mp3
Pitbul - Timber (ft. Kesha).mp3
Pitbull feat. Ne-Yo, Afrojack, Nayer - Give Me Everything.mp3
Pitbull Ft. Eila - Slow.mp3
Pixies - Where Is My Mind.mp3
Postmodern Jukebox - Thrift Shop .mp3
Professor Green feat. Emeli Sandé - Read All About It.mp3
Queen - Another One Bites The Dust.mp3
Queen - I Want To Break Free.mp3
R.E.M. - Losing My Religion.mp3
Radiohead - All I Need.mp3
Radiohead - Creep.mp3
Radiohead - Karma Police.mp3
Radiohead - No Surprises1.mp3
Rammstein - America.mp3
Rammstein - Ashe Zu Asche - 4 Herzeleid - 1995.mp3
Rammstein - Mein Land.mp3
RASMUS - In the shadows (re-edit.mp3
Rasmus - Livin' In A World Without You.mp3
Reamon - Tonight.mp3
Reamonn - My Supergirl.mp3
Red Hot Chili Peppers - Californication.mp3
Red Hot Chili Peppers - Can't Stop.mp3
Red Hot Chili Peppers - Dani California1.mp3
Red Hot Chili Peppers - Dark Necessities.mp3
Red Hot Chili Peppers - Desecration Smile.mp3
Red Hot Chili Peppers - Otherside.mp3
Red Hot Chili Peppers - Scar Tissue.mp3
Red Hot Chili Peppers - Snow (Hey Oh).mp3
Red Hot Chili Peppers - Under The Bridge.mp3
RHCP - Road Trippin'.mp3
Rick Astley - Never Gonna Give You Up.mp3
Ricky Martin - Livin' la Vida Loca.mp3
Rihanna - Diamonds.mp3
Rihanna - S&M.mp3
Rihanna feat. JAY-Z - Umbrella.mp3
Rob Thomas - Lonely No More.mp3
Robert Miles - Children (Dream Version2).mp3
Robin Schulz feat. Francesco Yates - Sugar (feat. Francesco Yates).mp3
Rod Stewart - Young Turks.mp3
Roxette - It Must Have Been Love.mp3
Roxette - Listen To Your Heart.mp3
Roxette - Sleeping In My Car.mp3
S3RL - MTC.mp3
SAFRI - DUO.mp3
Sam Smith - I'm Not The Only One.mp3
Sander van Doorn feat. Carol Lee - Love Is Darkness (Radio Edit) 2011 .mp3
Scatman John - (I Want To) Be Someone.mp3
Scatman John - Everybody Jam.mp3
Scatman John - Scatman (Ski-Ba-Bop-Ba-Dop-Bop).mp3
Scatman John - Scatman's World.mp3
Scooter - Fire.mp3
Scooter - How Much Is The Fish.mp3
Scooter - Scooter - Shake That.mp3
Scorpions - Still Loving You.mp3
Scorpions - White Dove.mp3
Scorpions - Wind Of Change.mp3
Selena Gomez - Come & Get It.mp3
Selena Gomez & The Scene - Love You Like A Love Song.mp3
Semisonic - Closing Time.mp3
September - It Doesn't Matter.mp3
September - Satelite.mp3
September - You'll Never See Me Again.mp3
Shakira - Objection (Tango).mp3
Shakira - She Wolf.mp3
Shakira - Underneath Your Clothes.mp3
Shakira - Whenever, Wherever.mp3
Shakira feat. Wyclef Jean - Hips Don't Lie.mp3
Shawn Mendes, Camila Cabello - Senorita.mp3
Sia - Chandelier.mp3
Sia - Unstoppable.mp3
SKRILLEX - Bangarang feat. Sirah
Smash Mouth - All Star.mp3
Smash Mouth - I'm A Believer.mp3
Smoke On The Water With Lyrics.mp3
Snoop Dogg & Wiz Khalifa Ft Bruno Mars - Young Wild & Free.mp3
Snoop Dogg, David Guetta - Sweat (Snoop Dogg Vs. David Guetta).mp3
Snoop Dogg, Dr. Dre - The Next Episode.mp3
Spice Girls - Wannabe.mp3
Steppenwolf - Born To Be Wild.mp3
Stevie Wonder - I just call to say I love you .mp3
Sting - Englishman in New York.mp3
Sting - Shape of my heart.mp3
Story Of The Year - The Antidote.mp3
Stromae - Alors on dance.mp3
Sum 41 - Fat Lip.mp3
Sum 41 - In Too Deep.mp3
Sum 41 - Some Say.mp3
Sum 41 - The Hell Song.mp3
Sum&41 - Still waiting.mp3
Sunrise Avenue - Fairytale Gone Bad.mp3
Sunrise Avenue - Welkom to my life.mp3
Supermode - Tell Me Why.mp3
Survivor - Eye of the Tiger.mp3
Survivor - You are the best.mp3
Sylver - Forgiven.mp3
System Of A Down - Aerials1.mp3
System Of A Down - Atwa.mp3
System Of A Down - B.Y.O.B. (2005).mp3
System Of A Down - Chop Suey!.mp3
System Of A Down - Empty Walls.mp3
System Of A Down - Hypnotize.mp3
System Of A Down - Lonely Day.mp3
System Of A Down - Lost In Hollywood.mp3
System Of A Down - Psycho.mp3
System Of A Down - Question!.mp3
System Of A Down - Radio Video.mp3
System Of A Down - Roulette.mp3
System Of A Down - Sky Is Over.mp3
System Of A Down - Toxity.mp3
Taio Cruz feat. Flo Rida - Hangover.mp3
Take That - Love Love [OST Люди-Икс Первый класс].mp3
Taylor Swift - Blank Space.mp3
Taylor Swift - I Knew You Were Trouble.mp3
Taylor Swift - Shake It Off.mp3
The Baseballs - Umbrella.mp3
The Black Eyed Peas - Don't Phunk With My Heart.mp3
The Black Eyed Peas - I Gotta Feeling.mp3
The Black Eyed Peas - Let's Get It Started
The Black Eyed Peas - My Humps\
The Black Eyed Peas - Pump It.mp3
The Black Eyed Peas - Shut Up.mp3
The Bobby Fuller Four - I Fought the Law [Battlefield Vietnam - OST #5 (Кванг Тр.mp3
The Caesars - Jerk It out.mp3
The Connells - 74'-75'.mp3
The Cranberries - Zombie.mp3
The Desert Rose Band - One Step Forward.mp3
The Guess Who - Shakin' All Over.mp3
The Killers - Mr. Brightside.mp3
The Killers - Somebody Told Me.mp3
The Mamas  The Papas - California Dreamin'.mp3
The Offspring - One Fine Day.mp3
The Offspring - The Kids Aren't Alright!.mp3
The Offspring - Trust In You.mp3
The Offspring - Want You Bad.mp3
the offspring - Why Don't You Get A Job.mp3
The Offspring - You're Gonna Go Far, Kid.mp3
the offstpring - white guy2.mp3
The Police - Every Breath You Take.mp3
THE PRODIGYPAIN - PAIN-Shut Your Mouth.mp3
The Pussycat Dolls - When I Grow Up.mp3
The Rembrandts - I'll Be There For You.mp3
The Rolling Stones - (I Can't Get No) Satisfaction (Official Lyric Video).mp3
The Rolling Stones - Paint It, Black (Official Lyric Video).mp3
The Verve - Bitter Sweet Symphony.mp3
The Weekend - Blinding lights.mp3
The Weeknd - Can't Feel My Face.mp3
The Weeknd - In Your Eyes.mp3
The Weeknd - Save Your Tears.mp3
The White Stripes - Seven Nation Army.mp3
The Who - Behind blue eyes (1971).mp3
La Caution - Thé à la Menthe - The Laser Dance Song.mp3
Third Eye Blind - Jumper (OST Yes Man).mp3
Three Days Grace - Chalk Outline.mp3
Three Days Grace - I Hate Everything About You.mp3
Tim McMorris - Life Is Beautiful [muzmo.ru].mp3
Timbaland ft. Katty Perry - If We Ever Meet Again.mp3
Tinie Tempah feat. Eric Turner - Written In The Stars.mp3
Tom Petty - runnin' down a dream.mp3
Tonight Radio Edit Jay Sean
Tony Igy - Astronomia.mp3
Tony Igy - Pentagrama (original).mp3
Törsh - Thai Take Away.mp3
Toto - Africa.mp3
Toto - Hold the Line.mp3
Train - 50 Ways To Say Goodbye.mp3
Train - Drive By.mp3
Train - Hey, Soul Sister.mp3
trauma.mp3
Turbo Knight - Rasengan (Original Mix 2018).mp3
twenty one pilots - Heathens.mp3
Twenty One Pilots - Stressed Out.mp3
U2 - With or without you .mp3
Usher feat. Lil Jon, Ludacris - Yeah.mp3
Vance Joy - Riptide.mp3
Velvet - Electric Avenue.mp3
Vengaboys - Boom Boom Boom Boom (mp3store.cc).mp3
Vengaboys - We Like To Party.mp3
Wham! - Careless Whisper (Дэдпул [2016]  Deadpool)[vk.comamazingmoviesmusic].mp3
Wiz Khalifa feat. Charlie Puth - See You Again (feat. Charlie Puth).mp3
Xzibit - X (original version).mp3
Yellowcard - Breathing.mp3
Yves Larock - Rise Up (Original Radio).mp3
АЗА#ZLO - Я хочу.mp3
Альберт Матосян - Адлер-Сочи.mp3
Ария - Потерянный рай.mp3
Ария-Беспечный Ангел - Беспечный ангел.mp3
Балаган Лимитед - Крылышки.mp3
Бутырка - Запахло весной.mp3
Валентин Стрыкало - Гей.mp3
валентин стрыкало - наше лето.mp3
Валентин Стрыкало - Преждевременное семяизвержение.mp3
Валентин Стрыкало - Ты не такая.mp3
Валентин Стрыкало - Я бью женщин и детей.mp3
Доминик Джокер - Если ты со мной.mp3
Звери - Брюнетки и блондинки.mp3
Кабанчик - Без названия.mp3
Кино - Кончится лето.mp3
Кипелов - 4. Я Свободен (2013).mp3
Король и Шут - Лесник.mp3
Король и Шут - Разбежавшись прыгну со скалы.mp3
Ленинград - Я свободен! .mp3
МАЛЬЧИШКИ - ЭТОТ БИТ (премьера клипа за 5 минут) (1).mp3
Михаил Круг - Владимирский централ.mp3
Михаил Круг - Магадан.mp3
Мортал Комбат - Саунтрек.mp3
Нейромонах Феофан - Притоптать.mp3
нексюша - Любви все возрасты покорны.mp3
Ногу свело - Наши юные смешные голоса.mp3
Сан бой - Гром хит мурашки по телу.mp3
Свинцовый Туман - Я знаю придет тот день.mp3
Сектор Газа - Песенка.mp3
Фактор 2 - Марихуана 2000.mp3
Шуфутинский Михаил - Наколочка.mp3
Я волна хрен пойми кто поёт.mp3
Kate Alexa - No Ordinary Girl.mp3
Grimes - Flesh without Blood.mp3
50 Cent Feat. Justin Timberlake & Timbaland - Ayo Technology (Prod by Timbaland)
J Cut & Kolt Siewerts - The Flute Tune (Soulpride Extended Remix)
Justin Timberlake - What Goes Around.Comes Around.mp3
Timbaland feat. Justin Timberlake, Nelly Furtado - Give It To Me.mp3
Madonna feat. Justin Timberlake, Timbaland - 4 Minutes (feat. Justin Timberlake .mp3
Enrique Iglesias feat. Ciara - Takin' Back My Love.mp3
Enrique Iglesias - Tired Of Being Sorry.mp3
Enrique Iglesias feat. Pitbull - I Like It.mp3
Enrique Iglesias feat. Wisin - DUELE EL CORAZON.mp3
S3RL - Pika Girl.mp3
Pendulum - Witchcraft.mp3
Pendulum - Watercolour.mp3
Shakira feat. Rihanna - Can't Remember to Forget You.mp3
Sean Paul - Give It Up to Me.mp3
Mr.Kitty - After Dark.mp3
Madcon feat. Ray Dalton - Don't Worry (with Ray Dalton).mp3
Robin Thicke feat. T.I, Pharrell - Blurred Lines.mp3
Cherish feat. Yung Joc - Killa.mp3
Taio Cruz feat. Ludacris - Break Your Heart.mp3
Placebo - Every You, Every Me.mp3
Placebo - Pure Morning.mp3
Aaron Smith - Dancin.mp3
Juanes - La Camisa Negra.mp3
Milky Chance - Stolen Dance.mp3
Miley Cyrus - Who Owns My Heart.mp3
Miley Cyrus - We Can't Stop.mp3
Willy William - Ego.mp3
Alex Clare - Too Close.mp3
Rag'n'Bone Man - Human.mp3
Kwabs - Walk.mp3
Disturbed - Decadence.mp3
Nelly Furtado - Manos Al Aire (Juan Magan Remix) (2010).mp3
Nelly Furtado - Turn Off The Light.mp3
Akcent - Stay with Me.mp3
Akcent - Jokero.mp3
Ace of Base - All That She Wants
Dr. Alban - It's My Life
Lil Nas X, Jack Harlow - INDUSTRY BABY.mp3
BRAINSTORM - MAYBE.mp3
Avril Lavigne - Sk8er Boi.mp3
Tityo - Come Along With Me.mp3
Burak Yeter Ft. Danelle Sandoval - Tuesday.mp3
P!NK - U + Ur Hand.mp3
P!NK - Stupid Girls.mp3
P!NK - Blow Me (One Last Kiss).mp3
P!NK - Who Knew.mp3
P!NK - Try.mp3
P!NK - Fkin' Perfect.mp3
P!NK - Whataya Want from Me.mp3
Alizée - Moi. Lolita.mp3
Lana Del Rey - Summertime Sadness.mp3
Lana Del Rey - Young And Beautiful.mp3
Daniel Powter - Bad Day
Lipps Inc. - Funky Town.mp3
Ellie Goulding - Burn.mp3
Ellie Goulding - Love Me Like You Do.mp3
Rita Ora, DJ Fresh, DJ Fresh feat. Rita Ora - Hot Right Now.mp3
Aura Dione feat. Rock Mafia - Friends.mp3
Gym Class Heroes - I have a new girlfriend.mp3
Timo Maas feat. Brian Molko - It's a first day of the rest of my life.mp3
Desireles - Voyage, Voyage.mp3
Madonna - Sorry.mp3
Stromae - Tous Les Memes.mp3
Evanescence - Going Under.mp3
Timbaland, D.O.E. feat. Keri Hilson - The Way I Are.mp3
Pitbull feat. Christina Aguilera - Feel This Moment.mp3
Aura Dione - Geronimo.mp3
Jay Sean - Ride It.mp3
Christina Aguilera - Genie In a Bottle.mp3
Christina Aguilera - Hurt.mp3
Christina Aguilera - Your Body.mp3
The Weeknd feat. Daft Punk - Starboy.mp3
Paradisio Ft Maria Garcia & Dj Patrick Samoy - Bailando.mp3
t.A.T.u. - Я сошла с ума.mp3
Two Door Cinema Club - What You Know (OST Мастер Гитары 2).mp3
Rick Astley - Together Forever.mp3
Daft Punk - Instant Crush.mp3
MGMT - Kids.mp3
Naughty Boy feat. Sam Smith - La La La.mp3
Kansas - Carry On Wayward Son.mp3
Morandi - Angels (Love Is The Answer).mp3
Morandi - Save Me.mp3
Powerwolf - Army of the Night.mp3
The Offspring - Can't Repeat.mp3
John Newman - Love Me Again.mp3
Lenka - Everything at Once.mp3
Irene Cara - Flashdance. What A Feeling.mp3
Manuel - Gas Gas Gas.mp3
Rammstein - Links 2 3 4.mp3
noisestorm_-_crab_rave_muzrecord.net.mp3
Дора - Если хочешь.mp3
Yakuza 0 - Friday Night.mp3
Alex Gaudino feat. Crystal Waters - Destination Calabria.mp3
Rihanna - Shut Up And Drive.mp3
ABBA - Gimme! Gimme! Gimme! (A Man After Midnight).mp3
Stromae - Papaoutai.mp3
Кино - Закрой за мной дверь, я ухожу.mp3
Village People - YMCA.mp3
Initial D - Don't Stop The Music.mp3
Madcon - Madcon_Beggin_48055195.mp3
Cypis - Gdzie jest biały węgorz (Zejście).mp3
Lil Nas X - Old Town Road.mp3
Piano Fantasia - Song for Denise.mp3
ATB - 9Pm (Till I Come).mp3
The Kiffness - Ievan Polkka ft. Bilal Göregen (Club Remix).mp3
Ace of Base - Happy Nation.mp3
Masterboy - Porque te vas.mp3
Selena - Freed from Desire 2008 (radio edit).mp3
PPK - Resurrection.mp3
Imany - Don't Be So Shy 
Cher - Believe.mp3
Eric Prydz - Call on Me.mp3
Dragonforce - Through The Fire & Flames.mp3
C.C. CATCH - I Can Lose My Heart Tonight.mp3
Laura Branigan - Self Control.mp3
Amy Macdonald - This Is The Life.mp3
Pesni_iz_SERIALOV_Visokosnyy_god-Tihiy_ogonek.mp3
Benassi Bros, Dhany - Hit My Heart - Radio Edit.mp3
Meg & Dia - Monster.mp3
Skillet - Monster.mp3
Rise Against - Savior.mp3
The Prodigy - Voodoo People.mp3
Daft Punk - Giorgio by Moroder (remix without Moroder's voice).mp3
Adam Gontier & Three Days Grace - Time of Dying.mp3
Far East Movement feat. Justin Bieber - Live My Life.mp3
C-BooL - Never Go Away.mp3
Gnarls Barkley - Crazy.mp3
LP - Lost on You.mp3
Geek Music - Portal _ End Credits _ Still Alive.mp3
Geek Music - Portal 2 _ End Credits _ Want You Gone.mp3
Flashdance - She's a maniac (Танец - вспышка).mp3
Bloodhound Gang - Foxtrot Uniform.mp3
Psy - Gangnam Style (강남스타일).mp3
Nina Kraviz - Skyscrapers.mp3
The Beloved - Sweet Harmony.mp3
Miss Jane - Its A Fine Day
A Touch Of Class - Around the World (La La La La La) (Radio Version).mp3
Babylon Zoo - Spaceman.mp3
Muse - Supermassive Black Hole.mp3
Bomfunk MC's - Freestyler.mp3
Doja Cat - Say So.mp3
Ногу Свело - Свежий ветер-ROCK-REMIX.mp3
Любэ - Ветер-ветерок.mp3
Dr Bombay - Calcutta (Taxi, Taxi, Taxi).mp3
Reel 2 Real feat. The Mad Stuntman - I Like To Move It (feat. The Mad Stuntman).mp3
Shocking Blue - Venus.mp3
Никодим - Кто-то отписался
Santana feat. Rob Thomas - Smooth.mp3
Marty Robbins - Big Iron.mp3
Axel F - Crazy Frog.mp3
Studio Yuraki - The 2017 Bad Apple Rock Cover (Sam Luff Ver.).mp3
Imagine Dragons x J.I.D - Enemy.mp3
Benny Benassi pres. The Biz - 02 Satisfaction (Isak Original Extended).mp3
Sabrina - Boys (Summertime Love)
Paul Engemann - Scarface
Fall Out Boy - Centuries.mp3
Arash feat. Helena - Pure Love.mp3
AySel, Arash - Always.mp3
Arash - Joone Man.mp3
Arash feat. Aneela - Chori Chori.mp3
The Chemical Brothers - Galvanize.mp3
Limp Bizkit - Rollin'.mp3
Sam Houghton, Joe Collinson - Into Asgard.mp3
Ray Parker, Jr. - Ghostbusters.mp3
INTELLIGENCY - AUGUST (ENGLISH VERSION).mp3
Lykke Li - I Follow Rivers.mp3
Fratii din Carbuna - Of Of Ce Sa Fac.mp3
Lazy Town - We Are Number One.mp3
Alex C. feat. Yass - Tienes el Culo Mas Bello del Mundo.mp3
E-Type - Russian Lullaby.mp3
Bellini - Samba De Janeiro (Club Mix 1997) .mp3
The Cardigans - My Favourite Game.mp3
Nena - 99 Luftballons.mp3
Ice Cube - It Was A Good Day.mp3
Невiдомий - Sonia y Selena - Con una mano en mi cintura.mp3
Мурат Тхагалегов - Калым.mp3
2Pac feat. Talent - Changes.mp3
Witch Doctor - cartoons ooh eeh uuh aah aah ting tang walla walla bing bang.mp3
REDNEX - Cotton Eye Joe.mp3
Tokio Hotel - Monsoon.mp3
Sash! - Ecuador.mp3
Armin van Buuren feat. Sharon den Adel - In And Out Of Love 
Mylène Farmer - L'amour n'est rien.mp3
Benny Benassi - Every Single Day
Sandra - Around My Heart
Hurts - Wonderful Life.mp3
Moby - Why Does My Heart Feel So Bad.mp3
Deepside Deejays - Never Be Alone.mp3
Inna - Amazing.mp3
Arash feat. Helena - Broken Angel.mp3
Adam Lambert - Whataya Want from Me.mp3
Adam Lambert - Ghost Town.mp3
Adam Lambert - If I Had You.mp3
Adam Lambert - Never Close Our Eyes.mp3
Mondotek - Alive.mp3
KATO feat. Jon - Turn The Lights Off.mp3
Alex Hepburn - Under.mp3
DJ Layla feat. Alissa - Single Lady, Pt. 1.mp3
The Script feat. will.i.am - Hall of Fame.mp3
Playmen feat. Demy - Fallin.mp3
Morandi - Midnight Train.mp3
The Black Eyed Peas - Just Can’t Get Enough.mp3
DEV - In The Dark.mp3
Example - Changed the Way You Kiss Me.mp3
Morandi - Colors.mp3
Morandi - Love Me.mp3
Don Omar feat. Tego Calderón - Bandoleros.mp3
Basic Element - Touch You Right Now.mp3
Lucenzo feat. Don Omar - Danza Kuduro
Avicii, Nicky Romero - I Could Be The One (Avicii Vs. Nicky Romero).mp3
The Wanted - Chasing The Sun.mp3
Bob Sinclar feat. Steve Edwards - World Hold on (Children of the Sky) [Radio Edi.mp3
Bob Sinclar - Love Generation.mp3
Alexandra Stan - Mr. Saxobeat.mp3
Pakito - Moving on Stereo.mp3
Tom Boxer feat. Antonia - Morena.mp3
Timofey ft. Bartosz Brenes vs. Terry B. - Heaven.mp3
The Prodigy - Omen.mp3
Skrillex feat. Sirah - Kyoto (feat. Sirah).mp3
Serge Devant featuring Hadley - Addicted.mp3
Serge Devant ft. Emma Hewitt - Take me with you.mp3
J-Five - Find a Way.mp3
Global Deejays - Hardcore Vibes (Original Mix).mp3
040_Discobitch - C'est Beau La Bourgeoisie (Bodybangers Remix).mp3
Danzel - You Spin Me Round.mp3
Danzel - Pump It Up.mp3
Dan Balan - Justify Sex.mp3
Dan Balan - Freedom.mp3
Skillet - Hero.mp3
Lil Jon & The East Side Boyz - Get Low 
Yolanda Be Cool & DCUP - We No Speak Americano.mp3
Rihanna, Calvin Harris - We Found Love.mp3
Fort Minor feat. Styles Of Beyond - Remember the Name (feat. Styles of Beyond).mp3
Radio Killer - Lonely Heart.mp3
R.I.O. - Shine On.mp3
Pitbull feat. Chris Brown - International Love.mp3
Pitbull - Hotel Room Service.mp3
Pitbull feat. T-Pain - Hey Baby (Drop It to the Floor).mp3
Paul van Dyk feat. Rea Garvey - Let Go.mp3
DMX - Get It On The Floor (Feat. Swizz Beatz).mp3
K.Maro - Let's go.mp3
K.Maro - Femme like U.mp3
Skrillex, Damian Jr Gong Marley - Make It Bun Dem.mp3
Shakira feat. Dizzee Rascal - Loca.mp3
Jakarta - One Desire.mp3
Loreen - Euphoria.mp3
Akon - Lonely.mp3
Far East Movement feat. The Cataracs, DEV - Like A G6.mp3
Far East Movement - Turn Up The Love (feat. Cover Drive).mp3
Nero - Promises.mp3
Marius feat. Giulia - Rain.mp3
Swedish House Mafia feat. John Martin - Don't You Worry Child.mp3
Flo Rida feat. Sia - Wild Ones (feat. Sia).mp3
MFG - Summertime Sadness (Cedric Gervais remix).mp3
Lexter - Freedom To Love.mp3
Laurent Wolf - No Stress (English radio).mp3
Keri Hilson - I Like.mp3
Fly Project - Mandala.mp3
Hurts - Stay.mp3
Guru Josh Project - Infinity 2008.mp3
[muzmo.ru] Global Deejays - The Sound Of San Francisco [muzmo.ru].mp3
Eric Prydz feat. Pink Floyd - Proper Education (Original Mix).mp3
Eric Prydz - Pjanoo.mp3
Freemasons - Heartbreak (Make Me a Dancer).mp3
Pitbull Ft. Marc Anthony - Rain Over Me(Prod. by RedOne).mp3
Cascada - Everytime We Touch.mp3
DJ Chris Parker - Symphony 2011.mp3
Craig David - Insomnia.mp3
Skillet - Awake and Alive.mp3
Ранетки - О Тебе.mp3
Anastacia - Left Outside Alone.mp3
Narcotic Thrust - I Like It.mp3
Basto - Again & Again.mp3
Bruno Mars - Just The Way You Are.mp3
Alan Walker - The Spectre.mp3
PewDiePie - Congratulations (Clean).mp3
Taylor Swift - Bad Blood.mp3
Dynoro, Gigi D'Agostino - In My Mind.mp3
Calvin Harris, Rihanna - This Is What You Came For.mp3
AronChupa - I'm an Albatraoz.mp3
Shawn Mendes - Stitches.mp3
Martin Garrix - Animals.mp3
The Chainsmokers feat. Daya - Don't Let Me Down.mp3
Fifth Harmony feat. Ty Dolla $ign - Work from Home.mp3
Pedro Capó - Calma.mp3
Daddy Yankee feat. Snow - Con Calma.mp3
Charlie Puth feat. Selena Gomez - We Don't Talk Anymore (feat. Selena Gomez).mp3
ZAYN feat. Sia - Dusk Till Dawn.mp3
Tones And I - Dance Monkey.mp3
Major Lazer feat. DJ Snake, MØ - Lean On.mp3
Dua Lipa - New Rules.mp3
J Balvin, Willy William - Mi Gente.mp3
Billie Eilish - bad guy.mp3
Justin Bieber feat. Ludacris - Baby.mp3
Marshmallow - Alone.mp3
Alan Walker - Faded.mp3
Alan Walker - Alone.mp3
Девид Таварэ - Summer love.mp3
David Guetta feat. Kelly Rowland - When Love Takes Over .mp3
Whitney Houston - I Will Always Love You.mp3
Ian Carey - Redlight.mp3
David A. Stewart feat. Candy Dulfer - Lily Was Here.mp3
Kenny G - Havana (1997 год).mp3
Неизвестен - Yann Tiersen - J'y Suis Jamais Alle-Amelie [Remix] CHECK THE DESCRI
Muse - Uprising
Boney M. - Sunny.mp3
Boney M. - Daddy Cool.mp3
Boney M. - Bahama Mama.mp3
Alice DeeJay - Better Off Alone (Radio Edit).mp3
PH Electro - San Francisco
SNAP! - Rhythm Is A Dancer.mp3
La Bouche - Be My Lover.mp3
Toto Cutugno - L'Italiano.mp3
Неизвестен - Al Bano - Felicita.mp3
Gipsy Kings - Bamboléo.mp3
bôa - Duvet.mp3
Bad Boys Blue - I Wanna Hear Your Heartbeat [Sunday Girl].mp3
Tom Jones feat. Mousse T. - Sexbomb.mp3
Kaoma - Lambada.mp3
Geri Halliwell - It's Raining Men.mp3
Fatboy Slim - The Rockafeller Skank (1).mp3
Blondie - Heart Of Glass.mp3
Freddie Mercury - Living on My Own.mp3
Демо - Солнышко.mp3
Charli XCX - Boom Clap.mp3
Bob Marley & The Wailers - Three Little Birds.mp3
Gloria Gaynor - I Will Survive.mp3
Ray Charles - Hit the Road Jack.mp3
Depeche Mode - Personal Jesus.mp3
Агата Кристи - Как на войне [320 kbps]
Агата Кристи - Сказочная тайга.mp3
TSERIES DISS TRACK // bitch lasagna Pewdipie
One Direction - One Way or Another (Teenage Kicks).mp3
Poets of the Fall - Carnival of Rust.mp3
ABBA - Mamma Mia.mp3
Цыган - Ай ДИГИ-ДИГИ-ДИГИ-ДАЙ (zaycev.net).mp3
Louis Armstrong - What A Wonderful World.mp3
Bring Me The Horizon - Can You Feel My Heart.mp3
Неизвестен - Tarkan - Dudu.mp3
Ram Jam - Black Betty.mp3
Daryl Hall & John Oates - Out of Touch.mp3
ARABESQUE (1980) - Midnight Dancer.mp3
Nirvana - Come As You Are.mp3
Mylène Farmer - Sans contrefaçon.mp3
The Cardigans - Lovefool.mp3
Sophie Ellis-Bextor - Catch You.mp3
Кино - Группа крови.mp3
Max Romeo, The Upsetters - Chase The Devil.mp3
Garbage - I Think I'm Paranoid.mp3
SEREBRO - Song #1.mp3
Icona Pop feat. Charli XCX - I Love It (feat. Charli XCX).mp3
George Thorogood & The Destroyers - Bad To The Bone.mp3
Lynyrd Skynyrd - Sweet Home Alabama.mp3
Поющие вместе - Такого, как Путин.mp3
Justice - Civilization.mp3
Nena - Irgendwie, irgendwo, irgendwann.mp3
HIM - Join Me in Death.mp3
Tears For Fears - Shout.mp3
Limp Bizkit - Behind Blue Eyes.mp3
David Guetta feat. Akon - Sexy Bitch (feat. Akon).mp3
Waterflame - Glorious Morning 2.mp3
Waterflame - Glorious Morning.mp3
Lou Bega - Mambo No. 5 (A Little Bit of.).mp3
In-Grid - Tu es foutu.mp3
New Order - Hey Now What You Doing.mp3
Radical Face - Welcome Home, Son (Remastered).mp3
The Living Tombstone, Eurobeat Brony - Discord.mp3
Alex Gaudino feat. Shena - Watch Out.mp3
Mötley Crüe - Kickstart My Heart.mp3
Ария - Пробил час.mp3
Bobby McFerrin - Don't Worry Be Happy.mp3
Akcent - On And On.mp3
Aly and Aj - Potential break up song.mp3
Amel Bent - Ma philosophie.mp3
Andreea Banica & Dony - Samba ( во румыны жгут! ).mp3
Bastian Van Shield - With Dust.mp3
Beats & Styles feat. Papa Dee - Take It Back (feat. Papa Dee).mp3
BeFour - How do you do.mp3
Benny Benassi & The Biz - Stop-Go.mp3
Cheryl Cole - Fight For This Love.mp3
Cheryl Cole - Parachute.mp3
Clara Chocolat - La Danse De Clara.mp3
193_Claudia Pavell Feat. Fatman Scoop - Just A Little Bit.mp3
Akon - Right Now (Na Na Na)
Danny feat. Therese - If Only You.mp3
David Tavare - Hot Summer Night (O La La La) .mp3
Delano and Crockett - Missing (Hi Tack radio mix)
DJ Matt feat Davin Dale - Baby I love you
Eiffel 65 - In a Song Italia
Flipsyde - When It Was Good.mp3
Florizel - Florizel - Les Valses De Vienne.mp3
Garou - Nothing Else Matters.mp3
Hi-tack - Silence
Ian Oliver feat. Shantel - Bucovina
Inna_-_Sun_is_Up
Inna - Love
John The Whistler - Wild Wild Web.mp3
Junior Caldera & Sophie Ellis-Bextor - Cant Fight This Feeling (Album Version).mp3
leonid_rudenko_and_max_fredrikson_-_goodbye_beautiful_eyes
Corona - Rhytm Of The Night.mp3
Calagero - Face A La Mer.mp3
Neoclubber - Don't Believe (Summer Mix).mp3
Neoclubber - I Heal My Soul.mp3
No Tone feat. Inusa Dawuda - Down Down Down (Dubwork mix).mp3.mp3
Oceana - Cry Cry.mp3
Plumb - Hang on (radio mix).mp3
Pussycat_Dolls_-_Hush_Hush(official_remix)
Rihanna - Cry.mp3
Rihanna - Rude Boy.mp3
Rihanna - Russian Roulette.mp3
Sean Paul & Zaho - Hold My Hand.mp3
Sharam featuring Daniel Bedingfield - The One.mp3
Shaun Baker Feat. Maloy - Give (Sebastian Volter Original Version).mp3
Sophie Ellis-Bextor - If I Can't Dance.mp3
Starclub - All The Boys (In Da Club) (DJRoMashko collection).mp3
01. STARCLUB feat. DR. ALBAN - CHIKI CHIKI (Radio Edit).mp3
Sunloverz - Summer Of Love (Ian Carey Remix).mp3
The Pussycat Dolls feat. Timbaland - Wait A Minute.mp3
Selena Gomez & The Scene - A Year Without Rain.m
Ottawan - Hands up (Give Me Your Heart).mp3p3
Smokie - I'll Meet You at Midnight.mp3
Zhi-Vago - Celebrate [The Love].mp3
Armin van Buuren, Sophie Ellis-Bextor - Not Giving Up On Love.mp3
Nelly - Just A Dream.mp3
T.I. - Castle Walls (feat. Christina Aguilera).mp3
Feder feat. Lyse - Goodbye (feat. Lyse).mp3
Kylie Minogue - Can't Get You out of My Head.mp3
StarPro - Mia Martina - Tu Me Manques (Missing You).mp3
Nico & Vinz - Am I Wrong.mp3
Scotty - The Black Pearl (Dave Darell Remix).mp3
TEAM BS - CASE DEPART (Europa Plus).mp3
Anna Naklab feat. Alle Farben, YOUNOTUS - Supergirl (feat. Alle Farben & YOUNOTU.mp3
Felix Jaehn feat. Jasmine Thompson - Ain't Nobody (Loves Me Better).mp3
Kygo, Parson James - Stole the Show.mp3
Lost Frequencies feat. Janieck Devy - Reality.mp3
Dana Russell - Romantic World (Radio Edit).mp3
Adele - Set Fire to the Rain.mp3
Adele - Set Fire to the Rain (Moto Blanco remix).mp3
Mishelle feat. Randi - Only You (Original Radio Edit).mp3
Nayer Feat. Mohombi & Pitbull - Suavemente.mp3
The Parakit feat. Alden Jacob - Save Me (feat. Alden Jacob).mp3
Alok, Zeeba, Bruno Martini - Hear Me Now (feat. Zeeba).mp3
Calvin Harris - My Way.mp3
Dimitri Vegas & Like Mike feat. Ne-Yo - Higher Place (Radio Edit).mp3
Felix Jaehn feat. Polina - Book Of Love.mp3
Capital Cities - Safe And Sound.mp3
The Underdog Project - Summer Jam.mp3
Daniel Powter - Crazy All My Life (Dfm 2013).mp3
Darren Hayes - Insatiable.mp3
De-Grees feat. Joy - 2 Times.mp3
Jessie J feat. B.o.B - Price Tag.mp3
Lana Del Rey - Young And Beautiful (Kevin Blank rmx)
LeAnn Rimes - Can't Fight The Moonlight (Latino Mix).mp3
Muttonheads feat. Eden Martin - Snow White (Alive).mp3
Ola - Jackie Kennedy.mp3
Samantha Jade - Firestarter.mp3
Riton x Nightcrawlers feat. Mufasa Hypeman - Friday (Dopamine Re-Edit) .mp3
Lil Wayne feat Jennifer Lopez - Im Into You.mp3
Dolce Vita - Mambo italiano DJ invive cut.mp3
Junior Caldera feat. Natalia Kills, Far East Movement - Lights Out (Go Crazy).mp3
Rockwell - Somebody's Watching Me (1984 г.).mp3
Deathray - I Wanna Lose Control (Uh Oh).mp3
Billy Talent - Fallen Leaves.mp3
Three Days Grace - Fallen Angel.mp3
Queen - Don't Stop Me Now.mp3
Snoop Dogg, Dr. Dre - Nuthin But A G'Thang.mp3
The Offspring - The Future Is Now.mp3
Ghost - Square Hammer.mp3
Айдар Галимов - Эх, алмасы.mp3
Empire Of The Sun - Alive.mp3
Army Of Lovers - Sexual Revolution.mp3
Empire Of The Sun - We Are The People.mp3
Neon Genesis Evangelion Full Opening Theme Song
The Pussycat Dolls feat. Snoop Dogg - Buttons.mp3
The Pussycat Dolls, Busta Rhymes - Don't Cha.mp3
Kelly Clarkson - Because of You.mp3
Adriano Celentano - Soli
Tim McMorris - It's a Beautiful Day.mp3
Tim McMorris - On Top Of The World.mp3
Morten Harket - Scared Of Heights.mp3
Counting Crows - Accidentally In Love.mp3
Royal Republic - Getting Along.mp3
ERA - Ameno.mp3 Remix
Aerosmith - I Don't Wanna Miss a Thing.mp3
Eminem - Like Toy Soldiers.mp3
DMX - X Gon' Give It To Ya.mp3
Robbie Williams - Supreme.mp3
KANA-BOON - Silhouette.mp3
Nickelback - Gotta Be Somebody.mp3
Oliver Heldens feat. Syd Silvair - Never Look Back (feat. Syd Silvair).mp3
Post Malone, Swae Lee - Sunflower.mp3
Anne-Marie - Ciao Adios.mp3
Sean Paul feat. Dua Lipa - No Lie.mp3
Erika - I Don't Know.mp3
Calvin Harris feat. Ellie Goulding - Outside.mp3
Anberlin - The Feel Good Drag.mp3
Azuro feat. Elly - Je Ne Sais Pas (R.I.O. Remix) (zaycev.net).mp3
Nelly feat. Kelly Rowland - Dilemma.mp3
Yellow Claw feat. Rochelle - Shotgun (feat. Rochelle).mp3
Element Eighty - Broken Promises.mp3
Fonzerelli featuring Ellenyi - Moonlight Party 2011 (feat. Ellenyi) [Extended Ra.mp3
Wham! - Last Christmas.mp3
Gorky Park - Moscow Calling.mp3
Fly Project - Musica.mp3
P!NK - So What.mp3
Sandu Ciorba - Ale.mp3
Whitesnake - Is This Love.mp3
DK - Я Смотрю Аниме.mp3
Unknown - Spooky Scary Skeletons (Remix) (Extended Mix) (Spooktober Theme Song).mp3
Roxette - Joyride.mp3
Silent Theory - Fragile Minds.mp3
Михайлов Стас - Все для тебя.mp3
Неизвестен - Magnolia - It's All Vain (Radio Edit).mp3
Lindsey Stirling - Roundtable Rival.mp3
Fratii din Carbuna - Ce Frumoasa E Carbuna.mp3
5sta Family - Вместе мы.mp3
Aoyagi Ryoko - Believe (Baki the Grappler OST).mp3
S3RL - I'll See You Again (feat. Chi Chi).mp3
DJ Smash - Dj Sm@sh-Moscow Never Sleeps.mp3
Lil Peep, XXXTENTACION - Falling Down.mp3
Asian Kung-Fu Generation (Naruto OST) - Haruka Kanata.mp3
Ikimonogakari - Blue Bird.mp3
003 Стас Михайлов - Без Тебя=.mp3
E-rotic - Max Don't Have Sex With Your Ex.mp3
Yakuza 0 OST - 82 Koi No Disco Queen (恋のディスコクイーン).mp3
blink-182 - What's My Age Again.mp3
Каста - Вокруг шум.mp3
Kate Ryan - Voyage voyage.mp3
Miracle Of Sound - The New Black Gold 2013 (Deus Ex Song).mp3
Alphaville - Big in Japan.mp3
Roy Orbison - Oh, Pretty Woman.mp3
Natalie Imbruglia - Torn.mp3
Сектор Газа - Бомж.mp3
Lily Allen - Smile.mp3
Витас - 7 Элемент.mp3
Танцы Минус - Город (Ремастеринг 2017).mp3
Кино - Последний герой.mp3
Our Stolen Theory - United (L.A.O.S Remix).mp3
Валерий Меладзе - Салют, Вера.mp3
Валерий Меладзе - Се ля ви.mp3
Caravan Palace - Miracle.mp3
DZIDZIO feat. Вова зі Львова - Павук - Павук.mp3
Vaya Con Dios - Nah Neh Nah.mp3
Paul Stanley - Live To Win.mp3
zerodovich - Нурминский - Валим (Gachi Remix).mp3
Cheryl - Call My Name.mp3
Oceana - Endless Summer (Video Version).mp3
Чи-Ли - Лето.mp3
David Guetta - One Love (feat. Estelle).mp3
Yeah Yeah Yeahs - Heads Will Roll (A-Trak Radio Edit) (320).mp3
Blondie - Maria.mp3
Andreas Johnson - Glorious.mp3 
Uniting Nations - You And Me
Jevo - Bad Piggies Theme.mp3
TWICE - The Feels.mp3
Fall Out Boy feat. John Mayer - Beat It.mp3
Dead by April - Losing You (ALT Version).mp3
Vengaboys - 5. We're Going To Ibiza.mp3
Tevvez - Legend Ψ.mp3
Men At Work - Down Under.mp3
Imagine Dragons - Bones.mp3
Pendulum - Propane Nightmares.mp3
Korn feat. Skrillex, Kill The Noise - Narcissistic Cannibal (feat. Skrillex & Ki.mp3
Günther - Ding Dong Song.mp3
Kiesza - Hideaway.mp3
DREAMERS - Die Happy.mp3
Nyusha - Выше.mp3
John Denver - Take Me Home, Country Roads.mp3
DJVI - Back On Track.mp3
DJVI - Can't Let Go.mp3
DJVI - Cycles.mp3
Avicii - Hey Brother.mp3
Pendulum - Crush.mp3
Kungs, Cookin' On 3 Burners - This Girl (Kungs Vs. Cookin' On 3 Burners).mp3
Aimee B - Fallen Angel.mp3
Dire Straits - Sultans Of Swing.mp3
Mr. Probz - Waves (Robin Schulz Remix) (Raadio Uuno).mp3
Лера МАССКВА [http___muz-vk.ru] - Мы с тобой вместе (OST Универ) - http___muz-vk.mp3
Корни - Наперегонки с ветром.mp3
Bambee - Bumble Bee
Ava Max - Sweet but Psycho.mp3
Jaymes Young - Infinity.mp3
Camila Cabello feat. Young Thug - Havana.mp3
Ariana Grande - Into You.mp3
Post Malone - Better Now.mp3
David Guetta - Love Is Gone (Another VERSION not my fav).mp3
Love is gone - SLANDER (1_45)(Justin Dai_Marvin remix).mp3
YAZOO - Don't Go ☆ MANDEE REMIX ☆
The Prodigy - Invaders Must Die (Radio Edit) (new).mp3
ATB - The Summer (Instrumental Club Version)
BEL SUONO & DJ Magic Finger - Te Quiero
P!NK feat. Nate Ruess - Just Give Me a Reason.mp3
Pompeya - 90.mp3
Dj_Snake_AlunaGeorge_-_You_Know_You_Like_It_(musmore.com).mp3
Elvis Presley - Tutti Frutti.mp3

https://cloud.mail.ru/public/AZei/wujutz5Do

* ChatGPT

** Could you recommend 10 song groups like "The Birthday Massacre"?

Certainly, here are 10 bands that you may enjoy if you like The Birthday Massacre:

    Covenant
    Ladytron
    Ashbury Heights
    Clan of Xymox
    Drab Majesty
    Blutengel
    Crüxshadows
    VNV Nation
    She Wants Revenge
    Depeche Mode

All of these bands have a similar sound to The Birthday Massacre, and they incorporate elements of synthpop, darkwave, and industrial music. Enjoy exploring!
