#+title: Networking

- [[https://github.com/leozz37/jaguar][leozz37/jaguar: 🐆 CLI tool for testing socket connections]]
- [[https://github.com/sysdream/chashell][sysdream/chashell: Chashell is a Go reverse shell that communicates over DNS. It can be used to bypass firewalls or tightly restricted networks.]]
- [[https://github.com/sysdream/ligolo][sysdream/ligolo: Reverse Tunneling made easy for pentesters, by pentesters https://sysdream.com/]]
- [[https://github.com/openwisp/openwisp-network-topology][openwisp/openwisp-network-topology: Network topology collector and visualizer. Collects network topology data from dynamic mesh routing protocols or other popular networking software like OpenVPN, allows to visualize the network graph, save daily snapshots that can be viewed in the future and more.]]
- [[https://github.com/prashantgupta24/firewalld-rest][prashantgupta24/firewalld-rest: A rest application to update firewalld rules on a linux server]]
- [[https://github.com/microsoft/ethr][microsoft/ethr: Ethr is a Network Performance Measurement Tool for TCP, UDP & HTTP.]]

* DHCP
- [[https://github.com/CyberShadow/dhcptest][CyberShadow/dhcptest: Cross-platform DHCP test client]]
- [[https://habr.com/ru/company/dsec/blog/333978/][Атакуем DHCP / Блог компании Digital Security / Хабр]]

* VLAN

| cisco       | tp-link       |
| access port | untagged port |
| trunk port  | tagged port   |

* Scan
- [[https://github.com/marco-lancini/goscan][marco-lancini/goscan: Interactive Network Scanner]]
- [[https://github.com/v-byte-cpu/sx][v-byte-cpu/sx: Fast, modern, easy-to-use network scanner]]

* keepalived
- [[https://tech-geek.ru/keepalived/][Настройка отказоустойчивой сети в Linux с keepalived]]
- [[https://www.altlinux.org/Keepalived][Keepalived — ALT Linux Wiki]]
- [[http://www.linux-admins.net/2015/02/keepalived-using-unicast-track-and.html][Linux Administration: Keepalived using unicast, track and notify scripts]]

* Packets
- [[https://github.com/pesos/rshark][pesos/rshark: Simple Packet Monitoring Tool]]
- [[https://github.com/thombashi/tcconfig][thombashi/tcconfig: A tc command wrapper. Make it easy to set up traffic control of network bandwidth/latency/packet-loss/packet-corruption/etc. to a network-interface/Docker-container(veth).]]

* Learning
- [[https://radiocrafts.com/why-is-multicasting-becoming-essential-for-mesh-networks/][Why is Multicasting Becoming Essential for Mesh Networks? - Radiocrafts]]
- [[https://unix.stackexchange.com/questions/619068/the-difference-between-ip-link-down-and-physical-link-absence][linux - The difference between ip link down and physical link absence - Unix & Linux Stack Exchange]]

* Tunnels
** Misc
 - [[https://github.com/Dreamacro/clash][Dreamacro/clash: A rule-based tunnel in Go.]]
** GRE
 - [[https://community.hetzner.com/tutorials/linux-setup-gre-tunnel][Hetzner Online Community]]

* WOL
- [[https://github.com/mdom/wakeonweb][mdom/wakeonweb: Dashboard for wakeonlan]]

* Backup
- [[https://github.com/ytti/oxidized][ytti/oxidized: Oxidized is a network device configuration backup tool. It's a RANCID replacement!]]

* bridge

- Create a bridge
  : ip link add name br0 type bridge

* nc
** UDP
  On server listen UDP port:
  : nc -ul 6111

  On client:
  : nc -u <server> 6111

* ip

- Bind port even if no IP address available:
: net.ipv4.ip_nonlocal_bind = 1

#+BEGIN_SRC yaml
  ethernet frame:
    preamble/sfd:
    destination address:
    source address:
    ethernet type:
    payload:
      ip header:
        1:
          version:
            size: 4 bytes
          ihl:
          type of service:
          total length:
        2:
          identification:
          flags:
          fragment offset:
        3:
          time to live:
          protocol:
          header checksum:
        4:
          source address:
        5:
          destination address:
        6: # rarely used
          options:
          padding:
    frame check sequence:
#+END_SRC

** Test gateway

- In =screen= session press Ctrl+C if successful
  : sh -c 'ip r delete default; ip r add default via 172.16.103.208; sleep 10; ip r delete default; ip r add default via 172.16.103.1'

* tcpdump
- [[https://danielmiessler.com/study/tcpdump/][A tcpdump Tutorial with Examples — 50 Ways to Isolate Traffic | Daniel Miessler]]

* Traffic shaping
- [[https://github.com/hkbakke/tc-gen][hkbakke/tc-gen: Modern linux traffic shaping made easy]]
- [[https://yandex.ru/search/?text=traffic%20shaping%20linux%20ssh%20%22tc%22][traffic shaping linux ssh "tc" — Яндекс: нашлось 3 тыс. результатов]]
- [[https://www.cyberciti.biz/faq/linux-traffic-shaping-using-tc-to-control-http-traffic/][tc: Linux HTTP Outgoing Traffic Shaping (Port 80 Traffic Shaping) - nixCraft]]
- [[https://yandex.ru/turbo/litl-admin.ru/s/linux/shejpim-trafik-linux-pri-pomoshhi-tc.html][Шейпим трафик Linux при помощи tc]]
- [[https://habr.com/ru/post/88624/][Шейпирование трафика в Linux / Хабр]]
- [[https://www.google.com/search?q=shapping+traffic+arch&hl=en][shapping traffic arch - Google Search]]
- [[https://wiki.archlinux.org/title/Advanced_traffic_control#Using_tc_only][Advanced traffic control - ArchWiki]]
- [[https://yandex.ru/search/?text=iperf%20example][iperf example — Яндекс: нашлось 2 млн результатов]]
- [[https://www.google.com/search?q=iperf+example][iperf example - Google Search]]
- [[https://iperf.fr/iperf-doc.php][iPerf - iPerf3 and iPerf2 user documentation]]
- [[https://openmaniak.com/iperf.php][IPERF - The Easy Tutorial]]
- [[http://netwild.ru/iperf/][Iperf. Что такое и как использовать. | Netwild.ru]]
- [[https://losst.ru/kak-polzovatsya-iperf][Как пользоваться iperf | Losst]]
- [[https://iperf.fr/][iPerf - The TCP, UDP and SCTP network bandwidth measurement tool]]
- [[https://www.google.com/search?hl=en&q=traffic%20shaping%20linux%20ssh%20%22tc%22%20reserve%20ssh][traffic shaping linux ssh "tc" reserve ssh - Google Search]]
- [[https://wiki.4psa.com/display/KB/How+to+prioritize+VoIP+traffic+in+the+network][How to prioritize VoIP traffic in the network - 4PSA Knowledge Base - 4PSA Wiki]]

* Packets

- [[https://github.com/netspooky/pdiff][netspooky/pdiff: Binary Protocol Differ]]
- [[https://loicpefferkorn.net/ipdecap/][Ipdecap: remove encapsulation from pcap packets]]
- [[https://github.com/projectdiscovery/nuclei][projectdiscovery/nuclei: Nuclei is a fast tool for configurable targeted scanning based on templates offering massive extensibility and ease of use.]]

- Find all clients connected to HTTP or HTTPS ports 
  : ss -o state established '( dport = :http or sport = :https )'

- Block all IPv4 addresses that has brute forcing our ssh server
  : for idiots in "$(cat /var/log/auth.log|grep invalid| grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b')"; do iptables -A INPUT -s "$idiots" -j DROP; done

* 

http://xmodulo.com/centos-bgp-router-quagga.html

https://www.tldp.org/HOWTO/BRIDGE-STP-HOWTO/set-up-the-bridge.html
https://lists.linuxfoundation.org/pipermail/bridge/2017-December/010832.html
https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking/

https://bugzilla.redhat.com/show_bug.cgi?id=542405
oleg@guixsd ~$ sudo sysctl  net.bridge.bridge-nf-call-arptables=0
net.bridge.bridge-nf-call-arptables = 0
oleg@guixsd ~$ sudo sysctl net.bridge.bridge-nf-call-iptables=0
net.bridge.bridge-nf-call-iptables = 0

** Misc
- [[https://github.com/IvanGlinkin/Host-enumeration][IvanGlinkin/Host-enumeration]]

* /etc/hosts

- [[https://github.com/txn2/txeh][txn2/txeh: Go library and CLI utility for /etc/hosts management.]]

* Monitoring
- [[https://github.com/ntop/ntopng][ntop/ntopng: Web-based Traffic and Security Network Traffic Monitoring]]

* Tools
- [[https://github.com/chiakge/Linux-NetSpeed][chiakge/Linux-NetSpeed: 将Linux现常用的网络加速集成在一起]]
- [[https://github.com/Ripolak/chk][Ripolak/chk: A small CLI tool to check connection from a local machine to a remote target in various protocols.]]

** WEB interface
- [[https://github.com/phpipam/phpipam][phpipam/phpipam: phpipam development repository]]

* [[file:bgp.org][BGP]]
** AS
 - [[https://github.com/stevenpack/asroute][stevenpack/asroute: Interpret traceroute output to show names of ASN traversed]]

* [[file:http.org][HTTP]]

* [[file:rsync.org][rsync]]

* [[file:smtp.org][SMTP]]

* [[file:proxy.org][Proxy]]

* Ping

  #+begin_src bash
    for ip in 10.0.0.{1..6}
    do
        if (timeout 1 ping -c 1 "$ip" &> /dev/null)
        then
            :
        else
            echo "$ip"
        fi
    done
  #+end_src

* Juniper/Cisco

[[https://it-wtf.com/juniper/juniper-cisco-commands/][Juniper/Cisco соответствие команд | IT-WTF?!]]

Команды Cisco 	Команды Juniper 	Описание
show run 	sh configuration 	Show running configuration
sh ver 	sh ver 	Show version
show ip interface brief 	show interface terse 	displays the status of interfaces configured for IP
show interface [intfc] 	show interfaces [intfc] detail 	displays the interface configuration, status and statistics.
show controller intfc 	show interfaces intfc extensive 	displays information about a physical port device
show interface | incl (proto|Desc) 	show interfaces description 	displays the interface configuration, status and statistics
show ip route 	show route 	displays summary information about entries in the routing table
show ip bgp summary 	show bgp summary 	displays the status of all Border Gateway Protocol (BGP) connections
show ip bgp net mask 	show route protocol bgp prefix 	will show you how that route is being advertised, look for the first line
show ip bgp net mask longer-prefixes 	show route range prefix 	will show you how that route is being advertised, look for the first line
show ip bgp regexp AS-regexp 	show route aspath-regexp “AS-regexp” 	displays routes matching the autonomous system (AS) path regular expression
show ip bgp neighbors neigh received-routes 	show route receive-protocol bgp neighshow route source-gateway neigh protocol bgp 	Shows whether a neighbor supports the route refresh capability
show ip bgp neighbor neigh advertised-routes 	show route advertising-protocol bgp neigh 	Shows whether a neighbor supports the route refresh capabilty
show clns neighbors 	show isis adjacency 	displays both ES and IS neighbors
show clns interface 	show isis interface 	shows specific information about each interface
show ip route isis 	show isis routes 	displays the current state of the the routing table
show isis topology 	show isis spf 	displays a list of all connected routers in all areas
show ip ospf interface 	show ospf neighbor 	shows neighbor ID, Priority, IP, & State if the neighbor router, dead time.
show ip ospf interface 	show ospf interface 	shows neighbor id, pri, state, dead time, address and interface
show ip route ospf 	show ospf route 	display the current state of the routing table
show ip ospf database 	show ospf database 	display list of information related to the OSPF database for a specific communication server
show version 	show version, show system uptime 	display the system hardware config., software version, and name and source of configuration files and boot images
show diags 	show chasis hardware 	displays power-on diagnostics status
show processes cpu 	show system process 	displays utilization statistics
show tech-support 	request support info 	displays the current software image, configuration, controllers, counters, stacks, interfaces, memory and buffers
show logging 	show log messages 	display the state of logging to the syslog
show route-map name 	show policy name 	displayall route-maps configured or only the one specified
show ip prefix-list name 	show policy name 	display information about a prefix list or prefix list entries
show ip community-list list 	configure,
show policy-options community name 	display routes that are permitted by BGP community list
show environment all 	show chassis environment 	displays temperature and voltage information on the console
ping dest 	ping dest rapid (for cisco like output)
ping dest (for unix like output) 	to check to see if a destination is alive
ping (setting source int) 	ping dest bypass-routing 	to check to see if a destination is alive
terminal monitor 	monitor start messages 	Change console terminal settings
terminal no monitor 	monitor stop 	Change console terminal settings
terminal length 0 	set cli screen-length 0 	sets the length for displaying command output
