#+TITLE: notes

* Tasks
** TODO Arch packaging tutorial on irc
   [2016-12-03 Sat]
   [[gnus:INBOX#91dac71e-4a12-4306-8f99-74ec6cd32167@dev.null.invalid][Email to go wigust: Any programmers here who don't]]
** TODO Watch Red Hat webinar
   [2016-12-03 Sat]
   [[gnus:INBOX#ff3304$ddjdj@smtp.theonlinexpo.com][Email from Red Hat Webcasts: Daily development with Docker,]]

* Notes
** Note read a book PAM Mastery by Michael W Lucas
 <2016-12-13 Tue 01:46>
** Note Checkout Unmark do something with your bookmarks 
 <2016-12-13 Tue 03:56>
** Note karboon                                              :drawing:vector: 
 <2016-12-13 Tue 04:08>
** Note Kodi announce official plex addon         :kodi:plex:addons:official: 
 <2016-12-13 Tue 04:42>
** Note linux enter group without logout ~newgrp~  :linux:group:enter:logout: 
 <2016-12-13 Tue 08:18>
** Note Find and Install missing build dependencies as found in debian/control                         :debian:develop:packaging:source:building: 
 <2016-12-13 Tue 12:55>
#+BEGIN_SRC bash
sudo mk-build-deps --install --remove
#+END_SRC
** Note Change token gitsome and ssh key       :security:token:github:update: 
 <2016-12-13 Tue 14:28>
** Note На сайте и на 2 этаде у диспетчерской в конце декабря появится наше расписание занятий :university:shedule: 
 <2016-12-30 Fri 20:57>
** Note use maybe                  :python:utilities:file:try:execute:github: 
 <2016-12-13 Tue 23:02>
[[https://github.com/p-e-w/maybe][p-e-w/maybe: :rabbit2: See what a program does before deciding whether you really want it to happen.]]
#+BEGIN_QUOTE
See what a program does before deciding whether you really want it to happen.
#+END_QUOTE
** Adblocking [[https://github.com/StevenBlack/hosts][StevenBlack/hosts]]                             :python:hosts:adblock:github: 
 <2016-12-14 Wed 00:34>
#+BEGIN_QUOTE
Extending and consolidating hosts files from a variety of sources like
adaway.org, mvps.org, malwaredomainlist.com, someonewhocares.org, yoyo.org, and
potentially others. You can optionally invoke extensions to block additional
sites by category.
#+END_QUOTE
** [[https://www.getlektor.com/][lektor]] static site generator with cms:python:static:site:generator:lector:github:top:cms: 
 <2016-12-14 Wed 00:49>
** [[https://github.com/etsy/logster][logster]] parse log files                 :python:system:log:metrics:parser: 
 <2016-12-14 Wed 00:51>
  Parse log files, generate metrics for Graphite and Ganglia
** [[https://github.com/micahflee/onionshare/blob/master/README.md][onionshare/README.md at master · micahflee/onionshare]] :onion:python:share:files:tor:github: 
 <2016-12-14 Wed 00:53>
 OnionShare lets you securely and anonymously share files of any size. It works by starting a web server, making it accessible as a Tor onion service, and generating an unguessable URL to access and download the files. It doesn't require setting up a server on the internet somewhere or using a third party filesharing service. You host the file on your own computer and use a Tor onion service to make it temporarily accessible over the internet. The other user just needs to use Tor Browser to download the file from you.

 Features include:

     A user-friendly drag-and-drop graphical user interface that works in Windows, Mac OS X, and Linux
     Ability to share multiple files and folders at once
     Support for multiple people downloading files at once
     Automatically copies the unguessable URL to your clipboard
     Shows you the progress of file transfers
     When file is done transferring, automatically closes OnionShare to reduce the attack surface
     Localized into several languages, and supports international unicode filenames

 If you're interested in exactly what OnionShare does and does not protect against, read the Security Design Document.
** [[https://github.com/maebert/jrnl#jrnl----][maebert/jrnl: A simple command line journal application that stores your journal in a plain text file.]]                                             :python:journal:github:top: 
 <2016-12-14 Wed 00:56>
 jrnl Build Status Downloads Version

 For news on updates or to get help, read the docs, follow @maebert or submit an issue on Github.

 jrnl is a simple journal application for your command line. Journals are stored as human readable plain text files - you can put them into a Dropbox folder for instant syncing and you can be assured that your journal will still be readable in 2050, when all your fancy iPad journal applications will long be forgotten.

 jrnl also plays nice with the fabulous DayOne and can read and write directly from and to DayOne Journals.

 Optionally, your journal can be encrypted using the 256-bit AES.
 Why keep a journal?

 Journals aren't only for 13-year old girls and people who have too much time on their summer vacation. A journal helps you to keep track of the things you get done and how you did them. Your imagination may be limitless, but your memory isn't. For personal use, make it a good habit to write at least 20 words a day. Just to reflect what made this day special, why you haven't wasted it. For professional use, consider a text-based journal to be the perfect complement to your GTD todo list - a documentation of what and how you've done it.
