#+TITLE: notes

* Tasks
** TODO Arch packaging tutorial on irc
   [2016-12-03 Sat]
   [[gnus:INBOX#91dac71e-4a12-4306-8f99-74ec6cd32167@dev.null.invalid][Email to go wigust: Any programmers here who don't]]
** TODO Watch Red Hat webinar
   [2016-12-03 Sat]
   [[gnus:INBOX#ff3304$ddjdj@smtp.theonlinexpo.com][Email from Red Hat Webcasts: Daily development with Docker,]]

* Notes
** Note read a book PAM Mastery by Michael W Lucas
 <2016-12-13 Tue 01:46>
** Note Checkout Unmark do something with your bookmarks 
 <2016-12-13 Tue 03:56>
** Note karboon                                              :drawing:vector: 
 <2016-12-13 Tue 04:08>
** Note Kodi announce official plex addon         :kodi:plex:addons:official: 
 <2016-12-13 Tue 04:42>
** Note linux enter group without logout ~newgrp~  :linux:group:enter:logout: 
 <2016-12-13 Tue 08:18>
** Note Find and Install missing build dependencies as found in debian/control                         :debian:develop:packaging:source:building: 
 <2016-12-13 Tue 12:55>
#+BEGIN_SRC bash
sudo mk-build-deps --install --remove
#+END_SRC
** Note Change token gitsome and ssh key       :security:token:github:update: 
 <2016-12-13 Tue 14:28>
** Note На сайте и на 2 этаде у диспетчерской в конце декабря появится наше расписание занятий :university:shedule: 
 <2016-12-30 Fri 20:57>
** Note use maybe                  :python:utilities:file:try:execute:github: 
 <2016-12-13 Tue 23:02>
[[https://github.com/p-e-w/maybe][p-e-w/maybe: :rabbit2: See what a program does before deciding whether you really want it to happen.]]
#+BEGIN_QUOTE
See what a program does before deciding whether you really want it to happen.
#+END_QUOTE
** Adblocking [[https://github.com/StevenBlack/hosts][StevenBlack/hosts]]                             :python:hosts:adblock:github: 
 <2016-12-14 Wed 00:34>
#+BEGIN_QUOTE
Extending and consolidating hosts files from a variety of sources like
adaway.org, mvps.org, malwaredomainlist.com, someonewhocares.org, yoyo.org, and
potentially others. You can optionally invoke extensions to block additional
sites by category.
#+END_QUOTE
** [[https://www.getlektor.com/][lektor]] static site generator with cms:python:static:site:generator:lector:github:top:cms: 
 <2016-12-14 Wed 00:49>
** [[https://github.com/etsy/logster][logster]] parse log files                 :python:system:log:metrics:parser: 
 <2016-12-14 Wed 00:51>
  Parse log files, generate metrics for Graphite and Ganglia
** [[https://github.com/micahflee/onionshare/blob/master/README.md][onionshare/README.md at master · micahflee/onionshare]] :onion:python:share:files:tor:github: 
 <2016-12-14 Wed 00:53>
 OnionShare lets you securely and anonymously share files of any size. It works by starting a web server, making it accessible as a Tor onion service, and generating an unguessable URL to access and download the files. It doesn't require setting up a server on the internet somewhere or using a third party filesharing service. You host the file on your own computer and use a Tor onion service to make it temporarily accessible over the internet. The other user just needs to use Tor Browser to download the file from you.

 Features include:

     A user-friendly drag-and-drop graphical user interface that works in Windows, Mac OS X, and Linux
     Ability to share multiple files and folders at once
     Support for multiple people downloading files at once
     Automatically copies the unguessable URL to your clipboard
     Shows you the progress of file transfers
     When file is done transferring, automatically closes OnionShare to reduce the attack surface
     Localized into several languages, and supports international unicode filenames

 If you're interested in exactly what OnionShare does and does not protect against, read the Security Design Document.
** [[https://github.com/maebert/jrnl#jrnl----][maebert/jrnl: A simple command line journal application that stores your journal in a plain text file.]]                                             :python:journal:github:top: 
 <2016-12-14 Wed 00:56>
 jrnl Build Status Downloads Version

 For news on updates or to get help, read the docs, follow @maebert or submit an issue on Github.

 jrnl is a simple journal application for your command line. Journals are stored as human readable plain text files - you can put them into a Dropbox folder for instant syncing and you can be assured that your journal will still be readable in 2050, when all your fancy iPad journal applications will long be forgotten.

 jrnl also plays nice with the fabulous DayOne and can read and write directly from and to DayOne Journals.

 Optionally, your journal can be encrypted using the 256-bit AES.
 Why keep a journal?

 Journals aren't only for 13-year old girls and people who have too much time on their summer vacation. A journal helps you to keep track of the things you get done and how you did them. Your imagination may be limitless, but your memory isn't. For personal use, make it a good habit to write at least 20 words a day. Just to reflect what made this day special, why you haven't wasted it. For professional use, consider a text-based journal to be the perfect complement to your GTD todo list - a documentation of what and how you've done it.
** [[https://github.com/PressLabs/gitfs][PressLabs/gitfs: Version controlled file system]]                                      :python:git:filesystem:github:top: 
 <2016-12-14 Wed 00:59>
 gitfs Build Status Coverage Status
 Welcome to GitFS

 gitfs is a FUSE file system that fully integrates with git. You can mount a remote repository's branch locally, and any subsequent changes made to the files will be automatically committed to the remote.
 What's its purpose?

 gitfs was designed to bring the full powers of git to everyone, no matter how little they know about versioning. A user can mount any repository and all the his changes will be automatically converted into commits. gitfs will also expose the history of the branch you're currently working on by simulating snapshots of every commit.

 gitfs is useful in places where you want to keep track of all your files, but at the same time you don't have the possibility of organizing everything into commits yourself. A FUSE filesystem for git repositories, with local cache
 Features

     Automatically commits changes: create, delete, update files and their metadata
     Browse through working index and commit history
     Merges with upstream by automatically accepting local changes
     Caching commits reduces the memory footprint and speeds up navigation
     Reduces the number of pushes by batching commits
** [[https://github.com/apenwarr/sshuttle][apenwarr/sshuttle: Transparent proxy server that works as a poor man's VPN. Forwards over ssh. Doesn't require admin. Works with Linux and MacOS. Supports DNS tunneling.]]                                  :python:github:top:ssh:vpn:proxy:easy: 
 <2016-12-14 Wed 06:49>
  Transparent proxy server that works as a poor man's VPN. Forwards over ssh. Doesn't require admin. Works with Linux and MacOS. Supports DNS tunneling.
** [[https://github.com/jkbrzt/httpie][jkbrzt/httpie: Modern command line HTTP client — user-friendly curl alternative with intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc. Follow https://twitter.com/CLIHTTP for tips and updates.]]                                         :python:github:top:http:client: 
 <2016-12-14 Wed 06:50>
 HTTPie: a CLI, cURL-like tool for humans

 HTTPie (pronounced aitch-tee-tee-pie) is a command line HTTP client. Its goal is to make CLI interaction with web services as human-friendly as possible. It provides a simple http command that allows for sending arbitrary HTTP requests using a simple and natural syntax, and displays colorized output. HTTPie can be used for testing, debugging, and generally interacting with HTTP servers.
** [[https://github.com/kennethreitz/requests][kennethreitz/requests: Python HTTP Requests for Humans™]]                             :python:github:top:http:request:human:easy: 
 <2016-12-14 Wed 06:51>
 Requests is the only Non-GMO HTTP library for Python, safe for human consumption.

 Warning: Recreational use of other HTTP libraries may result in dangerous side-effects, including: security vulnerabilities, verbose code, reinventing the wheel, constantly reading documentation, depression, headaches, or even death.
** [[https://github.com/donnemartin/data-science-ipython-notebooks][donnemartin/data-science-ipython-notebooks: Continually updated data science Python notebooks: Deep learning (TensorFlow, Theano, Caffe), scikit-learn, Kaggle, big data (Spark, Hadoop MapReduce, HDFS), matplotlib, pandas, NumPy, SciPy, Python essentials, AWS, and various command lines.]]                                        :python:github:top:data:science: 
 <2016-12-14 Wed 06:51>
  Continually updated data science Python notebooks: Deep learning (TensorFlow, Theano, Caffe), scikit-learn, Kaggle, big data (Spark, Hadoop MapReduce, HDFS), matplotlib, pandas, NumPy, SciPy, Python essentials, AWS, and various command lines.
** [[https://github.com/nvbn/thefuck][nvbn/thefuck: Magnificent app which corrects your previous console command.]]                  :python:github:top:shell:completion:fix:correct:spell: 
 <2016-12-14 Wed 06:52>
 Magnificent app which corrects your previous console command, inspired by a @liamosaur tweet.
** [[https://github.com/faif/python-patterns][faif/python-patterns: A collection of design patterns/idioms in Python]]                          :python:github:top:patterns:study:programming: 
 <2016-12-14 Wed 06:55>
 python-patterns

 A collection of design patterns and idioms in Python.

 When an implementation is added or modified, be sure to update this file and rerun append_output.sh (eg. ./append_output.sh borg.py) to keep the output comments at the bottom up to date.
** [[https://github.com/fchollet/keras][fchollet/keras: Deep Learning library for Python. Convnets, recurrent neural networks, and more. Runs on Theano or TensorFlow.]]                                       :python:github:top:deep:learning: 
 <2016-12-14 Wed 06:56>
 You have just found Keras.

 Keras is a high-level neural networks library, written in Python and capable of running on top of either TensorFlow or Theano. It was developed with a focus on enabling fast experimentation. Being able to go from idea to result with the least possible delay is key to doing good research.

 Use Keras if you need a deep learning library that:

     Allows for easy and fast prototyping (through total modularity, minimalism, and extensibility).
     Supports both convolutional networks and recurrent networks, as well as combinations of the two.
     Supports arbitrary connectivity schemes (including multi-input and multi-output training).
     Runs seamlessly on CPU and GPU.

 Read the documentation at Keras.io.

 Keras is compatible with: Python 2.7-3.5.
** [[https://github.com/jonathanslenders/python-prompt-toolkit][jonathanslenders/python-prompt-toolkit: Library for building powerful interactive command lines in Python]]                   :python:github:top:commandline:cli:build:programming: 
 <2016-12-14 Wed 06:59>

 prompt_toolkit is a library for building powerful interactive command lines and terminal applications in Python.

 Read the documentation on readthedocs.
** [[https://github.com/binux/pyspider][binux/pyspider: A Powerful Spider(Web Crawler) System in Python.]]                                          :python:github:top:spider:web: 
 <2016-12-14 Wed 07:00>

 A Powerful Spider(Web Crawler) System in Python. TRY IT NOW!

     Write script in Python
     Powerful WebUI with script editor, task monitor, project manager and result viewer
     MySQL, MongoDB, Redis, SQLite, Elasticsearch; PostgreSQL with SQLAlchemy as database backend
     RabbitMQ, Beanstalk, Redis and Kombu as message queue
     Task priority, retry, periodical, recrawl by age, etc...
     Distributed architecture, Crawl Javascript pages, Python 2&3, etc...

 Tutorial: http://docs.pyspider.org/en/latest/tutorial/
 Documentation: http://docs.pyspider.org/
 Release notes: https://github.com/binux/pyspider/releases
** [[https://github.com/soimort/you-get][soimort/you-get: Dumb downloader that scrapes the web]]                       :python:github:top:downloader:scrape:web:youtube: 
 <2016-12-14 Wed 07:17>

 You-Get is a tiny command-line utility to download media contents (videos, audios, images) from the Web, in case there is no other handy way to do it.

 Here's how you use you-get to download a video from this web page:

 $ you-get http://www.fsf.org/blogs/rms/20140407-geneva-tedx-talk-free-software-free-society
 Site:       fsf.org
 Title:      TEDxGE2014_Stallman05_LQ
 Type:       WebM video (video/webm)
 Size:       27.12 MiB (28435804 Bytes)

 Downloading TEDxGE2014_Stallman05_LQ.webm ...
 100.0% ( 27.1/27.1 MB) ├████████████████████████████████████████┤[0/0]   12 MB/s

 And here's why you might want to use it:

     You enjoyed something on the Internet, and just want to download them for your own pleasure.
     You watch your favorite videos online from your computer, but you are prohibited from saving them. You feel that you have no control over your own computer. (And it's not how an open Web is supposed to work.)
     You want to get rid of any closed-source technology or proprietary JavaScript code, and disallow things like Flash running on your computer.
     You are an adherent of hacker culture and free software.

 What you-get can do for you:

     Download videos / audios from popular websites such as YouTube, Youku, Niconico, and a bunch more. (See the full list of supported sites)
     Stream an online video in your media player. No web browser, no more ads.
     Download images (of interest) by scraping a web page.
     Download arbitrary non-HTML contents, i.e., binary files.

 Interested? Install it now and get started by examples.

 Are you a Python programmer? Then check out the source and fork it!
** [[https://github.com/miguelgrinberg/flasky][miguelgrinberg/flasky: Companion code to my O'Reilly book "Flask Web Development".]]                                         :python:github:top:flasky:book: 
 <2016-12-14 Wed 07:18>

 Flasky

 This repository contains the source code examples for my O'Reilly book Flask Web Development.

 The commits and tags in this repository were carefully created to match the sequence in which concepts are presented in the book. Please read the section titled "How to Work with the Example Code" in the book's preface for instructions.
** [[https://github.com/alexjc/neural-doodle][alexjc/neural-doodle: Turn your two-bit doodles into fine artworks with deep neural networks, generate seamless textures from photos, transfer style from one image to another, perform example-based upscaling, but wait... there's more! (An implementation of Semantic Style Transfer.)]]                             :python:github:top:neural:image:drawing:ia: 
 <2016-12-14 Wed 07:19>

 Use a deep neural network to borrow the skills of real artists and turn your two-bit doodles into masterpieces! This project is an implementation of Semantic Style Transfer (Champandard, 2016), based on the Neural Patches algorithm (Li, 2016). Read more about the motivation in this in-depth article and watch this workflow video for inspiration.

 The doodle.py script generates a new image by using one, two, three or four images as inputs depending what you're trying to do: the original style and its annotation, and a target content image (optional) with its annotation (a.k.a. your doodle). The algorithm extracts annotated patches from the style image, and incrementally transfers them over to the target image based on how closely they match.

 NOTE: Making a #NeuralDoodle is a skill. The parameters in the script were adjusted to work well by default and with the examples below. For new images, you may need to adjust values and modify on your input data too. It takes practice, but you can reach almost photo-realistic results if you iterate! (Ask for advice here or see examples.)
** [[https://github.com/toastdriven/restless][toastdriven/restless: A lightweight REST miniframework for Python.]]                                            :python:github:top:rest:api: 
 <2016-12-14 Wed 07:20>

 A lightweight REST miniframework for Python.

 Documentation is at http://restless.readthedocs.org/.

 Works great with Django, Flask, Pyramid, Tornado & Itty, but should be useful for many other Python web frameworks. Based on the lessons learned from Tastypie & other REST libraries.
 Features

     Small, fast codebase
     JSON output by default, but overridable
     RESTful
     Python 3.2+ (with shims to make broke-ass Python 2.6+ work)
     Flexible

 Anti-Features

 (Things that will never be added...)

     Automatic ORM integration
     Authorization (per-object or not)
     Extensive filtering options
     XML output (though you can implement your own)
     Metaclasses
     Mixins
     HATEOAS

 Why?

 Quite simply, I care about creating flexible & RESTFul APIs. In building Tastypie, I tried to create something extremely complete & comprehensive. The result was writing a lot of hook methods (for easy extensibility) & a lot of (perceived) bloat, as I tried to accommodate for everything people might want/need in a flexible/overridable manner.

 But in reality, all I really ever personally want are the RESTful verbs, JSON serialization & the ability of override behavior.

 This one is written for me, but maybe it's useful to you.
** [[https://github.com/coleifer/peewee][coleifer/peewee: a small, expressive orm -- supports postgresql, mysql and sqlite]]                    :python:github:top:database:mysql:sqlite:postgresql: 
 <2016-12-14 Wed 07:20>

 Peewee is a simple and small ORM. It has few (but expressive) concepts, making it easy to learn and intuitive to use.

     A small, expressive ORM
     Written in python with support for versions 2.6+ and 3.2+.
     built-in support for sqlite, mysql and postgresql
     tons of extensions available in the playhouse
         Postgresql HStore, JSON, arrays and more
         SQLite full-text search, user-defined functions, virtual tables and more
         Schema migrations and model code generator
         Connection pool
         Encryption
         and much, much more...
** [[https://github.com/nvie/rq][nvie/rq: Simple job queues for Python]]                            :python:github:top:job:processing:multitask: 
 <2016-12-14 Wed 07:21>

 RQ (Redis Queue) is a simple Python library for queueing jobs and processing them in the background with workers. It is backed by Redis and it is designed to have a low barrier to entry. It should be integrated in your web stack easily.

 RQ requires Redis >= 2.7.0.
** [[https://github.com/nicolargo/glances][nicolargo/glances: Glances an Eye on your system. A top/htop alternative.]]                                         :python:github:top:system:info: 
 <2016-12-14 Wed 07:22>

 Follow Glances on Twitter: @nicolargo or @glances_system

 Glances is a cross-platform curses-based system monitoring tool written in Python.
