#+TITLE: How to get emails fast in Linux with offlineimap on the command line
#+BEAMER_HEADER: \subtitle{Read/sync your IMAP mailboxes [Python]}
#+BEAMER_HEADER: \institute[INST]{whyfree.gitlab.io}
#+AUTHOR: Oleg Pykhalov
#+EMAIL: go.wigust@gmail.com
#+OPTIONS: author:nil date:nil toc:nil
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+LATEX_CLASS_OPTIONS: [aspectratio=169]

* Description
#+BEGIN_QUOTE
OfflineIMAP is software that downloads your email mailbox(es) as local Maildirs.
OfflineIMAP will synchronize both sides via IMAP.

IMAP's main downside is that you have to trust your email provider to not lose
your email. While certainly unlikely, it's not impossible. With OfflineIMAP, you
can download your Mailboxes and make you own backups of your Maildir.

This allows reading your email offline without the need for your mail reader
(MUA) to support IMAP operations. Need an attachment from a message without
internet connection? No problem, the message is still there.
#+END_QUOTE

Why should I use OfflineIMAP?
- fast
- reliable
- flexible
- safe

* Installation
You should first check if your distribution already packages OfflineIMAP for
you.

** Arch
#+BEGIN_SRC bash
  sudo pacman -S offlineimap
#+END_SRC

** Debian/Ubuntu
#+BEGIN_SRC bash
  sudo apt install offlineimap
#+END_SRC

** Fedora
#+BEGIN_SRC bash
  sudo dnf install offlineimap
#+END_SRC

* Configuration
** Official example
Depending on your distribution offlineimap you can check offlineimap.conf example.
On arch it's located in: /usr/share/offlineimap/offlineimap.conf

** Example
#+BEGIN_EXAMPLE
  # Offlineimap configuration file
  # More details can be found at http://www.offlineimap.org

  ##################################################
  # General definitions
  ##################################################

  [general]

  accounts = Gmail, Yandex
  maxsyncaccounts = 2

  socktimeout = 120

  ##################################################
  # Accounts
  ##################################################

  [Account Gmail]

  localrepository = GmailLocal
  remoterepository = GmailRemote
  status_backend = sqlite
  autorefresh = 0.5
  quick = 10
  synclabels = yes

  [Account Yandex]
  localrepository = YandexLocal
  remoterepository = YandexRemote
  status_backend = sqlite
  autorefresh = 0.5
  quick = 10

  [Repository YandexLocal]
  type = Maildir
  localfolders = ~/Mail/Yandex

  [Repository GmailLocal]
  type = GmailMaildir
  localfolders = ~/Mail/Gmail

  [Repository GmailRemote]

  # Instead of closing the connection once a sync is complete, offlineimap will
  # send empty data to the server to hold the connection open. A value of 60
  # attempts to hold the connection for a minute between syncs (both quick and
  # autorefresh).This setting has no effect if autorefresh and holdconnectionopen
  # are not both set.
  keepalive = 60

  # OfflineIMAP normally closes IMAP server connections between refreshes if
  # the global option autorefresh is specified.  If you wish it to keep the
  # connection open, set this to true. This setting has no effect if autorefresh
  # is not set.
  holdconnectionopen = yes

  keepalive = 60
  type = IMAP
  remotehost = imap.gmail.com
  remoteuser = <USER>@gmail.com
  ssl = yes
  maxconnections = 1
  realdelete = no
  folderfilter = lambda foldername: foldername in ['INBOX']
  sslcacertfile = /etc/ssl/certs/ca-certificates.crt
  auth_mechanisms = LOGIN

  [Repository YandexRemote]
  localfolders = ~/Mail/Yandex
  #
  # Instead of closing the connection once a sync is complete, offlineimap will
  # send empty data to the server to hold the connection open. A value of 60
  # attempts to hold the connection for a minute between syncs (both quick and
  # autorefresh).This setting has no effect if autorefresh and holdconnectionopen
  # are not both set.
  #
  keepalive = 60
  #
  # OfflineIMAP normally closes IMAP server connections between refreshes if
  # the global option autorefresh is specified.  If you wish it to keep the
  # connection open, set this to true. This setting has no effect if autorefresh
  # is not set.
  #
  holdconnectionopen = yes
  #
  keepalive = 60
  type = IMAP
  remotehost = imap.yandex.com
  remoteuser = <USER>@yandex.ru
  ssl = yes
  maxconnections = 1
  realdelete = no
  folderfilter = lambda foldername: foldername in ['INBOX']
  sslcacertfile = /etc/ssl/certs/ca-certificates.crt
  auth_mechanisms = LOGIN
#+END_EXAMPLE

* See also
- [[https://github.com/OfflineIMAP/offlineimap][offlineimap - Github repository]]
- [[http://www.offlineimap.org/][offlineimap - Community Website]]
- [[http://github.com/OfflineIMAP/offlineimap/wiki][offlineimap - Wiki]]
