#+TITLE: How to get emails fast in Linux with offlineimap on the command line
#+BEAMER_HEADER: \subtitle{Read/sync your IMAP mailboxes [Python]}
#+BEAMER_HEADER: \institute[INST]{whyfree.gitlab.io}
#+AUTHOR: Oleg Pykhalov
#+EMAIL: go.wigust@gmail.com
#+OPTIONS: author:nil date:nil toc:nil
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+LATEX_CLASS_OPTIONS: [aspectratio=169]

* Description
#+BEGIN_QUOTE
OfflineIMAP is software that downloads your email mailbox(es) as local Maildirs.
OfflineIMAP will synchronize both sides via IMAP.

IMAP's main downside is that you have to trust your email provider to not lose
your email. While certainly unlikely, it's not impossible. With OfflineIMAP, you
can download your Mailboxes and make you own backups of your Maildir.

This allows reading your email offline without the need for your mail reader
(MUA) to support IMAP operations. Need an attachment from a message without
internet connection? No problem, the message is still there.
#+END_QUOTE

** Why should I use OfflineIMAP?
- fast
- reliable
- flexible
- safe

* Installation
You should first check if your distribution already packages OfflineIMAP for
you.

** Arch
#+BEGIN_SRC bash
  sudo pacman -S offlineimap
#+END_SRC

** Debian/Ubuntu
#+BEGIN_SRC bash
  sudo apt install offlineimap
#+END_SRC

** Fedora
#+BEGIN_SRC bash
  sudo dnf install offlineimap
#+END_SRC

* See also
- [[https://github.com/OfflineIMAP/offlineimap][offlineimap - Github repository]]
- [[http://www.offlineimap.org/][offlineimap - Community Website]]
- [[http://github.com/OfflineIMAP/offlineimap/wiki][offlineimap - Wiki]]
