#+TITLE: opensource software
#+DATE: 2016-11-11
#+PROPERTY: TAGS oss
#+OPTIONS: toc:nil

* sshpt

Execute command and upload files to many servers simultaneosly via SSH *without*
using pre-shared keys.

* Gruik

- [[https://www.google.ru/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjovqXy4pjQAhUFDiwKHTG7BOkQFggdMAA&url=http%3A%2F%2Fgruik.io%2F&usg=AFQjCNHTRo760XCUpWSOv50hydS-cFimTQ&sig2=d9JjsbIz978qZRYMtdqGtQ][Gruik.]]

Note taking service.

* Less Pass

- [[https://lesspass.com/#/][LessPass]]

Next-gen open source password manager

* PDFtkServer

- [[https://www.pdflabs.com/tools/pdftk-server/][PDFtk Server]]

* Paperwork

- [[http://paperwork.rocks/][Paperwork by twostairs]]

* Kodi

- [[https://torrentfreak.com/pirate-kodi-add-ons-gain-massive-popularity-161007/][Pirate Kodi Add-Ons Gain Massive Popularity - TorrentFreak]]
* netdata

- [[https://github.com/firehol/netdata][firehol/netdata: Real-time performance monitoring, done right!]]

netdata is a system for distributed real-time performance and health monitoring.
It provides unparalleled insights, in real-time, of everything happening on the
system it runs (including applications such as web, or database servers), using
modern interactive web dashboards.

netdata is fast and efficient, designed to permanently run on all systems
(physical & virtual servers, containers, IoT devices), without disrupting their
core function.

* sentry

- [[https://github.com/getsentry/sentry][getsentry/sentry: Sentry is cross-platform crash reporting built with love]]

Sentry is a modern error logging and aggregation platform.

* Python

** Python cheatsheet

- [[https://github.com/crazyguitar/pysheeet][crazyguitar/pysheeet: Python Cheatsheet]]
- [[https://github.com/tartley/python-regex-cheatsheet][tartley/python-regex-cheatsheet: Python 2.7 Regular Expression cheatsheet, as a restructured text document and Makefile to convert it to PDF]]

* C language

** C language cheatsheet

- [[https://github.com/cirosantilli/cpp-cheat][cirosantilli/cpp-cheat: C and C++ minimal examples. Asserts used wherever possible. Hello worlds for cool third party libraries. Cheatsheets, tutorials and mini-projects.]]

* GitHub

** Trending

- [[https://github.com/josephyzhou/github-trending][josephyzhou/github-trending: Tracking the most popular Github repos, updated daily]]
- [[https://github.com/devfreebooks/devfreebooks.github.io][devfreebooks/devfreebooks.github.io: A huge collection of free books for developers]]
- [[https://github.com/trending/python][Trending Python repositories on GitHub today]]

** Showcases

- [[https://github.com/showcases/devops-tools][DevOps tools]]
- [[https://github.com/showcases/web-application-frameworks][Web application frameworks]]
- [[https://github.com/showcases/projects-that-power-github][Projects that power GitHub]]
- [[https://github.com/showcases/github-browser-extensions][GitHub Browser Extensions]]
- [[https://github.com/showcases/open-data][Open data]]
- [[https://github.com/showcases/text-editors][Text editors]]
- [[https://github.com/showcases/package-managers][Package managers]]
- [[https://github.com/showcases/clean-code-linters][Clean code linters]]
- [[https://github.com/showcases/github-pages-examples][GitHub Pages examples]]
- [[https://github.com/showcases/javascript-game-engines][JavaScript game engines]]
- [[https://github.com/showcases/web-games][Web games]]
- [[https://github.com/showcases/music][Music]]
- [[https://github.com/showcases/open-source-organizations][Open source organizations]]
- [[https://github.com/showcases/video-tools][Video tools]]
- [[https://github.com/showcases/science][Science]]
- [[https://github.com/showcases/projects-with-great-wikis][Projects with great wikis]]
- [[https://github.com/showcases/writing][Writing]]
- [[https://github.com/showcases/software-development-tools][Software development tools]]
- [[https://github.com/showcases/nosql-databases][NoSQL databases]]
- [[https://github.com/showcases/3d-modeling][3D modeling]]

* tmux

- [[https://github.com/tony/tmuxp][tony/tmuxp: tmux session manager built on libtmux]]

* Programming books

- [[https://github.com/vhf/free-programming-books][vhf/free-programming-books: Freely available programming books]]

* Google

- [[https://github.com/jwasham/google-interview-university#unix-command-line-tools][jwasham/google-interview-university: A complete daily plan for studying to become a Google software engineer.]]

* Webinars

- [[http://openssource.biz/][Openssource - халява, ежедневные раздачи, курсы по заработку, сливы, схемы заработка]]
- [[http://www.intuit.ru/][Национальный Открытый Университет "ИНТУИТ" | Бесплатное образование]]
- [[https://www.coursera.org/][Coursera | Online Courses From Top Universities. Join for Free]]

* Video

** Channels

- [[https://www.youtube.com/user/OfficeGarageSeries/featured][Microsoft Mechanics - YouTube]]
- [[https://www.youtube.com/channel/UC9F5SkQPgG1besItGOVkz0A][linuxgamecast]]
- [[https://www.youtube.com/channel/UCgueVZWcSz3L_7Yn4UdO1HQ][Your Cloud]]

* Android

** Software

- [[https://play.google.com/store/apps/details?id=com.icechen1.speechjammer&referrer=utm_source%3Dappgratis][SpeechJammer - Android Apps on Google Play]]

* Gnome

** Themes

- [[https://www.linux-apps.com/p/1136805/][xdgurl - www.linux-apps.com]]

* Ratings

** Alexa

- [[http://www.alexa.com/topsites/category/Top/Computers/Open_Source][Alexa - Top Sites by Category: Computers/Open Source]]

* Network

** Calc

- [[http://jodies.de/ipcalc][IP Calculator / IP Subnetting]]

* Math

- [[http://planetmath.org/][planetmath.org | Math for the people, by the people.]]

* Conferences

** Lists

- [[http://www.alexa.com/topsites/category/Top/Computers/Open_Source/Conferences][Alexa - Top Sites by Category: Computers/Open Source/Conferences]]
- [[https://fosdem.org/2017/][FOSDEM 2017 - Home]]
- [[http://www.socallinuxexpo.org/scale/15x/][Save the Date | SCALE 15x]]

** Alexa

*** 1

[[http://En.wikipedia.org]]
A free encyclopedia built collaboratively using wiki software. (Creative Commons Attribution-Sh…More

*** 2

[[https://github.com/]]
GitHub is the best place to share code with friends, co-workers, classmates, and complete stran…More

*** 3

[[https://www.mozilla.org/]]
Official website with information and downloads.

*** 4

[[http://Sourceforge.net]]
Resources for open-source developers and a directory of in-development open-source software.

*** 5

[[http://Apache.org]]
Supports the development of a number of open-source software projects, including the Apache web…More

*** 6

[[http://Codeplex.com]]
Free open source project hosting from Microsoft. It provides a source code repository with acce…More

*** 7

[[https://addons.mozilla.org/]]
Official site for extensions and themes for Mozilla Products, including Firefox, Thunderbird, a…More

*** 8

[[http://Slashdot.org]]
Source for technology related news with a heavy slant towards Linux and Open Source issues.

*** 9

[[http://Https://launchpad.net/]]
Free open source project hosting. Repository based on the Bazaar VCS.

*** 10

[[http://Notepad-plus-plus.org]]
Editor with tabbed interface, configurable syntax highlighting, syntax folding, line numbering,…More

*** 11

[[http://Portableapps.com]]
PortableApps.com is the world's most popular portable software solution allowing you to ta…More

*** 12

[[http://Nginx.org]]
A HTTP and mail proxy server licensed under a 2-clause BSD-like license. By Igor Sysoev. [Unix,…More

*** 13

[[http://Https://about.gitlab.com/]]
Provides Git repository management, code reviews, issue tracking, activity feeds and wikis. Git…More

*** 14

[[http://Zabbix.com]]
Software for application and network monitoring - logging, monitoring, capacity planning, avail…More

*** 15

[[http://Wikimediafoundation.org]]
International non-profit organization dedicated to encouraging the growth and development of fr…More

*** 16

[[http://Mozillazine.org]]
General information on the Open Source Netscape project.

*** 17

[[http://Curl.haxx.se]]
A tool and a library (usable from many languages) for client-side URL transfers, supporting FTP…More

*** 18

[[http://Musescore.org]]
Music composition and notation software. Site includes downloads, screenshots, manual, forum, a…More

*** 19

[[http://Https://bugzilla.mozilla.org/]]
The Mozilla bug database. Search for reported bugs, and report new ones in Mozilla products.

*** 20

[[http://Osdir.com]]
Provides news of the essential new releases and has a directory section where mature open sourc…More

*** 21

[[http://Linuxfoundation.org]]
A non-profit consortium dedicated to fostering the growth of Linux, and promoting standardizati…More

*** 22

[[http://Transifex.com]]
Transifex is a cloud-based localization workflow product for technology companies and the softw…More

*** 23

[[http://Jodies.de/ipcalc]]
Small online utility for IP address calculations including netmask, broadcast and network addre…More

*** 24

[[http://Blog.mozilla.org]]
News and updates from the Mozilla project.

*** 25

[[http://I4u.com]]
I4U is a Premium Technology Life Style News Magazine and Shopping Guide featuring one of the Be…More

*** 26

[[http://Opensource.org]]
Dedicated to managing and promoting the Open Source trademark for the good of the community. In…More

*** 27

[[http://Modx.com]]
A content management framework (CMF), a custom web application builder, and content management …More

*** 28

[[http://Xiph.org]]
Non-profit corporation dedicated to protecting multimedia from control by private interests, by…More

*** 29

[[http://Freecode.com]]
An index of Linux, Unix and cross-platform software, and mobile applications. Searchable or bro…More

*** 30

[[http://Poedit.net]]
A cross-platform gettext catalogs (.po files) editor. It aims to provide more convenient approa…More

*** 31

[[http://Vanillaforums.org]]
Vanilla is forum software that powers discussions on over 500,000 sites. Built for flexibility …More

*** 32

[[http://Postfix.org]]
A compatible, more secure replacement for sendmail program, which transfers mail over the inter…More

*** 33

[[http://Findbestopensource.com]]
To identify the best open source products and libraries in all categories.

*** 34

[[http://Https://www.fsf.org/]]
Non-profit organization dedicated to eliminating restrictions on copying, redistributing, under…More

*** 35

[[http://Mozdev.org]]
Hosts a large number of development projects for Mozilla applications.

*** 36

[[http://Mixxx.org]]
Open source DJ mixer.

*** 37

[[http://Emacswiki.org]]
A collection of the knowledge of the Emacs community to serve as a source of answers for all ki…More

*** 38

[[http://Dbpedia.org]]
A community effort to extract structured information from Wikipedia and to make this informatio…More

*** 39

[[http://Gnuwin32.sourceforge.net]]
The project provides various GNU tools and software for Win32.

*** 40

[[http://Linuxtoday.com]]
News related to Open Source software and community (continuous, +email)

*** 41

[[http://Phplist.com]]
PHPlist is a web application that implements a personalised mailing list manager or customer re…More

*** 42

[[http://Flightgear.org]]
The FlightGear flight simulator project is an open-source, multi-platform, cooperative flight s…More

*** 43

[[http://Sphinxsearch.com]]
A search engine designed for indexing database content. It natively supports MySQL, PostgreSQL,…More

*** 44

[[http://Savannah.gnu.org]]
Free Software hosting from the GNU project. Don't have to be part of the GNU project to host a …More

*** 45

[[http://Thefullwiki.org]]
Mashup of Google Maps and Wikipedia, providing a map of every location mentioned in any article.

*** 46

[[http://Https://lmms.io/]]
Open source sequencer for Linux.

*** 47

[[http://Alioth.debian.org]]
Free project hosting especially for software to do with Debian. Repository is accessible by SVN…More

*** 48

[[http://Everything2.com]]
An extensively hyperlinked collection of facts, ideas, notes and humor to which anyone can add.

*** 49

[[http://Gna.org]]
This site is run by FSF France. It's similar to SourceForge and Savannah in that it allows peop…More

*** 50

[[http://Tigris.org]]
Tightly-focused site hosting open source projects that build software engineering tools.

*** 51

[[http://Xmpp.org]]
Contact info, architectural docs and a weblog on Extensible Messaging and Presence Protocol (XM…More

*** 52

[[http://Boinc.berkeley.edu]]
Software platform for distributed computing using volunteered computer resources, allowing part…More

*** 53

[[http://Aosabook.org]]
The authors of several open source applications explain how their software is structured, and w…More

*** 54

[[http://Mantisbt.org]]
Information and download for a popular web-based bug tracking system with many features. (PHP)

*** 55

[[http://Planetmath.org]]
Collaborative, peer-reviewed mathematics encyclopedia with TeX input, inspired by MathWorld (GN…More

*** 56

[[http://Awstats.org]]
A web server logfile analyzer that works as a CGI and/or from command line, and supports multip…More

*** 57

[[http://Lame.sourceforge.net]]
Educational tool to be used for learning about MP3 encoding. LAME aims to be the basis of a pat…More

*** 58

[[http://Ubuntustudio.org]]
Contains information for musicians wishing to use Ubuntu-Linux as their Digital Audio Workstation.

*** 59

[[http://Apache.org/licenses/]]
Overview of the different versions of the Apache licenses.

*** 60

[[http://Directory.fsf.org]]
A catalog of free software collected by FSF staff and volunteers. Can be queried or browsed.

*** 61

[[http://En.flossmanuals.net]]
In an attempt to provide free documentation for free software, this wiki lets anyone read, writ…More

*** 62

[[http://Ardour.org]]
A multichannel digital audio workstation. (C++) [GNU/Linux, Mac OS X]

*** 63

[[http://Bugzilla.org]]
Open-source bug tracking software, with a web-based interface. Written in Perl, with MySQL data…More

*** 64

[[http://Onlamp.com]]
Provides articles on the open source LAMP web platform. Roughly defined as (but not limited to)…More

*** 65

[[http://Horde.org]]
A web application framework. Projects using the framework include webmail, a wiki and groupware…More

*** 66

[[http://Wesnoth.org]]
A turn-based single and multiplayer game with a fantasy theme. Manga-like graphical style. Incl…More

*** 67

[[http://Softpanorama.org]]
(slightly skeptical) open source software educational society. Eastern European focus; many lin…More

*** 68

[[http://Wikipediocracy.com]]
Wikipediocracy is a Wikipedia criticism site. We shine a light on Wikipedia's corrupt, bullying…More

*** 69

[[http://Java-source.net]]
A directory of open source software focused on Java.

*** 70

[[http://Audacious-media-player.org]]
The GTK+2 port of XMMS with modern GUI features.

*** 71

[[http://Ow2.org]]
Software community aiming to develop component-based middleware for large scale distributed sys…More

*** 72

[[http://Bluefish.openoffice.nl]]
A programmer's HTML editor written using GTK, designed to save the experienced webmaster some k…More

*** 73

[[http://Timreview.ca]]
Free monthly publication for Canadian business owners, company executives and employees, coveri…More

*** 74

[[http://Linuxappfinder.com]]
A catalog of GNU/Linux programs, which can be browsed or searched.

*** 75

[[http://Projects.apache.org]]
Detailed catalogue of projects by the foundation. Includes feeds and documentation for project …More

*** 76

[[http://Sourcearchive.com]]
A collection of open source code, easily browsable.

*** 77

[[http://Coppermine-gallery.net]]
Information and download page for a multi-lingual photo gallery suite. (PHP)

*** 78

[[http://Net-snmp.org]]
A suite of applications used to implement the management and agent components SNMP v1, SNMP v2c…More

*** 79

[[http://Jabber.org]]
Not-for-profit organization that oversees the general development of XMPP and maintains the Jab…More

*** 80

[[http://En.citizendium.org]]
Wiki encyclopedia project in which authors use their real, verified names and recognized subjec…More

*** 81

[[http://Sphider.eu]]
A lightweight search engine in PHP. Includes details of features, documentation, support forum,…More

*** 82

[[http://Osalt.com]]
osalt.com helps recommend a open source software alternative or replacement for commercial prod…More

*** 83

[[http://Oreilly.com/openbook/]]
Read entire books online which were published under various forms of "open" copyright.

*** 84

[[http://Opensourcescripts.com]]
Directory of scripts in various languages from Unix Shells to Visual Basic.

*** 85

[[http://Nutch.apache.org]]
Effort to implement a prototype of an open source web-search engine.

*** 86

[[http://Ilias.de]]
A SCORM compliant Learning Management System (LMS), developed at the University of Cologne/Germ…More

*** 87

[[http://Fengoffice.com/web/]]
An open-source web office to allow collaboration and sharing of documents, task lists, emails, …More

*** 88

[[http://Linuxvirtualserver.org]]
Complete Open Source solution to build server clusters with load balancers running Linux

*** 89

[[http://Scintilla.org]]
Download, screenshots and documentation of a free source code editing component for Win32 and G…More

*** 90

[[http://Hydrogen-music.org]]
Drum-machine for creating patterns-based music. Site contains project news, downloads, example …More

*** 91

[[http://Userfriendly.org]]
Comic strip about the Internet and hi-tech business in general. By Illiad. Includes wallpaper a…More

*** 92

[[http://Gnu.org/software/emacs/]]
Official Free Software Foundation page for the extensible, customizable, self-documenting real-…More

*** 93

[[http://Kmeleonbrowser.org]]
A browser for the Win32 platform based on the NGLayout engine.

*** 94

[[http://Oss.oetiker.ch/mrtg/]]
Tool to monitor the traffic load on network-links using UDP and SNMP. Provides information on l…More

*** 95

[[http://Fosdem.org]]
Free and non-commercial yearly event organized by the community, for the community. Its goal is…More

*** 96

[[http://Fsfe.org]]
Non profit organization working to create general understanding and support for software freedo…More

*** 97

[[http://Groonga.org]]
An LGPL 2.1, open-source, fulltext search engine and column store written in C. Works with MySQ…More

*** 98

[[http://Tuxguitar.com.ar]]
Multi-track tablature editor, compatible with Guitar Pro files. Site includes screenshots, down…More

*** 99

[[http://Phorum.org]]
Web based discussion software. (PHP)

*** 100

[[http://Freesoft.org/CIE/]]
The engineering, theoretical concepts, and organizations of the Internet (freely distributable).

*** 101

[[http://Xapian.org]]
Open source search engine library written in C++, with bindings to allow use from other languag…More

*** 102

[[http://Halfbakery.com]]
A communal database of original, fictitious inventions, edited by its users and spanning many t…More

*** 103

[[http://Opensong.org]]
Application to manage lyrics, chords, lead sheets, overheads, and computer projection. Website …More

*** 104

[[http://Vortexbox.org]]
Turns a computer into an easy to use music server/jukebox by automatically ripping CDs to FLAC …More

*** 105

[[http://Jobberbase.com]]
A job board software suited for single industry recruitment. Community, blog, download, and ins…More

*** 106

[[http://Opendatacommons.org]]
Open Knowledge Foundation project to provides a set of legal tools to help people provide and u…More

*** 107

[[http://Gnu.org/copyleft/gpl.html]]
One standard for licensing free software.

*** 108

[[http://Irssi.org]]
Modular realtime chat client supporting IRC and SILC protocols. Supports multiple servers, them…More

*** 109

[[http://Qtweb.net]]
Designed to be portable, has private browsing features which prevent sensitive data from being …More

*** 110

[[http://Galleryserverpro.com]]
A gallery application that supports photos, video, audio, and documents. Includes EXIF/IPTC sup…More

*** 111

[[http://Oss-watch.ac.uk]]
Promotes awareness and understanding of the legal, social, technical and economic issues that a…More

*** 112

[[http://Vim.sourceforge.net]]
Resources, tips and news for the Vim community.

*** 113

[[http://Nano-editor.org]]
Clone of the Pico text editor with some enhancements. Available for Linux and DOS.

*** 114

[[http://Iradeo.com]]
Mp3 streaming application for integration with websites. Site includes help and downloads. (PHP)

*** 115

[[http://Csharp-source.net]]
Directory of open source software focused in C#.

*** 116

[[http://Amarok.kde.org]]
Music player and manager with support for cover art, last.fm integration, and QtScript plugins.…More

*** 117

[[http://Opensearchserver.com]]
A GPLv3 search engine and crawler for urls, databases, and file systems. Comes with an XML/HTTP…More

*** 118

[[http://Yacy.net]]
A distributed Web crawler and caching HTTP/HTTPS proxy built on the principles of peer-to-peer …More

*** 119

[[http://Courier-mta.org]]
An SMTP/IMAP/POP3/HTTP (webmail) server, implementing SMTP extensions for mailing list manageme…More

*** 120

[[http://Konqueror.org]]
A web browser with HTML 4.0 compliance, supporting Java applets, JavaScript, CSS1 and (partiall…More

*** 121

[[http://Openarena.ws]]
An open-source content package for Quake III Arena (free stand-alone game). Contains bots. (GPL…More

*** 122

[[http://Pnotepad.org]]
Windows programming editor with an integrated Hex viewer/editor.

*** 123

[[http://Opendatacommons.org/licenses/odbl/]]
A share-alike licence for data and databases from Open Data Commons. Includes licence text, imp…More

*** 124

[[http://Ibm.com/developerworks/opensource]]
Open source software license.

*** 125

[[http://Aquamacs.org]]
Details about the differences between Aquamacs and other OS X Emacs implementations, hints abou…More

*** 126

[[http://Assault.cubers.net]]
Team oriented multiplayer first person shooter. (ZLIB license) [win32, linux and bsd (x86), mac…More

*** 127

[[http://Advogato.org]]
A community site for developers of free software.

*** 128

[[http://Editra.org]]
Project information, previews, documentation, downloads and a plugins section for the multi-pla…More

*** 129

[[http://Torcs.sourceforge.net]]
3D racing simulator using OpenGL technologies, derived from RARS. Players can develop their own…More

*** 130

[[http://Eyeos.com]]
An open-source browser based web desktop. Full documentation, download, and community support a…More

*** 131

[[http://Fretsonfire.sourceforge.net]]
The player has to strike the correct colored squares at the appropriate time during the songs t…More

*** 132

[[http://Sauerbraten.org]]
Singleplayer (2 game modes, savegames) and multiplayer (12 game modes) first person shooter, bu…More

*** 133

[[http://Openwebmail.org]]
A webmail system designed to manage very large mail folder files in a memory efficient way. (Perl)

*** 134

[[http://Schools-wikipedia.org]]
A free, hand-checked, non-commercial selection from Wikipedia, targeted around the UK National …More

*** 135

[[http://Beonex.com]]
Open-source distribution of Mozilla for end-users.

*** 136

[[http://Opensourcealternative.org]]
Provides information about free and open source alternatives to popular commercial software.

*** 137

[[http://Opencascade.org]]
A geometric modeling SDK available on Linux including geometric data structures, modeling algor…More

*** 138

[[http://Getnightingale.com]]
Forked from Songbird, features support GNU/Linux support. Add-ons list, support forum, wiki. (C…More

*** 139

[[http://Socallinuxexpo.org]]
An annual Linux and open-source conference organized by the open-source community

*** 140

[[http://Gnu.org/copyleft/fdl.html]]
A version of the GPL for reference material.

*** 141

[[http://Jobs.perl.org]]
For employers looking for Perl developers and for Perl developers looking for the next step in …More

*** 142

[[http://Obiblio.sourceforge.net]]
Automated library system with OPAC, circulation, cataloging, and staff administration functiona…More

*** 143

[[http://Megaglest.org]]
A cross-platform 3-d game, where players control the armies of one of seven fantasy themed fact…More

*** 144

[[http://Sklogwiki.org]]
An open wiki for statistical mechanics and thermodynamics.

*** 145

[[http://Dotsrc.org]]
Provides free Internet and application services, such as CVS, WWW, FTP, PHP, MySQL, and maillis…More

*** 146

[[http://Producingoss.com]]
Book by Karl Fogel. Full text freely available as HTML, PDF, and XML.

*** 147

[[http://Alternativepedia.com]]
Catalog with popular software and their free or open source alternatives. Visitors can filter a…More

*** 148

[[http://Cyrusimap.org]]
An IMAP server developed at Carnegie Mellon University. (C, Perl) [GNU/Linux, Unix]

*** 149

[[http://Cubeengine.com]]
Singleplayer (2 game modes, savegames) and multiplayer (12 game modes) first person shooter. Ov…More

*** 150

[[http://Dooble.sourceforge.net]]
A web browser featuring an integrated distributed search engine, a secure messenger and an e-ma…More

*** 151

[[http://Https://air.mozilla.org/]]
The Internet multimedia presence of Mozilla. Brings live and pre-recorded shows, interviews, ne…More

*** 152

[[http://Openwebspider.org]]
An open source web spider and search engine. Includes demo, source code and screenshots.

*** 153

[[http://Freebase.com]]
A collaborative knowledge base built on structured data harvested from many sources, including …More

*** 154

[[http://Opencontent.org]]
Reason for being: "facilitate the prolific creation of freely available, high-quality, well-mai…More

*** 155

[[http://Doxbox.ca]]
A multi-user knowledge-base system for publishing files and documents onto the web. Documentati…More

*** 156

[[http://Taskfreak.com]]
A web-based task manager. Installation instructions, a download link, community forums, and an …More

*** 157

[[http://Apachecon.com]]
Details of the annual ApacheCon meetings held in Europe and the United States, with registratio…More

*** 158

[[http://Https://mozillalabs.com/]]
A virtual lab to create, experiment, and play with new Web innovations and technologies. List o…More

*** 159

[[http://Osadl.org]]
Aims to promote and support the development of Open Source software for the automation industry…More

*** 160

[[http://Opensourcesoftwaredirectory.com]]
Provides a list of open source software organized by categories.

*** 161

[[http://Seekquarry.com]]
SeekQuarry is the parent site for Yioop!. Yioop! is a GPLv3, open source, PHP search engine. Yi…More

*** 162

[[http://Jwchat.org]]
A web-based client written using AJAX technology. It supports basic jabber instant messaging, r…More

*** 163

[[http://Opensourcebridge.org]]
Open source conference that focuses on the culture of being an open source citizen.

*** 164

[[http://Open-site.org]]
A volunteer-run open content encyclopedia.

*** 165

[[http://Oss-institute.org]]
Non-profit organization created to promote the adoption of open source solutions within U.S. ag…More

*** 166

[[http://Atunes.org]]
Audio player and organizer, with a tag editor, and ability to rip Audio CDs. Site includes scre…More

*** 167

[[http://Libervis.com]]
Community portal providing a discussion forum, articles and blogs.

*** 168

[[http://Vdrift.net]]
Open source driving simulation made with drift racing in mind, powered by Vamos physics engine.…More

*** 169

[[http://Mnogosearch.org]]
Search engine software for Internet and Intranet sites. The index can be stored in any of the p…More

*** 170

[[http://Creativitypool.com]]
A global pool of innovation and new ideas. People can browse the database and search for creati…More

*** 171

[[http://Softwarefreedom.org]]
Provides legal representation and other law related services to protect and advance Free and Op…More

*** 172

[[http://Cryptonomicon.com/beginning.html]]
Essay on operating systems written by Neal Stephenson. Download in Mac stuffit or PC Zip format.

*** 173

[[http://Freedroid.org]]
FreedroidRPG is an open source isometric role playing game. Clone of the classic game "Paradroi…More

*** 174

[[http://Arachnode.net]]
A .NET web crawler written in C# using SQL 2005 and Lucene. Documentation and online demonstrat…More

*** 175

[[http://Php.net/license/]]
Covers licensing issues for developers distributing applications in PHP. Includes links to anno…More

*** 176

[[http://Latex-project.org/lppl/]]
Particularly suited for TeX-related programs.

*** 177

[[http://Ekopedia.org]]
Ekopedia is an encyclopedia about alternative life techniques with strong focus on ecological i…More

*** 178

[[http://Courier-mta.org/maildrop/]]
A mail filter/local delivery agent with a perl-ish filtering language and maildir support. (C++…More

*** 179

[[http://Free-soft.org]]
General information on Free Software (Open Source) and its community.

*** 180

[[http://Gnu.org/licenses/license-list.html]]
Various licenses and comments about them.

*** 181

[[http://Hawksoft.com]]
Developer of the open source HAWK game engine, and the OpenNL portable networking library for W…More

*** 182

[[http://Netsurf-browser.org]]
Features its own layout engine. Site includes documentation, screen-shots, developer informatio…More

*** 183

[[http://Holtz.sourceforge.net]]
GPL implementation of the abstract strategy board games Zèrtz and Dvonn from the GIPF project. …More

*** 184

[[http://Xiph.org/flac/]]
FLAC is an open source lossless audio codec, supports streaming, seeking and archival.

*** 185

[[http://Tuxracer.sourceforge.net]]
An Open Source project in which the user takes the form of Tux (the Linux Mascot) and races dow…More

*** 186

[[http://Hme.sourceforge.net]]
Edits, generates, and manipulates terrain height maps. These can be used in terrain renders, wh…More

*** 187

[[http://Openscience.org]]
The Open Science Project is an Organization devoted to providing open source scientific software.

*** 188

[[http://Openlierox.net]]
The open source clone of the famous Liero (the realtime Worms) game.

*** 189

[[http://C-evo.org]]
Developing an Open Source strategy game based on Sid Meier's Civilization II. Public project.

*** 190

[[http://Fry-it.com]]
UK based provider of open source software across multiple industry sectors including education,…More

*** 191

[[http://Norconex.com/collectors/collector-http/download]]
Java-based Apache licensed enterprise web crawler running on any platform, and integrating with…More

*** 192

[[http://Dsl.org/cookbook/]]
All-encompassing book on using open source software, which itself is open source and available …More

*** 193

[[http://Debrief.info]]
Submarine maritime tactical analysis application. Used for analysis of maritime vessel tracks i…More

*** 194

[[http://Ordrumbox.com]]
Real-time drum machine and audio sequencer. Site contains online demo, full download, and user …More

*** 195

[[http://Traverso-daw.org]]
Audio recording and editing suite with support for CD mastering and non-linear processing. Site…More

*** 196

[[http://Osliving.com]]
A directory of the web's best open source software.

*** 197

[[http://Mayavi.sourceforge.net]]
Scientific data visualizer written in Python

*** 198

[[http://Planet.mozilla.org]]
Current Mozilla news and information from Mozilla community members.

*** 199

[[http://Pykota.com]]
Downloads, wiki, support and mailing lists for this print quota and print accounting package fo…More

*** 200

[[http://Jasspa.com]]
The JASSPA Distribution of MicroEmacs. Available on many platforms, including windows.

*** 201

[[http://Spi-inc.org]]
A non-profit organization which was founded to help organizations develop and distribute open h…More

*** 202

[[http://Mozillalinks.org]]
All the news, tips and reviews about Firefox, Thunderbird and all Mozilla related products.

*** 203

[[http://Alientrap.org/games/nexuiz]]
Nexuiz is a first-person shooter which started as a Quake modification in the summer of 2001. […More

*** 204

[[http://Phpmyvisites.us]]
A website statistics and web analytics application. Support, demo, download, and forums are pro…More

*** 205

[[http://Dotnetopen.net]]
A categorized list of open source C#, VB.NET, ASP.Net projects.

*** 206

[[http://Apacheweek.com]]
A weekly e-zine focused on Apache - it includes features, reviews, and Apache jobs.

*** 207

[[http://Bbc.co.uk/opensource/]]
Provides information about and links to BBC open source projects.

*** 208

[[http://Dataportability.org]]
Aims to consult, design, educate and advocate interoperable data portability to users, develope…More

*** 209

[[http://Gltron.org]]
gltron is a last player riding game based on the light cycle portion of the movie Tron. (C) [Ma…More

*** 210

[[http://Fsfla.org]]
Regional branch of the FSF. Includes background information, membership details, newsletters, a…More

*** 211

[[http://Marginalhacks.com]]
Collection of utilities, most of which are written in Perl. Includes HTML photo album generator…More

*** 212

[[http://Blacknova.net]]
Multi-player space exploration and strategy game (PHP) [GPL].

*** 213

[[http://Cogx.org]]
Audio player featuring playback of multiple formats, tags, and last.fm scrobbling. Site include…More

*** 214

[[http://Gplhost.com/software-dtc.html]]
A set of PHP scripts for domain administration, MySQL management database, backup scripts gener…More

*** 215

[[http://Ffii.org]]
Dedicated to establishing a free market in information technology, by the removal of barriers t…More

*** 216

[[http://Mp3bookhelper.sourceforge.net]]
Provides Mp3 and Ogg Vorbis tags editing and file renaming functions. (Delphi) [Windows]

*** 217

[[http://Opendx.org]]
Open source visualization software package based on IBM's Visualization Data Explorer.

*** 218

[[http://Fox-toolkit.org]]
An open source cross-platform C++ based Toolkit for GUI development.

*** 219

[[http://Speex.org]]
Open audio codec designed for speech, part of the Xiph.org Foundation.

*** 220

[[http://Osswin.sourceforge.net]]
Project to build a directory of open source software which is able to replace much of the propr…More

*** 221

[[http://Opensource.org/licenses/]]
Copies of licenses approved by the Open Source Initiative.

*** 222

[[http://Ufoai.org]]
UFO:AI is a 3d turn based strategy game inspired by the X-Com series by Microprose. (C) [Window…More

*** 223

[[http://Ruby-lang.org/en/about/license.txt]]
Dual terms: use GPL terms or its own terms.

*** 224

[[http://Https://opends.java.net/]]
A community project building a free and comprehensive directory service, based on LDAP and DSML…More

*** 225

[[http://Dataparksearch.org]]
Open source search engine tool released under GPL and designed to organize search within a webs…More

*** 226

[[http://Muhri.net/skipstone/]]
SkipStone is a Gtk+ only browser that aims to be fast and with few dependencies.

*** 227

[[http://Cockos.com/ninjam/]]
Music collaboration software for having realtime jam sessions over the Internet. Site includes …More

*** 228

[[http://Csharpopensource.com]]
Directory of open source software using C#.

*** 229

[[http://Hotlinuxjobs.com]]
Search firm specializing in placing Linux professionals, providing contract and direct hire ser…More

*** 230

[[http://Acme.cat-v.org]]
Acme is a textual user interface for programmers by Rob Pike for Plan 9, with ports to Unix-lik…More

*** 231

[[http://Opensource-it.com]]
Offers a directory dedicated to enterprise grade open source solutions.

*** 232

[[http://Lvee.org]]
International conference of developers and users of free and open source software. Located in B…More

*** 233

[[http://Cia.vc]]
Tracks open source projects in real-time and provides activity information and commit statistic…More

*** 234

[[http://Catb.org/~esr/writings/cathedral-bazaar/]]
Eric S. Raymond's seminal paper analysing why open source works so well; followup papers "Homes…More

*** 235

[[http://Sbooth.org/Play/]]
Audio player with support for many different file formats, last.fm, replay gain, and metadata e…More

*** 236

[[http://Zsync.moria.org.uk]]
An implementation of rsync over HTTP.

*** 237

[[http://Texmacs.org]]
Editor for extensible, structured and WYSIWYG technical documents, which was both inspired by T…More

*** 238

[[http://Schoolforge.net]]
An international coalition of organizations fostering free and open resources in and for educat…More

*** 239

[[http://Ngrep.sourceforge.net]]
Ngrep is a pcap-aware tool that will allow you to specify extended regular expressions to match…More

*** 240

[[http://Libregamewiki.org]]
The encyclopedia of free (as in freedom) games with free content.

*** 241

[[http://Opensourcehelpdesklist.com]]
A complete list of open source help desk software packages.

*** 242

[[http://Tranglos.com/free/keynote.html]]
A tabbed editor that has several plugins to add dialer, and calendar. [Open Source, Mozilla Pub…More

*** 243

[[http://Dangerdeep.sourceforge.net]]
Danger from the deep (aka dangerdeep) is a Free / Open Source World War II German submarine sim…More

*** 244

[[http://Exaile.org]]
Music player which supports album art fetching, Last.fm submission, and plugins. Site includes …More

*** 245

[[http://Rarewares.org/mp3-lamedrop.php]]
Mp3 encoder which reads FLAC and Ogg Vorbis files. Site includes download for binaries, source …More

*** 246

[[http://Leaf.sourceforge.net]]
Embedded Linux network appliance for use in small office and home automation environments; can …More

*** 247

[[http://Daimonin.org]]
Free isometric real-time MMORPG. 2d/3d graphics, 3d sound effects, digital ambient music.

*** 248

[[http://Tools.arlut.utexas.edu/gash2/]]
A system for managing a variety of directory services, such as NIS, DNS, Samba, Sendmail, and t…More

*** 249

[[http://Artlibre.org/licence/lal/en/]]
Copyleft license applied to artistic content and projects.

*** 250

[[http://Txt2html.sourceforge.net]]
Converts plain text to HTML, supporting headings, lists, simple character markup, and hyperlink…More

*** 251

[[http://Atnf.csiro.au/computing/software/arch/]]
An open source, high precision corporate search engine based on Apache Nutch

*** 252

[[http://Xemacs.org]]
Official site. Open source text editor for GUI environments. Includes downloads, documentation,…More

*** 253

[[http://Batman.no/buze/]]
Tracker designed as a drop-in replacement of Jeskola Buzz. Site includes downloads, forum, and …More

*** 254

[[http://Freegamer.blogspot.com]]
Open source games weblog and list.

*** 255

[[http://Winton.org.uk/zebedee/]]
Establishes an encrypted, compressed tunnel for TCP/IP or UDP traffic between two systems. (C) …More

*** 256

[[http://Osmius.com]]
Allows the monitoring of heterogeneous systems using multi-platform agents distributed over a n…More

*** 257

[[http://Robertogaloppini.net]]
Weblog analyzing commercial firms with open-source products.

*** 258

[[http://Emacspeak.sourceforge.net]]
Offers a reference, an user guide, instructions how to install, tips and tricks, a list of supp…More

*** 259

[[http://Nongnu.org/enigma/]]
A puzzle game based on oxyd. Runs on Windows, OS X, and most open source operating systems. (C+…More

*** 260

[[http://Jameleon.sourceforge.net]]
Automated testing tool that separates applications into features and allows those features to b…More

*** 261

[[http://Catb.org/~esr/halloween/]]
Microsoft are getting very worried indeed about competition from Open Source Software such as L…More

*** 262

[[http://Openforumeurope.org]]
Not-for-profit organisation helping to accelerate, broaden and strengthen the use of OSS in bus…More

*** 263

[[http://Cssed.sourceforge.net]]
A GTK2 application to help create and maintain CSS style sheets for web developing. An open sou…More

*** 264

[[http://Phprpg.org]]
A multiplayer fantasy roleplaying game driven by PHP and MySQL, with aims to develop a web-base…More

*** 265

[[http://Wikipediareview.com]]
An open forum for discussing Wikipedia and other Wikimedia projects as well as issues affecting…More

*** 266

[[http://Gnu.org/philosophy/free-software-for-freedom.html]]
An essay from the Free Software Foundation arguing that the term "free software" is a better ch…More

*** 267

[[http://Openinventionnetwork.com]]
An intellectual property company that was formed to promote Linux. It acquires patents and make…More

*** 268

[[http://Frozennorth.org/C2011481421/E652809545/index.html]]
Weblog entry. Describes the author's process of putting errors into Wikipedia and watching for …More

*** 269

[[http://Htdig.org]]
A complete world wide web indexing and searching system for a small domain or intranet. (C++) […More

*** 270

[[http://Kiosk.mozdev.org]]
A collection of tools that enable the creation of kiosk environment on the linux platform. The …More

*** 271

[[http://Dwheeler.com/oss_fs_why.html]]
In-depth review and analysis of the many quantitative reasons to use open source software, with…More

*** 272

[[http://Osforge.com]]
Features news, community discussion forums, and open source press releases.

*** 273

[[http://Openprotect.com]]
OpenProtect is an anti spam and anti virus for the mail server that filters spam and blocks vir…More

*** 274

[[http://Spicetrade.org]]
Colonize Europe in this Java based, open source game. Live an adventure in the 12th century world.

*** 275

[[http://Bincimap.org]]
Open source xinetd/tcpserver based IMAP server for the Linux platform, with support for Maildir.

*** 276

[[http://Vcf-online.org]]
C++ framework created to provide platform GUI framework, features such as Java and Java's Swing…More

*** 277

[[http://Infolets.com]]
Explores projects, products, and ideas that are interesting, innovative or just plain unique.

*** 278

[[http://Rss.slashdot.org/Slashdot/slashdot]]
Source for technology related news with a slant towards Linux and Open Source issues.

*** 279

[[http://Members.aon.at/grxpage]]
A free (GPL) Real Time Equalizer.

*** 280

[[http://Mysql.com/about/legal/licensing/oem/]]
Complex hybrid license: public domain, GPL, LGPL, Open Source, commercial.

*** 281

[[http://Farcrycore.org]]
Open-source Content Management System running on ColdFusion MX platform. Support for SQL databa…More

*** 282

[[http://Osw.sourceforge.net]]
Open-source programming environment that allows musicians sound processing in response to real-…More

*** 283

[[http://Danny.oz.au/free-software/]]
Focuses on connections between free software and community development and on free software in …More

*** 284

[[http://Web.clicknet.ro/mciobanu/mp3diags/]]
MP3 analysis tool that also includes file correction and tag editing. Site includes downloads, …More

*** 285

[[http://Boycottnovell.com]]
Discusses exclusionary and questionable deals (such as the deal between Novell and Microsoft) w…More

*** 286

[[http://Mailsync.sourceforge.net]]
Synchronizes a collection of mailboxes, which may be on the local filesystem or on an IMAP serv…More

*** 287

[[http://Gnu.org/software/emacs/manual/emacs.html]]
Official Emacs manual from the Free Software Foundation.

*** 288

[[http://Gnu.org/copyleft/lgpl.html]]
Formerly: GNU Library GPL.

*** 289

[[http://Coolplayer.sourceforge.net]]
Media player which supports skins and plugins. Site includes downloads, plugins, skins, forum, …More

*** 290

[[http://Lotgd.net]]
A remake of the classic BBS Door game, Legend of the Red Dragon (aka LoRD) by Seth Able Robinso…More

*** 291

[[http://Finseth.com/craft/]]
The full text of the book "The Craft of Text Editing: Emacs for the Modern World" by Craig Fins…More

*** 292

[[http://Gnu.org/software/zile/]]
An Emacs clone useful for small footprint installations (like on floppy disk) or quick editing …More

*** 293

[[http://Ecos.sourceware.org/license-overview.html]]
Summary of license for Red Hat eCos operating system.

*** 294

[[http://Jedsoft.org/jed/]]
Text editor for Unix, VMS, MSDOS, OS/2, BeOS, QNX, and Win9X/NT platforms. A macro language and…More

*** 295

[[http://Gnu.org/fry/]]
A short film featuring Stephen Fry, to introduce the idea of free software and celebrate 25 yea…More

*** 296

[[http://H2oproject.law.harvard.edu]]
Community-based development of educational software. Contains code for the projects and a missi…More

*** 297

[[http://Openmosix.sourceforge.net]]
OpenMosix is the free fork from MOSIX after this great project closed the user area tools to a …More

*** 298

[[http://Theopendisc.com]]
A collection of high quality open source software for Windows. Its programs section works as a …More

*** 299

[[http://Nosignal.fi/ecasound/]]
Command line tool designed for multitrack audio processing which can be used for tasks like aud…More

*** 300

[[http://Dmoz.org/license.html]]
Terms under which anyone may use the Open Directory data. Free. Acknowledgment required.

*** 301

[[http://Tkoutline.sourceforge.net]]
A cross-platform outline editor written in Tcl/Tk.

*** 302

[[http://Chiark.greenend.org.uk/~ian/adns/]]
ADNS is a free resolver library for C (and C++) programs, released under GNU's General Public L…More

*** 303

[[http://Mobilemaps.com]]
An open source search and locate engine which allows users to find Web pages by location. (C, P…More

*** 304

[[http://Galeon.sourceforge.net]]
GNOME web browser using the NGLayout engine. Galeon's principles are simplicity and standards c…More

*** 305

[[http://Achurch.org/services/]]
Provides IRC networks with definitive nickname and channel ownership, allows messages to be sen…More

*** 306

[[http://Fvwm.org]]
The standard window manager for Linux, stable but not as pretty as Window Maker or Enlightenment.

*** 307

[[http://Netbsd.org/about/redistribution.html]]
License patterned after FreeBSD Copyright.

*** 308

[[http://Prima.eu.org]]
Toolkit for multi-platform GUI development. (Perl) [OS Independent]

*** 309

[[http://Starynkevitch.net/Basile/guisdoc.html]]
Open source widget server. (Python, Ruby, GTK2) [OS Independent]

*** 310

[[http://Tibleiz.net/code-browser/]]
A folding text editor that allows to structure source code using folders. [Win32/Linux]

*** 311

[[http://Openbsd.org/policy.html]]
License and background on Berkeley Computer Systems Research Group copyrights.

*** 312

[[http://Project-strus.net]]
A collection of C++ (C++98) libraries and command line tools for building a competitive full-te…More

*** 313

[[http://Tectonic.co.za]]
Africa's top source for open source news

*** 314

[[http://Fte.sourceforge.net]]
A folding text editor for programmers.

*** 315

[[http://Anmar.eu.org/projects/sharpwebmail/]]
A WebMail application that's designed to work with a POP3 server as mailstore, and a SMTP serve…More

*** 316

[[http://Jajuk.info]]
An application that organizes and plays music, geared towards advanced users with large or scat…More

*** 317

[[http://Lde.sourceforge.net]]
Disk editor for Linux, originally written to help recover deleted files. It has a simple ncurse…More

*** 318

[[http://Shawnhargreaves.com]]
Has several open source projects and articles about the future of open source games.

*** 319

[[http://Https://sites.google.com/site/fjwcentaur/emacs]]
WoMan.el, an elisp package to browse UNIX man files without having man installed and msdos-shel…More

*** 320

[[http://Https://sites.google.com/site/freeportablesoftwares/]]
A collection of links to free portable applications.

*** 321

[[http://Sites.google.com/site/osbtools/]]
Compiles website from predefined template and content files, generates sitemap, has development…More

*** 322

[[http://Code.google.com/p/aldrin-sequencer/]]
A tracker written in Python, designed to be very similar to Jeskola Buzz. Site includes forum, …More

*** 323

[[http://Code.google.com/p/cspoker/]]
CSPoker is a lightweight poker client/server. Client implementations in Java and Flash. XML-bas…More

*** 324

[[http://Code.google.com/p/ochan/]]
Project page for Ochan, the java anonymouse imageboard application. (Java)

*** 325

[[http://Https://code.google.com/p/phpshop/]]
A shopping cart application. Documentation, download, demo, and forums are provided. (PHP,MySQL)

*** 326

[[http://Tech.groups.yahoo.com/group/ntemacs-users/]]
A browser accessible archive of the NT-Emacs mailing list.

*** 327

[[http://En.wikipedia.org/wiki/Apache_Software_Foundation]]
Encyclopedia article with a brief history of the organisation, and details of its projects and …More

*** 328

[[http://En.wikipedia.org/wiki/Nupedia]]
Nupedia was a public peer-reviewed general encyclopedia created by volunteer scholars, with res…More

*** 329

[[http://En.wikipedia.org/wiki/Free_software_foundation]]
Encyclopedia articles about the organisation, with background and details of activities.

*** 330

[[http://En.wikipedia.org/wiki/Open_source]]
Long article with examples.

*** 331

[[http://Developer.apple.com/opensource/]]
Features information on and downloads of the open source parts of Apple's OS X.

*** 332

[[http://Https://github.com/ampache]]
Open Source, web-based audio file manager and player. Site includes bug-tracker, support wiki, …More

*** 333

[[http://Https://github.com/jazztickets/irrlamb]]
3D game that probably involves a lot of physics and frustrating gameplay. (C++) [Linux, Windows…More

*** 334

[[http://Cnn.com/2003/TECH/internet/08/03/wikipedia/]]
Short article describing one individual's experiences.

*** 335

[[http://News.bbc.co.uk/1/hi/technology/7561943.stm]]
Supporters of open source software are claiming victory after a US court ruled copyright protec…More

*** 336

[[http://Nytimes.com/2009/07/26/technology/companies/26mozilla.html]]
A New York Times article that reflects on Mozilla's achievements and future challenges as the n…More

*** 337

[[http://Theguardian.com/technology/2004/oct/26/g2.onlinesupplement]]
Summary primarily of the positive aspects and milestones of the online encyclopedia.

*** 338

[[http://News.cnet.com/8301-13860_3-10317591-56.html]]
The advocacy group is encouraging businesses to throw out their Microsoft software in favor of …More

*** 339

[[http://Forbes.com/forbes/1999/0809/6403122a.html]]
"Hackers crack the code of a new chip and post the design secrets on the Web. The chip's maker,…More

*** 340

[[http://Altaxo.sourceforge.net]]
Data analysis and plotting program (C#) [Windows].

*** 341

[[http://Arachnida.sourceforge.net]]
An embedable web server and client written in C++. It uses the OpenSSL library for all connecti…More

*** 342

[[http://Audacity.sourceforge.net]]
Audio editor for recording, slicing, and mixing audio. Site includes help, downloads, and devel…More

*** 343

[[http://Sourceforge.net/projects/blueobelisk/]]
Project to develop resources for chemistry based around the concepts of open data, open standar…More

*** 344

[[http://Boincwapstats.sourceforge.net]]
Web page of an Open Source PHP script that generates signature images out of BOINC statistics. …More

*** 345

[[http://Bvi.sourceforge.net]]
The bvi editor is a display-oriented editor for binary files, based on the vi text editor.

*** 346

[[http://Caditor.sourceforge.net]]
Open source portable text editor written in C# with support for FTP, text encryption and syntax…More

*** 347

[[http://Chart2d.sourceforge.net]]
A library written in Java for adding two dimensional charts to Java programs.

*** 348

[[http://Cocalores.sourceforge.net]]
Resolves IP numbers to hostnames like in Apache, Squid, or other logfiles. It is able to cache …More

*** 349

[[http://Dailystrips.sourceforge.net]]
A utility to download your favorite online comic strips each day. (Perl)

*** 350

[[http://Dav-text.sourceforge.net]]
GNU/Linux console-based text editor. Freely licensed under the GPL.

*** 351

[[http://Eddi.sourceforge.net]]
Tcl and tix based editor.

*** 352

[[http://Emacro.sourceforge.net]]
EMacro is portable .emacs for GNU Emacs and XEmacs that configures itself. Beside download link…More

*** 353

[[http://Mac-emacs.sourceforge.net]]
Andrew Choi's port of Emacs to the Apple OS.

*** 354

[[http://Encyclopodia.sourceforge.net]]
Free software version of Wikipedia for Apple iPod devices. [English/German]

*** 355

[[http://Ftmon.sourceforge.net]]
A general purpose monitoring engine for use by home users and system administrators (Perl) [Uni…More

*** 356

[[http://Fate.sourceforge.net]]
A massive multiplayer space trading and combat game for Linux. [GPL]

*** 357

[[http://Feedlaunch.sourceforge.net]]
Graphical RSS and ATOM feed editor. [GPL].

*** 358

[[http://Fftrader.sourceforge.net]]
2D single player space strategy, combat, and trading game. (C++) [OS Independent]

*** 359

[[http://Freddy.sourceforge.net]]
An ascii text editor, primarily for programmers.

*** 360

[[http://Thegenius.sourceforge.net]]
Chess engine including artificial intelligence, user interface and several features.

*** 361

[[http://Globetrotter.sourceforge.net]]
Geographic guestbook where visitors can place messages and comments directly on a map. (PHP,MySQL)

*** 362

[[http://Gnotepad.sourceforge.net]]
An HTML/text editor using GTK+ and/or GNOME.

*** 363

[[http://Sourceforge.net/projects/grub/]]
Open source, cross-platform distributed crawler. FAQ, documentation and a support forum.

*** 364

[[http://Hessling-editor.sourceforge.net]]
Editor based on the VM/CMS editor XEDIT, using REXX as its macro language. Available for UNIX (…More

*** 365

[[http://Hponline.sourceforge.net]]
This game is a fast paced arena sport where players try to explode the opposition using a short…More

*** 366

[[http://Jgb.sourceforge.net]]
An engine that reads XML files describing graphical user interfaces layout.

*** 367

[[http://Jbuzzer.sourceforge.net]]
Triggers audio samples (*.mp3 and *.wav files) by pressing a key on the computer keyboard. Site…More

*** 368

[[http://Jemacs.sourceforge.net]]
JEmacs is a re-implementation of Emacs, written in a mixture of Java, Scheme, and Emacs Lisp.

*** 369

[[http://Quizshow.sourceforge.net]]
Free quiz game based on the "Who Wants to Be a Millionaire" game show. Add your own questions f…More

*** 370

[[http://Jtrix.sourceforge.net]]
An open source computing platform for developing adaptive, scalable applications. No longer mai…More

*** 371

[[http://Katy.sourceforge.net]]
A text editor for KDE inspired by the popular Editor UltraEdit.

*** 372

[[http://Guisearch.sourceforge.net]]
A tool for finding code by looking at the applications' GUI text messages (e.g., "Undo") and re…More

*** 373

[[http://Kraptor.sourceforge.net]]
2D shoot'em up made with Allegro. (C) [GNU/Linux, Windows, DOS]

*** 374

[[http://Kronojunior.sourceforge.net]]
Open source GUI for less powerful or old computers.

*** 375

[[http://Kulakcommander.sourceforge.net]]
Dual-panel text mode file manager. Built-in text editor with syntax highlighting, hex editor, F…More

*** 376

[[http://Leafwa.sourceforge.net]]
A web-based administration package for the Leafnode news server. (PHP)

*** 377

[[http://Sourceforge.net/projects/locust/]]
Specifically designed for knowledge area or corporate search, written in C++.

*** 378

[[http://Lyntin.sourceforge.net]]
An extensible Mud client and framework for the creation of autonomous agents, or bots, as well …More

*** 379

[[http://Mailfilter.sourceforge.net]]
A utility to get rid of unwanted spam mails, before downloading them from the POP3 mailbox. (C+…More

*** 380

[[http://Mkgallery.sourceforge.net]]
Generates an image gallery with thumbnails for the Internet. All pages are HTML 4.0 and CSS com…More

*** 381

[[http://Musosu.sourceforge.net]]
A free software project for playing, solving, and generating Sudoku games. (Java) [OS Independent]

*** 382

[[http://Netload-applet.sourceforge.net]]
A network load monitoring applet for GNOME. (C) [GNU/Linux, FreeBSD]

*** 383

[[http://Newsviking.sourceforge.net]]
Script to collect news articles into a weekly digest. Uses MySQL or MS SQL. (Perl)

*** 384

[[http://Nisca.sourceforge.net]]
A network interface traffic statistics reporting and graphing tool. (PHP)

*** 385

[[http://Openefm.sourceforge.net]]
An electronic filing manager designed to be used by courts and governmental agencies, to allow …More

*** 386

[[http://Openh323proxy.sourceforge.net]]
Proxy software to allow h.323 applications to pass firewall and NAT. (C++) [Windows 95/98/2000,…More

*** 387

[[http://Pagebox.sourceforge.net]]
A facility to deploy XML, servlets or JSP presentations on Java servers.

*** 388

[[http://Sourceforge.net/projects/pblang/]]
A customizable message board with many professional features, and it does not require a databas…More

*** 389

[[http://Peacock.sourceforge.net]]
HTML Editor for GTK+/GNOME. It supports most of basic HTML. It features session management and …More

*** 390

[[http://Newswriter2005.sourceforge.net]]
Administrate and publish news sections for websites, without using a database. (PHP)

*** 391

[[http://Quexf.sourceforge.net]]
A web application that takes scanned paper forms generated using queXML and reads them. The dat…More

*** 392

[[http://Rackview.sourceforge.net]]
Assists in visualizing a Data Center's computer rack layouts by creating a web page with HTML t…More

*** 393

[[http://Red0.sourceforge.net]]
A text editor written in TCL/Tk, meant to be platform-independend while still using the host sy…More

*** 394

[[http://Sourceforge.net/projects/ringlink/]]
CGI Perl program to build systems of links between websites of similar contents.

*** 395

[[http://Setedit.sourceforge.net]]
Text mode editor to supersede Borlands BC++ editor with a number of enhancements. Available for…More

*** 396

[[http://Shed.sourceforge.net]]
Easy to use hex editor written for Unix/Linux using ncurses, with a friendly pico-style interface.

*** 397

[[http://Shibboleth.sourceforge.net]]
Privacy and security aware mailing list project and software. (Perl)

*** 398

[[http://Snip.sourceforge.net]]
Open-source Tetris implementation.

*** 399

[[http://Spywar.sourceforge.net]]
SpyWar is an online strategic game in development phase. (PHP, PostgreSQL) [Linux] [GPL] {statu…More

*** 400

[[http://Tinn.sourceforge.net]]
A free text editor that trys to address some of Notepad's limitations without getting too big. …More

*** 401

[[http://Sourceforge.net/projects/typo3/]]
A system designed to manage form and content of websites. (JavaScript, PHP, Perl)

*** 402

[[http://Vigor.sourceforge.net]]
Has all the features of traditional Unix vi, plus the friendly and helpful Vigor paperclip assi…More

*** 403

[[http://Sourceforge.net/projects/visemacs/]]
A Visual Studio Add-In that allows Emacs to be integrated as the default text editor.

*** 404

[[http://Wikiproject.sourceforge.net]]
Wikipedia dedicated, open source browser for Windows.

*** 405

[[http://Wxchecksums.sourceforge.net]]
Calculates and verifies checksums. (C++) [Windows, GNU/Linux]

*** 406

[[http://Https://wiki.mozilla.org/Evangelism]]
Devoted to helping promote, coordinate, and support the Mozilla Evangelism effort.

*** 407

[[http://Https://blog.mozilla.org/feed/]]
Official weblog with news and announcements from the Mozilla Corporation.

*** 408

[[http://Mozilla.org/projects/calendar/]]
Project to developing a calendar client based on the open iCal standard. Features project infor…More

*** 409

[[http://Mozilla.org/community/]]
A list of user community sites related to Mozilla. Including newsgroups, forums, wikis and blogs.

*** 410

[[http://Https://blog.mozilla.org/creative/]]
A community of artists and designers inspired by the Mozilla ideals. Gallery of designs. Design…More

*** 411

[[http://Mozilla.org/press/mozilla-foundation.html]]
Press release covering the launch of the Mozilla Foundation, with a $2 million pledge from AOL.

*** 412

[[http://Https://wiki.mozilla.org/L10n:Home_Page]]
The starting point for getting involved in localization efforts of Mozilla products.

*** 413

[[http://Https://wiki.mozilla.org/Mobile]]
Details of the project to provide a standards-based open-source browser engine, optimized for e…More

*** 414

[[http://Mozilla.org/projects/]]
Complete ongoing Mozilla.org projects listing.

*** 415

[[http://Mozilla.org/MPL/]]
Describes the licensing policy of the Mozilla Foundation, and provides the full text of the lic…More

*** 416

[[http://Mozilla.org/MPL/1.0/]]
Follows the Debian Free Software guidelines.

*** 417

[[http://Www-archive.mozilla.org/press/mozilla-2004-08-02.html]]
Official announcement of the program to reward those who identify and report security vulnerabi…More

*** 418

[[http://Https://wiki.mozilla.org/WeeklyUpdates]]
Status updates and overview of what's happening at the whole Mozilla Foundation.

*** 419

[[http://Developer.mozilla.org/en/XML_in_Mozilla]]
This document provides an overview of the plans for XML in Mozilla. (Mozilla)

*** 420

[[http://Topix.com/rss/tech/open-source.xml]]
News about open source, collected from various sources on the web.

*** 421

[[http://Usatoday.com/tech/columnist/andrewkantor/2004-11-05-fifthofnovember_x.htm]]
Overview of Wikipedia's growth, quality, and editing process.

*** 422

[[http://Ccrma.stanford.edu/software/snd/]]
Sound editor modeled after Emacs and can be customized and extended using either Guile, Ruby, o…More

*** 423

[[http://Cyber.law.harvard.edu]]
A research program founded to explore cyberspace, share in its study, and help pioneer its deve…More

*** 424

[[http://Https://blogs.apache.org/foundation/feed/entries/atom]]
Official news and announcements from the foundation.

*** 425

[[http://Perl.apache.org/embperl/]]
Gives you the power to embed Perl code in your HTML documents and the ability to build your Web…More

*** 426

[[http://Opensource.arc.nasa.gov]]
Lists open source projects that could be essential to NASA missions.

*** 427

[[http://Python.org/community/jobs/]]
Large list of jobs for Python programmers.

*** 428

[[http://Docs.python.org/license.html]]
A very permissive, open source compliant and GPL compatible license used by the team developing…More

*** 429

[[http://Python.org/psf/]]
Non-profit organization devoted to advancing open source technology related to the Python progr…More

*** 430

[[http://Cs.purdue.edu/homes/dec/xlicense.html]]
License for the XINU operating system

*** 431

[[http://Arxiv.org/abs/0903.3971]]
Paper by Benjamin J. Weiner and co-authors, arguing that the advantages of open-sourcing astron…More

*** 432

[[http://Online.journalism.utexas.edu/2004/papers/wikipedia.pdf]]
Studies the growth of Wikipedia and analyzes the technologies and policies that made it prosper.

*** 433

[[http://W3.org/Consortium/Legal/copyright-software-19980720]]
W3C = World Wide Web Consortium, one of the Internet's main standard-setting bodies.

*** 434

[[http://Cs.cmu.edu/afs/cs/project/amulet/amulet3/manual/overview.html#1002211]]
CMU Amulet Toolkit License Agreement.

*** 435

[[http://Cs.cmu.edu/~AUIS/]]
Offers an extensible compound document architecture which can create and combine from text to p…More

*** 436

[[http://Eclipse.org/geclipse/]]
The g-Eclipse project aims to build an integrated workbench framework to access the power of ex…More

*** 437

[[http://Cs.arizona.edu/projects/xkernel/copyright.html]]
Arizona Board of Regents, University of Arizona.

*** 438

[[http://Salon.com/2004/04/27/wikipedia_3/]]
Attempts to examine the pros and cons of Wikipedia. Plus, comparisons to previous similar proje…More

*** 439

[[http://Arstechnica.com/uncategorized/2007/02/8938/]]
Ars Technica article covering Sun Microsystem's decision become a patron of the FSF.

*** 440

[[http://Debian.org/social_contract]]
Contains the Debian Free Software Guidelines, which are regarded as compliance rules for free s…More

*** 441

[[http://Debian.org/social_contract.html]]
Initially designed as a set of commitments that the Debian developers agreed to abide by, it ha…More

*** 442

[[http://Home.arcor.de/hirnstrom/htmlobserver/index.html]]
Web page checker based on regular expressions. (Java) [Linux, Windows]

*** 443

[[http://Slashdot.org/story/04/07/28/1351230/Wikipedia-Founder-Jimmy-Wales-Responds]]
Wikipedia founder responds to a dozen highly moderated questions.

*** 444

[[http://Slashdot.org/story/04/09/21/0027241/Wikipedia-Hits-Million-Entry-Mark]]
Lovely forum discussion.

*** 445

[[http://Pkp.sfu.ca]]
Mid-size university with three campuses and over 100 programs. Three semesters a year, day and …More

*** 446

[[http://Oreilly.com/opensource/]]
Features open source books, resources, news and articles.

*** 447

[[http://Oreilly.com/catalog/opensources/book/toc.html]]
The full text of this O'Reilly book has been made freely available online.

*** 448

[[http://Archive.oreilly.com/pub/a/policy/2001/12/12/transition.html]]
Article argues against the necessity of the Free Software movement tenet of copyleft.

*** 449

[[http://Oreilly.com/openbook/osfreesoft/book/]]
Full text of the book by Andrew M. St. Laurent.

*** 450

[[http://Gnu.org/software/emacs/emacs-paper.html]]
Stallman's paper on the original (TECO) Emacs. What it means to be extensible. Why lisp is good…More

*** 451

[[http://Gnu.org/software/w3/]]
A web browser that runs under GNU Emacs.

*** 452

[[http://Gnu.org/people/speakers.html]]
Individuals who can represent the GNU project and the Free Software Movement at events

*** 453

[[http://Gnu.org/software/emacs/windows/ntemacs.html]]
Files, documentation and a FAQ for the Windows versions of the GNU Emacs editor.

*** 454

[[http://Gnu.org/philosophy/open-source-misses-the-point.html]]
Explains the difference between "Free Software" described as a social movement focusing on free…More

*** 455

[[http://Savannah.gnu.org/projects/emacs/]]
The GNU Emacs project homepage at Savannah.

*** 456

[[http://Theregister.co.uk/2002/10/29/open_source_is_good/]]
Andrew Orlowski discusses a report commissioned by the US military about open source and free s…More

*** 457

[[http://Theregister.co.uk/2004/07/23/wiki_fiddlers_big_book/]]
Commentary by Andrew Orlowski. "Our jibe that the Wikipedia is the world's most useless encyclo…More

*** 458

[[http://Theregister.co.uk/2004/09/15/emergent_people_fail_to_impress/]]
Criticisms of Wikipedia and of arguments used by its admirers in an article by Andrew Orlowski.

*** 459

[[http://Theregister.co.uk/2004/09/07/khmer_rouge_in_daipers/]]
Opinion article by Andrew Orlowski suggesting that Wikipedia has a long way to go before it's a…More

*** 460

[[http://Ee.ryerson.ca/~elf/emacs/logo/]]
An interesting behind-the-scenes look at the design and creation of the Emacs 21 logo.

*** 461

[[http://Creativecommons.org/choose/]]
Service allowing quick and easy selection of one of a range of Open Content licenses to meet a …More

*** 462

[[http://Creativecommons.org/education/connexions]]
Article on the first steps of an experimental, open-source/open content project that will "give…More

*** 463

[[http://Members.shaw.ca/akochoi-emacs/]]
Latest news, a FAQ and tips about how to build the Macintosh port.

*** 464

[[http://Akhphd.au.dk/~bertho/cvsgraph/]]
A utility for generation of graphical representation of revisions and branches from a CVS/RCS r…More

*** 465

[[http://Projects.gnome.org/gedit/]]
Lightweight but powerful text editor of the GNOME project.

*** 466

[[http://Chinese-school.netfirms.com/computer-article-open-source.html]]
Explains the competing open source philosophies and development models, with examples of popula…More

*** 467

[[http://Freebsd.org/copyright/license.html]]
License for 4.4BSD.

*** 468

[[http://Freebsd.org/copyright/freebsd-license.html]]
License for FreeBSD operating system.

*** 469

[[http://Feeds2.feedburner.com/blogspot/cBoI]]
Weblog with news and comment on developments in open source, open genomics, and open content.

*** 470

[[http://Cs.vu.nl/pub/amoeba/COPYRIGHT]]
A free software OS.

*** 471

[[http://Users.softlab.ece.ntua.gr/~ttsiod/buildWikipediaOffline.html]]
Article by Thanassis Tsiodras describing how he put together a searchable offline version of th…More

*** 472

[[http://Ibiblio.org/osrt/develpro.html]]
University of North Carolina, Chapel Hill, study: histories, analyses, explanations.

*** 473

[[http://Opensource.ucc.ie]]
Resource site for Open Source Software researchers. Contains a bibliography, news and opinion s…More

*** 474

[[http://Forge.novell.com]]
A collaboration website for research and development of open-source projects.

*** 475

[[http://Opengroup.org/openmotif/license/]]
Open Motif Graphical GUI Software, Public End User License.

*** 476

[[http://Opengroup.org/dce/]]
An industry-standard, vendor-neutral set of distributed computing technologies. Provides scalab…More

*** 477

[[http://Lua.org/copyright.html]]
From Brazil, programming language framework.

*** 478

[[http://Www3.telus.net/Voiculescu/scene_3d/index.html]]
Illustrates most of the modeling, illumination, and rendering 3D objects. Covers Z-buffer, Shad…More

*** 479

[[http://Cs.vassar.edu/~priestdo/emacspeak/]]
An archive containing all the messages sent to the emacspeak mailing list by emacspeak users.

*** 480

[[http://Mediapost.com/publications/article/30253/wikipedias-symbiotic-relationship-with-search.html]]
Article by Max Kalehoff. "Wikipedia's orderly collection of consumer-created content is becomin…More

*** 481

[[http://Nongnu.org/fcp/]]
An effort to create a complete K-12 curriculum and set of course materials that are "Free" in t…More

*** 482

[[http://Nongnu.org/emacs-tiny-tools/]]
A collection of information about Emacs providing links to Emacs related papers, Emacs lisp dev…More

*** 483

[[http://Th.nao.ac.jp/MEMBER/zenitani/emacs-e.html]]
Carbon/OSX distribution of GNU Emacs. Downloads, list of included libraries and FAQs.

*** 484

[[http://Poynter.org/how-tos/digital-strategies/web-tips/21421/wikipedia-for-journalists/]]
Proclaims that the use of Wikipedia is a good source for basic background information for journ…More

*** 485

[[http://Freecode.com/projects/fireparse]]
Emails a report of all packets that have been logged by the kernel's ipchains or iptables packe…More

*** 486

[[http://Rediris.es/webber/about/]]
An environment for producing and maintaning the contents and metadata of Web pages. (Perl)

*** 487

[[http://Opensource.org/licenses/artistic-license.php]]
Perl package license.

*** 488

[[http://Opensource.org/docs/osd]]
A definition of the Open Source license for software.

*** 489

[[http://Static.fsf.org/fsforg/rss/news.xml]]
Official news and announcements from the FSF.

*** 490

[[http://Itworld.com/040614wikipedia]]
Chinese censors have blocked access to Chinese Wikipedia that was created as a free and open so…More

*** 491

[[http://Linuxtoday.com/news_story.php3]]
News related to Open Source software and community (continuous, +email)

*** 492

[[http://Webreference.com/new/opencode.html]]
Fans of free software and music found some allies this weekend who said if lawmakers don't unde…More

*** 493

[[http://Isc.org/software/bind]]
Widely-used DNS server software, and related tools. (C) [Many platforms]

*** 494

[[http://Wiki.laptop.org/go/Browse]]
Describes the OLPC Web Browser. Usage, support, known bugs and development state.

*** 495

[[http://Gasp.ow2.org]]
News, information and downloads for this Java based mobile gaming platform. (Java)

*** 496

[[http://Sourcewatch.org/wiki.phtml]]
Collaborative directory of people, organizations and issues shaping the public agenda. Catalogs…More

*** 497

[[http://Browserg.mozdev.org]]
Integrates functionalities such as file sharing and instant messaging in one environment.

*** 498

[[http://Firstmonday.org/ojs/index.php/fm/article/view/709]]
This paper makes the political and ethical case for the adoption of free software by Community …More

*** 499

[[http://Firstmonday.org/issues/issue8_8/cedergren/index.html]]
Article by Magnus Cedergren discusses models involving the driving forces in a theoretical open…More

*** 500

[[http://Firstmonday.org/ojs/index.php/fm/article/view/961]]
Scientific illustration and analysis of socio-technical approaches that make up a collaborative…More

* Programming

** C++

- [[https://www.youtube.com/playlist?list=PL0lO_mIqDDFXNfqIL9PHQM7Wg_kOtDZsW][С++ программирование / Уроки C++]]

* Security search

- [[https://www.shodan.io/][Shodan]]

* Firewall

- [[http://wiki.ipfire.org/en/configuration/firewall/blockshodan][How to block Shodan scanners wiki.ipfire.org]]]

* Software comparisons

- [[https://www.slant.co/][Home - Slant]]

* Filemanagers

** ranger

- [[https://github.com/ralesi/ranger.el][ralesi/ranger.el: Bringing the goodness of ranger to dired!]]

* VPN

** sshuttle

#+BEGIN_QUOTE
Transparent proxy server that works as a poor man's VPN. Forwards over ssh.
Doesn't require admin. Works with Linux and MacOS. Supports DNS tunneling.
#+END_QUOTE

- [[https://github.com/apenwarr/sshuttle][apenwarr/sshuttle: Transparent proxy server that works as a poor man's VPN. Forwards over ssh. Doesn't require admin. Works with Linux and MacOS. Supports DNS tunneling.]]

* Authentication systems

- [[https://www.freeipa.org/page/Main_Page][FreeIPA]]

* Screenrecording

** vokoscreen

#+BEGIN_QUOTE
vokoscreen is an easy to use screencast creator to record educational videos,
live recordings of browser, installation, videoconferences, etc.
http://linuxecke.volkoh.de/vokoscreen/vokoscreen.html
#+END_QUOTE

- [[https://github.com/vkohaupt/vokoscreen][vkohaupt/vokoscreen: vokoscreen is an easy to use screencast creator to record educational videos, live recordings of browser, installation, videoconferences, etc.]]
