* ChatGPT

** How to configure postfix to use specific IP address for sending messages?

To configure Postfix to use a specific IP address for sending messages, you can use the smtp_bind_address configuration parameter.

Here are the steps to configure Postfix to use a specific IP address:

    Edit the Postfix configuration file /etc/postfix/main.cf using your favorite text editor.

    Add the following line to the configuration file:

    makefile

smtp_bind_address = 192.168.1.100

Replace 192.168.1.100 with the IP address you want to use for sending email.

Save and close the configuration file.

Reload the Postfix configuration by running the following command:

swift

sudo systemctl reload postfix

Alternatively, you can restart the Postfix service by running the following command:

swift

    sudo systemctl restart postfix

Postfix will now use the specified IP address for sending email. Note that if you have multiple network interfaces or IP addresses, you may need to configure additional settings to ensure that Postfix uses the correct interface for outgoing email.

** What settings do you mean?

If you have multiple network interfaces or IP addresses, you may need to configure additional settings to ensure that Postfix uses the correct interface for outgoing email. Here are some additional settings you may need to configure:

    smtp_bind_address6: If you have IPv6 enabled and want to use a specific IPv6 address for outgoing email, you can use the smtp_bind_address6 parameter in a similar way to smtp_bind_address.

    inet_interfaces: This parameter specifies the network interface(s) on which Postfix listens for incoming email. By default, Postfix listens on all available network interfaces. To limit Postfix to a specific interface, you can set inet_interfaces to the IP address of the interface you want to use.

    sender_dependent_default_transport_maps: This parameter allows you to specify different transports (e.g. SMTP, LMTP) for different sender addresses or domains. This can be useful if you need to use different IP addresses or network interfaces for outgoing email based on the sender.

    relayhost: If you are using a relay server to send outgoing email, you can configure the relayhost parameter to specify the hostname or IP address of the relay server. Note that the smtp_bind_address parameter will not have any effect if you are using a relay server.

By configuring these parameters, you can ensure that Postfix uses the correct network interface or IP address for outgoing email, based on your specific requirements.

** How to redirect to email specified in header in Postfix?

To redirect email to an address specified in the message header in Postfix, you can use the header_checks configuration parameter.

Here are the steps to configure Postfix to redirect email to an address specified in the header:

    Edit the Postfix configuration file /etc/postfix/main.cf using your favorite text editor.

    Add the following lines to the configuration file:

    javascript

header_checks = regexp:/etc/postfix/header_checks
canonical_maps = regexp:/etc/postfix/canonical

The header_checks parameter specifies a regular expression file that defines the rules for redirecting email based on the message header. The canonical_maps parameter specifies a regular expression file that defines the rules for canonicalizing email addresses.

Create the file /etc/postfix/header_checks and add the following line:

css

/^To:.*@redirect\.example\.com/ REDIRECT ${1}@example.com

This regular expression matches email messages where the To: header contains the domain redirect.example.com, and replaces it with ${1}@example.com. The ${1} variable is a backreference to the email address specified in the original To: header.

Create the file /etc/postfix/canonical and add the following line:

ruby

/@redirect\.example\.com$/ ${1}@example.com

This regular expression canonicalizes any email addresses with the domain redirect.example.com to example.com.

Save and close the configuration files.

Reload the Postfix configuration by running the following command:

swift

sudo systemctl reload postfix

Alternatively, you can restart the Postfix service by running the following command:

swift

    sudo systemctl restart postfix

Postfix will now redirect any email messages where the To: header contains the domain redirect.example.com to the corresponding address in the example.com domain.

: kubectl -n mailout exec pod/postfix-mailout-jhcp8 /nix/store/nzg3950pbjw410zm5bn6ji6xm7h8a4kh-postfix-3.7.3/bin/mailq | grep -B1 noreply@foobar.ru | awk '/MAILER-DAEMON/ { print $1 }' | sed 's/\*//' | { while true; do read id; kubectl -n mailout exec pod/postfix-mailout-jhcp8 -- /nix/store/nzg3950pbjw410zm5bn6ji6xm7h8a4kh-postfix-3.7.3/bin/postsuper -c /etc/postfix -d "$id"; done; }

/nix/store/nzg3950pbjw410zm5bn6ji6xm7h8a4kh-postfix-3.7.3/bin/mailq | /nix/store/njz77ksdp38vy6wyb9bq70dzfjxm5im0-gnugrep-3.7/bin/grep -B1 noreply@foobar.ru | /nix/store/pndr3yb60iqx4igydv2irxi6s6y8rbvb-gawk-5.1.1/bin/awk '/MAILER-DAEMON/ { print $1 }' | /nix/store/scmjiz80b1hh521k06z4fgbkl6r5k84p-gnused-4.8/sed 's/\*//' | { while true; do read id; /nix/store/nzg3950pbjw410zm5bn6ji6xm7h8a4kh-postfix-3.7.3/bin/postsuper -c /etc/postfix -d "$id"; done; }

* Cheat sheet

Работа с очередью сообщений в Postfix
Обновлено Обновлено: 11.03.2020 Опубликовано Опубликовано: 13.06.2017
Посмотреть очередь

mailq

или:

postqueue -p
Принудительно запустить отправку из очереди

mailq -q

или: 

postqueue -f
Очистить очередь

1. Удалить все сообщения:

postsuper -d ALL

2. Удалить определенное письмо из очереди:

postsuper -d <идентификатор письма>

* идентификатор письма можно увидеть командой mailq.

3. Очистить очередь по отправителю:

postqueue -p | tail -n +2 | awk 'BEGIN { RS = "" } /spammer@email\.com/ { print $1 }' | tr -d '*!' | postsuper -d -

* в данном примере мы удалим все письма от spammer@email.com.
Количество писем в очереди

Команда mailq в конце выдает общее количество сообщений в очереди, например:

-- 23 Kbytes in 18 Requests.

* в данном примере в очереди находится 18 сообщений общим объемом 23 Кбайт.

Также, очередь можно посмотреть командами:

find /var/spool/postfix/deferred -type f | wc -l

find /var/spool/postfix/active -type f | wc -l

find /var/spool/postfix/incoming -type f | wc -l

find /var/spool/postfix/defer -type f | wc -l

* данные каталоги являются местом, где временно хранятся письма очереди.
Перезапустить очередь

postsuper -r ALL

Если не помогло, поочередно:

postfix stop

postsuper -r ALL

postfix start
Настройка очереди

Задать периодичность повторной отправки сообщений:

postconf -e "queue_run_delay = 5m"

Задать время, на которое будет отложена отправка сообщений, которые не были отправлены по причине временных неисправностей (например, принимающий сервер не отвечает или просит повторить запрос позже):

postconf -e "minimal_backoff_time = 10m"

Задать максимальное время для отправки сообщений, которые не были отправлены по причине временных неисправностей:

postconf -e "maximal_backoff_time = 15m"

Выставить время жизни для сообщения в очереди:

postconf -e "maximal_queue_lifetime = 1d"

После внесения изменений необходимо перезапустить postfix:

service postfix restart || systemctl restart postfix
Информация о конкретном сообщении

postcat -q <идентификатор>

Причины, по которым письма не отправляются, могут быть самыми разными. Если вы устранили причину и хотите принудительно отправить всю почту то используйте команду:

postsuper -r ALL deferred

Для удаления всех писем из очереди deferred используйте команду:

postsuper -d ALL deferred

* ChatGPT

** postfix show message content

To view the content of a message in Postfix, you can use the postcat command.

First, find the queue ID of the message that you want to view:

sudo postqueue -p

This will display a list of messages in the queue, along with their queue IDs (such as 5A7C7123456). Note down the queue ID of the message you want to view.

Then, use the postcat command with the queue ID to display the content of the message:

sudo postcat -vq <queue_id>

This will display the full content of the message, including the headers and body. You can then scroll through the output to view the message content.
