* Misc
:PROPERTIES:
:ID:       1e10d594-ef08-4dae-8a87-1cdfaf83aa7a
:END:

- [[https://fogproject.org/][FOG Project]]

- [[https://ipxe.org/scripting][iPXE - open source boot firmware [scripting]]]
- [[https://ipxe.org/cmd][iPXE - open source boot firmware [cmd]]]
- [[https://ipxe.org/cfg][iPXE - open source boot firmware [cfg]]]
- [[https://github.com/poseidon/matchbox][poseidon/matchbox: Network boot and provision Fedora CoreOS and Flatcar Linux clusters]]
- [[https://github.com/wentasah/novaboot][wentasah/novaboot: A tool that automates booting of operating systems on target hardware or in qemu]]
- [[https://github.com/samdbmg/dhcp-netboot.xyz][samdbmg/dhcp-netboot.xyz: Docker container that acts as a ProxyDHCP server for netbooting]]
- [[https://github.com/netbootxyz/docker-netbootxyz][netbootxyz/docker-netbootxyz: netboot.xyz docker container]]
- [[https://github.com/NickCao/netboot][NickCao/netboot]]
- [[https://github.com/ltsp/ltsp][ltsp/ltsp: LTSP code, issues and discussions]]
- [[https://www.theurbanpenguin.com/pxelinux-using-proxy-dhcp/][PXELinux using Proxy DHCP - The Urban Penguin]]

* 

** Windows 10 IPXE Boot

   https://docs.j7k6.org/windows-10-pxe-installation/

My Sysadmin Cheatsheet

«Who were you, DenverCoder9? — What did you see?» (xkcd/979)
PXE Boot & Install Windows 10 from a Samba Share
Prerequirements

This guide is based on this setup. The steps for configuring dnsmasq and pxelinux have to be completed to make booting the Windows Installer over the network work. There also needs to be a Windows 10 x64 ISO available on the Debian box.

    Install packages:

    apt-get update
    apt-get install -y samba genisoimage wimtools cabextract

    Link mkisofs:

    ln -s /usr/bin/genisoimage /usr/bin/mkisofs

    Create direcories:

    mkdir -p /mnt/waik
    mkdir -p /var/lib/tftpboot/windows

Prepare Windows PE ISO

    Download the Windows Automated Installation Kit (WAIK) ISO:

    wget https://download.microsoft.com/download/8/E/9/8E9BBC64-E6F8-457C-9B8D-F6C9A16E6D6A/KB3AIK_EN.iso

    Mount KB3AIK_EN.iso:

    mount KB3AIK_EN.iso /mnt/waik

    Generate Windows PE bootable ISO:

    mkwinpeimg --iso --arch=amd64 --waik-dir=/mnt/waik /var/lib/tftpboot/winpe.iso

    Unmount KB3AIK_EN.iso:

    umount /mnt/waik

Samba

    Edit /etc/samba/smb.conf:

    [global]
      workgroup = WORKGROUP
      map to guest = bad user
      usershare allow guests = yes

    [windows]
      browsable = true
      read only = yes
      guest ok = yes
      path = /var/lib/tftpboot/windows

    Restart samba service:

    systemctl restart smbd

    Mount Windows 10 ISO onto samba share:

    mount <WINDOWS_ISO> /var/lib/tftpboot/windows

pxelinux

    Link memdisk:

    ln -s /usr/lib/syslinux/memdisk /var/lib/tftpboot/

    Edit /var/lib/tftpboot/pxelinux.cfg/default:

    LABEL windows10
    MENU LABEL Windows 10
    KERNEL /memdisk
    INITRD /winpe.iso
    APPEND iso raw

Windows Installation

    Boot with PXE
    Wait for DHCP assigned IP (check with ipconfig)
    Mount Samba share:

    net use Z: \\192.168.1.10\windows

    Run z:\setup.exe
    Install Windows.

    http://it-joe.com/windows/pxe_install
    http://www.webupd8.org/2013/07/how-to-create-bootable-windows-pe-iso.html
    https://www.savelono.com/linux/how-to-install-windows-7-over-a-network-using-linux-pxe-dnsmasq-and-samba.html
    https://github.com/pimterry/rpi-pxe-server

    ♥ 2013-2019 — @j7k6 

** config examples

   label clonezilla
      linux memdisk
      initrd clonezilla-live-2.6.0-37-i686.iso
      append iso
   label kali
         linux memdisk
         initrd kali-linux-2018.2-amd64.iso
         append iso
   label other
         chain --autofree https://boot.netboot.xyz

** 

https://serverdoma.ru/viewtopic.php?t=879

** 

https://www.ameir.net/blog/archives/402-install-windows-using-netboot-xyz.html
First, get source machine ready to provide Windows installer to target machine.

ISO_DIR=~/Downloads

# disable firewall (I’m on macOS; do the equivalent on your OS)
sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 0

cd $ISO_DIR

# launch Samba container to share mounted image
docker run -d -p 139:139 -p 445:445 -v $ISO_DIR:/mount dperson/samba -s ‘public;/mount’ -u ‘user;password’

# mount ISO image locally for use by netboot.xyz
hdiutil mount -mountpoint ./win10/x64/ ./win10.iso

# start local web server
python -m SimpleHTTPServer 8000

On target machine:
Boot up netboot.xyz via USB or other media. Under “Signature Checks,” disable checking of Images. I was unable to get this to work correctly.
Go to Windows section, and set base URL to “http://:8000/win10”.

Select “Load Microsoft Windows Installer”.
netboot.xyz will download some binaries from the internet, and load the remaining binaries from your source machine over HTTP. You’ll see those requests in the Python server console.
remove usb after installer loads
shift + f10
wpeinit
net use S: \\\public\win10 /user:user password # wasn’t able to do anonymous login (system error 58)
S:\x64\sources\setup.exe

** 

https://docs.j7k6.org/windows-10-pxe-installation/
