:PROPERTIES:
:ID:       faa318df-a124-4624-bf47-7551319a9d6b
:END:
#+title: RAID

- [[https://altastor.ru/apps/raidcalc/][Калькулятор RAID]]
- [[https://wintelguy.com/raidcalc.pl][RAID Capacity Calculator - WintelGuy.com]]
- [[https://en.wikipedia.org/wiki/Nested_RAID_levels][Nested RAID levels - Wikipedia]]

- Copy disk partition information
: sfdisk -d /dev/sdb | sfdisk /dev/sda

- Scan disks
: echo "- - -" > /sys/class/scsi_host/host0/scan

- Add disk to raid
: mdadm /dev/md0 --add /dev/sda1

: partprobe /dev/sdd
: mount | grep sdd
: mdadm /dev/md127 --fail /dev/sdd1
: mdadm /dev/md0 --fail /dev/sda1
: mdadm /dev/md0 --remove /dev/sda1

- Disconnect disk
: echo 1 > /sys/block/sda/device/delete

- for i in {1..8}; do smartctl -a /dev/sg$i; done
- [[https://blog.tinned-software.net/replace-hard-disk-from-software-raid/][Replace hard disk from software RAID - Experiencing Technology]]
- # mdadm --create --verbose --level=5 --metadata=1.2 --chunk=256 --raid-devices=4 /dev/md/md0 /dev/sdb1 /dev/sdc1 /dev/sdd1 /dev/sde1
  note that could use devices derictly

- fail and remove disk
#+begin_example
root@mj744:~# mdadm /dev/md0 --fail /dev/sda1
mdadm: set /dev/sda1 faulty in /dev/md0
root@mj744:~# cat /proc/mdstat                                                                                                                                            
Personalities : [raid10] [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4]
md0 : active raid10 sdb1[1] sda1[0](F) sdd1[3] sdc1[2]                                                                                                                    
      999948288 blocks super 1.2 512K chunks 2 near-copies [4/3] [_UUU]
      bitmap: 5/8 pages [20KB], 65536KB chunk               
                             
unused devices: <none>                                          
root@mj744:~# mdadm /dev/md0 --remove /dev/sda1
mdadm: hot removed /dev/sda1 from /dev/md0
#+end_example

- create raid 1 with missing disk
: mdadm --create --verbose --level=1 --metadata=1.2 --raid-devices=2 /dev/md/1 /dev/sda1 missing
#+begin_example
root@mj744:~# mdadm --create --verbose --level=1 --metadata=1.2 --raid-devices=2 /dev/md/1 /dev/sda1 missing                                                              
mdadm: /dev/sda1 appears to be part of a raid array:
       level=raid10 devices=4 ctime=Tue Jun  2 14:45:26 2020
mdadm: size set to 499974144K
mdadm: automatically enabling write-intent bitmap on large array
Continue creating array? y
mdadm: array /dev/md/1 started.
#+end_example

* [[https://unix.stackexchange.com/questions/190264/disassemble-a-raid-1-arragement-without-removing-reinstalling-the-system][Disassemble a RAID 1 arragement without removing/reinstalling the system - Unix & Linux Stack Exchange]]
Just fail and remove one of your drives:

  mdadm /dev/md0 --fail /dev/sdb --remove /dev/sdb

After that change your /etc/fstab to use the drive left in RAID.

Reboot. And then destroy your RAID:

  mdadm /dev/md0 --destroy

* Debian 10

: apt install linux-image-4.19.0-16-amd64
: modprobe raid1

scan for raid md devices
#+begin_example
  root@debian:~# mdadm --assemble --scan
  mdadm: /dev/md/mj744:0 has been started with 2 drives (out of 4).
  mdadm: /dev/md/mj744.lex1.ru:1 has been started with 2 drives.
#+end_example

* Raid5 mdadm array change size

[[https://unix.stackexchange.com/questions/607104/raid5-mdadm-array-change-size][Raid5 mdadm array change size - Unix & Linux Stack Exchange]]

I have created a raid5 array with 4 disks. Initially i had 3x 3tb and 1x 4tb
(because 3tb was unavailable at the time). After some years i have replaced
most of these disks and have come to the point where all array disks are now
4tb in size. Still my mdadm array is 3TB. Is there any way to change the mdadm
array size to match the 4tb disk size w/o loosing my data? Thanks for your
help!

If you have a write-intent bitmap, remove it

  mdadm --grow /dev/mdX --bitmap none

Then grow the array

 mdadm --grow /dev/mdX --size max

Finally, restore the bitmap if you were using one

 mdadm --wait /dev/mdX
 mdadm --grow /dev/mdX --bitmap internal

This is all from the RAID Wiki

Things are different if your RAID is on partitions rather than full disks, as
you'll have to remove, resize, and then re-add each disk in turn. Wait for a
full resync after each disk partition has been extended

Finally you'll need to grow the filesystem or PV that site on top of your
RAID. (You can do this any time after the second step.)
