:PROPERTIES:
:ID:       94ccad4e-bdc0-4d4b-b799-ebe02f864fd8
:END:
#+title: Russia

- [[https://megapolisonline.ru/][Информационный портал: «Мегаполис» – Городская сеть информирования и взаимопомощи.]]

- https://vk.com/domskurantami?w=wall-64552396_43385%2Fall
Справа серым колпачком. Закручивать или ослаблять. Он давит на штырек. А
вообще лучше заменить его на термоголовку danfoss ra2994 (013g2994).

- [[https://www.youtube.com/watch?v=9ZMAWRkZyb8][ЗАПОЛНЕНИЕ 3-НДФЛ ОНЛАЙН В ЛИЧНОМ КАБИНЕТЕ НАЛОГОПЛАТЕЛЬЩИКА В 2021 ГОДУ / НАЛОГОВЫЙ ВЫЧЕТ - YouTube]]

- gos.sdrav.spb.ru

- [[https://vk.com/public73442711][Госуслуги Группа vk.com]]

* Shooping
- [[https://helpix.ru/currency/][Курс доллара Aliexpress и других китайских магазинов - Helpix]]
** Law
- [[https://praktikamsk.ru/articles/spory_po_postavke/nepostavka_tovara/][Непоставка товара – что делать если поставщик не поставил товар]]
- [[https://www.rusprofile.ru/][Проверка и анализ российских юридических лиц и предпринимателей]]
** Shops
- [[https://play.google.com/store/apps/details?id=ru.crptech.mark][Chestny ZNAK – Quality Control - Apps on Google Play]]
- [[https://spb.price.ru/][Цены, товары, скидки, все интернет-магазины Санкт-Петербурга на Price.ru]]
- [[https://www.onlinetrade.ru/][Интернет-магазин ОНЛАЙН ТРЕЙД.РУ. Покупай всё онлайн!]]
** Browser addons
- [[https://mayak.bz/][Сервис аналитики продаж на маркетплейсах Маяк — сервис для анализа статистика товаров на Wildberries и Ozon]]

* Relocation

- [[https://www.youtube.com/watch?v=rZ3-v5gSVQQ][(3) Как получить второе гражданство в 2022 - YouTube]]
- [[https://dzen.ru/a/ZDW3Z7cyj1L1lifE][Снятие с воинского учета для лиц, выезжающих/выехавших за пределы РФ | UT.Atty - Юридическая помощь бизнесу и физическим лицам | Дзен]]

* Money

** Налоги
Если в год больше 600к по картам будет приходить непонятные переводы то могут вызвать к инспектору.

** Оформление заружебежной карты
*** Именная карта
попросить сразу открыть именную карту.

Необходимо:
1. Оригинал загранпаспорта.
2. Местная симкарта.
3. Оригинал или ксерокопия русского паспорта со страницей прописки.
4. налоговый номер, который можно оформить онлайн [[https://www.youtube.com/watch?v=xFVZfdqJ-QE][(75) Как открыть карту за
   границей. Реально ли открытие счета за рубежом? - YouTube]].

*** Виртуальная карта
Виртуальная карта ласвегаса делается за 5 минут и пополняется криптой, платишь любые сервисы покупки.

** [[https://telegra.ph/Kak-otkryt-kartu-VisaMasterCard-za-rubezhom--Belarus-07-19][Как открыть карту Visa/MasterCard за рубежом — Беларусь  – Telegraph]]

** [[https://github.com/codez0mb1e/resistance][codez0mb1e/resistance: Pre-crisis Risk Management for Personal Finance]]

* Government

- [[https://digital.gov.ru/ru/activity/govservices/1/#section-list-of-accredited-organizations][Аккредитация ИТ-компаний :: Министерство цифрового развития, связи и массовых коммуникаций Российской Федерации]]
- [[https://fsa.gov.ru/][Федеральная служба по аккредитации]]
- [[https://secrets.tinkoff.ru/voprosy-otvety/reestr-rossijskogo-po/][Регистрация в реестре российского ПО: перечень документов для подачи заявления, сроки процедуры и требования к разработчикам]]

** Rules
- [[https://whoosh-bike.ru/new-rules][Подробный разбор новых ПДД в России]]

** Military

Как стать автором
Студента не уволишь: чему преподавание учит айтишников и менеджеров
Все потоки
Разработка
Администрирование
Дизайн
Менеджмент
Маркетинг
Научпоп
sergzah
2 часа назад
Снятие с воинского учета. Дистанционно. Пакет документов
Простой
5 мин
2K
IT-эмиграция Законодательство в IT
Туториал

По состоянию на лето 2023, в военных комиссариатах разных регионов и даже районов требования к пакету документов отличаются, запись через Госуслуги может не работать, без личного присутствия заявителя могут вообще не разговаривать. Информация ниже не является полным гайдом по снятию с учета, это скорее рекомендации из практики, которые помогут грамотно подготовить пакет документов.

Если вкратце, то рабочий кейс, это когда:

    имеется основание для снятия: уже живете зарубежом полгода, либо имеется иностранный ВНЖ,

    грамотно составлено заявление на снятие с учета и подписано вашей подписью,

    в военкомат идет ваш представитель по доверенности, которая оформлена у российского нотариуса или в зарубежном консульстве РФ.

Если вы находитесь зарубежом – то доверенность на представителя лучше оформлять в консульстве РФ. Такая доверка имеет вид обычной, сделанной у российского нотариуса, на бланке, имеет серию, номер, qr-код. Только такие доверенности принимают без вопросов. Можно оформить доверенность по правилам иностранного государства, перевести на русский язык и ссылаться на Договоры о взаимной правовой помощи и Минские конвенции. Да, в теории это прекрасно и работает в ряде сфер, но в военкоматах будут отказывать по причине ненадлежаще оформленных документов и невозможности установить полномочия представителя.

Для избежания дискуссий и отказов, в доверенности должны быть четко указаны "военные комиссариаты и их структурных подразделения, призывные комиссии", а также права "подавать заявления, в том числе о снятии с воинского учета", "подавать оригиналы документов, в том числе приписное свидетельство, военный билет", "получать за меня справки, в том числе Справку о снятии с воинского учета военнообязанного, убывающего за пределы РФ".
Образец доверенности на представителя в РФ

Рекомендуется также сделать нотариально заверенную копию доверенности, чтобы оставить ее в ВК при необходимости.

Рекомендуется сделать нотариально заверенную копию военного билета / приписного свидетельства, т.к. при снятии с учета документ сдается в ВК на хранение. Основной риск в том, что в документ без вашего ведома могут быть внесены изменения, например другая ВУС.

Нотариальные копии паспорта и загранпаспорта делать не нужно, таких требований нет. 

Нужно приложить копию всех страниц загранпаспорта. Если у вас их два – то возможно оба, но четких требований на этот счет нет. Главное – должны быть проставлены штампы о выезде и выезде; по ним должно быть четко понятно, что вы отсутствовали за пределами РФ полгода; а если и возвращались обратно в РФ – то каждый раз не более чем на 12 дней (даты приезда и отъезда являются спорным моментом, потому 14-2).

Факт проживания за пределами РФ более полугода является основанием для снятия с учета согласно п.6 ст.22 Приказа Министра обороны РФ от 22.11.2021 No.700.

Если имеется, нужно приложить копию иностранного ВНЖ, паспорта или иного документа. К иным документам относятся разрешение на работу (например, workpermit.am в Армении) или разрешение на временное проживание (например, в Казахстане), и не относятся долгосрочные визы и digital nomad сертификаты (например, QR-код в Киргизии). Перевод, нотариальный перевод или нотариальное заверение документа не требуются.

Факт наличия локального документа является основанием для снятия с учета согласно п.5 ст.22 Приказа Министра обороны РФ от 22.11.2021 No.700.

Рекомендуется приложить копию отрывную часть Уведомления в МВД о наличии ВНЖ, гражданства или иного документа по форме Приложения 2 к приказу МВД России от 31.12.2019 N 994.
Образец отрывной части уведомления

FYI. И если еще не подавали уведомление в РФ о наличии иностранного ВНЖ – разумно его подать, особенно если документ получен в стране ЕАЭС ввиду обмена информацией. Это можно сделать через представителя по доверенности в любом отделении Почты РФ. За не подачу уведомления предусмотрена уголовная ответственность по ст.330.2 УК РФ.

Подготовить Заявление о снятии с учета, форма заявления представлена в Приложении 14 к Приказу МО РФ от 22.11.2021 N 700.
Образец Заявления о снятии с учета

Во-первых, грамотно указать причину снятия в пункте 6:

(А) если есть ВНЖ:

6. Прошу снять меня с воинского учета в связи с:

убытием на постоянное проживание за пределы Российской Федерации на срок более шести месяцев и в связи с получением вида на жительство иностранного государства (п.5 и п.6 ст.22 Приказа Министра обороны РФ от 22.11.2021 No.700).

(B) если нет ВНЖ:

6. Прошу снять меня с воинского учета в связи с:

убытием на постоянное проживание за пределы Российской Федерации на срок более шести месяцев (п.6 ст.22 Приказа Министра обороны РФ от 22.11.2021 No.700).

Во-вторых, в пункте 4 указать свой адрес проживания зарубежом. Это важная формальность, но никто не будет просить его подтвердить или высылать туда письма.

В-третьих, в пункте 5 нужно указать место работы зарубежом. Аналогично.

Крайне рекомендуется прикладывать сопроводительное письмо.
Сопроводительное письмо в ВК

В письме сослаться на следующие положения (прямо процитировать в тексте письма):

п.1 ст.8 Федерального закона "О воинской обязанности и военной службе" от 28.03.1998 No.53-ФЗ, согласно которому, граждане, постоянно проживающие за пределами Российской Федерации не обязаны состоять на воинском учете.

абз.2 п.53 раздела IX Постановления Правительства РФ от 27.11.2006 No.719 "Об утверждении Положения о воинском учете", согласно которому, настоящее Заявление является основанием для снятия с воинского учета по причине убытия на постоянное проживание за пределы Российской Федерации на срок более шести месяцев и в связи с получением вида на жительство иностранного государства.

п.5 и п.6 ст.22 Приказа Министра обороны РФ от 22.11.2021 No.700 "Об утверждении Инструкции об организации работы по обеспечению функционирования системы воинского учета", согласно которому прилагаются:
- заявление о снятии с воинского учета,
- копия главного разворота общегражданского паспорта серия ХХХХ номер ХХХХХХ,
- копия отрывной части Уведомления о наличии у гражданина Российской Федерации вида на жительство от ХХ.ХХ.ХХХХ,
- копия заграничного паспорта номер ХХ ХХХХХХХ с отметками пограничного контроля в качестве документа, подтверждающего выезд за пределы территории Российской Федерации.

Если была направлена повестка, по которой вы не явились в ВК, рекомендуется это указать:

Ввиду того, что я не нахожусь на территории Российской Федерации более 6 месяцев с ДД.ММ.ГГГГ, требование о личной явке меня в Комиссариат ДД.ММ.ГГГГ по повестке серии ХХ №ХХХХХХХХХ не могло быть исполнено ввиду ненадлежащего информирования и наличия уважительной причины.

Если вам не выдавали военный билет / приписное удостоверение (такое бывает, если вы получали отсрочки по состоянию здоровья или судились с ВК), то сдавать будет нечего и рекомендуется указать:

Ввиду отсутствия на руках у меня соответствующих документов воинского учета по причине их невыдачи, имею основания полагать что соответствующие документы  могут находиться в Комиссариате, в готовом виде или на стадии оформления.

Отдельно нужно написать, что результат просите выдать представителю на руки, указать данные представителя и доверенности.

Письмо подготовить в 2х экземплярах.

Рекомендуется сделать два комплекта документов: один подписать лично, второй комплект пусть подпишет представитель, укажет данные доверенности и приложит ее копию. В некоторых ВК требуют, чтобы документы были подписаны непосредственно гражданином, а подавать их может представитель по доверенности. В каких-то даже готовы получить документы обычным почтовым отправлением. Если работники в ВК адекватны и работают согласно законодательства РФ и приказов МО – то примут заявление о снятии и выдадут справку без осложнений. В противном случае, нужно подать весь комплект документов в приемную (или канцелярию) ВК, чтобы поставили на 2м экземпляре штампик с датой, номером входящего, фио, должность и подпись сотрудника ВК.

Результатом является Справка о снятии с учета:

p.s. информация изначально и вкратце была в виде моего коммента здесь: https://habr.com/ru/articles/731480/comments/#comment_25508012

Теги:

    военкоматснятие с учетазаявлениевнждоверенностьвоенный билетвоенный комиссариатПриказ Министра оборонысправка 

Хабы:

    IT-эмиграцияЗаконодательство в IT 

Редакторский дайджест

Присылаем лучшие статьи раз в месяц
48
Карма
3
Рейтинг
Sergey Zakharov @sergzah

#crypto #fintech #it консалтинг
Сайт Сайт Facebook Telegram
Комментарии 4
Firsto
1 час назад

Через госуслуги возможно?
0
MiraclePtr
1 час назад

В госуслугах есть такая функция, но 1) оно работает только для подачи заявления, потом все равно надо чтобы кто-то с доверенностью пришел и принес оригиналы документов и военник 2) как пишут, многие военкоматы обращения через госуслуги просто игнорируют и на них не отвечают.

Но попробовать можно.

+2
edogs
1 час назад

Является ли проживание в Белоруссии основанием для снятия с воинского учета (страна-то вроде другая) и достаточно ли договора длительной аренды как доказательства долговременного отсутствия в россии (внж же там вроде не получить, а на границе штамп не ставят)?
0
Kodim
50 минут назад

Является, сам так снялся с учета как офицер запаса, но внж рекомендую получить, всем гражданам РФ выдают без специальных условий

0
Только полноправные пользователи могут оставлять комментарии. Войдите, пожалуйста.
Публикации

    0serg
    9 часов назад
    Ортографическая проекция в фотографии и прочие интересные фокусы с объективами
    Средний
    29 мин
    2.4K
    Обзор
    +53

7
+7
ru_vds
6 часов назад
Лучший софт для автоматизации скриншотов
Простой
6 мин
2.2K
Кейс
+17
15
+15
vladkorotnev
7 часов назад
Что внутри у однорукого бандита? Разборка, моддинг, и написание кейгена. [Part 1]
Простой
8 мин
1.7K
Обзор
+17
8
+8
Underskyer1
4 часа назад
Теория типов
Средний
43 мин
1.3K
Из песочницы
+14
6
+6
headmusic
5 часов назад
Электростаты — электростатические наушники, как это работает?
Средний
6 мин
1.5K
Из песочницы
+11
1
+1
AndreyKotlov
19 часов назад
Что такое арбитраж? Передовые технологии торговли на примере криптобиржи
Сложный
31 мин
2.1K
Аналитика
+9
7
+7
sergzah
2 часа назад
Снятие с воинского учета. Дистанционно. Пакет документов
Простой
5 мин
2K
Туториал
+6
4
AlexChroot
вчера в 19:00
Переписываем наш Object Cloud
Средний
8 мин
695
Туториал
+6
0
hyperon1
2 часа назад
Поиск под(от)круток в World of Tanks
Средний
7 мин
1.1K
Из песочницы
+4
2
+2
mssqlhelp
вчера в 19:31
Новое в SQL Server 2022: Контейнерные группы доступности
Сложный
5 мин
1.3K
Обзор
+4

    1
    +1
    В назначенный день мы тронемся в путь: проверь свою SQL-экипировку
    Спецпроект 

Минуточку внимания
Турбо
Как небольшой компании расцвести на Хабре за полгода
Спецпроект
Проверь свою SQL-экипировку в тесте для аналитиков
Промо
Боги приковали Промокодуса за слишком щедрые скидки
Заказы

    Разработчик ботов Telegram, умение работать с ФРИКАССОЙ
    20000 руб./за проект2 отклика9 просмотров
    Наполнить сайт на Tilda товарами
    1000 руб./за проект5 откликов15 просмотров
    Подготовить codemagic.yaml для сборки iOS/Android приложения
    10000 руб./за проект1 отклик10 просмотров
    Разработка бекенда под IPTV плеер на smart tv
    35000 руб./за проект22 просмотра
    Разработать бекэнд и админку на популярном фреймворке
    68000 руб./за проект12 откликов54 просмотра

Больше заказов на Хабр Фрилансе
Читают сейчас

    Новое запретное слово из трех букв: VPN
    2.9K
    10
    +10
    Единственное в мире число-субфакторион — это 148349. Что это такое?
    123K
    76
    +76
    Снятие с воинского учета. Дистанционно. Пакет документов
    2K
    4
    YandexGPT тоже провалил тест на ручник
    28K
    63
    +63
    «Кандидат имеет право задавать уточняющие вопросы», или Доводим интервьюера до нервного срыва
    121K
    222
    +222
    В назначенный день мы тронемся в путь: проверь свою SQL-экипировку
    Спецпроект 

Истории
Перевернуть календарь и добавить событие
Топ-7 хороших статей из блогов компаний
Дарим вакансии для стажеров
Как учить детей программированию
Когнитивные искажения
Как рассказать о событии на Хабре
Как заварить кофе прямо в чашке

Ваш аккаунт

    Войти
    Регистрация 

Разделы

    Статьи
    Новости
    Хабы
    Компании
    Авторы
    Песочница 

Информация

    Устройство сайта
    Для авторов
    Для компаний
    Документы
    Соглашение
    Конфиденциальность 

Услуги

    Корпоративный блог
    Медийная реклама
    Нативные проекты
    Образовательные программы
    Стартапам
    Спецпроекты 

Техническая поддержка
Вернуться на старую версию
© 2006–2023, Habr

** Elections
*** Март 2024

* Internet

- [[https://censortracker.org/][Censor Tracker | Плагин для обхода блокировок от Роскомсвободы]]
- [[https://traceroute.net.ru/][Russian Looking Glass and Traceroute List]]
- [[https://github.com/bol-van/zapret][bol-van/zapret: Обход DPI в linux]]
- [[https://github.com/zapret-info/z-i][zapret-info/z-i: Register of Internet Addresses filtered in Russian Federation]]
- [[https://habr.com/ru/post/413049/][Настройка BGP для обхода блокировок, версия 3, без VPS / Хабр]]
  - [[https://habr.com/ru/post/549282/][Настройка BGP для обхода блокировок, версия 3.1. И немного Q&A / Хабр]]
    - [[https://antifilter.download/][antifilter.download]]
    - [[https://antifilter.network/][Antifilter]]
- [[https://reestr.rublacklist.net/record/3110436/][Реестр запрещенных сайтов]]
- [[https://censortracker.org/][Censor Tracker | Плагин для обхода блокировок от Роскомсвободы]]
- [[https://reestr.rublacklist.net/ru/?q=185.84.108.9][Реестр запрещенных сайтов]]
- [[https://ntc.party/t/ooni-reports-of-tor-blocking-in-certain-isps-since-2021-12-01/1477/4][OONI reports of Tor blocking in certain ISPs since 2021-12-01 - Internet censorship all around the world / Russia - NTC]]
- [[https://github.com/stopcenz/fakesni][stopcenz/fakesni: Программа для обхода блокировок путем модификации заголовков протокола TLS.]]
- [[https://rutracker.wiki/Retracker.local][Retracker.local — WikiTorrents]]
- [[https://rutracker.wiki/%D0%A7%D1%82%D0%BE_%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C,_%D0%B5%D1%81%D0%BB%D0%B8_%D0%B2%D0%B0%D0%BC_%D0%B7%D0%B0%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD_%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF_%D0%BD%D0%B0_rutracker.org#Brave_Private_Browser][Что делать, если вам заблокирован доступ на rutracker.org — WikiTorrents]]
- [[https://rutracker.org/forum/viewtopic.php?p=75274766#75274766][Обход блокировки bt*. трекеров (основные инструкции) :: RuTracker.org]]
- [[https://rutracker.org/forum/viewtopic.php?t=5376074][Socks5 с X-Forwarded-For+privoxy :: RuTracker.org]]
- [[https://steambuy.com/][STEAMBUY.COM - Интернет-магазин лицензионных игр]]
- [[https://github.com/ValdikSS/GoodbyeDPI][ValdikSS/GoodbyeDPI: GoodbyeDPI — Deep Packet Inspection circumvention utility (for Windows)]]
- [[https://97-fz.rkn.gov.ru/][Реестр организаторов распространения информации в сети «Интернет»]]
- [[https://habr.com/ru/articles/777656/][GOST: швейцарский нож для туннелирования и обхода блокировок / Хабр]]
- [[https://github.com/roskomsvoboda/censortracker][roskomsvoboda/censortracker: Censor Tracker is a censorship circumvention extension for Google Chrome and Mozilla Firefox.]]
  - [[https://habr.com/ru/companies/roskomsvoboda/articles/696734/][Большое обновление Censor Tracker / Хабр]]
- [[https://t.me/s/antifilter_download][Antifilter Download News – Telegram]]
  - [[https://t.me/+zbvV3elo99gzNzhi][Antifilter Private Group]]
- [[https://antizapret.prostovpn.org/][АнтиЗапрет — скажи цензуре нет!]]

** Censor
*** Закон о суверенизации Рунета
- сенаторам Андреем Клишасом
- сенаторам Людмилой Боковой
- депутатом Андреем Луговым

*** Steam
Через киви кошелек. Открываешь тенге счет переводишь туда деньги и оплачиваешь
стим в тенге и все покупаешь любую игру но надо преепалтить за конвертации 10%.

*** YouTube
В соответствии с ч. 1 ст. 11 ФЗ от 01.07.2021 № 236-ФЗ «О деятельности
иностранных лиц в информационно-телекоммуникационной сети «Интернет» на
территории Российской Федерации», Роскомнадзором принято решение об
информировании пользователей www.youtube.com, что иностранное лицо, владеющее
информационным ресурсом, является нарушителем законодательства Российской
Федерации.

* Registers
- [[https://bootsman.tech/][Боцман Клик - платформа для управления мультикластерами kubernetes]]

* Security
- [[https://moshelovka.onf.ru/][Мошеловка.рф - народный фронт против мошенничества]]
