* Photo
:PROPERTIES:
:ID:       f463f542-9f6e-474d-a41d-38bf31b5332e
:END:

- [[https://blog.scaleway.com/40-open-source-projects/][40+ of the best open-source tools to build your startup]]
- [[https://blog.scaleway.com/40-open-source-projects/][40+ of the best open-source tools to build your startup]]
- [[https://github.com/AirenSoft/OvenMediaEngine][AirenSoft/OvenMediaEngine: OvenMediaEngine (OME) is a Sub-Second Latency Live Streaming Server with Large-Scale and High-Definition.]]
- [[https://github.com/ajnart/homarr][ajnart/homarr: Customizable browser's home page to interact with your homeserver's Docker containers (e.g. Sonarr/Radarr)]]
- [[https://github.com/allegro/ralph][allegro/ralph: Ralph is the CMDB / Asset Management system for data center and back office hardware.]]
- [[https://github.com/balzack/databag][balzack/databag: A self-hosted lightweight federated messenger for the decentralized web.]]
- [[https://github.com/baptisteArno/typebot.io][baptisteArno/typebot.io: 💬 Typebot is a conversational form builder that you can self-host.]]
- [[https://github.com/bdd/runitor][bdd/runitor: A command runner with healthchecks.io integration]]
- [[https://github.com/bigbluebutton/bigbluebutton][bigbluebutton/bigbluebutton: Complete open source web conferencing system.]]
  - [[https://guix.gnu.org/en/blog/2021/reproducible-data-processing-pipelines/][Reproducible data processing pipelines — 2021 — Blog — GNU Guix]]
- [[https://github.com/calendso/calendso?auto_subscribed=false][calendso/calendso: Scheduling infrastructure for absolutely everyone.]]
- [[https://github.com/ClaperCo/Claper][ClaperCo/Claper: The ultimate tool to interact with your audience]]
- [[https://conduit.rs/][Conduit - Your own chat server]]
- [[https://github.com/Cveinnt/LiveTerm][Cveinnt/LiveTerm: 💻 Build terminal styled websites in minutes!]]
- [[https://github.com/Dan6erbond/share-me/][Dan6erbond/share-me: An image and video hosting platform for your server, with rich embed support and API.]]
- [[https://github.com/dgtlmoon/changedetection.io][dgtlmoon/changedetection.io: changedetection.io - The best and simplest self-hosted open source website change detection monitoring and notification service. An alternative to Visualping, Watchtower etc. Designed for simplicity - the main goal is to simply monitor which websites had a text change. Open source web page change detection - Now also includes JSON API change detection and monitoring support!]]
- [[https://github.com/discuitnet/discuit][discuitnet/discuit: A free and open-source community discussion platform.]]
- [[https://github.com/domainmod/domainmod][domainmod/domainmod: DomainMOD is an open source application written in PHP & MySQL used to manage your domains and other internet assets in a central location. DomainMOD also includes a Data Warehouse framework that allows you to import your web server data so that you can view, export, and report on your live data.]]
- [[https://www.eonza.org/][Eonza Automation Software | Official site]]
- [[https://github.com/everywall/ladder][everywall/ladder: Selfhosted alternative to 12ft.io. and 1ft.io bypass paywalls with a proxy ladder and remove CORS headers from any URL]]
- [[https://github.com/exadel-inc/CompreFace][exadel-inc/CompreFace: Leading free and open-source face recognition system]]
- [[https://github.com/fastenhealth/fasten-onprem/][fastenhealth/fasten-onprem: Fasten is an open-source, self-hosted, personal/family electronic medical record aggregator, designed to integrate with 100,000's of insurances/hospitals/clinics]]
- [[https://framagit.org/fiat-tux/hat-softwares/lufi][Fiat Tux Let's Upload that FIle — File sharing software / Hat softwares / Lufi · GitLab]]
- [[https://framagit.org/fiat-tux/hat-softwares/lutim][Fiat Tux Let's Upload That IMage — Image sharing software / Hat softwares / Lutim · GitLab]]
- [[https://github.com/firefly-iii/firefly-iii][firefly-iii/firefly-iii: Firefly III: a personal finances manager]]
- [[https://framagit.org/flopedt/FlOpEDT][FlOpEDT Flexible and Open Scheduler / flopEDT - flopScheduler · GitLab]]
- [[https://github.com/GorvGoyl/Clone-Wars][GorvGoyl/Clone-Wars: 100+ open-source clones of popular sites like Airbnb, Amazon, Instagram, Netflix, Tiktok, Spotify, Whatsapp, Youtube etc. See source code, demo links, tech stack, github stars.]]
- [[https://github.com/grocy/grocy][grocy/grocy: ERP beyond your fridge - grocy is a web-based self-hosted groceries & household management solution for your home]]
- [[https://github.com/HemmeligOrg/Hemmelig.app][HemmeligOrg/Hemmelig.app: Keep your sensitive information out of chat logs, emails, and more with encrypted secrets.]]
- [[https://github.com/illacloud/illa-builder][illacloud/illa-builder: 🚀 Retool open-source alternative, with low-code UI components and support for multiple data resources.]]
- [[https://github.com/jech/galene][jech/galene: The Galène videoconference server]]
- [[https://github.com/jigar-sable/instagram-mern][jigar-sable/instagram-mern: Full-Stack Instgram Clone using MERN Stack and Socket.io]]
- [[https://github.com/JoyalAJohney/Realtime-Distributed-Chat][JoyalAJohney/Realtime-Distributed-Chat: High throughput 🚀 low latency - realtime chat built in Go and React ❤️]]
- [[https://sr.ht/~mjorgensen/jphotos/][jphotos: A simple HTTP server for sharing pictures.]]
- [[https://github.com/LANDrop/LANDrop][LANDrop/LANDrop: Drop any files to any devices on your LAN.]]
- [[https://github.com/leerob/leerob.io][leerob/leerob.io: My portfolio built with Next.js, Tailwind, Prisma, and Vercel.]]
- [[https://github.com/linuxserver/Heimdall][linuxserver/Heimdall: An Application dashboard and launcher]]
- [[https://github.com/lissy93/dashy][Lissy93/dashy: 🚀 A dashboard for your homelab]]
- Lychee
- [[https://github.com/madawei2699/free4chat][madawei2699/free4chat: free4.chat is a real-time audio chat service. It is designed by the local first and privacy first principle, and is very easy to use.]]
- [[https://github.com/makeplane/plane][makeplane/plane: 🔥 🔥 🔥 Open Source JIRA, Linear and Height Alternative. Plane helps you track your issues, epics, and product roadmaps in the simplest way possible.]]
- [[https://github.com/matrix-construct/construct][matrix-construct/construct: This is The Construct]]
- [[https://github.com/mattermost/focalboard][mattermost/focalboard: Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana.]]
- [[https://github.com/MaxLeiter/drift][MaxLeiter/Drift: Drift is a self-hostable Gist alternative and paste service]]
- [[https://github.com/Mayandev/notion-avatar][Mayandev/notion-avatar: 🪄 An online tool for making notion-style avatars.]]
- [[https://gitlab.com/mayan-edms/mayan-edms][Mayan EDMS Free Open Source DMS (document management system)]]
- MediaGoblin
- [[https://github.com/meienberger/runtipi][meienberger/runtipi: ⛺️ Tipi is a homeserver for everyone! One command setup, one click installs for your favorites self-hosted apps. ✨]]
- [[https://github.com/mikeroyal/Self-Hosting-Guide][mikeroyal/Self-Hosting-Guide: Self-Hosting Guide]]
- [[https://github.com/miroslavpejic85/mirotalksfu][miroslavpejic85/mirotalksfu: Open Source WebRTC with integrated server SFU. Video calls, messaging, screen sharing, recording and more.]]
- [[https://github.com/ohmyform/ohmyform][ohmyform/ohmyform: Free open source alternative to TypeForm, TellForm, or Google Forms]]
- [[https://github.com/omnivore-app/omnivore][omnivore-app/omnivore: Omnivore is a complete, open source read-it-later solution for people who like reading.]]
- [[https://github.com/paperless-ngx/paperless-ngx][paperless-ngx/paperless-ngx: A supercharged version of paperless: scan, index and archive all your physical documents]]
- PhotoPrism
- PhotoShow
- [[https://github.com/revoltchat][Revolt is a user-first chat platform built with modern web technologies]]
- [[https://github.com/root-gg/plik][root-gg/plik: Plik is a temporary file upload system (Wetransfer like) in Go.]]
- [[https://github.com/RunaCapital/awesome-oss-alternatives][RunaCapital/awesome-oss-alternatives: Awesome list of open-source startup alternatives to well-known SaaS products 🚀]]
  - [[https://github.com/penpot/penpot][penpot/penpot: Penpot - The Open-Source design & prototyping platform]]
  - [[https://github.com/logseq/logseq][logseq/logseq: A privacy-first, open-source platform for knowledge management and collaboration. Desktop app download link: https://github.com/logseq/logseq/releases, roadmap: https://trello.com/b/8txSM12G/roadmap]]
- [[http://sane-project.org/][SANE - Scanner Access Now Easy]]
- [[https://github.com/scolastico-dev/s.Status][scolastico-dev/s.Status: s.Status is a open source server status page written in java.]]
- [[https://healthchecks.io/docs/self_hosted/][Self-Hosted Healthchecks - Healthchecks.io]]
- [[https://git.swurl.xyz/swirl/clink][swirl/clink: dead-simple, super minimal URL shortener in C - clink - z]]
- [[https://github.com/tellform/tellform][tellform/tellform: Free Opensource Alternative to TypeForm or Google Forms]]
- [[https://tissue.systemreboot.net/][tissue - issue tracker and project information management system built on plain text files and git]]
- "title": "airsonic", "description": "Airsonic is a free, web-based media streamer, providing ubiqutious access to your music. Use it to share your music with friends, or to listen to your own music while at work. You can stream to multiple players simultaneously, for instance to one player in your kitchen and another in your living room."
- "title": "beets", "description": "The purpose of beets is to get your music collection right once and for all. It catalogs your collection, automatically improving its metadata as it goes using the MusicBrainz database. Then it provides a bouquet of tools for manipulating and accessing your music."
- "title": "booksonic", "description": "Booksonic is a server and an app for streaming your audiobooks to any pc or android phone. Most of the functionality is also availiable on other platforms that have apps for subsonic"
- "title": "calibre-web", "description": "Calibre Web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database.\n\n  [br][br]\n  [b][u][span style='color: #E80000;']Configuration[/span][/u][/b][br]\n  [b]/config[/b] Where Calibre-web should store it's database[br]\n  [b]/books[/b] Path to your calibre library metadata.db file[br]"
- "title": "Chevereto", "description": "Chevereto is a powerful and fast image hosting script that allows you to create your very own full featured image hosting website in just minutes. Please note that this offers only the free Chevereto version.."
- "title": "codiad", "description": "Codiad is a web-based IDE framework with a small footprint and minimal requirements.\n  "

- "title": "cops", "description": "COPS links to your Calibre library database and allows downloading and emailing of books directly from a web browser and provides a OPDS feed to connect to your devices."
- "title": "couchpotato", "description": "CouchPotato (CP) is an automatic NZB and torrent downloader. You can keep a \"movies I want\"-list and it will search for NZBs/torrents of these movies every X hours. Once a movie is found, it will send it to SABnzbd or download the torrent to a specified directory."
- "title": "daapd", "description": "DAAP (iTunes) media server with support for AirPlay devices, Apple Remote (and compatibles), MPD and internet radio."
- "title": "davos", "description": "davos is an FTP automation tool that periodically scans given host locations for new files. It can be configured for various purposes, including listening for specific files to appear in the host location, ready for it to download and then move, if required. It also supports completion notifications as well as downstream API calls, to further the workflow.\r\n\r\n/config : AppData Location\r\n/download : File Download Location"
- "title": "deluge", "description": "Deluge is a lightweight, Free Software, cross-platform BitTorrent client providing: Full Encryption, WebUI, Plugin System, Much more..."
- "title": "domoticz", "description": "Domoticz is a Home Automation System that lets you monitor and configure various devices like: Lights, Switches, various sensors/meters like Temperature, Rain, Wind, UV, Electra, Gas, Water and much more. Notifications/Alerts can be sent to any mobile device"
- "title": "duckdns", "description": "Duck DNS is a free service which will point a DNS (sub domains of duckdns.org) to an IP of your choice. The service is completely free, and doesn't require reactivation or forum posts to maintain its existence. First, go to duckdns site, register your subdomain and retrieve your token. Then run the docker create command above with your subdomain(s) and token. It will update your IP with the DuckDNS service every 5 minutes."
- "title": "duplicati", "description": "Free backup software to store encrypted backups online, Duplicati works with standard protocols like FTP, SSH, WebDAV as well as popular services like Microsoft OneDrive, Amazon Cloud Drive and S3, Google Drive, box.com, Mega, hubiC and many others."
- "title": "freshrss", "description": "A free, self-hostable rss aggregatorï¿½"
- "title": "gazee", "description": "A WebApp Comic Reader for your favorite digital comics. Reach and read your comic library from any web connected device with a modern web browser"
- "title": "headphones", "description": "Headphones is an automated music downloader for NZB and Torrent, written in Python. It supports SABnzbd, NZBget, Transmission, ï¿½Torrent and Blackhole."
- "title": "heimdall", "description": "Heimdall is a way to organise all those links to your most used web sites and web applications in a simple way."
- "title": "htpcmanager", "description": "Htpcmanager, a front end for many htpc related applications. Hellowlol version."
- "title": "hydra2", "description": "NZBHydra is a meta search for NZB indexers and the \"spiritual successor\" to NZBmegasearcH. It provides easy access to a number of raw and newznab based indexers."
- "title": "jackett", "description": "Jackett works as a proxy server it translates queries from apps like Sonarr etc into tracker-site-specific http queries and parses the html response sending results back to the requesting software.["
- "title": "kodi-headless", "description": "Headless installation of Kodiï¿½ (formerly known as XBMCï¿½), to enable library updates."
- "title": "lazylibrarian", "description": "LazyLibrarian is a program to follow authors and grab metadata for all your digital reading needs."
- "title": "letsencrypt", "description": "This container sets up an Nginx webserver and reverse proxy with php support and a built-in letsencrypt client that automates free SSL server certificate generation and renewal processes. It also contains fail2ban for intrusion prevention.\r\n  \r\n  Before running this container, make sure that the url and subdomains are properly forwarded to this container's host.\r\n  \r\n  - Port 443 on the internet side of the router should be forwarded to this container's port 443.\r\n  - If you need a dynamic dns provider, you can use the free provider duckdns.org where the url will be yoursubdomain.duckdns.org and the subdomains    can be www,ftp,cloud\r\n  - The container detects changes to url and subdomains, revokes existing certs and generates new ones during start. \r\n  - It also detects changes to the DHLEVEL parameter and replaces the dhparams file.\r\n  \r\n  - If you'd like to password protect your sites, you can use htpasswd. Run the following command on your host to generate the htpasswd file docker exec -it letsencrypt htpasswd -c /config/nginx/.htpasswd &lt;username&gt;"
- "title": "libresonic", "description": "Libresonic is a free, web-based media streamer, providing ubiqutious access to your music. Use it to share your music with friends, or to listen to your own music while at work. You can stream to multiple players simultaneously, for instance to one player in your kitchen and another in your living room. /music = Location of music. /media = Location of other media. /podcasts = Location of podcasts. /playlists = Location for playlists storage. CONTEXT_PATH is for setting url-base in reverse proxy setups - (optional) Default user/pass is admin/admin"
- "title": "lidarr", "description": "Lidarr is a music collection manager for Usenet and BitTorrent users."
- "title": "lychee", "description": "Lychee is a free photo-management tool, which runs on your server or web-space. Installing is a matter of seconds. Upload, manage and share photos like from a native application. Lychee comes with everything you need and all your photos are stored securely."
- "title": "mariadb", "description": "An Enhanced drop in replacement for Mysql"
- "title": "medusa", "description": "Medusa, automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic."
- "title": "minetest", "description": "Server version of minetest, a free, open source alternative to minecraft."
- "title": "minisatip", "description": "Minisatip is a multi-threaded satip server version 1.2 that runs under Linux and it was tested with DVB-S, DVB-S2, DVB-T, DVB-T2, DVB-C, DVB-C2, ATSC and ISDB-T cards.\n\n  The application is designed to stream the requested data to multiple clients (even with one dvb card) at the same time while opening different pids.\n  "
- "title": "musicbrainz", "description": " MusicBrainz is an open music encyclopedia that collects music metadata and makes it available to the public."
- "title": "muximux", "description": "A lightweight portal to view, manage your HTPC apps without having to run anything more than a PHP enabled webserver. With Muximux you don't need to keep multiple tabs open, or bookmark the URL to all of your apps."
- "title": "mylar", "description": "An automated Comic Book downloader (cbr/cbz) for use with SABnzbd, NZBGet and torrents."
- "title": "nextcloud", "description": "Nextcloud is an open source, self-hosted file sync and communication app platform. Access and sync your files, contacts, calendars and communicate and collaborate across your devices. You decide what happens with your data, where it is and who can access it!"
- "title": "nginx", "description": "Nginx is a web server with a strong focus on high concurrency, performance and low memory usage. It can also act as a reverse proxy server for HTTP, HTTPS, SMTP, POP3, and IMAP protocols, as well as a load balancer and an HTTP cache."
- "title": "nzbget", "description": "NZBGet is a usenet downloader, written in C++ and designed with performance in mind to achieve maximum download speed by using very little system resources. It supports all platforms including Windows, Mac, Linux and works on all devices including PC, NAS, WLAN routers and media players"
- "title": "ombi", "description": "Ombi allows you to host your own Plex Request and user management system. "
- "title": "openvpn-as", "description": "OpenVPN Access Server is a full featured secure network tunneling VPN software solution that integrates OpenVPN server capabilities, enterprise management capabilities, simplified OpenVPN Connect UI, and OpenVPN Client software packages that accommodate Windows, MAC, Linux, Android, and iOS environments."
- "title": "Organizr", "description": "Organizr allows you to setup Tabs that will be loaded all in one webpage. You can then work on your server with ease."
- "title": "oscam", "description": "OScam is a softcam, software to be used to decrypt digital television channels on a settopbox (receiver), as an alternative for a conditional access module (CAM). OScam is, compared with other softcams (CCcam, mgcamd, etc.), open source. Hence, the name Open Source Conditional Access Module (OScam). OScam is based on the not so well known softcam MpCS. The main features of OSCam are next to its softcam capabilities, that it is able to function as a cardserver."
- "title": "photoshow", "description": "A simple, easy way to turn a photo album into a webgallery"
- "title": "piwigo", "description": "Piwigo is photo gallery software for the web, built by an active community of users and developers."
- "title": "plex", "description": "Plex organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices. This container is packaged as a standalone Plex Media Server. has always been a top priority. Straightforward design and bulk actions mean getting things done faster."
- "title": "projectsend", "description": "ProjectSend is a self-hosted application that lets you upload files and assign them to specific clients that you create yourself! Secure, private and easy. No more depending on external services or e-mail to send those files!\n  "
- "title": "pydio", "description": "Pydio (formerly AjaXplorer) is a mature open source software solution for file sharing and synchronization. With intuitive user interfaces (web / mobile / desktop), Pydio provides enterprise-grade features to gain back control and privacy of your data: user directory connectors, legacy filesystems drivers, comprehensive admin interface, and much more."
- "title": "qbittorrent", "description": "The qBittorrent project aims to provide an open-source software alternative to ï¿½Torrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar library."
- "title": "quassel-core", "description": "Quassel IRC is a modern, cross-platform, distributed IRC client, meaning that one (or multiple) client(s) can attach to and detach from a central core -- much like the popular combination of screen and a text-based IRC client such as WeeChat, but graphical. Blowfish support and optional web-ui included."
- "title": "radarr", "description": "Radarr - A fork of Sonarr to work with movies ï¿½ la Couchpotato."
- "title": "resilio-sync", "description": "Resilio Sync (formerly BitTorrent Sync) uses the BitTorrent protocol to sync files and folders between all of your devices. There are both free and paid versions, this container supports both."
- "title": "rutorrent", "description": "Popular torrent client with a webui for ease of use."
- "title": "sabnzbd", "description": "SABnzbd makes Usenet as simple and streamlined as possible by automating everything we can. All you have to do is add an .nzb. SABnzbd takes over from there, where it will be automatically downloaded, verified, repaired, extracted and filed away with zero human interaction."
- "title": "sickchill", "description": "Sickchill is an Automatic Video Library Manager for TV Shows. It watches for new episodes of your favorite shows, and when they are posted it does its magic."
- "title": "smokeping", "description": "Smokeping keeps track of your network latency."
- "title": "sonarr", "description": "Sonarr (formerly NZBdrone) is a PVR for usenet and bittorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available."
- "title": "syncthing", "description": "Syncthing replaces proprietary sync and cloud services with something open, trustworthy and decentralized. Your data is your data alone and you deserve to choose where it is stored, if it is shared with some third party and how it's transmitted over the Internet."
- "title": "tautulli", "description": "Tautulli is a 3rd party application that you can run along side your Plex Media Server to monitor activity and track various statistics. Most importantly, these statistics include what has been watched, who watched it, when and where they watched it, and how it was watched. All statistics are presented in a nice and clean interface with many tables and graphs, which makes it easy to brag about your server to everyone else."
- "title": "thelounge", "description": "A self-hosted web IRC client"
- "title": "transmission", "description": "Transmission is designed for easy, powerful use. Transmission has the features you want from a BitTorrent client: encryption, a web interface, peer exchange, magnet links, DHT, ï¿½TP, UPnP and NAT-PMP port forwarding, webseed support, watch directories, tracker editing, global and per-torrent speed limits, and more."
- "title": "tvheadend", "description": "Tvheadend is a TV streaming server and recorder for Linux, FreeBSD and Android supporting DVB-S, DVB-S2, DVB-C, DVB-T, ATSC, ISDB-T, IPTV, SAT&gt;IP and HDHomeRun as input sources.\r\nTvheadend offers the HTTP (VLC, MPlayer), HTSP (Kodi, Movian) and SAT&gt;IP streaming.\r\nMultiple EPG sources are supported (over-the-air DVB and ATSC including OpenTV DVB extensions, XMLTV, PyXML)."
- "title": "ubooquity", "description": "Ubooquity is a free, lightweight and easy-to-use home server for your comics and ebooks. Use it to access your files from anywhere, with a tablet, an e-reader, a phone or a computer."
- "title": "unifi-controller", "description": "The Unifi-controller Controller software is a powerful, enterprise wireless software engine ideal for high-density client deployments requiring low latency and high uptime performance."
- "title": "webgrabplus", "description": "WebGrab+Plus is a multi-site incremental xmltv epg grabber. It collects tv-program guide data from selected tvguide sites for your favourite channels.Optional postprocessors to add IMDb data, or to customize your xmltv listing."
- "title": "znc", "description": "ZNC is an IRC network bouncer or BNC. It can detach the client from the actual IRC server, and also from selected channels. Multiple clients from different locations can connect to a single ZNC account simultaneously and therefore appear under the same nickname on IRC."
- [[https://github.com/umputun/remark42][umputun/remark42: comment engine]]
- [[https://github.com/Volmarg/personal-management-system][Volmarg/personal-management-system: Your web application for managing personal data. <personal.management.system.pms@gmail.com>]]
- [[https://github.com/WardPearce/paaster][WardPearce/paaster: Paaster is a secure by default end-to-end encrypted pastebin built with the objective of simplicity.]] 
- [[https://github.com/wirow-io/wirow-server][wirow-io/wirow-server: A full featured self-hosted video web-conferencing platform.]]
- [[https://github.com/yourselfhosted/slash][yourselfhosted/slash: An open source, self-hosted bookmarks and link sharing platform. Save and share your links very easily]]
- [[https://github.com/zulip/zulip][zulip/zulip: Zulip server and web app—powerful open source team chat]]
- [[https://serveradmin.ru/ustanovka-i-nastroyka-zulip/][Установка и настройка мессенджера Zulip — Server Admin]]

* Calendar
- [[https://github.com/calcom/cal.com][calcom/cal.com: Scheduling infrastructure for absolutely everyone.]]

* Comments
- [[https://github.com/djyde/cusdis][djyde/cusdis: lightweight, privacy-friendly alternative to Disqus.]]

* Control panel
- [[https://github.com/usmannasir/cyberpanel][usmannasir/cyberpanel: Cyber Panel - The hosting control panel for OpenLiteSpeed]]
