- [[https://mvmonitor.ru/][История цен интернет-магазинов Мвидео, Эльдорадо, Ситилинк, Pleer | MVmonitor]]
- https://akm-mebel.ru/
- [[https://www.citilink.ru/catalog/large_and_small_appliances/small_appliances/kettles/1405752/?mindbox-click-id=0cba5149-6b10-452d-bd5b-9a09e4fd83c7&utm_source=newsletter&utm_medium=email&utm_campaign=141020-new-products][Купить Чайник электрический SCARLETT SC-EK21S73, нержавеющая сталь в интернет-магазине СИТИЛИНК, цена на Чайник электрический SCARLETT SC-EK21S73, нержавеющая сталь (1405752) - Санкт-Петербург]]
- https://1track.ru/postservice/iml

* Software
- [[https://sovetnik.yandex.ru/welcome/][Яндекс.Советник]]

* Good shops
- [[https://www.regard.ru/][Регард - сеть компьютерных магазинов - Москва - продажа компьютеров, комплектующих, оргтехники]]

* Увлажнитель воздуха
** Ультразвуковой
- Ballu UHB-1000

* Audio
- [[https://www.youtube.com/channel/UCNrzUrkiCUnb8e0nFpgx8Cw][Михаил Греков - YouTube]]

* Sound cards
** USB
   - https://ru.aliexpress.com/item/ORICO-External-USB-Sound-Card-Stereo-Mic-Speaker-Headset-Audio-Jack-3-5mm-Cable-Adapter-Mute/32806995200.html?spm=a2g0s.9042311.0.0.PhYThh&dp=262c73425004d204c3356546ad4866cb&af=289709&cv=47843&afref=&mall_affr=pr3&dp=262c73425004d204c3356546ad4866cb&af=289709&cv=47843&afref=&mall_affr=pr3&aff_platform=aaf&cpt=1536614030425&sk=VnYZvQVf&aff_trace_key=a0c63f64fd0c49cd969d5c8e41bcafb7-1536614030425-04063-VnYZvQVf&terminal_id=075e2564eec74f9ebb21725f793b361f

* Home

1. Оформление задатка.
2. Оформление выписки со стороны продовца.
3. В случае использования материнского капитала ожидание средств со стороны
   покупателя.
4. Перевод денежных средств на счет в банке и его заморозка.  Разморозка
   осуществляется после передачи продовцом документа о передаче права
   собственности на имя покупателя.
#+begin_quote
Аккредитив это самый надежный способ покупки/продажи недвижимости. Суть его в
том, что до момента заключения договора купли продажи, покупатель идет в банк
и открывает специальный счет для аккредитива и вносит туда денежные средства,
продавец в своем банке открывает счет привязанный к счету покупателя,
заключается договор купли продажи и после его регистрации и перехода права
собственности, все документы относятся в банк и после проверки их банком
продавец получает деньги, в свою очередь если по какой либо причине сделака
будет призанна не действильной, деньги никуда не денутся и после ее
анулирвания, покупатель не потеряет свои деньги.
#+end_quote
5. Съезд продовца с жилища.
5. Акт приема и передачи.

** НДЛ

- [[https://www.gosuslugi.ru/situation/residential_property/tax_deduction][Как получить имущественный вычет и вернуть налог при покупке квартиры]]
- [[https://www.gosuslugi.ru/10055/1][Получение государственного сертификата на материнский (семейный) капитал]]

** Notes
- [[https://svoe.guru/zhilaya-sobstvennost/kvartira/pokupka/dokumenty-pokupka/posle-sdelki.html][Что нужно сделать после покупки квартиры? В результате заключения договора купли продажи квартиры какие документы остаются у покупателя, а какие необходимо оформить и дальше получить?]]
- [[https://mylawyer.club/nedvizhimost/kvartira/kuplya-prodazha/pokupka/chto-neobhodimo-sdelat-posle-sdelki.html][Какие действия необходимо сделать после покупки квартиры и подписания договора на вторичном рынке и в новостройке: куда идти дальше и как оформить собственность?]]
- [[https://zakonguru.com/nedvizhimost/priobretenije/pokupka/okonchatelnoe-oformlenie.html][Необходимые действия после покупки квартиры: инструкция]]
- [[https://moi-ipodom.ru/chto-delat-posle-pokupki-kvartiry.html][Что нужно сделать после покупки квартиры в 2020 году?]]
- [[https://safe-estate.ru/kak-dejstvovat-posle-pokupki-kvartiry/][Как действовать после покупки квартиры]]

** Wildberries
*** [[https://www.wildberries.ru/catalog/12813992/detail.aspx?size=39432059][Подушка "Лебяжий пух" - Роза 50 x 70 см желтый Marcy 12813992 в интернет-магазине Wildberries]]
 Состав хлопок 50%, полиэстер 50%
Описание

Чехол подушки Лебяжий пух выполнен из тика высшего качества. Наполнитель подушки: искусственный лебяжий пух. Искусственный лебяжий пух имеет уникальную способность держать и восстанавливать форму, а также обеспечивает правильное положение головы во время сна, что положительно влияет на качество сна. Тиковый наперник не электризуется, не бьётся током, в отличии от изделий с наперником из полиэстера или микрофибры. Подушки Лебяжий пух необычайно мягкие и легкие.
Развернуть описание
Декоративные элементы кант
Уход за вещами бережная стирка при 30 градусах; глажка запрещена; горизонтальная сушка в расправленном виде; деликатный отжим; нельзя выжимать
Наполнитель искусственный лебяжий пух
Особенности подушки гипоаллергенная; с рисунком; съемный чехол
Размер подушки 50х70 см
Высота предмета 50 см
Ширина предмета 70 см
Ширина упаковки 38 см
Высота упаковки 19.5 см
Глубина упаковки 29 см
Комплектация коробка; подушка; пакет
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/6911210/detail.aspx?size=24088084][Постельное белье Мальберри ECOTEX 6911210 в интернет-магазине Wildberries]]
 Состав хлопок 100%
Описание

Коллекция "Гармоника" - это уникальное сочетание мягкости и нежности благородного сатина со свежестью дизайнерских решений. Ткань: сатин-комфорт (100% хлопок). Упаковка: пакет ПВХ с фото. Товар поставляется без фирменной сумки. 1,5-СП: пододеяльник 145х215, простыня 150х215, наволочка 70х70 - 2 шт; 2-СП: пододеяльник 175х215, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт; ЕВРО: пододеяльник 200х220, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт; СЕМЕЙНЫЙ: пододеяльник 145х215 - 2 шт, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт.
Развернуть описание
Декоративные элементы без элементов
Размер постельного белья евро
Тип плетения постельного белья сатин
Размер наволочки 50х70 см; 70х70 см
Уход за вещами бережная стирка при t не более 40С
Размер пододеяльника 200х220
Размер простыни 220х240
Вес с упаковкой (кг) 2.32 кг
Ширина упаковки 35 см
Высота упаковки 35 см
Глубина упаковки 5 см
Размер натяжной простыни без натяжной простыни
Комплектация пододеяльник; простыня; наволочка - 4 шт.
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/4302889/detail.aspx?size=16040255][Одеяло "Антистресс" ECOTEX 4302889 в интернет-магазине Wildberries]]
 Состав микрофибра, искусственный лебяжий пух
Декоративные элементы без элементов
Размер постельного белья евро
Вес с упаковкой (кг) 2.7 кг
Вес без упаковки (кг) 2.5 кг
Высота предмета 220 см
Ширина предмета 200 см
Комплектация одеяло
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/12813993/detail.aspx?size=39432060][Подушка "Лебяжий пух"-Роза 70 x 70 см желтый Marcy 12813993 в интернет-магазине Wildberries]]
 Состав хлопок 50%, полиэстер 50%
Описание

Чехол подушки Лебяжий пух выполнен из тика высшего качества. Наполнитель подушки: искусственный лебяжий пух. Искусственный лебяжий пух имеет уникальную способность держать и восстанавливать форму, а также обеспечивает правильное положение головы во время сна, что положительно влияет на качество сна. Тиковый наперник не электризуется, не бьётся током, в отличии от изделий с наперником из полиэстера или микрофибры. Подушки Лебяжий пух необычайно мягкие и легкие.
Развернуть описание
Декоративные элементы кант
Уход за вещами бережная стирка при 30 градусах; глажка запрещена; горизонтальная сушка в расправленном виде; деликатный отжим; нельзя выжимать
Наполнитель искусственный лебяжий пух
Особенности подушки гипоаллергенная; с рисунком; съемный чехол
Размер подушки 70х70 см
Высота предмета 70 см
Ширина предмета 70 см
Ширина упаковки 38 см
Высота упаковки 19.5 см
Глубина упаковки 29 см
Комплектация подушка
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/9417360/detail.aspx?size=31301940][Постельное белье Вестерн евро ECOTEX 9417360 в интернет-магазине Wildberries]]
 Состав хлопок 100%
Описание

Коллекция "Гармоника" - это уникальное сочетание мягкости и нежности благородного сатина со свежестью дизайнерских решений. Ткань: сатин-комфорт (100% хлопок). Упаковка: пакет ПВХ с фото. Товар поставляется без фирменной сумки. Рисунок на наволочках может отличаться от фотоизображения. ЕВРО: пододеяльник 200х220, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт.
Развернуть описание
Декоративные элементы без элементов
Размер постельного белья евро
Тип плетения постельного белья сатин
Размер наволочки 50х70 см; 70х70 см
Уход за вещами бережная стирка при t не более 40С
Размер пододеяльника 200х220
Размер простыни 220х240
Вес с упаковкой (кг) 2.36 кг
Ширина упаковки 35 см
Высота упаковки 35 см
Глубина упаковки 5 см
Размер натяжной простыни без натяжной простыни
Комплектация пододеяльник; простыня; наволочка - 4 шт.
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/11007565/detail.aspx?size=35178510][Крышка для СВЧ-печи, диаметр 230 мм EUROKITCHEN 11007565 в интернет-магазине Wildberries]]
Описание

Защищает внутреннюю поверхность СВЧ-печи от загрязнения при размораживании и разогреве пищи. Изготовлена из пищевого термостойкого полипропилена.
Технические особенности
Материал изделия полипропилен
Общие характеристики
Количество предметов в упаковке 1 шт.
Дополнительная информация
Вес товара с упаковкой (г) 95 г
Вес товара без упаковки (г) 95 г
Высота предмета 5 см
Ширина предмета 25 см
Ширина упаковки 25 см
Высота упаковки 5 см
Глубина упаковки 25 см
Комплектация крышка
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/0/search.aspx?search=%D0%BA%D0%BE%D0%B2%D0%B5%D1%80%20%D0%B2%20%D0%BF%D1%80%D0%B8%D1%85%D0%BE%D0%B6%D1%83%D1%8E%20120&sort=priceup][ковер в прихожую 120]]

*** [[https://www.wildberries.ru/catalog/14377450/detail.aspx?targetUrl=XS][Ёрш для туалета "полосатый" KONONO 14377450 в интернет-магазине Wildberries]]

*** [[https://www.wildberries.ru/catalog/13221988/detail.aspx?size=40316460][Корзина для белья, 40 л EL CASA 13221988 в интернет-магазине Wildberries]]


Корзина для белья прямоугольная с крышкой объемом 40 л выполнена из качественного прочного пластика с плетением, напоминающим ротанг. Прочная и вместительная корзина позволит аккуратно сложить белье к стирке, а используя корзины разных цветов, можно сразу рассортировать белье по цветам или составам ткани.
Развернуть описание
Технические особенности
Материал изделия пластик
Дополнительная информация
Вес с упаковкой (кг) 1.15 кг
Высота предмета 48 см
Глубина предмета 30 см
Ширина предмета 38 см
Ширина упаковки 38 см
Высота упаковки 48 см
Глубина упаковки 30 см
Комплектация корзина
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/14579372/detail.aspx?size=43081027][Мешковый пылесос Tefal Compact Power TW3953EA Tefal 14579372 в интернет-магазине Wildberries]]

Описание

Сочетая эффективное качество уборки и эргономичный дизайн в компактном и удобном корпусе, Compact Power показывает наилучшие результаты в классе мешковых пылесосов. Новая мощная насадка эффективно удаляет въевшуюся грязь и убирает крупный мусор, гарантируя наилучшую эффективность уборки на твердых покрытиях. Усовершенствованная моноциклоническая технология обеспечивает двухуровневую фильтрацию и захват 99,98 процентов пыли. Новый мешок для сбора пыли Hygiene+ удерживает пыль и грязь внутри, предотвращая повторный их выброс.
Развернуть описание
Управление
Тип управления механическое
Общие характеристики
Гарантийный срок 2года
Объем пылесборника 3 л
Технические особенности
Тип пылесборника мешок
Тип уборки сухая
Максимальный уровень звука/шума 75 дБ
Выходной фильтр HEPA11
Индикация пылесоса заполнение пылесборника
Мощность устройства 750 Вт
Насадки
Количество насадок 4 шт.
Дополнительная информация
Материал корпуса пластик
Тип пылесоса обычный
Труба для всасывания телескопическая
Вес с упаковкой (кг) 6.49 кг
Вес без упаковки (кг) 3.68 кг
Ширина упаковки 29 см
Высота упаковки 29.3 см
Глубина упаковки 49.5 см
Комплектация пылесос; щелевая насадка; насадка для пола и ковров; насадка для мягкой мебели; насадка для паркета
Страна производитель Китай

*** [[https://www.wildberries.ru/catalog/10739348/detail.aspx?size=34520109][Набор для сухой уборки дома или офиса Topohome DryCleanSystem совок с веником Topohome 10739348 в интернет-магазине Wildberries]]

Описание

Набор для сухой уборки Topohome DryCleanSystem Удобный набор для сухой уборки дома или офиса. Ручка метлы сделана под углом для комфортного пользования. На совке расположена расческа для снятия мусора с метлы, при этом не нужно трогать мусор руками и нагибать спину.
Развернуть описание
Вес с упаковкой (кг) 1.05 кг
Высота предмета 88 см
Глубина предмета 24.5 см
Ширина предмета 26 см
Ширина упаковки 26 см
Высота упаковки 46 см
Глубина упаковки 10 см
Комплектация упаковка; совок; инструкция; веник
Страна производитель Китай

*** [[https://www.wildberries.ru/catalog/10396483/detail.aspx?size=33677254][Швабра с отжимом и двухкамерным ведром "Smart Mop" hauswell 10396483 в интернет-магазине Wildberries]]

Описание

Комплект состоит из швабры и двухкамерного ведра и позволяет мыть и отжимать одной рукой без усилий. К тому же вам никогда не придется трогать грязную насадку руками. Тонкий дизайн швабры позволяет проникать под кровати, диваны и другую мебель. Она поворачивается на 360 градусов и легко огибает углы, ножки мебели и разные препятствия. Насадка из микрофибры эффективно собирает грязь, шерсть и волосы. Она удерживает воду до 70% лучше, чем хлопок. Комплект сделан из материалов высокого качества.
Свернуть описание
Технические особенности
Материал изделия нержавеющая сталь; пластик
Дополнительная информация
Тип крепления нет
Вес товара с упаковкой (г) 1420 г
Ширина предмета 32 см
Длина предмета 11 см
Ширина упаковки 18 см
Высота упаковки 37.5 см
Глубина упаковки 21.5 см
Длина ручки 130 см
Комплектация ведро; швабра; насадка для швабры - 1 шт

*** [[https://www.wildberries.ru/catalog/8818450/detail.aspx?size=29672439][Коврик придверный влаговпитывающий 60х90 см. SUNSTEP. 8818450 в интернет-магазине Wildberries]]

Описание

Данный придверный влаговпитывающий коврик отлично подойдёт как для городских квартир, так и для загородных домов. Его можно положить с уличной стороны или в прихожей. Отлично защищает Ваш дом от грязи и влаги.
Свернуть описание
Технические особенности
Материал изделия полиэстер
Дополнительная информация
Форма коврика прямоугольная
Вес с упаковкой (кг) 5 кг
Вес без упаковки (кг) 5 кг
Высота предмета 5 см
Ширина предмета 49 см
Длина предмета 79 см
Ширина упаковки 5 см
Высота упаковки 5 см
Глубина упаковки 5 см
Комплектация коврик
Страна производитель Китай


*** [[https://www.wildberries.ru/catalog/13853303/detail.aspx?size=41640923][Диспенсер для жидкого мыла DeНАСТИЯ 13853303 в интернет-магазине Wildberries]]

Описание

Диспенсер для жидкого мыла DeНАСТИЯ впишется практически в любой современный интерьер. Мыло подаётся из него порционно, легким нажатием на дозатор. Материал изделия пластик. Дозатор для жидкого мыла можно приобрести вместе с другими аксессуарами для ванной комнаты, собрав единый по цвету и стилю комплект (стакан, мыльница, ершик для туалетной комнаты с чашей). Размеры изделия: длина - 7,3 см, ширина - 7,3 см, высота - 15 см.
Свернуть описание
Технические особенности
Материал изделия пластик
Дополнительная информация
Вес товара с упаковкой (г) 0.25 г
Высота предмета 15 см
Ширина предмета 7.3 см
Ширина упаковки 7.3 см
Высота упаковки 15 см
Глубина упаковки 7.3 см
Комплектация диспенсер
Страна производитель Китай

*** [[https://www.wildberries.ru/catalog/13737758/detail.aspx?size=41398850][Мыльница DeНАСТИЯ 13737758 в интернет-магазине Wildberries]]

Описание

Мыльница - это необходимая вещь в ванной комнате для всех, кто ценит настоящий комфорт, порядок и красоту. Если Вы отдаете предпочтение кусковому мылу, а не жидкому, то данная модель идеальный вариант для Вас. Любая мелочь при оформлении интерьера ванной комнаты может добавить изюминку и уют. Мыльница впишется практически в любой современный интерьер. Мыльницу можно приобрести вместе с другими аксессуарами для ванной комнаты, собрав единый по цвету и стилю комплект (стакан для зубных щёток, диспенсер для жидкого мыла, ершик для туалетной комнаты с чашей). Размеры изделия: длина - 12,7 см, ширина - 9,5 см, высота - 2,5 см.
Свернуть описание
Технические особенности
Материал изделия пластик
Дополнительная информация
Рисунок нет
Декоративные элементы без элементов
Тип крепления нет
Вес товара с упаковкой (г) 0.2 г
Высота предмета 2.5 см
Ширина предмета 9.5 см
Ширина упаковки 9.5 см
Высота упаковки 2.5 см
Глубина упаковки 12.7 см
Комплектация мыльница
Страна производитель Китай

*** [[https://www.wildberries.ru/catalog/13854569/detail.aspx?size=41644852][Стакан для зубных щёток DeНАСТИЯ 13854569 в интернет-магазине Wildberries]]

Описание

Стакан для зубных щеток DeНАСТИЯ впишется практически в любой современный интерьер. Материал изделия пластик. Стакан для зубных щеток можно приобрести вместе с другими аксессуарами для ванной комнаты, собрав единый по цвету и стилю комплект (диспенсер для жидкого мыла, мыльница, ершик для туалетной комнаты с чашей). Размеры изделия: длина - 7,3 см, ширина - 7,3 см, высота - 11,5 см.
Свернуть описание
Технические особенности
Материал изделия пластик
Дополнительная информация
Вес товара с упаковкой (г) 0.21 г
Высота предмета 11.5 см
Ширина предмета 7.3 см
Ширина упаковки 7.3 см
Высота упаковки 11.5 см
Глубина упаковки 7.3 см
Комплектация стакан
Страна производитель Китай

*** [[https://www.wildberries.ru/catalog/12634399/detail.aspx?size=39032009][Ковер для ванной комнаты AMSTER 50х80см белый-серый, микрофибра SWENSA 12634399 в интернет-магазине Wildberries]]

Описание

Сочетание оттенков серого, черного и белого делает коврик для ванной комнаты эффектным.Размер изделия 50 на 80, тип ворса микрофибра, высота ворса составляет 1,6 см. Коврик быстро сохнет, приятен на ощупь. Материал подложки термопластичная резина, предотвращающая скольжение на кафеле.
Свернуть описание
Материалы
Основа коврика термопластичная резина
Технические особенности
Материал изделия полиэстер
Дополнительная информация
Форма коврика прямоугольная
Высота ворса 5 мм
Вес товара с упаковкой (г) 933 г
Высота предмета 1 см
Ширина предмета 80 см
Ширина упаковки 50 см
Высота упаковки 15 см
Глубина упаковки 15 см
Комплектация коврик
Страна производитель Китай

*** [[https://www.wildberries.ru/catalog/13853302/detail.aspx?size=41640922][Диспенсер для жидкого мыла DeНАСТИЯ 13853302 в интернет-магазине Wildberries]]

Описание

Диспенсер для жидкого мыла DeНАСТИЯ впишется практически в любой современный интерьер. Мыло подаётся из него порционно, легким нажатием на дозатор. Материал изделия пластик. Дозатор для жидкого мыла можно приобрести вместе с другими аксессуарами для ванной комнаты, собрав единый по цвету и стилю комплект (стакан, мыльница, ершик для туалетной комнаты с чашей). Размеры изделия: длина - 7,3 см, ширина - 7,3 см, высота - 15 см.
Свернуть описание
Технические особенности
Материал изделия пластик
Дополнительная информация
Вес товара с упаковкой (г) 0.25 г
Высота предмета 15 см
Ширина предмета 7.3 см
Ширина упаковки 7.3 см
Высота упаковки 15 см
Глубина упаковки 7.3 см
Комплектация диспенсер
Страна производитель Китай

*** [[https://www.wildberries.ru/catalog/13855314/detail.aspx?size=41646376][Щётка для унитаза (ёршик) DeНАСТИЯ 13855314 в интернет-магазине Wildberries]]

Описание

Ершик для унитаза с чашей - это необходимая вещь в ванной комнате для всех, кто ценит настоящий комфорт, порядок и красоту. Поможет поддерживать чистоту в туалете и впишется практически в любой современный интерьер. Любая мелочь при оформлении интерьера ванной комнаты может добавить изюминку и уют. Ершик для унитаза с чашей можно приобрести вместе с другими аксессуарами для ванной комнаты, собрав единый по цвету и стилю комплект (стакан для зубных щёток, диспенсер для жидкого мыла, мыльница).
Свернуть описание
Технические особенности
Материал изделия пластик
Дополнительная информация
Вид щетки для унитаза напольный
Вес товара с упаковкой (г) 0.6 г
Ширина упаковки 9.5 см
Высота упаковки 36.5 см
Глубина упаковки 9.5 см
Длина ручки 26 см
Комплектация чаша; ершик
Страна производитель Китай

*** [[https://www.wildberries.ru/catalog/12813992/detail.aspx?size=39432059][Подушка "Лебяжий пух" - Роза 50 x 70 см желтый Marcy 12813992 в интернет-магазине Wildberries]]
 Состав хлопок 50%, полиэстер 50%
Описание

Чехол подушки Лебяжий пух выполнен из тика высшего качества. Наполнитель подушки: искусственный лебяжий пух. Искусственный лебяжий пух имеет уникальную способность держать и восстанавливать форму, а также обеспечивает правильное положение головы во время сна, что положительно влияет на качество сна. Тиковый наперник не электризуется, не бьётся током, в отличии от изделий с наперником из полиэстера или микрофибры. Подушки Лебяжий пух необычайно мягкие и легкие.
Свернуть описание
Декоративные элементы кант
Уход за вещами бережная стирка при 30 градусах; глажка запрещена; горизонтальная сушка в расправленном виде; деликатный отжим; нельзя выжимать
Наполнитель искусственный лебяжий пух
Особенности подушки гипоаллергенная; с рисунком; съемный чехол
Размер подушки 50х70 см
Высота предмета 50 см
Ширина предмета 70 см
Ширина упаковки 38 см
Высота упаковки 19.5 см
Глубина упаковки 29 см
Комплектация коробка; подушка; пакет
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/6911210/detail.aspx?size=24088084][Постельное белье Мальберри ECOTEX 6911210 в интернет-магазине Wildberries]]
 Состав хлопок 100%
Описание

Коллекция "Гармоника" - это уникальное сочетание мягкости и нежности благородного сатина со свежестью дизайнерских решений. Ткань: сатин-комфорт (100% хлопок). Упаковка: пакет ПВХ с фото. Товар поставляется без фирменной сумки. 1,5-СП: пододеяльник 145х215, простыня 150х215, наволочка 70х70 - 2 шт; 2-СП: пододеяльник 175х215, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт; ЕВРО: пододеяльник 200х220, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт; СЕМЕЙНЫЙ: пододеяльник 145х215 - 2 шт, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт.
Свернуть описание
Декоративные элементы без элементов
Размер постельного белья евро
Тип плетения постельного белья сатин
Размер наволочки 50х70 см; 70х70 см
Уход за вещами бережная стирка при t не более 40С
Размер пододеяльника 200х220
Размер простыни 220х240
Вес с упаковкой (кг) 2.32 кг
Ширина упаковки 35 см
Высота упаковки 35 см
Глубина упаковки 5 см
Размер натяжной простыни без натяжной простыни
Комплектация пододеяльник; простыня; наволочка - 4 шт.
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/4302889/detail.aspx?size=16040255][Одеяло "Антистресс" ECOTEX 4302889 в интернет-магазине Wildberries]]
 Состав микрофибра, искусственный лебяжий пух
Декоративные элементы без элементов
Размер постельного белья евро
Вес с упаковкой (кг) 2.7 кг
Вес без упаковки (кг) 2.5 кг
Высота предмета 220 см
Ширина предмета 200 см
Комплектация одеяло
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/9417360/detail.aspx?size=31301940][Постельное белье Вестерн евро ECOTEX 9417360 в интернет-магазине Wildberries]]
 Состав хлопок 100%
Описание

Коллекция "Гармоника" - это уникальное сочетание мягкости и нежности благородного сатина со свежестью дизайнерских решений. Ткань: сатин-комфорт (100% хлопок). Упаковка: пакет ПВХ с фото. Товар поставляется без фирменной сумки. Рисунок на наволочках может отличаться от фотоизображения. ЕВРО: пододеяльник 200х220, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт.
Свернуть описание
Декоративные элементы без элементов
Размер постельного белья евро
Тип плетения постельного белья сатин
Размер наволочки 50х70 см; 70х70 см
Уход за вещами бережная стирка при t не более 40С
Размер пододеяльника 200х220
Размер простыни 220х240
Вес с упаковкой (кг) 2.36 кг
Ширина упаковки 35 см
Высота упаковки 35 см
Глубина упаковки 5 см
Размер натяжной простыни без натяжной простыни
Комплектация пододеяльник; простыня; наволочка - 4 шт.
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/11007565/detail.aspx?size=35178510][Крышка для СВЧ-печи, диаметр 230 мм EUROKITCHEN 11007565 в интернет-магазине Wildberries]]

Описание

Защищает внутреннюю поверхность СВЧ-печи от загрязнения при размораживании и разогреве пищи. Изготовлена из пищевого термостойкого полипропилена.
Технические особенности
Материал изделия полипропилен
Общие характеристики
Количество предметов в упаковке 1 шт.
Дополнительная информация
Вес товара с упаковкой (г) 95 г
Вес товара без упаковки (г) 95 г
Высота предмета 5 см
Ширина предмета 25 см
Ширина упаковки 25 см
Высота упаковки 5 см
Глубина упаковки 25 см
Комплектация крышка
Страна производитель Россия


** 
- [[https://www.citilink.ru/catalog/large_and_small_appliances/small_appliances/ovens/1078202/][Купить Микроволновая Печь BBK 20MWS-715M/W С 20л. 700Вт белый в интернет-магазине СИТИЛИНК, цена на Микроволновая Печь BBK 20MWS-715M/W С 20л. 700Вт белый (1078202) - Санкт-Петербург]]
** Tables
- [[https://www.citilink.ru/catalog/furniture/pc_tables/1166579/][Стол игровой СОКОЛ КСТ-18, ЛДСП, белый]]
- [[https://www.citilink.ru/catalog/furniture/pc_tables/496381/][Купить Стол компьютерный СОКОЛ КСТ11.1Вкб, ЛДСП, венге и беленый дуб в интернет-магазине СИТИЛИНК, цена на Стол компьютерный СОКОЛ КСТ11.1Вкб, ЛДСП, венге и беленый дуб (496381) - Санкт-Петербург]]
- [[https://www.citilink.ru/catalog/furniture/pc_tables/496376/][Купить Стол компьютерный СОКОЛ КСТ11.1Дсб, ЛДСП, сонома и белый в интернет-магазине СИТИЛИНК, цена на Стол компьютерный СОКОЛ КСТ11.1Дсб, ЛДСП, сонома и белый (496376) - Санкт-Петербург]]
- [[https://www.citilink.ru/catalog/furniture/pc_tables/1092420/][Купить Стол игровой СОКОЛ КСТ-117, ЛДСП, венге в интернет-магазине СИТИЛИНК, цена на Стол игровой СОКОЛ КСТ-117, ЛДСП, венге (1092420) - Санкт-Петербург]]
** TV
- [[https://www.citilink.ru/catalog/audio_and_digits/tv/1376863/][Телевизор XIAOMI Mi TV 4S 43, 43", Ultra HD 4K]]

* Fun
- [[https://www.ozon.ru/context/detail/id/152312572?hs=1][Браслет от комаров Planka с кнопкой в пакете zip-lock — купить в интернет-магазине OZON с быстрой доставкой]]
- [[https://www.ozon.ru/context/detail/id/150557724?hs=1][− 24% Бестселлер 1 049 ₽ 1 390 ₽ Мягкая игрушка Leosco Голубь синий]]
- [[https://www.ozon.ru/context/detail/id/150500268?hs=1][− 10% Бестселлер 711 ₽ 790 ₽ Мягкая игрушка Leosco Ежик коричневый]]
- [[https://www.ozon.ru/context/detail/id/169566093/?_bctx=CAQQuR8&hs=1][Держатель для туалетной бумаги с полочкой для телефона хром металл]]
- [[https://www.ozon.ru/context/detail/id/169490869/?_bctx=CAQQuR8&hs=1][Держатель для туалетной бумаги с полочкой для телефона чёрный металл]]
- [[https://www.ozon.ru/product/derzhatel-dlya-tualetnoy-bumagi-s-polochkoy-dlya-telefona-chernyy-metall-dvoynoy-177240634/?_bctx=CAQQuR8&hs=1][Держатель туалетной бумаги с полочкой для телефона чёрный для 2-х рулонов]]
- [[https://www.ozon.ru/context/detail/id/189200033/?_bctx=CAQQ4wc&asb=tZlNC2Yv%252F2T47%252BHfilOpX5KF054tijv%252FArGNYYtl1nI%253D&hs=1][Органайзер - держатель для туалетной бумаги / Напольный (для 4х рулонов)]]
- [[https://www.ozon.ru/product/podushka-dlya-shei-bee-s-knees-170707151/?_bctx=CAQQ4wc&hs=1][Подушка для шеи Uvoo]]

* Organize
- [[https://www.ozon.ru/product/podstavka-dlya-obuvi-etazherka-obuvnitsa-v-prihozhuyu-multilevel-3-3-polki-171132203/?_bctx=CAQQ4wc&asb=Nc57Ldq7D%252FAQJphdzebCfxqnZFXGEwnvtDNB%252BMyblNk%253D&hs=1][Подставка для обуви U000185]]
