- [[https://mvmonitor.ru/][История цен интернет-магазинов Мвидео, Эльдорадо, Ситилинк, Pleer | MVmonitor]]
- https://akm-mebel.ru/
- [[https://www.citilink.ru/catalog/large_and_small_appliances/small_appliances/kettles/1405752/?mindbox-click-id=0cba5149-6b10-452d-bd5b-9a09e4fd83c7&utm_source=newsletter&utm_medium=email&utm_campaign=141020-new-products][Купить Чайник электрический SCARLETT SC-EK21S73, нержавеющая сталь в интернет-магазине СИТИЛИНК, цена на Чайник электрический SCARLETT SC-EK21S73, нержавеющая сталь (1405752) - Санкт-Петербург]]
- https://1track.ru/postservice/iml

* Software
- [[https://sovetnik.yandex.ru/welcome/][Яндекс.Советник]]

* Good shops
- [[https://www.regard.ru/][Регард - сеть компьютерных магазинов - Москва - продажа компьютеров, комплектующих, оргтехники]]

* Увлажнитель воздуха
** Ультразвуковой
- Ballu UHB-1000

* Audio
- [[https://www.youtube.com/channel/UCNrzUrkiCUnb8e0nFpgx8Cw][Михаил Греков - YouTube]]

* Sound cards
** USB
   - https://ru.aliexpress.com/item/ORICO-External-USB-Sound-Card-Stereo-Mic-Speaker-Headset-Audio-Jack-3-5mm-Cable-Adapter-Mute/32806995200.html?spm=a2g0s.9042311.0.0.PhYThh&dp=262c73425004d204c3356546ad4866cb&af=289709&cv=47843&afref=&mall_affr=pr3&dp=262c73425004d204c3356546ad4866cb&af=289709&cv=47843&afref=&mall_affr=pr3&aff_platform=aaf&cpt=1536614030425&sk=VnYZvQVf&aff_trace_key=a0c63f64fd0c49cd969d5c8e41bcafb7-1536614030425-04063-VnYZvQVf&terminal_id=075e2564eec74f9ebb21725f793b361f

* Home

1. Оформление задатка.
2. Оформление выписки со стороны продовца.
3. В случае использования материнского капитала ожидание средств со стороны
   покупателя.
4. Перевод денежных средств на счет в банке и его заморозка.  Разморозка
   осуществляется после передачи продовцом документа о передаче права
   собственности на имя покупателя.
#+begin_quote
Аккредитив это самый надежный способ покупки/продажи недвижимости. Суть его в
том, что до момента заключения договора купли продажи, покупатель идет в банк
и открывает специальный счет для аккредитива и вносит туда денежные средства,
продавец в своем банке открывает счет привязанный к счету покупателя,
заключается договор купли продажи и после его регистрации и перехода права
собственности, все документы относятся в банк и после проверки их банком
продавец получает деньги, в свою очередь если по какой либо причине сделака
будет призанна не действильной, деньги никуда не денутся и после ее
анулирвания, покупатель не потеряет свои деньги.
#+end_quote
5. Съезд продовца с жилища.
5. Акт приема и передачи.

** НДЛ

- [[https://www.gosuslugi.ru/situation/residential_property/tax_deduction][Как получить имущественный вычет и вернуть налог при покупке квартиры]]
- [[https://www.gosuslugi.ru/10055/1][Получение государственного сертификата на материнский (семейный) капитал]]

** Notes
- [[https://svoe.guru/zhilaya-sobstvennost/kvartira/pokupka/dokumenty-pokupka/posle-sdelki.html][Что нужно сделать после покупки квартиры? В результате заключения договора купли продажи квартиры какие документы остаются у покупателя, а какие необходимо оформить и дальше получить?]]
- [[https://mylawyer.club/nedvizhimost/kvartira/kuplya-prodazha/pokupka/chto-neobhodimo-sdelat-posle-sdelki.html][Какие действия необходимо сделать после покупки квартиры и подписания договора на вторичном рынке и в новостройке: куда идти дальше и как оформить собственность?]]
- [[https://zakonguru.com/nedvizhimost/priobretenije/pokupka/okonchatelnoe-oformlenie.html][Необходимые действия после покупки квартиры: инструкция]]
- [[https://moi-ipodom.ru/chto-delat-posle-pokupki-kvartiry.html][Что нужно сделать после покупки квартиры в 2020 году?]]
- [[https://safe-estate.ru/kak-dejstvovat-posle-pokupki-kvartiry/][Как действовать после покупки квартиры]]

** Wildberries
*** [[https://www.wildberries.ru/catalog/12813992/detail.aspx?size=39432059][Подушка "Лебяжий пух" - Роза 50 x 70 см желтый Marcy 12813992 в интернет-магазине Wildberries]]
 Состав хлопок 50%, полиэстер 50%
Описание

Чехол подушки Лебяжий пух выполнен из тика высшего качества. Наполнитель подушки: искусственный лебяжий пух. Искусственный лебяжий пух имеет уникальную способность держать и восстанавливать форму, а также обеспечивает правильное положение головы во время сна, что положительно влияет на качество сна. Тиковый наперник не электризуется, не бьётся током, в отличии от изделий с наперником из полиэстера или микрофибры. Подушки Лебяжий пух необычайно мягкие и легкие.
Развернуть описание
Декоративные элементы кант
Уход за вещами бережная стирка при 30 градусах; глажка запрещена; горизонтальная сушка в расправленном виде; деликатный отжим; нельзя выжимать
Наполнитель искусственный лебяжий пух
Особенности подушки гипоаллергенная; с рисунком; съемный чехол
Размер подушки 50х70 см
Высота предмета 50 см
Ширина предмета 70 см
Ширина упаковки 38 см
Высота упаковки 19.5 см
Глубина упаковки 29 см
Комплектация коробка; подушка; пакет
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/6911210/detail.aspx?size=24088084][Постельное белье Мальберри ECOTEX 6911210 в интернет-магазине Wildberries]]
 Состав хлопок 100%
Описание

Коллекция "Гармоника" - это уникальное сочетание мягкости и нежности благородного сатина со свежестью дизайнерских решений. Ткань: сатин-комфорт (100% хлопок). Упаковка: пакет ПВХ с фото. Товар поставляется без фирменной сумки. 1,5-СП: пододеяльник 145х215, простыня 150х215, наволочка 70х70 - 2 шт; 2-СП: пододеяльник 175х215, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт; ЕВРО: пододеяльник 200х220, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт; СЕМЕЙНЫЙ: пододеяльник 145х215 - 2 шт, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт.
Развернуть описание
Декоративные элементы без элементов
Размер постельного белья евро
Тип плетения постельного белья сатин
Размер наволочки 50х70 см; 70х70 см
Уход за вещами бережная стирка при t не более 40С
Размер пододеяльника 200х220
Размер простыни 220х240
Вес с упаковкой (кг) 2.32 кг
Ширина упаковки 35 см
Высота упаковки 35 см
Глубина упаковки 5 см
Размер натяжной простыни без натяжной простыни
Комплектация пододеяльник; простыня; наволочка - 4 шт.
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/4302889/detail.aspx?size=16040255][Одеяло "Антистресс" ECOTEX 4302889 в интернет-магазине Wildberries]]
 Состав микрофибра, искусственный лебяжий пух
Декоративные элементы без элементов
Размер постельного белья евро
Вес с упаковкой (кг) 2.7 кг
Вес без упаковки (кг) 2.5 кг
Высота предмета 220 см
Ширина предмета 200 см
Комплектация одеяло
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/12813993/detail.aspx?size=39432060][Подушка "Лебяжий пух"-Роза 70 x 70 см желтый Marcy 12813993 в интернет-магазине Wildberries]]
 Состав хлопок 50%, полиэстер 50%
Описание

Чехол подушки Лебяжий пух выполнен из тика высшего качества. Наполнитель подушки: искусственный лебяжий пух. Искусственный лебяжий пух имеет уникальную способность держать и восстанавливать форму, а также обеспечивает правильное положение головы во время сна, что положительно влияет на качество сна. Тиковый наперник не электризуется, не бьётся током, в отличии от изделий с наперником из полиэстера или микрофибры. Подушки Лебяжий пух необычайно мягкие и легкие.
Развернуть описание
Декоративные элементы кант
Уход за вещами бережная стирка при 30 градусах; глажка запрещена; горизонтальная сушка в расправленном виде; деликатный отжим; нельзя выжимать
Наполнитель искусственный лебяжий пух
Особенности подушки гипоаллергенная; с рисунком; съемный чехол
Размер подушки 70х70 см
Высота предмета 70 см
Ширина предмета 70 см
Ширина упаковки 38 см
Высота упаковки 19.5 см
Глубина упаковки 29 см
Комплектация подушка
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/9417360/detail.aspx?size=31301940][Постельное белье Вестерн евро ECOTEX 9417360 в интернет-магазине Wildberries]]
 Состав хлопок 100%
Описание

Коллекция "Гармоника" - это уникальное сочетание мягкости и нежности благородного сатина со свежестью дизайнерских решений. Ткань: сатин-комфорт (100% хлопок). Упаковка: пакет ПВХ с фото. Товар поставляется без фирменной сумки. Рисунок на наволочках может отличаться от фотоизображения. ЕВРО: пододеяльник 200х220, простыня 220х240, наволочка 70х70 - 2 шт, наволочка 50х70 - 2 шт.
Развернуть описание
Декоративные элементы без элементов
Размер постельного белья евро
Тип плетения постельного белья сатин
Размер наволочки 50х70 см; 70х70 см
Уход за вещами бережная стирка при t не более 40С
Размер пододеяльника 200х220
Размер простыни 220х240
Вес с упаковкой (кг) 2.36 кг
Ширина упаковки 35 см
Высота упаковки 35 см
Глубина упаковки 5 см
Размер натяжной простыни без натяжной простыни
Комплектация пододеяльник; простыня; наволочка - 4 шт.
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/11007565/detail.aspx?size=35178510][Крышка для СВЧ-печи, диаметр 230 мм EUROKITCHEN 11007565 в интернет-магазине Wildberries]]
Описание

Защищает внутреннюю поверхность СВЧ-печи от загрязнения при размораживании и разогреве пищи. Изготовлена из пищевого термостойкого полипропилена.
Технические особенности
Материал изделия полипропилен
Общие характеристики
Количество предметов в упаковке 1 шт.
Дополнительная информация
Вес товара с упаковкой (г) 95 г
Вес товара без упаковки (г) 95 г
Высота предмета 5 см
Ширина предмета 25 см
Ширина упаковки 25 см
Высота упаковки 5 см
Глубина упаковки 25 см
Комплектация крышка
Страна производитель Россия

*** [[https://www.wildberries.ru/catalog/0/search.aspx?search=%D0%BA%D0%BE%D0%B2%D0%B5%D1%80%20%D0%B2%20%D0%BF%D1%80%D0%B8%D1%85%D0%BE%D0%B6%D1%83%D1%8E%20120&sort=priceup][ковер в прихожую 120]]
** 
- [[https://www.citilink.ru/catalog/large_and_small_appliances/small_appliances/ovens/1078202/][Купить Микроволновая Печь BBK 20MWS-715M/W С 20л. 700Вт белый в интернет-магазине СИТИЛИНК, цена на Микроволновая Печь BBK 20MWS-715M/W С 20л. 700Вт белый (1078202) - Санкт-Петербург]]
** Tables
- [[https://www.citilink.ru/catalog/furniture/pc_tables/1166579/][Стол игровой СОКОЛ КСТ-18, ЛДСП, белый]]
- [[https://www.citilink.ru/catalog/furniture/pc_tables/496381/][Купить Стол компьютерный СОКОЛ КСТ11.1Вкб, ЛДСП, венге и беленый дуб в интернет-магазине СИТИЛИНК, цена на Стол компьютерный СОКОЛ КСТ11.1Вкб, ЛДСП, венге и беленый дуб (496381) - Санкт-Петербург]]
- [[https://www.citilink.ru/catalog/furniture/pc_tables/496376/][Купить Стол компьютерный СОКОЛ КСТ11.1Дсб, ЛДСП, сонома и белый в интернет-магазине СИТИЛИНК, цена на Стол компьютерный СОКОЛ КСТ11.1Дсб, ЛДСП, сонома и белый (496376) - Санкт-Петербург]]
- [[https://www.citilink.ru/catalog/furniture/pc_tables/1092420/][Купить Стол игровой СОКОЛ КСТ-117, ЛДСП, венге в интернет-магазине СИТИЛИНК, цена на Стол игровой СОКОЛ КСТ-117, ЛДСП, венге (1092420) - Санкт-Петербург]]
** TV
- [[https://www.citilink.ru/catalog/audio_and_digits/tv/1376863/][Телевизор XIAOMI Mi TV 4S 43, 43", Ultra HD 4K]]

* Fun
- [[https://www.ozon.ru/context/detail/id/152312572?hs=1][Браслет от комаров Planka с кнопкой в пакете zip-lock — купить в интернет-магазине OZON с быстрой доставкой]]
- [[https://www.ozon.ru/context/detail/id/150557724?hs=1][− 24% Бестселлер 1 049 ₽ 1 390 ₽ Мягкая игрушка Leosco Голубь синий]]
- [[https://www.ozon.ru/context/detail/id/150500268?hs=1][− 10% Бестселлер 711 ₽ 790 ₽ Мягкая игрушка Leosco Ежик коричневый]]
- [[https://www.ozon.ru/context/detail/id/169566093/?_bctx=CAQQuR8&hs=1][Держатель для туалетной бумаги с полочкой для телефона хром металл]]
- [[https://www.ozon.ru/context/detail/id/169490869/?_bctx=CAQQuR8&hs=1][Держатель для туалетной бумаги с полочкой для телефона чёрный металл]]
- [[https://www.ozon.ru/product/derzhatel-dlya-tualetnoy-bumagi-s-polochkoy-dlya-telefona-chernyy-metall-dvoynoy-177240634/?_bctx=CAQQuR8&hs=1][Держатель туалетной бумаги с полочкой для телефона чёрный для 2-х рулонов]]
- [[https://www.ozon.ru/context/detail/id/189200033/?_bctx=CAQQ4wc&asb=tZlNC2Yv%252F2T47%252BHfilOpX5KF054tijv%252FArGNYYtl1nI%253D&hs=1][Органайзер - держатель для туалетной бумаги / Напольный (для 4х рулонов)]]
- [[https://www.ozon.ru/product/podushka-dlya-shei-bee-s-knees-170707151/?_bctx=CAQQ4wc&hs=1][Подушка для шеи Uvoo]]

* Organize
- [[https://www.ozon.ru/product/podstavka-dlya-obuvi-etazherka-obuvnitsa-v-prihozhuyu-multilevel-3-3-polki-171132203/?_bctx=CAQQ4wc&asb=Nc57Ldq7D%252FAQJphdzebCfxqnZFXGEwnvtDNB%252BMyblNk%253D&hs=1][Подставка для обуви U000185]]
