* doomed

7:56o_adnauseam_o: нет - шалор и огр не подходят
7:57o_adnauseam_o: я корнаком играл, но лишнее очко ему разве что в начале нужно (ну либо если тебе ни светильник ни амулет на категорию shadows не попадётся)
7:59o_adnauseam_o: имей ввиду - у думеда пасивка на стан/конфуз резист и йика тоже
7:59o_adnauseam_o: я так и сделал - взял 5 инфузий
7:59o_adnauseam_o: пассивки вроде стакаются но если у тебя ещё с шмотки будут резисты, то получиться оверкап
8:00o_adnauseam_o: 100% конфуз и стан резист очень легко набираются за него
8:00o_adnauseam_o: (даже без йика)
8:00o_adnauseam_o: давать советы по билду или хочешь сам разобраться?)
8:02o_adnauseam_o: в первую очередь Shaodws 5/5/5/1 и Force of will 1/5/0/0, Punishments 1/1/1/1
8:03o_adnauseam_o: в дженериках dark sustenance 1/1/1/1 cursed form 1/x/0/0, cursed aura 1/1/1/5
8:04o_adnauseam_o: X - 3-5
8:04o_adnauseam_o: сколько посчитаешь нужным
8:05o_adnauseam_o: что по шмоткам будет
8:05o_adnauseam_o: по ситуации
8:06o_adnauseam_o: жест у меня заглючил - потому если у тебя 1,6,0 я бы его брать не советовал
8:06o_adnauseam_o: мб в 1,6,1 исправили - я не смотрел..
8:06o_adnauseam_o: в любом случаих их в самом конце можно брать на 1/1/1/1
8:06o_adnauseam_o: Gestures
8:07o_adnauseam_o: персонаж не атаковал врукопашню с включенным жестом... то есть вообе
8:07o_adnauseam_o: *вообще
8:08o_adnauseam_o: если хочешь с ним побегать - могу посоветовать держать очко так чтобы его можно было в любой момент вытащить
8:08o_adnauseam_o: (то есть перед распределением очков в дженерики вытаскивать из жестов очки а потом вкладывать их в последнюю очередь)
8:09o_adnauseam_o: там было немного классового лора)
8:09o_adnauseam_o: блин
8:09o_adnauseam_o: начни заново)
8:09o_adnauseam_o: ты только что отказался от важной дженерик ветки)
8:10o_adnauseam_o: когда будешь подбирать первое оружие - будь внимателен)
8:10o_adnauseam_o: не забудь включить теней и жест (коль он у тебя есть)
8:11o_adnauseam_o: мачи меч!!! SMOrc
8:13o_adnauseam_o: это важна ветка - вначале её на 1/1/1/5 берёшь, в средине 5/5/1/5 (а вообще есть (сомнительный) билд через 5/5/5/5)
8:14o_adnauseam_o: при прокачке первых двух скиллов из ней найденные тобой вещи будут проклятыми - это даёт бонусы (особенно если собирать комплекты)
8:15o_adnauseam_o: я бы их в средине качал...
8:15o_adnauseam_o: не-не - оно на дроп не влияет - просто накладывает на вещи (которые ты находишь) проклтия..
8:15o_adnauseam_o: в том числе (и на уже найденные)
8:16o_adnauseam_o: не - меч не нужен)
8:16o_adnauseam_o: у тебя уже прокляты твои майндстары)
8:16o_adnauseam_o: (вон "бафф" висит)
8:17o_adnauseam_o: все вещи того типа которые ты можешь проклясть (а это определяет уровень первого скила)
8:17o_adnauseam_o: там написно что будет за 2, 3, 4 вещи с таким типо проклятия
8:17o_adnauseam_o: неплохие проклятия - curse of shroad и curse of nightmars
8:19o_adnauseam_o: ну бонусы там такие - скорей просто как дополнительная фича.. особо спешить их получить смысла нет
8:20o_adnauseam_o: лучше поскорей прокачать 4 скилл из этой же ветки
8:21o_adnauseam_o: теней тоже включи)
8:30o_adnauseam_o: первую половину игры думед играет более пассивно - всё будут делать тени
8:31o_adnauseam_o: а вот когда вкачаешь punishments тогда тогда уже пойдет жара)
8:32o_adnauseam_o: но чтобы panishment хорошо работал нужна высокая mindpower
8:33o_adnauseam_o: к концу игры тебе нужно 90-100 собрать
8:37o_adnauseam_o: нет) но на 5 в первом скиле можно будет +2 получить к нужному проклятию
8:40o_adnauseam_o: к 20+ уровню желательно побольше дженериков скопить - там разом можно будет вложить 13+ очков (в антимагию и фунгус) и получить много профита
8:41o_adnauseam_o: с ресурсом вообще проблем нет (но я отключал отдых перед авто-исследованием)
8:43o_adnauseam_o: да там (в дженериках) кроме стан/конфуз резиста и cursed sentry нет ничего чтобы заметно повысило твою выживаемость
8:43o_adnauseam_o: на проклятия пока забей - там ничего страшного нет)
8:44o_adnauseam_o: да - первые 2 скила проклятия нужно качать вместе и быстро, чтоб получить от них профит - я делал это после фунгуса и антимагии
8:45o_adnauseam_o: да - можешь смело ходить в тяжелой
8:52o_adnauseam_o: думаю, она не сильно обиделась)
8:58o_adnauseam_o: я вначале полностью зачистил локу, а потом постарался там по-максимуму держать их в проходе, а в случаи чего отступать отступать на предыдущуий уровень чтобы змеи растянулись по локации.. можно и просто бегать кругами - тени сами охотятся на тех врагов что неподалёку
8:59o_adnauseam_o: думед в общем то не боиться рукопашной - но в уже во второй половине, когда жирку поднаберёт.. в первой всё же лучше держаться подальше от опасных ситуаций)
9:03o_adnauseam_o: в дайкаре? может ты туда рано идешь?
9:04o_adnauseam_o: вот если дайкара со штормом генериться - то ужас конечно)
9:06o_adnauseam_o: куча воздушных элементалей (в том числе элитных) напару с великанами бьют молниями со всех сторон а у тебя видимость пару клеток вокруг)
9:09o_adnauseam_o: тени всегда будут хилые, но по мере прокачки 1. они станут заметней дамажить 2. можно будет одной способностью призывать сразу всех (с маленьким КД)
9:09o_adnauseam_o: кроме того у них будут и другие весьма полезные функции
9:12o_adnauseam_o: кинь очки статов в силу воли/хитрость и можешь взять на единичку панишментс (правда толку от него поскольку постольку)
9:13o_adnauseam_o: с 4 уровня у тебя дефлекшен появиться и жить станет повеселей)
9:14o_adnauseam_o: силу воли и хитрость поровну
9:14o_adnauseam_o: они примерно одинаково полезны
9:15o_adnauseam_o: оба mindpower дают и оба для прокачки скилов нужны
9:16o_adnauseam_o: скопишь 500 золота - можно будет mindstar mastery взять в зигуре
9:17o_adnauseam_o: за 100 не бери - там категория будет неоткрыта
9:17o_adnauseam_o: лучше сразу за 500, а потом за 750 взять апргейд 0,3 к категории...
9:18o_adnauseam_o: (и только после этого брать продиджу "Адепт" - если ты её будешь брать)
9:20o_adnauseam_o: вот с этой продиджой не нужно увеличивать.. кроме того есть артефактный фанарь и случайные амулеты
9:21o_adnauseam_o: я для скрина набирал в ветке shadows 2,4 множитель)
9:22o_adnauseam_o: но больше 4 теней всё равно не дадут((
9:23o_adnauseam_o: (я видел баг вследствии которого было 5 теней но я хз как это вызвать и его уже могли пофиксить)
9:24o_adnauseam_o: аа - может это именно такой и был)
9:25o_adnauseam_o: если что - можно зажат ь правую кнопку мыши на мини-карте и двигать экран)
9:27o_adnauseam_o: а вот этого не знал я)
9:28o_adnauseam_o: ээ... у меня давно язык чешится спросить - зачем ты её так... странно сконфигурировал? я думал что тебе это удобно.. но если нет - то зачем?)
9:29o_adnauseam_o: их же можно перебиндить вроде?
9:30o_adnauseam_o: думеду 2 линии с головой
9:31o_adnauseam_o: (хотя TW тем более - он же человек пассивка)
9:33o_adnauseam_o: если что не стесняйся отступить в другую локацию
9:35o_adnauseam_o: а в конце на мобах будет постоянно висеть целый список вкусных статусов типа confused, stuned, bainlocked, paranoid (убегает) и т.п.)
9:36o_adnauseam_o: на финальных боссах у меня 1 раз ХП просел до 1700/1900 - а так весь бой фулловый был)
9:38o_adnauseam_o: жива)
9:38o_adnauseam_o: нет - не закрывал вообще
9:40o_adnauseam_o: под конец он большей частью как маг играет, вступаю в рукопашную только когда всё уже на кд
9:41o_adnauseam_o: это с боссами.. а черпаков в мили режет)
9:44o_adnauseam_o: вот и появилось куда очки кидать)
9:46o_adnauseam_o: яростный шоптом вроде переводиться)
9:46o_adnauseam_o: *шепот
9:47o_adnauseam_o: что значит тяжелый? конфузия со станом нравиться?)
9:48o_adnauseam_o: 5 в майндстары, 8 в фугусы и 8+ в антимагию)
9:48o_adnauseam_o: и всё это в районе 20 уровня
9:50o_adnauseam_o: до крепости
9:50o_adnauseam_o: крепость уже 25+
9:51o_adnauseam_o: антимгия и фунгусы после дайкары
9:52o_adnauseam_o: можно и до)
9:52o_adnauseam_o: на 20+
9:53o_adnauseam_o: дам будет рарник-корруптор в конце
9:55o_adnauseam_o: deflection здорово живучести добавляет - пока он активен кажется море по-колено, но стоит за ним следить - ибо как только его выбивают резко проседаешь
9:56o_adnauseam_o: заряд выбивают
9:56o_adnauseam_o: на сустейне цифра написана
9:58o_adnauseam_o: сходи в кор-пул)
9:58o_adnauseam_o: думеду нужны левелы чтобы набрать сил - на низких уровнях он слабей чем TW
10:00o_adnauseam_o: так как раз правильно качал)
10:00o_adnauseam_o: TW - человек-пассивка)
10:01o_adnauseam_o: он тень съёл
10:02o_adnauseam_o: из активных у TW эхо стерл и guardian focus.. да собачек телепортировать на голову мобам, если через них играешь)
10:03o_adnauseam_o: если что не забывай отступать подставляя вместо себя теней
10:03o_adnauseam_o: punishments работают через теней
10:06o_adnauseam_o: отступай
10:06o_adnauseam_o: барабан сделают)
10:07o_adnauseam_o: (когда умираешь там звук такой как будто в барабан бьют)
10:08o_adnauseam_o: (бас-бочку)
10:09o_adnauseam_o: шепот сам перебрасывается с моба на моба
10:12o_adnauseam_o: нет
10:13o_adnauseam_o: дефлекшен выбит
10:15o_adnauseam_o: уже всё ок)
10:17o_adnauseam_o: цены последние 2 бонуса
10:19o_adnauseam_o: скилл разблокирует сам бонус, а чтобы его получить нужно надевать шмотки с одинаковым проклятием
10:19o_adnauseam_o: то есть чтобы получить 4 бонус тебе нужны 4 шмокти с одинаковым проклятием
10:20o_adnauseam_o: бонус не нестолько хорошо чтобы выбирать под него шмотки
10:20o_adnauseam_o: но... первый скилл из курсед ауры на 5 уровне заменит собой 2 шмокти для любого проклятия на твой выбор
10:22o_adnauseam_o: всреднем у тебя пару проклятия будут на максимуме, а остальные на 2-3
10:23o_adnauseam_o: бег ему очень нужен.. даже два будут полезны
10:25o_adnauseam_o: из классовых способностей у него только 1 талант на мобильность - и тот из разблокируемой ветки
10:25o_adnauseam_o: (и тот не очень удобен)
10:26o_adnauseam_o: тебе до 20 уровня график забит )
10:27o_adnauseam_o: хотя.. на 10 можно взять One with shadows и положить по единичке.. но после прокачки теней и дефлекшен
10:29o_adnauseam_o: четвёртый талант там крутой - считай кауторайз)
10:36o_adnauseam_o: тени подамажней станут когда третий талант в ветке прокачаешь - будут молниями бить
10:37o_adnauseam_o: когда все 3-4 одну цель фокусят неплохой урон получается..
10:38o_adnauseam_o: на максимум - но вместе с ним на максимум нужно и второй брать
10:38o_adnauseam_o: и желательно это разом делать
10:39o_adnauseam_o: я б резисты от стана/конфуза взял...
10:40o_adnauseam_o: вторая пассивка в cursed form
10:42o_adnauseam_o: не - я писла что тут нужно по ситуации..
10:42o_adnauseam_o: если ты хочешь именно максимум выживаемости прямо сейчас то и все 5
10:42o_adnauseam_o: впринципе можешь гонять из неё 3 очка туда-сюда
10:44o_adnauseam_o: вначале она очень поелзна, просто под конец мне попалась броня 100% конфуз резистом а стан резист был побочным на каких то других хороших вещех так что у меня там по 100% с перебором было)
10:46o_adnauseam_o: да - потому можешь 5 в него положить но гонять 3 очка чтобы под конец откатить - это оптимальный вариант
10:46o_adnauseam_o: грибная посложней будет
10:47o_adnauseam_o: кор-пул/норгос/кристаллы потом инквизитор/грибы
10:48o_adnauseam_o: да - они часто куда то за стены заходят и там шухер наводят)
10:49o_adnauseam_o: не, ты конечно сам смотри в каком порядке тебе удобней идти.. ситуации разные бывают
10:50o_adnauseam_o: в 1.6.1 сейчас все робы +all resist имеют)
10:51o_adnauseam_o: тоже логично - можно до последнего уровня дойти (чтобы он сгенерился) и не трогать босса (в грибах он довольно неприятный)
11:01o_adnauseam_o: без movement инфузии тут шансов нет

6:00ModeratorAd_nauseam_: Я выяснил что 1. жесты хуже псикликов (однако гвардина жест работает даже если сустейн жеста боли не включен - правда без контратаки но она и не нужна с таким то шансом и уроном. Осталось выяснить нужен ли вообще гвардиан жест или лучше сэкономить 5 дженериков)
6:01ModeratorAd_nauseam_: 2. Багровая роба существенно увеличивает урон (в срванении с Plate of blackened mind)
6:03ModeratorAd_nauseam_: 3. Продиджа "Ментальная тирания" увеличивет суммарный урон на 20%, но Адепт всё же выгодней, так как даёт раннюю 4-ую тень и осводождает слот фонаря
