- [[https://gitlab.com/mildlyparallel/wayland-tv-remote-control][Ruslan Kuchumov / Wayland TV Remote Control: waylandtv is a remote control service with mobile web-interface for Linux TV home theater. · GitLab]]

* [[https://www.philips.ru/c-p/26PFL3405_60/66-cm-26-inch-hd-ready][ЖК телевизор Philips 26PFL3405/60]]

Изображение/дисплей

Формат изображения Широкий экран
Размер экрана по диагонали (в дюймах) 26  (дюймы)
Размер экрана по диагонали (метрич.) 66  см
Цвет корпуса Передняя панель цвета виски и черный глянцевый корпус
Разрешение панели 1366 x 768р
Яркость 400  кд/м²
Улучшение изображения
    Режим 3/2 – 2/2 Motion Pull Down
    3D гребенчатый фильтр
    3D MA деинтерлейсинг
    Активное управление
    Улучшение цвета
    Улучшение цветовых переходов
    Digital Crystal Clear
    Цифровое шумоподавление
    Динамическое повышение контрастности
    Прогрессивное сканирование
    Настройка четкости
    Автокоррекция телесного оттенка
    Обработка 1080p 24/25/30 Гц
    Обработка 1080p 50/60 Гц
Тип экрана дисплея ЖК-дисплей WXGA с активной матрицей TFT
Динамическая контрастность экрана 150 000:1
Время отклика (типич.) 8  мс
Угол просмотра 178º (Г) / 178º (В)
Пиковое отношение яркости 65  %
Улучшение экрана Антибликовое покрытие экрана

Поддерживаемое разрешение дисплея

Компьютерные форматы
        640 x 480, 60 Гц
        800 x 600, 60 Гц
        1024 x 768, 60 Гц
        1280 x 720, 60 Гц
        1280 x 768, 60 Гц
        1280 x 1024, 60 Гц
        1360 x 768, 60 Гц
        Через вход HDMI/DVI
Видеоформаты
        480i, 60 Гц
        480p, 60 Гц
        576i, 50 Гц
        576p, 50 Гц
        720p, 50, 60 Гц
        1080i; 50, 60 Гц
        1080p, 24, 50, 60 Гц
        1080p, 24, 25, 30, 50, 60 Гц

Тюнер/прием/передача

Вход антенны
    Коаксиальный кабель 75 Ом (IEC75)
Диапазоны тюнера
        Гипердиапазон
        S-канал
        UHF
        VHF
ТВ-система
        Система PAL I
        Система PAL B/G
        Система SECAM B/G
        SECAM L/L'
Воспроизведение видео
        NTSC
        SECAM
        PAL

Комфорт

Защита от детей
    Блок. от детей и ограничение на просмотр
Легкость установки
        Автонаименование программ
        Автоматическая установка каналов (ACI)
        Система автоматической настройки (ATS)
        Aвтосохранение
        Точная настройка
        Цифровая настройка PLL
        Подключение Plug & Play
Удобство использования
        Автоограничение громкости (AVL)
        Графический интерфейс пользователя
        Вывод на экран
        Управление на боковой панели
Часы
        Таймер отключения
        Будильник
        Таймер автоматического включения
Возможности подключения
    Easy link
Регулировка формата экрана
        4:3
        Автоформатирование
        Режим Super Zoom
        Расширение формата 14:9
        Расширение формата 16:9
        Увеличение субтитров
        Широкий экран
Пульт ДУ
    Телевизоры
Телетекст
    1000-страничный гипертекст
Возможности телетекста
        Fast text (Быстрый текст)
        Строка с информацией о программе
Режим Smart
        Индивидуальный
        Яркий
        Natural
        Кино
        Игра
        Энергосбережение
        Стандартный
        Фильм

Звук

Выходная мощность (среднеквадр.)
    2 x 5 Вт, Invisible Sound
Звуковая система
    Nicam Stereo
Улучшение звука
        Автоматическая регулировка громкости
        Incredible Surround
        Функция Smart Sound

Подключения

Количество разъемов SCART
    1
EasyLink (HDMI-CEC)
        Запуск воспроизведения одним нажатием
        EasyLink
        Режим ожидания системы
Фронтальные/боковые подключения
        Вход CVBS
        Аудиовход — левый/правый
        Выход для наушников
        Порт USB 2.0
1-й внешний разъем Scart
        Аудиоразъем: левый/правый
        RGB
HDMI 1
    HDMI v1.3
Другие подключения
        Выход композитного видеосигнала (CVBS)
        VGA вход ПК + аудиовход левый/правый
2-й внешний разъем
        Вход YPbPr
        Аудиовход — левый/правый
Краткое описание 2x HDMI, 1x USB, 1x SCART

Питание

Электропитание 220-240 В, 50 Гц
Температура окружающей среды 5 °C – 40 °C
Эко-знак Сертификация ECO label
Энергопотребление в режиме ожидания 0,3 Вт
Энергопотребление (в обычном режиме) 42  Вт
Потребление электроэнергии в год 68,62  кВт/ч
Наличие свинца Да*

Аксессуары

Входящие в комплект аксессуары
        Настольная подставка
        Шнур питания
        Краткое руководство пользователя
        Инструкция по эксплуатации
        Гарантийный сертификат
        Пульт ДУ
        Батарея типа AAA — 2 шт.
        Описание ПО

Размеры

Ширина устройства 637  миллиметра
Высота устройства 411  миллиметра
Глубина устройства 51,4  миллиметра
Вес продукта 5,2  кг
Ширина с подставкой 637  миллиметра
Высота с подставкой 447  миллиметра
Глубина с подставкой 170  миллиметра
Вес изделия с подставкой 5.5  кг
Ширина коробки 810  миллиметра
Высота коробки 525  миллиметра
Глубина коробки 170  миллиметра
Совместимое настенное крепление 75 x 75 мм

Что входит в комплект?
Другие продукты в комплекте

    Настольная подставка
    Шнур питания
    Краткое руководство пользователя
    Инструкция по эксплуатации
    Гарантийный сертификат
    Пульт ДУ
    Батарея типа AAA — 2 шт.
    Описание ПО
