- [[https://programmer.help/blogs/practice-vxlan-under-linux.html][Practice VxLAN under Linux]]
- [[https://russianblogs.com/article/15031512332/][Подробное объяснение и практика VXLAN - Русские Блоги]]
- [[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/assembly_using-a-vxlan-to-create-a-virtual-layer-2-domain-for-vms_configuring-and-managing-networking][Chapter 11. Using a VXLAN to create a virtual layer-2 domain for VMs Red Hat Enterprise Linux 8 | Red Hat Customer Portal]]
- [[https://ilearnedhowto.wordpress.com/2017/02/16/how-to-create-overlay-networks-using-linux-bridges-and-vxlans/][How to create overlay networks using Linux Bridges and VXLANs – I Learned How To…]]
- [[https://ilearnedhowto.wordpress.com/2016/09/16/how-to-create-a-overlay-network-using-open-vswitch-in-order-to-connect-lxc-containers/][How to create a overlay network using Open vSwitch in order to connect LXC containers. – I Learned How To…]]
- [[https://docs.openvswitch.org/en/latest/faq/vxlan/][VXLANs — Open vSwitch 3.0.90 documentation]]
- [[https://docs.openvswitch.org/en/latest/howto/userspace-tunneling/][Connecting VMs Using Tunnels (Userspace) — Open vSwitch 3.0.90 documentation]]
- [[https://habr.com/ru/post/508832/][Интеграция Open vSwitch с Р-виртуализацией / Хабр]]
- [[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/assembly_using-a-vxlan-to-create-a-virtual-layer-2-domain-for-vms_configuring-and-managing-networking][Chapter 6. Using a VXLAN to create a virtual layer-2 domain for VMs Red Hat Enterprise Linux 8 | Red Hat Customer Portal]]
- [[https://www.kernel.org/doc/Documentation/networking/vxlan.txt][kernel.org/doc/Documentation/networking/vxlan.txt]]
- [[https://vincent.bernat.ch/en/blog/2017-vxlan-linux][VXLAN & Linux]]
- [[https://joejulian.name/post/how-to-configure-linux-vxlans-with-multiple-unicast-endpoints/][How to configure linux vxlans with multiple unicast endpoints]]
- [[https://github.com/systemd/systemd/pull/12441][networkd: add support for bridge fdb destination address. by ssahani · Pull Request #12441 · systemd/systemd]]

* 

- [[https://wiki.astralinux.ru/pages/viewpage.action?pageId=158604065][Виртуальные сети VLAN и VXLAN в Astra Linux - Справочный центр - Справочный центр Astra Linux]]

** 

#+begin_example
  Создание и настройка VLAN с помощью службы networking

  Для настройки интерфейса VLAN с помощью службы networking

      Войти в сессию администратора (для Astra Linux Special Edition с включенным МКЦ — администратора с высоким уровнем целостности);

      Проверить список имеющихся сетевых интерфейсов:
      ip link show

      1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
          link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

      2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
          link/ether 52:54:00:64:d9:e8 brd ff:ff:ff:ff:ff:ff

      Далее для настройки будет использоваться интерфейс eth0;

      В файл конфигурации сетевого интерфейса добавить строки:
      # The first VLAN interface
      auto eth0.500
      iface eth0.500 inet static
      address 172.20.20.10
      netmask 255.255.255.240
      gateway 172.20.20.1
      dns-nameservers 8.8.8.8 8.8.4.4

      Название сетевого интерфейса VLAN должно иметь форму <имя_интерфейса>.<VLAN_ID>;

      Включить сетевые интерфейсы:
      sudo ifup eth0.500

      Проверить состояние интерфейса:
      sudo ifconfig eth0.500

  При необходимости можно добавить несколько интерфейсов VLAN
  # The second VLAN interface
  auto eth0.501
  iface eth0.501 inet static
  address 172.21.10.0
  netmask 255.255.255.0

  Если хост используется в качестве гипервизора, то выполнить настройку сети:

      Разрешить в конфигурации сети пересылку пакетов:
      echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
      echo "net.ipv4.conf.all.arp_filter=0" | sudo tee -a /etc/sysctl.conf
      echo "net.ipv4.conf.all.rp_filter=2" | sudo tee -a /etc/sysctl.conf

      Загрузить конфигурацию:
      sudo sysctl -p
#+end_example

** 

#+begin_example
  Включение и настройка VXLAN
  Базовые команды

      Создание устройства VXLAN:
      sudo ip link add vxlan0 type vxlan id 42 group 239.1.1.1 dev eth0 dstport 4789
      Указанная команда создает новое устройство с именем vxlan0. Это устройство использует широковещательную группу 239.1.1.1 и родительское устройство eth0 для обработки трафика, не имеющего правил обработки в таблице пересылки (форвардинга) пакетов. Целевой порт 4789 выбран в соответствии со стандартом IANA;

      Удаление устройства VXLAN:
      sudo ip link delete vxlan0

      Получение информации об устройстве VXLAN:
      sudo ip -d link show vxlan0

  Управление таблицами пересылки VXLAN выполняется с помощью команды bridge:

      Создать правило в таблице пересылки:
      sudo bridge fdb add to 00:17:42:8a:b4:05 dst 192.19.0.2 dev vxlan0

      Удалить правило пересылки:
      sudo bridge fdb delete 00:17:42:8a:b4:05 dev vxlan0

      Получение информации о правилах пересылки:
      sudo bridge fdb show dev vxlan0

  Проверить состояние устройства VXLAN можно командой ifconfig:
  sudo ifconfig vxlan0

  Проверить таблицу маршрутизации можно командой:
  sudo route -n

  Простейшую проверку работоспособности можно сделать, выполнив команду ping с адресом VXLAN другого устройства:
  ping 10.0.0.107
#+end_example

** p2p

#+begin_example
  Описание стенда:

      Сервер 1:
          IP-адрес: 172.31.0.106;
          VXLAN-адрес: 10.0.0.106;
      Сервер 2:
          IP-адрес: 172.31.0.107;
          VXLAN-адрес: 10.0.0.107;

  Настройка стенда:

      Настройка Сервера 1:

          Добавить интерфейс VXLAN:
          sudo ip link add vxlan0 type vxlan id 1 remote 172.31.0.107 dstport 4789 dev eth0

          Включить добавленный интерфейс:
          sudo ip link set vxlan0 up

          Назначить интерфейсу адрес:
          sudo ip addr add 10.0.0.106/24 dev vxlan0

      Настройка Сервера 2 выполняется аналогично, отличаются только адреса:
      sudo ip link add vxlan0 type vxlan id 1 remote 172.31.0.106 dstport 4789 dev eth0
      sudo ip link set vxlan0 up
      sudo ip addr add 10.0.0.107/24 dev vxlan0
#+end_example

** docker

#+begin_example
  VXLAN между контейнерами Docker

  Далее используются две хост-машины:

      Хост-машина 1:
          IP-адрес: 172.31.0.106;
      Хост-машина 2:
          IP-адрес: 172.31.0.107;

  По умолчанию контейнеры на каждой хост-машине подключены к одному сетевому мосту и могут коммуницировать друг с другом, а контейнеры на разных хост-машинах не могут коммуницировать друг с другом (для коммуникации может использоваться специальное ПО, как, например k8s). В настоящем примере для установления связи между контейнерами на разных хост-машинах используются стандартные сетевые интерфейсы docker и VXLAN.

  Материалы по установке docker и созданию контейнеров см. Применение системы изоляции приложений docker в ОС Astra Linux Special Edition 1.7. Далее в примере используется образ wiki/astralinux:se.

  Далее используется команда brctl из пакета bridge-utils. Установить пакет bridge-utils можно командой:
  sudo apt install bridge-utils
  При установке docker на компьютере по умолчанию создается специальный сетевой интерфейс - мост docker0, которому присваивается IP-адрес 172.17.0.1/16. Это сетевой мост, соединяющий контейнеры. Проверить параметры интерфейса:
  sudo ifconfig docker0
  docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
         inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
         ether 02:42:a9:5e:6f:00  txqueuelen 0  (Ethernet)
         RX packets 0  bytes 0 (0.0 B)
         RX errors 0  dropped 0  overruns 0  frame 0
         TX packets 0  bytes 0 (0.0 B)
         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
  IP-адреса контейнеров docker назначаются автоматически начиная с адреса 172.17.0.2. Чтобы зафиксировать адреса сетевых интерфейсов контейнеров, используемых далее в примере, необходимо при запуске контейнеров использовать параметр --ip. Использование это параметра поддерживается только на дополнительных сетях docker, и такую сеть нужно создать на каждой из хост-машин:
  docker network create --subnet 172.18.0.0/16 mynetwork
  Проверить список сетей:
  docker network ls
  NETWORK ID     NAME        DRIVER    SCOPE
  265dff745581   bridge      bridge    local
  ddf7301657ff   host        host      local
  a28625161bb9   mynetwork   bridge    local
  b74b0b0796bb   none        null      local
  При создании сети будет создан новый сетевой интерфейс br-... типа "мост":
  sudo ifconfig
  br-a28625161bb9: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
         inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
         ether 02:42:e9:f0:e9:a0  txqueuelen 0  (Ethernet)
         RX packets 0  bytes 0 (0.0 B)
         RX errors 0  dropped 0  overruns 0  frame 0
         TX packets 0  bytes 0 (0.0 B)
         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
  Теперь при запуске контейнера можно указать сеть и фиксированный IP-адрес, для первой хост-машины:
  docker run -itd --net mynetwork --ip 172.18.0.2 wiki/astralinux:se
  Для второй хост-машины:
  docker run -itd --net mynetwork --ip 172.18.0.3 wiki/astralinux:se
  Контейнер также можно запустить в сети docker, принятой "по умолчанию", с автоматическим присвоением адреса:
  docker run -itd wiki/astralinux:se
  Теперь на хост-машинах имеются следующие сетевые интерфейсы:

      docker0 - мост, созданный при установке docker. Сеть 172.17.0.0/16, IP-адрес интерфейса 172.17.0.1;
      br-xxxx - мост сети, созданной для реализации примера. Сеть 172.18.0.0/16, IP-адрес интерфейса 172.18.0.1;
      vethxxxx - интерфейсы контейнеров. Создаются при создании (запуске) каждого контейнера. Интерфейс eth0 контейнера соответствует интерфейсу veth;

  При этом на каждой хост-машине работает контейнер.

  Получить список мостов и их интерфесов можно командой brctl, например:
  sudo brctl show          
  br-a28625161bb9         8000.0242e9f0e9a0       no              veth1675dd1
  docker0         8000.0242a95e6f00       no              vethe587b2d
  Далее создадим сетевые интерфейсы VXLAN в каждой из хост-машин, и подключим их к мосту docker. Сетевые пакеты из контейнера будут доставляться в мост docker, инкапсулироваться в сообщения VXLAN и пересылаться на вторую хост-машину. На второй хост-машине сообщения VXLAN пересылаются в контейнер docker через мост второй хост-машины.

      Настройка первой хост-машины:

          Создать интерфейс VXLAN с идентификатором (VNI) 2000 и названием vxlan_docker. Параметры похожи на использованные в предыдущем примере:
          sudo ip link add vxlan_docker type vxlan id 200 remote 172.31.0.107 dstport 4789 dev eth0

          Включить созданный интерфейс VLAN:
          sudo ip link set vxlan_docker up

          Подключить созданный интерфейс к мосту docker:
          sudo brctl addif br-3231f89d69f6 vxlan_docker

      Настройка второй хост-машины выполняется аналогично:
      sudo ip link add vxlan_docker type vxlan id 200 remote 172.31.0.106 dstport 4789 dev eth0
      sudo ip link set vxlan_docker up
      sudo brctl addif br-f4b35af34313 vxlan_docker

  Далее можно проверить соединение с помощью команды ping, выполняемой в контейнере:
  ping 172.18.0.2
#+end_example

** Tunnel

*** First host tunnel side

#+begin_example
  ip link add vxlan0 type vxlan id 1 remote 88.XXX.XXX.XX dstport 4XXX dev eth0
  ip link set vxlan0 up
  ip addr add 10.X.X.X/24 dev vxlan0
#+end_example

*** Second host tunnel side

#+begin_example
  ip link add vxlan0 type vxlan id 1 remote 185.105.108.96 dstport 4XXX dev br0
  ip link set vxlan0 up
  ip addr add 10.X.X.XXX/24 dev vxlan0
  ip r add 141.XX.XXX.XX/32 via 10.X.X.X
#+end_example

*** NAT through first host

Make sure nftables packet is installed, then run:

#+begin_example
  nft add table nat
  nft 'add chain nat postrouting { type nat hook postrouting priority 100 ; }'
  nft add rule nat postrouting masquerade
  sysctl -w net.ipv4.ip_forward=1
#+end_example

* [[https://blog.thomas.maurice.fr/posts/some-vxlan-stuff-so-i-dont-forget/][Some VXLAN stuff so I don't forget how it works]]
📅 Aug 7, 2021
 ·  ☕ 2 min read

    🏷️
    #linux
    #networking
    #kernel
    #namespaces
    #vxlan

Just like my network namespace post, this post is going to be a basic cheat sheet for me so I don’t have to endlessly Google stuff for ages in case I need to use VXLANs again.
What is a VXLAN

Thta’s just a like a VLAN, essentially an overlay network that is not limited to 4000 IDs. It also has some nice features such as auto discovery of peers via broadcast on the same network.
Create a unicast vxlan interface

You can create a vxlan interface like so

$ ip link add name vx-0 type vxlan id 69 dev <IFACE> remote <REMOTE_IP> local <LOCAL_IP> dstport <PORT>
$ ip address add 10.69.0.1/24 dev vx-0
$ ip link set up dev vx-0

And mirror on the other host. Note that

    IFACE is the “parent” interface of the VXLAN interface, it should be the interface you will use to
    communicate with the NUC.
    REMOTE_IP is the IP of the remote vxlan endpoint, not on the overlay network (so like your LAN IP)
    LOCAL_IP is the same but for your local machine
    PORT is the port you will send packets to

It is worth noting you can just omit local IP dstport PORT the kernel should figure it out.

You can also bridge the interface like so:

$ ip link add name vx-0 type vxlan id 69 dev <IFACE> remote <REMOTE_IP> local <LOCAL_IP> dstport <PORT>
$ ip link add br-vx-0 type bridge
$ ip address add 10.69.0.1/24 dev br-vx-0
$ ip link set master br-vx-0 dev vx-0
$ ip link set up dev br-vx-0
$ ip link set up dev vx-0
