* Оглавление

** Введение

*** Глава 1. Факторы, обусловившие образование государства
- 1.1. Социальные факторы
- 1.2. Внешнеполитические и экономические факторы
- 1.3. Общественные факторы
- 1.4. "Союзы союзов"
*** Глава 2. Предпосылки возникновения
*** Глава 3. Этапы образования государства
*** Глава 4. Норманисты и антинорманисты
*** Заключение

*  Введение.

Образование государства у восточных славян явилось закономерным итогом
длительного процесса разложения родоплеменного строя и перехода к классовому
обществу.

Процесс имущественного и социального расслоения среди общинников привел к
выделению из их среды наиболее зажиточной части. Родоплеменная знать и
зажиточная часть общины, подчиняя себе массу рядовых общинников, нуждается для
поддержания своего господства в государственных структурах.

Зародышевую форму государственности представляли собой восточнославянские союзы
племен, которые объединились в суперсоюзы, правда, непрочные. Одним из таких
объединений был, по-видимому, союз племен во главе с князем Кием. Есть сведения
о некоем русском князе Бравлине который воевал в хазарско-византийском Крыму в
VIIIIX вв., пройдя от Сурожа до Корчева (от Судака до Керчи). Восточные
историки рассказывают о существовании накануне образования Древнерусского
государства трех крупных объединений славянских племен: Куябы, Славии и
Артании. Куябой, или Куявой, тогда называлась область вокруг Киева. Славия
занимала территорию в районе озера Ильмень. Ее центром был Новгород.
Местоположение Артании — третьего крупного объединения славян — точно не
установлено.

Согласно "Повести временных лет", русская княжеская династия берет свое начало
в Новгороде. В 859 г. Северные славянские племена, платившие тогда дань
варягам, или норманнам (по мнению большинства историков, выходцам из
Скандинавии), изгнали их за море. Однако вскоре после этих событий в Новгороде
началась междоусобная борьба. Чтобы прекратить столкновения, новгородцы решили
пригласить варяжских князей как силу, стоящую над противоборствующими
группировками. В 862 г. князь Рюрик и его два брата были призваны на Русь
новгородцами, положив начало русской княжеской династии.

Легенда о призвании варяжских князей послужила основанием для создания так
называемой норманской теории возникновения Древнерусского государства. Авторами
ее были приглашенные в XVIII в. в Россию немецкие ученые Г.Байер, Г.Миллер и
А.Шлецер. Авторы этой теории подчеркивали полное отсутствие предпосылок для
образования государства у восточных славян. Научная несостоятельность
норманской теории очевидна, так как определяющим в процессе образования
государства является наличие внутренних предпосылок, а не действия отдельных,
пусть даже и выдающихся, личностей.

Если варяжская легенда не вымысел (так считает большинство историков), рассказ
о призвании варягов свидетельствует лишь о норманском происхождении княжеской
династии.

Версия об иноземном происхождении власти была довольно типична для
Средневековья.

Датой образования Древнерусского государства условно считается 882 г., когда
князь Олег, захвативший после смерти Рюрика власть в Новгороде (некоторые
летописцы называют его воеводой Рюрика), предпринял поход на Киев. Убив
княживших там Аскольда и Дира, он впервые объединил северные и южные земли в
составе единого государства. Так как столица была перенесена из Новгорода в
Киев, это государство часто называют Киевская Русь.

Глава 1. Факторы, обусловившие образование государства.

Из ряда существующих в советской Древнерусского обусловившие исторической науке
концепций государства образование происхождения славян наиболее государства:
полно отвечает требованиям современной науки так называемая Днепровско-Одерская
концепция происхождения славян академика Б.А.Рыбакова, в соответствии с которой
с сере­дины II тыс. до н.э. в северной части Восточной Европы между Днепром и
Одером проживали древнейшие праславяне выделившиеся к этому времени из состава
индоевропейцев. По мнению Седова и некоторых других ученых, историю праславян
следует вести приблизительно с середины I тыс. до н.э.

1.1. Социальные факторы.

В письменных источниках, относящихся к началу нашей эры, славяне упоминаются
под названием "венеды". Известно что венеды вели оседлый образ жизни,знали
пашенное земледелие. У них существовала внутренняя торговля, связанная с
развитием ремесла, и внешняя торговля, в частности, с Римом. Торговля ускоряла
процесс дифференциации общества, способствовала появлению богатой социальной
верхушки. Малая семья, состоящая из мужа, жены, детей, становилась составной
частью важнейшей социальной клеточки общества - сельской общины. В сельской
территориальной общине выделялись отдельные, зажиточные семьи, обладавшие
определенной собственностью. В VIв. усиливается военная и политичес­кая власть.
Все это ускоряло имущественную и социальную дифференциацию славянского
общества, и формирование в ней классовых отношений. По мере углубления
социальной дифференциации в союзах племен все более усиливалось государственное
начало, что неизбежно вела в конечном счете к образованию государства. Но этот
процесс потребовал длительного времени.

1.2. Внешнеполитические и экономические факторы.

Неблагоприятно складывается и внешнеполитический фактор. На экономическом
развитии славян тяжело отразилось нашествие гуннов. В результате этого
задержалось и их собственное развитие. Как считал М.Н.Тихомиров, о при­чинах
возникновения государства было "развитие земледе­лия и ремесла в области
экономики, развитие феодализма - в области общественных отношений". Так в
VII-VIIIвв. в связи с ростом производительности труда становилось вполне
возможной индивидуализация производства. Подго­тавливались условия для перехода
от раннеклассовых от­ношений к феодализму. Экономический прогресс у восточ­ных
славян являлся движущей силой их общественного раз­вития. При условии
существования индивидуальных хо­зяйств дополнительный продукт, получаемый в них
и достигавший значительных размеров, становился собствен­ностью производителя и
мог являться источником обогаще­ния. Так возникло сначала имущественное, а
потом и со­циальное неравенство. Так же в это время складывалась и росла
частная собственность у зажиточных член общины. Формировалась социальная
верхушка общеста.

1.3. Общественные факторы.

Большое значение для образования государства имели союзы племен. В начале
существования таких союзов племен, формой организации управления была военная
демократия. Однако при этом еще дол­гое время сохранялась первобытные
демократи­ческие учреждения - народные собрания и со­вет старейшин: Но народное
собрание превра­щалось в собрание воинов которому военный предводитель,
окруженный и поддерживаемый дружиной, навязывал свою волю, приобретая все
большее влияние и власть за счет других старейшин. Таким образом шел процесс
преоб­разования органов общественного самоуправле­ния в государственные органы.
Военная демок­ратия постепенно перестала в военноиерархи­ческое
правление-княжение. Органы обществен­ного самоуправления превращались в органы
господства и угнетения, ,направленные против народа. Завершалось тем самым
оформление государственного строя, важнейшим признаком которого было по явление
особой, не совпада­ющей непосредственно с населением, отделен­ной от него
публичной власти, располагающей специальным аппаратом управления и
распрост­раняющейся на определенную территорию. Воен­ный предводитель крупного
союза племен прев­ращался в правителя - князя. Главенство князей приобретало
характер осуществления властных классовых функций. Приближенные князя
становились его советниками и намест­никами. Дружина превращалась в военную
силу, которая подавляла сопротивление эксплуатиру­емых масс и вела
захватнические и оборони­тельные войны. Указанный процесс преобразо­вания
органов общественного самоуправления в государственные органы не был актом
единов­ременным для всех союзов восточнославянских племен. В VIII в. в условиях
борьбы с кочев­никами в Среднем Приднепровье произошло объ­единение нескольких
союзов племен или княжений в "союз союзов" под названием "Русь" столицей
которого стал Киев.

1.4. «Союзы союзов».

"Союзы союзов", объединявшие по несколько союзов племен-княжений, являлись
новыми об­разованьями и отражали более высокий этап в процессе
восточнославянской консолидации. Примерно на рубеже VIII-IXвв. приднепровский
союз союзов племен "Русь" перерастает еще более мощное объединение с названием
"Русская земля", включавшее значительное число союзов славянских племен.
Летопись их перечисляет: Русь, Поляне, Древляне, Полоча­не, Дреговичи, Север.
Это уже почти половина восточных славян. Правила в этом госу­дарственном
объединении, по своей вероят­ности, династия Кия, представителями которой в
середине IXв. были, по сообщению летописи, князья Дир и Аскольд.

Глава 2. Предпосылки возникновения.

«Повести временных лет», первого письменного источника древнерусской истории,
где имеются свидетельства государственного объединения славянских племен.

Обратите внимание на то, что Киевская Русь одно из крупнейших государств
Средневековья IX-XII вв. В отличие от других стран , как Восточных так и
Западных, процесс формирования государственности имел свои специфические черты -
пространственные и геополитические. В ходе своего становления Русь приобрела
особенности как Восточных так и Западных государственных образований, поскольку
занимала срединное положение между Европой и Азией и не имела ярко выраженных
естественных географических границ в пределах огромного равнинного пространства
(двуглавый орел, утвержденный в качестве государственного герба Иваном III и
символизирующий евразийское единство Руси, был введен за четыре с лишним
столетия до того Ярославом Мудрым). Потребность в постоянной защите от внешних
врагов значительной территории вынуждала сплачиваться народы с разным типом
развития, вероисповедания, культуры, языка, создавать сильную государственную
власть. 

Важно понять, что государство возникает в неоднородном обществе и представляет
собой способ регулирования отношений между различными социальными слоями,
классами и т.д. Государственность у славян начинает формироваться с VI в.,
когда происходит переход от родовой и племенной общины к соседской, формируется
имущественное неравенство (соседская община - поселения людей, не связанных
родственными узами, но занимающих определенную ограниченную территорию,
коллективно обрабатывающих землю: каждая семья имеет право на свою долю
общинной собственности.)

Переходной ступенью к образованию государства у восточных славян был период
военной демократии.

Военная демократия предполагает выделение военной знати (князь и дружина),
которая сосредотачивает в своих руках значительные материальные ценности и
политическую власть, однако вече еще продолжает играть определенную роль в
жизни племени . Князь-военный вождь, первоначально племени, а затем - общий для
союза племен . Дружина - профессиональное войско, постоянное занятие которого
война . Вече - племенное собрание, в котором первоначально участвовали
практически все мужчины, а затем только боеспособные; верховный орган
племенного самоуправления и суда . Общее племенное ополчение - боеспособная
часть мужского населения племени, участвующая в военных действиях в случае
крайней необходимости.

Начальная нестабильность объединительного процесса, проявилась в приглашении на
правление Рюрика, князя варяжского происхождения. Обратите внимание на 882 год,
когда конунгу Олегу удалось объединить Новгородскую и Киевские земли в
древнерусское государство - Киевскую Русь со столицей в Киеве, по определению
князя - "Матерью городов русских». 

После распада Киевской Руси процесс рождения новорусского государства оказался
замедленным, поскольку феодальная раздробленность зашла слишком далеко. В
условиях политического и экономического упадка Киева другие княжества, которые
могли бы претендовать на роль нового центра Русской земли, были вынуждены
осуществлять эту роль в неблагоприятных внутренних и внешнеполитических
условиях.

Новгород, обособившийся от киевского политического центра еще в XII в., стал
ориентироваться в хозяйственном отношении по преимуществу на балтийский регион.
Естественно, что это не способствовало усилению его заинтересованности во
внутрирусских делах.

Унаследовшая у Киева Великое княжение Владимиро-Суздальская земля не успела
(накануне «батыева нашествия») набрать достаточный хозяйственный и людской, а
следовательно, и военный потенциал для «собирания» вокруг себя осколков бывшей
«рюриковской империи». Именно в это время последовал мощный удар с Востока и на
горизонте последующей истории нашего Отечества появились татары.

Глава 3. Этапы образования государства.

Народность, как таковая, складывается на определенном этапе общественного
развития в эпоху классового общества. Древнерусская народность не является
исключением из этого правила. Как мы уже знаем истоки ее восходят к очень
отдаленным временам, складывание восточных славян в особую ветвь славянства
дотируется VII – IX вв., то есть относится к тому времени, когда образовывается
язык восточных славян, а началом формирования древнерусской народности следует
считать IX – X вв. – время возникновения на Руси феодальных отношений и
образования древне Русского государства.

VIII – IX вв. в истории славянства были временем разложения первобытно общинных
отношений. При этом переход от одного общественного строя (первобытно
общинного) к другому, более прогрессивному, а именно феодальному обществу, в
конечном счете, был результатом развития производительных сил, эволюции
производства, которая в свою очередь в основном явилась следствием изменения и
развития орудий труда, орудий производства.

Наряду с развитием производительных сил в области сельскохозяйственного
производства и усовершенствованием земледельческой техники огромную роль в
разложении первобытно общинных отношений сыграло общественное разделение труда,
отделение ремесленной деятельности от сельского хозяйства.

Когда же в общину проникло разделение труда и члены ее стали каждый в одиночку
производством одного какого-нибудь продукта и продавать его на рынке, тогда
выражением этой материальной обособленности товаропроизводителей явился
институт частной собственности.

Поселения становятся центрами ремесленного производства и обмена, превращаются
в города. Города вырастают на основе старых городищ времен первобытного строя,
возникают как ремесленно – торговые поселения. Наконец княжый острог нередко
обрастает поселением городского типа. Так возникли города на Руси : Киев,
Перьяславль, Ладога, Псков, Новгород, Полоцк, Чернигов, Любеч, Смоленск, Гуров,
Червень и др.

Город явление характерное не для первобытно общинного строя, а для феодального
строя. Город торговал с городом, область с областью,горд с селом. По рекам и
сухопутным дорогам тянулись купеческие караваны. По Неве, Ладжскому озеру,
Волохову озеру, Ловати и Днепру проходил водный путь из “ варяг в греки ”.
Торговые пути вели чрез Карпаты в Ризу игерманские города.

Рост торговли вызвал развитие денежного обрасчения. На Руси пользовались
главным образом восточными серебряными монетами, но встречались и Византийские,
и западно – европейские монеты. Когдато на Руси в качестве денег использовали
меховые деньги представлявшие собой кусочки меха (куны, ререзаны, погаты и
пр.). С течением времени их заменили железные деньги которые сохранили старые
названия ( мордки, векши и пр.). С конца Х века на Руси стали чеканить свою
золотую и серебряную монету. Затем чеканная монета уступает место серебряным
слиткам – гривнам.

Торговля разлогала общину способствуя еще большему укреплению экономически
могущественных семейств. Господствующая верхушка в древнерусских источниках
выступает перед нами под названием князей, дружинников, бояр, старой чади и
т.д. Выростает она из старой племенной знати и из местной богатой верхушки.

Накапливая ценности и угодия, создавая мощную дружинную организацию совершая
походы заканчивающиеся захватом военной добычи и пленников превращаемых в
рабов, накапливая дань, собирая поборы, торгуя и занимаясь ростовщичеством,
древнерусская знать отрывается от племенных и общинных объединений и
превращается в силу стоящую над обществом и подчиняющую себе ранее свободных
общинников.

Возникает и развивается основа феодального общества – феодальная собственность
на землю. Нам извесны города принадлежащие князьям: Изьяславль, Вышгород,
Белгород; княжеские села: Ольжичи, Берестово, Ракома. Вокруг сел лежали нивы
(пашни), луга, охотничье – промысловые и рыболовпые угодия, бортные уходы. На
камни, деревья, столбы отмечающие княжеские земли наносились княжеские томги –
знаки собственности. Князья либо осваивали свободные земли либо захватывали их
у ранее свободных общинников превращая последних на основе вне економического
принуждения в рабочую силу свою и вотчины.

Формируются различные группировки зависимого люда. Среди них рабы – холопы,
робы – рабыни. Одни из них халопы утратили свою свободу в результате продажи
долговых обязательств, семейного или служебного положения, другие челядь стали
рабами в результате пленения. С течением времени термин челядь начинает
обозначать всю совокупность людей зависящих от господина. На начальном этапе
истории Киевской Руси рабство играло весьма существенную роль.

Огромную массу сельского населения составили свобдные общинники, обложенные
только данью. В источниках они выступают под названием – люди, но чаще всего их
называют смерды. Смерды считались княжескими людьми, но по мере захвата их
земель и угодий князьями и боярами они сохраняя свое старое название – смерды,
превращались в феодально зависимых и их повинности в пользу господина стали
носить феодальный характер. Дань переростала в оброк. Среди зависимого
населения насчитывалось немало закааленного люда потерявшего свою независимость
в результате долговых обязательств. Этот кабальный люд выступает в источниках
под названием рядовичей и закупов.многочисленными были изгои, люди изжитые
(гоить – жить) т.е. люди выбитые из обычной жизненной колеи порвавшие со своей
социальной средой. Так складывались зщависимые группировки непосредственных
производителей в Киевской Руси.

На Руси начало формироваться классовое ранне феодальное общество. Там где
произошло деление на классы неизбежно должно было возникнуть государство и оно
возникло.

Государство создается там и тогда где и когда имеются условия для его появления
в виде деления общества на классы. Складывание феодальных отношений у восточных
славян не могло не обусловить образование ранне феодального государства.
Таковым в Восточной Европе было Древнерусское государствосо стольным градом
Киевом.

Борьба со скандинавскими викингами варягами на северо – западе, с хазарами, а
позднее с печенегами, тюрками и другими кочувыми племенами на юго – востоке и
юге ускорил процесс складывания мощных териториальных объединений, пришедших на
смену племенным союзам.

Мы не знаем, сколь велика была территория Руси той поры, в какой мере включала
в себя восточно славянские земли, но очевидно что кроме средне днепровского,
киевского центра она состояла из ряда слабо связанных друг с другом земель и
племянных княжений. Древнерусское государство еще не сложилось, его образование
завершается слиянием Приднепровья с Приильменьем, Киева и новгорода двух
важнейших центров Руси.

Слиянием Киева и Новгорода завершается образование Древнерусского государстваю
Это событие летопись связала с именем Олега. В 882г. В результате похода дружин
под предводительством Олега из Новгорода в Киев по пути из варяг в греки оба
важнейшие центра Руси были объеденены. Киевский князь стал создавать опорные
пункты в землях восточной славян, собирать с них дань и требовать их участия в
походах. Но много земель восточных славян еще небыло связано с Киевом, а само
Древнерусское государство протянулось сравнительно узкой полосой с севера на юг
вдоль Великого водного пути по Днепру, Ловати, Волохову.

Столицей Древнерусского государства стал Киев. Это произошло потому что он был
древнейшим центром восточно славянской культуры, с глубокими историческими
традициями и связями. Расположенный на пограничье леса и степи с мягким ровным
климатом, черноземной очвой, дремучими лесами, прекрасными пастбищами и
залежамижелезной руды, многоводными реками основными средствами передвижения
тех времен. Киев был ядром восточнославянского мира. Киев был одинаково близок
к византии, к востоку и западу, что способствовало развитию торговых,
политических и культурных связей Руси.

Конец Х столетия ознаменовался завершением объединения всех восточных славян в
государственных границах Киевской Руси. Это объединение происходит во время
княжения Владимира Святославовича (980 – 1015 гг). В 981 г. Была присоеденена
область червенских городов Перемышль т.е. восточнославянские земли до Сана. В
992 г. Вошли в состав Древнерусского государства земли хорватов лежавшие по
обоим склонам Карпатских гор. В 989 г. Русские дружинники ходили на Ятвягов и
русское население заселявшее край вплоть до границ владений Пруссов положило
начало Черной Руси.

В 981 г. К Древнерусскому государству прсоеденилась земля Вятичей, хотя здесь
еще долгое время сохранялись следы былой ее независимости. Спустя 3 года в 984
г. После битвы на реке Пищане власть Киева распостронилась на Радимичей. Так
было закончено объединение всего восточного славянства в едином государстве.
Русские земли были объеденены под властью Киева ” Мати градом Русским “.

Глава 4. Норманисты и антинорманисты.

Как ранее, так и сейчас идут споры об истории возникновения Древ­нерусского
государства. Эта проблема постоянных политических спекуля­ций. Анализ
исторических исследований показывает, что прав был, навер­ное, М.Н.Покровский,
определивший историю как "политику, опрокинутую в прошлое".

В исторической науке по вопросу образования государства у восточ­ных славян с
18 века кипят страсти. В 30-60 гг. 18 века немецкие уче­ные Бейер и Миллер,
работавшие в Петербургской Академии наук, в своих научных трудах впервые
попытались доказать, что Древнерусское госу­дарство было создано варягами
(норманами). Они и положили начало нор­манской теории происхождения Российского
государства. Крайним проявле­нием концепции является утверждение, что славяне в
силу своей неполно­ценности не могли создать государства, а затем без
иноземного руко­водства были и не в состоянии управлять им.

Против этой теории в то время решительно выступил М.В.Ломоносов, которому
императрица Елизавета I поручила написать историю России. С тех пор борьба
норманистов и антинорманистов не утихает.

Норманисты единодушны в двух принципиальных вопросах. Во-первых, они считают,
что норманы добились господства над восточными славянами путем внешнего
военного захвата или с помощью мирного покорения (приг­лашения княжить);
во-вторых, они считают, что слово "русь" норманского происхождения.

Антинорманисты считают, что термин "Русь" доваряжского происхожде­ния и
восходит к очень древним временам. В "Повести временных лет" есть места,
которые противоречат легенде о призвании трех братьев кня­жить. За 852 год есть
указание о том, что при царствовании в Византии Михаила уже была Русская земля.
В Ларентьевской и Ипатьевской летопи­сях речь идет о том, что варягов княжить
приглашали все северные пле­мена, в том числе и Русь. Советские исследователи
М.Н.Тихомиров,

Д.С.Лихачев считают, что запись о призвании варяжских князей появилась в
летописи позже, чтобы противопоставить два государства - Киевскую Русь и
Византию. Автору летописи для этого потребовалось указать иностранное
происхождение династии. Согласно исследованию А.А.Шахмато­ва, варяжские дружины
стали называться Русью после того, как перешли на юг. А в Скандинавии ни по
каким источникам нельзя узнать о каком-то племени русь.

Вот уже в течении двух с лишним веков идут споры между представите­лями
норманской и антинорманской (славянской) школ в истории. В насто­ящее время
позиции норманистов и славянофилов сблизились. Однако это сближение вовсе не
является свидетельством утверждения истины. Как та, так и другая концепции
оказались тупиковыми. Кроме того, существуют еще и другие мнения. В.А.Мокшин
доказывает греческое происхождение названия "Русь". О существовании Руси как
Тмутараканского княжества в 9 веке пишет А.Н.Насонов, М.В.Левченко,
А.Л.Монгайт. Протоиерей Лев Лебедев пишет: "...в 4-7 вв. происходило известное
нам формирование первой русской государственности - культурно-политическое
объединение племенных союзов полян и северян под общим главенством племени
"рус" с княжеской династией кривичей". Этот вывод интересен тем, что корень
"крив" соответствует сегодняшнему названию "русский" у соседей криви­чей -
латышей.

Научные результаты двухсотлетних дискуссий состоят в том, что ни одна из школ
не может внятно объяснить, что такое "русь"; если это эт­нос, то где он
локализовался, в силу каких причин на определенном эта­пе усилился и куда
впоследствии исчез.

Заключение.

Вопрос о происхождении славян считается одним из основных вопросов в истории
Восточной и Юго-Восточной Европы. Парадоксально, что у этого многомиллионного
народа", расселявшегося на огромных пространствах Европы и Азии от лазурной
Адриатики до берегов Тихого океана и от знойных степей и пустынь Казахстана и
Средней Азии до хмурых вод Балтики и Северного Ледовитого океана",

не могут определить место откуда он вышел.

Одна из причин этого, по словам В.П. Кобычева,- отсутствие сколько-нибудь
полноценных письменных источников о славянах до середины 6 века н.э.

В настоящее время в состав славянских народов входят русские, украинцы,
белоруссы, поляки, чехи, словаки, болгары, сербы, хорваты, гасконцы, словенцы.
Но на первоначальном этапе существовала еще масса групп и племен славян,
которые были известны в Греции, Малой Азии, Северной Африке, некоторые селились
даже в Испании. Но впоследствии они были уничтожены, либо ассимилировали,
например, как поморские славяне, подпавшие под власть Тевтонского ордена в
12-14 веках.

Несмотря на вроде бы разрозненность и разбросанность славянских племен,
все-таки славянские племена представляли из себя единое целое, Древнерусское
государство. Летописец " Повести временных лет" в начале своего труда
писал:"... Был один народ славянский" ("Бе един язык словенск").
