* Установка

Всем привет. Вы на канале Fossmap.

Сегодня установим операционную систему GNU/Linux Fedora. 

Несколько слов о системе. 

Прежде всего она развивается сообществом всего мира. Не только RedHat. Большая часть обычных пользователей участвуют в ее разработке. Спонсирует компания RedHat. 

Главное достоинство системы для меня это прозрачность.
Огромное количество кода на языке программирования Python. Все что не на Python на C. Можно что-то исправить для себя без больших навыков программирования. 

Простой и мощный пакетный менеджер dnf. Есть поддержка истории транзакций. Допустим вы ставите сотню пакетов, а через определенное время вам эти пакеты не нужны. Их очень просто удалить. Огромная экономия трафика и в результате быстрое обновление пакетов. Скачивается лишь из разница. Автоматически выбирается самое быстрое зеркало. Простая работа с большим количеством сторонних репозиторий..

Также при установке каких-то сервисов, они не стартуют и не добавляются в автозагрузку по умолчанию. 

Удобный firewall с профилями для каждого интерфейса. 

Selinux который закрывает использование возможных уязвимостей в одной программе для доступа ко всей системе. 

Стабильный gnome интерфейс с рабочим gnome software и offline обновлениями. Уведомлением об обновлениях. Терминал с прозрачностью и уведомлениями о завершенных командах. Поддержка новых форматов пакетов flatpak.

Огромное современное community. Журнал в виде блога WordPress. Почтовая рассылка в виде социальной сети новый mail3. Git репозиторий в виде github. Wiki сайт в виде Wikipedia. Чат в виде Irc. Система уведомлений обо всех сервисах Fedora fedmsg. Единственный минус по сравнению с debian community, не нашел rtsp новостного архива почтовой рассылки. Надеюсь когда нибудь увидеть.

Документация не очень. Но покрывает огромное community и документация rhel, очень подробная и легко читаемая. 

Бесплатные webinar от RedHat. 

Поддержка всех кодеков через сторонний репозиторий. Хотя и говорится, что это не официальный репозиторий. Но им пользуются все, а также в Irc комнате написано что можно задавать вопросы касательно него и официального  репозитория fedora. То есть он хоть и не является официальным по юридическим соображениям других стран, но он им является, особенно учитывая что это community дистрибутив. 

В нем свежие программы. К примеру obs версии 18, который далеко еще не во всех дистрибутивах. 

Официальный репозиторий содержит только свободное программное обеспечение, кроме blob ядра для поддержки как можно большего оборудования. Остальное обеспечивает rpmfusion.

Легко пересобирать пакеты. Вся разработка происходит в репозиториях Git. Система сборки пакетов, обновлений. 

Инструменты для сборки удобны для локального использования. 

