#+TITLE: Emacs org-mode
#+AUTHOR: Oleg Pykhalov
#+EMAIL: go.wigust@gmail.com

http://spacemacs.org/

* Documentation
[[https://github.com/syl20bnr/spacemacs/tree/master/layers/org][Official documentation]]

** layers
[[https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/ranger][ranger]]
[[https://github.com/syl20bnr/spacemacs/tree/master/layers/shell][shell]]
[[https://github.com/syl20bnr/spacemacs/tree/master/layers/auto-completion][auto-completion]]

** Russian

*** Habrahabr
[[http://www.gnu.org/software/emacs/manual/html_mono/eintr.html][An Introduction to Programming in Emacs Lisp]]

* Video Tutorials
** English
*** How to by Harry Schwartz
https://www.youtube.com/watch?v=SzA2YODtgK4

Harry Schwartz demonstrates some of the nifty features of Org mode

"Org mode is an outliner, markup language, task manager, calendar, contact
manager, and who-knows-what-else. I use it to write documents and presentations,
manage my todo list, and I even write my Emacs configuration in it.

In other words, Org is taking over my life.

I’ll be introducing some of the functionality of Org, demonstrating what it can
do, and showing how you, too, can become pleasantly obsessed with a wacky,
overgrown outlining tool."

*** Embedding code snippets
Embedding code snippets within Org Mode couldn't be easier when using these neat
little tricks.

https://www.youtube.com/watch?v=lsYdK0C2RvQ
** Russian

Дмитрий Бушенко

[[https://www.youtube.com/watch?v=lpPS6JPUUME][Изучаем Emacs. Эпизод 10: Базовые возможности Org-mode, literate programming и экспорт в html/pdf]]

* Visibility cycling
| Key             | Function                   |
| Tab             | show current               |
| S-Tab           | show all children          |
| C-u C-u C-u Tab | show all including drawers |
* Editing
| Key         | Function                      |
| M-Ret       | add element on the same level |
| M-S-Ret     | insert TODO element           |
| M-Left      | promote current element       |
| M-S-Left    | promote current subtree       |
| M-Right     | demote current element        |
| M-S-Right   | demote current subtree        |
| M-S-Up      | move current tree up          |
| M-S-Down    | move current tree down        |
| C-c C-x C-w | kill current subtree          |
| C-c C-x M-w | copy current subtree          |
| C-c C-x C-y | yank subtree                  |
* Plain lists
Use M-Ret to add list item

Ordered list:
1. First
2. Second
3. Third

Unordered lists:
- abc
- abd
- afg
- asd

List with checkouts (M-S-Ret)
- [ ] Element with checkbox (C-c - togle checkbox state)
* More devices (drawers) 
- C-c C-z - time-stamped drawer
- C-c C-x f - footnote
* Start up options

Hide all trees
~#+STARTUP: overview~

Show all in trees
~#+STARTUP: showall~

Show only content
~#+STARTUP: content~

Show all including utilities
~#+STARTUP: showeverything~
* ToDo functionality
| C-c C-t         | rotate TODO state    |
| S-Left, S-Right | rotate TODO state    |
| S-M-Ret         | insert new TODO note |

#+SRC_CODE
(setq org-todo-keywords'((sequence "TODO" "FEEDBACK" "VERIFY" "|" "DONE" "DELEGATED")))
#+END_SRC
* Code editing
| C-c '     | open code block in pop up buffer |
| C-c C-v t | export to code file              |

:tangle yes
:tangle no

<s tab -- insert begin_src

#+begin_src -n -- add line numbering

** References
C-c l -- org-store-link -- reference
#+begin_src -r -- add tugging feature

C-c C-l -- access to reference

* Exporting

C-c C-e -- export

org2blog - export to WordPress

org-publish
* Header

+ TITLE: Python programming example
+ AUTHOR: Oleg Pykhalov
+ DATE: 11.09.2016
+ EMAIL: go.wigust@gmail.com
+ DESCRIPTION: Demonstration of org-mode
+ KEYWORDS: org-mode, python
+ LANGUAGE: en

* HTML Tags

** One line
+HTML: My email: <b>go.wigust@gmail.com</b>
** Multiple lines
+BEGIN_HTML
<h3>02.09.2013</h3>
+END_HTML
* Images and links

+CAPTION: Python Tutorial
+ATTR_HTML: title="Python!" style="float:left;"
file:python-logo.gif

* Tables
#+CAPTION: This is a table with lines around and between cells
| 1 | 2 | 3 | 4 |  5 |
|---+---+---+---+----|
| 6 | 7 | 8 | 9 | 10 |

* Links & URL
Is this SPC m l which does evil-org-open-links . There is a pending pull request
about this: evil-org-mode/issue/14

* Buffer
read buffer from stdin on start
#+BEGIN_SRC bash
emacs --insert <(echo 123)
#+END_SRC
* Wrapping
visual-line-mode -- line wrap
smartparens-mode -- auto close parens
* LaTex
** Math mode
$somemath$
$$somemath$$ -- на отдельной строке
** Exponents

*** superscripts

#+BEGIN_SRC latex
\documentclass[11pt]{article}

\begin

superscripts: $2x^3$
superscripts: $2x^(34)$ != superscripts: $2x^34$
$$2x^(3x+4)$$
$$2x^(3x^4+5)$$

\end{document}
#+END_SRC

*** subscripts

Underline "_" instead of caret brace "^"

#+BEGIN_SRC latex
\documentclass[11pt]{article}

\begin

$$x_1$$
$$x_(12)$$
$$x_1_2$$
$$(x_1)_2$$
$$((x_1)_2)_3$$

\end{document}
#+END_SRC

** Greek letters

#+BEGIN_SRC latex
\documentclass[11pt]{article}

\begin

$$\pi$$
$$\alpha$$
$$A=\pi r^2$$

\end{document}
#+END_SRC

* How to force a syntax-highlighting refresh
M-x -- font-lock-fontify-buffer
