* INBOX
** [2017-09-15 Fri 01:47] [[gnus:INBOX#87y3pqtvze.fsf@gnu.org][Email from Ludovic Courtès: “Code Staging in GNU Guix”]] by [[mailto:ludovic.courtes@inria.fr][Ludovic Courtès]]

- https://hal.inria.fr/hal-01580582/en
- https://conf.researchr.org/home/gpce-2017
- https://lists.gnu.org/archive/html/guix-devel/2017-07/msg00181.html

** [2017-09-15 Fri 11:33] [[gnus:INBOX#87d16xdway.fsf@gmail.com][Email from Maxim Cournoyer: Re: My experiences with GuixSD]] by [[mailto:maxim.cournoyer@gmail.com][Maxim Cournoyer]]

   What greatly improved the font rendering on my side was to create a
   ~/.config/fontconfig/fonts.conf containing the following:

** [2017-09-15 Fri 11:34] [[gnus:INBOX#87d16xdway.fsf@gmail.com][Email from Maxim Cournoyer: Re: My experiences with GuixSD]] by [[mailto:maxim.cournoyer@gmail.com][Maxim Cournoyer]]

   What greatly improved the font rendering on my side was to create a
   ~/.config/fontconfig/fonts.conf containing the following:

   #+BEGIN_EXAMPLE
     <?xml version="1.0"?>
     <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
     <fontconfig>
     <match target="font">
       <edit mode="assign" name="hinting" >
         <bool>true</bool>
       </edit>
     </match>
     <match target="font" >
       <edit mode="assign" name="autohint" >
         <bool>true</bool>
       </edit>
     </match>
     <match target="font">
       <edit mode="assign" name="hintstyle" >
         <const>hintfull</const>
       </edit>
     </match>
     <match target="font">
       <edit mode="assign" name="rgba" >
         <const>rgb</const>
       </edit>
     </match>
     <match target="font">
       <edit mode="assign" name="antialias" >
         <bool>true</bool>
       </edit>
     </match>
     <match target="font">
       <edit mode="assign" name="lcdfilter">
         <const>lcddefault</const>
       </edit>
     </match>
     <match target="pattern">
       <edit name="dpi" mode="assign"><double>92</double></edit>
     </match>
     <alias>
       <family>monospace</family>
       <prefer><family>Hack</family></prefer>
     </alias>
     <alias>
       <family>fixed</family>
       <prefer><family>Hack</family></prefer>
     </alias> 
     </fontconfig>
   #+END_EXAMPLE

** [2017-09-15 Fri 21:32] [[gnus:INBOX#86fubtkatd.fsf@zoho.com][Email from Emanuel Berg: Re: dired local ignore file ex]] by [[mailto:moasen@zoho.com][Emanuel Berg]]

   #+BEGIN_SRC emacs-lisp
     (setq completion-ignored-extensions
           (nconc completion-ignored-extensions (list ".bcf" ".run.xml")))
   #+END_SRC

** [2017-09-15 Fri 22:10] [[gnus:INBOX#a6e1d6254c16421fef857bf8dbb208a2@hypermove.net][Email from Amirouche Boubekki: Guile in the browser {Was: Sum]] by [[mailto:amirouche@hypermove.net][Amirouche Boubekki]]

** [2017-09-15 Fri 23:28] [[gnus:INBOX#E1dsOqu-00038a-T9@crmserver1p.fsf.org][Email from Richard Stallman: Why hackathons should insist o]] by [[mailto:info@fsf.org][Richard Stallman]]

- https://www.gnu.org/philosophy/hackathons.html
- https://www.gnu.org/philosophy/free-sw.html
- https://www.gnu.org/philosophy/free-hardware-designs.html
- https://www.gnu.org/philosophy/free-software-even-more-important.html
- https://www.beyondhackathon.com/en
- http://www.hackathon.io/rbc-digital
- https://expediaconnectivity.com/blog#madrid-hackathon-winners
- https://www.gnu.org/licenses/license-list.html
- https://www.gnu.org/philosophy/open-source-misses-the-point.html
- https://www.gnu.org/education/edu-schools.html
- https://status.fsf.org/fsf
- https://fsf.org/blogs/RSS
- https://www.fsf.org/jf
- https://my.fsf.org/civicrm/mailing/unsubscribe?reset=1&jid=153744&qid=27942913&h=25897b414aa3112c
- https://my.fsf.org/civicrm/mailing/optout?reset=1&jid=153744&qid=27942913&h=25897b414aa3112c

** [[gnus:INBOX#E1dtjUd-0006B5-SG@fencepost.gnu.org][Email from Richard Stallman: Re: JSON/YAML/TOML/etc. parsin]] by [[mailto:rms@gnu.org][Richard Stallman]]

   Yes it can be, but please avoid the term "MIT license".  There are
   two different licenses people sometimes call by that term, the X11
   license and the Expat license.  See
   https://gnu.org/licenses/license-list.html.

   Both of them are weak licenses -- we also call them "pushover"
   licenses -- since they permit inclusion in nonfree software.

   Please don't associate them with the name of MIT, as the
   association tends to promote them.

** [[gnus:INBOX#20170920061156.ed6ybieloxxvvs42@abyayala][Email from ng0: Re: Adopt a patch!]] by [[mailto:ng0@infotropique.org][ng0]]

   https://www.youtube.com/watch?v=KJ9Y0midtW4&feature=youtu.be
   http://blog.ffwll.ch/2017/01/maintainers-dont-scale.html
   http://blog.ffwll.ch/slides/lca-2017.pdf
   https://www.linux.conf.au/schedule/presentation/57/

   There's also some interesting links in there aswell.

   There are some more recent post of this maintainer
   at http://blog.ffwll.ch/
* Email
** [2017-10-06 Fri 07:46] [[gnus:INBOX#87h8vd4p38.fsf@gnu.org][Email from Ludovic Courtès: Re: WIP gnu social package]] by [[mailto:ludo@gnu.org][Ludovic Courtès]]
** [2017-10-06 Fri 07:47] [[gnus:INBOX#87fubazdn8.fsf@gmail.com][Email from Chris Marusich: Re: Should I upgrade root user]] by [[mailto:cmmarusich@gmail.com][Chris Marusich]]
** [2017-10-06 Fri 07:48] [[gnus:INBOX#87a82c7vmf.fsf_-_@escafil][Email from Ian Dunn: Re: {ELPA} New package: Captai]] by [[mailto:dunni@gnu.org][Ian Dunn]]
** [2017-10-09 Mon 19:56] [[gnus:INBOX#20170918215906.2c32b61d@cbaines.net][Email from Christopher Baines: Building things other than Gui]] by [[mailto:mail@cbaines.net][Christopher Baines]]
** [2017-11-03 Fri 19:50] [[gnus:nndoc+ephemeral:bug#29137#CAJ=RwfZbfzsg-TrFQkU48E6Mza0+PWDhTokGdzK9sXAReC7Ukw@mail.gmail.com][Email from David Thompson: Re: Interactive programming wi]] by [[mailto:dthompson2@worcester.edu][David Thompson]]

 #+BEGIN_SRC scheme
   (use-modules (chickadee)
                (chickadee math vector)
                (chickadee render sprite)
                (chickadee render texture)
                (system repl coop-server))

   (define sprite #f)
   (define repl #f)

   (define (load)
     (set! sprite (load-image "images/chickadee.png"))
     (set! repl (spawn-coop-repl-server)))

   (define (draw alpha)
     (draw-sprite sprite (vec2 256.0 176.0)))

   (define (update dt)
     (poll-coop-repl-server repl))

   (add-hook! load-hook load)
   (add-hook! update-hook update)
   (add-hook! draw-hook draw)
   (add-hook! quit-hook abort-game)

   (run-game)
 #+END_SRC
** Libpurple Bitlbee [[gnus:INBOX#20171004080427.13668-1-sleep_walker@gnu.org][Email from Tomáš Čech: {bug#28698} {PATCH} gnu: Enabl]] by [[mailto:sleep_walker@gnu.org][Tomáš Čech]]
** [2017-11-14 Tue 00:57] [[gnus:INBOX#87vak1l11m.fsf@nicolasgoaziou.fr][Email from Nicolas Goaziou: Re: {O} function for inserting]] by [[mailto:mail@nicolasgoaziou.fr][Nicolas Goaziou]]
** Replicant FOSDEM 2017

   - [[gnus:INBOX#1510570651.1176.2.camel@paulk.fr][Email from Paul Kocialkowski: {Replicant} FOSDEM Hardware En]] by
     [[mailto:contact@paulk.fr][Paul Kocialkowski]]
** [2017-11-18 Sat 21:40] [[gnus:nndoc%2Bephemeral:bug#27271#fake%2Bnone%2Bnndoc%2Bephemeral:bug#27271%2B1][Email from bug: Status: {PATCH 0/4} Catch collisions]] by [[mailto:27271@debbugs.gnu.org][bug]]
** Emacs with athena graphical toolkit

   [[gnus:INBOX#87po8gwjpk.fsf@gmail.com][Email from Mekeor Melire: Re: error running emacs instal]] by [[mailto:mekeor.melire@gmail.com][Mekeor Melire]]

   #+BEGIN_SRC scheme
     (define-public own-emacs
       (package
         (inherit emacs)
         (name "emacs")
         (synopsis "The extensible, customizable, self-documenting text editor
         with athena toolkit" )
         (build-system gnu-build-system)
         (inputs `(
                   ("inotify-tools" ,inotify-tools)
                   ("libxaw" ,libxaw)
                   ,@(alist-delete "gtk+" (package-inputs emacs))))
         (arguments `(
                      #:configure-flags '("--with-x-toolkit=athena")
                                        ,@(package-arguments emacs)))))
   #+END_SRC
** TODO GitHub highlight-escape-sequences
   [2017-11-19 Sun 01:10] [[gnus:INBOX#dgutov/highlight-escape-sequences/issues/6/345467554@github.com][Email from Dmitry Gutov: Re: {dgutov/highlight-escape-s]] by [[mailto:notifications@github.com][Dmitry Gutov]]
