#+TITLE: Linux video bloggers

- [[https://www.youtube.com/channel/UCJ65UG_WgFa_O_odbiBWZoA][celebrateubuntu]]

** [[https://www.youtube.com/channel/UC5vqzCb5kpIb1VzELAelO8w][Ubuntarium by Redroot]]

*** Description

 Всем большой привет! Мое имя Михаил (redroot), я большой фанат Linux и постоянно
 изучаю как эту интересную, надежду и дружелюбную систему можно использовать
 Дома, на работе и просто в любой ситуации, где Вам нужно использовать
 возможности ПК или вашего ноутбука. А также у меня небольшой фетиш на установку
 windows игр на Linux через wine, надеюсь это Вас не напугает)))

 Hello everyone! My name is Michael (redroot), I'm a big fan of Linux and is
 constantly studying how this interesting , hope and friendly system can be used
 at home , at work or just in any situation where you need to harness the power
 of your PC or your laptop . And also I have a small fetish for installing
 windows games on Linux through wine, I hope it does not scare you ) ) )

 П.С. Для тех кто готов поддержать канал материально: Twitch:
 https://www.twitchalerts.com/donate/ubuntarium Yandex деньги:
 http://yasobe.ru/na/ubuntarium#form_submit

*** [[https://vk.com/club125021013][VK]]

** [[https://www.youtube.com/channel/UCnbiPsM5jf3BW5Vnu_EYjow][# IT Navigator by Alexander Kordiy]]

*** Description
 Поддержать меня можно по этой ссылке, используя любую доступную(там есть Qiwi и
 тд.) на сервисе платежную систему: https://donutor.ru/id5639 Финансовая
 поддержка канала: WebMoney U606287170526 Z132716328251 R315186762528
 ЯндексДеньги
 https://money.yandex.ru/to/410013951249374?_openstat=template%3Bipulldown%3Btopupme
 410013951249374 Приват24 4731185606882212

** [[https://www.youtube.com/user/ANTGPRO][Gena ANTG - YouTube]]

***  Description

Канал посвящён видео-урокам по программированию. Канал создан для тех, кто хочет научиться программировать. Для тех, кто хочет более детально разобраться в компьютерном мире. Канал постоянно обновляется. Видео-уроки идут курсами. Каждый курс имеет свой уровень сложности. Обучение идёт с самых основ и очень доступным языком - разберётся и поймёт каждый!

Мы с Вами изучим основы программирования, поймём, что нужно знать, чтобы стать программистом. Разберём популярные ошибки у начинающих разработчиков. Научимся эффективно работать с информацией, научимся быстро и удобно её обрабатывать.

На канале запланированы курсы по следующим языкам: C(Си), C++, C#, Java, Python.
А также: HTML, CSS, JavaScript, MySQL, MongoDB, CodeIgniter, Yii, Django, Cake, Symphony, jQuery, Node.js, Grabbing / Parsing, Linux, Безопасность, Взлом, Ethical Hacking.

Подписывайтесь на канал, будет много интересного! 
Желаю Вам приятного обучения!

[[https://goo.gl/photos/999eiHeuf44qQCgSA]]

** [[https://www.youtube.com/channel/UC-feZzXf8igOvfmGCdAgl5w][Иван Глазков]]

** [[https://www.youtube.com/channel/UCeRY0LppLWdxWAymRANTb0g][Cloud Academy]]

** [[https://www.youtube.com/channel/UCrjKdwxaQMSV_NDywgKXVmw][Novaspirit Tech - YouTube]]
raspberry pi
